### ISSUE TITLE
TS0044

### ISSUE THREAD

**Issue by vazy86** [sprut/Hub#1003]
Address: B4E3F9FFFEBF5A86/0235<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 66</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_dku2cfsc</li><li>0005_ModelIdentifier: TS0044</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFFE_Custom: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li></ul></li></ul></li><li>Endpoint 3 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li></ul></li></ul></li><li>Endpoint 4 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jan 23 15:10:19 MSK 2022

Покупал на <a href="https://aliexpress.ru/item/1005002259012678.html?gatewayAdapt=glo2rus&spm=a2g2w.detail.1000023.9.abd35c85KwP9Jo&_ga=2.104752836.57264607.1642922172-1076831722.1639935367" rel="nofollow" data-for="at-external-link" style>Алиэкспрес</a>
Ник в Telegram: vazyton

В каталоге не нашел:

Версия Zigbee: ----
Режим спаривания, сброса: удержание кнопки сброса 7 секунд
Наличие нуля: выключатель на батарейках
Количество клавиш: 4 клавиши
Энергоизмеритель: ----
Статус после восстановления питания: ----

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zemismart-tuya-zigbee-besprovodnoy-pereklyuchatel-4ch
