### ISSUE TITLE
Zemismart ZW-EU-01 (zigbeeModel: LXN59-1S7LX1.0)

### ISSUE THREAD

**Issue by lenar-khairullin** [sprut/Hub#1006]
Одноклавишный выключатель с нулевой линией
(также со схожим исполнением есть без нулевой, с двумя и тремя кнопками)
Zemismart ZW-EU-01 (zigbeeModel: LXN59-1S7LX1.0)

в HA добавляют судя по github таким кодом

{
    zigbeeModel: ['LXN59-1S7LX1.0'],
    model: 'LXN59-1S7LX1.0',
    vendor: 'Nue / 3A',
    description: 'Smart light relay - 1 gang',
    extend: generic.switch,
    whiteLabel: [
        {vendor: 'Zemismart', model: 'ZW-EU-01'},
    ],
    meta: {configureKey: 1},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1) || device.getEndpoint(3);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
        await configureReporting.onOff(endpoint);
    },
    
    
    при попытке добавления в Sprut Hub. выдает такой лог
    Device loaded 'LXN59-1S7LX1.0', manufacturer '3A Smart Home DE', firmware '1', ZigBeeNode 086BD7FFFE5B84DE/543D, init=Нет шаблона, sleepy=false, loading=false, removed=false, Type=Router]

**Comment by lenar-khairullin** [comment]
Address: 086BD7FFFE5B84DE/543D<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 0</li><li>0004_ManufacturerName: 3A Smart Home DE</li><li>0005_ModelIdentifier: LXN59-1S7LX1.0</li><li>0006_DateCode: 20200519</li><li>0007_PowerSource: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4478</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jan 23 19:06:21 MSK 2022

**Comment by Batyushin** [comment]
ссылку на магазин прикрепите пожалуйста

**Comment by lenar-khairullin** [comment]
https://aliexpress.ru/item/4000460716855.html

**Comment by lenar-khairullin** [comment]
> ссылку на магазин прикрепите пожалуйста

https://aliexpress.ru/item/4000460716855.html

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zemismart-tuya-zigbee-1-gang-neutral
