### ISSUE TITLE
TuYa TS0503B. Контроллер RGB 12V (светодиодные ленты)

### ISSUE THREAD

**Issue by lenar-khairullin** [sprut/Hub#1008]
Контроллер Zigbee для светодиодных лент 12V.
выдает такой лог
Device loaded 'TS0503B', manufacturer '_TZ3210_trm3l2aw', firmware '65', ZigBeeNode A4C138A9B0110AC7/826C, init=Нет шаблона, sleepy=false, loading=false, removed=false, Type=Router]

куплен тут - https://aliexpress.ru/item/1005002928304090.html

**Comment by lenar-khairullin** [comment]
https://www.zigbee2mqtt.io/devices/TS0503B.html 
тут данные по нему

**Comment by lenar-khairullin** [comment]
Address: A4C138A9B0110AC7/826C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (COLOR_DIMMABLE_LIGHT)<ul><li>Input<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>EF00_ManufacturerSpecific<ul><li>0051_Custom: -50</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3210_trm3l2aw</li><li>0005_ModelIdentifier: TS0503B</li><li>0007_PowerSource: 1</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 148</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 191</li><li>000F_Options: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 65</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jan 23 17:59:48 MSK 2022

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/svetodiodnaya-neonovaya-rgb-rgbw-rgbcct-lenta-zigbee-3-0
