### ISSUE TITLE
Zemismart Tuya Zigbee. TS00001. Одноканальное реле

### ISSUE THREAD

**Issue by lenar-khairullin** [sprut/Hub#1009]
Реле одноканальное Zigbee
Zemismart Zigbee переключатель SmartThings Tuya Zigbee

лог:
Device loaded 'TS0001', manufacturer '_TZ3000_ih4awjkl', firmware '71', ZigBeeNode 60A423FFFEB15945/7160, init=Нет шаблона, sleepy=false, loading=false, removed=true, Type=Router]

куплен тут - https://aliexpress.ru/item/4001277870388.html

**Comment by lenar-khairullin** [comment]
Address: A4C13857CA533FAD/F7FF<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 13</li><li>0002_ZoneStatus: 1</li><li>0010_IASCIEAddress: 0000000000000000</li><li>0011_ZoneID: 255</li><li>0013_CurrentZoneSensitivityLevel: 1</li><li>F001_Custom: 1</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 70</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_mmtwjmaq</li><li>0005_ModelIdentifier: TS0202</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 70</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Sun Jan 23 22:05:13 MSK 2022

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zemismart-smart-light-relay-1-gang
