### ISSUE TITLE
Добавить поддержку NEO Coolcam Z-wave Door/Window Sensor

### ISSUE THREAD

**Issue by meowlab-net** [sprut/Hub#101]
https://szneo.com/en/products/show.php?id=188
https://www.neocoolcam.ru/datchik-otkrytiya/

![Screenshot 2020-05-02 at 11 29 59](https://user-images.githubusercontent.com/60046294/80859303-43c9af80-8c68-11ea-8708-ebd58d84cca9.png)

![Screenshot 2020-05-02 at 11 31 03](https://user-images.githubusercontent.com/60046294/80859317-6c51a980-8c68-11ea-9611-c20e3a55544f.png)

**Comment by MakeSimpleOrg** [comment]
1.6.4
