### ISSUE TITLE
Zemismart Tuya TS0202. Датчик движения

### ISSUE THREAD

**Issue by lenar-khairullin** [sprut/Hub#1014]
Датчик движения

лог.

Device loaded 'TS0202', manufacturer '_TZ3000_mmtwjmaq', firmware '70', ZigBeeNode A4C13857CA533FAD/F7FF, init=Нет шаблона, sleepy=false, loading=false, removed=false, Type=End Device]
--

покупал тут - https://aliexpress.ru/item/1005001921075098.html

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/datchik-dvizheniya-zemismart-tuya-zigbee-3-0
