### ISSUE TITLE
Добавить поддержку NEO Coolcam Z-Wave Motion Sensor(PIR)

### ISSUE THREAD

**Issue by meowlab-net** [sprut/Hub#102]
Бюджетный датчик движения. Стабильно работает.

https://szneo.com/en/products/show.php?id=190
https://www.neocoolcam.ru/datchik-dvizheniya/

![Screenshot 2020-05-02 at 11 54 44](https://user-images.githubusercontent.com/60046294/80859743-b9834a80-8c6b-11ea-8cc8-15a9b2b61682.png)

Обнаружено движение
![Screenshot 2020-05-02 at 11 55 42](https://user-images.githubusercontent.com/60046294/80859762-dc156380-8c6b-11ea-97e8-641eeb1f8824.png)

Отмена
![Screenshot 2020-05-02 at 11 56 16](https://user-images.githubusercontent.com/60046294/80859775-efc0ca00-8c6b-11ea-9af8-15a73e49de52.png)

**Comment by MakeSimpleOrg** [comment]
1.6.4
