### ISSUE TITLE
TS0044 новый SH vendor

### ISSUE THREAD

**Issue by nicktambov** [sprut/Hub#1021]
Устройство https://sprut.ai/catalog/item/loratap-tuya-zigbee-30-besprovodnoj-4-knopocnyj-pult засветилось с новым manufacturerId
Я поправил шаблон, протестировал все работает. шаблон прикладываю, упакован в zip, имя файла оставил старое.
[TS0044.zip](https://github.com/sprut/Hub/files/7933104/TS0044.zip)
.

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/loratap-tuya-zigbee-30-besprovodnoj-4-knopocnyj-pult

**Comment by Batyushin** [comment]
информацию об устройстве прикрепи.

**Comment by nicktambov** [comment]
Structure
Endpoint 1 (ON_OFF_SWITCH)
Input
0000_Basic
0001_ApplicationVersion: 65
0003_HWVersion: 1
0004_ManufacturerName: _TZ3000_ee8nrt2l
0005_ModelIdentifier: TS0044
0007_PowerSource: 3
0001_PowerConfiguration
0021_BatteryPercentageRemaining:
0006_OnOff
Output
0006_OnOff
0019_OtaUpgrade
000A_Time
Endpoint 2 (ON_OFF_SWITCH)
Input
E000_ManufacturerSpecific
0001_PowerConfiguration
0006_OnOff
Output
0006_OnOff
Endpoint 3 (ON_OFF_SWITCH)
Input
E000_ManufacturerSpecific
0001_PowerConfiguration
0006_OnOff
Output
0006_OnOff
Endpoint 4 (ON_OFF_SWITCH)
Input
E000_ManufacturerSpecific
0001_PowerConfiguration
0006_OnOff
Output
0006_OnOff
Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags | 0
-- | --
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 66
Incoming Transfer Size | 66
Logical Type | End Device
Mac Capabilities | [REDUCED_FUNCTION_DEVICE]
Manufacturer Code | 4417
Out Going Transfer Size | 66
Stack Compliance | 21


Power Descriptor
Current Power Mode | RECEIVER_ON_STIMULATED
-- | --
Available Power Sources | [RECHARGABLE_BATTERY]
Current Power Source | RECHARGABLE_BATTERY
Power Level | MEDIUM
