### ISSUE TITLE
Добавить поддержку ТЕРМОСТАТ-АКТУАТОР DIT-102 ZWawe

### ISSUE THREAD

**Issue by DomikMaksa** [sprut/Hub#103]
https://www.defaro.ru/index.php/support/instructions/68-dit101-dit102

**Comment by DomikMaksa** [comment]
![Снимок экрана 2020-05-05 в 17 13 51](https://user-images.githubusercontent.com/48162267/81076202-0d07c980-8ef4-11ea-853e-55719ba3e2d3.png)

**Comment by dragaleff** [comment]
Доброго вечера, дяденьки. Скажите, есть ли перспектива?

**Comment by MakeSimpleOrg** [comment]
Добавлен
