### ISSUE TITLE
TS0041

### ISSUE THREAD

**Issue by drogdorg** [sprut/Hub#1030]
Address: 60A423FFFE6CBDFA/DDCE<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 65</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_tk3s5tyg</li><li>0005_ModelIdentifier: TS0041</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Custom: �d�(ws�(s��(���(
��(���(</li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 1</li><li>FFFE_Custom: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 174</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jan 28 09:44:02 UTC 2022

**Comment by drogdorg** [comment]
покупался тут: https://aliexpress.ru/item/4001230762751.html?_ga=2.210035349.1404524240.1643362153-1833545612.1642062235&_gac=1.23829192.1642769016.CjwKCAiA0KmPBhBqEiwAJqKK407iLvcRB0k_ylBI54YIQNwHOi2ev40aQqWvubWpk3ohRWyMkYgK_hoC-ygQAvD_BwE&item_id=4001230762751&sku_id=10000015383495491&spm=a2g39.orderlist.0.0.66934aa63OB3Gu

**Comment by drogdorg** [comment]
Версия Zigbee = 3
Режим спаривания, сброса = открываем, держим кнпоку 5 сек
Наличие нуля
Количество клавиш = 1
Энергоизмеритель
Статус после восстановления питания

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/nastennyy-vyklyuchatel-neutral-1gang
