### ISSUE TITLE
TS0202

### ISSUE THREAD

**Issue by AndylgTom** [sprut/Hub#1032]
Address: 00124B00091860C8/C20F<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0500_IasZone<ul><li>0002_ZoneStatus: 1</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 33</li><li>0003_HWVersion: 0</li><li>0004_ManufacturerName: _TYZB01_dl7cejts</li><li>0005_ModelIdentifier: TS0202</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0003_Identify<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0500_IasZone<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Sat Jan 29 06:47:05 GMT-07:00 2022

Покупал https://aliexpress.ru/item/1005002346449643.html
Датчик движения ZM-35ZH-Q
Батарейка CR2450 (1,5 лет, 10 раз в день)
В каталоге нет
[logs.zip](https://github.com/sprut/Hub/files/7963837/logs.zip)

Телеграмм @Andylg

**Comment by AndyLG** [comment]
ecac9＿ㄍζの

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zigbee-pir-human-motion-sensor

**Comment by AndylgTom** [comment]
Что-то не то. Теперь даже информацию он всю получить не может c датчика, и пишет unknown и данные только такие показывает:

Address: 00124B00091860C8/C2E7<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0500_IasZone<ul><li>0002_ZoneStatus: 1</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Wed Apr 06 14:53:42 NOVT 2022

**лог:**
00:50:05	ZigBee: Поиск завершён	
00:50:05	00124B00091860C8/C2E7: Изучение возможностей, Нет ответа	
00:50:04	Transaction terminated (Device not respond): 0005_ActiveEndpointsRequest [0000/0 -> C2E7/0, TID=8E, nwkAddrOfInterest=C2E7], sleepy	
00:49:34	00124B00091860C8/C2E7: Энергопотребление	
00:49:32	00124B00091860C8/C2E7: Базовая информация	
00:49:31	EzspZigbeeKeyEstablishmentHandler [networkId=0, partner=00124B00091860C8, status=EMBER_TC_RESPONDED_TO_KEY_REQUEST]	
00:49:30	00124B00091860C8/C2E7: Опрос	
00:49:30	Join node: ZigBeeNode 00124B00091860C8/C2E7, init=Базовая информация, online=true, sleepy=true, loading=true, removed=false, ota=Неизвестно, Type=End Device]	
00:49:28	00124B00091860C8/C2E7, online -> true	
00:49:28	00124B00091860C8/C2E7: Node UNSECURED_JOIN	
00:49:28	EzspTrustCenterJoinHandler [networkId=0, newNodeId=C2E7, newNodeEui64=00124B00091860C8, status=EMBER_STANDARD_SECURITY_UNSECURED_JOIN, policyDecision=EMBER_USE_PRECONFIGURED_KEY, parentOfNewNodeId=0000]	
00:49:28	EzspChildJoinHandler [networkId=0, index=3, joining=true, childId=C2E7, childEui64=00124B00091860C8, childType=EMBER_SLEEPY_END_DEVICE]	
00:49:15	ZigBee: Поиск запущен на 60 секунд	
00:49:14	ZigBee: Поиск завершён

**Comment by AndyLG** [comment]
ecac9＿ㄍζの
