### ISSUE TITLE
Умная розетка Tuya Zigbee TS011F_TZ3000_gjnozsaz

### ISSUE THREAD

**Issue by pmitry** [sprut/Hub#1041]
Address: A4C138E9D5E9BB79/2A01<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_PLUG_IN_UNIT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul><li>D001_Custom: ByteArray [value=00 06]</li><li>D002_Custom: ByteArray [value=00 0A]</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 68</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_gjnozsaz</li><li>0005_ModelIdentifier: TS011F</li><li>0007_PowerSource: 1</li></ul></li><li>E001_ManufacturerSpecific<ul><li>D000_Custom: 0</li><li>D001_Custom: 0</li><li>D002_Custom: 0</li><li>D003_Custom: 0</li><li>D004_Custom: 0</li><li>D005_Custom: 0</li><li>D010_Custom: 2</li><li>D030_Custom: 0</li></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 228</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0B04_ElectricalMeasurement<ul><li>0505_RMSVoltage: 226</li><li>0508_RMSCurrent: 96</li><li>050B_ActivePower: 20</li></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>5000_Custom: 1</li><li>8000_MultipleClick: false</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 2</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>0C4314FFFE9AF7D3</td><td>9539</td><td>Router</td><td>false</td><td>Parent</td><td>63</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFEFF4BA7</td><td>6AA8</td><td>Router</td><td>false</td><td>Sibling</td><td>51</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFEFF3D0C</td><td>BB5A</td><td>Router</td><td>false</td><td>Sibling</td><td>51</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFEFF16DD</td><td>2C97</td><td>Router</td><td>false</td><td>Sibling</td><td>60</td><td>UNKNOWN</td><td>1</td></tr><tr><td>00158D00023EF0AA</td><td>E29E</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>2</td></tr><tr><td>00124B0022ED4F10</td><td>F4A6</td><td>Router</td><td>false</td><td>Sibling</td><td>69</td><td>UNKNOWN</td><td>2</td></tr><tr><td>00158D0002FBF42B</td><td>BA8E</td><td>Router</td><td>false</td><td>Sibling</td><td>88</td><td>UNKNOWN</td><td>2</td></tr><tr><td>00124B0022ED4F14</td><td>BEEA</td><td>Router</td><td>false</td><td>Sibling</td><td>69</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFEFF14B7</td><td>11F5</td><td>Router</td><td>false</td><td>Sibling</td><td>115</td><td>UNKNOWN</td><td>1</td></tr><tr><td>588E81FFFEFED23A</td><td>EDEC</td><td>Router</td><td>false</td><td>Sibling</td><td>106</td><td>UNKNOWN</td><td>1</td></tr><tr><td>04CF8CDF3C7B2123</td><td>0E1C</td><td>Router</td><td>false</td><td>Sibling</td><td>60</td><td>UNKNOWN</td><td>1</td></tr><tr><td>00158D0006722CBC</td><td>0C76</td><td>Router</td><td>false</td><td>Sibling</td><td>24</td><td>UNKNOWN</td><td>2</td></tr><tr><td>54EF4410000EB2CC</td><td>9FA9</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>1</td></tr><tr><td>0C4314FFFE60A635</td><td>474F</td><td>Router</td><td>false</td><td>Sibling</td><td>127</td><td>UNKNOWN</td><td>1</td></tr><tr><td>0C4314FFFE9AFCF1</td><td>6161</td><td>Router</td><td>false</td><td>Sibling</td><td>103</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFEFF502C</td><td>C320</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFE416649</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>88</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D00028AE3E8</td><td>36E5</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>2</td></tr><tr><td>00158D0006794EDF</td><td>03DE</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>2</td></tr><tr><td>00158D000689A260</td><td>FDA6</td><td>Router</td><td>false</td><td>Sibling</td><td>42</td><td>UNKNOWN</td><td>2</td></tr><tr><td>04CF8CDF3C7B2238</td><td>2443</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>1</td></tr><tr><td>842E14FFFE00C87A</td><td>43E1</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>1</td></tr><tr><td>00158D000689B117</td><td>2946</td><td>Router</td><td>false</td><td>Sibling</td><td>15</td><td>UNKNOWN</td><td>2</td></tr><tr><td>00124B0022EA2A96</td><td>9E6D</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>1</td></tr><tr><td>0C4314FFFE9AF93F</td><td>AD67</td><td>Router</td><td>false</td><td>Sibling</td><td>12</td><td>UNKNOWN</td><td>1</td></tr><tr><td>A4C138420BA1857A</td><td>90AA</td><td>Router</td><td>false</td><td>Sibling</td><td>157</td><td>UNKNOWN</td><td>2</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jan 31 09:43:54 IST 2022
Розетку покупал по ссылке https://aliexpress.ru/item/1005003658767835.html?spm=a2g39.orderlist.0.0.12fd4aa6guuJwX&_ga=2.202534354.218589796.1643448686-1362241583.1634713439&_gac=1.23442888.1643065227.Cj0KCQiAubmPBhCyARIsAJWNpiPBhnJPr43jMNPW8mv0JXApGS9iDvuYFfWQbwGAiqrQiKA-n9glnvsaAtyPEALw_wcB  Для спаривания зажимаем кнопку на 5-7 секунд пока индикатор не начнёт мигать. Для подключения к спрт хаб использовал кастомный шаблон. Есть энергомониторинг. На данной прошивке сохранение состояния после  пропажи питания работает не корректно, если выбрать запоминать состояние, то после восстановления питания включается на мгновение и выключается(перед отключением была включена. По информации от Alex Kvazis есть новая прошивка в которой запоминание состояния работает корректно. Но хаба туевского нет поэтому проверить не могу пока. Закажу хаб, тогда дополню информацию. 
[TS011F_TZ3000_gjnozsaz.zip](https://github.com/sprut/Hub/files/7969080/TS011F_TZ3000_gjnozsaz.zip)

**Comment by pmitry** [comment]
Забыл написать: есть управление индикатором, индикация включения, индикация выключения и отключена.

**Comment by andreypopov** [comment]
+1 нужен шаблон на эту розетку

https://www.youtube.com/watch?v=jG9SpJBwYFM&t=609s

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/umnaya-rozetka-tuya-zigbee-16a-3800-vt-evropa-franc
