### ISSUE TITLE
Редактирование имени сервиса на мобильном устройстве.

### ISSUE THREAD

**Issue by top4ek** [sprut/Hub#1048]
** Подробное описание ошибки **
Невозможно отредактировать имя сервиса на мобильном устройстве: https://user-images.githubusercontent.com/16016/151843728-dfffe551-5b02-4800-9bd7-633f678b0724.mp4

** Как воспроизвести ? **
1. Открыть редактирование сервиса
2. Перейти на вкладку настройки
3. Нажать на текстбокс с именем

** Ожидаемое поведение **
Успешный набор имени в текстбоксе на стандартной клавиатуре системы.

** Пожалуйста, заполните следующую информацию: **
  - Версия: CE 6567

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
