### ISSUE TITLE
TS011F

### ISSUE THREAD

**Issue by meles-meles** [sprut/Hub#1053]
покупал тут https://aliexpress.ru/item/1005003489089894.html
подробное описание тут 
https://www.youtube.com/watch?v=Zkoi1baLvRM
умная розетка Haozee Zigbee в круглый подрозетник с энергомониторингом.
родного хаба нет.
статус после восстановления питания не помнит.
рабочая таемплата:
[TS011F_outlet_TZ3000_w0qqde0g.zip](https://github.com/sprut/Hub/files/7973775/TS011F_outlet_TZ3000_w0qqde0g.zip)

Address: A4C138616C5FC584/BAAE<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_PLUG_IN_UNIT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul><li>D001_Custom: ByteArray [value=00 06]</li><li>D002_Custom: ByteArray [value=00 0A]</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 68</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_w0qqde0g</li><li>0005_ModelIdentifier: TS011F</li><li>0007_PowerSource: 1</li></ul></li><li>E001_ManufacturerSpecific<ul><li>D000_Custom: 0</li><li>D001_Custom: 0</li><li>D002_Custom: 0</li><li>D003_Custom: 0</li><li>D004_Custom: 0</li><li>D005_Custom: 0</li><li>D010_Custom: 2</li><li>D030_Custom: 0</li></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 128</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0B04_ElectricalMeasurement<ul><li>0505_RMSVoltage: 241</li><li>0508_RMSCurrent: 51</li><li>050B_ActivePower: 7</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>5000_Custom: 1</li><li>8000_MultipleClick: false</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 2</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 68</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>[4] Sprut zigbee Новая комната (1)</td><td>0006_OnOff</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFEAEA892</td><td>F0EB</td><td>Router</td><td>false</td><td>Parent</td><td>91</td><td>UNKNOWN</td><td>1</td></tr><tr><td>84FD27FFFE864D1D</td><td>D4E3</td><td>Router</td><td>false</td><td>Sibling</td><td>63</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFE41559F</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>48</td><td>UNKNOWN</td><td>0</td></tr><tr><td>84FD27FFFE830A66</td><td>54EA</td><td>Router</td><td>false</td><td>Sibling</td><td>39</td><td>UNKNOWN</td><td>1</td></tr><tr><td>CC86ECFFFE9336F4</td><td>220B</td><td>Router</td><td>false</td><td>Sibling</td><td>0</td><td>UNKNOWN</td><td>1</td></tr><tr><td>A4C138A5C7CC7F9E</td><td>8772</td><td>Router</td><td>false</td><td>Sibling</td><td>0</td><td>UNKNOWN</td><td>2</td></tr><tr><td>84FD27FFFE5F02F4</td><td>B060</td><td>Router</td><td>false</td><td>Sibling</td><td>21</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFED2F487</td><td>FEA8</td><td>Router</td><td>false</td><td>Sibling</td><td>15</td><td>UNKNOWN</td><td>1</td></tr><tr><td>0C4314FFFEBB6FB0</td><td>D787</td><td>Router</td><td>false</td><td>Sibling</td><td>15</td><td>UNKNOWN</td><td>1</td></tr><tr><td>0C4314FFFEBB6F6F</td><td>6C4B</td><td>Router</td><td>false</td><td>Sibling</td><td>15</td><td>UNKNOWN</td><td>1</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jan 31 22:10:31 MSK 2022

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/umnaya-rozetka-tuya-zigbee-16a-3800-vt-evropa-franc
