### ISSUE TITLE
GL-SD-001

### ISSUE THREAD

**Issue by meles-meles** [sprut/Hub#1054]
zigbee trial ac dimmer.
тиристорный диммер в подрозетник.
на 220в разрешенная мощность: led=200W, галогенки=400W, лампочки через трансформаторы=200W.
покупал тут https://www.aliexpress.com/item/1005002120424028.html
Версия Zigbee 3
Режим спаривания, сброса: 5 раз нажать на копку reset или 5 раз выключить и включить димер (убрать и подать на него напряжение)
Наличие нуля: нужен
Количество каналов: 1
Энергоизмеритель: нет
рабочая темплата: [GL-SD-001.zip](https://github.com/sprut/Hub/files/7973986/GL-SD-001.zip)

Address: CC86ECFFFEBFB5AF/E3DF<br><br><b>Structure</b><br><ul><li>Endpoint 1 (DIMMABLE_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-SD-001</li><li>0007_PowerSource: 0</li><li>4000_SWBuildID: 10451201</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 200</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4687</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jan 31 23:17:03 MSK 2022

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zigbee-triac-ac-dimmer
