### ISSUE TITLE
ZB-CL01

### ISSUE THREAD

**Issue by warwar-spb** [sprut/Hub#1056]
Address: 00124B00226D87CF/1D7C<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 13</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLight</li><li>0005_ModelIdentifier: ZB-CL01</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 1.0.13</li></ul></li><li>0300_ColorControl<ul><li>0003_CurrentX: 29406</li><li>0004_CurrentY: 12058</li><li>0007_ColorTemperature: 252</li><li>400B_ColorTemperatureMin: 153</li><li>400C_ColorTemperatureMax: 370</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 216</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><table border=1 width=100%><tr><th>NWK</th><th>IEEE</th><th>Name</th><th>Type</th></tr><tr><td>8B29</td><td>00158D0004071E97</td><td>Выключатель</td><td>Router</td></tr></table><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415656</td><td>0000</td><td>Coordinator</td><td>true</td><td>Parent</td><td>48</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D0004071E97</td><td>8B29</td><td>End Device</td><td>true</td><td>Child</td><td>170</td><td>UNKNOWN</td><td>2</td></tr><tr><td>00158D0002911AAA</td><td>BC28</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>DISCOVERY_FAILED</td><td>BC28</td><td>FFFE</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Feb 01 00:01:49 MSK 2022

@AlekseyOlenyuk

https://aliexpress.ru/item/1005002029756634.html?_ga=2.95438748.1021285197.1643702013-1991695593.1641234799&sku_id=12000018467587511&spm=a2g39.orderlist.0.0.7b684aa6b6bTzK

Zigbee 3.0

5-ти кратное включение/отключение

Точечный светильник

Запоминает состояние при отключении питания.

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/tochechnyy-svetilnik-rgbcct
