### ISSUE TITLE
Блок WBM1w2

### ISSUE THREAD

**Issue by teleexpert** [sprut/Hub#107]
Блок контроля датчиков температуры не добавился в СХ
https://wirenboard.com/ru/product/WB-M1W2/

**Comment by sprut666666** [comment]
Не описан какой контроллер используется и если мктт не указано имя

**Comment by teleexpert** [comment]
Контролер WB 6, подключение по модбас

**Comment by teleexpert** [comment]
Добавите в новой версии?

**Comment by teleexpert** [comment]
Извините что дергаю, а когда сможете добавить WBM1W2 ?

**Comment by sprut666666** [comment]
в след версии будет, в ближайшее время будет опубликована

**Comment by teleexpert** [comment]
Вот эта ветка

**Comment by Stronmax** [comment]
Олег приветствую, очень нужен этот модуль
