### ISSUE TITLE
SML002

### ISSUE THREAD

**Issue by nKarlson** [sprut/Hub#1079]
Address: 0017880106464F13/DE84<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: SML002</li><li>0006_DateCode: 20180828</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 6.1.0.25261</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (OCCUPANCY_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: SML002</li><li>0006_DateCode: 20180828</li><li>0007_PowerSource: 3</li><li>0032_CustomPhilips (100B): false</li><li>0033_CustomPhilips (100B): false</li></ul></li><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 18744</li><li>0001_MinMeasuredValue: 1</li><li>0002_MaxMeasuredValue: 65534</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 31</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2489</li><li>0001_MinMeasuredValue: -27315</li><li>0002_MaxMeasuredValue: 32767</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0406_OccupancySensing<ul><li>0000_Occupancy: 1</li><li>0001_OccupancySensorType: 0</li><li>0010_PIROccupiedToUnoccupiedDelay: 0</li><li>0030_MotionDetectionSensitivity (100B): 2</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 1107321517</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4107</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>89</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>63</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>63</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, MAINS, RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Feb 05 18:33:46 MSK 2022

Режим спаривания, сброса: Удерживать на задней стороне датчика кнопку "setup", пока датчик не загорится красным.

Покупался тут: https://www.apple.com/shop/product/HNRK2ZM/A/philips-hue-outdoor-motion-sensor

В каталоге: https://sprut.ai/catalog/item/philips-hue-outdoor-sensor

Телеграм: @nktndrr

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/philips-hue-outdoor-sensor
