### ISSUE TITLE
Не работает по mqtt/modbus WB-MRGBW-D Firmware 3

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#1087]
** Подробное описание ошибки **
Хаб не поддерживает новую прошивку диммера wb-mrgbw-d версии 3, особенно разных режимов работы 4W / 1W + RGB и т.д. 

В которой в целом решены все основные проблемы устройства и в WB он работает как надо + появилось много регулировок и настроек 

https://wirenboard.com/wiki/WB-MRGBW-D_Modbus_LED_Dimmer

**Comment by Alxprv** [comment]
@sprut666666 не положить custom template в SprutHub (BOX) Covid Edition

**Comment by andreypopov** [comment]
+1 , ну когда уже?

**Comment by sfiloniuk** [comment]
+1 обещали темплейт после выхода стабильной прошивки

**Comment by alexey-gamov** [comment]
[скачать шаблон для 3й прошивки](https://github.com/alexey-gamov/wirenboard/blob/main/templates/sprut-mqtt/wb-mrgbw-d-fw3.json)
