### ISSUE TITLE
SH 1.6 не добавляет  Модуль WBIO-DO-R10R-4 по ModBus 

### ISSUE THREAD

**Issue by jeka8877** [sprut/Hub#109]
SH 1.6, 

Модуль ввода-вывода WBIO-DO-R10R-4 подключен по ModBus через Преобразователь интерфейсов WB-MIO (ID 205),
при добавлении новых устройств модуль обнаруживается, но не  добавляется.

![image](https://user-images.githubusercontent.com/54616619/85524714-13bbde80-b611-11ea-82f0-abc44d667361.png)

**Comment by sprut666666** [comment]
1.6.5
