### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by Simion1982** [sprut/Hub#1097]
Address: 00124B0023B7CA07/84A8<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><br><b>Power Descriptor</b><br><br><br><br>Last update: Thu Feb 10 14:29:24 CET 2022
Telegram Senea192@
Покупал:
https://a.aliexpress.com/_u6Ie3a

**Comment by sprut666666** [comment]
нужно пересоздать запрос через новый веб + на последней версии хаба
