### ISSUE TITLE
Обновление из UI

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#11]
Очевидная штука, хотелось бы иметь возможность обновлять СХ из UI. 
Первое время большое количество обновлений/фиксов выходит, можно не уследить.

![2019-07-05_10-28-35](https://user-images.githubusercontent.com/1624839/60705391-b31f2780-9f0f-11e9-9248-c2bd77653c07.png)

Кнопку обновить можно вынести в "настройки"

**Comment by mazaxaka** [comment]
+1
