### ISSUE TITLE
Беспроводной выключатель Aqara неправильно отрабатывает нажатие

### ISSUE THREAD

**Issue by peefoo** [sprut/Hub#110]
С версии 1,5 и по 1.6 появился баг. Опишу что делал.

На чистый 1.6 добавляю устройство - кнопка aqara  WXKG02LM.

В триггеры прописываю, чтобы переключала реле по одиночному нажатию. Однако, переключение происходит, только если предыдущим состоянием было двойное или долгое нажатие. [https://drive.google.com/file/d/1CMUDKi9SUd2S9blUZY36mlJ7COQukuaD/view](url)

**Comment by earlywaff** [comment]
Ап! Есть такая проблема!

**Comment by sprut666666** [comment]
1.6.1
