### ISSUE TITLE
Добавить поддержку ZigBee On Off Controller

### ISSUE THREAD

**Issue by SitkoAleksandr** [sprut/Hub#111]
Прошу добавить темплейт для ZigBee On Off Controller [https://v2.sprut.ai/catalog/item/noname-zigbee-on-off-controller](https://v2.sprut.ai/catalog/item/noname-zigbee-on-off-controller) в SprutHub

в SH реле определяется как:
**manufacturerId:	eWeLink
modelId:	SA-003-Zigbee**

имя в телеге: @Sitko_Aleksandr

**Comment by Kopoklok** [comment]
Присоединяюсь, прошу добавить поддержку данного реле, отображается аналогично.

**Comment by sprut666666** [comment]
1.6.2
