### ISSUE TITLE
Добавить поддержку AQARA Relay

### ISSUE THREAD

**Issue by KZuev** [sprut/Hub#112]
Прошу добавить темплейт в SprutHub для **AQARA Relay** [https://v2.sprut.ai/catalog/item/akara-relay](https://v2.sprut.ai/catalog/item/akara-relay)
В SH пока не добавлял, т.к. они используется для света. При необходимости, могу попробовать добавить в SH.

Telegram: @KirillZuev

**Comment by sprut666666** [comment]
1.6.2
