### ISSUE TITLE
Несколько homekit шлюзов с возможностью ограничения списка девайсов для экспорта

### ISSUE THREAD

**Issue by Tri0L** [sprut/Hub#1129]
## Ситуация
Есть умный дом. В нем есть куча девайсов, начиная от лампочек в прихожей и заканчивая газовыми котлами, управлением водоснабжением и прочие mission critical устройства.

Есть семья где есть родители, отдающие себе отчет о том, чем они управляют и есть дети.
У детей есть iPhone и макбук и им очень хочется управлять своим по праву куском умного дома. 
Например освещением в своей комнате, шторами там же и тп. Но дети маленькие и не способны в полной мере понять всю сложность и серьезность последствий неправильного управления критичными элементами инфраструктуры. Выключить газовый котел или перекрыть воду, для них такое же нажатие кнопки как и включить/выключить свет.
Аналогичная история с пожилыми родственниками, которым нужна условная одна кнопка "сделать что-то хорошо". И они не в силах разобраться во всем функционале homekit.

## Предложение
Сделать возможность создавать несколько homekit контроллеров с возможностью экспорта не всех девайсов.
Как именно, по комнате, по названию или вообще отмечать галочками избранные устройства, это уже детали реализации.
Важна просто возможность сделать так, чтобы человек видел у себя только ограниченный список девайсов когда в то же время другой человек видит все или другой список доступных ему девайсов.

**Comment by SmartHaven** [comment]
Согласны, и это давно включено в планы. Будет несколько мостов, и можно будет указать, какие устройства в каких мостах видны. Касается не только хомкита, но и алису и прочих.
