### ISSUE TITLE
lumi.sensor_smoke

### ISSUE THREAD

**Issue by KZuev** [sprut/Hub#113]
Прошу добавить темплейт в SprutHub для Xiaomi mijia Honeywell Smoke sensor [https://v2.sprut.ai/catalog/item/honeywell-smoke-sensor](https://v2.sprut.ai/catalog/item/honeywell-smoke-sensor)
В SH определяется как:
manufacturerId: LUMI
modelId: lumi.sensor_smoke

Telegram: kirillzuev

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by KZuev** [comment]
Address: 00158D00028F62BC/4DE0<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 3000-0001</li><li>0001_ApplicationVersion: 2</li><li>FF01_Custom: {1=3075, 3=34, 4=424, 100=1, 5=101, 6=11, 150=0, 8=4100, 10=0}</li><li>0003_HwVersion: 16</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.sensor_smoke</li><li>0007_PowerSource: 3</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0010_IasCieAddress: 0000000000000000</li><li>0001_ZoneType: 40</li><li>0011_ZoneId: 255</li><li>0002_ZoneStatus: 0</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0012_MultistateInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>004A_NumberOfStates: 6</li><li>006F_StatusFlags: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0.0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sun Jul 05 18:54:44 MSK 2020


[Sun Jul 05 19:01:53 MSK 2020.pcap.zip](https://github.com/sprut/Hub/files/4875213/Sun.Jul.05.19.01.53.MSK.2020.pcap.zip)

1. Добавление устройства
2. Нажатие на кнопку на устройстве
3. Срабатывание на дым
4. Выключение сигнала кнопкой
Настройки
1. Место установки Зона без дыма
2. Место установки Зона со слабым задымлением
3. Место установки Зона с умеренным задымлением
4. Самопроверка устройства (Раздается ли звуковой сигнал - Нет)
5. Самопроверка устройства (Раздается ли звуковой сигнал - Да)
6. Звуковой сигнал при соединении (Шлюз соединен для отправки звукового сигнала при обнаружении дыма) Выкл
7. Звуковой сигнал при соединении (Шлюз соединен для отправки звукового сигнала при обнаружении дыма) Вкл

**Comment by kirillzuev** [comment]
Ребзя, я всё понимаю, умный дом, все дела, но давайте настройте свои учетки так, чтобы мне не приходили уведомления. Спасибо!

**Comment by sprut666666** [comment]
> Ребзя, я всё понимаю, умный дом, все дела, но давайте настройте свои учетки так, чтобы мне не приходили уведомления. Спасибо!

Думаю именно вам стоит настроить уведомления, которые вас интереуют

**Comment by kirillzuev** [comment]
Ну пусть так. Тогда прошу меня хотя бы не упоминать :)

> You’re receiving notifications because you were mentioned.

**Comment by sprut666666** [comment]
1.6.3
