### ISSUE TITLE
ZigBee - GLEDOPTO - GL-MC-001P

### ISSUE THREAD

**Issue by xxxMACTEPxxx** [sprut/Hub#1134]
Address: 680AE2FFFEC0CBB3/A80A<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11 (EXTENDED_COLOR_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 0</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 3</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-MC-001P</li><li>0006_DateCode: 20210226</li><li>0007_PowerSource: 0</li><li>0008_GenericDeviceClass: 255</li><li>0009_GenericDeviceType: 255</li><li>4000_SWBuildID: V_1_7_H2</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 0</li><li>0001_CurrentSaturation: 0</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 17623</li><li>0004_CurrentY: 43739</li><li>0007_ColorTemperature: 250</li><li>0008_ColorMode: 1</li><li>4000_EnhancedCurrentHue: 0</li><li>4001_EnhancedColorMode: 1</li><li>4002_ColorLoopActive: 0</li><li>4003_ColorLoopDirection: 1</li><li>4004_ColorLoopTime: 25</li><li>4005_ColorLoopStartHue: 8960</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 255</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>000F_Options: 0</li><li>4000_StartUpCurrentLevel: 51</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 10</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4687</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Feb 23 22:52:59 MSK 2022

Telegram: [@Sergius_dm](https://t.me/Sergius_dm)

Покупал: https://www.aliexpress.ru/item/1005001431435292.html?spm=a2g39.orderlist.0.0.57fa4aa62onLXv&_ga=2.118886793.1812980611.1645555883-1385788864.1578995109&_gac=1.254622202.1645646478.Cj0KCQiA09eQBhCxARIsAAYRiyma1OUMnBwNHNCxEKlhCx1NfjZDK9VHp223l-agY-y66nNAEzunQywaAmXUEALw_wcB

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/gledopto-zigbee-usb-mini-led-controller-rgb-cct
