### ISSUE TITLE
SH 1.6 не видит Sprut Stick 

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#114]
Не на WИ, не на Raspberry SH не опередят стик.

** Как воспроизвести ? **
На WB:
1. Создаем новое устройство зигби
2. В настройках указываем спрут стик и USB0
3. Ставим галочку
4. в логах  Available Ports: ttymxc6,ttymxc0,ttymxc1,ttymxc5,ttymxc3,ttyUSB0
5. все больше ничего не происходит, стик не появляется
На Raspberry:
1. Создаем новое устройство зигби
2. В настройках указываем спрут стик и USB0
3. Ставим галочку
4. в логах  Available Ports: ttyUSB0,ttyAMA0
5. все больше ничего не происходит, стик не появляется
--

** Ожидаемое поведение **
Ожидаю что должен появится спрут стик.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия: SH 1.6

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by meowlab-net** [comment]
Аналогичная проблема. Также пробовал менять библиотеку с  JSerial на PureJavaComm.

**Comment by droni4** [comment]
решено
