### ISSUE TITLE
Отсутствует значение виртуального датчика (0.0)

### ISSUE THREAD

**Issue by KZuev** [sprut/Hub#115]
**Подробное описание ошибки**
После создания виртуального датчика температуры или влажности и связывания его с физическим, его значение не обновляется до момента обновления значений у физического датчика.

**Как воспроизвести ?**
1. Создать виртуальный датчик
2. Связать его с физическим
3. Значение виртуального датчика 0.0

**Ожидаемое поведение**
Получение предыдущих значений физического датчика, без ожидания их обновления.

**Скриншоты/ Логи**
<img width="362" alt="Снимок экрана 2020-06-24 в 16 52 18" src="https://user-images.githubusercontent.com/2257007/85562597-af634400-b63d-11ea-9ef9-4afddbb996a5.png">

**Пожалуйста, заполните следующую информацию:**
  - Версия: SputHub 1.6.0b

**Comment by MakeSimpleOrg** [comment]
1.6.4
