### ISSUE TITLE
Битовая маска для Modbus регистров в шаблоне

### ISSUE THREAD

**Issue by shishov-pavel** [sprut/Hub#1161]
** Максимально подробное описание предложения.**
В СХ добавить функцию, с помощью которой, используя в шаблоне определённый синтаксис, будет возможно читать и записывать необходимый бит в Modbus-регистре, для добавленного контроллера в СХ.

Например, в шаблоне для WB синтаксис чтения и записи необходимого бита в Modbus-регистре выглядит следующим образом:
![photo_2022-03-01_00-39-03](https://user-images.githubusercontent.com/88215731/158686034-bb7daa83-7baf-48b7-b4d1-a9b5d4e9dca7.jpg)

Имеется сейчас: можем читать и записывать только весь Modbus-регистр.
Необходимо: считывать и записывать только конкретный бит в Modbus-регистре.
![Имеется и Необходимо](https://user-images.githubusercontent.com/88215731/158691293-02a27528-e170-4c79-b5dd-5be43cae9426.jpg)

Телеграмм: @shishov_pavel

**Comment by shishov-pavel** [comment]
UP

**Comment by shishov-pavel** [comment]
UP

**Comment by shishov-pavel** [comment]
UP

**Comment by sprut666666** [comment]
вынесено на голосование
