### ISSUE TITLE
TS0601

### ISSUE THREAD

**Issue by DzRou** [sprut/Hub#1162]
Address: 9035EAFFFE03E98F/5500<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 72</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZE200_zyrdrmno</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: 
��)��)</li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Mar 17 11:51:15 MSK 2022

Привод для жалюзи от компании ALUTECH 
привод в комплекте с блоком управления Alutech Zigbee Module 
![04  AM0_trp](https://user-images.githubusercontent.com/96169371/158776233-4606c578-89e2-4123-8eeb-1e14a206c4b3.png)

файл sniffer: 
[2022-03-17_11-45-46.zip](https://github.com/sprut/Hub/files/8283292/2022-03-17_11-45-46.zip)

Ник в ТГ: @A_l_e_x_p
в каталоге Sprut отсутствует
https://market.yandex.ru/product--blok-upravleniia-alutech-zigbee-module/1665518277?cpa=1

работает с custom template  
[zyrdrmno.zip](https://github.com/sprut/Hub/files/8283349/zyrdrmno.zip)

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/blok-upravleniya-alutech-zigbee-module
