### ISSUE TITLE
Добавьте пожалуйста шаблон на выключатель ZEMISMART

### ISSUE THREAD

**Issue by kachalex** [sprut/Hub#1168]
Address: 84BA20FFFE8DA711/9262<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 75</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_a37eix1s</li><li>0005_ModelIdentifier: TS0004</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: </li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>E000_ManufacturerSpecific<ul><li>D001_Custom: ByteArray [value=00 06]</li><li>D002_Custom: ByteArray [value=00 0A]</li><li>D003_Custom: AAAAAgAABAAABgAA</li></ul></li><li>E001_ManufacturerSpecific<ul><li>D010_Custom: 0</li><li>D030_Custom: 1</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 177</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>5000_Custom: 1</li><li>8000_MultipleClick: false</li><li>8001_IndicatorMode: 2</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>E001_ManufacturerSpecific<ul><li>D010_Custom: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 219</li><li>0002_CurrentGroup: 8192</li><li>0003_SceneValid: true</li><li>0004_NameSupport: 189</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 2</li><li>8002_RestartStatus: 0</li></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul><li>0010_GppMaxProxyTableEntries: 5</li><li>0011_ProxyTable: ByteArray [value=]</li><li>0016_GppFunctionality: 633903</li><li>0017_GppActiveFunctionality: 16777215</li><li>0022_GpClientLinkKey: 5A6967426565416C6C69616E63653039</li></ul></li></ul></li></ul></li><li>Endpoint 3 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>E001_ManufacturerSpecific<ul><li>D010_Custom: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 4</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 2</li><li>8002_RestartStatus: 0</li></ul></li></ul></li></ul></li><li>Endpoint 4 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>E001_ManufacturerSpecific<ul><li>D010_Custom: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 9</li><li>0002_CurrentGroup: 37024</li><li>0003_SceneValid: true</li><li>0004_NameSupport: 9</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 2</li><li>8002_RestartStatus: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 22 16:47:02 IST 2022

**Comment by Batyushin** [comment]
Необходимо добавить:
 - ссылку на устройство в магазине, 
 - ссылку на ваш телеграм.

**Comment by kachalex** [comment]
ссылку на устройство в магазине:
https://aliexpress.ru/item/1005003767817391.html?_ga=2.3588342.736640938.1648046454-770840956.1614420733&_gac=1.91349352.1647069388.CjwKCAiAg6yRBhBNEiwAeVyL0E2WVPzM-UaYgcBDGt4t4kcb1GcBLT2IM1e2Maz_roznJ6zux8_XGxoCOYsQAvD_BwE&item_id=1005003767817391&mp=1&sku_id=12000027097162921&spm=a2g0o.cart.0.0.68503c00nZaOz6

Телеграмм : @kacha_alex

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/wall-light-switch-4-gangs
