### ISSUE TITLE
Редактирование минимального и максимально значения, а также шага регулировки

### ISSUE THREAD

**Issue by AGKulikov** [sprut/Hub#117]
В аксессуарах, в которых есть абсолютное минимальное и максимальное значение добавить возможность редактировать эти значения (например. термостат)

Так же в регулируемых аксессарах добавит возможность настройки шага (термостат, скорость вентилятора, окно и т.д.)

**Comment by sprut666666** [comment]
для виртуальный устройств в актуальных сборках работает
