### ISSUE TITLE
Добавить поддержку Aqara Cube

### ISSUE THREAD

**Issue by corsaroff** [sprut/Hub#118]
Прошу добавить поддержку Aqara Cube https://v2.sprut.ai/catalog/item/aqara-cube в SprutHub

определяется как:
manufacturerId: LUMI
modelId: lumi.sensor_cube

Telegram - @vklimov

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by sprut666666** [comment]
не приведено в соответствие
