### ISSUE TITLE
Добавление Термостат Fibaro FGT-001 RU 869MHz ISM

### ISSUE THREAD

**Issue by Yuanti** [sprut/Hub#1180]
Heat controller radiator thermostat Fibaro FGT-001 RU 869MHz ISM
https://www.fibaro.com/ru/products/the-heat-controller/

<b>Fibargroup - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>32</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>1301</td></tr><tr><td width=35%>Device Id</td><td>4001</td></tr><tr><td width=35%>App Version</td><td>4.7</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Thermostat</td></tr><tr><td width=35%>Specific Class</td><td>Thermostat General V2</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>true</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>1</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 CRC16Encap</li><li>V5 SensorMultiLevel<ul><li>Temperature: </li></ul></li><li>V1 Protection</li><li>V1 ThermostatSetpoint<ul><li>Heating: 16</li></ul></li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V3 MultiChannelAssociation</li><li>V1 Security</li><li>V1 NoOperation</li><li>V1 ZWavePlusInfo</li><li>V2 ManufacturerSpecific</li><li>V1 Schedule</li><li>V1 Battery<ul><li>Level: 85</li><li>Low: false</li></ul></li><li>V1 Configuration</li><li>V1 ApplicationStatus</li><li>V2 Association</li><li>V1 AssociationGRPInfo</li><li>V2 Version</li><li>V1 DeviceResetLocally</li><li>V2 MultiChannel</li><li>V1 Basic</li><li>V1 FirmwareUpdateMD</li><li>V1 ThermostatMode<ul><li>Heat</li><li>Off</li><li>Manual</li></ul></li><li>V8 Alarm<ul><li>PowerManagement</li><li>System</li></ul></li><li>V1 Clock</li></ul></li><li>Endpoint 1<ul><li>V1 Protection</li><li>V1 ThermostatSetpoint<ul><li>Heating: </li></ul></li><li>V1 AssociationGRPInfo</li><li>V3 MultiChannelAssociation</li><li>V1 Security</li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li><li>V1 Battery</li><li>V1 Schedule</li><li>V1 ApplicationStatus</li><li>V1 ThermostatMode<ul><li>Heat</li><li>Off</li></ul></li><li>V2 Association</li><li>V8 Alarm<ul><li>PowerManagement</li><li>System</li></ul></li><li>V1 Clock</li></ul></li><li>Endpoint 2<ul><li>V1 ZWavePlusInfo</li><li>V5 SensorMultiLevel<ul><li>Temperature: </li></ul></li><li>V1 Basic</li><li>V1 Battery</li><li>V1 ApplicationStatus</li><li>V1 AssociationGRPInfo</li><li>V3 MultiChannelAssociation</li><li>V1 Security</li><li>V8 Alarm<ul><li>PowerManagement</li></ul></li><li>V2 Association</li></ul></li></ul><br>Last update: Wed Apr 06 15:32:15 UTC 2022

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/fibaro-the-heat-controller-2

**Comment by SmartHaven** [comment]
Эта термоголовка давно поддерживается, но тут чуть другой номер модели. Добавил в поддерживаемые в r7005. И аналогичные номера тоже.
