### ISSUE TITLE
Зависание веб-интерфейса при открытии свойства "Без звука" аксессуара "Динамик"

### ISSUE THREAD

**Issue by lexalexalexa** [sprut/Hub#1182]
** Подробное описание ошибки **
При попытке развернуть аксессуар типа динамик возникает ошибка: кнопки свойства "Без звука" не подгружаются, все кнопки на странице перестают реагировать на нажатия, к свойству нет возможности привязать другое свойство.

** Как воспроизвести ? **
Зайти в старый веб (55555), добавить виртуальный аксессуар типа "Динамик", раскрыть его до свойства "Без звука".

** Ожидаемое поведение **
Отсутствие зависания страницы, возможность привязки другого свойства в свойству "Без звука".

** Скриншоты/ Логи **
![photo_2022-04-06_08-29-03](https://user-images.githubusercontent.com/7578657/162202014-a38badd8-0e45-4d87-9091-a406d2ccbcdf.jpg)

** Пожалуйста, заполните следующую информацию: **
  - Версия: Ревизия: 6981 Дата сборки: 04.04.2022, 00:40:53

**Comment by SmartHaven** [comment]
Исправлено в r7004.
