### ISSUE TITLE
DIYRuZ_Flower

### ISSUE THREAD

**Issue by pcadminby** [sprut/Hub#1183]
Заявлена поддержка modcam датчика влажности почвы.. однако он у меня определяется просто как батарейка.
Address: 00124B00234C967D/8017

Structure
Endpoint 1 (SIMPLE_SENSOR)
Input
0000_Basic
0001_ApplicationVersion: 3
0003_HWVersion: 1
0004_ManufacturerName: modkam.ru
0005_ModelIdentifier: DIYRuZ_Flower
0007_PowerSource: 3
4000_SWBuildID: 26/01/2021 21:03
0001_PowerConfiguration
0021_BatteryPercentageRemaining:
Output
0400_IlluminanceMeasurement
0001_PowerConfiguration
0402_TemperatureMeasurement
0403_PressureMeasurement
0405_RelativeHumidityMeasurement
0408_SoilMoisture
0019_OtaUpgrade
Endpoint 2 (SIMPLE_SENSOR)
Output
0402_TemperatureMeasurement

Node Descriptor
Aps Flags	0
Frequency Bands	[FREQ_2400_MHZ]
Server Capabilities	[]
Buffer Size	80
Incoming Transfer Size	160
Logical Type	End Device
Mac Capabilities	[REDUCED_FUNCTION_DEVICE]
Manufacturer Code	0
Out Going Transfer Size	160
Stack Compliance	0

Power Descriptor
Current Power Mode	RECEIVER_ON_PERIODICALLY
Available Power Sources	[RECHARGABLE_BATTERY]
Current Power Source	RECHARGABLE_BATTERY
Power Level	MEDIUM

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/modkam-sensor-vlaznosti-pocvy-zigbee-versia-no3

**Comment by pcadminby** [comment]
как бы..  вторая https://sprut.ai/catalog/item/modkam-sensor-vlaznosti-pocvy-zigbee-versia-no2
а у Вас ссылка на третью

**Comment by pcadminby** [comment]
Так а где шаблон ?

**Comment by DobriyVasia** [comment]
3310
[DIYRuZ_Flower.zip](https://github.com/sprut/Hub/files/9686940/DIYRuZ_Flower.zip)
