### ISSUE TITLE
Предложение к добавлению устройств (Широкий список)

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#119]
Aqara двойной выключатель с нулевой линией.
Aqara одинарный выключатель с нулевой линией.
Лампочка Ikea e14 https://v2.sprut.ai/catalog/item/ikea-e14-warm-white
Aqara Relay https://v2.sprut.ai/catalog/item/akara-relay
Aqara B1 шторы https://v2.sprut.ai/catalog/item/aqara-curtain-motor
Philips Hue светильник https://v2.sprut.ai/catalog/item/philips-play-light-bar
Philips Hue лента  https://v2.sprut.ai/catalog/item/philips-lightstrip-plus-base-pack-hue-white-and-color-ambiance
Philips Hue Лампочка (Отправил Спруту) https://v2.sprut.ai/catalog/item/philips-hue-white-single-filament-a19-e26-bulb
Никита Усков
nergu229@gmail.com

**Comment by sprut666666** [comment]
1 устройство = одно ишью
