### ISSUE TITLE
ZigBee-_TZ3000_zirycpws-TS130F

### ISSUE THREAD

**Issue by dimis75** [sprut/Hub#1202]
**Zigbee Curtain module**

**Информация об устройстве:**
Address: A4C138DA4200463C/B2D2<br><br><b>Structure</b><br><ul><li>Endpoint 1 (WINDOW_COVERING_DEVICE)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 64</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_zirycpws</li><li>0005_ModelIdentifier: TS130F</li><li>0007_PowerSource: 1</li></ul></li><li>0102_WindowCovering<ul><li>0008_CurrentPositionLiftPercentage: 100</li><li>F000_PositionState: 1</li><li>F001_UpDownConfirm: 1</li><li>F002_ControlBack: 0</li><li>F003_ScheduleTime: 100</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>8001_IndicatorMode: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 64</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>2C1165FFFEABE008</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>77</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Apr 28 06:09:39 MSK 2022

В SH определяется как: https://sprut.ai/catalog/item/tuya-zigbee-curtain-module
**при добавлении в SH в логе:**
13:50:13 Device loaded 'TS130F', manufacturer '_TZ3000_zirycpws', firmware '64', ZigBeeNode A4C138DA4200463C/B2D2, **init=Нет шаблона,** sleepy=false, loading=false, removed=false, Type=Router] 

Цвет устройства: Темно-серый
Наличие нуля:С нулевой линией
Управление:Управление электроприводом
Способ монтажа:В подрозетник
Источник питания:От сети
Версия ZigBee:3.0
Режим спаривания, сброса:10 сек нажатие

Telegram: @DimisRu
Покупал здесь: https://aliexpress.ru/item/1005003657445466.html

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zigbee-curtain-module
