### ISSUE TITLE
_TZ3000_upgcbody

### ISSUE THREAD

**Issue by VladimirIusupov** [sprut/Hub#1214]
Address: A4C138915EB88442/6314<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 42</li><li>0002_ZoneStatus: 0</li><li>0010_IASCIEAddress: B4E3F9FFFE672064</li><li>0011_ZoneID: 29</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_upgcbody</li><li>0005_ModelIdentifier: TS0207</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Sat May 14 23:26:46 MSK 2022

покупал на али https://aliexpress.ru/item/1005002910190482.html?aff_fcid=f5fb9ced47f54bb4ba4d251147fdc11c-1652572440378-02167-_9vmH8Z&aff_fsk=_9vmH8Z&aff_platform=default&aff_trace_key=f5fb9ced47f54bb4ba4d251147fdc11c-1652572440378-02167-_9vmH8Z&bizType=ProductDetail&businessType=ProductDetail&platform=AE&shareId=40181094574&sk=_9vmH8Z&sku_id=12000022738148692&social_params=40181094574&spreadType=socialShare&srcSns=sns_More&terminal_id=7c3f9d627ad44b3a935544c816fb9f71&tt=MG

tg@vladimir_yusupov

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/water-leak-alarm
