### ISSUE TITLE
Датчик качества воздуха LifeControl MCLH-08 не прокидывается в Алису

### ISSUE THREAD

**Issue by maxfaq** [sprut/Hub#122]
После добавление в Алису навыка SprutHub

ФР: Датчик LifeControl MCLH-08 не появился.
ОР: Появился датчик LifeControl MCLH-08

Предполагаю проблема в том, что датчик не инициализирован для данного ассистента
![image](https://user-images.githubusercontent.com/55385391/85629078-e0616a00-b679-11ea-9a7b-9010494ecbf3.png)
![image](https://user-images.githubusercontent.com/55385391/85629159-ff5ffc00-b679-11ea-8ac8-fa8dd9573fd8.png)

Версия: SprutHub 1,6,0b
Телефон: Oneplus 8 (Android 10)
Ник в Telegram: Maxim Shcheniatskiy

**Comment by sprut666666** [comment]
1.6.3
