### ISSUE TITLE
Danalock V3 Smart Lock Z-Wave

### ISSUE THREAD

**Issue by little-dgek** [sprut/Hub#1225]
Danalock V3 Smart Lock  ZWave некорректно отображается заряд батареи. Поставил новые батарейки - пишет 0.

ZWave sitck UZB7. 
Spruthub CE
Ревизия: 6981
Дата сборки: 04.04.2022, 00:40:53

<img width="1262" alt="Снимок экрана 2022-06-04 в 15 18 51" src="https://user-images.githubusercontent.com/9482740/171998685-b6f11437-aa49-4971-9b89-edfc21807ce7.png">

UPD 

В старом веб интерфейсе вижу зарядку 92%. В новом 0 и в хоумкит передается 0.

**Comment by little-dgek** [comment]
В информации о девайсе, в структуре, я вижу заряд. А в "аксессуарах" заряд 0 (как на картинке в первом сообщении)



![B28A9791-5B68-42A4-AB3E-3285E6D40EEE](https://user-images.githubusercontent.com/9482740/172260462-aa69f772-1cec-4563-b649-7c6e8719868a.png)

**Comment by SmartHaven** [comment]
Это очень хорошо, что заряд есть в информации. Значит точно исправим. Но сначала нужно дождаться крупного обновления (1.9.1) и проверить еще раз, т.к. многое поменялось.

**Comment by SmartHaven** [comment]
Проверить снова.

**Comment by little-dgek** [comment]
> Проверить снова.

На текущем релизе все хорошо.
Батарея появилась в Хоум кит.
