### ISSUE TITLE
ZigBee - _TZ3000_yd2e749y - TS0201

### ISSUE THREAD

**Issue by ShiroiKanto** [sprut/Hub#1227]
Type:	End Device
Capabilities:	[REDUCED_FUNCTION_DEVICE]
Manufacturer Code:	4417
Stack:	21
Power Mode:	RECEIVER_ON_STIMULATED
Power Level:	MEDIUM
Currect Source:	RECHARGABLE_BATTERY
Last Update:	Jun 8, 2022 2:18:42 AM

Address: A4C138E588432FF1/612D

Structure
Endpoint 1 (TEMPERATURE_SENSOR)
Input
0000_Basic
0001_ApplicationVersion: 69
0003_HWVersion: 1
0004_ManufacturerName: _TZ3000_yd2e749y
0005_ModelIdentifier: TS0201
0007_PowerSource: 3
0001_PowerConfiguration
0021_BatteryPercentageRemaining:
0402_TemperatureMeasurement
0000_MeasuredValue: 2216
0003_Identify
0405_RelativeHumidityMeasurement
0000_MeasuredValue: 4616
Output
0003_Identify
0019_OtaUpgrade
000A_Time

Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags	0
Frequency Bands	[FREQ_2400_MHZ]
Server Capabilities	[]
Buffer Size	66
Incoming Transfer Size	66
Logical Type	End Device
Mac Capabilities	[REDUCED_FUNCTION_DEVICE]
Manufacturer Code	4417
Out Going Transfer Size	66
Stack Compliance	21

Power Descriptor
Current Power Mode	RECEIVER_ON_STIMULATED
Available Power Sources	[RECHARGABLE_BATTERY]
Current Power Source	RECHARGABLE_BATTERY
Power Level	MEDIUM

Last update: Wed Jun 08 02:28:42 MSK 2022

**Дополнительно**

Telegram: @KantoKage

Новое устройство - Датчик температуры и влажности - Zigbee Tuya

Приобретал здесь:
https://m.aliexpress.ru/item/1005002362873744.html?srcSns=sns_More&spreadType=socialShare&bizType=ProductDetail&social_params=40187957767&aff_fcid=1c23cb96ce1544b08b7f5141b1372ec7-1654645143973-08449-_9wZVsl&tt=MG&aff_fsk=_9wZVsl&aff_platform=default&sk=_9wZVsl&aff_trace_key=1c23cb96ce1544b08b7f5141b1372ec7-1654645143973-08449-_9wZVsl&shareId=40187957767&businessType=ProductDetail&platform=AE&terminal_id=b11ab7255d0a4c83a95bdf2fba61819a&sku_id=12000027900165584

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zigbee-3-0-temperature-and-humidity-sensor
