### ISSUE TITLE
Новая логика - изменение яркости канала диммера (WB-MDM3 / WB-RGBW) без изменения статуса канала на "Вкл" в HomeKit

### ISSUE THREAD

**Issue by OwlBawl** [sprut/Hub#1228]
Ранее думал что это функциональное ограничение HomeKit, что при изменении уровня яркости канал отображается как "Вкл", по-фату же он остается выключенным.

Цель была сделать сценарий регулировки яркости по времени дня. Не изменяя статус "вкл / выкл" для света.
Получилось реализовать с помощью Node-Red, значит HomeKit позволяет на WB так делать. В SH при изменении только яркости - канал включается. 
А если у вас выключатели на входы реле выведены физически (для меня это как задел автономности механики от софта) - то нельзя софтверно обработать работу клавиши и разорвать связь.

Все оказалось совсем не сложно.

Взял шаблон из node-red-wirenboard для mdm3 и всего лишь изменил функции между WB-in к HomeKit:
**для K1:**
msg.payload = (msg.payload == '1') ? {'On':true} : {'On':false};
return msg

**для Cnannel 1:**
var characteristic = {};
characteristic.Brightness = parseInt(msg.payload);
msg.payload = characteristic;
return msg;

То есть просто не смешивать статус K1 и яркость. Тогда регулировка яркости не прифодит к fake включению.

Теперь по времени яркость меняется отдельным flow, но нет ложного отображения включения в HomeKit.
Статус считывается корректно в HK, при изменении яркости в HK ползунком - свет включается как и положенно.
Было бы неплохо такую логику и SH добавить.

Могу скинуть полный flow для удобства.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"

**Comment by demkanone** [comment]
Приветствую! Можете, пожалуйста, флоу скинуть?

**Comment by OwlBawl** [comment]
Есть уже сценарий на JS написанный для SH такой
NR больше не юзаю для этого
