### ISSUE TITLE
 3325-S

### ISSUE THREAD

**Issue by Co1dSUN** [sprut/Hub#1234]
Address: 000D6F000B119AD0/4154<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: CentraLite</li><li>0005_ModelIdentifier: 3325-S</li><li>0006_DateCode: ����������������</li><li>0007_PowerSource: 3</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 14400</li><li>0001_LongPollInterval: 24</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li><li>0004_CheckinIntervalMin: 240</li><li>0005_LongPollIntervalMin: 23</li><li>0006_FastPollTimeoutMax: 120</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 13</li><li>0002_ZoneStatus: 38</li><li>0010_IASCIEAddress: FFFFFFFFFFFFFFFF</li><li>0011_ZoneID: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 26</li><li>0031_BatterySize: 2</li><li>0033_BatteryQuantity: 1</li><li>0036_BatteryVoltageMinThreshold: 21</li><li>003E_BatteryAlarmState: 0</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2617</li><li>0001_MinMeasuredValue: -4000</li><li>0002_MaxMeasuredValue: 6000</li><li>0003_Tolerance: 150</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0100_MACRxBcast: 536870912</li><li>0101_MACTxBcast: 536870912</li><li>0102_MACRxUcast: 536870988</li><li>0103_MACTxUcast: 536870966</li><li>0104_MACTxUcastRetry: 14</li><li>0105_MACTxUcastFail: 0</li><li>0106_APSRxBcast: 3</li><li>0107_APSTxBcast: 2</li><li>0108_APSRxUcast: 16</li><li>0109_APSTxUcastSuccess: 8</li><li>011C_LastMessageLQI: 255</li><li>011D_LastMessageRSSI: -78</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 520573712</li><li>0003_CurrentZigBeeStackVersion: 65535</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4174</li><li>0008_ImageTypeID: 27</li><li>0009_MinimumBlockRequestPeriod: 0</li><li>000A_ImageStamp: </li></ul></li></ul></li></ul></li><li>Endpoint 2 (OCCUPANCY_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul></ul></li><li>0B05_Diagnostics<ul></ul></li><li>FC46_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4174</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jun 24 19:01:40 CEST 2022
https://t.me/ColdSUN
Покупался очень давно. Наверное где-то на немецком амазоне.
https://sprut.ai/catalog/item/smartthings-devices-smartthings-motion-sensor-2015-model
Питание от CR2450, для спаривания надо нажать кнопку и вставить батарейку. Сразу отпустить кнопку.
Тампера нет.

**Comment by Co1dSUN** [comment]
[3325-S.txt](https://github.com/sprut/Hub/files/8980726/3325-S.txt)

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/smartthings-devices-smartthings-motion-sensor-2015-model

**Comment by Co1dSUN** [comment]
[3325-S.zip](https://github.com/sprut/Hub/files/9463817/3325-S.zip)
