### ISSUE TITLE
ZigBee - _TZE200_la2c2uo9 - TS0601

### ISSUE THREAD

**Issue by ShiroiKanto** [sprut/Hub#1235]
Structure 
Endpoint 1 (SMART_PLUG)
Input
0000_Basic
0000_ZCLVersion: 3
0001_ApplicationVersion: 68
0002_StackVersion: 0
0003_HWVersion: 1
0004_ManufacturerName: _TZE200_la2c2uo9
0005_ModelIdentifier: TS0601
0006_DateCode:
0007_PowerSource: 1
FFDF_Custom:
FFE2_Custom: 31
FFE4_Custom: 0
FFFE_Custom: 0
EF00_ManufacturerSpecific
0001_Custom: true
0002_Custom: 21
0003_Custom: 0
0004_Custom: 0
0004_Groups
0000_NameSupport: 0
0005_Scenes
0000_SceneCount: 0
0001_CurrentScene: 0
0002_CurrentGroup: 0
0003_SceneValid: false
0004_NameSupport: 0
Output
0019_OtaUpgrade
0000_UpgradeServerID: FFFFFFFFFFFFFFFF
0001_FileOffset: -1
0006_ImageUpgradeStatus: 0
000A_Time

Binding table

Group membership

Associated devices

Neighbor table

Routing table

Frequency Bands	[FREQ_2400_MHZ]
Server Capabilities	[]
Buffer Size	82
Incoming Transfer Size	82
Logical Type	Router
Mac Capabilities	[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]
Manufacturer Code	4098
Out Going Transfer Size	82
Stack Compliance	22

Power Descriptor
Current Power Mode	RECEIVER_ON_IDLE
Available Power Sources	[MAINS]
Current Power Source	MAINS
Power Level	FULL

Last update: Sun Jun 26 01:43:30 MSK 2022

Дополнительно

Telegram: @KantoKage

Новое устройство - Диммер одноканальный  - Zigbee MOES

Приобретал здесь:
893,60 руб.  -42％ | Умный диммер мини «сделай сам» для Tuya ZigBee 3,0, модуль переключателя Zigbee, требуется приложение Smart Life, Alexa Google Home, голосовое управление, 1/2 каналов
https://a.aliexpress.com/_DDrma39

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/moes-zigbee-dimmer-module

**Comment by Co1dSUN** [comment]
[TS0601_dimmer_TZE200_la2c2uo9.zip](https://github.com/sprut/Hub/files/8991946/TS0601_dimmer_TZE200_la2c2uo9.zip)

**Comment by neoinworld** [comment]
> [TS0601_dimmer_TZE200_la2c2uo9.zip](https://github.com/sprut/Hub/files/8991946/TS0601_dimmer_TZE200_la2c2uo9.zip)

ID в посте 3975, а девайсы приезжают видимо обновленные с новым ID 4098.

**Comment by ShiroiKanto** [comment]
Понял. Благодарю!

**Comment by neoinworld** [comment]
покупался : [https://aliexpress.ru/item/1005001593033528.html?spm=a2g2w.orderdetails.0.0.64e34aa6ZQbWrA&sku_id=12000016713088950](url)

Для коробки SHCE:
Решается добавлением кастомного шаблона (Templates) на внешний носитель. За основу брался оригинальный шаблон "TS0601_dimmer_TZE200_dfxkcots.json" с заменой соответствующих строк "manufacturerId" и "catalogId".

`"manufacturer": "Tuyatec",
  "model": "TS0601",
  "manufacturerId": "_TZE200_la2c2uo9",
  "modelId": "TS0601",
  "catalogId": 7940,`

После добавления переподключение самого реле не требуется, лишь перезапуск контроллера ZigBee.
