### ISSUE TITLE
ZigBee - _TZ3210_1elppmba - TS0504B

### ISSUE THREAD

**Issue by den1ss666** [sprut/Hub#1236]
Address: A4C138DA6001E0D8/CD59<br><br><b>Structure</b><br><ul><li>Endpoint 1 (EXTENDED_COLOR_LIGHT)<ul><li>Input<ul><li>EF00_ManufacturerSpecific<ul><li>0051_Custom: -50</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3210_1elppmba</li><li>0005_ModelIdentifier: TS0504B</li><li>0007_PowerSource: 1</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 147</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 191</li><li>000F_Options: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 65</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jun 26 18:53:37 MSK 2022

<b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br>

Aps Flags | 0
-- | --
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 66
Incoming Transfer Size | 66
Logical Type | Router
Mac Capabilities | [FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]
Manufacturer Code | 4417
Out Going Transfer Size | 66
Stack Compliance | 21

<br>

<h1 id="tuya-ts0504b" tabindex="-1">TuYa TS0504B</h1>

  |  
-- | --
Model | TS0504B
Vendor | TuYa
Description | Zigbee RGBW light
Exposes | light (state, brightness, color_xy), effect, linkquality

https://www.zigbee2mqtt.io/devices/TS0504B.html
![TS0504B](https://user-images.githubusercontent.com/51699946/175823100-b5bb60d9-9973-484e-90c2-234edc318565.jpg)

Ссылка на товар https://a.aliexpress.com/_DeMhmrd

**Comment by Batyushin** [comment]
необходимо добавить ссылку на магазин

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/ysrsai-zigbee-led-controller-rgbcct
