### ISSUE TITLE
FYRTUR block-out roller blind

### ISSUE THREAD

**Issue by spychief** [sprut/Hub#1241]
Address: 804B50FFFE58F16C/6AA1<br><br><b>Structure</b><br><ul><li>Endpoint 1 (WINDOW_COVERING_DEVICE)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 33</li><li>0002_StackVersion: 99</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: FYRTUR block-out roller blind</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 2.3.088</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 172800</li><li>0001_LongPollInterval: 4</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 1</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 83</li><li>0021_BatteryPercentageRemaining: 100</li></ul></li><li>0102_WindowCovering<ul><li>0000_WindowCoveringType: 0</li><li>0007_ConfigStatus: 3</li><li>0008_CurrentPositionLiftPercentage: 0</li><li>0010_InstalledOpenLimitLift: 0</li><li>0011_InstalledClosedLimitLift: 65535</li><li>0012_InstalledOpenLimitTilt: 0</li><li>0013_InstalledClosedLimitTilt: 65535</li><li>0017_Mode: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>FC7C_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 587761201</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4476</li><li>0008_ImageTypeID: 65535</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>00047400008B5D53</td><td>D0EE</td><td>Router</td><td>false</td><td>Parent</td><td>176</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Jun 30 13:55:56 MSK 2022
Telegram: impreza1001
https://sprut.ai/catalog/item/ikea-fyrtur
https://www.ikea.com/ru/ru/p/fyrtur-fyurtyur-rulonnaya-shtora-blokiruyushchaya-svet-umnyy-dom-besprovodnaya-s-batareynym-pitaniem-seryy-50408214/

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/ikea-fyrtur
