### ISSUE TITLE
TRADFRI remote control

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Hub#125]
Address: 14B457FFFE504A9D/ECDF<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>4000_SwBuildId: 2.3.014</li><li>0001_ApplicationVersion: 33</li><li>0002_StackVersion: 98</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI remote control</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 172800</li><li>0001_LongPollInterval: 1160</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 27</li><li>0021_BatteryPercentageRemaining: 47</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>FC7C_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Mon Jun 29 03:23:16 MSK 2020

Телеграм: [@GeorgeBennelli](https://t.me/GeorgeBennelli)
[Девайс в каталоге](https://v2.sprut.ai/catalog/item/ikea-besprovodnoj-reostat-2)

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ikea-besprovodnoj-reostat-2
