### ISSUE TITLE
Добавить поддержку контроллера MegaD-2561-31I15O-RTC-PoE (моноблок)

### ISSUE THREAD

**Issue by RonL1** [sprut/Hub#1257]
Добавить поддержку контроллера MegaD-2561-31I15O-RTC-PoE (моноблок)
По информации от производителя они отправляли Вам экземпляр моноблока.

Ник в телеграм: @Vyacheslav2622

[Сайт производителя](https://ab-log.ru/smart-house/ethernet/megad-2561)
[Ссылка в каталоге](https://sprut.ai/catalog/item/megad-kontroller-ispolnitelnyj-modul-v-odnom-korpuse-2561-24i14o-rtc)
[Форум MegaD-2561-31I15O-RTC-PoE (моноблок)](https://ab-log.ru/forum/viewtopic.php?f=1&t=1505)
[Интеграция в Home Asistant](https://github.com/andvikt/mega_hacs)

**Comment by sprut666666** [comment]
вынесено на голосование

**Comment by onboard123** [comment]
Поддержка не появилась? читал в группе, что обещали.
