### ISSUE TITLE
Датчик открытия дверей и окон Perenio PECWS01

### ISSUE THREAD

**Issue by naumserg74** [sprut/Hub#1264]
Address: 00158D0002AEBABB/FC30<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 25</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: LDS</li><li>0005_ModelIdentifier: ZHA-DoorLockSensor</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 2.4</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 21</li><li>0002_ZoneStatus: 48</li><li>0010_IASCIEAddress: 0000000000000000</li><li>0011_ZoneID: 255</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 6480</li><li>0001_LongPollInterval: 1200</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li><li>0004_CheckinIntervalMin: 1200</li><li>0005_LongPollIntervalMin: 1200</li><li>0006_FastPollTimeoutMax: 240</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 28</li><li>0021_BatteryPercentageRemaining: 90</li><li>0031_BatterySize: 255</li></ul></li><li>0003_Identify<ul></ul></li><li>0B05_Diagnostics<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4456</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jul 24 18:08:41 YEKT 2022

Покупал здесь:
https://www.wildberries.ru/catalog/70327647/detail.aspx?sort=popular&search=perenio

**Comment by naumserg74** [comment]
Шаблон  рабочий:
[PECWS01.json.zip](https://github.com/sprut/Hub/files/9176305/PECWS01.json.zip)

**Comment by naumserg74** [comment]
Можно добавить в следующей версии

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/door-window-sensor
