### ISSUE TITLE
Фильтр на странице со сценариями.

### ISSUE THREAD

**Issue by top4ek** [sprut/Hub#1266]
**Подробное описание ошибки**
Eсли на странице с блочными сценариями выбрать комнату и переключиться на шаблоны(и логические с глобальными), то фильтр продолжает "действовать", т.е. вкладки с шаблонами и прочим пустые.

**Как воспроизвести?**
1. Открыть блочные сценарии.
2. Переключить фильтр с "Все комнаты" на любую комнату.
3. Переключиться на вкладку Шаблоны.
4. Пустота.

**Ожидаемое поведение**
Видеть мои сценарии. 
Тут надо либо сброс фильтра, либо НЕ скрывать дропбокс фильтра на вкладках.

**Пожалуйста, заполните следующую информацию:**
SprutHub CE
Web 1.1.3
System 1.9.1 (7853)

**Comment by aliksiy** [comment]
Поправлено Web 1.1.4
