### ISSUE TITLE
ZigBee - Philips - LLC020

### ISSUE THREAD

**Issue by tim0feev** [sprut/Hub#1268]
LLC020. 1.9.1. Не спаривается. Пишет "Очистка групп". Лампа стоит уже прям рядом с роутером и хабом.

Address: 00178801011947EC/CFE6<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Input<ul><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 2</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: Signify Netherlands B.V.</li><li>0005_ModelIdentifier: LLC020</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 67.93.7</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>FC03_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: </li></ul></li><li>0008_LevelControl<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>84FD27FFFE07FC6B</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>255</td><td>ENABLED</td><td>0</td></tr><tr><td>00178801104FDB23</td><td>1468</td><td>Router</td><td>false</td><td>Unknown</td><td>255</td><td>ENABLED</td><td>1</td></tr><tr><td>0017880102281243</td><td>D458</td><td>Router</td><td>false</td><td>Unknown</td><td>255</td><td>ENABLED</td><td>1</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>71</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>45</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>45</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, RECHARGABLE_BATTERY, MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jul 25 15:49:25 SAMT 2022

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/philips-hue-go-besprovodnoj-led-svetilnik
