### ISSUE TITLE
Zigbee RGB Tunable LED Bulb RGB E27 [добавить устройств]

### ISSUE THREAD

**Issue by gonczarov** [sprut/Hub#128]
прошу добавить устройство Zigbee RGB Tunable LED Bulb RGB E27

ссылка на каталог

https://v2.sprut.ai/catalog/item/trust-light-bulb-2

gonczarov85

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by gonczarov** [comment]
Address: 00158D00011D8AD2/1327<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>FFFF_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sat Jul 04 17:21:56 MSK 2020

**Comment by sprut666666** [comment]
Устройство прошло не полный опрос, прошу обновить информацию

**Comment by sprut666666** [comment]
не приведено в соответствие

**Comment by oleg77s** [comment]
оно и у меня не проходит полный опрос  (пробовал несколько раз)

20:58:53 | ZigBee поиск завершён |  
-- | -- | --
20:58:52 | 00158D00011EB6E2/D7D4 : Информация о модели - Нет ответа |  
20:58:52 | Transaction terminated (Timeout): 0000_ReadAttributesCommand [0000_Basic: 0000/0 -> D7D4/1, TID=1A, Input, identifiers=[0001_ApplicationVersion, 0005_ModelIdentifier, 0004_ManufacturerName, 0007_PowerSource, 4000_SwBuildId, 0003_HwVersion]] |  
20:58:37 | 00158D00011EB6E2/D7D4 : 2/2, Изучение конечной точки 1 |  
20:58:37 | 00158D00011EB6E2/D7D4 : 2/1, Изучение конечной точки 2 |  
20:58:37 | 00158D00011EB6E2/D7D4 : Изучение возможностей |  
20:58:36 | 00158D00011EB6E2/D7D4 : Энергопотребление |  
20:58:36 | 00158D00011EB6E2/D7D4 : Базовая информация |  
20:58:36 | 00158D00011EB6E2/D7D4: Запущен опрос устройства |  
20:58:35 | Unknown node 00158D00011EB6E2, frame: ZigBeeApsFrame [sourceAddress=D7D4/0, destinationAddress=0000/0, profile=0000, cluster=0013, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=B3, payload=5C D4 D7 E2 B6 1E 01 00 8D 15 00 8E, lastHopLqi=172, lastHopRssi=-57] |  
20:58:17 | ZigBee поиск запущен на 60 секунд
