### ISSUE TITLE
Добавить датчик газа honeywell

### ISSUE THREAD

**Issue by ivan-trifonov-77** [sprut/Hub#129]
Добавьте пожалуйста Добавить датчик газа honeywell для Sprut  стика.
![EE0BDE69-9C15-4473-AE76-6D054626EEF6](https://user-images.githubusercontent.com/59847695/85720626-480aca00-b6f9-11ea-8ef9-52ab03d12b81.jpeg)

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by sprut666666** [comment]
1.6.3
