### ISSUE TITLE
lumi.light.acn014(Aqara LED Bulb T1 Tunable White(ZNLDP13LM)

### ISSUE THREAD

**Issue by pmitry** [sprut/Hub#1291]
Address: 54EF441000359FC5/5782<br><br><b>Structure</b><br><ul><li>Endpoint 1 (COLOR_TEMPERATURE_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 30</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.light.acn014</li><li>0006_DateCode: Jul 29 2021</li><li>0007_PowerSource: 4</li></ul></li><li>0300_ColorControl<ul><li>0003_CurrentX: 24939</li><li>0004_CurrentY: 24701</li><li>0007_ColorTemperature: 308</li><li>00F5_Custom: 5734912</li><li>400B_ColorTemperatureMin: 153</li><li>400C_ColorTemperatureMax: 370</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>00F7_ExtInfo (115F): {160=1, 3=39, 100=0, 5=3, 101=57, 102=308, 8=286, 9=6656, 10=0, 106=425986700, 11=0, 12=10, 154=0}</li><li>0134_Custom (115F): ByteArray [value=04 CD 15 DA 69 40]</li><li>0201_PowerOffMemory (115F): true</li><li>0513_Custom (115F): 6500</li><li>0514_Custom (115F): 2700</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0702_Metering<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0B04_ElectricalMeasurement<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 5734912</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 57</li><li>00F5_Custom: 5734912</li></ul></li><li>0009_Alarms<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li><li>000F_BinaryInputBasic<ul></ul></li><li>0012_MultistateInputBasic<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 21 (COLOR_TEMPERATURE_LIGHT)<ul><li>Input<ul><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 31 (COLOR_TEMPERATURE_LIGHT)<ul><li>Input<ul><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>[4] Sprut zigbee Кабинет Димы (1)</td><td>0006_OnOff</td></tr><tr><td>1</td><td>IEEE</td><td>[4] Sprut zigbee Кабинет Димы (1)</td><td>0008_LevelControl</td></tr><tr><td>1</td><td>IEEE</td><td>[4] Sprut zigbee Кабинет Димы (1)</td><td>0300_ColorControl</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE416649</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>150</td><td>UNKNOWN</td><td>0</td></tr><tr><td>04CF8CDF3C7B2123</td><td>0E1C</td><td>Router</td><td>false</td><td>Sibling</td><td>200</td><td>UNKNOWN</td><td>15</td></tr><tr><td>60A423FFFEFF14B7</td><td>11F5</td><td>Router</td><td>false</td><td>Sibling</td><td>193</td><td>UNKNOWN</td><td>15</td></tr><tr><td>A4C138420BA1857A</td><td>2495</td><td>Router</td><td>false</td><td>Sibling</td><td>167</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D000689B117</td><td>2946</td><td>Router</td><td>false</td><td>Sibling</td><td>215</td><td>UNKNOWN</td><td>15</td></tr><tr><td>60A423FFFEFF16DD</td><td>2C97</td><td>Router</td><td>false</td><td>Sibling</td><td>100</td><td>UNKNOWN</td><td>15</td></tr><tr><td>A4C138E9D5E9BB79</td><td>2F37</td><td>Router</td><td>false</td><td>Sibling</td><td>133</td><td>UNKNOWN</td><td>15</td></tr><tr><td>04CF8CDF3C7B2238</td><td>33DF</td><td>Router</td><td>false</td><td>Sibling</td><td>192</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00028AE3E8</td><td>36E5</td><td>Router</td><td>false</td><td>Sibling</td><td>207</td><td>UNKNOWN</td><td>15</td></tr><tr><td>54EF4410000EAF43</td><td>424E</td><td>Router</td><td>false</td><td>Sibling</td><td>160</td><td>UNKNOWN</td><td>15</td></tr><tr><td>842E14FFFE00C87A</td><td>43E1</td><td>Router</td><td>false</td><td>Sibling</td><td>148</td><td>UNKNOWN</td><td>15</td></tr><tr><td>60A423FFFEFF4BA7</td><td>5454</td><td>Router</td><td>false</td><td>Sibling</td><td>190</td><td>UNKNOWN</td><td>15</td></tr><tr><td>804B50FFFE08DE76</td><td>6F71</td><td>Router</td><td>false</td><td>Sibling</td><td>144</td><td>UNKNOWN</td><td>15</td></tr><tr><td>54EF4410000EB697</td><td>7D62</td><td>Router</td><td>false</td><td>Sibling</td><td>197</td><td>UNKNOWN</td><td>15</td></tr><tr><td>0C4314FFFE9AFCF1</td><td>813E</td><td>Router</td><td>false</td><td>Sibling</td><td>112</td><td>UNKNOWN</td><td>15</td></tr><tr><td>0C4314FFFE9AFCF1</td><td>813E</td><td>Router</td><td>false</td><td>Sibling</td><td>111</td><td>UNKNOWN</td><td>15</td></tr><tr><td>54EF4410000EB2CC</td><td>9FA9</td><td>Router</td><td>false</td><td>Sibling</td><td>78</td><td>UNKNOWN</td><td>15</td></tr><tr><td>0C4314FFFE9AF93F</td><td>B7CF</td><td>Router</td><td>false</td><td>Sibling</td><td>112</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0002FBF42B</td><td>BA8E</td><td>Router</td><td>false</td><td>Sibling</td><td>227</td><td>UNKNOWN</td><td>15</td></tr><tr><td>804B50FFFE08EEEF</td><td>C25A</td><td>Router</td><td>false</td><td>Sibling</td><td>143</td><td>UNKNOWN</td><td>15</td></tr><tr><td>60A423FFFEFF502C</td><td>C320</td><td>Router</td><td>false</td><td>Sibling</td><td>206</td><td>UNKNOWN</td><td>15</td></tr><tr><td>60A423FFFEFF3D0C</td><td>DF15</td><td>Router</td><td>false</td><td>Sibling</td><td>138</td><td>UNKNOWN</td><td>15</td></tr><tr><td>0C4314FFFE9AF7D3</td><td>DFB6</td><td>Router</td><td>false</td><td>Sibling</td><td>192</td><td>UNKNOWN</td><td>15</td></tr><tr><td>804B50FFFE0A6372</td><td>F15C</td><td>Router</td><td>false</td><td>Sibling</td><td>77</td><td>UNKNOWN</td><td>15</td></tr><tr><td>804B50FFFE0A6372</td><td>F15C</td><td>Router</td><td>false</td><td>Sibling</td><td>77</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B0022ED4F10</td><td>F4A6</td><td>Router</td><td>false</td><td>Sibling</td><td>120</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>8726</td><td>813E</td></tr><tr><td>ACTIVE</td><td>F4A6</td><td>F4A6</td></tr><tr><td>ACTIVE</td><td>E29E</td><td>2946</td></tr><tr><td>ACTIVE</td><td>43E1</td><td>43E1</td></tr><tr><td>ACTIVE</td><td>C25A</td><td>C25A</td></tr><tr><td>ACTIVE</td><td>813E</td><td>813E</td></tr><tr><td>ACTIVE</td><td>5454</td><td>5454</td></tr><tr><td>ACTIVE</td><td>2946</td><td>2946</td></tr><tr><td>ACTIVE</td><td>C320</td><td>C320</td></tr><tr><td>ACTIVE</td><td>BA8E</td><td>BA8E</td></tr><tr><td>ACTIVE</td><td>36E5</td><td>36E5</td></tr><tr><td>ACTIVE</td><td>2495</td><td>424E</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>9FA9</td><td>DFB6</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>2F37</td><td>813E</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jul 30 09:13:39 IDT 2022

Лампа сейчас подключена к спрут хабу используя кастомный шаблон от лампы lumi.light.cwac02, изменён только ModelIdentifier(lumi.light.acn014). Но я не уверен, что работает полностью как должна.
Подключал её к родному хабу акара. Для подключения подаём электричество на лампу, она два раза мигнёт, что означает что она готова к подключению(если этого не произошло, то 5 раз включить выключить, лампа мигнёт два раза) и дальше добавляем её в приложении акара. После подключения делал следующее: включал-выключал, подвигал ползунок яркости, поменял температуру. Далее зашёл в настройки лампы и включил сохранение состояния после пропадания питания, проверил что это работает. Дальше в настройках лампы имеются опции для выставления времени включения и отключения, для каждой опции отдельно. Время можно выставить от 0 до 30 секунд с шагом 0,5 секунды. За это время яркость плавно меняется от нуля до того значения которое выставлено для яркости в настройках лампы. Выставил время и включения и выключения 0, понажимал включить выключить. Выставил время и включения и выключения 30 секунд, понажимал включить выключить. По умолчанию время и на включение и на выключение стоит на 1,5 секунды. И похоже что это время зашито на уровне пршивки лампы, потому что при подключении к спрут хабу, где нет возможности выставить время включения и отключения, лампа включается визуально примерно с задержкой 1,5 секунды. 
На данный момент лампы модели ZNLDP13LM все работают не совсем корректно в спрут хабе. Если к лампе применена виртуальная логика менять яркость и температуру по времени и лампа включается и выключается по датчику движения, то в 50 процентов случаев лампа физически не включается при обнаружении движения, хотя в спрут хабе отображается со статусом включена, хотя по факту не горит. Если поставить виртуальную логику менять только яркость, то всё отрабатывает как должно. При этом лампы более старой модели ZNLDP12LM во всех этих случаях отрабатывают корректно.
[2022-07-29_19-20-21.zip](https://github.com/sprut/Hub/files/9225459/2022-07-29_19-20-21.zip)

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/aqara-smart-bulb-t1
