### ISSUE TITLE
GLEDOPTO GL-FL-004P

### ISSUE THREAD

**Issue by svt222** [sprut/Hub#1295]
Address: CC86ECFFFEC7236B/92A4<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11 (EXTENDED_COLOR_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 0</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 2</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-FL-004P</li><li>0006_DateCode: 20211126</li><li>0007_PowerSource: 0</li><li>0008_GenericDeviceClass: 255</li><li>0009_GenericDeviceType: 255</li><li>4000_SWBuildID: 11076804</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 0</li><li>0001_CurrentSaturation: 0</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 17623</li><li>0004_CurrentY: 43739</li><li>0007_ColorTemperature: 250</li><li>0008_ColorMode: 1</li><li>4000_EnhancedCurrentHue: 0</li><li>4001_EnhancedColorMode: 1</li><li>4002_ColorLoopActive: 0</li><li>4003_ColorLoopDirection: 1</li><li>4004_ColorLoopTime: 25</li><li>4005_ColorLoopStartHue: 8960</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 255</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>000F_Options: 0</li><li>4000_StartUpCurrentLevel: 51</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: 60A423FFFE415352</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 18</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4687</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jul 31 17:59:24 MSK 2022

Прожектор Gledopto 
Для сопряжения 5 раз вкл.\выкл.
Telegram: @vsergeev152
Покупал здесь: https://aliexpress.ru/item/1005001665597113.html?gatewayAdapt=glo2rus&sku_id=12000017041019351&spm=a2g0s.12269583.0.0.50d913d4SZcJRL
Версия Zigbee - 
Режим спаривания, сброса - 5 раз вкл.\выкл.
Тип цоколя - Провод (фаза, ноль, земля)
Статус после восстановления питания - Всегда включено

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/zemismart-zigbee-prozhektor
