### ISSUE TITLE
Возможность включения/отключения блоков внутри сценария

### ISSUE THREAD

**Issue by kyruxa** [sprut/Hub#1297]
При создании и отладке сценария было бы удобно иметь возможность включать/отключать блоки внутри сценария.

Например, ставишь оповещение в телеге, чтобы проверить работу сценария. После завершения отладки блок деактивируется и финальный сценарий не спамит сообщениями. Если нужно допилить сценарий - активируешь обратно и тестишь.
Сейчас приходится постоянно вписывать блок кода с уведомлением вручную и потом его удалять.

Или это может быть полезно, если нужно временно исключить одно из условий в сценарии.

Ник в телеге: kirillgrigorov

**Comment by sprut666666** [comment]
вынесено на голосование
