### ISSUE TITLE
GL-S-006P

### ISSUE THREAD

**Issue by makleso6** [sprut/Hub#1298]
Address: A4C1381A1DF8DE33/E2FB<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11 (EXTENDED_COLOR_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0003_HWVersion: 2</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-S-006P</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 10551203</li></ul></li><li>0300_ColorControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>4000_StartUpCurrentLevel: 255</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 352399361</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4687</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4687</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Aug 01 15:00:22 MSK 2022

покупал тут
https://aliexpress.ru/item/1005003650972554.html?businessType=ProductDetail&shareFrom=screenShot&sku_id=12000026657916253&spreadType=socialShare&srcSns=sns_More&tt=MG
Оригинального хаба нет

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/gledopto-gu10-smart-bulb-zigbee
