### ISSUE TITLE
Сортировка аксессуаров

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#13]
Большой список вызывает проблемы, особенно когда два модуля di-dr по 16 контактов, или реле на 6 - все вперемешку. Предлагаю сортировать как в ВБ по топику, а не по ID !

![2019-07-05_13-50-35](https://user-images.githubusercontent.com/1624839/60717999-2df63b80-9f2c-11e9-8de3-9106ca5d56ce.png)

**Comment by diamond5170** [comment]
Есть фильтр, и сортировка. Вероятно, надо распространить сортировку на модель (если еще нет), но по топикам точно сортировать не будем. Кроме того, это техническая версия интерфейса, а для людей будет отдельная версия.
