### ISSUE TITLE
Виртуальный термостат - перепутаны пороги нагрева и охлаждения

### ISSUE THREAD

**Issue by corsaroff** [sprut/Hub#131]
Для виртуального Термостата параметры "Порог охлаждения" и "Порог нагрева" похоже перепутаны где-то. На иконке термостата и в его панели данные отображаются криво: Нагреть до 10 - Охладить до 26
Если выставить параметры в СХ как на скриншоте, то будет "диапазон от 26 до 10" (что тоже криво - от большего к меньшему), но стоит дотронуться до шкалы настройки - опять слетает к "Нагреть до 10 - Охладить до 26".

Telegram - @vklimov

![2020-06-25 20 19 03](https://user-images.githubusercontent.com/31987140/85768104-58cf3600-b721-11ea-89ff-7d3210fc8ad0.jpg)
![2020-06-25 20 18 47](https://user-images.githubusercontent.com/31987140/85768130-5ff64400-b721-11ea-8619-7813e43b7657.jpg)
![2020-06-25 20 18 53](https://user-images.githubusercontent.com/31987140/85768140-62589e00-b721-11ea-8be4-f7fc38f2b5c6.jpg)

**Comment by MakeSimpleOrg** [comment]
Так по идее наоборот надо ставить, порог нагрева 10, порог охлаждения 26.
Т.е. ниже 10 включать обогреватель, выше 26 включать охладитель.
Думаю, проблема лишь в том, что надо запретить ставить порог нагрева выше, чем порог охлаждения.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
