### ISSUE TITLE
прошу добавить устройство на zwave neocoolcam 

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#132]
Node Id | 7
Manufacturer Id | 0258
Device Type | 0003
Device Id | 108C
Basic Class | Routing Slave
Generic Class | Switch Binary
Specific Class | Power Switch Binary
Routing | true
Secure | false
Beaming | true
Listening | true
Frequently Listening | false

Structure
Endpoint 0
V1 SwitchBinary
V2 Version
V1 SwitchAll
V1 PowerLevel
Level: 0
Timeout: 0
V1 Configuration
V2 Association
V2 ManufacturerSpecific
V1 DeviceResetLocally
V1 NoOperation
V1 AssociationGRPInfo
V1 Basic
V1 ZWavePlusInfo

**Comment by bumer0** [comment]
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>7</td></tr><tr><td width=35%>Manufacturer Id</td><td>0258</td></tr><tr><td width=35%>Device Type</td><td>0003</td></tr><tr><td width=35%>Device Id</td><td>108C</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><tr><th>ID</th><th>Label</th><th>Associations</th></tr><br><b>Association Groups</b><br><table border=1 width=100%><tr><td>1</td><td></td><td>[node_1]</td></tr><tr><td>2</td><td></td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 AssociationGRPInfo</li><li>V1 Basic</li><li>V2 Version</li><li>V1 SwitchBinary</li><li>V1 SwitchAll</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 ZWavePlusInfo</li><li>V2 ManufacturerSpecific</li><li>V1 DeviceResetLocally</li><li>V1 Configuration</li><li>V2 Association</li><li>V1 NoOperation</li></ul></li></ul><br>Last update: Thu Jun 25 19:51:05 MSK 2020

**Comment by MakeSimpleOrg** [comment]
Название устройства? Ссылка на страницу производителя?

**Comment by bumer0** [comment]
Neo CoolCam Z-wave Light Switch EU-1  https://szneo.com/en/products/show.php?id=201

есть такой же но двухклавишный добавь пожалуйста, его тоже  
Neo CoolCam Z-wave Light Switch EU-2 https://szneo.com/en/products/show.php?id=196

**Comment by MakeSimpleOrg** [comment]
По каждому устройству необходима информация о структуре.

**Comment by bumer0** [comment]
есть такой же но двухклавишный добавь пожалуйста, его тоже
Neo CoolCam Z-wave Light Switch EU-2 https://szneo.com/en/products/show.php?id=196


<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>24</td></tr><tr><td width=35%>Manufacturer Id</td><td>0258</td></tr><tr><td width=35%>Device Type</td><td>0003</td></tr><tr><td width=35%>Device Id</td><td>108B</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td> Lifeline</td><td>[node_1_1]</td></tr><tr><td>2</td><td> Endpoint 1: Switch Status Report</td><td>[]</td></tr><tr><td>3</td><td> Endpoint 2: Switch Status Report</td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 Basic</li><li>V2 ManufacturerSpecific</li><li>V2 MultiChannel</li><li>V1 SwitchBinary</li><li>V1 NoOperation</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V3 MultiChannelAssociation</li><li>V1 SwitchAll</li><li>V1 DeviceResetLocally</li><li>V2 Association</li><li>V1 ZWavePlusInfo</li><li>V1 Configuration</li><li>V1 AssociationGRPInfo</li><li>V2 Version</li></ul></li><li>Endpoint 1<ul><li>V1 Basic</li><li>V1 SwitchBinary</li><li>V1 ZWavePlusInfo</li><li>V3 MultiChannelAssociation</li><li>V2 Version</li></ul></li><li>Endpoint 2<ul><li>V1 Basic</li><li>V1 SwitchBinary</li><li>V1 ZWavePlusInfo</li><li>V3 MultiChannelAssociation</li><li>V2 Version</li></ul></li></ul><br>Last update: Mon Aug 03 21:37:02 MSK 2020

**Comment by MakeSimpleOrg** [comment]
1.6.4
