### ISSUE TITLE
Есть проблема связанная с виртуальным термостатом и датчиком температуры.

### ISSUE THREAD

**Issue by nikolay812** [sprut/Hub#1322]
Предлагаю продумать логику работы виртуального термостата в случае потери связи с zigbee датчиком температуры. На сегодня, если датчик не в сети, термостат продолжает работать основываясь на последних данных от датчика, предлагаю в случае потери связи, как то отображать это в виртуальном термостате, вплоть до отключения термостата, чтобы было очевидно, что в доме есть проблема, а в карту сети zigbee заходить каждый раз не будешь.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
