### ISSUE TITLE
TS000F _TZ3000_mx3vgyea (реле)

### ISSUE THREAD

**Issue by beeqw** [sprut/Hub#1326]
Address: A4C1388958826460/4648<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HWVersion: 0</li><li>0004_ManufacturerName: _TZ3000_mx3vgyea</li><li>0005_ModelIdentifier: TS000F</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 0122052017</li></ul></li><li>E000_ManufacturerSpecific<ul><li>D001_Custom: ByteArray [value=00 06]</li><li>D002_Custom: ByteArray [value=00 0A]</li><li>D003_Custom: AAAA</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>E001_ManufacturerSpecific<ul><li>D030_Custom: 0</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>8000_MultipleClick: false</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 2</li></ul></li><li>000A_Time<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><table border=1 width=100%><tr><th>NWK</th><th>IEEE</th><th>Name</th><th>Type</th></tr><tr><td>489F</td><td>A4C138EC8AC32AA2</td><td>Датчик касания</td><td>End Device</td></tr></table><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>A4C13865FB5AFA19</td><td>7CDA</td><td>Router</td><td>false</td><td>Parent</td><td>77</td><td>UNKNOWN</td><td>1</td></tr><tr><td>84FD27FFFE8A4AE6</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>150</td><td>UNKNOWN</td><td>0</td></tr><tr><td>A4C138EC8AC32AA2</td><td>489F</td><td>End Device</td><td>true</td><td>Child</td><td>217</td><td>UNKNOWN</td><td>3</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Aug 13 08:49:47 MSK 2022

Покупалось тут - https://aliexpress.ru/item/1005002311216920.html

Проблема в том что при наличии в каталоге тут https://sprut.ai/catalog/item/mini-pereklyuchatel-16a-zigbee-3-0-diy-1 это устройство при спаривании выдает ошибку "нет шаблона"

**Comment by ashlepov** [comment]
Заработало с шаблоном от Tuyatec  _TZ3000_1hwjutgo

[TS000F_relay__TZ3000_mx3vgyea.zip](https://github.com/sprut/Hub/files/9331070/TS000F_relay__TZ3000_mx3vgyea.zip)
