### ISSUE TITLE
Верстка плохо адаптируется к экрану телефона

### ISSUE THREAD

**Issue by maxfaq** [sprut/Hub#133]
Имею датчик Lifecontrol MCLH-08
В разделе "Аксессуары" наблюдаю некорректное отображение

> Как тип датчика залазит на значение датчика (см. Скрин 1)

> имя датчика обрезается (см.скрин 2)

![Screenshot_20200625-234658~3](https://user-images.githubusercontent.com/55385391/85794500-6b586800-b73f-11ea-931d-ac97ef2bb32f.jpg)
![Screenshot_20200625-234648~3](https://user-images.githubusercontent.com/55385391/85794507-6c899500-b73f-11ea-85e9-f7ec5689b42a.jpg)

Версия: SprutHub 1,6,0b
Телефон: Oneplus 8 (Android 10)
Ник в Telegram: Maxim Shcheniatskiy

**Comment by diamond5170** [comment]
Мобильная версия не поддерживается и поддерживаться в ближайшее время не будет. Открывайте десктопную.
