### ISSUE TITLE
Более универсальное отображение для девайсов WBIO-DI-...

### ISSUE THREAD

**Issue by DjScava** [sprut/Hub#134]
** Максимально подробное описание предложения.**
при добавлении девайсов вида WBIO-DI-... ( в частности WBIO-DI-WD-14) они добавляются как WBIO-DI-HVD нужно сделать более универсально название и возможно несколько переработать аксессуары. (обработку мультинажатий например)

** Дополнительные материалы **
![image](https://user-images.githubusercontent.com/48600162/85798162-a8275d80-b745-11ea-9cbd-90ec7e5c80be.png)
![image](https://user-images.githubusercontent.com/48600162/85798188-b8d7d380-b745-11ea-9af9-ed4f8752064a.png)

**Comment by sprut666666** [comment]
1.6.3
