### ISSUE TITLE
Z-Wave Fibaro FGS212  - ошибка в Template

### ISSUE THREAD

**Issue by kvbr156** [sprut/Hub#135]
При подключении нового устройства Fibaro FGS212 к контроллеру Z-Wave это устройство обнаруживается, но обозначается как неизвестное.
В логе идентификатор производителя указан верный, а вот идентификатор устройства прочитан 0402:4002.
В файле темплейта есть варианты идентификатора 0401:100A и 0402:1002.
После добавления идентификатора 0402:4002 в темплейт устройство распозналось правильно и полностью функционирует.

Предлагаю внести коррекцию в темплейт FGDS212.json
Спасибо.

  - Версия SH: 1.6.0b

**Comment by MakeSimpleOrg** [comment]
1.6.4
