### ISSUE TITLE
TS0505B Bulb HA Zigbee2mqtt not supported 

### ISSUE THREAD

**Issue by azeitona69** [sprut/Hub#1356]
Dear all,

I have bought new Zigbee 18w RGBCCT bulbs and trying to connect them to my Home Assistant instance via Zigbeemqtt .
I managed to connect the new bulb but I get an "unsupported" error message out of it.
FYI, I already have multiple other devices working fine there, mainly switches. So the Zigbee2mqtt interface seems out of question.

I've seen that it could be possible to update the zigbee2mqtt database to solve the issue, but I'm already playing at the edge of my skills and don't want to create any additional issue ! 

I would appreciate some help.
Here below are the bulb parameters I see in HA

thanks for support
AZ
--------------------

Friendly name
0xa4c138d70120b130
Description
Last seen
N/A
Availability
[Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type
Router
Zigbee Model
TS0505B
Zigbee Manufacturer
_TZ3210_r5afgmkl
Support status
Not supported

IEEE Address
0xa4c138d70120b130
Network address
0xF492

**Comment by sprut666666** [comment]
Unfortunately, we do not support Home Assistant and Zigbee2Мqtt, we only support https://spruthub.ru/device/sprut-hub-covid-edition.html
