### ISSUE TITLE
Zigbee_TZ3000_4fjiwweb (button+dimmer)

### ISSUE THREAD

**Issue by AlexSinttig** [sprut/Hub#1358]
Address: 540F57FFFE2E3E65/A824<br><br><b>Structure</b><br><ul><li>Endpoint 1 (DIMMER_SWITCH)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 67</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_4fjiwweb</li><li>0005_ModelIdentifier: TS004F</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFFE_Custom: 0</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 176</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>8004_OperationMode: 0</li></ul></li></ul></li><li>Output<ul><li>0300_ColorControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Sep 01 22:59:49 YEKT 2022

Кнопка с диммером, ссылка на магазин https://aliexpress.ru/item/1005003420464054.html?_ga=2.233399837.204121835.1662053438-1524510256.1662053438&sku_id=12000026969407909&spm=a2g39.buyer_reviews.tabs.5.355b4aa6ckD57Y

**Comment by Batyushin** [comment]
https://github.com/sprut/Hub/issues/1164 дубль
