### ISSUE TITLE
Добавить темплейт Z-Wave датчика движения NEO Coolcam

### ISSUE THREAD

**Issue by Stunt4man** [sprut/Hub#137]
Есть две модификации с датчиком температуры и без.
**это без температуры:**

Node Id | 6
-- | --
Manufacturer Id | 0258
Device Type | 0003
Device Id | 1083
Basic Class | Routing Slave
Generic Class | Sensor Notification
Specific Class | Notification Sensor
Routing | true
Secure | false
Beaming | true
Listening | false
Frequently Listening | false

Structure
Endpoint 0
V0 ManufacturerSpecific
V0 SensorBinary
V0 Association
V0 Basic
V0 Alarm
V0 Battery
V0 SensorMultiLevel
V0 Version
V0 WakeUp
V0 ZWavePlusInfo
V0 DeviceResetLocally
V0 AssociationGRPInfo
V0 Configuration
V0 PowerLevel
Level: 0
Timeout: 0
V1 NoOperation

**Comment by MakeSimpleOrg** [comment]
1.6.4
