### ISSUE TITLE
Добавить поддержку кнопки беспроводной кнопки Aqara

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#138]
https://v2.sprut.ai/catalog/item/aqara-wireless-switch-2
WXKG12LM
Телеграмм:
@UskovvNA

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by sprut666666** [comment]
Не предоставлена полная информация
