### ISSUE TITLE
Удаляется прошивка стика при обновлении на WB (?)

### ISSUE THREAD

**Issue by qwedy** [sprut/Hub#139]
** Подробное описание ошибки **
При обновлении SprutHub 1.6.0b -> 1.6.1b на WB поломалась прошивка Sprut stick 2 pro.
Светодиод стика не горит, стик спрутхабом не определяется, прошивка какая-то на стике есть (перешивал с магнитом).

Накатил снова прошивку 6.7.6.0, 
втыкнул в WB, 
переткнул галку контроллера zigbee
через полминуты началось обновление стика -- и всё прошло успешно [http://i.imgur.com/WdtmiZb.png](http://i.imgur.com/WdtmiZb.png)

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1) Ткнул обновить в вебморде спрутхаба
2) Примерно через полминуты обновил страницу (спрутхаб ещё не загрузился)
3) Спустя 1,5 минуту после перезагрузки спрутхаба ткнул поиск девайсов, 
4) Переткнул галку зигби контроллера
5) спустя 15 минут пошёл прошивать стик
[http://i.imgur.com/Dp2E2dO.png](http://i.imgur.com/Dp2E2dO.png)

** Ожидаемое поведение **
чего-то такого и ожидал

** Пожалуйста, заполните следующую информацию: **
  - Версия SprutHub: 1.6.0b -> 1.6.1b
  - Версия прошивки стика: 6.7.6.0 -> 6.7.6.1

**Comment by droni4** [comment]
Аналогичная ситуация

**Comment by sprut666666** [comment]
1.6.4
