### ISSUE TITLE
Прошу добавить поле с комментарием к устройству ( датчику) для уточнения места размещения внутри комнаты или щитка

### ISSUE THREAD

**Issue by EShchepilov** [sprut/Hub#1392]
** Максимально подробное описание предложения.**
Четкое и краткое описание предложения, так чтобы вас смог понять "глупый" человек.

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
вынесено на голосование
