### ISSUE TITLE
TZE200_bkkmqmyo

### ISSUE THREAD

**Issue by Nikkel15** [sprut/Hub#1397]
Address: 84B4DBFFFEB8AAA9/D34C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>EF00_ManufacturerSpecific<ul><li>0001_Custom: 0</li><li>0006_Custom: ByteArray [value=00 00 00 00 00 00 00 00 03 E8 00 00 00 08 D4]</li><li>0009_Custom: 0</li><li>0010_Custom: false</li><li>0011_Custom: ByteArray [value=00 00 00 00 00 00 00 00 00 00 00 64 00 01 0E 00 00 AA 00 00 00 00 00 0A 00 00 00 00 00 00]</li><li>0012_Custom: ByteArray [value=00 05 00 64 00 05 00 1E 00 3C 00 00 00 00 00 00 00]</li><li>0065_Custom: 0</li><li>0066_Custom: 0</li><li>0067_Custom: 0</li><li>0069_Custom: 4997</li><li>006D_Custom: 0</li><li>006E_Custom: 0</li><li>006F_Custom: 1000</li></ul></li><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 65</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZE200_bkkmqmyo</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: �s�*�t�*e�t�*�t�*</li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>842E14FFFE6DB6DC</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>200</td><td>UNKNOWN</td><td>0</td></tr><tr><td>54EF44100018E8FF</td><td>37E8</td><td>Router</td><td>false</td><td>Sibling</td><td>124</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0003F46D0C</td><td>5E71</td><td>Router</td><td>false</td><td>Sibling</td><td>102</td><td>UNKNOWN</td><td>15</td></tr><tr><td>9035EAFFFEBA7A55</td><td>E14D</td><td>Router</td><td>false</td><td>Parent</td><td>255</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Sep 17 12:10:12 MSK 2022

В каталоге указано как совместимое со SprutHub
https://sprut.ai/catalog/item/tomzn-hiking-dds238-2-zigbee-rele-s-energomonitoringom

**Comment by Batyushin** [comment]
Дубликат https://github.com/sprut/Hub/issues/1445
