### ISSUE TITLE
Статус девайса No response

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#14]
Если удалить девайс из WB
_mqtt-delete-retained "/devices/wb-mrm2_114/#"_ , то в приложении ДОМ, визуально, ничего не меняется, надо бы посылать статус NO RESPONSE. При этом в логах есть ошибка чтения.

![2019-07-05_13-47-05](https://user-images.githubusercontent.com/1624839/60718893-ae1da080-9f2e-11e9-8bf9-13fa8a19e9aa.png)

**Comment by sprut666666** [comment]
mosquitto_sub -t "/devices/+/controls/+/meta/error" -v
