### ISSUE TITLE
Не правильно отображается Выключатель Свет в ХоумКит

### ISSUE THREAD

**Issue by Stunt4man** [sprut/Hub#140]
Заметил такой глюк: свет на фибаро димер 2 в хоумкит, при автоматизации по датчику движения ( настроена в хоумкит) свет физически включается, но отображение в ките остается выкл. Если свернуть кит и открыть то после возвращения отображается правильно. По выключателю отображение отрабатывает четко. В спрутхабе тоже правильно отрабатывает.

![IMG_2011](https://user-images.githubusercontent.com/31995081/85904173-be4e2000-b810-11ea-94c7-40d60663b68c.jpg)

**Comment by MakeSimpleOrg** [comment]
Это баг в хомките.
