### ISSUE TITLE
Время на термостате отстаёт на час

### ISSUE THREAD

**Issue by Co1dSUN** [sprut/Hub#1401]
При летнем времени на термостатах отображается время на час назад. При установке правильного времени непосредственно на термостате, через какое-то время часы снова начинают оставать ровно на час.

Взять любой термостат, например https://sprut.ai/catalog/item/moeshouse-moes-thermostat-electric-floor-2
Спарить с СХ, дождаться, когда термостат получит инфо о времени с СХ.

Время должно совпадать с актуальным

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
