### ISSUE TITLE
Добавить поддержку трёх устройств z-wave

### ISSUE THREAD

**Issue by AGKulikov** [sprut/Hub#141]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/67376842/85916997-c46aed80-b85e-11ea-8839-c2a54307eb88.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/67376842/85917009-e1072580-b85e-11ea-8393-47bd4ae07525.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/67376842/85917012-ebc1ba80-b85e-11ea-99f9-212847c99abf.png">

**Comment by MakeSimpleOrg** [comment]
TKB Home TZ68
TKB Home TZ78
Philio PAN03

Добавил все три. На будущее - одно устройство один репорт. И всю информацию.
