### ISSUE TITLE
Кран tuya. Добавить устройство

### ISSUE THREAD

**Issue by denis86111** [sprut/Hub#145]
81AB/EC1BBDFFFE803A80 |   | UNKNOWN | _TYZB01_rifa0wlb | TS0011 | NO_TEMPLATE

![369544C8-6C87-4DDC-BD28-4139B5B9004F](https://user-images.githubusercontent.com/48566084/85927871-8cd96100-b8b1-11ea-942e-4ef939382586.jpeg)

**Comment by denis86111** [comment]
Добавить кубик aqara
0898/00158D00027850E8 |   | ONLINE | LUMI | lumi.sensor_cube.aqgl01 | NO_TEMPLATE

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by sprut666666** [comment]
1.6.3
