### ISSUE TITLE
Виртуальные устройства WB

### ISSUE THREAD

**Issue by rufusgor** [sprut/Hub#146]
** Подробное описание ошибки **
При создании виртуального устройства через правила WB, не появляются в СХ.

** Ожидаемое поведение **
Автоматическое добавление виртуальных устройств.

** Пожалуйста, заполните следующую информацию: **
  - Версия: [SH 1.6.1b]

**Comment by sprut666666** [comment]
Если что-то делается руками в вб, это так же РУКАМИ переносится в SH.
