### ISSUE TITLE
LED Bulb 6 Multi-Color (ZWA002)

### ISSUE THREAD

**Issue by MevilVoronkevich** [sprut/Hub#1466]
AEON Labs - Unknown
    Node Id 8
    Manufacturer Id 0371
    Device Type 0003
    Device Id 0002
    App Version 2.5
    Basic Class Routing Slave
    Generic Class Switch MultiLevel
    Specific Class Power Switch MultiLevel 
    Routing true 
    Secure false 
    Beaming true 
    Listening true 
    Frequently Listening false 
    
Association Groups 
    ID  Label Associations Max
    1   Lifeline [1]                  1 

Structure

Endpoint 0
V2 Association
V2 SwitchMultiLevel
Level: 99
V2 Version
V1 Basic
Value: 0
V1 Security
V1 NoOperation
V2 ManufacturerSpecific
V1 SwitchColor
V1 FirmwareUpdateMD
V1 PowerLevel
Level: 0
Timeout: 0
V1 AssociationGRPInfo
V1 ZWavePlusInfo
V1 DeviceResetLocally
V1 Configuration
V1 SwitchAll

https://aeotec.freshdesk.com/support/solutions/articles/6000202221-led-bulb-6-multi-color-user-guide-
https://aeotec.freshdesk.com/helpdesk/attachments/6072848203

**Comment by MevilVoronkevich** [comment]
Прикрепляю "самописный" шаблон. Но с ним не работает управление цветом.
[ZWA002.txt](https://github.com/sprut/Hub/files/9843795/ZWA002.txt)

В инструкции есть такое:
![Снимок экрана 2022-10-22 в 10 36 56](https://user-images.githubusercontent.com/39233318/197327164-d8dcffeb-a55d-4e29-91b8-38d0b8f1d875.png)

**Comment by SmartHaven** [comment]
Добавлено в r219 шаблонов.
