### ISSUE TITLE
Нет Двойного нажатия у Universal Dimmer 2 (FGD-212) и Double Switch 2(FGS-223) Z-Wave

### ISSUE THREAD

**Issue by GDaurov** [sprut/Hub#1490]
** Подробное описание ошибки **

СпрутХаб не определяет Двойное нажатие у реле и диммера
 Universal Dimmer 2 (FGD-212) и Double Switch 2(FGS-223)

** Как воспроизвести ? **
В сценариях нет возможности нанять на эти устройства Двойное нажатие.

Видимо, они не прописаны в шаблонах 

** Ожидаемое поведение **
Возможность управления с использованием Двойного нажатия

** Пожалуйста, заполните следующую информацию: **
СХ 1.9.3 ревизия 8086

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
