### ISSUE TITLE
zigbee 4x канальное реле + 433

### ISSUE THREAD

**Issue by KVolkov87** [sprut/Hub#1500]
zigbee 4x канальное реле + 433

Address: 00124B00226B12E2/284B<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 4</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 4</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li></ul></li></ul></li><li>Endpoint 3 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li></ul></li></ul></li><li>Endpoint 4 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB?SW04</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SWBuildID: 1.0.3</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415683</td><td>0000</td><td>Coordinator</td><td>true</td><td>Parent</td><td>132</td><td>UNKNOWN</td><td>0</td></tr><tr><td>000D6F00131532DC</td><td>671C</td><td>Router</td><td>true</td><td>Unknown</td><td>40</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00124B00232831DA</td><td>2352</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00158D0002A8D727</td><td>D14D</td><td>Router</td><td>true</td><td>Unknown</td><td>126</td><td>UNKNOWN</td><td>255</td></tr><tr><td>000D6F00131844CE</td><td>CCF0</td><td>Router</td><td>true</td><td>Unknown</td><td>95</td><td>UNKNOWN</td><td>255</td></tr><tr><td>588E81FFFEFF6046</td><td>E9AF</td><td>Router</td><td>true</td><td>Unknown</td><td>106</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE417525</td><td>494D</td><td>Router</td><td>true</td><td>Unknown</td><td>5</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE69C38C</td><td>94F4</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE417452</td><td>9CC0</td><td>Router</td><td>true</td><td>Unknown</td><td>27</td><td>UNKNOWN</td><td>255</td></tr><tr><td>A4C1387FB395DC22</td><td>47FE</td><td>Router</td><td>true</td><td>Unknown</td><td>82</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE69C393</td><td>6C93</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>A4C1386CE0D1F3AB</td><td>3362</td><td>Router</td><td>true</td><td>Unknown</td><td>93</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00124B002328C873</td><td>4329</td><td>Router</td><td>true</td><td>Unknown</td><td>52</td><td>UNKNOWN</td><td>255</td></tr><tr><td>0C4314FFFE9AF7FA</td><td>FE4A</td><td>Router</td><td>true</td><td>Unknown</td><td>2</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE4174BC</td><td>1089</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE41739A</td><td>111B</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr><tr><td>54EF44100002EB38</td><td>F06F</td><td>Router</td><td>true</td><td>Unknown</td><td>47</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>47FE</td><td>47FE</td></tr><tr><td>ACTIVE</td><td>6990</td><td>CCF0</td></tr><tr><td>DISCOVERY_FAILED</td><td>494D</td><td>FFFE</td></tr><tr><td>ACTIVE</td><td>D14D</td><td>D14D</td></tr><tr><td>ACTIVE</td><td>3142</td><td>671C</td></tr><tr><td>ACTIVE</td><td>94F4</td><td>CCF0</td></tr><tr><td>ACTIVE</td><td>E9AF</td><td>E9AF</td></tr><tr><td>ACTIVE</td><td>111B</td><td>F06F</td></tr><tr><td>ACTIVE</td><td>4329</td><td>4329</td></tr><tr><td>ACTIVE</td><td>CCF0</td><td>CCF0</td></tr><tr><td>ACTIVE</td><td>3362</td><td>E9AF</td></tr><tr><td>ACTIVE</td><td>671C</td><td>671C</td></tr><tr><td>ACTIVE</td><td>6C93</td><td>671C</td></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>441B</td><td>671C</td></tr><tr><td>DISCOVERY_FAILED</td><td>F06F</td><td>FFFE</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Nov 17 07:33:44 YEKT 2022

Каталог Sprut.Hub: https://sprut.ai/catalog/item/4h-kanalnyy-releynyy-modul-aubess-5-32v
Ссылка на Aliexpress: https://aliexpress.ru/item/1005003903297725.html?spm=a2g0o.order_list.0.0.21efa396nMqQ0G&gatewayAdapt=glo2rus&sku_id=12000028523712186

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/4h-kanalnyy-releynyy-modul-aubess-5-32v
