### ISSUE TITLE
Сохранять статус логических сценариев

### ISSUE THREAD

**Issue by MaximSidorov777** [sprut/Hub#1502]
Предлагаю сохранять параметры стандартных логических сценариев Sprut.Hub, которые пересоздаются при загрузке хаба.

Например, у меня активно используется Сигнализация, но стандартный сценарий меня не устраивает. Каждый раз приходится делать его неактивным, потому что датчики реагируют на кота и запускаются уведомления, сирены, смски и пр. :)

<img width="561" alt="Снимок экрана 2022-10-31 в 17 33 38" src="https://user-images.githubusercontent.com/86353917/199033182-e270e00c-759f-4789-96e1-4d5d1e008c72.png">

<img width="793" alt="Снимок экрана 2022-10-31 в 17 33 44" src="https://user-images.githubusercontent.com/86353917/199033193-146b4870-6429-4c3c-bb0d-aa5661bb212f.png">

**Comment by sprut666666** [comment]
Создайте вирт девайс сигнализация и свою логику к нему
