### ISSUE TITLE
темплейт WB-MRGBW-D ModBus доработка, старая прошивка

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#153]
** Максимально подробное описание предложения.**
Немного доработал темплейт для WB-MRGBW-D, старая прошивка блока, работа по ModBus
Предлагаю добавить в последующую сборку.

** Дополнительные материалы **

Добавлена возможность управления кнопками, отвязать от каналов и привязать

![image](https://user-images.githubusercontent.com/60096192/86209847-7ae31100-bb84-11ea-967b-ad553eb37bff.png)

[WB-MRGBW-D.zip](https://github.com/sprut/Hub/files/4856040/WB-MRGBW-D.zip)

**Comment by sprut666666** [comment]
1.6.3 спасибо
