### ISSUE TITLE
Двойные выключатели в одинарные

### ISSUE THREAD

**Issue by GDaurov** [sprut/Hub#1534]
При присоединении двойных (тройных и тд.) реле (выключателей)
они идут как одно устройство, с "клавишами внутри"

В этом случае проблематично разнести такой выключатель по комнатам.

Например: в коридоре двойной выключатель, который на ванную и кухню (иногда и третий на туалет)
Так вот, при установке двойного реле - это будет одно устройство с двумя выключателями, которое можно приписать только к одной комнате.
В этом случае надо заморачиваться с созданием виртуального устройства, получить два независимых устройства и уже потом раскидывать

**Предложение:**

В настройках устройства сделать возможность сделать его "раздельным".
И (например после перезагрузки) вместо одного выключателя - два одинарных.

Чтобы вопрос решался одной галочкой.

Бывают что ещё с измерением энергии.
Разделять по порядку ID  - первое значение идёт первому выключателю, второе - второму и т.д.
Именно такая схема реализована у Vera.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
