### ISSUE TITLE
темплейты WB-MSW, WB-MSW2, WB-MSW3 ModBus доработка

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#154]
** Максимально подробное описание предложения.**
Сделал отдельные темлейты к устройствам WB-MSW, WB-MSW2, WB-MSW3
Предлагаю добавить в последующую сборку.

** Дополнительные материалы **

WB-MSW у меня нет этого устройства проверить работоспособность не могу, но во всяком случае должно определиться в системе
WB-MSW2 устройство определяется в спрутхабе и появляется в устройствах контроллера и появляется в аксессуарах, набор функционала в аксессуарах не менялся, сейчас он аналогичен  WB-MSW3. В дальнейшем можно переписать.
WB-MSW3 теперь определяется как WB-MSW3, все остальное осталось как и было ранее.

![image](https://user-images.githubusercontent.com/60096192/86210669-090bc700-bb86-11ea-9ec2-a925e66bd8c4.png)

В архиве три темплейта.
[WB-MSW.zip](https://github.com/sprut/Hub/files/4856088/WB-MSW.zip)

**Comment by sprut666666** [comment]
1.6.3  спасибо
