### ISSUE TITLE
_TZE200_3towulqd TS0601 Мини-детектор движения с пассивным инфракрасным датчиком движения и ярким освещением

### ISSUE THREAD

**Issue by EShchepilov** [sprut/Hub#1552]
Tuya 2 in 1 Zigbee Mini PIR Motion Detector + Bright Lux ZG-204ZL
https://githubplus.com/dresden-elektronik/deconz-rest-plugin/issues/6158

в режиме отладки zigbee
дает на движение :
<html>
<body>

23:51:20 | Controllers.ZigBee.ZigBee_1 | <-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=FC, Input, seq=63, records=[[0001_Custom, value=0, type=TUYA_ENUMERATION_8_BIT]], payload=00:3F:01:04:00:01:00]
-- | -- | --
23:51:17 | Controllers.ZigBee.ZigBee_1 | <-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=FB, Input, seq=62, records=[[0001_Custom, value=1, type=TUYA_ENUMERATION_8_BIT]], payload=00:3E:01:04:00:01:01]

</body>
</html>

Это интенсивность света:
<html>
<body>

23:56:58 | Controllers.ZigBee.ZigBee_1 | <-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=25, Input, seq=103, records=[[000C_Custom, value=634, type=TUYA_32_BIT_INTEGER]], payload=00:67:0C:02:00:04:00:00:02:7A]
-- | -- | --
23:56:52 | Controllers.ZigBee.ZigBee_1 | <-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=22, Input, seq=100, records=[[000C_Custom, value=0, type=TUYA_32_BIT_INTEGER]], payload=00:64:0C:02:00:04:00:00:00:00]

</body>
</html>
<body>

Название | Значение
-- | --
Производитель | _TZE200_3towulqd
Модель | TS0601
Прошивка | 72
WEB Build | 1.2.5
API Build | 1.9.4 (8533)

</body>
</html>

Куплен на https://sl.aliexpress.ru/p?key=etVNxDK

Версия ZigBee:
3.0
Функция роутера ZigBee:
Конечное устройство
Режим спаривания, сброса:
5 сек нажатие
Цвет устройства:
Белый
Тип датчика:
Движение
Источник питания:
От батареиCR2450

<html>
<body>

ZigBee: Нет шаблона _TZE200_3towulqd TS0601
--

</body>
</html>
Address: A4C138B9F25A6656/974C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 40</li><li>0002_ZoneStatus: 0</li><li>0010_IASCIEAddress: 9035EAFFFE600DCE</li><li>0011_ZoneID: 255</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 66</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZE200_3towulqd</li><li>0005_ModelIdentifier: TS0601</li><li>0007_PowerSource: 3</li></ul></li><li>EF00_ManufacturerSpecific<ul><li>0001_Custom: 1</li><li>0004_Custom: 100</li><li>0009_Custom: 2</li><li>000A_Custom: 0</li><li>000C_Custom: 562</li></ul></li><li>0001_PowerConfiguration<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: ?1</li><li>0002_CurrentFileVersion: 66</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: ?1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Mon Nov 14 16:41:25 MSK 2022

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/mini-pir-sensor

**Comment by EShchepilov** [comment]
> Tuya 2 in 1 Zigbee Mini PIR Motion Detector + Bright Lux ZG-204ZL https://githubplus.com/dresden-elektronik/deconz-rest-plugin/issues/6158
> 
> в режиме отладки zigbee дает на движение :
> 
> 23:51:20	Controllers.ZigBee.ZigBee_1	<-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=FC, Input, seq=63, records=[[0001_Custom, value=0, type=TUYA_ENUMERATION_8_BIT]], payload=00:3F:01:04:00:01:00]
> 23:51:17	Controllers.ZigBee.ZigBee_1	<-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=FB, Input, seq=62, records=[[0001_Custom, value=1, type=TUYA_ENUMERATION_8_BIT]], payload=00:3E:01:04:00:01:01]
> Это интенсивность света:
> 
> 23:56:58	Controllers.ZigBee.ZigBee_1	<-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=25, Input, seq=103, records=[[000C_Custom, value=634, type=TUYA_32_BIT_INTEGER]], payload=00:67:0C:02:00:04:00:00:02:7A]
> 23:56:52	Controllers.ZigBee.ZigBee_1	<-- 0002_ReportDeviceStatus [EF00_ManufacturerSpecific: 793F/1 -> 0000/1, TID=22, Input, seq=100, records=[[000C_Custom, value=0, type=TUYA_32_BIT_INTEGER]], payload=00:64:0C:02:00:04:00:00:00:00]
> Название	Значение
> Производитель	_TZE200_3towulqd
> Модель	TS0601
> Прошивка	72
> WEB Build	1.2.5
> API Build	1.9.4 (8533)
> Куплен на https://sl.aliexpress.ru/p?key=etVNxDK
> 
> Версия ZigBee: 3.0 Функция роутера ZigBee: Конечное устройство Режим спаривания, сброса: 5 сек нажатие Цвет устройства: Белый Тип датчика: Движение Источник питания: От батареиCR2450
> 
> ## ZigBee: Нет шаблона _TZE200_3towulqd TS0601
> Address: A4C138B9F25A6656/974C
> 
> Structure
> * Endpoint 1 (IAS_ZONE)* Input* 0500_IasZone* 0000_ZoneState: 0* 0001_ZoneType: 40* 0002_ZoneStatus: 0* 0010_IASCIEAddress: 9035EAFFFE600DCE* 0011_ZoneID: 255* 0000_Basic* 0001_ApplicationVersion: 66* 0003_HWVersion: 1* 0004_ManufacturerName: _TZE200_3towulqd* 0005_ModelIdentifier: TS0601* 0007_PowerSource: 3* EF00_ManufacturerSpecific* 0001_Custom: 1* 0004_Custom: 100* 0009_Custom: 2* 000A_Custom: 0* 000C_Custom: 562* 0001_PowerConfiguration* Output* 0019_OtaUpgrade* 0000_UpgradeServerID: FFFFFFFFFFFFFFFF* 0001_FileOffset: ?1* 0002_CurrentFileVersion: 66* 0003_CurrentZigBeeStackVersion: 2* 0004_DownloadedFileVersion: ?1* 0005_DownloadedZigBeeStackVersion: 65535* 0006_ImageUpgradeStatus: 0* 0007_ManufacturerID: 4417* 0008_ImageTypeID: 65535* 0009_MinimumBlockRequestPeriod: 0* 000A_Time
> 
> 
> 
> Binding table
> 
> Group membership
> 
> Associated devices
> 
> Neighbor table
> 
> Routing table
> 
> Node Descriptor
> Aps Flags	0
> Frequency Bands	[FREQ_2400_MHZ]
> Server Capabilities	[]
> Buffer Size	66
> Incoming Transfer Size	66
> Logical Type	End Device
> Mac Capabilities	[REDUCED_FUNCTION_DEVICE]
> Manufacturer Code	4417
> Out Going Transfer Size	66
> Stack Compliance	21
> 
> Power Descriptor
> Current Power Mode	RECEIVER_ON_STIMULATED
> Available Power Sources	[RECHARGABLE_BATTERY]
> Current Power Source	RECHARGABLE_BATTERY
> Power Level	MEDIUM
> 
> 
> 
> Last update: Mon Nov 14 16:41:25 MSK 2022

не работает в данном template - батарейка (всегда 0%)
так же нет сервиса - датчик освещенности

**Comment by EShchepilov** [comment]
Закрыто преждевременно

**Comment by ashlepov** [comment]
Удалось подключить его к spruthub? 

> Закрыто преждевременно
