### ISSUE TITLE
Ошибка в тригерах.

### ISSUE THREAD

**Issue by Stunt4man** [sprut/Hub#156]
![IMG_2036](https://user-images.githubusercontent.com/31995081/86237728-f94fab00-bba4-11ea-8025-9c18a7625273.PNG)
Вот такой триггер по значению "Любому значению" включает яркость всегда на 1% вместо 99 как на этом примере. Процент не важно какой установишь всегда включает на 1. По ЗАКРЫТО , ОТКРЫТО все работает норм. Лампа Икея.

**Comment by sprut666666** [comment]
1.6.4
