### ISSUE TITLE
test

### ISSUE THREAD

**Issue by sprut666666** [sprut/Hub#157]
Address: 00158D000428E3C0/2A54<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 0</li><li>0001_ApplicationVersion: 1</li><li>FF01_Custom: {3=33, 100=false, 5=18, 101=false, 7=0, 8=4644, 9=256, 110=255, 111=255, 148=99, 149=0.03437500074505806, 150=2343.403076171875, 151=0.2625759541988373, 152=61.48112487792969, 155=0}</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 18</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.relay.c2acn01</li><li>0007_PowerSource: 4</li></ul></li><li>0010_BinaryOutputBasic<ul><li>0100_ApplicationType: 67109376</li><li>0051_OutOfService: false</li><li>0004_ActiveText: ON</li><li>0055_PresentValue: false</li><li>FF06_Custom: true</li><li>001C_Description: CHANNEL1</li><li>002E_InactiveText: OFF</li><li>006F_StatusFlags: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0010_MainsAlarmMask: 0</li><li>0020_BatteryVoltage: 0</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0B04_ElectricalMeasurement<ul><li>0300_AcFrequency: 65535</li><li>0000_MeasurementType: 1</li><li>0505_RmsVoltage: 65535</li><li>0508_RmsCurrent: 65535</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>F000_State: 237655047</li></ul></li><li>000A_Time<ul><li>0000_Time: �������	�</li></ul></li><li>000C_AnalogInputBasic<ul><li>0041_MaxPresentValue: 2500.0</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0.0</li><li>001C_Description: CHANN</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0010_BinaryOutputBasic<ul><li>0100_ApplicationType: 67109377</li><li>0051_OutOfService: false</li><li>0004_ActiveText: ON</li><li>0055_PresentValue: false</li><li>001C_Description: CHANNEL2</li><li>002E_InactiveText: OFF</li><li>006F_StatusFlags: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>F000_State: 117440520</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br>Last update: Thu Jul 02 23:15:40 MSK 2020

**Comment by diamond5170** [comment]
NWK | IEEE | Name | Type
-- | -- | -- | --
C326 | 00158D0002019E00 | Датчик температуры и влажности | End Device
DC07 | 00158D00023A8763 | Программируемая кнопка | End Device
59EA | 00158D0002EA1202 | Датчик касания | End Device
3CEC | 00158D0001100EAA | lumi.sensor_cube | End Device
6B7D | 000B57FFFE8BF19D | TRADFRI remote control | End Device
8FCD | 00158D00034D146A | Универсальный датчик | End Device

**Comment by sprut666666** [comment]
Address: 00158D0003153751/0E63

Structure
Endpoint 1
Input
0000_Basic
0001_ApplicationVersion: 22
FF01_Custom: {1=3300, 3=23, 100=false, 101=true, 5=24, 8=9750, 153=0, 10=0, 155=0, 110=0, 111=2}
0003_HwVersion: 38
0004_ManufacturerName: LUMI
0005_ModelIdentifier: lumi.ctrl_neutral2
0007_PowerSource: 4
FF22_MappingModeLeft: 18
FF23_MappingModeRight: 34
0001_PowerConfiguration
0002_DeviceTemperatureConfiguration
0003_Identify
0019_OtaUpgrade
000A_Time
Output
0000_Basic
0019_OtaUpgrade
000A_Time
Endpoint 2
Input
0000_Basic
0010_BinaryOutputBasic
0004_Groups
0005_Scenes
0006_OnOff
0000_OnOff: false
F000_State: 51274496
Output
Endpoint 3
Input
0000_Basic
0010_BinaryOutputBasic
0004_Groups
0005_Scenes
0006_OnOff
0000_OnOff: true
F000_State: 51274496
Output
Endpoint 4
Input
0000_Basic
0006_OnOff
0000_OnOff: true
Output
Endpoint 5
Input
0000_Basic
0012_MultistateInputBasic
0006_OnOff
0000_OnOff: true
Output
Endpoint 6
Input
0000_Basic
0012_MultistateInputBasic
0006_OnOff
Output
Endpoint 8
Input
0000_Basic
000C_AnalogInputBasic
Output

**Comment by diamond5170** [comment]
NWK | IEEE | Name | Type
-- | -- | -- | --
C326 | 00158D0002019E00 | Датчик температуры и влажности | End Device
DC07 | 00158D00023A8763 | Программируемая кнопка | End Device
59EA | 00158D0002EA1202 | Датчик касания | End Device
3CEC | 00158D0001100EAA | lumi.sensor_cube | End Device
6B7D | 000B57FFFE8BF19D | TRADFRI remote control | End Device
8FCD | 00158D00034D146A | Универсальный датчик | End Device

**Comment by diamond5170** [comment]
<p>Address: 000B3CFFFEF03637/C9C9<br><br><b>Associated Devices</b><br><table border=1 width=100%><tr><th>NWK</th><th>IEEE</th><th>Name</th><th>Type</th></tr><tr><td>C326</td><td>00158D0002019E00</td><td>Датчик температуры и влажности</td><td>End Device</td></tr><tr><td>DC07</td><td>00158D00023A8763</td><td>Программируемая кнопка</td><td>End Device</td></tr><tr><td>59EA</td><td>00158D0002EA1202</td><td>Датчик касания</td><td>End Device</td></tr><tr><td>3CEC</td><td>00158D0001100EAA</td><td>lumi.sensor_cube</td><td>End Device</td></tr><tr><td>6B7D</td><td>000B57FFFE8BF19D</td><td>TRADFRI remote control</td><td>End Device</td></tr><tr><td>8FCD</td><td>00158D00034D146A</td><td>Универсальный датчик</td><td>End Device</td></tr></table><br><b>Bindings</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>000B57FFFE7E332D/1</td><td>0006_OnOff</td></tr><tr><td>1</td><td>IEEE</td><td>000B57FFFE7E332D/1</td><td>0008_LevelControl</td></tr></table><br><b>Neighbors</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th></tr><tr><td>00158D0002019E00</td><td>C326</td><td>End Device</td><td>true</td><td>Child</td><td>255</td></tr><tr><td>000B57FFFE8BF19D</td><td>6B7D</td><td>End Device</td><td>true</td><td>Child</td><td>255</td></tr><tr><td>00158D00023A8763</td><td>DC07</td><td>End Device</td><td>true</td><td>Child</td><td>255</td></tr><tr><td>000B3CFFFEFDAAFD</td><td>0F3E</td><td>Router</td><td>false</td><td>Sibling</td><td>129</td></tr><tr><td>00158D00034D146A</td><td>8FCD</td><td>End Device</td><td>true</td><td>Child</td><td>255</td></tr><tr><td>00158D0002EA1202</td><td>59EA</td><td>End Device</td><td>true</td><td>Child</td><td>255</td></tr><tr><td>000B57FFFE7E332D</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>135</td></tr><tr><td>000B57FFFE301909</td><td>AA0A</td><td>Router</td><td>false</td><td>Sibling</td><td>57</td></tr><tr><td>00158D0001100EAA</td><td>3CEC</td><td>End Device</td><td>true</td><td>Child</td><td>255</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 1.2.214</li><li>0001_ApplicationVersion: 17</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI bulb GU10 W 400lm</li><li>0007_PowerSource: 1</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0B05_Diagnostics<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0020_PollControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Thu Jul 02 04:02:30 MSK 2020</p>
