### ISSUE TITLE
3AFE170100510001

### ISSUE THREAD

**Issue by OXOTH1K** [sprut/Hub#158]
Address: 086BD7FFFEBFEAEB/443F<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 23</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Konke</li><li>0005_ModelIdentifier: 3AFE170100510001</li><li>0006_DateCode: </li><li>0007_PowerSource: 0</li><li>0008_GenericDeviceClass: 255</li><li>0009_GenericDeviceType: 255</li><li>000A_ProductCode: ByteArray [value=]</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 0</li><li>0030_BatteryManufacturer: </li><li>0031_BatterySize: 255</li><li>0033_BatteryQuantity: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li></ul></li></ul></li></ul><br>Last update: Fri Jul 03 00:20:03 MSK 2020
[Thu Jul 02 14:16:18 MSK 2020.zip](https://github.com/sprut/Hub/files/4866829/Thu.Jul.02.14.16.18.MSK.2020.zip)
Телеграм: [OXOTH1K](@OXOTH1K)
[Девайс в каталоге](https://v2.sprut.ai/catalog/item/konke-multi-function-button).
Покупал [тут](https://aliexpress.ru/item/33015636907.html).

**Comment by OXOTH1K** [comment]
[Thu Jul 02 14:16:18 MSK 2020.zip](https://github.com/sprut/Hub/files/4866825/Thu.Jul.02.14.16.18.MSK.2020.zip)

**Comment by sprut666666** [comment]
https://github.com/sprut/Hub/issues/176
