### ISSUE TITLE
Lamp_01

### ISSUE THREAD

**Issue by ypiter2006** [sprut/Hub#159]
Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device
Address: 01124B001C3BF06F/BC7E<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: SZ</li><li>0005_ModelIdentifier: Lamp_01</li><li>0006_DateCode: 20181107</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br>Last update: Fri Jul 03 14:17:53 MSK 2020

**Comment by sprut666666** [comment]
1.6.3
