### ISSUE TITLE
Не пробрасывается  датчик температуры 1-wire DS18B20

### ISSUE THREAD

**Issue by Volkovskij-r** [sprut/Hub#16]
** Подробное описание ошибки **
Датчик температуры не виден во вкладке аксессуаров

** Как воспроизвести ? **
Подключить датчик DS18B20 по 1-wire

** Ожидаемое поведение **
Данные с датчика температуры в HomeKit

** Скриншоты/ Логи **
Скриншот из Wiren Board Web UI (MQTT Channels)
![1-wire датчик температуры](https://user-images.githubusercontent.com/52540897/60742089-e9df5700-9f7c-11e9-8ebe-2817f3df49e1.png)

** Пожалуйста, заполните следующую информацию: **
 - SprutHub 1.1.1b (последнее обновление на 05.07.2019)
 

** Дополнительные материалы **
Сам датчик: https://wirenboard.com/ru/product/1wire-DS18B20/ подключен непосредственно к Wirenboard.

**Comment by sprut666666** [comment]
Нужен пример с 2-я датчиками

**Comment by Popov2006** [comment]
![photo_2019-07-06_10-12-23](https://user-images.githubusercontent.com/52490000/60753105-b03b3a00-9fd6-11e9-88c1-c047a72f9b29.jpg)


логи подключения двух датчиков

**Comment by sprut666666** [comment]
Обновляемся, пробуем
