### ISSUE TITLE
У лампы Акара нет регулировки цветовой температуры

### ISSUE THREAD

**Issue by shurikshurikov** [sprut/Hub#161]
В хомките у лампы Акара (lumi.light.aqcn02) не регулируется температура. Яркость регулируется рывками, а температура не регулируется вообще. В Web Спрутхаба яркость регулируется только с 51 на 52 с очень холодного на очень теплые цвет, в других положениях не регулируется, в хомките я вообще не смог поймать это положение, температура свечения не регулируется.

Влогах СХ при смене температуры следующее:
![image](https://user-images.githubusercontent.com/59749751/86495386-d2020500-bd81-11ea-952f-f74758ceb8af.jpeg)

Проверял в хомките на iOS 12.4.6, 13.5 и 14

ник в телеге @Shurik_Shurikov

**Comment by sprut666666** [comment]
1.6.3
