### ISSUE TITLE
Меняются характеристики при включении / выключении ламп

### ISSUE THREAD

**Issue by MaximSidorov777** [sprut/Hub#1626]
При включении / выключении ламп меняются её характеристики после обновления с 1.9.3 на 1.9.4
Условий при которых этого бы не происходило не удалось найти, постоянно мигают лампы при включении.
Пока сделал сценарий чтоб устанавливалась нужная яркость через пару секунд после включения...

SprutHub CE
Система 1.9.4 (8697)
Шаблоны 282
Web 1.2.11

Дальше на примере Philips Hue GU10 у которой из характеристик только Яркость.
Address: 0017880108C7046B/3F95

Для видео удалил все входящие связи у устройства, отключил виртуальную логику.
В конце видео решил показать другую лампу с большим количеством характеристик, но как назло прыгала только яркость.

Видео залил сюда: https://youtu.be/kRTrIrhv_eg

Логи [sprut.zip](https://github.com/sprut/Hub/files/10148462/sprut.zip)

В последнем значении яркости прописывается вот такое:
`"\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"100\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\""`
<img width="587" alt="Снимок экрана 2022-12-06 в 11 19 22" src="https://user-images.githubusercontent.com/86353917/205858011-9ec36a88-f696-46ae-b9bf-490986466977.png">

UPD: Приложил еще логи со всеми уровнями логирования.

Вот само прыгнуло:
`I | 2022-12-06 | 10:43:23.828 | org.makesimple.SprutHub.Model.CLink      499 | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '100'->'77']`
[Sprut.Hub_Log_2022.12.06-10_46_07.zip](https://github.com/sprut/Hub/files/10163891/Sprut.Hub_Log_2022.12.06-10_46_07.zip)

`
15:06:04 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '58'->'100'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196135202884
-- | -- | --
15:06:04 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '58'->'100']
15:06:04 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'true'->'true']
15:06:02 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'true'->'true'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196133214390
15:05:59 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '3'->'58'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196130188561
15:05:59 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '3'->'58']
15:05:59 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false']
15:05:58 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196129771803
15:05:54 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '100'->'3'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196125181946
15:05:54 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '100'->'3']
15:05:53 | Model.CLink | <-- L[ZigBee_1/[sprut.zip](https://github.com/sprut/Hub/files/10148458/sprut.zip)/On//11/0006/0000/false//Lightbulb 'true'->'true']
15:05:53 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'true'->'true'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196125086690
15:05:42 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '64'->'100'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196114070972
15:05:42 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '64'->'100']
15:05:38 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false']
15:05:37 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '1'->'64'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196109054050
15:05:37 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '1'->'64']
15:05:37 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196108689187
15:05:33 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'true'->'true']
15:05:32 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '100'->'1'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196104038962
15:05:32 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '100'->'1']
15:05:32 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'true'->'true'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196103949387
15:05:28 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false']
15:05:27 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196098281403
15:05:23 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '82'->'100'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196094991936
15:05:23 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '82'->'100']
15:05:23 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'true'->'true']
15:05:21 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'true'->'true'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196092414777
15:05:18 | Model.Characteristic | --- C[104.13.16 Lightbulb.Brightness '100'->'82'], ctx: C[104.13.16 Lightbulb.Brightness] <- CLINK[0017880108C7046B]_8196089992869
15:05:18 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/Brightness//11/0008/0000/false//Lightbulb '100'->'82']
15:05:18 | Model.CLink | <-- L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false']
15:05:18 | Model.CLink | --> L[ZigBee_1/0017880108C7046B/On//11/0006/0000/false//Lightbulb 'false'->'false'], ctx: C[104.13.15 Lightbulb.On] <- WEB[RPC]_8196089769230
14:42:30 | ZigBee.ZigBeeNode | 0017880108C7046B/3F95: Обновление не требуется
`

Ник в ТГ @MSidorov

**Comment by SmartHaven** [comment]
Исправлено в r8739, после обновления нужно будет удалить такие значения вручную.

**Comment by MaximSidorov777** [comment]
Значения последней яркости?

**Comment by MaximSidorov777** [comment]
> Исправлено в r8739, после обновления нужно будет удалить такие значения вручную.

Обновился до 1.9.5 (8740), поведение не поменялось, яркость прыгает.

@MakeSimpleOrg @sprut666666

**Comment by SmartHaven** [comment]
Параметр "последнее значение" ни на что не влияет, это была ошибка никак не связанная с самой яркостью, и уже исправлена. Из за этого не увидели основную проблему с яркостью.
Открыл тикет.
