### ISSUE TITLE
Fibaro FGS-223 отсутствует обратная связь со второго выхода и нет данных о потреблении с обоих

### ISSUE THREAD

**Issue by Danceny2** [sprut/Hub#1645]
Fibaro FGS-223:
1) отсутствует обратная связь со второго выхода. Если включать/выключать кнопкой - состояние в СХ (на малине) не меняется. На первом выходе все работает корректно.

2) нет данных о потреблении с обоих выходов. При включении первого и/или второго или обоих выходов не изменяется в СХ (на малине) значения потребляемой мощности и кВт/ч. 
Значения кВт/ч, которое указано ниже в сведениях - это исторические данные со времени подключения его к Fibaro HC2

<b>Fibargroup - FGS-223</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>3</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0203</td></tr><tr><td width=35%>Device Id</td><td>1000</td></tr><tr><td width=35%>App Version</td><td>3.4</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>1</td></tr><tr><td>2</td><td> On/Off (S1)</td><td>[]</td><td>5</td></tr><tr><td>3</td><td> Dimmer (S1)</td><td>[]</td><td>5</td></tr><tr><td>4</td><td> On/Off (S2)</td><td>[]</td><td>5</td></tr><tr><td>5</td><td> Dimmer (S2)</td><td>[]</td><td>5</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 Version</li><li>V2 MultiChannel</li><li>V3 MultiChannelAssociation</li><li>V2 Protection</li><li>V1 SwitchBinary</li><li>V1 DeviceResetLocally</li><li>V1 ZWavePlusInfo</li><li>V1 AssociationGRPInfo</li><li>V3 Meter<ul><li>Energy: 82.51 kWh</li><li>Power: 0 W</li></ul></li><li>V1 NoOperation</li><li>V1 Basic</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V5 Alarm<ul><li>Heat</li><li>PowerManagement</li></ul></li><li>V1 FirmwareUpdateMD</li><li>V2 Association</li><li>V1 Security</li><li>V2 CentralScene</li><li>V1 CRC16Encap</li><li>V1 Configuration</li><li>V2 ManufacturerSpecific</li><li>V1 ApplicationStatus</li></ul></li><li>Endpoint 1<ul><li>V1 Basic</li><li>V2 Version</li><li>V3 MultiChannelAssociation</li><li>V2 Association</li><li>V1 SwitchBinary</li><li>V1 ZWavePlusInfo</li><li>V1 AssociationGRPInfo</li><li>V3 Meter<ul><li>Energy: 82.51 kWh</li><li>Power: 0 W</li></ul></li></ul></li><li>Endpoint 2<ul><li>V1 Basic</li><li>V2 Version</li><li>V3 MultiChannelAssociation</li><li>V2 Association</li><li>V1 SwitchBinary</li><li>V1 ZWavePlusInfo</li><li>V1 AssociationGRPInfo</li><li>V3 Meter<ul><li>Energy: 5.97 kWh</li><li>Power: 0 W</li></ul></li></ul></li></ul><br>Last update: Fri Dec 09 08:46:33 MSK 2022

**Comment by Danceny2** [comment]
Логи работы второго выхода Fibaro FGS-223:
**Включение из СХ:**
<html>
<body>


20:59:27 | ZWave.transaction.ZWTransactionManager | Received: Message: SendData[0x13], type=Request[0], dest=255, callback=160, payload=A0 00 00 01 00 B2 7F 7F 7F 7F 00 00 03 00 00 00 00 03 01 00 00 7F 7F 7F 7F 7F
-- | -- | --
20:59:27 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 1D 00 13 A0 00 00 01 00 B2 7F 7F 7F 7F 00 00 03 00 00 00 00 03 01 00 00 7F 7F 7F 7F 7F 9C
20:59:26 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false
20:59:26 | ZWave.transaction.ZWTransaction | NODE 3: TID 1514: TransactionAdvance WAIT_RESPONSE -> WAIT_REQUEST
20:59:26 | ZWave.serial.classes.SendDataClass | NODE 3: sentData successfully placed on stack.
20:59:26 | ZWave.ZWController | Incoming Message: Message: SendData[0x13], type=Response[1], dest=255, callback=0, payload=01
20:59:26 | ZWave.transaction.ZWTransactionManager | Callback 160: correlated to TID 1514
20:59:26 | ZWave.transaction.ZWTransactionManager | Outstanding: (1) [TID 1514: WAIT_RESPONSE, requiresResponse=true, callback: 160, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]]
20:59:26 | ZWave.transaction.ZWTransactionManager | Received: Message: SendData[0x13], type=Response[1], dest=255, callback=0, payload=01
20:59:26 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 04 01 13 01 E8
20:59:26 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false
20:59:26 | ZWave.transaction.ZWTransactionManager | Received: Message: null[0x0], type=ACK[2], dest=255, callback=0, payload=
20:59:26 | ZWave.serial.ZWSerialHandlerJSerial | Received ACK: true
20:59:26 | ZWave.serial.ZWSerialHandlerJSerial | NODE 3: Message sended, rxState: 0
20:59:26 | ZWave.serial.ZWSerialHandlerJSerial | NODE 3: Sending REQUEST Message = 01 0E 00 13 03 07 60 0D 01 02 25 01 FF 01 A0 F2, false
20:59:26 | ZWave.serial.SerialMessage | Assembled message buffer = 01 0E 00 13 03 07 60 0D 01 02 25 01 FF 01 A0 F2
20:59:26 | ZWave.serial.SerialMessage | messagePayload = 03 07 60 0D 01 02 25 01 FF
20:59:26 | ZWave.transaction.ZWTransactionManager | Outstanding Transactions: [TID 1514: WAIT_RESPONSE, requiresResponse=true, callback: 160, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]]
20:59:26 | ZWave.transaction.ZWTransactionManager | NODE 3: Transaction started: TID 1514: WAIT_RESPONSE, requiresResponse=true, callback: 160, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]
20:59:26 | ZWave.serial.SerialMessage | NODE 3: Creating empty message of class = SendData (0x13), type = Request
20:59:26 | ZWave.transaction.ZWTransactionManager | NODE 3: TID 1514: Transaction from sendQueue
20:59:26 | ZWave.transaction.ZWTransactionManager | NODE 3: TID 1514: Add to queue(1): [TID 1514: UNINTIALIZED, requiresResponse=true, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]]
20:59:26 | ZWave.commandclass.SwitchBinary | NODE 3: Creating new message for application command SWITCH_BINARY_SET
20:59:26 | Controllers.ZWave.Controls.SwitchBinary | 3: Set state: true


</body>
</html>

**Выключение из СХ:**
<html>
<body>


21:02:50 | ZWave.transaction.ZWTransaction | NODE 3: TID 1515: Transaction COMPLETED in 440ms: SwitchBinary
-- | -- | --
21:02:50 | ZWave.serial.classes.SendDataClass | NODE 3: TxStatus: Time: 10, Hops: 0, Rssi: -79 127 127 127 127, AckChannel: 0, TxChannel: 0, RouteScheme: 3, Route: 0 0 0 0, RouteSpeed: 3, RouteTries: 1, FailedLinkFrom: 0, FailedLinkTo: 0
21:02:50 | ZWave.serial.classes.SendDataClass | NODE 3: SendData Request. CallBack ID = 161, Status = Transmission complete and ACK received(0)
21:02:50 | ZWave.ZWController | Incoming Message: Message: SendData[0x13], type=Request[0], dest=255, callback=161, payload=A1 00 00 01 00 B1 7F 7F 7F 7F 00 00 03 00 00 00 00 03 01 00 00 7F 7F 7F 7F 7F
21:02:50 | ZWave.transaction.ZWTransactionManager | Callback 161: correlated to TID 1515
21:02:50 | ZWave.transaction.ZWTransactionManager | Outstanding: (1) [TID 1515: WAIT_REQUEST, requiresResponse=true, callback: 161, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]]
21:02:50 | ZWave.transaction.ZWTransactionManager | Received: Message: SendData[0x13], type=Request[0], dest=255, callback=161, payload=A1 00 00 01 00 B1 7F 7F 7F 7F 00 00 03 00 00 00 00 03 01 00 00 7F 7F 7F 7F 7F
21:02:50 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 1D 00 13 A1 00 00 01 00 B1 7F 7F 7F 7F 00 00 03 00 00 00 00 03 01 00 00 7F 7F 7F 7F 7F 9E
21:02:50 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false
21:02:50 | ZWave.transaction.ZWTransaction | NODE 3: TID 1515: TransactionAdvance WAIT_RESPONSE -> WAIT_REQUEST
21:02:50 | ZWave.serial.classes.SendDataClass | NODE 3: sentData successfully placed on stack.
21:02:50 | ZWave.ZWController | Incoming Message: Message: SendData[0x13], type=Response[1], dest=255, callback=0, payload=01
21:02:50 | ZWave.transaction.ZWTransactionManager | Callback 161: correlated to TID 1515
21:02:50 | ZWave.transaction.ZWTransactionManager | Outstanding: (1) [TID 1515: WAIT_RESPONSE, requiresResponse=true, callback: 161, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]]
21:02:50 | ZWave.transaction.ZWTransactionManager | Received: Message: SendData[0x13], type=Response[1], dest=255, callback=0, payload=01
21:02:50 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 04 01 13 01 E8
21:02:50 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false
21:02:50 | ZWave.transaction.ZWTransactionManager | Received: Message: null[0x0], type=ACK[2], dest=255, callback=0, payload=
21:02:50 | ZWave.serial.ZWSerialHandlerJSerial | Received ACK: true
21:02:49 | ZWave.serial.ZWSerialHandlerJSerial | NODE 3: Message sended, rxState: 0
21:02:49 | ZWave.serial.ZWSerialHandlerJSerial | NODE 3: Sending REQUEST Message = 01 0E 00 13 03 07 60 0D 01 02 25 01 00 01 A1 0C, false
21:02:49 | ZWave.serial.SerialMessage | Assembled message buffer = 01 0E 00 13 03 07 60 0D 01 02 25 01 00 01 A1 0C
21:02:49 | ZWave.serial.SerialMessage | messagePayload = 03 07 60 0D 01 02 25 01 00
21:02:49 | ZWave.transaction.ZWTransactionManager | Outstanding Transactions: [TID 1515: WAIT_RESPONSE, requiresResponse=true, callback: 161, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]]
21:02:49 | ZWave.transaction.ZWTransactionManager | NODE 3: Transaction started: TID 1515: WAIT_RESPONSE, requiresResponse=true, callback: 161, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]
21:02:49 | ZWave.serial.SerialMessage | NODE 3: Creating empty message of class = SendData (0x13), type = Request
21:02:49 | ZWave.transaction.ZWTransactionManager | NODE 3: TID 1515: Transaction from sendQueue
21:02:49 | ZWave.transaction.ZWTransactionManager | NODE 3: TID 1515: Add to queue(1): [TID 1515: UNINTIALIZED, requiresResponse=true, [Node: 3, Command: SwitchBinary/0x1->0x0, Priority: Set, MaxAttempts: 0, Security: false, Response: true]]
21:02:49 | ZWave.commandclass.SwitchBinary | NODE 3: Creating new message for application command SWITCH_BINARY_SET
21:02:49 | Controllers.ZWave.Controls.SwitchBinary | 3: Set state: false


</body>
</html>

**Включение или Выключение второго канала кнопкой логи не формирует**

Для примера включение и выключение первого канала с кнопки:
**Включение 1 канала кнопкой:**
<html>
<body>


21:07:51 | ZWave.transaction.ZWTransactionManager | 0 transactions completed, outstandingTransactions: 0
-- | -- | --
21:07:51 | ZWave.transaction.ZWTransactionManager | NODE 3: Command NOT verified: [Node: 3, CC: Meter, CMD: 0x2, Payload: 32 02 21 32 01 CC 00 00]
21:07:51 | Controllers.ZWave.ZWave_1 | Event [3/0, class=Meter, type=Electric, scale=E_W, value=46 W]
21:07:51 | ZWave.commandclass.CommandClass | NODE 3/0: Received Meter V3 METER_REPORT
21:07:51 | ZWave.ZWNode | NODE 3: Decapsulating CRC_16_ENCAP
21:07:51 | ZWave.transaction.ZWTransactionManager | Received: Message: ApplicationCommandHandlerBridge[0xa8], type=Request[0], dest=3, callback=0, payload=00 01 03 0C 56 01 32 02 21 32 01 CC 00 00 4E 97 00 B3
21:07:51 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 15 00 A8 00 01 03 0C 56 01 32 02 21 32 01 CC 00 00 4E 97 00 B3 9F
21:07:51 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false
21:07:45 | Controllers.ZWave.Controls.SwitchBinary | 3: State: 255
21:07:45 | ZWave.transaction.ZWTransactionManager | 0 transactions completed, outstandingTransactions: 0
21:07:45 | Controllers.ZWave.ZWave_1 | Event [3/0, class=SwitchBinary, value=255]
21:07:45 | ZWave.transaction.ZWTransactionManager | NODE 3: Command NOT verified: [Node: 3, CC: SwitchBinary, CMD: 0x3, Payload: 25 03 FF]
21:07:45 | ZWave.commandclass.SwitchBinary | NODE 3: Switch Binary report, value = 255
21:07:45 | ZWave.commandclass.CommandClass | NODE 3/0: Received SwitchBinary V1 SWITCH_BINARY_REPORT
21:07:45 | ZWave.ZWNode | NODE 3: Decapsulating CRC_16_ENCAP
21:07:45 | ZWave.transaction.ZWTransactionManager | Received: Message: ApplicationCommandHandlerBridge[0xa8], type=Request[0], dest=3, callback=0, payload=00 01 03 07 56 01 25 03 FF 79 58 00 B3
21:07:45 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 10 00 A8 00 01 03 07 56 01 25 03 FF 79 58 00 B3 5E
21:07:45 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false


</body>
</html>

**Выключение первого канала с кнопки:**
<html>
<body>


21:09:08 | ZWave.transaction.ZWTransactionManager | 0 transactions completed, outstandingTransactions: 0
-- | -- | --
21:09:08 | ZWave.transaction.ZWTransactionManager | NODE 3: Command NOT verified: [Node: 3, CC: Meter, CMD: 0x2, Payload: 32 02 21 32 00 00 00 00]
21:09:08 | ZWave.commandclass.CommandClass | NODE 3/0: Received Meter V3 METER_REPORT
21:09:08 | ZWave.ZWNode | NODE 3: Decapsulating CRC_16_ENCAP
21:09:08 | ZWave.transaction.ZWTransactionManager | Received: Message: ApplicationCommandHandlerBridge[0xa8], type=Request[0], dest=3, callback=0, payload=00 01 03 0C 56 01 32 02 21 32 00 00 00 00 6B B5 00 B3
21:09:08 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 15 00 A8 00 01 03 0C 56 01 32 02 21 32 00 00 00 00 6B B5 00 B3 55
21:09:08 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false
21:09:03 | ZWave.transaction.ZWTransactionManager | 0 transactions completed, outstandingTransactions: 0
21:09:03 | Controllers.ZWave.Controls.SwitchBinary | 3: State: 0
21:09:03 | ZWave.transaction.ZWTransactionManager | NODE 3: Command NOT verified: [Node: 3, CC: SwitchBinary, CMD: 0x3, Payload: 25 03 00]
21:09:03 | Controllers.ZWave.ZWave_1 | Event [3/0, class=SwitchBinary, value=0]
21:09:03 | ZWave.commandclass.SwitchBinary | NODE 3: Switch Binary report, value = 0
21:09:03 | ZWave.commandclass.CommandClass | NODE 3/0: Received SwitchBinary V1 SWITCH_BINARY_REPORT
21:09:03 | ZWave.ZWNode | NODE 3: Decapsulating CRC_16_ENCAP
21:09:03 | ZWave.transaction.ZWTransactionManager | Received: Message: ApplicationCommandHandlerBridge[0xa8], type=Request[0], dest=3, callback=0, payload=00 01 03 07 56 01 25 03 00 67 A8 00 B3
21:09:03 | ZWave.serial.ZWSerialHandlerJSerial | Receive Message = 01 10 00 A8 00 01 03 07 56 01 25 03 00 67 A8 00 B3 4F
21:09:03 | ZWave.serial.ZWSerialHandlerJSerial | Received SOF: false


</body>
</html>

**Comment by Danceny2** [comment]
Ваты появились сами - может обновление и перезагрузка СХ помогла. Но обратной связи в СХ привключении второго канала нет.

**Comment by Danceny2** [comment]
Кажется нашел в чем проблема. В "Связь с устройством" в ссылке вместо //0/ должна быть единица.
![image](https://user-images.githubusercontent.com/120160129/206872921-681ece07-1530-402f-861d-b029c199024e.png)

**Comment by SmartHaven** [comment]
Но если при включении/выключении второго канала ничего не приходит в логи, то не важно что стоит в связях, 0 или 1, все равно второй канал работать не будет.
Если обратная связь видна в логах, то да, правка связей может решить проблему. Но если нет, то более вероятно, что неправильно установлены ассоциации, либо не настроен какой-нибудь параметр из pdf производителя.

**Comment by Danceny2** [comment]
Я видимо ошибся с каналами (реле за выключателем уже года два как), не работает обратная связь от первого канала. От второго работает. 

Чтобы не плодить шаблоны - может я его в виде кастомного опробую и отпишусь по факту?

**Comment by SmartHaven** [comment]
Переключить дебаг обратно на уровень "info", галочку "показать все события" оставить. Иначе много лишних строчек в логе.
Достаточно ивентов типа "Event [3/N, class=SwitchBinary, value=0]" в логе, при нажатии кнопок. Здесь N это эндпойнт, 0, 1, 2 или бывает больше. SwitchBinary класс тоже должен быть правильным в шаблоне.

Сейчас первая кнопка на эндпойнте 0, вторая на 2. Предположу, что при нажатии из веб интерфейса такие ивенты и приходят (0 и 2), а при нажатии физических кнопок приходят 1 и 2.

Здесь нет ничего сложного, просто собрать точную информацию.

**Comment by Danceny2** [comment]
пожалуйста:

16:09:10
Controllers.ZWave.ZWave_1
Event [3/1, class=Meter, type=Electric, scale=E_W, value=0 W]
16:09:04
Controllers.ZWave.ZWave_1
Event [3/2, class=Meter, type=Electric, scale=E_W, value=0 W]
16:09:03
Controllers.ZWave.ZWave_1
Event [3/1, class=Meter, type=Electric, scale=E_W, value=0 W]
16:09:01
Controllers.ZWave.ZWave_1
Event [3/2, class=SwitchBinary, value=0]
16:09:00
Controllers.ZWave.ZWave_1
Event [3/1, class=SwitchBinary, value=0]
16:08:56
Controllers.ZWave.ZWave_1
Event [3/1, class=Meter, type=Electric, scale=E_W, value=46.1 W]
16:08:51
Controllers.ZWave.ZWave_1
Event [3/1, class=Meter, type=Electric, scale=E_W, value=46.1 W]
16:08:49
Controllers.ZWave.ZWave_1
Event [3/1, class=SwitchBinary, value=255]
16:08:39
Homekit.http.AccessoryHandler
Terminated homekit connection from /192.168.4.52:64255
16:08:36
Controllers.ZWave.ZWave_1
Event [3/2, class=Meter, type=Electric, scale=E_W, value=122.9 W]
16:08:32
Controllers.ZWave.ZWave_1
Event [3/2, class=SwitchBinary, value=255]

**Comment by SmartHaven** [comment]
Нажми "Обновить шаблоны" в расширенных настройках хаба. Потом перезагрузи контроллер z-wave и протестируй все ли исправилось.

**Comment by Danceny2** [comment]
Работает. Большое спасибо!
