### ISSUE TITLE
Тормозит web интерфейс при выборе неверного порта zigbee

### ISSUE THREAD

**Issue by nikolay812** [sprut/Hub#166]
При добавлении контроллера zigbee в sh и выборе неверного порта, веб интерфейс начинает тормозить, очень долго открываются настройки контроллера, изменить порт становится почти невозможно.

В моем случае порт был выбран правильно, но по какой-то причине не коннектился. У других пользователей аналогичная проблема при выборе неверного порта.

[stdout.log](https://github.com/sprut/Hub/files/4875744/stdout.log)

**Comment by sprut666666** [comment]
1.6.3
