### ISSUE TITLE
Подтверждение при снятии галки с аксессуара

### ISSUE THREAD

**Issue by nikolay812** [sprut/Hub#167]
Предложение ввести дополнительное подтверждение в web SH для скрытия аксессуара из homekit (снятия галки - скрин во вложении), как при нажатии на кнопку перезагрузки.
Проблема в том, что иногда можно случайно промахнуться и скрыть аксессуар, при добавлении обратно в homekit этот аксессуар попадает в комнату по умолчанию и с именем как в sh, приходится править все вручную.[image](https://user-images.githubusercontent.com/60763765/86544641-4038fa00-bf31-11ea-9f03-f31b5fd56ba7.jpeg)

**Comment by MakeSimpleOrg** [comment]
Новый интерфейс
