### ISSUE TITLE
RH3040

### ISSUE THREAD

**Issue by diamond5170** [sprut/Hub#170]
Address: EC1BBDFFFE95443E/6237<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 64</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: TUYATEC-zn9wyqtr</li><li>0005_ModelIdentifier: RH3040</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Unknown: �</li><li>FFE2_Unknown: 21</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0010_IasCieAddress: 0000000000000000</li><li>0001_ZoneType: 13</li><li>0011_ZoneId: 255</li><li>0002_ZoneStatus: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 21</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>000A_Time<ul><li>0007_LocalTime: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br>Last update: Mon Jul 06 23:32:47 MSK 2020

**Comment by sprut666666** [comment]
1.6.3
