### ISSUE TITLE
Ошибка в темплейте MQTT WB-MIO-GPIO-K

### ISSUE THREAD

**Issue by nikolay812** [sprut/Hub#171]
До:
   "topicGet": "/devices/(wb-mio-gpio[0-9]{1,3}/controls/K[0-9]{1,2})",
            "topicSet": "/devices/(wb-mio-gpio[0-9]{1,3}/controls/K[0-9]{1,2})/on"

После:
   "topicGet": "/devices/(wb-mio-gpio_[0-9]{1,3}:[0-9]{1,3}/controls/K[0-9]{1,2})",
            "topicSet": "/devices/(wb-mio-gpio_[0-9]{1,3}:[0-9]{1,3}/controls/K[0-9]{1,2})/on"

На верность правок не претендую, но в таком виде работает.
Исправленный темплейт во вложении.
[WB-MIO-GPIO-K.zip](https://github.com/sprut/Hub/files/4881612/WB-MIO-GPIO-K.zip)

**Comment by sprut666666** [comment]
1.6.3

**Comment by nikolay812** [comment]
1.6.3 не полностью исправили темплейт. Не хватает нижнего подчеркивания.

wb-mio-gpio_[0-9]

**Comment by sprut666666** [comment]
1.6.5
