### ISSUE TITLE
Возможность полной отвязки от облаков

### ISSUE THREAD

**Issue by rekby** [sprut/Hub#1718]
** Максимально подробное описание предложения.**
Хочется иметь максимально автономное устройство, которое может полноценно функционировать не подключаясь к интернету.
1. Локальные учётки, без привязки/проверки в облаке.
2. Локальное обновление прошивок (через флешку/веб-интерфейс) - как в роутерах/NAS (Synology).

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
