### ISSUE TITLE
Резервное копирование на внешний сервер

### ISSUE THREAD

**Issue by rekby** [sprut/Hub#1723]
** Максимально подробное описание предложения.**
Для надёжного хранения резервной копии было бы удобно делать её на внешний сервер вместо флешки.

** Дополнительные материалы **
Была бы удобна реализация протоколов: S3 (удобно для облаков), FTP (удобно для копий на домашний сервер), возможно WebDAV (может быть удобно на NAS, но тут и ftp подойдёт).

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"

**Comment by rekby** [comment]
@sprut666666 не очень понятно как долгосрочные пожелания функционала могут решаться в телеграм-чате, где диалоги быстро убегают и никакого долгосрочного отслеживания статусов там нет.
