### ISSUE TITLE
WBIO-DI-DR-8 перепутан с WBIO-DI-DR-14

### ISSUE THREAD

**Issue by OXOTH1K** [sprut/Hub#173]
** Подробное описание ошибки **
WBIO-DI-DR-8  в вебморде определяется как WBIO-DI-DR-14
Имя не менялось, настройки не менялись.

** Дополнительные материалы **
![image](https://user-images.githubusercontent.com/19778219/86749410-4a044f80-c04e-11ea-9f55-3426ce2516bc.png)

**Comment by sprut666666** [comment]
1.6.3 будет дано универсально название, ибо идентифицировать модель невозможно
