### ISSUE TITLE
Эмулятор выполнения сценариев

### ISSUE THREAD

**Issue by tommy-vrb** [sprut/Hub#1734]
Хотелось бы иметь возможность проверить работу сценария не на реальном доме и реальных устройствах, а на эмуляторе. Например, создать отдельный раздел в вебе, в котором можно вручную эмулировать активацию каких-то условий или триггеров и смотреть, как будут отрабатывать устройства по алгоритму сценария. Как вариант, сделать такой эмулятор онлайн (в интернете) с возможностью выгрузки сценария на хаб.

Так будет проще создавать более сложные сценарии и проверять их работу, не мучая домашние устройства.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
