### ISSUE TITLE
Модуль управления моторами DAR-102

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#177]
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>2</td></tr><tr><td width=35%>Manufacturer Id</td><td>032E</td></tr><tr><td width=35%>Device Type</td><td>0041</td></tr><tr><td width=35%>Device Id</td><td>0014</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Class B Motor</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><tr><th>ID</th><th>Label</th><th>Associations</th></tr><br><b>Association Groups</b><br><table border=1 width=100%><tr><td>1</td><td></td><td>[node_1]</td></tr><tr><td>2</td><td></td><td>[]</td></tr><tr><td>3</td><td></td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 Association</li><li>V1 Version</li><li>V2 ManufacturerSpecific</li><li>V1 NoOperation</li><li>V1 SwitchMultiLevel<ul></ul></li><li>V1 Basic</li><li>V1 Configuration</li><li>V1 FirmwareUpdateMD</li><li>V1 SwitchBinary</li><li>V2 MultiChannelAssociation</li></ul></li></ul><br>Last update: Thu Jul 09 15:45:43 UTC 2020

Телеграм: @ziracul
[Девайс в каталоге.](https://v2.sprut.ai/catalog/item/defaro-modul-upravlenia-motorami-dar-102)

**Comment by MakeSimpleOrg** [comment]
1.6.4
