### ISSUE TITLE
TRADFRI bulb E27 WS opal 1000lm

### ISSUE THREAD

**Issue by sotidis** [sprut/Hub#178]
Address: 680AE2FFFE933974/8FB8<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>4000_SwBuildId: 2.0.022</li><li>0001_ApplicationVersion: 32</li><li>0002_StackVersion: 98</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI bulb E27 WS opal 1000lm</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>4001_EnhancedColorMode: 2</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 30138</li><li>0004_CurrentY: 26909</li><li>0007_ColorTemperature: 370</li><li>0008_ColorMode: 2</li><li>400A_ColorCapabilities: 16</li><li>400B_ColorTemperatureMin: 250</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0010_OnOffTransitionTime: 5</li><li>4000_StartUpCurrentLevel: 255</li><li>0001_RemainingTime: 0</li><li>0011_OnLevel: 255</li><li>000F_Options: 0</li></ul></li><li>FC7C_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0020_PollControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sun Jul 12 07:48:11 CEST 2020 с инструкцией: https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

Телеграм @Grek21
Каталог https://v2.sprut.ai/catalog/item/ikea-lampocka-6

**Comment by sprut666666** [comment]
1.6.4
