### ISSUE TITLE
Не работает switchOffTime

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#18]
** Подробное описание ошибки **
При установленном  2000 (2с) реле не выключается физически

** Как воспроизвести ? **
1. В Аксессуарах установил switchOffTime (2000)
2. Реле отобразилось в ХоумКите .
3. Нажимаю в ХоумКите на кнопку реле.
4. По прошествии двух секунд, состояние картинки кнопки реле переходит из включенного в выключенное.
5. Реле остается в состоянии включено.

** Ожидаемое поведение **
По прошествии заданного времени переводить состояние реле выкл.
** Скриншоты/ Логи **
Видео работы представлено в чате. Если необходимо попробую  вставить сюда.

** Пожалуйста, заполните следующую информацию: **
  - Версия: IOS 12.4 (бета) IPhone 8, последняя официальная на IPhone Xs

** Дополнительные материалы **
Проверял на разных типах реле - Сяоми, WB

**Comment by diamond5170** [comment]
Исправлено.

**Comment by Popov2006** [comment]
Не исправлено. У меня не работает. Физически реле не возвращается в исходное состояние.

**Comment by Popov2006** [comment]
все работает
