### ISSUE TITLE
8643db61de35494d93e72c1289b526a3

### ISSUE THREAD

**Issue by OXOTH1K** [sprut/Hub#182]
Address: 00124B001130A314/E5AB<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: 欧瑞博</li><li>0005_ModelIdentifier: 8643db61de35494d93e72c1289b526a3</li><li>0006_DateCode: 2015-06-25      </li><li>0007_PowerSource: 4</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 0</li><li>0001_CurrentSaturation: 0</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 20480</li><li>0004_CurrentY: 21845</li><li>0007_ColorTemperature: 0</li><li>0008_ColorMode: 2</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 0</li><li>0001_RemainingTime: 0</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li></ul></li></ul></li></ul><br>Last update: Mon Jul 13 14:35:42 MSK 2020

Родного Хаба нету.
Купить можно [тут](https://rozetka.com.ua/orvibo_rl804czb/p34821119/#tab=characteristics)
[В каталоге](https://v2.sprut.ai/catalog/item/orvibo-zigbee-rgb-relay)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/orvibo-zigbee-rgb-relay
