### ISSUE TITLE
TS0201

### ISSUE THREAD

**Issue by corsaroff** [sprut/Hub#183]
Address: EC1BBDFFFE32645C/D1CA<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 67</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ2000_hjsgdkfl</li><li>0005_ModelIdentifier: TS0201</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2750</li><li>0001_MinMeasuredValue: -32768</li><li>0002_MaxMeasuredValue: -32768</li></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 5860</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Mon Jul 13 20:55:29 MSK 2020

[Ссылка на каталог](https://v2.sprut.ai/catalog/item/blitzwolf-temperature-humidity-sensor)
Ник в Телеграмм - @vklimov
Покупал [тут](https://aliexpress.ru/item/4000640062775.html?spm=a2g0s.9042311.0.0.3eaf33edweqjKI&_ga=2.235210881.1684699884.1594663354-2105572549.1589283079)

**Comment by sprut666666** [comment]
1.6.3
