### ISSUE TITLE
TS0011

### ISSUE THREAD

**Issue by denis86111** [sprut/Hub#185]
Address: EC1BBDFFFE803A80/B281

Logical Type | End Device
-- | --
Server Capabilities | []
Mac Capabilities | [REDUCED_FUNCTION_DEVICE]

Current Power Mode | RECEIVER_ON_IDLE
-- | --
Available Power Sources | [MAINS]
Current Power Source | MAINS
Power Level | FULL

Structure
Endpoint 1
Input
0000_Basic
0000_ZclVersion: 3
0001_ApplicationVersion: 65
0002_StackVersion: 0
0003_HwVersion: 1
0004_ManufacturerName: _TYZB01_rifa0wlb
0005_ModelIdentifier: TS0011
0006_DateCode:
0007_PowerSource: 3
FFE2_Unknown: 19
0004_Groups
0000_NameSupport: 0
0005_Scenes
0000_SceneCount: 0
0001_CurrentScene: 0
0002_CurrentGroup: 0
0003_SceneValid: false
0004_NameSupport: 0
0006_OnOff
0000_OnOff: true
4001_OnTime: 0
4002_OffWaitTime: 0
Output
0019_OtaUpgrade

**Comment by sprut666666** [comment]
1.6.3 и в дальнейшем прошу заполнять ишью правильно
