### ISSUE TITLE
Положение Штор Aqara в Яндекс  Алисе отображаются как Яркость

### ISSUE THREAD

**Issue by JonnyLuz** [sprut/Hub#188]
Положение Штор Aqara в приложении Алиса отображаются как яркость. Соответственно голосовое управление идет через установи яркость Штор.

"Включи яркость шторы 20 %" - это пример голосовой команды из Алисы.
Есть функция для штор "Open" через нее должно работать правильно.

**Comment by Bigmanekb** [comment]
то же касается окон и роллет

**Comment by sprut666666** [comment]
Исправлено
