### ISSUE TITLE
Нагрузка на SprutHub

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#19]
** Максимально подробное описание предложения.**
Мне кажется, что нужно установить в одном из разделов ПО СпрутХаба монитор ресурсов железа. Что бы не перегрузить обилием устройств и дополнительно установленным ПО. (например нодеред)

** Дополнительные материалы **
Во всех ПО серверов в обязательном порядке выводят оставшиеся или задействованные ресурсы памяти, процессора, температуры и т.д. 
По моему мнению, что бы отсечь возможные проблемы у пользователей, необходимо информировать человека о нагрузках.

**Comment by diamond5170** [comment]
В целом, нагрузка почти не зависит от количества устройств. А тот кто будет ставить node-red будет делать это через консоль, где итак видно всю информацию.
Но когда-нибудь может быть и добавлю индикатор, только он бесполезен.

**Comment by diamond5170** [comment]
Нагрузка с включенным ZigBee уменьшена с 60% до 1-3%.
Без ZigBee раньше было 7-20%, теперь тоже 1-3%.
