### ISSUE TITLE
lumi.plug.mmeu01

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#192]
Address: 04CF8CDF3C759E81/D52B<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 22</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.plug.mmeu01</li><li>0007_PowerSource: 1</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>00F7_Custom: ByteArray [value=64 10 00 03 28 1A 98 39 00 00 00 00 95 39 44 1D 34 3F 96 39 00 80 13 45 97 39 00 00 00 00 05 21 01 00 9A 20 00 08 21 16 01 07 27 00 00 00 00 00 00 00 00 09 21 00 04 0B 20 00 9B 10 00]</li><li>0207_OutletInUse: false</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 703</li><li>0200_Status: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0B04_ElectricalMeasurement<ul><li>0000_MeasurementType: 8</li><li>050B_ActivePower: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: true</li><li>00F5_Unknown: 64301824</li></ul></li><li>0009_Alarms<ul><li>0000_AlarmCount: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 21<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>0055_PresentValue: 0.0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br>Last update: Fri Jul 17 23:29:02 BST 2020
[В каталоге ](https://v2.sprut.ai/catalog/item/xiaomi-mi-power-plug-eu)
Телеграм @ziracul

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device
