### ISSUE TITLE
GS BRHM8E27W70-I1

### ISSUE THREAD

**Issue by sergoo-lbt** [sprut/Hub#193]
Address:  BRHM8E27W70-I1  <br><br><b>Neighbors</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th></tr><tr><td>000B57FFFE18057C</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>102</td></tr><tr><td>00158D0004174798</td><td>2D50</td><td>Router</td><td>false</td><td>Sibling</td><td>31</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>4000_SwBuildId: 2000-1002</li><li>0001_ApplicationVersion: 10</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 16</li><li>0004_ManufacturerName: GS</li><li>0005_ModelIdentifier: BRHM8E27W70-I1</li><li>0006_DateCode: 20180628</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 23</li><li>4000_EnhancedCurrentHue: 6069</li><li>0001_CurrentSaturation: 220</li><li>4001_EnhancedColorMode: 2</li><li>0002_RemainingTime: 0</li><li>4002_ColorLoopActive: 0</li><li>0003_CurrentX: 30295</li><li>0004_CurrentY: 27192</li><li>0007_ColorTemperature: 370</li><li>0008_ColorMode: 2</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 1</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: 0000000000000000</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0010_OnOffTransitionTime: 2</li><li>4000_StartUpCurrentLevel: 255</li><li>0001_RemainingTime: 0</li><li>000F_Options: 1</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sun Jul 19 10:58:10 MSK 2020

Родного хаба нет. 

Устройство в каталоге https://v2.sprut.ai/catalog/item/trikolor-umnaa-lampa-cvetnaa-gs-brhm8e27w70-i1

Мой Телеграмм @sergoo_lbt

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device прошу привести пост в соответствие

**Comment by sergoo-lbt** [comment]
> https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device прошу привести пост в соответствие

Сделано.

**Comment by sprut666666** [comment]
1.6.4
