### ISSUE TITLE
добавить нумерацию клавиш для Homekit

### ISSUE THREAD

**Issue by pabl33** [sprut/Hub#194]
Кнопки выключателей Aqara Opple в хомките имеют неправильный порядок.в приложении Eve порядок нормальный.Так же это проявилось на одном из беспроводных выключателей Aqara WXKG02LM-перепутаны местами левая и правая клавиша.

**Comment by diamond5170** [comment]
Дом и Eve работают по одному протоколу, точнее Eve берет данные из дома.
Если в вебе порядок нормальный то чинить нечего, закрыть.

**Comment by pabl33** [comment]
> Дом и Eve работают по одному протоколу, точнее Eve берет данные из дома.
> Если в вебе порядок нормальный то чинить нечего, закрыть.

в телеге обсуждали.
вроде как характеристика ServiceLabelIndex задаёт порядок.
порядок кнопок 6/4 клавишного выключателя идёт вразнобой-это точно нужно доработать.

**Comment by sprut666666** [comment]
1.6.4
