### ISSUE TITLE
Баги при регулировке цветовой температуры у RGB светильников в HomeKit

### ISSUE THREAD

**Issue by VolchkovVlad** [sprut/Hub#1958]
** Подробное описание ошибки **
- При управлении цветовой температуры виртуального светильника, через HomeKit. Не применяется цвет, и "Курсор" перескакивает в левую часть круга.

** Как воспроизвести ? **
Создаю виртуальное устройтсво с сервисом "Лампочка"
При создании сервиса, выбираю следующие характеристки:
- Характеристики по умолчанию
- Яркость
- Оттенок
- Насыщеность
- Цветовая температура (Баг ловил с ним и без него)
Дожидаюсь появления устройтсва в Homekit
- Захожу в настройку цветовой температуры
- При выборе цветовой температуры из диапозона, она не применяется.
- Если нажимать на правую часть круга, то "курсор", перескакивает на левую часть круга.

** Ожидаемое поведение **
- При выборе цветовой температуры из диапозона, она применяется к устройству
- Если нажимать на правую часть круга, то "курсор", не должен перескакивавать на левую часть круга.

** Скриншоты/ Логи **
![photo_2023-01-15 09 21 38](https://user-images.githubusercontent.com/44304751/212526129-a89fd883-9e0a-4de0-9066-676ea603e591.jpeg)
[Sprut.Hub_Log_2023.01.15-09_24_48.zip](https://github.com/sprut/Hub/files/10419589/Sprut.Hub_Log_2023.01.15-09_24_48.zip)
<img width="1305" alt="Снимок экрана 2023-01-15 в 09 25 19" src="https://user-images.githubusercontent.com/44304751/212526249-5999186a-c0de-41b4-9dcc-88d1dd02cbcc.png">

** Пожалуйста, заполните следующую информацию: **
SprutHub:
- Установлен на Wirenboard 6.7.2
- [beta] 1.9.6 (9070)

IPhone 12 mini:
- IOS: 16.1.1

** Дополнительные материалы **
https://youtube.com/shorts/YMgWEl_66Hw?feature=share

**Comment by VolchkovVlad** [comment]
UPD: Обнаружил что баг появляется если добавить характеристику "Оттенок"

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
