### ISSUE TITLE
Ошибка в темплейте MQTT\WB\WB\System.json

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#197]
** Подробное описание ошибки **
Кнопка перезагрузки WB не появлялась

1. Исправил кнопка появилась и перезагружает WB
2. Добавил название что Перезагрузка WB

** Скриншоты/ Логи **
![image](https://user-images.githubusercontent.com/60096192/88146188-959d2880-cc0c-11ea-8d28-3d04d6a2a0cc.png)

Исправленный темплейт:
[System.zip](https://github.com/sprut/Hub/files/4958434/System.zip)

 
Прошу добавить в следующую сборку

**Comment by sprut666666** [comment]
1.6.4
