### ISSUE TITLE
управление котлом отопления через несколько датчиков температуры 

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#198]
имеем несколько комнат  и в каждой комнате свой датчик температуры.
подключаем виртуальный термостат 

Задача включать / отключать котел отопления. 
если в любой из комнат температура упала ниже установленной на термостате - включаем котел 
если во всех комнатах температура поднялась выше заданной на термостате - выключаем котел 

или так
если минимальная из всех комнат комнат упала ниже заданой на термостате - включить 
если минимальная из всех комнат комнат выше заданой на термостате - выключить

**Comment by sprut666666** [comment]
Ревизия: 3257
