### ISSUE TITLE
Получение статуса сценария из другого сценария

### ISSUE THREAD

**Issue by amalashin** [sprut/Hub#1992]
** Максимально подробное описание предложения.**
Я, как пользователь-автоматизатор СХ, хочу иметь возможность из блочного сценария получить статус другого сценария (активен/не активен) и иметь возможность инвертировать этот статус (по аналоги с вкл/выкл у сервисов).

** Дополнительные материалы **
Да нету, всё итак ясно.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"

**Comment by amalashin** [comment]
А там меня послали сюда.... окей, режим пинг-понг [on]
