### ISSUE TITLE
Улучшение раздела "Параметры" устройства через систему шаблонов

### ISSUE THREAD

**Issue by alexey-gamov** [sprut/Hub#1994]
**Максимально подробное описание предложения.**

В текущей версии **[beta] 1.9.6 (9070)** в разделе "Параметры" не хватает типа блока "текст", чтобы иметь возможность выводить некоторые статусы/информацию из устройства.

В json шаблоне через секцию <kbd>options</kbd> сейчас можно показать след. типы параметров: 

1. Поле для ввода своего значения _(type: integer/float/string = дефолт)_
2. Поле выбора из предложенного списка _(добавление секции values)_
3. Переключатель true/false _(type: boolean)_

**Предложение:** реализовать <kbd>type: text</kbd> в элементе блока <kbd>options</kbd> для отображения статической информации.

![options-text](https://user-images.githubusercontent.com/4319149/214434280-9bec2c73-4533-4d2c-9c98-040a499efb3c.jpg)

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
