### ISSUE TITLE
ZigBee - _TZE200_dwcarsat A4C138387FC08DE5/F69D

### ISSUE THREAD

**Issue by kmira78** [sprut/Hub#2012]
куплено тут https://aliexpress.ru/item/1005003797507518.html?spm=a2g2w.orderdetail.0.0.41f84aa6ROcsCz&sku_id=12000030818992383

Address: A4C138387FC08DE5/F69D<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>EF00_ManufacturerSpecific<ul><li>0002_Custom: 9</li><li>0012_Custom: 243</li><li>0013_Custom: 354</li><li>0014_Custom: 47</li><li>0015_Custom: 271</li><li>0016_Custom: 613</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 70</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZE200_dwcarsat</li><li>0005_ModelIdentifier: TS0601</li><li>0007_PowerSource: 1</li><li>FFDF_Custom: o</li><li>FFE2_Custom: 54</li><li>FFE4_Custom: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 70</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jan 28 17:49:21 MSK 2023

**Comment by skilett** [comment]
Мой шаблон:
{
  "manufacturer": "_TZE200_dwcarsat",
  "model": "TS0601",
  "manufacturerId": "_TZE200_dwcarsat",
  "modelId": "TS0601",
  "catalogId": -1,
  "services": [
    {
      "name": "Температура",
      "type": "TemperatureSensor",
      "characteristics": [
        {
          "type": "CurrentTemperature",
          "link": {
            "endpoint": 1,
            "cluster": "EF00_ManufacturerSpecific",
            "attribute": "0012_Custom",
            "scale": 0.1
          }
        }
      ]
    },
    { 
        "name": "Влажность",
        "type": "HumiditySensor",
        "characteristics": [
          {
            "type": "CurrentRelativeHumidity",
            "link": {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "attribute": "0013_Custom",
              "scale": 0.1
            }
          }
        ]
      },
      { 
        "name": "CO2",
        "type": "CarbonDioxideSensor",
        "characteristics": [
          {
            "type": "CarbonDioxideLevel",
            "link": {
                "endpoint": 1,
                "cluster": "EF00_ManufacturerSpecific",
                "attribute": "0016_Custom"
              }
          }
        ]
      },
      {
        "name": "Качество воздуха",
        "type": "AirQualitySensor",
        "AirQuality": 1,
        "characteristics":[
          {
            "name": "PM 2.5",
            "type": "PM2_5Density",
            "link": {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "attribute": "0002_Custom"
            }
          },
          {
            "name": "Формальдегид",
            "type": "C_FormaldehydeDensity",
            "link": {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "attribute": "0014_Custom"
            }
          },
          {
            "name": "Летучие органические вещества (VOC)",
            "type": "VOCDensity",
            "link": {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "attribute": "0015_Custom",
              "scale": 0.1
            }
          }
        ]
      }
  ],
  "options": []
}
