### ISSUE TITLE
mcdj3aq

### ISSUE THREAD

**Issue by AlexALu** [sprut/Hub#203]
Address: EC1BBDFFFE68F071/6DB0<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 73</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYST11_wmcdj3aq</li><li>0005_ModelIdentifier: mcdj3aq</li><li>0007_PowerSource: 1</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 128</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Thu Jul 23 17:01:23 MSK 2020

Телеграм: @A_l_e_x_p
В каталоге отсутствует
Куплено здесь https://www.zemismart.com/products/zemismart-tuya-zigbee-roller-shade-motor-for-38mm-tube-alexa-echo-google-home-control-electric-engine-shutter-rod

У меня два мотора с виду одинаковые, но у них разные определяются разные модели.

[Thu Jul 23 14_56_06 MSK 2020.zip](https://github.com/sprut/Hub/files/4966437/Thu.Jul.23.14_56_06.MSK.2020.zip)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/zemismart-tubular-motor
