### ISSUE TITLE
ZB-CL01

### ISSUE THREAD

**Issue by Skull09rus** [sprut/Hub#204]
Address: 00124B001CD6A72C/1CB1<br><br><b>Neighbors</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th></tr><tr><td>000B57FFFE7E314E</td><td>0000</td><td>Coordinator</td><td>true</td><td>Parent</td><td>53</td></tr><tr><td>CCCCCCFFFEAE86B4</td><td>7229</td><td>Router</td><td>true</td><td>Unknown</td><td>31</td></tr><tr><td>000B3CFFFEF17DFF</td><td>BE89</td><td>Router</td><td>true</td><td>Unknown</td><td>53</td></tr><tr><td>000D6FFFFEE41B72</td><td>8BF0</td><td>Router</td><td>true</td><td>Unknown</td><td>72</td></tr><tr><td>0000000000000000</td><td>C262</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td></tr><tr><td>00124B001BD8472A</td><td>236A</td><td>Router</td><td>true</td><td>Unknown</td><td>28</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>4000_SwBuildId: 1.0.6</li><li>0001_ApplicationVersion: 6</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: YSRSAI</li><li>0005_ModelIdentifier: ZB-CL01</li><li>0006_DateCode: 20200514</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 0</li><li>4000_EnhancedCurrentHue: 0</li><li>0001_CurrentSaturation: 0</li><li>4001_EnhancedColorMode: 2</li><li>0002_RemainingTime: 0</li><li>4002_ColorLoopActive: 0</li><li>0003_CurrentX: 24939</li><li>4003_ColorLoopDirection: 0</li><li>0004_CurrentY: 24701</li><li>4004_ColorLoopTime: 25</li><li>4005_ColorLoopStartHue: 8960</li><li>4006_ColorLoopStoredHue: 0</li><li>0007_ColorTemperature: 350</li><li>0008_ColorMode: 2</li><li>400A_ColorCapabilities: 31</li><li>400B_ColorTemperatureMin: 153</li><li>400C_ColorTemperatureMax: 370</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 65535</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br>Last update: Mon Jul 27 18:57:18 MSK 2020

Телеграмм [Borod09](https://t.me/boroda09)
В каталоге нет
Купил [тут](https://ysrsai.aliexpress.ru/store/5431355?spm=a2g0s.9042311.0.0.306933edB3hBMY&_ga=2.110912579.792501122.1595849231-1648335158.1595849231)

**Comment by sprut666666** [comment]
Заказано, как прийдёт добавлю.

**Comment by Skull09rus** [comment]
> Заказано, как прийдёт добавлю.

Может проще было отправить тебе мои ?

**Comment by sprut666666** [comment]
1.6.5
