### ISSUE TITLE
BASICZBR3

### ISSUE THREAD

**Issue by Kopoklok** [sprut/Hub#205]
Oleg, please add Sonoff BASICZBR3 template. Many Thanks!

Address: 00124B001B798853/3236<br><br><b>Neighbors</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th></tr><tr><td>00158D0003A0109B</td><td>FFA7</td><td>Router</td><td>true</td><td>Unknown</td><td>51</td></tr><tr><td>000B57FFFE80CCC8</td><td>0000</td><td>Coordinator</td><td>true</td><td>Unknown</td><td>57</td></tr><tr><td>00158D0003A02C7C</td><td>15E1</td><td>Router</td><td>true</td><td>Unknown</td><td>45</td></tr><tr><td>000B57FFFE9C54D5</td><td>4BA0</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td></tr><tr><td>00158D0003A03621</td><td>D61A</td><td>Router</td><td>true</td><td>Parent</td><td>123</td></tr><tr><td>00158D0003A01128</td><td>71BF</td><td>Router</td><td>true</td><td>Unknown</td><td>60</td></tr><tr><td>00124B001B627AF6</td><td>029C</td><td>Router</td><td>true</td><td>Unknown</td><td>49</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: SONOFF</li><li>0005_ModelIdentifier: BASICZBR3</li><li>0006_DateCode: 20191113</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li></ul></li></ul></li></ul><br>

**Comment by Kopoklok** [comment]
telegram: @Kopoklok 
catalog: https://v2.sprut.ai/catalog/item/itead-sonoff-basic-r3

**Comment by sprut666666** [comment]
Заказано, как прийдёт добавлю.

**Comment by sprut666666** [comment]
1.6.5
