### ISSUE TITLE
Неправильное отображение мощности на устройстве Fibaro Dimmer 2

### ISSUE THREAD

**Issue by Stunt4man** [sprut/Hub#207]
На устройстве Fibaro Dimmer 2 неправильно отображается мощность. Лампа включена показывает 0W. Включаешь , выключаешь ничего не меняется..

<img width="1376" alt="Снимок экрана 2020-07-28 в 8 31 57" src="https://user-images.githubusercontent.com/31995081/88624518-cc14f080-d0af-11ea-86d5-a1021c925480.png">

**Comment by MakeSimpleOrg** [comment]
Версию диммера и данные с вкладки информации (i)

**Comment by Stunt4man** [comment]
Версия  FGD212


<b>Fibargroup - FGD212</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>16</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0102</td></tr><tr><td width=35%>Device Id</td><td>1000</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch MultiLevel</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td> Lifeline</td><td>[node_1_1]</td></tr><tr><td>2</td><td> On/Off(S1)</td><td>[]</td></tr><tr><td>3</td><td> Dimmer(S1)</td><td>[]</td></tr><tr><td>4</td><td> On/Off(S2)</td><td>[]</td></tr><tr><td>5</td><td> Dimmer(S2)</td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 SwitchAll</li><li>V3 Meter<ul><li>Energy: 517.36</li><li>Power: 0</li></ul></li><li>V1 Configuration</li><li>V1 Security</li><li>V1 CRC16Encap</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V4 SensorMultiLevel<ul></ul></li><li>V1 DeviceResetLocally</li><li>V1 AssociationGRPInfo</li><li>V1 NoOperation</li><li>V1 Basic</li><li>V1 FirmwareUpdateMD</li><li>V2 ManufacturerSpecific</li><li>V1 ApplicationStatus</li><li>V3 MultiChannelAssociation</li><li>V5 Alarm</li><li>V2 Association</li><li>V2 MultiChannel</li><li>V2 Protection</li><li>V3 SwitchMultiLevel<ul><li>Primary Type: OFF_ON</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 ZWavePlusInfo</li><li>V2 Version</li><li>V1 SceneActivation</li></ul></li><li>Endpoint 1<ul><li>V3 Meter<ul><li>Energy: 525.61</li><li>Power: Unknown</li></ul></li><li>V3 MultiChannelAssociation</li><li>V5 Alarm</li><li>V2 Association</li><li>V4 SensorMultiLevel<ul><li>Power: 55.6</li></ul></li><li>V3 SwitchMultiLevel<ul><li>Level: 99</li><li>Primary Type: OFF_ON</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 AssociationGRPInfo</li><li>V1 ZWavePlusInfo</li><li>V1 Basic<ul><li>Value: 0</li></ul></li><li>V2 Version</li></ul></li><li>Endpoint 2<ul><li>V3 MultiChannelAssociation</li><li>V2 Association</li><li>V3 SwitchMultiLevel<ul><li>Level: 99</li><li>Primary Type: OFF_ON</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 AssociationGRPInfo</li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li><li>V2 Version</li></ul></li></ul><br>Last update: Fri Jul 31 20:44:14 MSK 2020
