### ISSUE TITLE
[Beta] 1.9.6 (9436) Не верная информация на графиках в алисе

### ISSUE THREAD

**Issue by Tri0L** [sprut/Hub#2076]
## Что случилось?

Spruthub версия: [beta] 1.9.6 (9436)
Графики в алисе показывают неверную температуру снятую с датчиков WSDCGQ11LM.
В то же самое время в логах спрутхаба не тех данных которые отображаются на графиках.

## Как воспроизвести

Опишите подробно как воспроизвести ошибку

1. Подключить датчике по Zigbee (spruthub + raspberry pi 4 + sprut stick)
2. Подключить навык алисы
3. Смотреть график

## Скриншоты

<details>
  <summary>Развернуть</summary>
<img width="1119"  src="https://user-images.githubusercontent.com/1208486/219864779-94807fe1-e9d7-44a4-96e5-7337e647146f.jpeg">
<img width="1119" alt="Снимок экрана 2023-02-18 в 22 17 12" src="https://user-images.githubusercontent.com/1208486/219884155-bfb8a73c-5c35-4ab2-8b5f-599deaf5cd5a.png">

</details>

## Логи

Приложите логи приложения (откройте раздел ... и нажмите ... чтобы скопировать), используйте спойлер

<details>
  <summary>Развернуть</summary>
    <pre>
13:17:50
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-3.7'->'-3.4'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_304757718472
12:57:39
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-3.9'->'-3.7'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_303547063166
12:08:55
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.0'->'-3.9'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_300623009347
12:01:10
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-3.9'->'-4.0'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_300158515299
11:45:12
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.3'->'-3.9'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_299200413594
11:02:41
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.4'->'-4.3'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_296648907112
10:48:54
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.6'->'-4.4'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_295821767978
10:20:30
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.7'->'-4.6'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_294117677678
10:14:16
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.8'->'-4.7'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_293744260302
10:13:46
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.7'->'-4.8'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_293713730430
10:04:00
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.8'->'-4.7'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_293128143097
09:55:36
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-4.9'->'-4.8'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_292623685160
09:08:21
Model.Characteristic
--- C[18.13.15 TemperatureSensor.CurrentTemperature '-5.0'->'-4.9'], ctx: C[18.13.15 TemperatureSensor.CurrentTemperature] <- CLINK[00158D00090E6168]_289788652860
    </pre>
</details>

**Comment by Tri0L** [comment]
Так же, если датчик вовсе недоступен (отключен от Zigbee сети), в Яндексе все равно рисуются графики по каким-то выдуманным данным.

На графике ниже, датчик не подключен к Zigbee сети уже несколько дней. В HK все ок, показывается как недоступный. А в яндексе продолжает жить своей жизнью.)

## Скриншоты

<details>
  <summary>Развернуть</summary>
<img width="1119" alt="Снимок экрана 2023-02-18 в 22 17 12" src="https://user-images.githubusercontent.com/1208486/221557595-3df6700e-bbe1-4cc6-9a6e-57f2c0bb48b8.jpeg">

</details>

**Comment by Batyushin** [comment]
Данные вопросы решаются в реальном времени в чате поддержки

**Comment by Tri0L** [comment]
@Batyushin ну вот прошло больше года, так и не решились пока.

**Comment by Batyushin** [comment]
все-же лучше написать в чате. и в реальном времени разобраться в чем проблема. предоставить доступ к хабу
