### ISSUE TITLE
СХ отваливается от управления девайсами (

### ISSUE THREAD

**Issue by kyruxa** [sprut/Hub#208]
Ник в телеге @kirillgrigorov

Временами в логах появляются сообщения, после которых происходит отваливание СХ от аксессуаров.
Проявляется в том, что плашки в ХК нажимаются, в логах видны изменения статусов, но включения/выключения девайсов в реальности не происходит.

При этом, в логах вот такие сообщения:

```
W | 2020-07-28 | 11:29:09.233 | o.m.ZigBee.dongle.ember.internal.ash.d   349 | ASH: ERROR received (code 81). Disconnecting.
I | 2020-07-28 | 11:29:09.235 | o.m.SprutHub.Controllers.ZigBee.e        400 | Status: OFFLINE
I | 2020-07-28 | 11:29:20.250 | org.makesimple.ZigBee.p                  157 | Serial port [/dev/ttyUSB0] closed
I | 2020-07-28 | 11:29:20.270 | o.m.SprutHub.Controllers.ZigBee.e        180 | Initialising...
I | 2020-07-28 | 11:29:20.452 | org.makesimple.ZigBee.p                  105 | Available Ports: ttyUSB0,ttyAMA0
I | 2020-07-28 | 11:29:23.822 | o.m.SprutHub.Controllers.ZigBee.e        185 | Status: SUCCESS
W | 2020-07-28 | 11:29:23.886 | org.makesimple.ZigBee.dongle.ember.e     269 | Cannot get key: EMBER_TRUST_CENTER_LINK_KEY
```

Помогает рестарт СХ вручную. Логи прикладываю. 
В такие моменты никаких настроек/добавлений не делается, СХ штатно функционирует.

[logs-7.zip](https://github.com/sprut/Hub/files/4989098/logs-7.zip)

**Comment by diamond5170** [comment]
Incorrect template: terneo-thermo.json

**Comment by kyruxa** [comment]
Дело не в темплейте, это старые эксперименты. Отвалы случаются и при отключенном MQTT.

**Comment by diamond5170** [comment]
Дисконнект произошел из за ошибки связанной вероятно с USB (плохой коннект, помехи, какие-то другие неизвестные проблемы).
После этого должен был произойти автоматический реконнект, но реконнекты у нас пока не работают, это известный нам баг.

**Comment by kyruxa** [comment]
Тогда все понятно. Стик стоит в малине в шкафу, скорее всего, с этим связано.

**Comment by kyruxa** [comment]
Но очень прошу починить реконнект, сейчас опять отвалился. Будет печально, если он повиснет, когда дома никого нет.

**Comment by MakeSimpleOrg** [comment]
Если это возможно починить, то конечно починим.

**Comment by sprut666666** [comment]
1.6.4
