### ISSUE TITLE
ШАБЛОН. Добавить. 1 Кнопка Переключатель Scene Switch Moes

### ISSUE THREAD

**Issue by BIGKirillKaa** [sprut/Hub#2083]
<html><body>

Название | Значение
-- | --
Производитель | _TZ3000_axpdxqgu
Модель | TS0041
Прошивка | 31
WEB Build | 1.2.12
API Build | 1.9.5 (8740)

</body>
</html>

Прошу Вас добавить шаблон для 1 кнопочного выключателя ( без реле):
Просьба ограничить **долгое нажатие**, дял корректной работы.
Так же в выключателе имеется светодиод. При нажатии - синий. Хотелось бы указывать данный **светодиод подсветки в сценариях**.

Наименование на АЛи: Переключатель MOES Tuya ZigBee кнопочный беспроводной на батарейках, 2/3 клавиши

Сссылка на АЛИ: [https://aliexpress.ru/item/1005002518213174.html?af=2926_Y6Ljx9&utm_campaign=2926_Y6Ljx9&aff_platform=api-new-link-generate&utm_medium=cpa&sku_id=12000020968587251&cn=2ururqe1l4eflxxcbpvfr9yf9427ml1q&dp=2ururqe1l4eflxxcbpvfr9yf9427ml1q&aff_fcid=cb01705bac344e208eec93520be680f9-1676912009176-03964-_Dc8TZJl&cv=2&aff_fsk=_Dc8TZJl&click_id=9mTZ1XY7oUZEsGM&sk=_Dc8TZJl&aff_trace_key=cb01705bac344e208eec93520be680f9-1676912009176-03964-_Dc8TZJl&terminal_id=6f5bd7e384c3483c955c6e106b12e120&utm_content=2&utm_source=aerkol](url)

Address: 70AC08FFFEB76463/5237<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 66</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_axpdxqgu</li><li>0005_ModelIdentifier: TS0041</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Custom: </li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Feb 20 19:57:53 MSK 2023

**Comment by Batyushin** [comment]
ссылка на Али битая

**Comment by BIGKirillKaa** [comment]
Спасибо за работу !!! 
> ссылка на Али битая
Копирую 1в1 из адресной строки

https://aliexpress.ru/item/1005002518213174.html?af=2926_Y6Ljx9&utm_campaign=2926_Y6Ljx9&aff_platform=api-new-link-generate&utm_medium=cpa&sku_id=12000020968587256&cn=2ururqj31iq0sotl1aqa80n78c7e6cao&dp=2ururqj31iq0sotl1aqa80n78c7e6cao&aff_fcid=c6a370f000834482839dbaf6883db003-1677147174530-06458-_Dc8TZJl&cv=2&aff_fsk=_Dc8TZJl&click_id=9mTZ1XY7oUZEsGM&sk=_Dc8TZJl&aff_trace_key=c6a370f000834482839dbaf6883db003-1677147174530-06458-_Dc8TZJl&terminal_id=6f5bd7e384c3483c955c6e106b12e120&utm_content=2&utm_source=aerkol

[
![изображение](https://user-images.githubusercontent.com/122694805/220878841-dd01c657-f6e1-4630-8c2b-223cceb43130.png)
](url)
