### ISSUE TITLE
Проблема с регулировкой температуры в Gledopto GL-C-006

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Hub#209]
Gledopto GL-C-006 [#126](https://github.com/sprut/Hub/issues/126) добавляется в Spruthub с функционалом GL-C-007(как RGB контроллер).Из функций работает только ON/OFF и яркость.Хотя GL-C-006 должен регулировать только температуру CW и WW каналов.
![GL-C-006](https://user-images.githubusercontent.com/57914147/89131119-16b0c580-d513-11ea-8d42-5ed1fd2d8fcc.jpg)

**Comment by sprut666666** [comment]
1.6.5
