### ISSUE TITLE
Панель отображения температуры в комнате, задание уставки.

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#21]
** Максимально подробное описание предложения.**

Для отображения текущей температуры и задание уставки температуры в конкретном помещении, предлагаю доработать соответствующие файлы WB и СпрутХаб для нормальной работы устройства "Сенсорная панель управления ПУ-3"

Я понимаю, что завязывать умный дом только на виртуальные устройства не правильно, по крайней мере пока в голову человека не внедрят нанокомпьютер. Как правило  в семьях есть консерваторы и новаторы, для одних нужно "покрутить", для других достаточно виртуальных устройств. Управлять виртуальными устройствами за всех не получится, если кому то из домашних или гостей дома захочется ночью сделать прохладней или теплее его постигнет разочарование виртуального мира.

Я долго выбирал максимально простые устройства, позволяющие пользователю посмотреть и изменить температуру. ПУ-3 это устройство из разряда проще некуда. Из портов у ПУ-3 есть только порт RS 485 ModBus и питание от 9 до 25 В постоянного напряжения. Можно видеть текущую температуру от встроенного датчика, задавать необходимую температуру, менять скорость вентилятора, переключать режимы -нагрев, охлаждение, авто, только вентиляция. Скорее всего эти режимы созданы для управления фанкойлами, и режимы авто позволят изменять приток воздуха в зависимости от температуры нагрева, но сегодня только описание простого терморегулятора.

Для тестов я купил одну панельку, подключил ее к соответствующему порту WirenBoard. 

Благодаря помощи Андрея Попова, мне удалось получить и записать данные с интересующих меня адресов.

В /usr/share/wb-mqtt-serial/templates/

я создал файл config-temperature-control-panel.json следующего содержания

{
   "device_type":"TemperatureControlPanel",
   "device":{
      "name":"Temperature Control Panel",
      "id":"temp",
      "max_read_registers":0,
      "channels":[
         {
            "name":"Current temperature",
            "reg_type":"holding",
            "readonly":false,
            "address":0,
            "type":"temperature",
            "scale":0.1,
            "format":"s16"
         },
{
            "name":"Mode",
            "reg_type":"holding",
            "readonly":false,
            "address":3,
            "type":"value",
            "scale":1,
            "format":"s16"
         },
{
            "name":"Speed Vent",
            "reg_type":"holding",
            "readonly":false,
            "address":4,
            "type":"range",
            "scale":1,
            "max":5
         },
{
            "name":"Temperature Set",
            "reg_type":"holding",
            "readonly":false,
            "address":1,
            "type":"range",
            "scale":0.1,
	    "max":35
          },
         {
            "name":"The thermostat works",
            "reg_type":"holding",
            "readonly":false,
            "address":2,
            "type":"switch"

          },
{
            "name":"Outdoor temperature",
            "reg_type":"holding",
            "readonly":false,
            "address":9,
            "type":"value",
            "scale":0.1,
            "format":"s16"
           }
        
      ]
   }
}

Я вообще далек от программирования, и считаю, что файл может быть написан не правильно с точки зрения описания состояния портов и т.д. К тому же я использовал только часть адресов контроллера, другую часть я оставил на дальнейшие эксперименты - а это установка времени,  изменение максимальных и минимальных параметров уставки, запись внешней температуры для отображения ее рядом с текущей.

Вот такой внешний вид получился в устройствах WirenBoard

![image](https://user-images.githubusercontent.com/52490000/61023413-8ad17600-a3b2-11e9-9805-70105e7a9bad.png)

Я могу видеть
- текущую температуру
- режим работы 
- скорость вентилятора
- заданную температуру
- включить выключить устройство
- внешнюю температуру получаемую от других источников (не проверено)

В NodeRed написано node работы с портами и передачи их в apple home.  Соответственно у меня в Доме появился термостат, которым я могу управлять. Все изменения отображаются на физической панельке ПУ-3

Для согласования данного устройства со Спрут Хабом. я написал в 
/mnt/data/makesimple/.SprutHub/data/Templates/WirenBoard/Custom
файл pu3.json

#pu3 https://cityron.ru/catalog/ventilation/sensor-panel-upravleniy-pu3.html
{
    "name": "Термостат PU3",
    "mask": "temp_.*",
    "services": [{
        "name": "Температура",
        "mask": "Current temperature.*",
        "type": "TemperatureSensor"
    }]
}

в котором я извлекаю только текущую температуру со встроенного датчика, для создания в СпрутХабе виртуального термостата.

вот что получилось:

 
![image](https://user-images.githubusercontent.com/52490000/61023968-bbb2aa80-a3b4-11e9-8f8a-c9d44d13a3c7.png)

Виртуальный термостат пробросился в ХомКит и я смог подключить реле для управлением нагрева в конкретной комнате.

Мне не хватает времени и знаний, для написания правильно файла для СпрктХаба, который позвали бы задействовать все реестры адресов ПУ-3 для передачи в него режимов, скорости вентилятора заданной температуры и т.д.

Если есть возможность довести до ума данный проект, буду очень благодарен.

Выражаю огромную благодарность Андрею Попову за терпение и помощь в написании файлов управления.

** Дополнительные материалы **

ссылка на сайт производителя:
https://cityron.ru/catalog/ventilation/sensor-panel-upravleniy-pu3.html
там же есть документация по реестрам Modbus. и файлы для обновления прошивки.
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
1.4.0
