### ISSUE TITLE
Неверно добавляется Gledopto GL-C-008 2ID

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Hub#210]
Gledopto GL-C-008(Версия 2ID)  [#124](https://github.com/sprut/Hub/issues/124) в Spruthub добавляется как устройство с моделью [GL-C-007](https://v2.sprut.ai/catalog/item/gledopto-rgbw-led-controller) и в результате может управлять лишь его RGB каналом.При этом CW/WW канал  остается недоступным для управления.Вообще Gledopto GL-C-008(Версия 2ID) подразумевает работу как 2 отдельных устройства(либо как одно устройство, но управление RGB и CW/WW каналами идет совершенно независимо друг от друга).RGB канал идет как устройство [GL-C-007](https://v2.sprut.ai/catalog/item/gledopto-rgbw-led-controller) а CW/WW канал идет как устройство GL-C-006 [#209](https://github.com/sprut/Hub/issues/209)
Ниже продублирую данные GL-C-008(Версия 2ID) с Spruthub после обновления 
Address: 00124B001F79CFD4/02ED<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 2.0.2</li><li>0001_ApplicationVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-C-007</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 71</li><li>0001_CurrentSaturation: 1</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li><li>Endpoint 15<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br>Last update: Sun Aug 02 23:43:32 MSK 2020

**Comment by sprut666666** [comment]
1.6.5
