### ISSUE TITLE
Не сохраняются настройки цвета у Gledopto GL-C-007 в HomeKit

### ISSUE THREAD

**Issue by Sierra65** [sprut/Hub#212]
При настройке вариантов свечения ленты подключенной к Gledopto GL-C-007 в HomeKit происходит сбрасывание ранее выбранного варианта.
Посмотреть как это происходит можно [**здесь**](https://youtu.be/M7FTffIpyI0)
Версия IOS [13.5.1](url)
Gledopto GL-C-007
Address: 00124B00213777B6/C221<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 2.0.1</li><li>0001_ApplicationVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-C-007</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 90</li><li>0001_CurrentSaturation: 251</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br>Last update: Thu Aug 06 21:55:22 SAKT 2020
Телеграмм Maksim Gordeev

**Comment by MakeSimpleOrg** [comment]
В чем проблема так и не поняли.

**Comment by Sierra65** [comment]
Если смотрели видео, то видно что на плашке выбора цвета свечения ленты раннее выбранный цвет меняется на произвольный.

**Comment by sprut666666** [comment]
1.6.5
