### ISSUE TITLE
Работа спрутхаба на raspberry pi4 SSD

### ISSUE THREAD

**Issue by Sierra65** [sprut/Hub#213]
При переводе raspberry pi4 на работу с SSD по варианту от **[Alex Kvazis]( https://youtu.be/i8zOJvLqVHk)** спрутхаб работает, спрутстик определяется, но невозможно добавить не одно устройство. Все логи скинуты.
Телеграмм Maksim Gordeev

**Comment by ekomrak** [comment]
Проделал аналогичную вещь. Перевел спрутхаб 1.6.4 на SSD. Для ZWave все работает и все добавляется. Для Zigbee не проверял.

**Comment by ekomrak** [comment]
Для истории:
Raspberry PI 4 model B
Спрутхаб на SSD

Если стик вставлен в один из USB 3.0 (в другой USB 3.0 вставлен SSD), то поиск устройств не работает. Если воткнуть стик в USB 2.0, то все работает.

**Comment by MakeSimpleOrg** [comment]
Думаю, это не является проблемой хаба или стика. Аналогичная проблема будет с любым стиком. Нужно просто запомнить как особенность.

**Comment by Sierra65** [comment]
Здравствуйте. 
Дмитрий, это ишью просил открыть Олег что-бы не забыть и самому попробовать. 

С уважением Гордеев Максим.
