### ISSUE TITLE
Добавить Neo Coolcam Z-Wave Smart Power Plug

### ISSUE THREAD

**Issue by Stunt4man** [sprut/Hub#214]
Устройство Neo Coolcam Z-Wave Smart Power Plug

 https://v2.sprut.ai/catalog/item/neo-z-wave-smart-power-plug

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>18</td></tr><tr><td width=35%>Manufacturer Id</td><td>0258</td></tr><tr><td width=35%>Device Type</td><td>0003</td></tr><tr><td width=35%>Device Id</td><td>1087</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td></td><td>[]</td></tr><tr><td>2</td><td></td><td>[]</td></tr><tr><td>3</td><td></td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 SwitchAll</li><li>V0 Association</li><li>V1 SwitchBinary</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li><li>V1 NoOperation</li><li>V2 Version</li><li>V3 Meter</li><li>V1 AssociationGRPInfo</li><li>V1 Configuration</li><li>V1 DeviceResetLocally</li><li>V8 Alarm</li><li>V2 ManufacturerSpecific</li></ul></li></ul><br>Last update: Fri Aug 07 19:34:18 MSK 2020

**Comment by MakeSimpleOrg** [comment]
1.6.4
