### ISSUE TITLE
Добавить поддержку трех устройств Z-WAVE Fibaro 

### ISSUE THREAD

**Issue by Yuanti** [sprut/Hub#216]
Необходимо добавить поддержку устройств Fibaro FGR-223EU, FGS-213EU. Устройства обнаруживаются но не определяются.

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>3</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0303</td></tr><tr><td width=35%>Device Id</td><td>1000</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Class B Motor</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td> Lifeline</td><td>[node_1_1]</td></tr><tr><td>2</td><td> Roller Shutter</td><td>[]</td></tr><tr><td>3</td><td> Slats</td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 DeviceResetLocally</li><li>V1 FirmwareUpdateMD</li><li>V4 SwitchMultiLevel<ul><li>Primary Type: DOWN_UP</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 AssociationGRPInfo</li><li>V2 ManufacturerSpecific</li><li>V1 Security</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V3 CentralScene</li><li>V1 CRC16Encap</li><li>V1 Basic</li><li>V2 Association</li><li>V2 Version</li><li>V2 Protection</li><li>V8 Alarm</li><li>V1 NoOperation</li><li>V1 ApplicationStatus</li><li>V3 MultiChannelAssociation</li><li>V3 Meter<ul><li>Power: Unknown</li><li>Energy: Unknown</li></ul></li><li>V1 ZWavePlusInfo</li><li>V2 MultiChannel</li><li>V1 Configuration</li></ul></li><li>Endpoint 1<ul><li>V2 Association</li><li>V4 SwitchMultiLevel<ul><li>Primary Type: DOWN_UP</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 AssociationGRPInfo</li><li>V8 Alarm</li><li>V1 Security</li><li>V1 ApplicationStatus</li><li>V3 MultiChannelAssociation</li><li>V3 Meter<ul><li>Power: 0</li><li>Energy: Unknown</li></ul></li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li></ul></li><li>Endpoint 2<ul><li>V2 Association</li><li>V4 SwitchMultiLevel<ul><li>Primary Type: DOWN_UP</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 AssociationGRPInfo</li><li>V1 Security</li><li>V1 ApplicationStatus</li><li>V3 MultiChannelAssociation</li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li></ul></li></ul><br>Last update: Sat Aug 08 16:22:40 UTC 2020

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>5</td></tr><tr><td width=35%>Manufacturer Id</td><td>0118</td></tr><tr><td width=35%>Device Type</td><td>0311</td></tr><tr><td width=35%>Device Id</td><td>0304</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td></td><td>[node_1]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 DeviceResetLocally</li><li>V1 FirmwareUpdateMD</li><li>V1 AssociationGRPInfo</li><li>V2 ManufacturerSpecific</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 SceneActuatorConfiguration</li><li>V1 Basic<ul><li>Value: 255</li></ul></li><li>V2 Association</li><li>V1 SceneActivation</li><li>V1 SwitchAll</li><li>V1 SwitchBinary</li><li>V2 Version</li><li>V1 NoOperation</li><li>V1 ZWavePlusInfo</li><li>V1 Configuration</li><li>V2 MultiChannel</li></ul></li><li>Endpoint 1<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li><li>Endpoint 2<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li></ul><br>Last update: Sat Aug 08 16:33:31 UTC 2020

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>7</td></tr><tr><td width=35%>Manufacturer Id</td><td>7FFFFFFF</td></tr><tr><td width=35%>Device Type</td><td>7FFFFFFF</td></tr><tr><td width=35%>Device Id</td><td>7FFFFFFF</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V0 DeviceResetLocally</li><li>V0 FirmwareUpdateMD</li><li>V0 AssociationGRPInfo</li><li>V0 SwitchMultiLevel<ul></ul></li><li>V0 ManufacturerSpecific</li><li>V0 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V0 Security</li><li>V0 CRC16Encap</li><li>V0 CentralScene</li><li>V0 Basic</li><li>V0 Association</li><li>V0 Version</li><li>V0 SwitchBinary</li><li>V0 Protection</li><li>V0 Alarm</li><li>V1 NoOperation</li><li>V0 MultiChannelAssociation</li><li>V0 ApplicationStatus</li><li>V0 ZWavePlusInfo</li><li>V0 Meter</li><li>V0 Configuration</li><li>V0 MultiChannel</li></ul></li></ul><br>Last update: null

**Comment by MakeSimpleOrg** [comment]
Не должно быть 7FFFFFFF. Это значит, что устройство не смогло пройти опрос, нужно переспаривать.

Здесь указана информация сразу для трех устройств, непонятно что где, а у второго производитель вообще TKB Home судя по id 0118.

Один репорт - один баг, одно устройство. Отклонено, пересоздать нормально.
