### ISSUE TITLE
Ошибка в MQTT шаблоне Умный домофон v.6

### ISSUE THREAD

**Issue by MaximSidorov777** [sprut/Hub#2168]
Устройство https://sprut.ai/catalog/item/gelmer-umnyj-domofon-v6

Если прокинуть созданный Звонок в HomeKit, то он срабатывает при перезагрузке платы или при обновлении/перечитывании значений.

У меня коробочная версия, не достать шаблоны, но судя по всему там что-то вроде такого

```
    {
      "name": "Звонок",
   "type": "Doorbell",
      "characteristics": [
        {
          "type": "ProgrammableSwitchEvent",
          "link": {
            "type": "String",
            "topicGet": "(1)/binary_sensor/domofon_incoming_call/state",
             "map": {
              "1": "ON",
              "0": "OFF"
            }
           },
          "validValues": "0,1"
        }
   ]
    }
```

0 — это одиночное нажатие и при прокидывании звонка в HomeKit получается он постоянно орёт на OFF.

По идее надо поставить одиночное нажатие для ON, а OFF вообще убрать.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"

**Comment by MaximSidorov777** [comment]
Диалог был от 15 марта в Шаблонах, оперативно не решилось)
