### ISSUE TITLE
Gledopto GL-C-007 пропадают настройки в спрутхабе

### ISSUE THREAD

**Issue by Sierra65** [sprut/Hub#217]
Если в аксессуарах у Gledopto GL-C-007 в поле Тип изменить с Лампочки на любое другое, то исчезнут все настройки RGBW. Возврат на Лампочку, как и другие действия, настройки не возвращают. Только удаление и новое добавление устройства.
![2020-08-09_13-39-15](https://user-images.githubusercontent.com/67527254/89724224-fb324700-da4b-11ea-9d9d-c0f417b78047.png)
![2020-08-09_13-40-10](https://user-images.githubusercontent.com/67527254/89724225-02f1eb80-da4c-11ea-921a-e6225c7d2deb.png)
![2020-08-09_13-41-17](https://user-images.githubusercontent.com/67527254/89724227-071e0900-da4c-11ea-9253-6f3091755607.png)
![2020-08-09_13-42-27](https://user-images.githubusercontent.com/67527254/89724229-0a18f980-da4c-11ea-9c0f-73db4cfe79df.png)
Address: 00124B00213777B6/C8CD<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 2.0.1</li><li>0001_ApplicationVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-C-007</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 168</li><li>0001_CurrentSaturation: 224</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sun Aug 09 14:25:13 SAKT 2020
Телеграмм: Maksim Gordeev

**Comment by MakeSimpleOrg** [comment]
В 1.6.4 больше нельзя будет менять тип.
