### ISSUE TITLE
Нет обратной связи о выключении  диммера в спрутхаб.

### ISSUE THREAD

**Issue by dantist138** [sprut/Hub#218]
Ошибка в диммерах MDM3 и WB-MRGBW-D.
Когда я кнопкой включаю диммер, то программер в спрутхаб отображается состояние «вкл». Но если я так же кнопкой выключаю диммер , то программер в спрутхаб устройство будто работает в прежнем режиме, то есть отображается состояние «вкл». Если я включённый канал диммера удерживаю кнопкой, и тем самым снижаю яркость до нуля, то в спрутхаб канал корректно отображается сначала снижением мощности, а затем окончательным состоянием «выкл». Может я как-то не так настроил модули? Помогите!
Не знаю , на сколько это может быть связано, но при подключении контроллера возникает такая ошибка (на фото подчеркнул)
![312BACD9-4A6D-49C4-823F-C7704F638CD1](https://user-images.githubusercontent.com/69497934/89860076-c00b5180-dbcc-11ea-97ee-898689be6a47.jpeg)
![EC4B4C9F-296A-425E-8BF9-C9BDD5B94030](https://user-images.githubusercontent.com/69497934/89860078-c3064200-dbcc-11ea-8c2e-15d0302c5fda.jpeg)

**Comment by sprut666666** [comment]
исправлено
