### ISSUE TITLE
прошу добавить устройство popp Strike Lock Control (012501) z-wave

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#219]
прошу добавить устройство popp Strike Lock Control (012501)
z-wave
https://www.popp.eu/products/actuators/strike-lock-control/

открыть закрыть
статус открытия двери

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>25</td></tr><tr><td width=35%>Manufacturer Id</td><td>0154</td></tr><tr><td width=35%>Device Type</td><td>0005</td></tr><tr><td width=35%>Device Id</td><td>0001</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Entry Control</td></tr><tr><td width=35%>Specific Class</td><td>Door Lock</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>true</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 ManufacturerSpecific</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 Battery</li><li>V1 FirmwareUpdateMD</li><li>V1 AssociationGRPInfo</li><li>V1 Configuration</li><li>V5 Alarm</li><li>V1 NoOperation</li><li>V1 ZWavePlusInfo</li><li>V2 Version</li><li>V1 DeviceResetLocally</li><li>V2 Association</li><li>V1 Basic</li><li>V1 DoorLock</li><li>V2 SensorBinary<ul><li>DoorWindow</li></ul></li><li>V1 Security</li></ul></li></ul><br>Last update: Wed Aug 12 12:20:51 MSK 2020

**Comment by MakeSimpleOrg** [comment]
Нужно добавлять пометки New device и Z-Wave, а не Bug, т.к. это не ошибка.

**Comment by bumer0** [comment]
принял спасибо 
правда при создании новой заявки только такие варианты 
см картинку
![image](https://user-images.githubusercontent.com/31984665/90048343-0c918280-dcdc-11ea-8ea1-63133f7f6e80.png)

**Comment by MakeSimpleOrg** [comment]
Добавил шаблон issue для Z-Wave.

**Comment by MakeSimpleOrg** [comment]
r4164
