### ISSUE TITLE
Привод для рулонных штор Tuya ZigBee M515EGZT

### ISSUE THREAD

**Issue by Nollingten** [sprut/Hub#2191]
Определяется вот так:
Address: 60A423FFFEEC4A56/00EB

Structure
Endpoint 1 (SMART_PLUG)
Input
0000_Basic
0000_ZCLVersion: 3
0001_ApplicationVersion: 66
0003_HWVersion: 1
0004_ManufacturerName: _TZE200_nueqqe6k
0005_ModelIdentifier: TS0601
0007_PowerSource: 1
FFDF_Custom:
FFE2_Custom: 31
FFE4_Custom: 0
FFFE_Custom: 0
EF00_ManufacturerSpecific
0001_Control: (null)
0002_PercentControl: 100
0005_ControlBack: (null)
0007_WorkState: (null)
000C_Fault:
0004_Groups
0005_Scenes
Output
0019_OtaUpgrade
000A_Time

Node Descriptor
Aps Flags | 0
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 82
Incoming Transfer Size | 82
Logical Type | Router
Mac Capabilities | [FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]
Manufacturer Code | 4098
Out Going Transfer Size | 82
Stack Compliance | 22

Power Descriptor
Current Power Mode | RECEIVER_ON_IDLE
Available Power Sources | [MAINS]
Current Power Source | MAINS
Power Level | FULL

По факту шаблон вообще не работает. Управление ничего не делает ни с веба, ни с homekit.

**Comment by sprut666666** [comment]
запрос на добавление оформляется так https://wiki.spruthub.ru/Моё_устройство_не_поддерживается._Нет_шаблона._Что_делать%3F
