### ISSUE TITLE
Spirit Z Wave plus Термостат

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#22]
** Подробное описание ошибки **
Не передаются данные термостата в СпрутХаб, а следовательно нельзя использовать.

** Скриншоты/ Логи **

I | 2019-07-20 | 09:31:04.260 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=7C, identifiers=[0]]
I | 2019-07-20 | 09:30:41.970 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=62, identifiers=[0]]
I | 2019-07-20 | 09:30:41.409 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=11, identifiers=[0]]
I | 2019-07-20 | 09:30:04.240 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=3F, identifiers=[0]]
I | 2019-07-20 | 09:29:41.978 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=25, identifiers=[0]]
I | 2019-07-20 | 09:29:41.411 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=D4, identifiers=[0]]
I | 2019-07-20 | 09:29:11.997 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Pressure Measurement: 33725/1 -> 0/1, cluster=0403, TID=0C, reports=[Attribute Report: attributeDataType=SIGNED_16_BIT_INTEGER, attributeIdentifier=0, attributeValue=992, Attribute Report: attributeDataType=SIGNED_8_BIT_INTEGER, attributeIdentifier=20, attributeValue=-1, Attribute Report: attributeDataType=SIGNED_16_BIT_INTEGER, attributeIdentifier=16, attributeValue=9925]]
I | 2019-07-20 | 09:29:11.980 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Relative Humidity Measurement: 33725/1 -> 0/1, cluster=0405, TID=0B, reports=[Attribute Report: attributeDataType=UNSIGNED_16_BIT_INTEGER, attributeIdentifier=0, attributeValue=6224]]
I | 2019-07-20 | 09:29:11.960 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Temperature Measurement: 33725/1 -> 0/1, cluster=0402, TID=0A, reports=[Attribute Report: attributeDataType=SIGNED_16_BIT_INTEGER, attributeIdentifier=0, attributeValue=2087]]
I | 2019-07-20 | 09:29:04.266 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=02, identifiers=[0]]
I | 2019-07-20 | 09:28:51.469 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Basic: 14173/1 -> 0/1, cluster=0000, TID=F4, reports=[Attribute Report: attributeDataType=STRUCT2, attributeIdentifier=65281, attributeValue={16=8737, 0=33, 100=768, 57=0, 109=15594}]]
I | 2019-07-20 | 09:28:41.966 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=E8, identifiers=[0]]
I | 2019-07-20 | 09:28:41.408 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=97, identifiers=[0]]
I | 2019-07-20 | 09:28:04.236 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=C4, identifiers=[0]]
I | 2019-07-20 | 09:27:41.988 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=AB, identifiers=[0]]
I | 2019-07-20 | 09:27:41.426 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=5A, identifiers=[0]]
I | 2019-07-20 | 09:27:04.244 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=87, identifiers=[0]]
I | 2019-07-20 | 09:26:41.965 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=6E, identifiers=[0]]
I | 2019-07-20 | 09:26:41.405 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=1D, identifiers=[0]]
I | 2019-07-20 | 09:26:26.877 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Basic: 18546/1 -> 0/1, cluster=0000, TID=5D, reports=[Attribute Report: attributeDataType=STRUCT2, attributeIdentifier=65281, attributeValue={0=0, 33=-26112, 100=768, 215=14309, 57=0, 9=1025}]]
I | 2019-07-20 | 09:26:10.323 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Basic: 18106/1 -> 0/1, cluster=0000, TID=FC, reports=[Attribute Report: attributeDataType=STRUCT2, attributeIdentifier=65281, attributeValue={100=768, 7=0, 57=0, 154=2064, 206=15245}]]
I | 2019-07-20 | 09:26:04.252 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=4A, identifiers=[0]]
I | 2019-07-20 | 09:25:41.997 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=30, identifiers=[0]]
I | 2019-07-20 | 09:25:41.432 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=DF, identifiers=[0]]
I | 2019-07-20 | 09:25:13.989 | org.makesimple.SprutHub.Homekit.http.a   42  | New homekit connection from /192.168.88.108:52186 /192.168.88.108:52186
I | 2019-07-20 | 09:25:04.252 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=0D, identifiers=[0]]
I | 2019-07-20 | 09:24:41.967 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=F3, identifiers=[0]]
I | 2019-07-20 | 09:24:41.412 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=A2, identifiers=[0]]
I | 2019-07-20 | 09:24:04.235 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=D0, identifiers=[0]]
I | 2019-07-20 | 09:23:41.986 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=B6, identifiers=[0]]
I | 2019-07-20 | 09:23:41.420 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=65, identifiers=[0]]
W | 2019-07-20 | 09:23:08.707 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: alarm_power
W | 2019-07-20 | 09:23:08.688 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: alarm_system
W | 2019-07-20 | 09:23:08.673 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: thermostat_setpoint
W | 2019-07-20 | 09:23:08.663 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: thermostat_setpoint
W | 2019-07-20 | 09:23:08.646 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: eurotronic_spirit_00_000_thermostat_mode
I | 2019-07-20 | 09:23:08.621 | o.m.SprutHub.Controllers.ZWave.c         102 | 3: RadiatorControl, Eurotronics, Spirit Thermostatic Valve, Spirit
I | 2019-07-20 | 09:23:08.556 | o.m.SprutHub.Controllers.ZWave.j         147 | NODE 3: BASIC_TYPE_ROUTING_SLAVE GENERIC_TYPE_THERMOSTAT SPECIFIC_TYPE_THERMOSTAT_GENERAL_V2
I | 2019-07-20 | 09:23:08.407 | o.m.SprutHub.Controllers.ZWave.j         82  | NODE 3: Device discovery completed
W | 2019-07-20 | 09:23:08.238 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: alarm_power
W | 2019-07-20 | 09:23:08.224 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: alarm_system
W | 2019-07-20 | 09:23:08.217 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: thermostat_setpoint
W | 2019-07-20 | 09:23:08.201 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: thermostat_setpoint
W | 2019-07-20 | 09:23:08.195 | o.m.SprutHub.Controllers.ZWave.c         251 | Unknown type: eurotronic_spirit_00_000_thermostat_mode
I | 2019-07-20 | 09:23:08.153 | o.m.SprutHub.Controllers.ZWave.c         102 | 2: RadiatorControl, Eurotronics, Spirit Thermostatic Valve, Spirit
I | 2019-07-20 | 09:23:06.949 | o.m.SprutHub.Controllers.ZWave.j         147 | NODE 2: BASIC_TYPE_ROUTING_SLAVE GENERIC_TYPE_THERMOSTAT SPECIFIC_TYPE_THERMOSTAT_GENERAL_V2
I | 2019-07-20 | 09:23:06.781 | o.m.SprutHub.Controllers.ZWave.j         82  | NODE 2: Device discovery completed
I | 2019-07-20 | 09:23:04.249 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=93, identifiers=[0]]
I | 2019-07-20 | 09:22:55.343 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Basic: 14173/1 -> 0/1, cluster=0000, TID=88, reports=[Attribute Report: attributeDataType=STRUCT2, attributeIdentifier=65281, attributeValue={16=8737, 0=33, 100=768, 57=0, 109=15594}]]
I | 2019-07-20 | 09:22:52.555 | o.m.Z.s.SerialApiGetInitDataMessageClass 64  | ZWave Controller is Primary Controller
I | 2019-07-20 | 09:22:52.547 | o.m.Z.s.SerialApiGetInitDataMessageClass 63  | ZWave Controller using Controller API
I | 2019-07-20 | 09:22:52.539 | o.m.Z.s.SerialApiGetInitDataMessageClass 55  | NODE 3: Node found
I | 2019-07-20 | 09:22:52.533 | o.m.Z.s.SerialApiGetInitDataMessageClass 55  | NODE 2: Node found
I | 2019-07-20 | 09:22:52.522 | o.m.Z.s.SerialApiGetInitDataMessageClass 55  | NODE 1: Node found
I | 2019-07-20 | 09:22:52.410 | o.m.Z.s.GetSucNodeIdMessageClass         35  | NODE 1: Node is SUC.
I | 2019-07-20 | 09:22:52.341 | Z.s.SerialApiGetCapabilitiesMessageClass 48  | Device ID      = 0x4
I | 2019-07-20 | 09:22:52.335 | Z.s.SerialApiGetCapabilitiesMessageClass 47  | Device Type    = 0x4
I | 2019-07-20 | 09:22:52.330 | Z.s.SerialApiGetCapabilitiesMessageClass 46  | Manufacture ID = 0x0
I | 2019-07-20 | 09:22:52.326 | Z.s.SerialApiGetCapabilitiesMessageClass 45  | API Version    = 7.0
I | 2019-07-20 | 09:22:52.266 | o.m.Z.s.MemoryGetIdMessageClass          33  | Got MessageMemoryGetId response. Home id = 0xe0899104, Controller Node id = 1
I | 2019-07-20 | 09:22:52.138 | o.m.Z.s.GetVersionMessageClass           37  | Got MessageGetVersion response. Version=Z-Wave 7.11, Library Type=7
I | 2019-07-20 | 09:22:50.610 | .m.Z.ZWaveController$InitializeDelayTask 114 | Initialising network
I | 2019-07-20 | 09:22:41.963 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=79, identifiers=[0]]
I | 2019-07-20 | 09:22:41.404 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=28, identifiers=[0]]
I | 2019-07-20 | 09:22:40.566 | org.makesimple.ZWave.ZWaveController     92  | Starting ZWave controller
I | 2019-07-20 | 09:22:39.799 | o.m.ZWave.ZWaveSerialHandlerJSSC         42  | Connecting to serial port '/dev/ttyUSB0'
I | 2019-07-20 | 09:22:39.786 | o.m.SprutHub.Controllers.ZWave.c         62  | Loaded 1413 ZWave templates
I | 2019-07-20 | 09:22:04.244 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=55, identifiers=[0]]
I | 2019-07-20 | 09:22:00.090 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesResponse [Level Control: 29057/1 -> 0/1, cluster=0008, TID=29, records=[ReadAttributeStatusRecord [attributeDataType=UNSIGNED_8_BIT_INTEGER, attributeIdentifier=0, status=SUCCESS, attributeValue=127]]]
I | 2019-07-20 | 09:21:59.996 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesResponse [On/Off: 29057/1 -> 0/1, cluster=0006, TID=28, records=[ReadAttributeStatusRecord [attributeDataType=BOOLEAN, attributeIdentifier=0, status=SUCCESS, attributeValue=false]]]
I | 2019-07-20 | 09:21:59.988 | o.m.S.Controllers.ZigBee.Controls.OnOff  134 | 086BD7FFFE08ABC9: ZigBee attribute reports 1 1 ZclAttribute [cluster=On/Off, id=0, name=On Off, dataType=BOOLEAN, lastValue=false, lastReportTime=Sat Jul 20 09:21:59 MSK 2019]
I | 2019-07-20 | 09:21:59.879 | o.m.S.Controllers.ZigBee.Controls.OnOff  134 | 086BD7FFFE08ABC9: ZigBee attribute reports 1 1 ZclAttribute [cluster=On/Off, id=0, name=On Off, dataType=BOOLEAN, lastValue=false, lastReportTime=Sat Jul 20 09:21:59 MSK 2019]
I | 2019-07-20 | 09:21:59.867 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesResponse [On/Off: 29057/1 -> 0/1, cluster=0006, TID=27, records=[ReadAttributeStatusRecord [attributeDataType=BOOLEAN, attributeIdentifier=0, status=SUCCESS, attributeValue=false]]]
I | 2019-07-20 | 09:21:59.624 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesResponse [On/Off: 14173/1 -> 0/1, cluster=0006, TID=26, records=[ReadAttributeStatusRecord [attributeDataType=BOOLEAN, attributeIdentifier=0, status=SUCCESS, attributeValue=false]]]
I | 2019-07-20 | 09:21:59.620 | o.m.S.Controllers.ZigBee.Controls.OnOff  134 | 00158D0003160399: ZigBee attribute reports 1 1 ZclAttribute [cluster=On/Off, id=0, name=On Off, dataType=BOOLEAN, lastValue=false, lastReportTime=Sat Jul 20 09:21:59 MSK 2019]
I | 2019-07-20 | 09:21:59.512 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesResponse [On/Off: 18546/1 -> 0/1, cluster=0006, TID=25, records=[ReadAttributeStatusRecord [attributeDataType=BOOLEAN, attributeIdentifier=0, status=SUCCESS, attributeValue=false]]]
I | 2019-07-20 | 09:21:59.506 | o.m.S.Controllers.ZigBee.Controls.OnOff  134 | 00158D000290A42A: ZigBee attribute reports 1 1 ZclAttribute [cluster=On/Off, id=0, name=On Off, dataType=BOOLEAN, lastValue=false, lastReportTime=Sat Jul 20 09:21:59 MSK 2019]
I | 2019-07-20 | 09:21:59.442 | o.m.S.Controllers.ZigBee.Controls.OnOff  134 | 00158D0002F2FDCD: ZigBee attribute reports 1 1 ZclAttribute [cluster=On/Off, id=0, name=On Off, dataType=BOOLEAN, lastValue=false, lastReportTime=Sat Jul 20 09:21:59 MSK 2019]
I | 2019-07-20 | 09:21:59.421 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesResponse [On/Off: 18106/1 -> 0/1, cluster=0006, TID=24, records=[ReadAttributeStatusRecord [attributeDataType=BOOLEAN, attributeIdentifier=0, status=SUCCESS, attributeValue=false]]]
I | 2019-07-20 | 09:21:41.986 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18546/1 -> 0/1, cluster=000A, TID=3C, identifiers=[0]]
I | 2019-07-20 | 09:21:41.416 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 18106/1 -> 0/1, cluster=000A, TID=EB, identifiers=[0]]
I | 2019-07-20 | 09:21:21.956 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ConfigureReportingResponse [Level Control: 29057/1 -> 0/1, cluster=0008, TID=1F, status=SUCCESS, records=null]
I | 2019-07-20 | 09:21:21.919 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ConfigureReportingResponse [On/Off: 29057/1 -> 0/1, cluster=0006, TID=1E, status=SUCCESS, records=null]
I | 2019-07-20 | 09:21:04.236 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReadAttributesCommand [Time: 14173/1 -> 0/1, cluster=000A, TID=18, identifiers=[0]]
I | 2019-07-20 | 09:21:02.034 | o.m.SprutHub.Controllers.ZigBee.b        634 | Command: ReportAttributesCommand [Basic: 18546/1 -> 0/1, cluster=0000, TID=12, reports=[Attribute Report: attributeDataType=STRUCT2, attributeIdentifier=65281, attributeValue={0=0, 33=-26112, 100=768, 215=14309, 57=0, 9=1025}]]
I | 2019-07-20 | 09:20:59.754 | o.m.SprutHub.Controllers.ZigBee.a        239 | 086BD7FFFE08ABC9: New control: LevelControl, 1
I | 2019-07-20 | 09:20:58.914 | o.m.SprutHub.Controllers.ZigBee.a        239 | 086BD7FFFE08ABC9: New control: OnOff, 1
I | 2019-07-20 | 09:20:58.916 | o.m.SprutHub.Controllers.ZigBee.a        223 | 00158D000290A42A: Unsupported cluster: d
I | 2019-07-20 | 09:20:58.924 | o.m.SprutHub.Controllers.ZigBee.a        203 | 00158D0002B89C10: New control: OnOff, 1
I | 2019-07-20 | 09:20:58.922 | o.m.SprutHub.Controllers.ZigBee.a        223 | 00158D0002F2FDCD: Unsupported cluster: d
I | 2019-07-20 | 09:20:58.919 | o.m.SprutHub.Controllers.ZigBee.b        356 | Unsupported device: 00158D0002B0E7DD, LUMI, lumi.sensor_switch.aq3
I | 2019-07-20 | 09:20:58.909 | o.m.SprutHub.Controllers.ZigBee.b        356 | Unsupported device: 00158D0002B0FA0D, LUMI, lumi.sensor_switch.aq3
I | 2019-07-20 | 09:20:58.899 | o.m.SprutHub.Controllers.ZigBee.a        239 | 00158D000290A42A: New control: OnOff, 1
I | 2019-07-20 | 09:20:58.896 | o.m.SprutHub.Controllers.ZigBee.a        239 | 00158D0002F2FDCD: New control: OnOff, 1
I | 2019-07-20 | 09:20:58.874 | o.m.SprutHub.Controllers.ZigBee.a        239 | 00158D0003160399: New control: OnOff, 1
I | 2019-07-20 | 09:20:58.847 | o.m.SprutHub.Controllers.ZigBee.a        223 | 086BD7FFFE08ABC9: Unsupported cluster: F
I | 2019-07-20 | 09:20:58.810 | o.m.SprutHub.Controllers.ZigBee.a        223 | 00158D0002B0FA0D: Unsupported cluster: Y
I | 2019-07-20 | 09:20:58.807 | o.m.SprutHub.Controllers.ZigBee.a        223 | 00158D0002B0E7DD: Unsupported cluster: Y
I | 2019-07-20 | 09:20:58.805 | o.m.SprutHub.Controllers.ZigBee.a        223 | 086BD7FFFE08ABC9: Unsupported cluster: ar

** Дополнительные материалы **
ссылка на продавца:
https://www.z-wave.ru/shop/category/termostaty/eurotronic-spirit.html

данные во вкладке контроллеры:

![image](https://user-images.githubusercontent.com/52490000/61575185-75a2c880-aad1-11e9-96de-76d529a174c9.png)

данные во вкладке аксессуары:

![image](https://user-images.githubusercontent.com/52490000/61575216-c9151680-aad1-11e9-855e-fa7a113a54c7.png)

**Comment by diamond5170** [comment]
Не актуально
