### ISSUE TITLE
FB56-ZCW20FB1.2

### ISSUE THREAD

**Issue by Skull09rus** [sprut/Hub#220]
Address: 00124B001F9737F1/CFCF<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>4000_SwBuildId: 1.0.0</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: FeeBit  RGBW    </li><li>0005_ModelIdentifier: FB56-ZCW20FB1.2</li><li>0006_DateCode: 20160406</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 0</li><li>4000_EnhancedCurrentHue: 1</li><li>0001_CurrentSaturation: 254</li><li>4001_EnhancedColorMode: 2</li><li>0002_RemainingTime: 0</li><li>4002_ColorLoopActive: 0</li><li>0003_CurrentX: 20480</li><li>4003_ColorLoopDirection: 0</li><li>0004_CurrentY: 21845</li><li>4004_ColorLoopTime: 25</li><li>4005_ColorLoopStartHue: 8960</li><li>4006_ColorLoopStoredHue: 0</li><li>0007_ColorTemperature: 222</li><li>0008_ColorMode: 2</li><li>400A_ColorCapabilities: 31</li><li>400B_ColorTemperatureMin: 210</li><li>400C_ColorTemperatureMax: 234</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 224</li><li>0001_RemainingTime: 65535</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br>Last update: Wed Aug 12 20:00:36 MSK 2020
Телеграмм [Borodа09](https://t.me/boroda09)
В каталоге нет
Купил [тут](https://ysrsai.aliexpress.ru/store/5431355?spm=a2g0s.9042311.0.0.306933edB3hBMY&_ga=2.110912579.792501122.1595849231-1648335158.1595849231)

**Comment by sprut666666** [comment]
Заказано, как прийдёт добавлю.

**Comment by sprut666666** [comment]
1.6.5
