### ISSUE TITLE
SSHM-I1

### ISSUE THREAD

**Issue by meowlab-net** [sprut/Hub#222]
Address: 000D6F00132AB2CE/7E08<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>4000_SwBuildId: 1.1.1</li><li>0001_ApplicationVersion: 34</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 16</li><li>0004_ManufacturerName: GS</li><li>0005_ModelIdentifier: SSHM-I1</li><li>0006_DateCode: 2019.12.2</li><li>0007_PowerSource: 3</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0010_IasCieAddress: 0000000000000000</li><li>0001_ZoneType: 40</li><li>0011_ZoneId: 255</li><li>0002_ZoneStatus: 32</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 151</li><li>0034_BatteryRatedVoltage: 32</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sat Aug 15 15:45:28 MSK 2020

Telegram: @meowlab
Покупал тут https://shop.tricolor.tv/catalog/umnyy-dom/datchik-dyma-gs-sshm-i1/?client=private&section=smart&wall=8SOLO1

**Comment by sprut666666** [comment]
1.6.4

**Comment by meowlab-net** [comment]
После обновления на 1.6.4 датчик не заработал.
Включив в настройках стика "Показать все события" в логах следкющее:

При включении устройства (вставил батарею)
ZoneStatusChangeNotificationCommand [0500_IasZone: D022/1 -> 0000/1, TID=03, Input, zoneStatus=32, extendedStatus=0, zoneId=255, delay=0]	

При нажатии на кнопку тест - устройство 3 раза подает сигнал
ZoneStatusChangeNotificationCommand [0500_IasZone: D022/1 -> 0000/1, TID=02, Input, zoneStatus=33, extendedStatus=0, zoneId=255, delay=0]	
ZoneStatusChangeNotificationCommand [0500_IasZone: D022/1 -> 0000/1, TID=3B, Input, zoneStatus=32, extendedStatus=0, zoneId=0, delay=0]	

При срабатывании датчика
ZoneStatusChangeNotificationCommand [0500_IasZone: D022/1 -> 0000/1, TID=06, Input, zoneStatus=33, extendedStatus=0, zoneId=255, delay=0]

Датчик орет. В инструкции указано "Если вы убедились в отсутствии пожара при срабатывании устройства, то нажмите и удерживайте 3 сек. кнопку на лицевой стороне датчика для отключения звукового оповещения"
При нажатии на кнопку датчик перестает орать, но в логе периодически ппоявляются записи
ZoneStatusChangeNotificationCommand [0500_IasZone: D022/1 -> 0000/1, TID=06, Input, zoneStatus=33, extendedStatus=0, zoneId=255, delay=0] и при нажатии на кнопку тест - тестирование не производится (сигнала нет).

Похоже на то, что датчику нужно сделать  rearm.
Если сбросить датчик по питанию, при включении в логе
ZoneStatusChangeNotificationCommand [0500_IasZone: D022/1 -> 0000/1, TID=03, Input, zoneStatus=32, extendedStatus=0, zoneId=255, delay=0] и тест работает.
