### ISSUE TITLE
Ошибка скачивания firmware.tar.gz при установке

### ISSUE THREAD

**Issue by HexMaster-RU** [sprut/Hub#2229]
** Подробное описание ошибки **
Ошибка скачивания firmware.tar.gz при первоначальной установке.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Чистый Wirenboard 6
2. Выполнить wget -qO - https://makesimple.org/scripts/install.sh | bash
3. Получить ошибку скачивания firmware.tar.gz

** Ожидаемое поведение **
Установка прошла без ошибок.

** Скриншоты/ Логи **
/mnt/data/makesimpl 100%[===================>]  21.64M   785KB/s    in 17s
web2.tar.gz: OK
/mnt/data/makesimpl 100%[===================>] 738.71K  1.18MB/s    in 0.6s
jni.tar.gz: OK
Retrying in 3 seconds...
Retrying in 3 seconds...
Failed to download 'http://makesimple.org/release/firmware.tar.gz' please check internet connection!
/mnt/data/makesimpl 100%[===================>]  25.83M  1.48MB/s    in 16s
main.tar.gz: OK
Configuring ...
/mnt/data/makesimpl 100%[===================>]    1011  --.-KB/s    in 0s
backup.sh: OK

**Comment by SmartHaven** [comment]
Это не ошибка, этот файл отсутствует на релизной ветке и не требуется. После следующего релиза будет скачиваться.
