### ISSUE TITLE
Ошибка OTA upgrade Philips SML001

### ISSUE THREAD

**Issue by meowlab-net** [sprut/Hub#223]
SH 1.6.4

Подключаю датчик движения Philips SML001
Датчик определяется, все работает. В контроллере:
934C/0017880102118504	[5] Универсальный датчик	ONLINE	Philips	JOIN_COMPLETE

После этого начинается обновление firmware датчика. Много записей типа:
ImageBlockCommand [0019_OtaUpgrade: 934C/2 -> 0000/1, TID=96, Output, fieldControl=2, manufacturerCode=4107, imageType=269, fileVersion=1107323831, fileOffset=237880, maximumDataSize=64, requestNodeAddress=null, blockRequestDelay=0

По завершению обновления в логе:
0017880102118504/934C : Firmware update - DONE

После обновления в контроллере статус датчика START_POLLING вместо JOIN_COMPLETE: 
934C/0017880102118504	[5] Универсальный датчик	ONLINE	Philips	START_POLLING

Если запустить поиск устройств на контроллере и "переспарить" датчик, он нормально определяется, имеет статус JOIN_COMPLETE. После этого опять стартует OTA upgrade  и все повторяется по кругу.

Повторил несколько раз и на SprutStick Pro и на SprutStick Pro WB.

Нижне - информация о датчике.

Address: 0017880102118504/934C<br><br><b>Bindings</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>2</td><td>IEEE</td><td>000B57FFFE7E2D69/1</td><td>0406_OccupancySensing</td></tr><tr><td>2</td><td>IEEE</td><td>000B57FFFE7E2D69/1</td><td>0400_IlluminanceMeasurement</td></tr><tr><td>2</td><td>IEEE</td><td>000B57FFFE7E2D69/1</td><td>0402_TemperatureMeasurement</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, RECHARGABLE_BATTERY, MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 6.1.0.18912</li><li>0001_ApplicationVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: SML001</li><li>0007_PowerSource: 3</li></ul></li><li>0004_Groups<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 8417</li></ul></li><li>0001_PowerConfiguration<ul><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 3306</li></ul></li><li>0003_Identify<ul></ul></li><li>0406_OccupancySensing<ul><li>0000_Occupancy: 1</li><li>0010_PirOccupiedToUnoccupiedDelay: 60</li><li>0030_MotionDetectionSensitivity: 1</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sun Aug 16 20:50:31 MSK 2020

**Comment by sprut666666** [comment]
1.6.6
