### ISSUE TITLE
прошу добавить 2-х клавишную кнопку

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#225]
Прошу добавить 
https://v2.sprut.ai/catalog/item/akara-uireless-remote-suitch

Address: 00158D0002387F0C/FB01<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 5</li><li>FF01_Custom: {1=3065, 3=24, 4=424, 5=59, 6=1, 8=5125, 10=0}</li><li>0005_ModelIdentifier: lumi.sensor_86sw2</li></ul></li><li>0012_MultistateInputBasic<ul></ul></li><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>FFFF_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>FFFF_ManufacturerSpecific<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul></ul></li><li>0003_Identify<ul></ul></li></ul></li><li>Output<ul><li>0012_MultistateInputBasic<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0003_Identify<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li></ul><br>Last update: Mon Aug 17 20:44:09 MSK 2020

**Comment by bumer0** [comment]
lumi.sensor_86sw2

**Comment by sprut666666** [comment]
1.6.5
