### ISSUE TITLE
Проблемы с цветом и рывками Philips Hue play Light Bar

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#227]
** Подробное описание ошибки **
https://v2.sprut.ai/catalog/item/philips-play-light-bar
Две проблемы:
А) При изменении цвета или яркости через Home Kit освещение меняется рывками - скорее всего проблема с слишком быстрым срабатыванием
Б) Цвет при выборе в хоумките не совпадает с освещением через устройство. Через Hue Hub показывает другой цвет.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
А)
1)Подключаем лампу через спрутхаб
2)Включаем лампу через HomeKit
3)Начинаем плавно перемещает ползунок по цветовой палитре
4)Пробуем покрутить яркость
5)Получаем свет , переключающийся рывками.

Б)
1) Подключаем лампу через спрутхаб
2)Включаем лампу через HomeKit
3)Начинаем плавно перемещает ползунок по цветовой палитре
4) Замечаем, что цвет на цветовой палитре в HomeKit и фактический на лампе отличается.
5) Подключаем вторую лампу к Hue Hub
6) В хоумкит выставляем одинаковые цвета на лампах
7) Замечаем, что цвета различаются.
8) Обязатаельно смотрим, что в принципе вся цветовая палитка на Hue лампе, подключенная через Sprut сбита.

** Ожидаемое поведение **
1) Плавное изменение яркости и цвета в хоумките
2) Корректное отображение фактического цвета при управлении через Home Kit

** Скриншоты/ Логи **
Фотография двух ламп: одна через Sprut , вторая через Hue Hub
https://drive.google.com/file/d/14_w3pLCjlJvPa6DgA44nmTPu0wsAvAMB/view?usp=sharing

** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, 13.6]

** Дополнительные материалы **
Записал видео искать в чате телеграмм (Sprut.stick ZigBee 2 Pro) по сообщению:

@sprut записал для тебя по поводу hue лампы

**Comment by sprut666666** [comment]
1.6.5
