### ISSUE TITLE
ntesis ME-AC-MBS-1 INMBSMIT001I000 Интерфейс ModBus для кондиционеров Mitsubishi Electric серии Domestic Intesis

### ISSUE THREAD

**Issue by AnatolyLap** [sprut/Hub#2270]
https://intesis.su/catalog/shlyuzy_konditsionerov/modbus_ac/37233/

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"

**Comment by AnatolyLap** [comment]
Это issue - просьба сделать шаблон . Почему её закрыли ?

**Comment by AnatolyLap** [comment]
@sprut666666 ?
