### ISSUE TITLE
TX_NAK: EMBER_MESSAGE_TOO_LONG

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#228]
каждые 2 часа вот так 

06:54:58 | 000B57FFFE391D79/A217 : Firmware update - DONE |  
-- | -- | --
06:54:53 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:48 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:43 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:38 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:33 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:28 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:23 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:18 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:13 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:08 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:53:59 | 000B57FFFE391D79/A217 : Firmware update - START, ZigBeeOtaFile [headerVersion=256, headerLength=56, headerFieldControl=0, manufacturerCode=4476, imageType=2101, fileVersion=12214572, stackVersion=ZIGBEE_PRO, headerString=EBL tradfri_light_basic, imageSize=168318] |  
06:43:30 | New homekit connection from /192.168.1.7:63155 |  
06:43:30 | Terminated homekit connection from /192.168.1.7:63120 |  
06:10:53 | New homekit connection from /192.168.1.41:50535 |  
06:10:52 | Terminated homekit connection from /192.168.1.41:50531 |  
06:06:00 | New homekit connection from /192.168.1.41:50531 |  
06:06:00 | Terminated homekit connection from /192.168.1.41:50525 |  
06:02:55 | New homekit connection from /192.168.1.41:50525 |  
06:02:54 | Terminated homekit connection from /192.168.1.41:50517 |  
05:55:44 | New homekit connection from /192.168.1.41:50517 |  
05:55:44 | Terminated homekit connection from /192.168.1.41:50487 |  
05:53:57 | New homekit connection from /192.168.1.7:63120 |  
05:53:56 | Terminated homekit connection from /192.168.1.7:63111 |  
07:42:38 | New homekit connection from /192.168.1.28:59086 |  
07:42:38 | Terminated homekit connection from /192.168.1.28:58876 |  
07:02:49 | New homekit connection from /192.168.1.7:63165 |  
07:02:49 | Terminated homekit connection from /192.168.1.7:63155 |  
06:54:58 | 000B57FFFE391D79/A217 : Firmware update - DONE |  
06:54:53 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:48 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:43 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:38 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:33 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:28 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:23 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:18 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:13 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:54:08 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
06:53:59 | 000B57FFFE391D79/A217 : Firmware update - START, ZigBeeOtaFile [headerVersion=256, headerLength=56, headerFieldControl=0, manufacturerCode=4476, imageType=2101, fileVersion=12214572, stackVersion=ZIGBEE_PRO, headerString=EBL tradfri_light_basic, imageSize=168318] |  
06:43:30 | New homekit connection from /192.168.1.7:63155 |  
06:43:30 | Terminated homekit connection from /192.168.1.7:63120 |  
06:10:53 | New homekit connection from /192.168.1.41:50535 |  
06:10:52 | Terminated homekit connection from /192.168.1.41:50531 |  
06:06:00 | New homekit connection from /192.168.1.41:50531 |  
06:06:00 | Terminated homekit connection from /192.168.1.41:50525 |  
06:02:55 | New homekit connection from /192.168.1.41:50525 |  
06:02:54 | Terminated homekit connection from /192.168.1.41:50517 |  
05:55:44 | New homekit connection from /192.168.1.41:50517 |  
05:55:44 | Terminated homekit connection from /192.168.1.41:50487 |  
05:53:57 | New homekit connection from /192.168.1.7:63120 |  
05:53:56 | Terminated homekit connection from /192.168.1.7:63111 |  
05:40:53 | New homekit connection from /192.168.1.7:63111 |  
05:40:52 | Terminated homekit connection from /192.168.1.7:63094 |  
04:53:32 | 000B57FFFE391D79/A217 : Firmware update - DONE |  
04:53:27 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:53:22 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:53:17 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:53:12 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:53:09 | New homekit connection from /192.168.1.7:63094 |  
04:53:08 | Terminated homekit connection from /192.168.1.7:63062 |  
04:53:07 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:53:02 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:52:57 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:52:52 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:52:47 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:52:42 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
04:52:33 | 000B57FFFE391D79/A217 : Firmware update - START, ZigBeeOtaFile [headerVersion=256, headerLength=56, headerFieldControl=0, manufacturerCode=4476, imageType=2101, fileVersion=12214572, stackVersion=ZIGBEE_PRO, headerString=EBL tradfri_light_basic, imageSize=168318] |  
04:38:46 | Terminated homekit connection from /192.168.1.42:53076 |  
04:00:32 | Terminated homekit connection from /192.168.1.48:59798 |  
04:00:32 | Terminated homekit connection from /192.168.1.48:59799 |  
03:45:53 | New homekit connection from /192.168.1.7:63062 |  
03:45:53 | Terminated homekit connection from /192.168.1.7:63048 |  
03:20:53 | New homekit connection from /192.168.1.7:63048 |  
03:20:53 | Terminated homekit connection from /192.168.1.7:63038 |  
03:00:53 | New homekit connection from /192.168.1.7:63038 |  
03:00:53 | Terminated homekit connection from /192.168.1.7:63023 |  
02:52:06 | 000B57FFFE391D79/A217 : Firmware update - DONE |  
02:52:01 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
02:51:56 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
02:51:51 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
02:51:46 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
02:51:41 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
02:51:36 | TX_NAK: EMBER_MESSAGE_TOO_LONG |  
02:51:32 | TX_NAK: EMBER_MESSAGE_TOO_LONG

**Comment by bumer0** [comment]
![image](https://user-images.githubusercontent.com/31984665/90473799-753d8c80-e12c-11ea-9270-5bd422da85de.png)

**Comment by sprut666666** [comment]
1.6.5
