### ISSUE TITLE
В умном доме Яндекса привод окна Drivent отображается как штора

### ISSUE THREAD

**Issue by Maksimka** [sprut/Hub#2285]
** Подробное описание ошибки **
В умном доме Яндекса [привод окна Drivent](https://sprut.ai/catalog/item/drivent-okonnyj-privod) отображается как штора [devices.types.openable.curtain](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-type-openable-curtain.html).

** Как воспроизвести ? **
1. Спарить привод окна в sprut hub.
2. Прокинуть его в умноый дом яндекса
3. Посмотреть на привод окна в умном доме яндекса
4. Убедится что оно отображается как штора, а не дверь или окно

** Ожидаемое поведение **
В умном доме Яндекса [привод окна Drivent](https://sprut.ai/catalog/item/drivent-okonnyj-privod) отображается как устройство, которое умеет открываться и/или закрываться [devices.types.openable](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-type-openable-curtain.html).

** Скриншоты/ Логи **
<img width="1708" alt="drivent_view_in_sprut_hub" src="https://user-images.githubusercontent.com/474617/232963329-643d01c7-8f98-4a9d-b267-a5cd656b6700.png">

** Дополнительные материалы **
[Обсуждение телеграме](https://t.me/c/1610305989/5390)

**Comment by AlexSinttig** [comment]
Для решения задачи пришлось создать в SprutHub'e виртуальное устройство "Дверь" и связать это устройство с "Окном" после этого новое устройство прокинул в Яндекс (оно прикидывается как [devices.types.openable](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-type-openable-curtain.html). ).

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"

**Comment by Maksimka** [comment]
Какой информации не хватило для решения задачи?

**Comment by Maksimka** [comment]
Я очень старался когда писал данный таск и излагал максимально подробно. Для максимального удобства моего что бы остлеживать статус и вашего что бы нечего не потерялось сделал это в task tracker.
Меня очень сильно опечалил и обидел факт закрытия данной задачи без ответа по существу вопроса.
