### ISSUE TITLE
Двухканальный модуль реле WB-MRM2-mini

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#23]
** Подробное описание ошибки **
Двухканальный модуль реле WB-MRM2-mini не появляется в Аксессуарах

** Скриншоты/ Логи **
в контроллерах он есть. Вот часть:
wb-mrm2-mini_33/Input Voltage | voltage | true

**Comment by Popov2006** [comment]
wb-mrm2-mini_33 | Button 1 | switch (ro) | /devices/wb-mrm2-mini_33/controls/Button 1 | 0 | OK
-- | -- | -- | -- | -- | --
wb-mrm2-mini_33 | Button 1 counter | value (ro) | /devices/wb-mrm2-mini_33/controls/Button 1 counter | 0 | OK
wb-mrm2-mini_33 | Button 2 | switch (ro) | /devices/wb-mrm2-mini_33/controls/Button 2 | 0 | OK
wb-mrm2-mini_33 | Button 2 counter | value (ro) | /devices/wb-mrm2-mini_33/controls/Button 2 counter | 0 | OK
wb-mrm2-mini_33 | Input Voltage | voltage (ro) | /devices/wb-mrm2-mini_33/controls/Input Voltage | 11.674 | OK
wb-mrm2-mini_33 | Relay 1 | switch | /devices/wb-mrm2-mini_33/controls/Relay 1 | 0 | OK
wb-mrm2-mini_33 | Relay 2 | switch | /devices/wb-mrm2-mini_33/controls/Relay 2 | 0 | OK
wb-mrm2-mini_33 | Safety Timer | range | /devices/wb-mrm2-mini_33/controls/Safety Timer | 0 | OK
wb-mrm2-mini_33 | Serial | text | /devices/wb-mrm2-mini_33/controls/Serial | 4266420458 | OK

**Comment by sprut666666** [comment]
Исправлено, обновление будет в след релизе.
