### ISSUE TITLE
Прошу добавить шаблон для Aqara cube / Mi cube

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#230]
Добрый день, прошу добавить шаблон для управления сценариями через контроллер Aqara Cube / Mi Cube
https://v2.sprut.ai/catalog/item/aqara-cube

На данный момент имеет статус NO_TEMPLATE

Address: 00158D00034954D6/D060<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 3000-0001</li><li>0001_ApplicationVersion: 5</li><li>FF01_Custom: {1=3025, 3=24, 4=5032, 5=110, 6=1, 151=0, 152=1304, 153=1287, 10=0, 154=4}</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.sensor_cube.aqgl01</li><li>0007_PowerSource: 3</li></ul></li><li>0012_MultistateInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>004A_NumberOfStates: 6</li><li>006F_StatusFlags: 0</li></ul></li><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul><li>0055_PresentValue: 2</li></ul></li><li>0003_Identify<ul></ul></li></ul></li><li>Output<ul><li>0012_MultistateInputBasic<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: -11.469999313354492</li><li>FF05_Unknown: 500</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li></ul><br>Last update: Wed Aug 19 08:10:36 UTC 2020

**Comment by sprut666666** [comment]
Прошу придерживаться правил оформления запросов, и не дублировать задачи https://github.com/sprut/Hub/issues/174
