### ISSUE TITLE
https://github.com/sprut/Hub/issues/1655

### ISSUE THREAD

**Issue by kachalex** [sprut/Hub#2304]
закрыто ишью 
https://github.com/sprut/Hub/issues/1655

реле не работает, хоть и определяется как штора.
шаблон не работает

если нужна дополнительная инфо, напишите.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
