### ISSUE TITLE
WBIO-DO-R10R-4 в режиме крана (шаблон mqtt)

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#231]
** Максимально подробное описание предложения.**
Не у всех модуль WBIO-DO-R10R-4 используется для управления шторами
У меня, например, это управление кранами 12В от Нептуна (без самого Нептуна) 
Нет никого дома - закрыли краны, надо - открыли
Нет воды = нет протечки, не нужны датчики, нет страха что устроишь потоп и т.п.

** Дополнительные материалы **
Создается 4 крана (DIR) и 4 выключателя (ON)
Триггерами СпрутХаб можно настроить включение (ON) и открытие крана (DIR) и обратный процесс - в Homekit когда кран активен (ON) отображается капелька внутри крана, когда кран открыт (DIR) - рисуется капля из крана 
![Valve](https://user-images.githubusercontent.com/55746897/90612794-36353700-e211-11ea-9d0c-4bac099d8e27.png)

Код шаблона: 
>
[
   {
      "manufacturer":"WirenBoard",
      "model":"WBIO-DO-R10R-4",
      "services":[
         {
            "name":"Кран",
            "type":"Valve",
            "characteristics":[
               {
                  "type":"Active",
                  "link2":{
                     "type":"Integer",
                     "topicSearch":"/devices/(wb-gpio)/controls/(EXT[1-9]_DIR[1-4])/meta/type",
                     "topicGet":"/devices/(1)/controls/(2)",
                     "topicSet":"/devices/(1)/controls/(2)/on"
                  }
               }
            ]
         }
      ]
   },
   {
      "manufacturer":"WirenBoard",
      "model":"WBIO-DO-R10R-4",
      "services":[
         {
            "name":"Статус",
            "type":"Switch",
            "characteristics":[
               {
                  "type":"On",
                  "link2":{
                     "type":"Integer",
                     "topicSearch":"/devices/(wb-gpio)/controls/(EXT[1-9]_ON[1-4])/meta/type",
                     "topicGet":"/devices/(1)/controls/(2)",
                     "topicSet":"/devices/(1)/controls/(2)/on"
                  }
               }
            ]
         }
      ]
   }
]

[WBIO-DO-R10R-4.txt](https://github.com/sprut/Hub/files/5095512/WBIO-DO-R10R-4.txt)

**Comment by Alxprv** [comment]
@sprut666666

**Comment by sprut666666** [comment]
Удобная смена типов будет через интерфейс, заставлять пользователей менять темплейты не планируется
