### ISSUE TITLE
Philips Hue wall switch module

### ISSUE THREAD

**Issue by kachalex** [sprut/Hub#2312]
[beta] 1.9.6 (10162)

Philips Hue wall switch module

https://sprut.ai/catalog/item/philips-hue-wall-switch-module

после добавления опознает только одну кнопку(свитч) хотя должен давать 2

работает только одиночное нажатие  (долгое не отображает, не знаю может есть двойное)

<img width="665" alt="image" src="https://user-images.githubusercontent.com/42259721/234357704-86e3e6cd-6bdd-4084-979f-fa6787b42a34.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/42259721/234357787-58d54952-7a98-4ad4-b02e-c64c25c1f008.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/42259721/234523719-651e5c06-070b-4381-8f48-8a170b1638b9.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/42259721/234523841-6dfe1183-5d90-4eb2-b510-922d2c9f37cf.png">

Если надо еще какая-то информация, буду рад скинуть.

Я попробовал подключить к деконз и получил такой результат

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/42259721/234358231-f51bbd02-c5be-424d-87aa-41c064a3544a.png">

в z2m

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/42259721/234574212-c89ede6f-e2a2-4e62-8976-7a6ea59708da.png">

очень хотелось бы получить такой же девайс в спрутхабе

**Comment by Batyushin** [comment]
проверить, если возникнуть проблемы отписать в чат поддержки
