### ISSUE TITLE
_TZ3210_pgq2qvyv - отсутствие настройки памяти

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#2319]
** Подробное описание ошибки **
Лента при отключении электричества по умолчанию всегда включает свет.

** Как воспроизвести ? **
Выключить ленту в вебе СХ
Выключить из розетки/отключить электричество
Включить в розетку.
Получить подсветку.
** Ожидаемое поведение **
При отключении электричества последнее состояние или же всегда выключено.

** Скриншоты/ Логи **
![2023-05-02 01 08 42](https://user-images.githubusercontent.com/59850734/235540212-15edf49b-f4bc-48de-b09d-24dc3d46355d.jpg)

** Пожалуйста, заполните следующую информацию: **
Версия СХ Beta 10242 Pi4

** Дополнительные материалы **

Address: A4C13803E77E2C9C/9482
 
Structure
Endpoint 1 (COLOR_TEMPERATURE_LIGHT)
Input
1000_TouchlinkCommissioning
0300_ColorControl
0007_ColorTemperature: 476 [UNSIGNED_16_BIT_INTEGER]
400B_ColorTemperatureMin: 153 [UNSIGNED_16_BIT_INTEGER]
400C_ColorTemperatureMax: 500 [UNSIGNED_16_BIT_INTEGER]
EF00_ManufacturerSpecific
0051_Custom: -50 [TUYA_32_BIT_INTEGER]
0000_Basic
0001_ApplicationVersion: 100 [UNSIGNED_8_BIT_INTEGER]
0003_HWVersion: 1 [UNSIGNED_8_BIT_INTEGER]
0004_ManufacturerName: _TZ3210_pgq2qvyv [CHARACTER_STRING]
0005_ModelIdentifier: TS0502B [CHARACTER_STRING]
0007_PowerSource: 1 [ENUMERATION_8_BIT]
0003_Identify
0004_Groups
0005_Scenes
0006_OnOff
0000_OnOff: true [BOOLEAN]
0008_LevelControl
0000_CurrentLevel: 8 [UNSIGNED_8_BIT_INTEGER]
Output
0019_OtaUpgrade
000A_Time
Endpoint 242 (ZGP_PROXY_BASIC)
Output
0021_GreenPower
 
 
Binding table
 
Group membership
 
Associated devices
 
Neighbor table
 
Routing table
 
Node Descriptor
Aps Flags       0
Frequency Bands [FREQ_2400_MHZ]
Server Capabilities     []
Buffer Size     66
Incoming Transfer Size  66
Logical Type    Router
Mac Capabilities        [FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]
Manufacturer Code       0x1141 (4417)
Out Going Transfer Size 66
Stack Compliance        21
 
Power Descriptor
Current Power Mode      RECEIVER_ON_IDLE
Available Power Sources [MAINS]
Current Power Source    MAINS
Power Level     FULL
 
OTA info
Image type      0xD3A3 (54179)
File version    0x00000064 (100)
Manufacturer code       0x1141 (4417)
<img width="425" alt="Снимок экрана 2023-05-02 в 01 11 23" src="https://user-images.githubusercontent.com/59850734/235540439-6bf462a4-bb79-44dc-a38b-29682e74f328.png">

 Telegram @UskovvNA

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
