### ISSUE TITLE
ZigBee - SONOFF - ZBMINIL2

### ISSUE THREAD

**Issue by beezoncheg** [sprut/Hub#2321]
Расширить шаблон, который был добавлен ранее https://github.com/sprut/Hub/issues/2096
Не хватает настроек:
- поведения при восстановлении питания (StartUpOnOff)
  - 0 state off
  - 1 state on
  - 2 state toggle
  - 255 last state

Есть еще эндпоинт выбора типа выключателя, но не нашёл значения. Видимо нужен оригинальный/совместимый хаб с которого можно отсниффать/собрать эти значения. Возможно релюха поддерживает значения по спецификации (но это не точно).

Ссылка на устройство в каталоге https://sprut.ai/catalog/item/zbmini-l2-zigbee-bez-neytralnogo-provoda

<span>Address:
    60B647FFFE53DFB6/0BA7</span><br><br><b>Structure</b><br>
<ul>
    <li>
        Endpoint 1 (ON_OFF_OUTPUT)<ul>
            <li>
                Input<ul>
                    <li>0000_Basic<ul>
                            <li>0000_ZCLVersion: 8 [UNSIGNED_8_BIT_INTEGER]</li>
                            <li>0004_ManufacturerName: SONOFF [CHARACTER_STRING]</li>
                            <li>0005_ModelIdentifier: ZBMINIL2 [CHARACTER_STRING]</li>
                            <li>0006_DateCode: 20221118 [CHARACTER_STRING]</li>
                            <li>0007_PowerSource: 0 [ENUMERATION_8_BIT]</li>
                            <li>4000_SWBuildID: 1.0.10 [CHARACTER_STRING]</li>
                            <li>FFFD_Custom: [UNSIGNED_16_BIT_INTEGER]</li>
                        </ul>
                    </li>
                    <li>0001_PowerConfiguration<ul>
                            <li>FFFD_Custom: [UNSIGNED_16_BIT_INTEGER]</li>
                        </ul>
                    </li>
                    <li>0003_Identify<ul>
                            <li>0000_IdentifyTime: 0 [UNSIGNED_16_BIT_INTEGER]</li>
                            <li>FFFD_Custom: [UNSIGNED_16_BIT_INTEGER]</li>
                        </ul>
                    </li>
                    <li>0B05_Diagnostics<ul>
                            <li>FFFD_Custom: [UNSIGNED_16_BIT_INTEGER]</li>
                        </ul>
                    </li>
                    <li>0006_OnOff<ul>
                            <li>0000_OnOff: false [BOOLEAN]</li>
                            <li>4003_StartUpOnOff: 0 [ENUMERATION_8_BIT]</li>
                            <li>FFFD_Custom: [UNSIGNED_16_BIT_INTEGER]</li>
                        </ul>
                    </li>
                    <li>0007_OnOffSwitchConfiguration<ul>
                            <li>0000_SwitchType: 0 [ENUMERATION_8_BIT]</li>
                            <li>0010_SwitchActions: 0 [ENUMERATION_8_BIT]</li>
                            <li>FFFD_Custom: [UNSIGNED_16_BIT_INTEGER]</li>
                        </ul>
                    </li>
                    <li>FC57_ManufacturerSpecific<ul>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                Output<ul>
                    <li>0019_OtaUpgrade<ul>
                            <li>0000_UpgradeServerID: 60A423FFFE415618 [IEEE_ADDRESS]</li>
                            <li>0001_FileOffset: -1 [UNSIGNED_32_BIT_INTEGER]</li>
                            <li>0002_CurrentFileVersion: 4106 [UNSIGNED_32_BIT_INTEGER]</li>
                            <li>0006_ImageUpgradeStatus: 0 [ENUMERATION_8_BIT]</li>
                            <li>0007_ManufacturerID: 4742 [UNSIGNED_16_BIT_INTEGER]</li>
                            <li>0008_ImageTypeID: 65535 [UNSIGNED_16_BIT_INTEGER]</li>
                            <li>FFFD_Custom: [UNSIGNED_16_BIT_INTEGER]</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul><br><br><b>Binding
    table</b><br><br><b>Group
    membership</b><br><br><b>Associated
    devices</b><br><br><b>Neighbor
    table</b><br><br><b>Routing
    table</b><br><br><b>Node
    Descriptor</b><br>

Aps Flags | 0
-- | --
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 82
Incoming Transfer Size | 255
Logical Type | End Device
Mac Capabilities | [REDUCED_FUNCTION_DEVICE]
Manufacturer Code | 0x1286 (4742)
Out Going Transfer Size | 255
Stack Compliance | 22

**Comment by Ivan-Baranov** [comment]
> Название	Значение
> **Производитель**	SONOFF
> **Модель**	ZBMINIL2
> **Прошивка**	1.0.10
> **WEB Build**	1.2.12
> **API Build**	1.9.5 (8740)
> Детальная информация
> #### Дополнительно
> Telegram: [@imbaranov](https://t.me/imbaranov)
> 
> Где приобрели? https://aliexpress.ru/item/1005005459900457.html?sku_id&#x3D;12000033168203771

Шаблон заработал после перехода на beta.

**Comment by sprut666666** [comment]
мы не добавляем опции которые не работают, а в данном выключатели они есть и не работают.
