### ISSUE TITLE
Сценарии работы оборудования - типовые на каждый день

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#233]
** Максимально подробное описание предложения.**
Функционала триггеров категорически не хватает @sprut666666 @MakeSimpleOrg 
Есть ряд простых задач, которые можно наверняка просто реализовать в графическом интерфейсе, чем писать код под wb. Также это повлечет переход на modbus большинства пользователей :)

Примеры таких задач: 
1) Включение света (одного или нескольких источников) по расписанию (в данном случае актуально для подсветки фасада дома / участка, или управления шторами - ночью закрыть, утром открыть, днем закрывать если солнце в окна и никого нет дома)
Например - через 30 минут после заката солнца включить диммер 1 белый канал с яркостью 50 (из 255) 
Выключить свет в будний день в 23:00, в выходной в 0:00 (получается следующие сутки)
Потом включить свет в 7 утра и выключить за 30 минут до восхода солнца
Проверять по датчику освещенности текущий уровень и если что корректировать поведение правила (например сильные осадки и темно - включаем раньше или очень светло - выключаем раньше)

Специально указал тут привязку к восходу/закату, так как вкорячить такой код на wirenboard я даже не пытаюсь (но некоторые вроде осилили, хотя это не для обычного человека). Заодно любителей Siemens Logo! и ОВЕН-ПЛК можно перетянуть будет - там это сейчас элементарно делается готовыми блоками, плюс есть логика И/ИЛИ/ИЛИ НЕ и т.д., таймеры на включение/выключение, расписания, реле с и без памятью состояния и т.п.)

2) Включение света по датчику движения с учетом уровня освещенности - управлять 1 или несколькими источниками света но так, что если светло - не включать их. Уровень освещенности получать с датчика движения/освещенности (совмещенного или раздельного). Диммер включать на требуемом уровне. Ночью включать например в четверть мощности, а днем на полную. Выключать с варьируемой задержкой (от времени суток, освещенности - вдруг кто еще свет включил, положения солнца над горизонтом) или снижая яркость по задаваемому алгоритму (через 30 сек минус 20 пунктов, еще через 30 сек минус 50 пунктов, а потом через 45 сек вырубить совсем). 

3) Автоматизация прихода в дом / ухода - связка геркона на двери и датчика (-ов) движения. Нет движения внутри и открылась дверь - включать тот, тот и тот свет, открыть воду (там или там или везде). Есть движение внутри и открылась дверь - ждем Х времени и потом (если нет движения и дверь не открывалась снова) отключаем часть оборудования (хотя бы свет или приглушаем его). Потом через еще Х времени - розетки и остатки света, а потом еще через Х времени еще и воду перекроем и шторы задёрнем и роллеты опустим.

То есть мне лично не хватает инструментов Homekit для такой настройки и это там не очень наглядно / удобно
А в целом, как мне кажется, даст хороший приток пользователей (им же главное - цена, простота и удобство) 

** Дополнительные материалы **
Предлагаю дополнять идеями (и сам буду если что придумаю) - видел в Issue пример про котельную, но хотя бы с простого пока начать бы :)

**Comment by Alxprv** [comment]
4. Сухие контакты (датчики касания, то есть кнопки без фиксации) - иметь возможность обрабатывать одиночное нажатие (для включения и выключения приборов), двойное, тройное, четверное, и т.д., а также длинное (с регулируемой длительностью). Назначать на них наборы реле, параметры диммеров и другого оборудования. Сделать свой вариант сценариев - увеличив количество включаемого/выключаемого оборудования с одной кнопки за счет разных нажатий. Пример - одно короткое нажатие выключает (если выключен) или выключает (если включен) большой свет в комнате (например люстру), двойное нажатие включает режим "кино" - в котором настроено что верхний свет (реле люстры) выключается, включается светодиодная подсветка, бра у дивана на яркость 30 пунктов из 255, а торшер с умной цветной лампой меняет цвет на фиолетовый. Повторное двойное нажатие возвращает предыдущий режим (например просто большой свет - люстру). А тройное нажатие включает вообще весь свет, диммер со светодиодной лентой на 100% и торшер в белый цвет на полную яркость. Тогда как длительное нажатие плавно увеличивает яркость диммера, а повторное - также плавно его уменьшает до требуемого уровня. И т.д.

**Comment by Alxprv** [comment]
5. Добавить возможность корректировки работы термостатов (теплый пол, радиаторы) с доп. датчиками температуры - брать показания с другого датчика Modbus или wireless (или нескольких - например с усреднением, либо приоритетом), добавить им расписание работы - нагрев / отключение

**Comment by Alxprv** [comment]
6. Добавить возможность управления шторами по расписанию (несколько интервалов), с возможностью учета уровня освещенности (по датчику или нескольким)

**Comment by Alxprv** [comment]
7. Добавить возможность выбора нескольких условий с приоритетным условием, выбираемым пользователем системы, например:
   - Закрывать шторы каждый день с заходом солнца или в 21:00 - но в зависимости от того, что наступает раньше (закат солнца или заданное время)
   - Выключать подсветку фасада утром с в 9 утра или за ХХ минут до восхода солнца (если он в этот день наступает раньше, чем 9 утра)

**Comment by Bigmanekb** [comment]
Выполнено
