### ISSUE TITLE
ошибка, что-то поменялось в модбас регистрах

### ISSUE THREAD

**Issue by DjScava** [sprut/Hub#234]
** Подробное описание ошибки **
в интерфейсе увидел спам логов вида:
15:16:30 | Error Input, only reading |  
-- | -- | --
15:16:29 | Error Input, only reading |  
15:16:29 | Error Input, only reading |  
15:16:29 | Error Input, only reading |  
15:16:29 | Error Input, only reading |  
15:16:29 | Error Input, only reading |  
15:16:29 | Error Input, only reading |  
15:16:29 | Error Input, only reading

в логах нашел начало этого спама, выглядит вот так:
I | 2020-08-18 | 20:23:33.433 | org.makesimple.SprutHub.Controllers.ModBus.b       642 | I/O exception - failed to read response for request [3B 04 01 1B 00 01] - Cannot read from serial port
I | 2020-08-18 | 20:23:33.436 | org.makesimple.SprutHub.Controllers.ModBus.b       643 | time = 187570061312639, pollingTime = 10, link = 59/283/Input/1
I | 2020-08-18 | 20:44:18.846 | org.makesimple.SprutHub.Homekit.http.a             62  | Terminated homekit connection from /192.168.1.70:58006
I | 2020-08-18 | 20:44:19.275 | org.makesimple.SprutHub.Homekit.http.a             54  | New homekit connection from /192.168.1.70:58665
I | 2020-08-18 | 21:00:35.863 | org.makesimple.SprutHub.Controllers.ModBus.b       642 | I/O exception - failed to read response for request [3B 04 01 1B 00 01] - Cannot read from serial port
I | 2020-08-18 | 21:00:35.866 | org.makesimple.SprutHub.Controllers.ModBus.b       643 | time = 189792127919725, pollingTime = 10, link = 59/283/Input/1
I | 2020-08-18 | 21:28:54.984 | org.makesimple.SprutHub.Controllers.ModBus.b       642 | I/O exception - failed to read response for request [3B 04 01 1B 00 01] - Cannot read from serial port
I | 2020-08-18 | 21:28:54.988 | org.makesimple.SprutHub.Controllers.ModBus.b       643 | time = 191491227356528, pollingTime = 10, link = 59/283/Input/1
I | 2020-08-18 | 21:32:19.522 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:19.710 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:19.762 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:19.822 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:19.883 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:19.949 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:20.008 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:20.068 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:20.123 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:20.180 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:20.278 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:20.378 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading
I | 2020-08-18 | 21:32:20.522 | org.makesimple.SprutHub.Controllers.ModBus.b       416 | Error Input, only reading

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
как воспроизвести не знаю сижу в шоке. в то время с СХ ничего не делал.

** Ожидаемое поведение **
Четкое и краткое описание того, что вы ожидали.

** Скриншоты/ Логи **
[logs.zip](https://github.com/sprut/Hub/files/5096333/logs.zip)

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.6.4

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
проверить на 1.6.5
