### ISSUE TITLE
Буквы украинского/белорускиого алфавитов не сохраняются

### ISSUE THREAD

**Issue by blobor** [sprut/Hub#235]
**Подробное описание ошибки**
Если вы попытаетесь использовать в имени аксессуара буквы украинского/белорускиого языков, например, `«i», «ї», «ґ», «'», «є», «ў»` они не сохранятся в имени.

**Как воспроизвести ?**
1. Перейдите к странице "Аксессуары"
2. Попробуйте добавить в название любого аксессуара букву с украинского/белорускиого алфавитов которой нет в руском алфавите.
3. Перезагрузите страницу
4. Буква не добав

**Ожидаемое поведение**
Названия аксессуаров могут использовать буквы с украинского/белорусского алфавитов

**Скриншоты/ Логи**
![image](https://user-images.githubusercontent.com/4813007/90825604-d5594c00-e341-11ea-8537-bf56cc5a2713.png)

- запрос (PUT | http://IP:55555/api/accessories/24/name) ушел с правильным именем
![image](https://user-images.githubusercontent.com/4813007/90826034-79db8e00-e342-11ea-96ec-5d837a7a0732.png)

- но (GET | http://IP:55555/api/accessories/24/services) приходит уже с неправильным
![image](https://user-images.githubusercontent.com/4813007/90826137-9d9ed400-e342-11ea-9ba0-0422768a3f82.png)

**Пожалуйста, заполните следующую информацию:**
  - Версия:  SprutHub 1.6.4b
  - Браузер: Firefox

**Comment by sprut666666** [comment]
обновить/пробовать
