### ISSUE TITLE
Некорректно работают шторы управляемые через сухие контакты и виртуальную логику

### ISSUE THREAD

**Issue by mazaxaka** [sprut/Hub#237]
** Подробное описание ошибки **
При попытке открыть или закрыть шторы штора едет некорректное время. Иногда едет немного останавливается и снова продолжает ехать
** Как воспроизвести ? **
Создаем виртуальный аксессуар "Штора", собираем её с виртуальной логикой "управление позицией по таймеру", обе реле включены - остановлена, одна выключена - закрывается, другая выключена - открывается. Устанавливаем время. Проверено на 15, 30 секундах и времени разгона 1 секунда. 

** Ожидаемое поведение **
Нужно, чтобы открываясь и закрывалась до конца, то есть держала выключенными реле столько времени, сколько указано в настройках

** Скриншоты/ Логи **

Версия - SprutHub 1.6.4b

**Comment by sprut666666** [comment]
1.6.5
