### ISSUE TITLE
lumi.sensor_magnet.aq2

### ISSUE THREAD

**Issue by kotenev** [sprut/Hub#2370]
Прошёл процедуру сопряжения повторно: "Нет шаблона"
Address: 00158D00076AB95C/57D6

Structure
Endpoint 1
Input
0000_Basic
0000_ZCLVersion: 1 [UNSIGNED_8_BIT_INTEGER]
0001_ApplicationVersion: 3 [UNSIGNED_8_BIT_INTEGER]
0003_HWVersion: 2 [UNSIGNED_8_BIT_INTEGER]
0004_ManufacturerName: LUMI [CHARACTER_STRING]
0005_ModelIdentifier: lumi.sensor_magnet.aq2 [CHARACTER_STRING]
0007_PowerSource: 3 [ENUMERATION_8_BIT]
0010_LocationDescription: [CHARACTER_STRING]
0011_PhysicalEnvironment: 0 [ENUMERATION_8_BIT]
4000_SWBuildID: 3000-0001 [CHARACTER_STRING]
FF01_ExtInfo (115F): {1=3005, 3=30, 4=424, 5=7711, 6=1, 10=0} [STRUCT2]
0003_Identify
0000_IdentifyTime: 0 [UNSIGNED_16_BIT_INTEGER]
0006_OnOff
FFFF_ManufacturerSpecific
Output
0000_Basic
0004_Groups
0019_OtaUpgrade
FFFF_ManufacturerSpecific

Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags 0
Frequency Bands [FREQ_2400_MHZ]
Server Capabilities []
Buffer Size 127
Incoming Transfer Size 100
Logical Type End Device
Mac Capabilities [REDUCED_FUNCTION_DEVICE]
Manufacturer Code 4151
Out Going Transfer Size 100
Stack Compliance 0

Power Descriptor
Current Power Mode RECEIVER_ON_IDLE
Available Power Sources [DISPOSABLE_BATTERY]
Current Power Source DISPOSABLE_BATTERY
Power Level FULL

Last update: Mon Jun 05 15:51:35 MSK 2023

**Comment by sprut666666** [comment]
запрос на добавление оформляется так https://wiki.spruthub.ru/Моё_устройство_не_поддерживается._Нет_шаблона._Что_делать%3F
