### ISSUE TITLE
Добавить поддержку ТЕРМОСТАТ-АКТУАТОР DEFARO DIT-102 ZWawe

### ISSUE THREAD

**Issue by DomikMaksa** [sprut/Hub#239]
https://www.defaro.ru/index.php/support/instructions/68-dit101-dit102

**Comment by MakeSimpleOrg** [comment]
Добавьте информацию как написано в инструкции

**Comment by MakeSimpleOrg** [comment]
А хотя, это дубль

**Comment by DomikMaksa** [comment]
Не получается ( он вообще не добавляется стик стоит кампании зевейв.ми

Отправлено с iPhone

**Comment by MakeSimpleOrg** [comment]
Вероятно стик EU, а термостат RU, или наоборот. Отсутствие темплейта не мешает добавлению в хаб.
