### ISSUE TITLE
Возможность добавлять устройства по отдельности.

### ISSUE THREAD

**Issue by Anzic23** [sprut/Hub#24]
Прошу добавить возможность добавлять или исключать устройства в системы УД по отдельности, что бы можно было добавить устройство в Яндекс, но не добавлять его в Home Kit.

**Comment by diamond5170** [comment]
Скорее всего, добавим такую возможность, в виде галочек в настройках устройств (галочки хомкит, гугл, яндекс). Только учтите, что к примеру для яндекса потребуется полностью переспаривать мост на каждое такое изменение.

**Comment by Bigmanekb** [comment]
да и пофигу, главное чтобы можно было в разные места отправлять разные устройства при необходимости
