### ISSUE TITLE
Добавить поддержку компактного модуля для управления мотороми (жалюзи, шторы) Fibaro FGR211 V1.9

### ISSUE THREAD

**Issue by DomikMaksa** [sprut/Hub#240]
https://rus.z-wave.me/manuals/show?sku=FIB_FGR-221

**Comment by DomikMaksa** [comment]
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>2</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0300</td></tr><tr><td width=35%>Device Id</td><td>400A</td></tr><tr><td width=35%>App Version</td><td>2.1</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Motor Multiposition</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 BasicWindowCovering</li><li>V1 MultiChannel</li><li>V1 SwitchBinary</li><li>V2 MultiChannelAssociation</li><li>V1 NoOperation</li><li>V1 Basic</li><li>V3 SwitchMultiLevel<ul></ul></li><li>V1 Version</li><li>V1 SwitchAll</li><li>V2 Association</li><li>V1 FirmwareUpdateMD</li><li>V1 SceneActivation</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 ManufacturerSpecific</li><li>V1 Configuration</li></ul></li></ul><br>Last update: Fri Nov 27 15:04:08 MSK 2020

**Comment by DomikMaksa** [comment]
![Снимок экрана 2020-11-27 в 19 56 06](https://user-images.githubusercontent.com/48162267/100471104-a5f96e80-30ea-11eb-883a-48f12afb0b1f.png)

**Comment by Batyushin** [comment]
Необходимо правильно заполнить:
- указываете свой ник в телеграме для быстрой связи с вами
- указываете ссылку, по которой покупался девайс
- указываете ссылку в каталоге если такое устройство там уже есть.
- Статус после восстановления питания (если устройство релейного типа или лампочка).

**Comment by DomikMaksa** [comment]
@Mak51mu5   ник в телеграме для быстрой связи.
https://www.z-wave.ru в этом магазине покупалось давно года три назад.
В каталоге такое устройство не описано.
Инструкция: https://rus.z-wave.me/drive/?file=f003e80aaabdf6f519224a8fe7bc017cce45

**Comment by MakeSimpleOrg** [comment]
r4165
