### ISSUE TITLE
Подмена аксессуара в триггере после перезагрузки.

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#241]
** Подробное описание ошибки **
После перезагрузки WB, в триггере меняется аксессуар. И само виртуальное устройство перестает работать.

** Как воспроизвести ? **
В соответствии с инструкцией создан осушитель id устройства 121
![image](https://user-images.githubusercontent.com/60096192/91130347-90744300-e6bc-11ea-8d04-0c6d88343d63.png)

Привязан датчик влажности
![image](https://user-images.githubusercontent.com/60096192/91130626-fa8ce800-e6bc-11ea-8e5e-a40c7243d309.png)

Создано три триггера
![image](https://user-images.githubusercontent.com/60096192/91130979-90c10e00-e6bd-11ea-81e3-e2835e093050.png)
![image](https://user-images.githubusercontent.com/60096192/91131060-b8b07180-e6bd-11ea-8c3b-2da80c896f36.png)
![image](https://user-images.githubusercontent.com/60096192/91131368-ee555a80-e6bd-11ea-9f0b-b2071b73ca96.png)

После перезагрузки WB в триггерах меняется устройство.
![image](https://user-images.githubusercontent.com/60096192/91142814-85241600-e6c2-11ea-961c-f1e97abb6178.png)

** Ожидаемое поведение **
Ожидается, что созданном триггере не будет меняться устройство после перезагрузки

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия: SprutHub 1.6.4b на WB
Все устройства 30 и 121 были созданы ранее не удалялись и не менялись. устройство 30 подключено по RS485.

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by MakeSimpleOrg** [comment]
Повторить не получилось.

**Comment by droni4** [comment]
После удаления виртуального устройства, и создание вновь. Ошибка не и у меня не повторяется. Выше описываемый случай произошло после обновления системы с 1.6.3 на 1.6.4

**Comment by sprut666666** [comment]
Если сможете воспроизвести, тогда сможем поправить, а пока закрыто.
