### ISSUE TITLE
Добавить поддержку датчика движения TS0202

### ISSUE THREAD

**Issue by SitkoAleksandr** [sprut/Hub#242]
Address: 680AE2FFFE71B6B4/0A51<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 68</li><li>0004_ManufacturerName: _TYZB01_zwvaj5wy</li><li>0005_ModelIdentifier: TS0202</li><li>0007_PowerSource: 3</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0010_IasCieAddress: 0000000000000000</li><li>0001_ZoneType: 13</li><li>0011_ZoneId: 255</li><li>0002_ZoneStatus: 1</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>EF01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li></ul><br>Last update: Wed Aug 26 20:23:00 MSK 2020

Телеграм: @Sitko_Aleksandr
Девайс в каталоге вроде бы этот [TS0202](https://v2.sprut.ai/catalog/item/cr-smart-home-motion-sensor)
Покупал [тут](https://aliexpress.ru/item/4000829510396.html?spm=a2g0s.9042311.0.0.37c633edcTbpxp)

**Comment by SitkoAleksandr** [comment]
[logs.zip](https://github.com/sprut/Hub/files/5131413/logs.zip)

**Comment by sprut666666** [comment]
1.6.5
