### ISSUE TITLE
Philips hue light strip - LST002

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#243]
Address: 001788010498C689/9553<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, MAINS, RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>4000_SwBuildId: 1.50.2_r30933</li><li>0001_ApplicationVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: LST002</li><li>0007_PowerSource: 1</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 32</li><li>4000_EnhancedCurrentHue: 8418</li><li>0001_CurrentSaturation: 140</li><li>4001_EnhancedColorMode: 2</li><li>0002_RemainingTime: 0</li><li>4002_ColorLoopActive: 0</li><li>0003_CurrentX: 29972</li><li>4003_ColorLoopDirection: 0</li><li>0004_CurrentY: 26871</li><li>0007_ColorTemperature: 366</li><li>0008_ColorMode: 2</li></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>4000_StartUpCurrentLevel: 254</li><li>0001_RemainingTime: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 16779778</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4107</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br>Last update: Sat Aug 29 14:06:25 MSK 2020

1) Снял галочку около Zigbee контроллера в веб морде спрутхаба, отвязывал Hue ленту от его родного хабаи(удалил в приложении Hue, включил назад галочку и , нажал кнопку добавить в приложении Hue. Лента сама подключилась к хабу с помощью light link , т.е фактически и по сути к ленте я ни разу не притронулся. 
Затем я изменял цвет и яркость в приложении дом у этой ленты, покрутил по цветовому кругу от теплого к холодному. Изменял яркость от меньшего к большему.
Зашел в приложение Hue , начал изменять состояние после потери питания. 
Там их было три штуки: 
1) Стандартные настройки Philips Hue (Теплый белый свет, максимальная яркость)
2) Восстановление после отключение электричества
3)Настройка цвета и яркости
Я протыкал все настройки и выбрал второй пункт.
Нажал скачать логи.

Затем снял галочку напротив контроллера и переключил на координатор со своим каналом и добавил ленту в хаб , прежде удалив ее из приложения Hue. 
Лента залетела сама с помощью Light link.

Телеграм: @UskovvNA
Покупалась лента на amazon.uk (давно достаточно, уже не найду прямую ссылку)

[Sat Aug 29 14:00:45 MSK 2020.pcap.zip](https://github.com/sprut/Hub/files/5145122/Sat.Aug.29.14.00.45.MSK.2020.pcap.zip)

[Ссылка на ленту в каталоге](https://v2.sprut.ai/catalog/item/philips-lightstrip-plus-base-pack-hue-white-and-color-ambiance)

**Comment by sprut666666** [comment]
проверить
