### ISSUE TITLE
Не реагирует на переключение в вебе спутхаба

### ISSUE THREAD

**Issue by zloydimo4ka** [sprut/Hub#244]
Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device
Address: 01124B001C3BF06F/69E0<br><br><b>Neighbors</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th></tr><tr><td>0000000000000000</td><td>29CE</td><td>Router</td><td>true</td><td>Unknown</td><td>31</td></tr><tr><td>00158D00032CA6B3</td><td>4E85</td><td>Router</td><td>true</td><td>Parent</td><td>84</td></tr><tr><td>000B57FFFE80CD13</td><td>0000</td><td>Coordinator</td><td>true</td><td>Unknown</td><td>17</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: SZ</li><li>0005_ModelIdentifier: Lamp_01</li><li>0007_PowerSource: 1</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sun Aug 30 16:31:06 MSK 2020

**Comment by sprut666666** [comment]
1.6.5
