### ISSUE TITLE
Устройства ZigBee отваливаются 

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#246]
** Подробное описание ошибки **
Через какое-то время устройства перестают работать, что устройства пропали из сети видно только на карте сети
![image](https://user-images.githubusercontent.com/60096192/91722126-e3f9fb80-ebaa-11ea-87e5-7c64ca4caad1.png)

В контроллере данные устройств имеют статус в сети
![image](https://user-images.githubusercontent.com/60096192/91722285-1572c700-ebab-11ea-8c55-260fe893ca8f.png)

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Перейдите к «...»
2. Нажмите «....»
3. Прокрутите вниз до «....»
4. Смотрите ошибку

** Ожидаемое поведение **
Ожидается, что в случае отваливания устройство, статус офлайн будет видно и в аксессуарах

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - WB, SH 1.6.4

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
И как это воспроизвести ?
