### ISSUE TITLE
не подключаются акаровские кнопки 

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#25]
** Подробное описание ошибки **
При попытке спарить зигби и акаровские кнопки выдает ошибку/

![photo_2019-07-28_07-52-07](https://user-images.githubusercontent.com/52490000/62011063-089bcc80-b17c-11e9-8c1b-dbd02d401fb7.jpg)

При более ранних версиях Спрутхаба? они заходили, но не работали, сейчас не заходят.

**Comment by diamond5170** [comment]
Кнопки добавятся в следующем релизе. И это не баг, а улучшение.
