### ISSUE TITLE
Не отоброжается состояние выключателя, при использовании физического выключателя

### ISSUE THREAD

**Issue by andrey-working** [sprut/Hub#250]
После обновления сх до 1.6.4б. При включении света физической  клавишей, статус в СХ и ХК не обновляется, при этом в ВБ все фиксирует как надо .

** Пожалуйста, заполните следующую информацию: **
  - Версия: , IOS 13.6.1
 - Версия СХ 1.6.4b

** 
![EC09BB06-39C7-4F61-AC8E-9936728CE4DD](https://user-images.githubusercontent.com/70601959/91893822-5ba85300-ec9d-11ea-9e45-f41e52622c57.jpeg)
![0C095982-72BD-41D4-A538-82771EF06B4C](https://user-images.githubusercontent.com/70601959/91893828-606d0700-ec9d-11ea-990c-f3ec741e5cce.jpeg)
![796D6CF3-1555-47EC-965D-26DDD847B61F](https://user-images.githubusercontent.com/70601959/91893831-6236ca80-ec9d-11ea-821f-6ae043518f84.jpeg)

**Comment by sprut666666** [comment]
1.6.5
