### ISSUE TITLE
Устройства Z-wave не проходят опрос

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#253]
** Подробное описание ошибки **
Устройство DAS-102 не проходит полностью опрос и аксессуар не появляется в SH

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
Установить последнюю версию SH на данный момент доступную (1.6.4) апдейт сделан в 17:00 по москве, установить Z-wave  стик в первый порт USB Wirenboard, выставить слеюущие настройки на скрине видно будет и включить контроллер, нажать на поиск устройств на котроллер Zwave, а на блоке DAs-102 нажать на кнопку сопряжения 3 раза.
Именно добавление нового устройства 

** Ожидаемое поведение **
 устройство полностью пройдет опрос и возможно управление из SH

** Пожалуйста, заполните следующую информацию: **
  - Версия: SH 1.6.4 обновленная в 2 сентября 2020 в 17:00
Проверяно на Wirenboard и RPi

** Дополнительные материалы **
![Снимок экрана 2020-09-02 в 16 32 47](https://user-images.githubusercontent.com/5717388/91995444-813a6880-ed40-11ea-8fd0-0c0026ff4ff5.png)
![Снимок экрана 2020-09-02 в 16 32 40](https://user-images.githubusercontent.com/5717388/91995452-83042c00-ed40-11ea-8636-44cef394fb50.png)
![Снимок экрана 2020-09-02 в 16 29 17](https://user-images.githubusercontent.com/5717388/91995454-84355900-ed40-11ea-8f6c-e308148eefd9.png)

Telegram @ziracul

**Comment by MakeSimpleOrg** [comment]
1.6.5
