### ISSUE TITLE
danalock - не обновляется текущий статус

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#254]
**Подробное описание ошибки** 
Danalock подключен через z-wave
в homekit 13.7.1 
не обновляется текущий статус замка после открытия 

** Как воспроизвести ? **
1. замок закрыт физичеки  
2. через homekit нажимаю открыть (07/09/2020. в 20:28:52)

3. замок физически открывается 
4. Долго, более 10 минут висит статус открывается см картинку 
5. через 20 минут замок сам закрылся (это настройка из родного приложения) и статус в homekit не изменился. 
___________

20:28:52

** Ожидаемое поведение **
замок открыл - статус открыто 
замок закрыл - статус закрыто 

** Скриншоты/ Логи **
лог в режиме debag
[logs (4).zip](https://github.com/sprut/Hub/files/5184317/logs.4.zip)
![image](https://user-images.githubusercontent.com/31984665/92409126-348fcc80-f148-11ea-9529-4738c6b87c9d.png)
![IMG_3069](https://user-images.githubusercontent.com/31984665/92409167-538e5e80-f148-11ea-8b7b-cdec6308cd7e.jpg)

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by bumer0** [comment]
если руками открываешь замок или закрываешь - статус не меняется.

**Comment by MakeSimpleOrg** [comment]
Проблемы замка давно исправлены, все остальное связано с мощностью/плохой связью/проблемами в стике, к самому замку не относится.
