### ISSUE TITLE
ошибка в работе TRADFRI bulb E14 WS candle opal 470lm

### ISSUE THREAD

**Issue by vladitep** [sprut/Hub#2543]
Лампочка TRADFRI bulb E14 WS candle opal 470lm, добавляется в спрутхаб без каких либо ошибок, корректно обновляет прошивку, но после этого - не управляет лампой и не видит ее текущего статуса. Но при физическом отключении лампы - видит что устройство не в сети.  

Raspberry pi 3
Sprut.stick ZigBee 2 Pro
1.9.8 (11054)

**Comment by Batyushin** [comment]
необходима точная модель устройства. так как она идентифицируется в Sprut.hub

**Comment by vladitep** [comment]
Этой информации достаточно?
Structure
Endpoint 1 (COLOR_TEMPERATURE_LIGHT)
Input
0000_Basic
0000_ZCLVersion: 8 [UNSIGNED_8_BIT_INTEGER]
0001_ApplicationVersion: 17 [UNSIGNED_8_BIT_INTEGER]
0003_HWVersion: 1 [UNSIGNED_8_BIT_INTEGER]
0004_ManufacturerName: IKEA of Sweden [CHARACTER_STRING]
0005_ModelIdentifier: TRADFRIbulbE14WScandleopal470lm [CHARACTER_STRING]
0006_DateCode: 20211201 [CHARACTER_STRING]
0007_PowerSource: 1 [ENUMERATION_8_BIT]
4000_SWBuildID: 1.1.003 [CHARACTER_STRING]
0300_ColorControl
1000_TouchlinkCommissioning
0003_Identify
0004_Groups
0005_Scenes
0006_OnOff
FC57_ManufacturerSpecific
0008_LevelControl
Output
0019_OtaUpgrade
Endpoint 242 (ZGP_PROXY_BASIC)
Input
0021_GreenPower
Output
0021_GreenPower

**Comment by Batyushin** [comment]
попробовать удалить и добавить лампу повторно.

**Comment by vladitep** [comment]
1.9.9 (11328) 
Удалил, добавил - добавилось без проблем, появилось в интерфейсе. Не работает - на команды не отвечает.
