### ISSUE TITLE
0005_ModelIdentifier: TS0201

### ISSUE THREAD

**Issue by Batyushin** [sprut/Hub#259]
Address: 842E14FFFEF30E2B/3DE1<br><br><b>Neighbors</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th></tr><tr><td>000B57FFFE80CEF5</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>63</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 67</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ2000_a476raq2</li><li>0005_ModelIdentifier: TS0201</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 31</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2610</li></ul></li><li>0004_Groups<ul></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 2810</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Sun Sep 20 22:52:22 MSK 2020

[Sun Sep 20 22:54:37 MSK 2020.pcap.zip](https://github.com/sprut/Hub/files/5252521/Sun.Sep.20.22.54.37.MSK.2020.pcap.zip)
Телеграм: [@red_ik](tg://resolve?domain=red_ik )
Девайс в [каталоге](https://v2.sprut.ai/catalog/item/heiman-temperature-humidity-sensor-2).
Покупал [тут](https://jhome.ru/catalog/sensors/241/).

**Comment by Bigmanekb** [comment]
название ишью неправильное. Надо жеж 0005_ModelIdentifier: TS0201 указывать

**Comment by Batyushin** [comment]
> название ишью неправильное. Надо жеж 0005_ModelIdentifier: TS0201 указывать

поправил, спасиб
