### ISSUE TITLE
Огромная просьба прокинуть в СХ wifi железки от Xiaomi

### ISSUE THREAD

**Issue by jigi84** [sprut/Hub#26]
Такие как
Пылесос
Увлажнитель
Приточная вентиляция

Сразу извиняюсь, если не тут и не то написал.

**Comment by andreypopov** [comment]
В этом плагине я хотел уделить вниманию только робороку. 
Чтобы что-то другое подключить, мне надо иметь железку на руках, я не могу писать код вслепую.

**Comment by andreypopov** [comment]
https://github.com/andreypopov/node-red-contrib-miio-roborock

мне кажется, они заколебутся это делать) я прокинул роборок через нодред

**Comment by jigi84** [comment]
> https://github.com/andreypopov/node-red-contrib-miio-roborock
> 
> мне кажется, они заколебутся это делать) я прокинул роборок через нодред

Если бы ты закуинл видос для нубов как этот норед работает, было бы вообще прекрасно.
я с СХ и ВБ разобрался не с первого раза, а вот по НОДу будет еще веселее, особенно учитывая что инфа многая на английском. 
пылесос для меня тема актуальная тоже, но как и куда поставить нод для меня загадка, нужен Гайд для нубов

**Comment by sprut666666** [comment]
Сделать не проблема, самая большая проблема что по человечески пока сделать нельзя...

**Comment by Bigmanekb** [comment]
на самом деле логику добывания токена можно будет потом упростить ежели получится такая возможность, а саму интеграцию это вообще не останавливает как я полагаю.... пока можно с ручным токеном, потом с логином паролем.... но интеграция то будет та же самая вроде как ? или я что-то не так понимаю ?
