### ISSUE TITLE
R10A8 реле не управляется из SH

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#262]
** Подробное описание ошибки **
Нет возможности управлять модулем R10A8 через SH 

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Подключить к ВБ модуль R10A8
2. Создать контроллер MQTT в SH и включить его
3. Перейти в Аксессуары и попробовать поуправлять этим блоком

** Ожидаемое поведение **
Будет управление R10A8

** Скриншоты/ Логи **

** Пожалуйста, заполните следующую информацию: **
  - Версия: SH 1.6.5

** Дополнительные материалы **
выслал

**Comment by sprut666666** [comment]
1.6.5 работает ?

**Comment by Ziracul** [comment]
да
