### ISSUE TITLE
темплейты WB-MSW v3 ModBus доработка

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#264]
** Максимально подробное описание предложения.**
Доработка действующего темлейта:
- добавлен вольтметр;
- добавлено 32 ячейки памяти, ИК приемника передатчика
- добавлена возможность записи ИК в датчик
- удаление\очистка всех ячеек памяти
- исправлено воспроизведение, было указано что выключатель в автоматическом режиме выключается, необходимо просто чтение, т.к. прошивка датчика сама после воспроизведения возвращает значение 0

** Дополнительные материалы **
![image](https://user-images.githubusercontent.com/60096192/94000751-a737b380-fda8-11ea-9f7c-0b0775e39583.png)
![image](https://user-images.githubusercontent.com/60096192/94000783-b3bc0c00-fda8-11ea-8b55-b58a11950770.png)

Предлагаю добавить в последующую сборку.

[WB-MSW3.zip](https://github.com/sprut/Hub/files/5269230/WB-MSW3.zip)

**Comment by sprut666666** [comment]
1.6.5
