### ISSUE TITLE
ошибка в работе TS0011

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#265]
** Подробное описание ошибки **
При физическом выключении света, в HomeKit статус остается включённый

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Подойти к выключателю весящему на стене, счет должен быть включен
2. Нажать на выключатель, свет должен погаснуть 
3. В HomeKit статус выключателя останется включённый
![IMG_1999](https://user-images.githubusercontent.com/60096192/94002916-950b4480-fdab-11ea-9c54-36ccacff2bdc.PNG)
4. В СХ указано два типа, Активно и Включено, при физическом нажатии на клавишу включается и выключается только тип Активно.
![IMG_1998](https://user-images.githubusercontent.com/60096192/94003508-5aee7280-fdac-11ea-8082-9a39d7ced5d5.PNG)

** Ожидаемое поведение **
Что при физическом управлении устройством, измененный статус будет виден в HomeKit и C{

** Скриншоты/ Логи **
Скины, приложены выши

** Пожалуйста, заполните следующую информацию: **
  -СХ 1.6.4

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
Вы уверены что ничего руками не правили ? и забыли об этом умолчать ?

**Comment by droni4** [comment]
Руками трогал выключатель ))
