### ISSUE TITLE
Добавить поддержку модуля для управления мотороми (жалюзи, шторы) Fibaro FGR-223 

### ISSUE THREAD

**Issue by Yuanti** [sprut/Hub#267]
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>22</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0303</td></tr><tr><td width=35%>Device Id</td><td>1000</td></tr><tr><td width=35%>App Version</td><td>5.0</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Class B Motor</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td></td><td>[]</td></tr><tr><td>2</td><td></td><td>[]</td></tr><tr><td>3</td><td></td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 AssociationGRPInfo</li><li>V1 ZWavePlusInfo</li><li>V1 Configuration</li><li>V1 CRC16Encap</li><li>V4 SwitchMultiLevel<ul><li>Primary Type: DOWN_UP</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 FirmwareUpdateMD</li><li>V1 Basic</li><li>V2 ManufacturerSpecific</li><li>V1 ApplicationStatus</li><li>V2 Protection</li><li>V2 Version</li><li>V1 DeviceResetLocally</li><li>V3 Meter<ul><li>Energy: Unknown</li><li>Power: Unknown</li></ul></li><li>V2 Association</li><li>V2 MultiChannel</li><li>V3 CentralScene</li><li>V1 NoOperation</li><li>V3 MultiChannelAssociation</li><li>V1 Security</li><li>V8 Alarm<ul><li>PowerManagement</li><li>System</li></ul></li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li></ul></li><li>Endpoint 1<ul><li>V1 AssociationGRPInfo</li><li>V1 ZWavePlusInfo</li><li>V3 Meter<ul><li>Energy: Unknown</li><li>Power: Unknown</li></ul></li><li>V4 SwitchMultiLevel<ul><li>Primary Type: DOWN_UP</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V2 Association</li><li>V3 MultiChannelAssociation</li><li>V1 Security</li><li>V8 Alarm<ul><li>PowerManagement</li><li>System</li></ul></li><li>V1 Basic</li><li>V1 ApplicationStatus</li></ul></li><li>Endpoint 2<ul><li>V1 AssociationGRPInfo</li><li>V1 ZWavePlusInfo</li><li>V4 SwitchMultiLevel<ul><li>Primary Type: DOWN_UP</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V2 Association</li><li>V3 MultiChannelAssociation</li><li>V1 Security</li><li>V1 Basic</li><li>V1 ApplicationStatus</li></ul></li></ul><br>Last update: Sun Sep 27 11:53:21 UTC 2020

**Comment by MakeSimpleOrg** [comment]
Проверить в 1.6.7
