### ISSUE TITLE
Добавить поддержку модуля TKB HOME TZ74

### ISSUE THREAD

**Issue by Yuanti** [sprut/Hub#268]
[TKB HOME TZ74.pdf](https://github.com/sprut/Hub/files/5382735/TKB.HOME.TZ74.pdf)
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>23</td></tr><tr><td width=35%>Manufacturer Id</td><td>0118</td></tr><tr><td width=35%>Device Type</td><td>0311</td></tr><tr><td width=35%>Device Id</td><td>0304</td></tr><tr><td width=35%>App Version</td><td>2.3</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td></td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 AssociationGRPInfo</li><li>V1 ZWavePlusInfo</li><li>V1 Configuration</li><li>V1 SwitchBinary</li><li>V1 SceneActuatorConfiguration</li><li>V1 FirmwareUpdateMD</li><li>V1 Basic</li><li>V2 ManufacturerSpecific</li><li>V1 SceneActivation</li><li>V2 Version</li><li>V1 DeviceResetLocally</li><li>V1 SwitchAll</li><li>V2 Association</li><li>V2 MultiChannel</li><li>V1 NoOperation</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li></ul></li><li>Endpoint 1<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li><li>Endpoint 2<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li></ul><br>Last update: Sun Sep 27 12:10:04 UTC 2020
Сайт производителя https://www.facebook.com/ZWAVECN/

**Comment by MakeSimpleOrg** [comment]
Где ссылка на каталог, на сайт производителя, и на pdf инструкцию?

**Comment by Yuanti** [comment]
> 
> 
> Где ссылка на каталог, на сайт производителя, и на pdf инструкцию?

Приложил инструкцию и сайт

**Comment by MakeSimpleOrg** [comment]
Добавлено.
