### ISSUE TITLE
Eltex SZ-W02

### ISSUE THREAD

**Issue by Bigmanekb** [sprut/Hub#269]
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>12</td></tr><tr><td width=35%>Manufacturer Id</td><td>039B</td></tr><tr><td width=35%>Device Type</td><td>0002</td></tr><tr><td width=35%>Device Id</td><td>0003</td></tr><tr><td width=35%>App Version</td><td>1.26</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Meter</td></tr><tr><td width=35%>Specific Class</td><td>Simple Meter</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td></td><td>[]</td></tr><tr><td>2</td><td></td><td>[]</td></tr><tr><td>3</td><td></td><td>[]</td></tr><tr><td>4</td><td></td><td>[]</td></tr><tr><td>5</td><td></td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 AssociationGRPInfo</li><li>V2 ManufacturerSpecific</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V2 Version</li><li>V1 ZWavePlusInfo</li><li>V8 Alarm<ul></ul></li><li>V1 FirmwareUpdateMD</li><li>V3 MultiChannelAssociation</li><li>V1 Security</li><li>V1 DeviceResetLocally</li><li>V2 Meter<ul><li>Count: Unknown</li></ul></li><li>V1 Basic</li><li>V2 Association</li><li>V2 MultiChannel</li><li>V1 Battery</li><li>V1 NoOperation</li><li>V2 WakeUp</li></ul></li><li>Endpoint 1<ul><li>V1 ZWavePlusInfo</li><li>V8 Alarm<ul></ul></li><li>V1 AssociationGRPInfo</li><li>V3 MultiChannelAssociation</li><li>V2 Meter<ul><li>Count: Unknown</li></ul></li><li>V1 Basic</li><li>V2 Association</li></ul></li><li>Endpoint 2<ul><li>V1 ZWavePlusInfo</li><li>V8 Alarm<ul></ul></li><li>V1 AssociationGRPInfo</li><li>V3 MultiChannelAssociation</li><li>V2 Meter<ul><li>Count: Unknown</li></ul></li><li>V1 Basic</li><li>V2 Association</li></ul></li></ul><br>Last update: Mon Sep 28 21:43:05 MSK 2020

[Ссылка на устройство](https://eltex-co.ru/catalog/registratory/registrator_potrebleniya_vody_sz-w02/)
[Документация](https://eltex-co.ru/upload/iblock/58f/SZ-W02_user_manual.pdf)
[логи.zip](https://github.com/sprut/Hub/files/5294389/default.zip)

**Comment by Bigmanekb** [comment]
Я тут подключился через дефаро-стик нормальный, картинка чутка поменялась

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>3</td></tr><tr><td width=35%>Manufacturer Id</td><td>039B</td></tr><tr><td width=35%>Device Type</td><td>0002</td></tr><tr><td width=35%>Device Id</td><td>0003</td></tr><tr><td width=35%>App Version</td><td>1.26</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Meter</td></tr><tr><td width=35%>Specific Class</td><td>Simple Meter</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1.1]</td><td>4</td></tr><tr><td>2</td><td> report meter 1</td><td>[]</td><td>?</td></tr><tr><td>3</td><td> report meter 2</td><td>[]</td><td>?</td></tr><tr><td>4</td><td> ALARM meter 1</td><td>[]</td><td>?</td></tr><tr><td>5</td><td> ALARM meter 2</td><td>[]</td><td>?</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 MultiChannel</li><li>V2 WakeUp</li><li>V2 ManufacturerSpecific</li><li>V2 Meter<ul><li>Count: Unknown</li></ul></li><li>V8 Alarm<ul></ul></li><li>V1 NoOperation</li><li>V1 FirmwareUpdateMD</li><li>V2 Association</li><li>V3 MultiChannelAssociation</li><li>V1 AssociationGRPInfo</li><li>V2 Version</li><li>V1 Battery<ul><li>Level: 100</li><li>Low: false</li></ul></li><li>V1 ZWavePlusInfo</li><li>V1 DeviceResetLocally</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 Basic</li><li>V1 Security</li></ul></li><li>Endpoint 1<ul><li>V1 AssociationGRPInfo</li><li>V2 Meter<ul><li>Count: Unknown</li></ul></li><li>V1 ZWavePlusInfo</li><li>V8 Alarm<ul></ul></li><li>V1 Basic</li><li>V2 Association</li><li>V3 MultiChannelAssociation</li></ul></li><li>Endpoint 2<ul><li>V1 AssociationGRPInfo</li><li>V2 Meter<ul><li>Count: Unknown</li></ul></li><li>V1 ZWavePlusInfo</li><li>V8 Alarm<ul></ul></li><li>V1 Basic</li><li>V2 Association</li><li>V3 MultiChannelAssociation</li></ul></li></ul><br>Last update: Wed Nov 18 01:08:48 MSK 2020

**Comment by MakeSimpleOrg** [comment]
1.6.6
