### ISSUE TITLE
Не рабоатет долгое нажатие кнопки Mi

### ISSUE THREAD

**Issue by jigi84** [sprut/Hub#27]
Кнопка Mi круглая. Zegbee
В ХК долгое нажатие кнопки читается как короткое нажатие. В Михоум долгое нажатие работало. 

Кнопка
https://ru-mi.com/besprovodnoy-kommutator-xiaomi-mi-smart-home-wireless-switch?gclid=Cj0KCQjws7TqBRDgARIsAAHLHP5xlt890Ng3NXTzbeq4ctG5q-5kUQaNU2ogCMUnkmI3Lt5YtESfB_8aAgmHEALw_wcB

**Comment by diamond5170** [comment]
Отклонено. Нет модели кнопки как минимум. А по хорошему еще и дебаг включить и показать, какие сообщения приходят от зигби при коротком и длинном нажатии.
