### ISSUE TITLE
Zigbee - Aqara WXKG12LM странное поведение при добавлении

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#270]
** Подробное описание ошибки **
При добавлении в СХ не определяется нормально как остальные устройства (пишет NO_TEMPLATE, но шаблон то как раз есть) и не создается аксессуар
После 1-3 перезагрузок хаба появляется аксессуар, init CX: REMOVE_ALL_GROUPS

** Как воспроизвести ? **
Добавлял на новый хаб несколько раз - всегда результат один

** Ожидаемое поведение **
Что устройство добавится и создастся аксессуар

** Скриншоты/ Логи **
<img width="1226" alt="WXKG12LM" src="https://user-images.githubusercontent.com/55746897/94685734-846e4780-0332-11eb-852b-4582af680d4b.png">

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.6.4b

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by dragaleff** [comment]
Не удаляя его попробуй опять включить поиск и ввести его в режим спаривания. Он "доспарится". У меня многие так делают

**Comment by sprut666666** [comment]
1.6.5
