### ISSUE TITLE
При перезагрузке хаба, срабатывают автоматизации привязанные к Aqara Opple и возможно другие

### ISSUE THREAD

**Issue by Bigmanekb** [sprut/Hub#271]
При перезагрузке хаба, сработали все автоматизации, которые привязаны к подключенному Aqara Opple.

Связка SprutHub - Node Red - различные системы

Например на кнопки Aqara Opple привязан toggle розетки и отключение всего света в квартире. Розетка сделала toggle 3 раза, свет вырубился и не давал включаться в течение примерно 20 секунд.

Используется готовая нода SprutHub и не установлена защита от повторных сообщений

![изображение](https://user-images.githubusercontent.com/46221443/94752630-3d6d6a00-03a5-11eb-9718-ecfacec34f15.png)

происходит при каждой перезагрузке хаба

**Comment by sprut666666** [comment]
1.6.5

**Comment by Bigmanekb** [comment]
> 1.6.5

не вылечилось
