### ISSUE TITLE
После перезагрузки снова видны скрытые аксессуары

### ISSUE THREAD

**Issue by simart11** [sprut/Hub#274]
В версии 1.6.5b на вкладке аксессуары есть возможность снять галку и скрыть устройство в том числе из HomeKit. Но после перезагрузки хаба все устройства на вкладке аксессуары вновь становятся видимыми в том числе в HomeKit. В логах не каких ошибок нет.

**Comment by sprut666666** [comment]
Исправлено, скоро будет минорный апдейт.
