### ISSUE TITLE
Статус диммера в хабе (modbus wb-mrgbw-d) 

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#275]
** Подробное описание ошибки **

При управлении кнопками (родными) диммером wb-mrgbw-d, подключенным по modbus в хабе не меняется уровень яркости и состояние устройства (вкл/выкл) 

У меня это не работает с моим шаблоном для диммера с бета-версией прошивки 2.0 на 4 белых канала, у коллеги С А со стандартной прошивкой W-канал

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Подключить диммер через модбас
2. Включить любой канал с кнопки
3. Убедиться, что в Хомките аксессуар так и остался выключенным

** Ожидаемое поведение **
Что состояние аксессуара в хабе будет соответствовать реальному состоянию устройства

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.6.5b

** Дополнительные материалы **
Мой шаблон:

[

  {
    "name": "Диммер 4W (2.0)",
    "manufacturer": "WirenBoard",
    "model": "WB-MRGB",
    "modelId": "WBMRGB",
    "init": {
      "modelId": {
        "type": "String",
        "address": 200,
        "function": "Holding",
        "length": 6
      },
      "firmware": {
        "type": "String",
        "address": 250,
        "function": "Holding",
        "length": 15
      }
    },
    "services": [
      {
        "name": "G канал",
        "type": "Lightbulb",
        "characteristics": [
          {
            "type": "Brightness",
            "link2": {
              "type": "Integer",
              "address": 0,
              "function": "Holding",
              "max": 255
            },
            "data": {
              "PollingTime": 1000
            }
          }
        ]
      },
      {
        "name": "R канал",
        "type": "Lightbulb",
        "characteristics": [
          {
            "type": "Brightness",
            "link2": {
              "type": "Integer",
              "address": 1,
              "function": "Holding",
              "max": 255
            },
            "data": {
              "PollingTime": 1000
            }
          }
        ]
      },
      {
        "name": "B канал",
        "type": "Lightbulb",
        "characteristics": [
          {
            "type": "Brightness",
            "link2": {
              "type": "Integer",
              "address": 2,
              "function": "Holding",
              "max": 255
            },
            "data": {
              "PollingTime": 1000
            }
          }
        ]
      },
      {
        "name": "W канал",
        "type": "Lightbulb",
        "characteristics": [
          {
            "type": "Brightness",
            "link2": {
              "type": "Integer",
              "address": 3,
              "function": "Holding",
              "max": 255
            },
            "data": {
              "PollingTime": 1000
            }
          }
        ]
      }
    ],
    "options": [
      {
        "link2": {
          "type": "Integer",
          "address": 128,
          "function": "Holding"
        },
        "name": "Modbus-адрес устройства",
        "value": 1,
        "min": 1,
        "max": 252
      },
      {
        "link2": {
          "type": "Integer",
          "address": 5,
          "function": "Holding"
        },
        "name": "Режим работы кнопок",
        "value": 0,
        "values": [
          {
            "value": 0,
            "name": "Стандартный режим"
          },
          {
            "value": 1,
            "name": "Отключить управление"
          }
        ]
      }
    ]
  }
]

**Comment by sprut666666** [comment]
проверить на сборке 5722 и выше

**Comment by Alxprv** [comment]
При смене состояния диммера кнопкой, привязанной к контакту (шаблон стандартный, по каналам) в СХ и ХК изменение состояния не происходит - устройство остаётся включенным с прежним уровнем яркости, тогда как в реальности оно выключено.

**Comment by Alxprv** [comment]
В MQTT аж 2 устройства есть:
/devices/wb-mrgb_204/controls/Brightness B - яркость
/devices/wb-mrgb_204/controls/Enable B
