### ISSUE TITLE
кастомные шаблоны Xiaomi

### ISSUE THREAD

**Issue by pabl33** [sprut/Hub#2758]
https://wiki.spruthub.ru/Добавление_кастомных_шаблонов_для_любых_устройств

если у вас есть ещё какие-то шаблоны,кидайте их в комментарии.
если сделанный вами шаблон уже выложили,и у вас есть новая/альтернативная версия так же кидайте в комментарии,отредактирую.

бризер Xiaomi MIJIA Electric Air Purifier MJXFJ-150-A1
[dmaker.airfresh.a1.json](https://github.com/sprut/Hub/files/13516577/dmaker.airfresh.a1.json)
бризер Xiaomi c1-80
[zhimi.airfresh.ua1.json](https://github.com/sprut/Hub/files/13503703/zhimi.airfresh.ua1.json)
бризер Xiaomi Smartmi Fresh Air System Wall Mounted XFXTDFR02ZM
[zhimi.airfresh.va4-5.json](https://github.com/sprut/Hub/files/13503718/zhimi.airfresh.va4-5.json)

напольный вентилятор Mi Smart Standing Fan Pro
[dmaker.fan.p15.json](https://github.com/sprut/Hub/files/13503626/dmaker.fan.p15.json)
напольный вентилятор Xiaomi Smart Standing Fan 2
[dmaker.fan.p18.json](https://github.com/sprut/Hub/files/13503634/dmaker.fan.p18.json)
напольный вентилятор Smartmi Dc Inverter Floor Fan 2
[zhimi.fan.v2.json](https://github.com/sprut/Hub/files/13503745/zhimi.fan.v2.json)

робот-пылесос Roborock S6 Pure (Global) S6P02-00
[roborock.vacuum.a08.json](https://github.com/sprut/Hub/files/13503662/roborock.vacuum.a08.json)
робот-пылесос Roborock S7
[roborock.vacuum.a15.json](https://github.com/sprut/Hub/files/13503674/roborock.vacuum.a15.json)

очиститель воздуха Xiaomi Smart Air Purifier 4
[zhimi.airp.mb5a.json](https://github.com/sprut/Hub/files/13503720/zhimi.airp.mb5a.json)
очиститель воздуха Mi Air Purifier 2S
[zhimi.airpurifier.ma2.json](https://github.com/sprut/Hub/files/13503729/zhimi.airpurifier.ma2.json)
очиститель воздуха Xiaomi Mi Air Purifier Pro
[zhimi.airpurifier.v6.json](https://github.com/sprut/Hub/files/13503733/zhimi.airpurifier.v6.json)

**Comment by permadm** [comment]
Умная розетка Mijia WiFi Smart Plug (ZNCZ02CM)
[permadm.chuangmi.plug.m3.json] переехало в официальные шаблоны

Увлажнитель Mi Smart Humidifier
[permadm.deerma.humidifier.jsq.json] переехало в официальные шаблоны

- Шаблон устарел (Увлажнитель Mijia Smart Anti-bacterial Humidifier 2 (MJJSQ05DY)
[permadm.deerma.humidifier.jsq2g.json] переехало в официальные шаблоны

- Шаблон устарел (Увлажнитель Xiaomi Smart Humidifier 2
[permadm.deerma.humidifier.jsq2w.json] переехало в официальные шаблоны

Увлажнитель Mi Smart Antibacterial Humidifier
[permadm.deerma.humidifier.jsq5.json] переехало в официальные шаблоны

Увлажнитель Mi Smart Humidifier (только облако)
[permadm.deerma.humidifier.mjjsq.json] переехало в официальные шаблоны

Шлюз Xiaomi Gateway 2 (v3) DGNWG02LM
[permadm.lumi.gateway.v3_3.json](https://github.com/sprut/Hub/files/13503937/permadm.lumi.gateway.v3_3.json)

Нательный термометр Miaomiaoce MMC-T201-1 Blue (не тестироваллось)
[permadm.miaomiaoce.thermo.t01.json](https://github.com/sprut/Hub/files/13503938/permadm.miaomiaoce.thermo.t01.json)

Очиститель воздуха Xiaomi Smart Air Purifier 4 Pro
[permadm.zhimi.airp.vb4.json] переехало в официальные шаблоны

Очиститель воздуха Mi Air Purifier 3/3H
[permadm.zhimi.airpurifier.mb3.json] переехало в официальные шаблоны

- Шаблон устарел (Увлажнитель Smartmi Humidifier (CJXJSQ02ZM)
[permadm.zhimi.humidifier.ca1.json] переехало в официальные шаблоны

Увлажнитель Smartmi Evaporative Humidifier 2, CJXJSQ04ZM
[permadm.zhimi.humidifier.ca4.v3.json] переехало в официальные шаблоны

Умная розетка Mi WiFi Smart Plug
[permadm.chuangmi.plug.212a01.v2.json] переехало в официальные шаблоны

Трехкнопочный переключатель PTX (WIFI) (управление в режиме Только Облако)
[permadm.090615.switch.xswitch03.json](https://github.com/sprut/Hub/files/13505266/permadm.090615.switch.xswitch03.json)

**Comment by permadm** [comment]
- Шаблон устарел (Увлажнитель Xiaomi Mijia Pure Smart Humidifier 2 (CJSJSQ01XY) CN
[permadm.dmaker.humidifier.p2.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Умный удлинитель Gosund СP5
[permadm.cuco.plug.sp5.json] переехало в официальные шаблоны

Умный удлинитель Gosund CP5d
[permadm.cuco.plug.cp5d.json] переехало в официальные шаблоны

Умная розетка Xiaomi Gosund Smart Wall Socket White (CO1-M)
[permadm.cuco.plug.co1m.json] переехало в официальные шаблоны

Smartmi Evaporative Humidifier 3
[permadm.zhimi.humidifier.ca6.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Вентилятор Smartmi Standing Fan 2s
[permadm.dmaker.fan.p10.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Увлажнитель Mi Smart Humidifier
[permadm.deerma.humidifier.jsq1.json] переехало в официальные шаблоны

Анализатор почвы Flower Care (BLE)
[permadm.hhcc.plantmonitor.v1.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Датчик температуры и влажности с часами MiaoMiaoce Smart Hygrometer MHO-C303 (BLE)
[permadm.miaomiaoce.clock.ht02.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Новые версии шаблонов (добавлен статус работы)

Увлажнитель Xiaomi Mijia Pure Smart Humidifier 2 (CJSJSQ01XY) CN
[permadm.dmaker.humidifier.p2.v3.json] переехало в официальные шаблоны

Увлажнитель Mijia Smart Anti-bacterial Humidifier 2 (MJJSQ05DY)
[permadm.deerma.humidifier.jsq2g.v2.json] переехало в официальные шаблоны

Увлажнитель Xiaomi Smart Humidifier 2
[permadm.deerma.humidifier.jsq2w.v3.json] переехало в официальные шаблоны

Увлажнитель Smartmi Humidifier (CJXJSQ02ZM)
(Добавлен статус работы, исправлены показания уровня воды)
[permadm.zhimi.humidifier.ca1.v3.2.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Очиститель воздуха Xiaomi Smart Air Purifier 4 Lite CN
[permadm.zhimi.airp.rma2.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Напольный вентилятор Xiaomi Mijia DC Smart Inverter Tower Fan 2 (BPTS02DM)
[permadm.dmaker.fan.p45.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
UPDATE
Убраны из сценариев неиспользуемые текущие режимы,
добавлен датчик отсутствия воды (в виде датчика протечки)

Увлажнитель Mijia Smart Anti-bacterial Humidifier 2 (MJJSQ05DY)
[permadm.deerma.humidifier.jsq2g.v4.json] переехало в официальные шаблоны

Увлажнитель Xiaomi Smart Humidifier 2
[permadm.deerma.humidifier.jsq2w.v4.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
UPDATE
Убраны из сценариев неиспользуемые текущие режимы

Увлажнитель Xiaomi Mijia Pure Smart Humidifier 2 (CJSJSQ01XY) CN
[permadm.dmaker.humidifier.p2.v6.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Умный увлажнитель Mi Smart Humidifier
[permadm.deerma.humidifier.jsqm.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Очиститель воздуха Xiaomi Smart Air Purifier 4 Compact
[permadm.zhimi.airp.cpa4.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Тепловентилятор Smartmi Smart Fan Heater 
[permadm.zhimi.heater.nb1.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Вентилятор Zhimi DC 3  (не тестил)
[permadm.zhimi.fan.za1.json](https://github.com/sprut/Hub/files/13629296/permadm.zhimi.fan.za1.json)

**Comment by permadm** [comment]
Нагреватель-охладитель Xiaomi Smart Cool and Hot Fan Heater
[permadm.dmaker.fan.p23.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Очиститель воздуха Xiaomi Mi Smart Air Purifier 4 Lite EU
[permadm.zhimi.airp.rmb1.json] переехало в официальные шаблоны

**Comment by permadm** [comment]
Умный удлинитель Gosund СP5pro
[permadm.cuco.plug.cp5pro.JSON] переехало в официальные шаблоны

**Comment by zelas91** [comment]
А есть инструкция как писать шаблоны ?

**Comment by pabl33** [comment]
> А есть инструкция как писать шаблоны ?

в чате поддержки сейчас уже очень быстро делают шаблоны
