### ISSUE TITLE
Не правильно добавляется кнопка Aqara

### ISSUE THREAD

**Issue by Tuhulka** [sprut/Hub#276]
** Подробное описание ошибки **
При добавлении кнопки Aqara WXKG11LM, она добавляется как непознанное устройство. Информация о модели-нет ответа. Так происходит и на малине и на WB.

** Скриншоты/ Логи **
![кнопка акара WB](https://user-images.githubusercontent.com/49401605/95659618-e7c65980-0b2a-11eb-8c36-94c50cd1eb0b.jpg)
![кнопка акара WB 2](https://user-images.githubusercontent.com/49401605/95659626-ee54d100-0b2a-11eb-91ef-23a10897183c.jpg)

** Пожалуйста, заполните следующую информацию: **
  - Версия: SH 1.6.5

** Дополнительные материалы **
Результат такой же если кнопку тыкать.

**Comment by sprut666666** [comment]
исправлено
