### ISSUE TITLE
Универсальный датчик WB-MSW3

### ISSUE THREAD

**Issue by vitalek2019** [sprut/Hub#277]
** Подробное описание ошибки **
Ошибка в работе датчика движения WB-MSW3. 

** Как воспроизвести ? **
Контроллер WB с периферией подключен в SprutHub как "MQTT контроллер".
После обновления на версию 1.6.5, состояние датчика постоянно "Обнаружено движение -да"

** Скриншоты/ Логи **

![image](https://user-images.githubusercontent.com/52519798/95668017-2c94d380-0bb1-11eb-8236-64b1a69bb2bd.png)

![image](https://user-images.githubusercontent.com/52519798/95668021-4504ee00-0bb1-11eb-82ff-ba51140f6cf4.png)

![image](https://user-images.githubusercontent.com/52519798/95668030-606ff900-0bb1-11eb-8187-463b5de21752.png)

![image](https://user-images.githubusercontent.com/52519798/95668035-72ea3280-0bb1-11eb-9298-cc5de35de21f.png)

** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, IOS]

** Дополнительные материалы **
все отлично работало до обновления.

**Comment by sprut666666** [comment]
исправлено
