### ISSUE TITLE
Добавить поддержку модуля расширения Wirenboard WBE2-DO-R6C-1

### ISSUE THREAD

**Issue by OXOTH1K** [sprut/Hub#278]
[Описание модуля](https://wirenboard.com/ru/product/WBE2-DO-R6C-1/)
[Вики по модулю](https://wirenboard.com/wiki/Wiren_Board_6:_%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_%D1%80%D0%B5%D0%BB%D0%B5%D0%B9%D0%BD%D1%8B%D1%85_%D0%B2%D1%8B%D1%85%D0%BE%D0%B4%D0%BE%D0%B2_(WBE2-DO-R6C-1))
Инфа из Wirenboard MQTT топика:
wb-gpio | MOD1_OUT1 | switch | /devices/wb-gpio/controls/MOD1_OUT1 | 0 | OK

**Comment by OXOTH1K** [comment]
Сам запилил шаблон. Поправьте если где неправ.
```
{
  "manufacturer": "WirenBoard",
  "model": "WBE2-DO-R6C-1",
  "services": [
    {
      "type": "Switch",
      "characteristics": [
        {
          "type": "On",
          "link2": {
            "type": "Integer",
            "topicSearch": "/devices/wb-gpio/controls/(MOD[1-9]_OUT[1-9])",
            "topicGet": "/devices/wb-gpio/controls/(1)",
            "topicSet": "/devices/wb-gpio/controls/(1)/on"
          }
        }
      ]
    }
  ]
}

```

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/wirenboard-modul-rassirenia-wbe2-do-r6c-1
