### ISSUE TITLE
Некорректная работа датчиков движения

### ISSUE THREAD

**Issue by mazaxaka** [sprut/Hub#28]
** Подробное описание ошибки **
Датчик движения перестает уведомлять о движении раньше, чем оно по факту прекращаяется

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Зайти в настройки аксессуаров
2. В настройках датчика движения выставить время 40000, порог срабатывания 20
3. Проверить из приложения дом, время отображения датчика в состоянии обнаружено движение будет около 3х секунд. 
4. Смотрите ошибку

** Ожидаемое поведение **
Отображение состояния датчика = обнаружено движение после прекращения движения в течении установленного в настройках времени

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.
![Скриншот 2019-08-20 17 54 56](https://user-images.githubusercontent.com/3436461/63359036-b9a91780-c374-11e9-9378-4b1f6955a1c5.png)
 

видео срабатыавания датчика https://youtu.be/e5uATYA5bjc

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.2.1b

**Comment by sprut666666** [comment]
проверить на актуальной версии
