### ISSUE TITLE
Пульт филипс	RWL021 не получается использовать в тригерах управления лампами

### ISSUE THREAD

**Issue by sotidis** [sprut/Hub#280]
Пульт филипс  на кнопки реагирует но в тригерах лампами не управляет , пробовал с лампой филипс LWA001
и ламопй Икеа TRADFRI bulb E27 WS opal 1000lm

![1](https://user-images.githubusercontent.com/41840382/95686673-9c31af80-0bff-11eb-8185-02b6b171e5e1.jpeg)
![2](https://user-images.githubusercontent.com/41840382/95686676-9e940980-0bff-11eb-94b3-0e42e612243f.jpeg)

**Comment by sprut666666** [comment]
исправлено
