### ISSUE TITLE
0005_ModelIdentifier: WarningDevice - HEIMAN HS2WD-E сирена ZigBee

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#281]
Прошу добавить сирену Zigbee HEIMAN HS2WD-E
https://www.zigbee2mqtt.io/devices/HS2WD-E.html

Продается на ali, но брал на jhome.ru 

Результаты опроса:
Address: 000D6F0014F6DA11/632B<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 18</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 16</li><li>0004_ManufacturerName: Heiman</li><li>0005_ModelIdentifier: WarningDevice</li><li>0006_DateCode: 2018.03.21</li><li>0007_PowerSource: 129</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 549</li><li>0002_ZoneStatus: 0</li><li>0010_IasCieAddress: 0000000000000000</li><li>0011_ZoneId: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 36</li><li>0021_BatteryPercentageRemaining: 76</li></ul></li><li>0502_IasWd<ul><li>0000_MaxDuration: 240</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0009_Alarms<ul></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 18</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4619</li><li>0008_ImageTypeId: 8458</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Oct 11 18:39:24 UTC 2020

**Comment by shurikshurikov** [comment]
Очень жду добавления данного девайса!!!

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-smart-wireless-siren
