### ISSUE TITLE
После перезагрузки хаба не работает логика виртуального термостата

### ISSUE THREAD

**Issue by dragaleff** [sprut/Hub#284]
После перезагрузки хаба виртуальный термостат не придерживается логики. Он все время выключен. Для исправления необходимо перевести ползунок через "пороговые" значения.
Пример:
На термостате таргет 30гр
На термометре 20
Перезагружаем.
Термостат остается в выключенном состоянии.
Для исправления бага необходимо перевести ползунок на 31гр и затем на 19. Потом поставить требуемое значение температуры и логика заработает

1,6,5 иос 14

**Comment by sprut666666** [comment]
1.6.6
