### ISSUE TITLE
некорректная работа с Node-Red

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#285]
** Подробное описание ошибки **
если из NR отправляю команду true/false 
то лампа нормально управляется, 
но в ноде IN  ничего не происходит 

если из СХ отправляю команду true/false 
то лампа нормально управляется, 
в ноде IN меняется значение

** Как воспроизвести ? **
![IMAGE 2020-10-13 09:53:16](https://user-images.githubusercontent.com/31984665/95825675-ec149180-0d39-11eb-98d7-3f68ba2c1b39.jpg)

1 2 3 - это порядок как я нажимал 
в debag сообщение после 1 нажатия 2 и 3 

** Ожидаемое поведение **

** Скриншоты/ Логи **

** Пожалуйста, заполните следующую информацию: **
СХ 1.6.5B update 12/10/2020
Node-Red 1.1.3
node-red-contrib-spruthub 0.1.6

** Дополнительные материалы **
![IMAGE 2020-10-13 09:52:56](https://user-images.githubusercontent.com/31984665/95825651-e1f29300-0d39-11eb-919b-f1d506f278b6.jpg)

**Comment by sprut666666** [comment]
готово
