### ISSUE TITLE
Оформить Sprut.hub в версии для linux в качестве docker container

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#2858]
** Максимально подробное описание предложения.**
Сделать сборку с возможностью установки в качестве docker-контейнера с поддержкой docker-compose 
Подготовить базовый конфиг, описание shared folders, портов и прочего 

Получится прекрасный вариант работы в изолированной среде (над чем  так радеют разработчики) и экономия аппаратных ресурсов - так как можно будет наконец установить разные необходимые приложения на одину малину

**Comment by IIeTp** [comment]
а монетизация за спасибо получается?

**Comment by Alxprv** [comment]
Не понятен вопрос. 
У вас же лицензия - номера всякие и так далее, защита ПО своя

**Comment by Bigmanekb** [comment]
Не планируется в принципе
