### ISSUE TITLE
GL-S-007Z

### ISSUE THREAD

**Issue by SitkoAleksandr** [sprut/Hub#287]
Address: 00124B001EF9EBA4/457B<br><br><b>Structure</b><br><ul><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-S-007Z</li><li>0006_DateCode: 20131206</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 2.0.0</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 252</li><li>0001_CurrentSaturation: 254</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 12480</li><li>0004_CurrentY: 47190</li><li>0007_ColorTemperature: 129</li><li>0008_ColorMode: 1</li><li>4000_EnhancedCurrentHue: 0</li><li>4001_EnhancedColorMode: 0</li><li>4002_ColorLoopActive: 0</li><li>4003_ColorLoopDirection: 0</li><li>4004_ColorLoopTime: 25</li><li>4005_ColorLoopStartHue: 8960</li><li>4006_ColorLoopStoredHue: 0</li><li>400A_ColorCapabilities: 31</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Oct 13 16:24:38 MSK 2020

@Sitko_Aleksandr (телеграмм)
покупал тут https://aliexpress.ru/item/32926055612.html?spm=a2g0s.9042311.0.0.264d33edkO8IzD
в каталоге   https://v2.sprut.ai/catalog/item/gledopto-dual-white-and-color-led-gu10

**Comment by sprut666666** [comment]
готово
