### ISSUE TITLE
Перестал работать шаблон кастомного устройства PU3

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#288]
** Подробное описание ошибки **
к WB подключен через модбас устройство PU-3 (Панель задания и отображения температуры). 
Написан шаблон для спрутхаба. 

{
	"manufacturer": "Cityron",
	"model": "PU-3",
	"services": [{
		"type": "TemperatureSensor",
		"characteristics": [{
			"type": "CurrentTemperature",
			"link2": {
				"type": "Float",
				"topicSearch": "/devices/(temp_[0-9]{1,3})/controls/Current temperature/meta/type",
				"topicGet": "/devices/(1)/controls/Current temperature"
			},
			"type": "TargetTemperature",
			"link2": {
				"type": "Float",
				"topicSearch": "/devices/(temp_[0-9]{1,3})/controls/Target Temperature/meta/type",
				"topicSet": "/devices/(1)/controls/Target Temperature",
				"topicGet": "/devices/(1)/controls/Target Temperature"

			}
		}]
	}]
}

В спрутхаб устройство залетело и великолепно работало в 1.6.5 до какого то очередного обновления.

![image](https://user-images.githubusercontent.com/52490000/95902018-dc7a6480-0d9c-11eb-9b71-052d247ab3b5.png)
 
В настоящий момент Current temperature не соответствует показаниям встроенного датчика.
Target Temperature - работает исправно. т.е. я могу задать из спрутхаба нужную температуру и она поменяется в интерфейсе WB.

Вот данные в WB по этой панельке.

![image](https://user-images.githubusercontent.com/52490000/95902469-8bb73b80-0d9d-11eb-88e7-24502b78bdde.png)

как видно температура в WB 21.8 а в спрутхабе 23.6

** Ожидаемое поведение **
Отображение текущей температуры в соответствии с реальными показаниями встроенного датчика.

** Дополнительные материалы **
На всякий случай выкладываю темплейт WB данной панельки.

{
   "device_type":"TemperatureControlPanel",
   "device":{
      "name":"Temperature Control Panel",
      "id":"temp",
      "max_read_registers":0,
      "channels":[
         {
            "name":"Current temperature",
            "reg_type":"holding",
            "readonly":true,
            "address":0,
            "type":"value",
            "scale":0.1,
            "format":"s16"
         },
{
            "name":"Target Temperature",
            "reg_type":"holding",
            "readonly":false,
            "address":1,
            "type":"range",
            "scale":0.1,
	    "max":35
          },
{
            "name":"Outdoor temperature",
            "reg_type":"holding",
            "readonly":false,
            "address":9,
            "type":"value",
            "scale":0.1,
            "format":"s16"
           },

{
            "name":"Mode",
            "reg_type":"holding",
            "readonly":false,
            "address":3,
            "type":"range",
            "scale":1,
            "max":3,  
            "format":"s16"
         },
{
            "name":"FAN speed",
            "reg_type":"holding",
            "readonly":false,
            "address":4,
            "type":"range",
            "scale":1,
            "max":5
         },
        
         {
            "name":"Hours",
            "reg_type":"holding",
            "address":20,
            "type":"range",
            "max":23
         },
         {
            "name":"Minutes",
            "reg_type":"holding",
            "address":21,
            "type":"range",
            "max":59
         },
         {
            "name":"Week Day",
            "reg_type":"holding",
            "address":22,
            "type":"range",
            "max":7
         },
 {
            "name":"Power",
            "reg_type":"holding",
            "readonly":false,
            "address":2,
            "type":"switch"

          }

          ]
   }
}

**Comment by Popov2006** [comment]
может поможет: 
в логах вот такая информация


Received: topic=/spruthub/accessories/145/10/Thermostat/CurrentTemperature/set, value=22.7, retained=false
--

**Comment by magdi2000li7** [comment]
Похожая проблема

**Comment by magdi2000li7** [comment]
Могу изменить значение ползунка температуры через спрутхаб, с web ui синхронизируется. А получить данные с датчика не удается.

**Comment by tkasyanov** [comment]
Похожая проблема

**Comment by Popov2006** [comment]
Проблема решена. Был не правильный шаблон.
Вот правильный, созданный Дмитрием.

{
  "manufacturer": "Cityron",
  "model": "PU-3",
  "services": [
    {
      "type": "Thermostat",
      "data": {
        "Logic": {
          "selected": "GenericThermostat",
          "GenericThermostat": {
            "Hysteresis": 0.5
          }
        }
      },
      "characteristics": [
        {
          "type": "CurrentHeatingCoolingState",
          "validValues": "0,1"
        },
        {
          "type": "TargetHeatingCoolingState",
          "validValues": "0,1"
        },
        {
          "type": "CurrentTemperature",
          "link2": {
            "type": "Float",
            "topicSearch": "/devices/(temp_[0-9]{1,3})/controls/Current temperature/meta/type",
            "topicGet": "/devices/(1)/controls/Current temperature"
          }
        },
        {
          "type": "TargetTemperature",
          "link2": {
            "type": "Float",
            "topicSearch": "/devices/(temp_[0-9]{1,3})/controls/Target Temperature/meta/type",
            "topicSet": "/devices/(1)/controls/Target Temperature/On",
            "topicGet": "/devices/(1)/controls/Target Temperature"
          }
        }
      ]
    }
  ]
}
