### ISSUE TITLE
Работа диммера в хабе (modbus wb-mrgbw-d)

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#289]
** Подробное описание ошибки **
wb-mrgbw-d со стандартной прошивкой RGB + W
подключено WB на котором стоит SH по modbus

Клавиши нажимные (те что с пружинкой) подключены к wb-mrgbw-d
работа W
1. Нажимаем клавишу включения белого канала.
    - Ничего не происходит
2. Нажимаем клавишу включения белого канала.
    - Свет включается. В SH или HA видим, что свет включился на 59%
3. Выключаем свет через SH или HA.
   - Свет выключается
4. Нажимаем клавишу включения белого канала.
    - Ничего не происходит
5. Нажимаем клавишу включения белого канала.
    - Свет включается. В SH или HA видим, что свет включился на 59%

**Появилось лишнее нажатие физической кнопки. Необходимо, что бы свет включался поле первого нажатия.** 

1. Нажимаем клавишу включения белого канала.
    - Ничего не происходит
2. Нажимаем клавишу включения белого канала.
    - Свет включается. В SH или HA видим, что свет включился на 59%
3. Разжигаем свет на 100% через физическую кнопку или SH или HA.
    - Свет разгарается
3. Выключаем свет через SH или HA.
   - Свет выключается
4. Нажимаем клавишу включения белого канала.
    - Ничего не происходит
5. Нажимаем клавишу включения белого канала.
    - Свет включается. В SH или HA видим, что свет включился на 59%

**Физической кнопкой свет белого канала всегда включается на 59%, Необходимо, что бы свет включался на последнее значение не важно как был выключен свет.**

работа RGB 
1. Нажимаем клавишу включения RGB.
    - Ничего не происходит
2. Нажимаем клавишу включения RGB.
    - Свет включается. Светить синий. В SH или HA не видно включения RGB.
3. Включаем RGB в SH или HA
    - Свет становиться зеленый
3. Выключаем свет через SH или HA.
   - Свет выключается
4. Нажимаем клавишу включения RGB.
    - Ничего не происходит
5. Нажимаем клавишу включения RGB.
    - Свет включается. Светить синий. В SH или HA не видно включения RGB.

**Нет связи устройства, при включении и выключении физической клавишей и программное включение через SH или  HA. Хочется, что бы связь была восстановлена, Не было лишних нажатий, и включение происходило на уровень последнего % и цвета.**

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Перейдите к «...»
2. Нажмите «....»
3. Прокрутите вниз до «....»
4. Смотрите ошибку

** Ожидаемое поведение **
Четкое и краткое описание того, что вы ожидали.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия: SH 1.6.5 обновлено 14.10.2020 в 20:00 по Самаре

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
Вопросы с неактуальных версий не интересны, прошу перетестить на актуальной версии
