### ISSUE TITLE
Нелогичная работа терморегулятора

### ISSUE THREAD

**Issue by mazaxaka** [sprut/Hub#29]
** Подробное описание ошибки **
Странная штука по терморегуляторам. Он отображает как будто они включены, но в состоянии отображается будто выключены, нажимаешь на переключатель - они выключаются, хотя переключатель не двигается
![photo_2019-08-20 18 09 27](https://user-images.githubusercontent.com/3436461/63359590-ad718a00-c375-11e9-9478-079163718b78.jpeg)
![photo_2019-08-20 18 09 25](https://user-images.githubusercontent.com/3436461/63359605-b2ced480-c375-11e9-8c6d-d7489c443ede.jpeg)

** Как воспроизвести ? **
Происходит, если сначала поставить температуру 16, а потом включить нагрев. Если после этого ещё раз поменять температуру, то все ок

** Ожидаемое поведение **
![photo_2019-08-20 18 08 33](https://user-images.githubusercontent.com/3436461/63359535-9763c980-c375-11e9-93ee-d1e5f96a04af.jpeg)
![photo_2019-08-20 18 08 30](https://user-images.githubusercontent.com/3436461/63359549-9cc11400-c375-11e9-935c-092467b65b11.jpeg)

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.2.1b 

** Дополнительные материалы **
https://youtu.be/2j7CLbDgA1Y

**Comment by sprut666666** [comment]
Проверить на актуальной версии
