### ISSUE TITLE
Работа диммера в хабе (modbus DDM845R v3)

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#290]
** Подробное описание ошибки **
При включении света физической кнопкой свет плавно разжигается при выключении плавно выключается.

При включении света через SH или HA свет включается и выключается мгновенно

**Необходимо, что бы было плавное включение и выключение как физическими кнопками так и через SH или HA.**

Аналогично как и в [теме](https://github.com/sprut/Hub/issues/289) при включении физической кнопкой и выключения через SH или HA. Появляется дополнительное пустое нажатие физической кнопки.

**Необходимо включать и выключать свет как через физическую кнопку так и через SH или HA. без лишних дополнительных нажатий.**

Аналогично как и в [теме](https://github.com/sprut/Hub/issues/289) при включении физической кнопкой и выключения через SH или HA. не происходит запоминания последнего % на которой был включен модуль.

**Необходимо, что бы происходило запоминание последнего состояния % при выключении модуля без разницы ка оно происходило физически или через SH или HA.**

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Перейдите к «...»
2. Нажмите «....»
3. Прокрутите вниз до «....»
4. Смотрите ошибку

** Ожидаемое поведение **
Четкое и краткое описание того, что вы ожидали.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
    - Версия: SH 1.6.5 обновлено 14.10.2020 в 20:00 по Самаре

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
Вопросы с неактуальных версий не интересны, прошу перетестить на актуальной версии
