### ISSUE TITLE
Не правильно работает триггер на сдвоенном беспроводном выключателе Aqara WXKG02LM

### ISSUE THREAD

**Issue by JonnyLuz** [sprut/Hub#291]
Похоже отдает двойное событие и поэтому стандартный триггер работает не стабильно, не может включить или выключить.Иногда это получается. Поменял на новый выключатель, стал работать, но на следующий день - та же история.
[logs (2).zip](https://github.com/sprut/Hub/files/5387634/logs.2.zip)

**Comment by sprut666666** [comment]
исправлено
