### ISSUE TITLE
Проблема с отображением крана в Neptun

### ISSUE THREAD

**Issue by OXOTH1K** [sprut/Hub#292]
В интеграции Neptun в HomeKit у крана вечный статус обновления и статус "начало". Помогает передернуть кран.

![image](https://user-images.githubusercontent.com/19778219/96348821-9551e380-10bc-11eb-890e-3903ba7a05e4.jpeg)

**Comment by corsaroff** [comment]
Присоединяюсь. Хотелось бы исправить.

**Comment by MakeSimpleOrg** [comment]
Включите логику в настройках сервиса крана.
В r3349 это будет происходить автоматически при создании крана.

**Comment by corsaroff** [comment]
> Включите логику в настройках сервиса крана.
> В r3349 это будет происходить автоматически при создании крана.

Только переключатель Виртуальная логика на кране от Нептуна недоступен для установки. Ждем r3349.

**Comment by corsaroff** [comment]
Обновился на r3375, удалил все аксессуары, удалил контроллер Neptun, создал заново, аксессуары появились, но на Кране виртуальная логика не включена, и самому включить нет возможности.

**Comment by OXOTH1K** [comment]
> Обновился на r3375, удалил все аксессуары, удалил контроллер Neptun, создал заново, аксессуары появились, но на Кране виртуальная логика не включена, и самому включить нет возможности.
> И соответственно кран так и висит в ХК со статусом «Начало...».

Можно создать виртуальный аксессуар и привязать его к реальному крану

**Comment by corsaroff** [comment]
> Можно создать виртуальный аксессуар и привязать его к реальному крану
И работает у тебя? Создал виртуальное устройство, включил логику, отображается нормально, но не работает. На Вкл/Выкл реальный кран никак не реагирует (в сантехшкафу который). И при привязке виртуального устройства характеристика "Активно" привязывается, а вот "Используется" и "Тип крана" нет (ошибка на скрине).
![Снимок экрана 2020-12-19 в 21 04 44](https://user-images.githubusercontent.com/31987140/102696395-03db2b00-423f-11eb-824d-d0b55e120fe1.png)

**Comment by MakeSimpleOrg** [comment]
Тип крана привязывать не нужно.
И нужно понимать, как работает привязка. Привязывать можно только к характеристикам, у которых есть связь, т.е. значок связи синий.
Можно просто использовать двухсторонние триггеры.

**Comment by corsaroff** [comment]
@MakeSimpleOrg добейте, пожалуйста, этот ишью 🙏 очень хочется кран с датчиками использовать!

**Comment by stalkerj** [comment]
Краны не управляются, оповещение о протечке не приходит
