### ISSUE TITLE
Не добавляется розетка BlitzWolf BW-SHP13

### ISSUE THREAD

**Issue by corsaroff** [sprut/Hub#293]
При попытке добавления устройства BlitzWolf BW-SHP13 процесс заканчивается на этапе "Таблица связей". В логе красным сообщение:
842E14FFFEDFA35C/5AC5: REPORTING, 0000_CurrentSummationDelivered : (3600 - 3600, 1)

Во вложение скриншот и часть лога.

![Снимок экрана 2020-10-17 в 20 27 11](https://user-images.githubusercontent.com/31987140/96349330-9d5b5480-10b7-11eb-80b3-edd36663b9b7.png)
[BW-SHP13.log](https://github.com/sprut/Hub/files/5396138/BW-SHP13.log)

Update: Через какое-то время розетка появилась в аксессуарах и HomeKit. Но при этом устройство на вкладке "Контроллеры" остается в статусе "Таблица связей".
![Снимок экрана 2020-10-18 в 09 39 50](https://user-images.githubusercontent.com/31987140/96360453-201af880-1126-11eb-889b-096dc3ba4182.png)

Версия SprutHub 1.6.5b, версия прошивки стика 6.7.7.0.

Ник в Telegram: @vklimov

Ссылка на каталог: https://v2.sprut.ai/catalog/item/blitzwolf-zigbee-30-smart-socket-eu

Куплена здесь: https://aliexpress.ru/item/4001153556759.html?spm=a2g0s.9042311.0.0.264d33edbQbCTW&_ga=2.45477740.936118427.1602956181-207417903.1602956181

Информация об устройстве:
Address: 842E14FFFEDFA35C/5AC5<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 64</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_3ooaz3ng</li><li>0005_ModelIdentifier: TS0121</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Unknown: � </li><li>FFE2_Unknown: 30</li></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 2</li></ul></li><li>0004_Groups<ul></ul></li><li>0B04_ElectricalMeasurement<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_Unknown: 1</li><li>8002_Unknown: 2</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>000B57FFFE80CDDE/1</td><td>0702_Metering</td></tr></table><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Oct 17 20:32:54 MSK 2020

**Comment by sprut666666** [comment]
исправлено
