### ISSUE TITLE
Создание категорий и поиска для сценариев

### ISSUE THREAD

**Issue by Micvisual** [sprut/Hub#2952]
В пункте "сценарии" хочется добавить категории сценариев с их созданием и редактированием. Например я создал более 30 сценариев связанных с лампами/светильниками, климатическими устройствами , выключателями и в дальнейшем если хочу отредактировать что нибудь, приходятся потратить время для поиска необходимого сценария и вот поэтому тут напрашивается поиск по имени сценария и создания категорий например "освещение, климат и т.п)

Вот как например глобальных сценариях есть категория "системные", сделать бы что то подобное, только чтобы названия можно было отредактировать и рядом добавить кнопку поиска

<img width="687" alt="Снимок экрана 2024-01-16 в 20 33 43" src="https://github.com/sprut/Hub/assets/77418295/ff589957-ee5c-4c04-ac85-b87d416b6905">

**Comment by sprut666666** [comment]
вынесено на голосование
