### ISSUE TITLE
Возможность редактировать виртуальное устройство, либо создавать копию из существующего

### ISSUE THREAD

**Issue by wsnzone** [sprut/Hub#2955]
При составлении больших виртуальных устройст очень часто что-то забываешь добавить и приходится "перебивать" все устройство руками.

Просьба либо дать возможность редактировать существующее устройство.

Либо (если архитектурно невозможно), создавать копию из созданного вируального (а в общем случае может даже создание виртуального из любого, даже физического) и показывать страницу редактирования копии. То войти в режим создания вируального устройства, скопировать из "шаблонного" все его сервисы и характеристики и остаться в режиме редактирования.

Обсуждения в чатах поддержки:
https://t.me/c/1756326800/39569/190158
https://t.me/c/1756326800/39574/159192
https://t.me/c/1756326800/1/132797
https://t.me/c/1756326800/40781/95310
https://t.me/c/1756326800/39569/78642

**Comment by sprut666666** [comment]
https://t.me/c/1756326800/204131/207452
