### ISSUE TITLE
SprutHub2 первоначальный запуск

### ISSUE THREAD

**Issue by Kostas623** [sprut/Hub#2958]
Хаб: Sprut.hub 2
Версия: неизвестна
Маркировка на корпусе устройства:
P/N:ISXA-73181391
S/N:3IJ510D2842
MAC:CC09C80D2842
Подключение к сети: проводное через Ethernet 
Описание проблемы:
Не происходит предварительное скачивание и установка ПО в устройство. Устройство подключается согласно инструкции: подключил сетевой кабель к устройству и к роутеру, подключил питание к устройству, загорелся красный светодиод, загорелся синий светодиод. Дальше ничего не происходит. Синий светодиод горит всегда. В роутере появляется IP адрес устройства, но, с помощью браузера к нему не подключится. Устройство в статусе скачивания ПО (синий светодиод Включен) находилось в течении 12 часов. Подключил к ТВ: spurhub не запущен, версия (недоступно) ((недоступно)+20231217_0641_spruthub2)
QR код показывает IP адрес устройства. 
Что сделано:
Поменял сетевой кабель, проверка подключения LAN посредством подключения ноутбука - все работает!

Как установить ПО В spruthub2 согласно пунктам инструкции?

**Comment by wsnzone** [comment]
Попробуйте сброс хаба методом зубочистки
https://wiki.spruthub.ru/%D0%A1%D0%B1%D1%80%D0%BE%D1%81_Sprut.hub_%D0%BD%D0%B0_%D0%B7%D0%B0%D0%B2%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D0%B5_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8

**Comment by Kostas623** [comment]
Спасибо большое. Все хорошо. Получилось запустить СХ2.
