### ISSUE TITLE
ZigBee - EfektaLab - EFEKTA_TH_LR

### ISSUE THREAD

**Issue by zubyk** [sprut/Hub#2969]
Производитель 	EfektaLab 
Модель 	EFEKTA_TH_LR
Прошивка 	1
WEB Build 	1.3.1
API Build 	1.9.7 (10895)

Telegram: [@Zarkon](https://t.me/Zarkon)
Где приобрели?
https://aliexpress.ru/item/1005006004048791.html?sku_id=12000035541082066
Ссылка на шаблоны - https://github.com/smartboxchannel/EFEKTA-TH-v2/tree/main/SprutHub_Templates

`Structure

    Endpoint 1
        Input
            0000_Basic
                0000_ZCLVersion: 1 [UNSIGNED_8_BIT_INTEGER]
                0001_ApplicationVersion: 3 [UNSIGNED_8_BIT_INTEGER]
                0002_StackVersion: 4 [UNSIGNED_8_BIT_INTEGER]
                0003_HWVersion: 1 [UNSIGNED_8_BIT_INTEGER]
                0004_ManufacturerName: EfektaLab [CHARACTER_STRING]
                0005_ModelIdentifier: EFEKTA_TH_LR [CHARACTER_STRING]
                0006_DateCode: 20231013 643 [CHARACTER_STRING]
                0007_PowerSource: 3 [ENUMERATION_8_BIT]
                4000_SWBuildID: 2.0.9 [CHARACTER_STRING]
            0001_PowerConfiguration
                0020_BatteryVoltage: 32 [UNSIGNED_8_BIT_INTEGER]
                0021_BatteryPercentageRemaining: 174 [UNSIGNED_8_BIT_INTEGER]
                003E_BatteryAlarmState: 0 [BITMAP_32_BIT]
                0201_Custom: 90 [UNSIGNED_16_BIT_INTEGER]
            0402_TemperatureMeasurement
                0000_MeasuredValue: -1731 [SIGNED_16_BIT_INTEGER]
                0220_Custom: false [BOOLEAN]
                0221_Custom: 33 [SIGNED_16_BIT_INTEGER]
                0222_Custom: 22 [SIGNED_16_BIT_INTEGER]
                0225_Custom: false [BOOLEAN]
                A19B_Custom: ds18b20 [CHARACTER_STRING]
            0405_RelativeHumidityMeasurement
                0000_MeasuredValue: 0 [UNSIGNED_16_BIT_INTEGER]
                0220_Custom: true [BOOLEAN]
                0221_Custom: 75 [SIGNED_16_BIT_INTEGER]
                0222_Custom: 35 [SIGNED_16_BIT_INTEGER]
                0225_Custom: false [BOOLEAN]
        Output
            0402_TemperatureMeasurement
            0003_Identify
            0405_RelativeHumidityMeasurement
            0006_OnOff
            0019_OtaUpgrade`

**Comment by zubyk** [comment]
готовый шаблон 
[EFEKTA_TH_LR.json](https://github.com/sprut/Hub/files/13990045/EFEKTA_TH_LR.json)

**Comment by Batyushin** [comment]
К сожалению, мы не можем обеспечить поддержку устройств DIY, из-за несоблюдение протокола Zigbee. 

В момент добавления подобных устройств мы столкнулись с проблемой несовместимости одного и того же устройства на разных версиях ПО.

Но вы всегда сможете воспользоваться возможностью написанием Custome шаблонов самостоятельно.
