### ISSUE TITLE
Добавить Термоголовку TS0601

### ISSUE THREAD

**Issue by denis86111** [sprut/Hub#299]
Address: BC33ACFFFE5E6579/A0D9

Structure
Endpoint 1
Input
0000_Basic
0000_ZclVersion: 3
0001_ApplicationVersion: 83
0002_StackVersion: 0
0003_HwVersion: 1
0004_ManufacturerName: _TZE200_ckud7u2l
0005_ModelIdentifier: TS0601
0006_DateCode:
0007_PowerSource: 3
EF00_ManufacturerSpecific
0004_Groups
0000_NameSupport: 0
0005_Scenes
0000_SceneCount: 0
0001_CurrentScene: 0
0002_CurrentGroup: 0
0003_SceneValid: false
0004_NameSupport: 0
Output
0019_OtaUpgrade
0000_UpgradeServerId: FFFFFFFFFFFFFFFF
0001_FileOffset: -1
0006_ImageUpgradeStatus: 0
000A_Time

Binding table

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags | 0
-- | --
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 82
Incoming Transfer Size | 82
Logical Type | End Device
Mac Capabilities | [REDUCED_FUNCTION_DEVICE]
Manufacturer Code | 4098
Out Going Transfer Size | 82
Stack Compliance | 22
 
TRV Tuya ZigBee 3,0 термоголовка
покупал тут https://aliexpress.ru/item/4001179398549.html?spm=a2g0s.9042311.0.0.542033edI6Ld9d&_ga=2.187331176.1597146965.1603204754-484972367.1602353842

**Comment by pabl33** [comment]
Address: BC33ACFFFE37E8A5/C821<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 83</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_ckud7u2l</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Unknown: 똰�옰�</li><li>FFE2_Unknown: 31</li><li>FFE4_Unknown: 0</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>

[2020-12-31_18-14-31.zip](https://github.com/sprut/Hub/files/5757659/2020-12-31_18-14-31.zip)

**Comment by yvovikn** [comment]
Тоже очень жду в спруте. Особенно с привязкой к сторонник датчикам для регулировки по комнатам.

**Comment by ImmortaleVita** [comment]
аналогично
пришло три штучки
чуток другие 
0001_ApplicationVersion: 85
0004_ManufacturerName: _TZE200_ywdxldoj
брал тут
https://aliexpress.ru/item/4001065119510.html?spm=a2g0s.9042311.0.0.703833edB9qyM2

могу чем помочь?

**Comment by toroff** [comment]
очень нужна прилинковка другого темп датчика. И возможность управлять отдельно открыто-закрыто.

**Comment by Doublenik8** [comment]
Пришло две штуки
Опять другие!

0001_ApplicationVersion: 64
0004_ManufacturerName: _TZE200_b6wax7g0
брал по ссылке из каталога Спрут  (сейчас ссылка битая)
https://v2.sprut.ai/catalog/item/moeshouse-moes-radiator-zigbee-tvr-controller 

Address: 84FD27FFFEA65846/4151

Structure
Endpoint 1 (SMART_PLUG)
Input
0000_Basic
0000_ZCLVersion: 3
0001_ApplicationVersion: 64
0002_StackVersion: 0
0003_HWVersion: 1
0004_ManufacturerName: _TZE200_b6wax7g0
0005_ModelIdentifier: TS0601
0006_DateCode:
0007_PowerSource: 3
FFDF_Custom: ��(��(
FFE2_Custom: 31
FFE4_Custom: 0
FFFE_Custom: 0
EF00_ManufacturerSpecific
0001_Custom: 1
0002_Custom: 26
0003_Custom: 210
0004_Custom: false
0005_Custom: 0
0007_Custom: 0
0008_Custom: false
0009_Custom: 1
000D_Custom: false
000E_Custom: 97
0065_Custom: ByteArray [value=06 00 28 0B 1E 2A 0D 1E 2C 11 1E 2E 06 00 30 0C 00 2E 0E 1E 2C 11 1E 2A 06 00 26 0C 1E 28 0E 1E 2A 12 1E 28]
0067_Custom: 300
0068_Custom: 100
0069_Custom: -2
006A_Custom: false
006B_Custom: 20
006C_Custom: 45
006D_Custom: 5
0004_Groups
0000_NameSupport: 0
0005_Scenes
0000_SceneCount: 0
0001_CurrentScene: 0
0002_CurrentGroup: 0
0003_SceneValid: false
0004_NameSupport: 0
Output
0019_OtaUpgrade
0000_UpgradeServerID: FFFFFFFFFFFFFFFF
0001_FileOffset: -1
0006_ImageUpgradeStatus: 0
000A_Time


Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags	0
Frequency Bands	[FREQ_2400_MHZ]
Server Capabilities	[]
Buffer Size	82
Incoming Transfer Size	82
Logical Type	End Device
Mac Capabilities	[REDUCED_FUNCTION_DEVICE]
Manufacturer Code	4098
Out Going Transfer Size	82
Stack Compliance	22

Power Descriptor
Current Power Mode	RECEIVER_ON_IDLE
Available Power Sources	[MAINS]
Current Power Source	MAINS
Power Level	FULL



Last update: Sat Aug 28 17:21:20 MSK 2021
