### ISSUE TITLE
Шторы и окна

### ISSUE THREAD

**Issue by mazaxaka** [sprut/Hub#3]
Постоянные значения для устройства: 
* MotionTime = Время за которая устройство перемещается из одного кранего положения в другое (полностью открыта -> полностью закрыта / полностью закрыта -> полностью открыта)
* Boost Time = Время, которое проходит между подачей питания на штору и началом движения. 

Переменные:
* CurrentPosition - Текущее положение в процентах, где 0 - полностью закрыто
* TargetPosition - Целевое положение в процентах, где 0 - полностью закрыто

Возможные состояния:
* Остановлена
* Полностью открыта
* Полностью закрыта
* Частично открыта
* Движется вверх
* Движется вниз

Важные моменты:
* В каждый момент времени нужно понимать, в каком состоянии находится устройство. 
Это можно сделать за счет изменения переменной CurrentPosition при каждом шаге изменения шторы с каким-то периодом.
В таком случае, если штора движется в какое-то целевое состояние, при поступлении новой команды мы можем рассчитать новые данные от текущего положения.
* При движении шторы в крайние положения нужно подавать питание на устройство MotionTime+BoostTime
Но при этом не забывать про то, что мы всегда должны иметь информацию обо актуальном состоянии устройства и уведомлять о том, что оно достигло конечного положения в тот момент, когда оно должно было достигнуть конечного положения, а не в тот момент, когда на него перестанет подаваться питание.

**Comment by sprut666666** [comment]
Всё должно работать, можно проверять
