### ISSUE TITLE
z-wave.me ZMR_FMBL (управление жалюзи)

### ISSUE THREAD

**Issue by khvilon** [sprut/Hub#300]
Для добавления поддержки нового устройства в хаб, необходимо:

1) Спарить устройство с хабом, и убедиться, что оно не поддерживается хабом. Устройство должно появиться на вкладке контроллеров, но не появиться в списке аксессуаров. Модель устройства должна определиться как "Unknown".
2) Найти в интернете или на корпусе/упаковке/инструкции название модели и производителя, и указать их в сообщении.
**z-wave.me ZMR_FMBL**
3) Указать ссылку на сайт производителя с описанием устройства, и pdf файл с описанием настроек и другой информации, если есть.
**https://rus.z-wave.me/shop/jalousie/z-waveme-flush-mountable-blind/**
4) В хабе, напротив устройства нажать на кнопку "i", появится подробная информация об устройстве. Ее нужно скопировать (с помощью кнопки в верхнем правом углу) и вставить в сообщение.
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>9</td></tr><tr><td width=35%>Manufacturer Id</td><td>0115</td></tr><tr><td width=35%>Device Type</td><td>1000</td></tr><tr><td width=35%>Device Id</td><td>0003</td></tr><tr><td width=35%>App Version</td><td>1.6</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Class C Motor</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td></td><td>[]</td><td>8</td></tr><tr><td>2</td><td></td><td>[]</td><td>8</td></tr><tr><td>3</td><td></td><td>[]</td><td>8</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 MultiChannelAssociation</li><li>V1 SwitchAll</li><li>V1 Basic</li><li>V3 SwitchMultiLevel<ul><li>Primary Type: CLOSE_OPEN</li><li>Secondary Type: UNDEFINED</li></ul></li><li>V1 Protection</li><li>V1 NoOperation</li><li>V1 ManufacturerSpecific</li><li>V1 NodeNaming</li><li>V1 SwitchBinary</li><li>V1 Version</li><li>V2 Association</li><li>V1 Configuration</li><li>V1 Indicator</li></ul></li></ul><br>Last update: Tue Oct 20 21:38:58 MSK 2020

Если на вкладке информации напротив Manufacturer Id/Device Type/Device Id стоит значение "7FFFFFFF" то необходимо вначале переспарить устройство.

В названии issue указать название производителя и модели.

**Comment by Batyushin** [comment]
Необходимо правильно заполнить:

- указываете свой ник в телеграме для быстрой связи с вами
- указываете ссылку, по которой покупался девайс
- указываете ссылку в каталоге если такое устройство там уже есть.
- Статус после восстановления питания (если устройство релейного типа или лампочка).

**Comment by khvilon** [comment]
@khvilonПокупалось много лет назад, где - не найти.20:11, 30 декабря 2020 г., ReD <notifications@github.com>:
Необходимо правильно заполнить:

указываете свой ник в телеграме для быстрой связи с вами
указываете ссылку, по которой покупался девайс
указываете ссылку в каталоге если такое устройство там уже есть.
Статус после восстановления питания (если устройство релейного типа или лампочка).


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by MakeSimpleOrg** [comment]
r4166
