### ISSUE TITLE
Remotec ZRC-90EU (контроллер сцен)

### ISSUE THREAD

**Issue by khvilon** [sprut/Hub#302]
Для добавления поддержки нового устройства в хаб, необходимо:

1) Спарить устройство с хабом, и убедиться, что оно не поддерживается хабом. Устройство должно появиться на вкладке контроллеров, но не появиться в списке аксессуаров. Модель устройства должна определиться как "Unknown".
2) Найти в интернете или на корпусе/упаковке/инструкции название модели и производителя, и указать их в сообщении.
**Remotec ZRC-90EU**
3) Указать ссылку на сайт производителя с описанием устройства, и pdf файл с описанием настроек и другой информации, если есть.
**https://www.remotec.com.hk/zrc90**
4) В хабе, напротив устройства нажать на кнопку "i", появится подробная информация об устройстве. Ее нужно скопировать (с помощью кнопки в верхнем правом углу) и вставить в сообщение.
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>10</td></tr><tr><td width=35%>Manufacturer Id</td><td>5254</td></tr><tr><td width=35%>Device Type</td><td>0001</td></tr><tr><td width=35%>Device Id</td><td>8510</td></tr><tr><td width=35%>App Version</td><td>1.1</td></tr><tr><td width=35%>Basic Class</td><td>Controller</td></tr><tr><td width=35%>Generic Class</td><td>Generic Controller</td></tr><tr><td width=35%>Specific Class</td><td>Remote Control Simple</td></tr><tr><td width=35%>Routing</td><td>false</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td></td><td>[]</td><td>?</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 WakeUp</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 AssociationGRPInfo</li><li>V1 DeviceResetLocally</li><li>V1 Battery<ul><li>Level: 0</li><li>Low: true</li></ul></li><li>V1 Basic</li><li>V1 ZWavePlusInfo</li><li>V1 ControllerReplication</li><li>V1 NoOperation</li><li>V2 ManufacturerSpecific</li><li>V2 Association</li><li>V2 Version</li><li>V2 CentralScene</li></ul></li></ul><br>Last update: Tue Oct 20 22:04:44 MSK 2020

Если на вкладке информации напротив Manufacturer Id/Device Type/Device Id стоит значение "7FFFFFFF" то необходимо вначале переспарить устройство.

В названии issue указать название производителя и модели.

**Comment by MakeSimpleOrg** [comment]
Проверить в 1.6.7

**Comment by Batyushin** [comment]
Необходимо правильно заполнить:

- указываете свой ник в телеграме для быстрой связи с вами
- указываете ссылку, по которой покупался девайс
- указываете ссылку в каталоге если такое устройство там уже есть.
- Статус после восстановления питания (если устройство релейного типа или лампочка).

**Comment by khvilon** [comment]
@khvilonhttps://z-neco.com/catalog/nastennye_kontrollery/z_wave_plus_remotec_kontroller_stsen_zrc_90/20:11, 30 декабря 2020 г., ReD <notifications@github.com>:
Необходимо правильно заполнить:

указываете свой ник в телеграме для быстрой связи с вами
указываете ссылку, по которой покупался девайс
указываете ссылку в каталоге если такое устройство там уже есть.
Статус после восстановления питания (если устройство релейного типа или лампочка).


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
