### ISSUE TITLE
Мультисэнсор Fibaro FGMS-001 (2.6)

### ISSUE THREAD

**Issue by dimis75** [sprut/Hub#306]
Motion Sensor  Fibaro FGMS-001 версия 2.6, 
Подключен через Sprut.stick Z-Wave 
к контроллеру WirenBoard 6.7, 
Версия SprutHub 1.6.5b

**Не изменятся статус датчика движения , соответственно не срабатывают триггеры. 
При этом на датчике присутствует индикация движения.**

<b>Fibargroup - FGMS-001</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>6</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0800</td></tr><tr><td width=35%>Device Id</td><td>1001</td></tr><tr><td width=35%>App Version</td><td>2.6</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Sensor Binary</td></tr><tr><td width=35%>Specific Class</td><td>Routing Sensor Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td></td><td>[]</td></tr><tr><td>2</td><td></td><td>[]</td></tr><tr><td>3</td><td></td><td>[1]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V5 SensorMultiLevel<ul><li>Luminance: 394</li><li>Temperature: 23.9</li></ul></li><li>V1 CRC16Encap</li><li>V1 NoOperation</li><li>V1 Battery<ul><li>Level: 100</li><li>Low: false</li></ul></li><li>V1 WakeUp</li><li>V1 SensorBinary<ul></ul></li><li>V1 ManufacturerSpecific</li><li>V2 MultiChannelAssociation</li><li>V2 Association</li><li>V1 Configuration</li><li>V1 MultiCommand</li><li>V1 Basic<ul><li>Value: 0</li></ul></li><li>V1 SensorAlarm<ul><li>General: 255</li></ul></li><li>V2 Version</li></ul></li></ul><br>Last update: Fri Oct 23 12:07:10 MSK 2020

Фрагмент лога :
14:57:18 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:57:15 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:56:45 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:55:49 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:55:18 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:55:17 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:54:46 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:51:04 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:50:34 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:49:03 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:48:25 | Event [6/0, class=SensorMultiLevel, type=Luminance, scale=1, value=55] |  
14:48:19 | Event [6/0, class=SensorAlarm, type=General, value=255] |  
14:47:36 | Event [6/0, class=SensorAlarm, type=General, value=255] |  
14:47:31 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:46:56 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:45:57 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:41:34 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:41:03 | Event [6/0, class=SensorBinary, type=Unknown, value=255] |  
14:40:19 | Event [6/0, class=SensorBinary, type=Unknown, value=0] |  
14:38:58 | Event [6/0, class=SensorAlarm, type=General, value=255] |  
14:38:11 | Event [6/0, class=SensorAlarm, type=General, value=255] |  
14:37:45 | Event [6/0, class=SensorBinary, type=Unknown, value=255]

**Comment by MakeSimpleOrg** [comment]
Попробуй обновиться, глаз должен работать
