### ISSUE TITLE
Шаблоны: Некорректное определение значений характеристик нескольких сервисов одного типа

### ISSUE THREAD

**Issue by ranold** [sprut/Hub#3069]
**Подробное описание ошибки**
В кастомных шаблонах происходит дублирование значения характеристики сервиса, если в рамках одного шаблона определяется несколько сервисов с одним типом на базе одного значения топика MQTT/адреса Modbus/атрибута Zigbee и использовании inFunc.

**Как воспроизвести?**
Пример на базе MQTT-шаблона: 
```
...
    {
      "type": "C_VoltMeter",
      "name": "Напряжение L1",
      "endpoint": 2,
      "characteristics": [
        {
          "type": "C_Volt",
          "link": {
            "type": "Double",
            "topicGet": "zigbee2mqtt/sensor/(1)",
            "inFunc": "JSON.parse(value).voltage_a"
          }
        }
      ]
    },
    {
      "type": "C_VoltMeter",
      "name": "Напряжение L2",
      "endpoint": 3,
      "characteristics": [
        {
          "type": "C_Volt",
          "link": {
            "type": "Double",
            "topicGet": "zigbee2mqtt/sensor/(1)",
            "inFunc": "JSON.parse(value).voltage_b"
          }
        }
      ]
    }
...
```

В результате в обоих сервисах окажутся одинаковые значения.

**Ожидаемое поведение**
Каждый из сервисов содержит свои собственные значения, полученные в результате соответствующего выполнения inFunc.

**Скриншоты/ Логи**
Одинаковые значения в разных сервисах одного типа
<img width="300" alt="CleanShot 2024-02-17 at 5 20 57@2x" src="https://github.com/sprut/Hub/assets/15378732/894f32da-b6ce-4620-9d3c-30ad23b63773">

Выдержка из логов:
```
17:32:07
Controllers.MQTT.MQTT_1
<-- zigbee2mqtt/sensor/energy, retained: false, msg: '{"ac_frequency":50,"current":1.7,"current_a":0.822,"current_b":0.454,"current_c":0.375,"device_status":0,"energy":129.28,"energy_a":86.699,"energy_b":7.464,"energy_c":35.123,"linkquality":150,"power":180,"power_a":107,"power_b":35,"power_c":39,"power_factor_a":56,"power_factor_b":32,"power_factor_c":45,"temperature":34.7,"voltage_a":229.1,"voltage_b":227.9,"voltage_c":230}'
```

**Пожалуйста, заполните следующую информацию**
Версия: 1.9.10 (11650) 
Ветка: release
Ник в тг: @dmitry_antonov

**Дополнительные материалы**
Шаблон, с которым воспроизводится поведение:
[TS0601_TZE200_nslr42tt.json](https://github.com/sprut/Hub/files/14319150/TS0601_TZE200_nslr42tt.json)

С подобной проблемой сталкиваются и другие пользователи:
https://t.me/c/1756326800/40781/113552
https://t.me/c/1756326800/39599/209580

**Comment by sprut666666** [comment]
начиная со сборки 11719 будет работать
