### ISSUE TITLE
Домофон ПИК

### ISSUE THREAD

**Issue by aptem334** [sprut/Hub#3082]
** Максимально подробное описание предложения.**
Четкое и краткое описание предложения, так чтобы вас смог понять "глупый" человек.

Прошу добавить  интеграцию с домофоном ПИК.

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

такая интеграция есть для HA https://github.com/alryaz/hass-pik-intercom/tree/main/custom_components/pik_intercom

**Comment by sprut666666** [comment]
вынесено на голосование
