### ISSUE TITLE
Модуль ввода-вывода WBIO-AO-10V-8 (Wiren Board)

### ISSUE THREAD

**Issue by B0Bka83** [sprut/Hub#309]
** Подробное описание ошибки **
Некорректное изменение напряжение 0-10V через SH 

** Как воспроизвести ? **
подключил Модуль ввода-вывода WBIO-AO-10V-8 к BW и SH 
в аксессуарах он отображается как Лампочка. 
при движении ползунка значения меняются от 0 до 100. 
В WB эти значения указываются как 0-10000 т.к. у них значения в милливольтах. 
В доп. параметрах SH в дополнительных параметрах есть пункт "MaxBrightness" в котором стоит значение 10000

** Ожидаемое поведение **
При значении ползунка 0 в SH отображается 0 в WB
При значении ползунка 100  в SH отображается 100 в WB (а нужно 10000)

** Скриншоты/ Логи **
![image](https://user-images.githubusercontent.com/72896470/97089248-36054d80-163f-11eb-8541-9efd1d0916f0.png)
![image](https://user-images.githubusercontent.com/72896470/97089231-1c640600-163f-11eb-9890-4968d4740cfb.png)
![image](https://user-images.githubusercontent.com/72896470/97089238-284fc800-163f-11eb-8122-850a3bd9abf5.png)

** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, IOS]

** Дополнительные материалы **

**Comment by Sanderworlds** [comment]
Столкнулся с такой же проблемой

**Comment by Rainstation** [comment]
Аналогичная ситуация. Нет возможности управлять в таком случае.

**Comment by B0Bka83** [comment]
Реально встал вопрос критично. 
Не могу менять уровень освещения на магнитных треках. А они почти в каждом проекте присутствуют.

**Comment by Rainstation** [comment]
Мне требовалось управление через homekit, решил вопрос через node-red.
Но, конечно, нативно через SH несравненно лучше.
