### ISSUE TITLE
Некорректно работает датчик температуры через Deconz (conbee2)

### ISSUE THREAD

**Issue by Oleg-Rent4all** [sprut/Hub#31]
При добавлении в SprutHub датчика температуры/влажности/давления от Aqara (lumi.weather)  через Deconz (conbee2) , он добавляется, но значений не получает. Также он должен отдавать 4 параметра (температура, давление, влажность, батарейка), а отдает 3 (давление не отдает).

При этом сами данные не отдает (см. скриншот)

** Как воспроизвести ? **
Подключить датчик в Spruthub через USB  стик Conbee2
![1](https://user-images.githubusercontent.com/52973099/63927872-3ca62e00-ca57-11e9-9b48-d5b9f47995ea.jpg)

**Comment by sprut666666** [comment]
Исправлено в 1.3.6
