### ISSUE TITLE
SmartWeb -Добавить поддержку автоматики для управления котельной, отоплением и тд.

### ISSUE THREAD

**Issue by uroopek** [sprut/Hub#311]
Очень частый вопрос по котельной, отоплению, теплые полы, котлы и тд - в общем список можно перечислять бесконечно. 
Предлагаю добавить поддержку [SmartWeb](http://gidrologo.ru/каталог/автоматика/управление/smartweb/smartweb_k) - он покрывает абсолютно все возможные сценарии  автоматизации которые только можно придумать, у самого такой стоит, есть поддержка и [интеграция](http://gidrologo.ru/каталог/автоматика/управление/smartweb/wirenboard_6) с WirenBoard 

Нужно только добавить поддержку. Работает по принципу обмена данными SmartWeb <=> WirenBoard, конкретно в моем случае покомнатное управление отоплением. Забирает данные с датчиков WB  и передает на SmartWeb - этот в свое очередь по своей автоматике управляет каскадом котлов, сервопрводов, датчиками температуры в полу и тд.  - и подогревает каждую комнату. С WB передаем уставку и нужную температуру по каждой комнате на SmartWeb.

Тк по сути все уже есть и интегрировано с WB - добавка поддержки закроет все вопросы связанные с котельной. Есть доступные версии SmartWeb по низкой цене, и можно закрыть почти все вопросы по отоплению.

Спасибо. 
PS такая система стоит у меня, готов посодействовать с тестированием.

**Comment by Bigmanekb** [comment]
На [официальном сайте SmartWeb](https://gidrologo.ru/каталог/автоматика/управление/smartweb/wirenboard_6#интеграция_в_spruthub) есть шаблон для интеграции в СХ
