### ISSUE TITLE
Ошибка в шаблоне aqara smart socket T1(lumi.plug.macn01)

### ISSUE THREAD

**Issue by pmitry** [sprut/Hub#3123]
Если зайти в параметры устройства и включить переключатель - блокировка от детей, то кнопки на розетке физически нажимаются, и наоборот, если выключить переключатель - блокировка от детей, то кнопки блокируются и не реагируют на физические нажатия. Хотелось бы поправить этот момент в шаблоне.

**Comment by Batyushin** [comment]
проверить после следующего обновления хаба, после чего отписать

**Comment by Batyushin** [comment]
если возникнуть проблемы отписать в чате поддержки. можно тегнуть @red_ik
