### ISSUE TITLE
Добавить поддержку модуля расширения Wirenboard WBE2-AO-10V-2

### ISSUE THREAD

**Issue by azazel87** [sprut/Hub#313]
[Вики Wirenboard ](https://wirenboard.com/wiki/Wiren_Board_6:_%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F_DAC_(WBE2-AO-10V-2))

**Comment by Bigmanekb** [comment]
оно снято с поддержки
