### ISSUE TITLE
Добавить поддержку модуля WB-MAO4

### ISSUE THREAD

**Issue by uroopek** [sprut/Hub#314]
Добрый день, добавьте поддержку модуля аналогового вывода 0-10В: [WB-MAO4](https://wirenboard.com/wiki/index.php/WB-MAO4_Modbus_Dimmer)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/wirenboard-modul-analogovogo-vyvoda-0-10v-wb-mao4

**Comment by sprut666666** [comment]
Добавить куда modbus/mqtt ? ник в телеграм ?

**Comment by uroopek** [comment]
в Спутхаб, когда писал не было поддержки, там шаблоне вроде была ошибка вместо MAO4 стояло MA04 ноль или наоборот, не знаю сохранилась ли сейчас эта проблема, я вручную новый шаблон тогда прописал и забыл.
