### ISSUE TITLE
Проблема с уровнем яркости белого на RGB/WW Zigbee лампах 

### ISSUE THREAD

**Issue by OXOTH1K** [sprut/Hub#317]
** Подробное описание ошибки **
При переключении лампы на режим RGB и потом обратно на белый холодный/теплый - уровень яркости падает в два-три раза, и изменение уровня яркости при этом уже не помогает.

** Скриншоты/ Логи **
Слева спрутхаб, справа ХА
![photo_2020-10-31_22-47-34](https://user-images.githubusercontent.com/19778219/97787379-2bacfb80-1bcb-11eb-825d-b6ebb9a6ebef.jpg)

**Comment by sprut666666** [comment]
1.6.6
