### ISSUE TITLE
Нептун OKE-20 не работает

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#318]
** Подробное описание ошибки **
Терморегулятор ОКЕ-20 не управляется через SH
** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Установить Spruthub 1.6.5
2. Создать контроллер Нептун 
3. Пройти авторизацию на серверах SST Cloud
4. Получить устройства OKE-20 
5. Включить виртуальную логику Термостата
6. попробовать поуправлять устройствами из Веб интерфейса или Apple Homekit 

** Ожидаемое поведение **
Полное управление термостатом через SH 

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия SH: 1.6.5 обновление от 1 ноября 14:00 мск

**Comment by sprut666666** [comment]
Включить виртуальную логику Термостата - это с какой целью ?

**Comment by Ziracul** [comment]
> Включить виртуальную логику Термостата - это с какой целью ?

Понял она не нужна в данном случае.
