### ISSUE TITLE
IRControl-EM

### ISSUE THREAD

**Issue by KZuev** [sprut/Hub#319]
Address: 000D6F001534F474/E948<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 20</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 16</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: IRControl-EM</li><li>0006_DateCode: 2018.10.19</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 31</li><li>0021_BatteryPercentageRemaining: 200</li><li>0034_BatteryRatedVoltage: 30</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 20</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4619</li><li>0008_ImageTypeId: 8483</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Nov 04 14:53:34 MSK 2020

Хаба нет
Telegram: [kirillzuev](https://t.me/kirillzuev)
Каталог Sprut.AI: [ИК-передатчик Heiman](https://v2.sprut.ai/catalog/item/heiman-ik-peredatcik)
Покупал тут: [JHome](https://jhome.ru/catalog/trasceivers/235/)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-ik-peredatcik

**Comment by MiSolkin** [comment]
Address: 000D6F001534E621/9AEE<br><br><b>Structure</b><br><ul><li>Endpoint 1 (REMOTE_CONTROL)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 2</li><li>0001_ApplicationVersion: 20</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 16</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: IRControl-EM</li><li>0006_DateCode: 2018.10.19</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 31</li><li>0021_BatteryPercentageRemaining: 200</li><li>0034_BatteryRatedVoltage: 30</li></ul></li><li>FC82_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>011C_LastMessageLQI: 255</li><li>011D_LastMessageRSSI: -32</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: -1</li><li>0003_CurrentZigBeeStackVersion: 65535</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4619</li><li>0008_ImageTypeID: 8483</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Feb 05 11:47:56 MSK 2022 
--
Хаба нет
Telegram: [misolkin](https://t.me/misolkin)
Каталог Sprut.AI: [ИК-передатчик Heiman](https://v2.sprut.ai/catalog/item/heiman-ik-peredatcik)
Покупал с рук

**Comment by Batyushin** [comment]
https://github.com/sprut/Hub/issues/3602 дубликат, старый запрос
