### ISSUE TITLE
SML001 в вебе SH не отображает изменённые настройки

### ISSUE THREAD

**Issue by pabl33** [sprut/Hub#320]
датчик движения Philips Hue.
если в вебе изменить настройки,к примеру период обнаружения и чувствительность к движению,нажать сохранить и далее перезагрузить сх-при повторном заходе в настройки датчика будут отображаться дефолтные параметры,хотя датчик продолжает работать согласно изменённым настройкам.

**Comment by sprut666666** [comment]
1.6.6
