### ISSUE TITLE
Универсальный датчик WB-MSW3 после обновления 1.6.5

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#323]
** Подробное описание ошибки **
В доме 8 датчиков WB-MSW3
После обновления SH до 165, какие-то устройства получили обновление темплейта и стали old? какие-то видимо нет.

По факту сейчас датчик движения (обнаружение движения) выглядит 
![image](https://user-images.githubusercontent.com/60096192/98432812-6fc46280-20db-11eb-90da-f12072eb0fb4.png)
![image](https://user-images.githubusercontent.com/60096192/98432836-a8fcd280-20db-11eb-94ec-797fab7939ff.png)
![image](https://user-images.githubusercontent.com/60096192/98432897-e19cac00-20db-11eb-984c-a9d696c45f17.png)

аналогичная ситуация и по другим датчикам в WB-MSW3

хотелось бы, что бы при обновлении системы, обновлялись все темлейты устройств.

** Пожалуйста, заполните следующую информацию: **
  - 1.6.5 
  - 14

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
Всё работает верно, проверяем все места где применялся олд заменяем на новое устройство и удаляем старое.
