### ISSUE TITLE
Перестал работать cетевой фильтр ZigBee с 2 USB и 4 вилками

### ISSUE THREAD

**Issue by DomikMaksa** [sprut/Hub#328]
Перестал работать сетевой фильтр при добавлении устройства пишет нет шаблона на карте устройств появляется формируются связи с соседними устройства в аксессуарах не появляется и не появляется в хомките и спрутхоме.
Ссылка на устройство в каталоге:
https://v2.sprut.ai/catalog/item/lellki-setevoj-filtr-zigbee-s-2-usb-i-4-vilkami
![Снимок экрана 2020-11-06 в 18 33 02](https://user-images.githubusercontent.com/48162267/98661905-23398b00-2358-11eb-8937-77d397d4c751.png)
![Снимок экрана 2020-11-06 в 18 33 24](https://user-images.githubusercontent.com/48162267/98661927-292f6c00-2358-11eb-9609-e3367f93d42b.png)
![Снимок экрана 2020-11-06 в 18 33 59](https://user-images.githubusercontent.com/48162267/98661947-2e8cb680-2358-11eb-83bd-e9118dd60d19.png)

**Comment by DomikMaksa** [comment]
![Снимок экрана 2020-11-10 в 13 28 59](https://user-images.githubusercontent.com/48162267/98662392-c094bf00-2358-11eb-85b8-9e47c3d0889f.png)

**Comment by sprut666666** [comment]
Это не мой темплейт, обновить хаб и показать что будет.

**Comment by DomikMaksa** [comment]
[logs.zip](https://github.com/sprut/Hub/files/5540978/logs.zip)

**Comment by InfinityMe** [comment]
Сегодня добавил такой же удлинитель, у меня работает.

**Comment by DomikMaksa** [comment]
Так и у меня добавился только при следующем сканировании создаются дубли в аксессуарах после этого в хомките уже не управляются вкладка контролеры нет имени нет производителя и опять же через какое-то время пишет нет шаблона хотя он есть ))))

**Comment by InfinityMe** [comment]
> Так и у меня добавился только при следующем сканировании создаются дубли в аксессуарах после этого в хомките уже не управляются вкладка контролеры нет имени нет производителя и опять же через какое-то время пишет нет шаблона хотя он есть ))))

У меня он тоже задвоился вроде, там стало штук 8-10 розеток вместо 4 или 5 (все розетки одновременно), Но это мои первые эксперименты поэтому я пока просто изучаю, главное в целом работет.

**Comment by DomikMaksa** [comment]
![Снимок экрана 2020-11-18 в 15 16 41](https://user-images.githubusercontent.com/48162267/99529604-231d3900-29b1-11eb-96a1-beee00c6e290.png)

**Comment by DomikMaksa** [comment]
Вот три одинаковых два из них скрыты ))))

**Comment by DomikMaksa** [comment]
Я пробовал удалять лишние не помогает ) проще скрыть

**Comment by DomikMaksa** [comment]
Добавьте свой лог может парни увидят что дает такое задвоение и вылечат сетивечек

**Comment by sprut666666** [comment]
1.6.6
