### ISSUE TITLE
Неправильный уровень заряда батареи Aqara WSDCGQ11LM  после замены

### ISSUE THREAD

**Issue by dmertsalov** [sprut/Hub#329]
** Подробное описание ошибки **
Не показывается корректный уровень заряда батарейки у Aqara WSDCGQ11LM после замены батарейки

** Как воспроизвести ? **
Посмотреть в аксессуарах инфу по датчику, развернув строку "Батарея"
Удаление аксессуара, перезагрузка и повторное добавление не помогают

** Ожидаемое поведение **
Уровень заряда больше 0 на новой качественной батарейке

** Скриншоты/ Логи **
<img width="1198" alt="Screen Shot 2020-11-10 at 10 02 27 PM" src="https://user-images.githubusercontent.com/17335832/98722703-6f112200-23a2-11eb-9a13-8e5e48a701e7.png">

<img width="429" alt="Screen Shot 2020-11-10 at 10 02 42 PM" src="https://user-images.githubusercontent.com/17335832/98722755-805a2e80-23a2-11eb-899f-8779249b6a14.png">

** Пожалуйста, заполните следующую информацию: **
  - hub 1.6.5b

**Comment by sprut666666** [comment]
Информацию об устройстве с вкладки контроллеры скрином

**Comment by dmertsalov** [comment]
<img width="626" alt="Screen Shot 2020-11-11 at 10 25 18 AM" src="https://user-images.githubusercontent.com/17335832/98781983-4885d200-2408-11eb-987e-2b00e5aee222.png">
<img width="622" alt="Screen Shot 2020-11-11 at 10 25 11 AM" src="https://user-images.githubusercontent.com/17335832/98781992-4b80c280-2408-11eb-8ee6-dfca4e2dbd16.png">

**Comment by dmertsalov** [comment]
Утром уровень заряда стал 100%. При этом несколько часов после смены батарейки не было изменений, хотя температура и влажность менялись. 
Если такой лаг это нормальная ситуация, то ишью можно закрывать.
