### ISSUE TITLE
Лампочка HUE не работает, как нужно. Проблемы с яркостью.

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#330]
** Подробное описание ошибки **
У меня создан виртуальный девайс-лампочка. Прилинковал к ней три лампочки Hue. Все работает , как надо. 
Кроме одного момента, создаю сценарий на яркость и при нажатии или в автоматизации , как видно на видео происходит следующее: выставляет заданную яркость, но затем возвращает последнее состояние у лампы. Т.е если лампа была выключена с например 70% яркости, то в следующий раз, если я захочу начать автоматизацию с 10% в хоум ките, то он сначала действительно начнет с 10% , но затем переключит на 70%.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1) Создать виртуальный девайс-лампочка
2) Прилинковать к нему несколько лампочек Hue (https://v2.sprut.ai/catalog/item/philips-hue-white-filament-bulb-a60-e27-bluetooth) Вроде бы вот эта лампочка (Та, что у Олега есть, я присылал ее)
3) Попробовать создать автоматизацию в хоумките или же забиндить в хк на одиночное нажатие включение яркости на определенный процент.
Сначала выключить лампочку с любой яркостью , пусть будет 50%.
Затем создать автоматизацию в ХК, включение на яркость 10%.
Увидеть, как лампочка включается сначала на 10% , а затем на 50%.

** Ожидаемое поведение **

Хотелось бы, чтобы лампочка работала , как нужно.

** Скриншоты/ Логи **
https://drive.google.com/drive/folders/1_eLiuxXlOAiwMR8Y_Aieja5zFuUQUJUi?usp=sharing
Закинул все скринны и видео сюда.

** Пожалуйста, заполните следующую информацию: **
IOS 14.2

** Дополнительные материалы **Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
1.6.6
