### ISSUE TITLE
Лампочки икеа не выключаются через ползунок яркости

### ISSUE THREAD

**Issue by sponchbob** [sprut/Hub#333]
** Подробное описание ошибки **
Лампочки икеа вподключены в сх. в приложении дом сгруппированы в группу. При уменьшении яркости ползунком в приложении "дом" до состояния выкл. лампочки продолжают гореть на минимальной яркости. 

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
Открыть приложение дом, уменьшить яркость у лампочек. 

** Ожидаемое поведение **
Лампочки не должны гореть.

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.6.5b iOS 14

**Comment by sprut666666** [comment]
1.6.6
