### ISSUE TITLE
LCT024

### ISSUE THREAD

**Issue by InfinityMe** [sprut/Hub#334]
Address: 00178801068657AA/D4B2<br><br><b>Structure</b><br><ul><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: LCT024</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 1.30.4_r23032</li></ul></li><li>0300_ColorControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>71</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>45</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>45</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY, MAINS, DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Nov 17 19:58:19 MSK 2020

Логи:

21:03:18 | 00178801068657AA/D4B2 : Firmware update - NO_IMAGE_AVAILABLE |  
-- | -- | --
21:03:17 | 001788010686749D/423F : Firmware update - NO_IMAGE_AVAILABLE |  
21:02:45 | 0017880106867345/C814 : Firmware update - NO_IMAGE_AVAILABLE |  
20:59:19 | Route Problem: EzspIncomingRouteErrorHandler [networkId=0, status=EMBER_MANY_TO_ONE_ROUTE_FAILURE, target=F79A] |  
20:59:19 | EzspDeprecatedChangeSourceRouteHandler [] |  
20:57:44 | EzspDeprecatedChangeSourceRouteHandler [] |  
20:57:42 | 0017880106867345/C814 : Настройка, 4003_StartUpOnOff = 255 - UNSUPPORTED_ATTRIBUTE |  
20:57:41 | 001788010686749D/423F : Настройка, 4003_StartUpOnOff = 255 - UNSUPPORTED_ATTRIBUTE |  
20:57:41 | ZigBee поиск завершён |  
20:57:41 | publish: 3.10.12/On/false to 1 clients |  
20:57:41 | 00178801068657AA/D4B2 : Настройка, 4003_StartUpOnOff = 255 - UNSUPPORTED_ATTRIBUTE |  
20:57:40 | 0017880106867345/C814: Запущен опрос устройства |  
20:57:40 | 00178801068657AA/D4B2: Запущен опрос устройства |  
20:57:40 | 001788010686749D/423F: Запущен опрос устройства |  
20:57:31 | ZigBee поиск запущен на 60 секунд

https://www.ozon.ru/product/panel-osveshcheniya-philips-hue-play-2-sht-180434099/
https://v2.sprut.ai/catalog/item/philips-hue-play-2
https://v2.sprut.ai/catalog/item/philips-play-light-bar

@AntonInfi
[logs.zip](https://github.com/sprut/Hub/files/5555333/logs.zip)

**Comment by InfinityMe** [comment]
Спасибо, после обновления прошивки всё заработало



11:04:29 | publish: 12.10.12/On/true to 1 clients |  
-- | -- | --
11:04:25 | publish: 12.10.12/On/false to 1 clients |  
11:04:22 | publish: 13.10.12/On/true to 1 clients |  
11:04:17 | publish: 13.10.15/Saturation/100.0 to 2 clients |  
11:04:17 | publish: 13.10.14/Hue/52.0 to 2 clients |  
11:04:12 | publish: 13.10.14/Hue/30.0 to 1 clients |  
11:04:12 | publish: 13.10.15/Saturation/75.0 to 1 clients |  
11:04:11 | publish: 13.10.14/Hue/30.0 to 1 clients |  
11:04:11 | publish: 13.10.15/Saturation/72.0 to 1 clients |  
11:04:08 | publish: 13.10.14/Hue/337.0 to 1 clients |  
11:04:08 | publish: 13.10.15/Saturation/100.0 to 1 clients |  
11:04:08 | publish: 13.10.14/Hue/338.0 to 1 clients |  
11:04:08 | publish: 13.10.15/Saturation/100.0 to 1 clients |  
11:04:08 | publish: 13.10.14/Hue/345.0 to 1 clients |  
11:04:08 | publish: 13.10.15/Saturation/84.0 to 1 clients |  
11:04:07 | publish: 13.10.14/Hue/349.0 to 1 clients |  
11:04:07 | publish: 13.10.15/Saturation/79.0 to 1 clients |  
11:04:07 | publish: 13.10.14/Hue/6.0 to 1 clients |  
11:04:07 | publish: 13.10.15/Saturation/69.0 to 1 clients |  
11:04:00 | publish: 13.10.12/On/false to 1 clients |  
11:03:42 | publish: 13.10.15/Saturation/100.0 to 2 clients |  
11:03:42 | publish: 13.10.14/Hue/52.0 to 2 clients |  
11:03:39 | publish: 12.10.15/Saturation/100.0 to 2 clients |  
11:03:39 | publish: 12.10.14/Hue/52.0 to 2 clients |  
11:03:38 | publish: 13.10.14/Hue/255.0 to 1 clients |  
11:03:38 | publish: 13.10.15/Saturation/68.0 to 1 clients |  
11:03:35 | publish: 13.10.12/On/true to 1 clients |  
11:03:33 | publish: 12.10.14/Hue/255.0 to 1 clients |  
11:03:33 | publish: 12.10.15/Saturation/68.0 to 1 clients |  
11:03:31 | publish: 12.10.12/On/true to 1 clients |  
11:03:30 | publish: 11.10.15/Saturation/100.0 to 2 clients |  
11:03:30 | publish: 11.10.14/Hue/52.0 to 2 clients |  
11:03:26 | publish: 11.10.14/Hue/255.0 to 1 clients |  
11:03:26 | publish: 11.10.15/Saturation/68.0 to 1 clients |  
11:03:23 | publish: 11.10.12/On/true to 1 clients |  
11:03:20 | publish: 11.10.12/On/false to 1 clients |  
11:03:19 | publish: 12.10.12/On/false to 1 clients |  
11:03:19 | publish: 11.10.12/On/true to 1 clients |  
11:03:18 | publish: 13.10.15/Saturation/100.0 to 2 clients |  
11:03:18 | publish: 13.10.14/Hue/52.0 to 2 clients |  
11:03:18 | publish: 12.10.15/Saturation/100.0 to 2 clients |  
11:03:18 | publish: 12.10.14/Hue/52.0 to 2 clients |  
11:03:17 | publish: 11.10.12/On/false to 1 clients |  
11:02:23 | Created accessory: id=13, name=Лампочка, model=LCT024 |  
11:02:23 | 00178801068657AA/A4F2: Опрос пройден. Производитель: Philips, Модель: LCT024 |  
11:02:23 | 00178801068657AA/A4F2 : Настройка, 0004_CurrentY = 65535 |  
11:02:23 | 00178801068657AA/A4F2 : Настройка, 0003_CurrentX = 65535 |  
11:02:23 | 00178801068657AA/A4F2 : Настройка, 4010_StartUpColorTemperatureMireds = 65535 |  
11:02:22 | 00178801068657AA/A4F2 : Настройка, 4000_StartUpCurrentLevel = 255 |  
11:02:19 | Created accessory: id=12, name=Лампочка, model=LCT024 |  
11:02:19 | 001788010686749D/2729: Опрос пройден. Производитель: Philips, Модель: LCT024 |  
11:02:19 | 001788010686749D/2729 : Настройка, 0004_CurrentY = 65535 |  
11:02:19 | 001788010686749D/2729 : Настройка, 0003_CurrentX = 65535 |  
11:02:19 | 001788010686749D/2729 : Настройка, 4010_StartUpColorTemperatureMireds = 65535 |  
11:02:19 | 001788010686749D/2729 : Настройка, 4000_StartUpCurrentLevel = 255 |  
11:02:19 | 001788010686749D/2729 : Настройка, 4003_StartUpOnOff = 255 |  
11:02:19 | 001788010686749D/2729 : Firmware update - NO_IMAGE_AVAILABLE |  
11:02:19 | 001788010686749D/2729 : Таблица связей |  
11:02:19 | 001788010686749D/2729 : Очистка групп |  
11:02:18 | 001788010686749D/2729 : Актуализация прошивки |  
11:02:18 | Created accessory: id=11, name=Лампочка, model=LCT024 |  
11:02:18 | 0017880106867345/1466: Опрос пройден. Производитель: Philips, Модель: LCT024 |  
11:02:18 | 0017880106867345/1466 : Настройка, 0004_CurrentY = 65535 |  
11:02:18 | 0017880106867345/1466 : Настройка, 0003_CurrentX = 65535 |  
11:02:18 | 0017880106867345/1466 : Настройка, 4010_StartUpColorTemperatureMireds = 65535 |  
11:02:18 | 0017880106867345/1466 : Настройка, 4000_StartUpCurrentLevel = 255 |  
11:02:18 | 0017880106867345/1466 : Настройка, 4003_StartUpOnOff = 255 |  
11:02:18 | 0017880106867345/1466 : Таблица связей |  
11:02:18 | 0017880106867345/1466 : Firmware update - NO_IMAGE_AVAILABLE |  
11:02:17 | 0017880106867345/1466 : Очистка групп |  
11:02:17 | 001788010686749D/2729 : Информация о модели |  
11:02:17 | 00178801068657AA/A4F2 : Firmware update - NO_IMAGE_AVAILABLE |  
11:02:17 | 00178801068657AA/A4F2 : Настройка, 4003_StartUpOnOff = 255 |  
11:02:17 | 0017880106867345/1466 : Актуализация прошивки |  
11:02:17 | 001788010686749D/2729 : 2/2, Изучение конечной точки 242 |  
11:02:17 | 00178801068657AA/A4F2 : Таблица связей |  
11:02:17 | 001788010686749D/2729 : 2/1, Изучение конечной точки 11 |  
11:02:17 | 00178801068657AA/A4F2 : Очистка групп |  
11:02:17 | 001788010686749D/2729 : Изучение возможностей |  
11:02:17 | 001788010686749D/2729 : Энергопотребление |  
11:02:17 | EzspDeprecatedChangeSourceRouteHandler [] |  
11:02:16 | 00178801068657AA/A4F2 : Актуализация прошивки |  
11:02:16 | 0017880106867345/1466 : Информация о модели |  
11:02:16 | 0017880106867345/1466 : 2/2, Изучение конечной точки 242 |  
11:02:16 | 0017880106867345/1466 : 2/1, Изучение конечной точки 11 |  
11:02:16 | 0017880106867345/1466 : Изучение возможностей |  
11:02:16 | 0017880106867345/1466 : Энергопотребление |  
11:02:16 | 0017880106867345/1466 : Базовая информация |  
11:02:16 | 0017880106867345/1466: Запущен опрос устройства |  
11:02:15 | 00178801068657AA/A4F2 : Информация о модели |  
11:02:15 | 00178801068657AA/A4F2 : 2/2, Изучение конечной точки 242 |  
11:02:15 | 00178801068657AA/A4F2 : 2/1, Изучение конечной точки 11 |  
11:02:15 | EzspDeprecatedChangeSourceRouteHandler [] |  
11:02:15 | 00178801068657AA/A4F2 : Изучение возможностей |  
11:02:15 | 001788010686749D/2729 : Базовая информация |  
11:02:15 | 00178801068657AA/A4F2 : Энергопотребление |  
11:02:15 | 00178801068657AA/A4F2 : Базовая информация |  
11:02:14 | 001788010686749D/2729: Запущен опрос устройства |  
11:02:14 | 00178801068657AA/A4F2: Запущен опрос устройства |  
11:01:07 | 0017880106867345/1466 : Firmware update - DONE

**Comment by sprut666666** [comment]
1.6.6
