### ISSUE TITLE
Add a new template for WZ-M100-W sensor

### ISSUE THREAD

**Issue by Andreydr0id** [sprut/Hub#3358]
Add a new template for WZ-M100-W sensor

[TS0601_WZ-M100-W.json](https://github.com/user-attachments/files/16115554/TS0601_WZ-M100-W.json)
But lux sensor don,t work with this template . It is 5 lux always

  manufacturer  "wenzhi"
  model "WZ-M100-W"
  manufacturerId "_TZE204_laokfqwu"

**Comment by Batyushin** [comment]
необходимо ссылку на устройство.

**Comment by Andreydr0id** [comment]
Типо ссылку на товар на али?
https://sl.aliexpress.ru/p?key=ke2zsCR
