### ISSUE TITLE
lumi.switch.b2nacn02

### ISSUE THREAD

**Issue by upmkvik** [sprut/Hub#337]
Address: 00158D000544D85B/FEDC<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 61</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 18</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.b2nacn02</li><li>0007_PowerSource: 1</li><li>FF01_Custom: {3=37, 100=false, 101=true, 149=30.914512634277344, 5=13, 7=0, 152=35.06999969482422, 8=4157, 9=1280, 154=0}</li></ul></li><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 2278</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>F000_State: 67108608</li></ul></li><li>000A_Time<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0002_CurrentFileVersion: 61</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>F000_State: 67034112</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 35.06999969482422</li><li>006F_StatusFlags: 0</li><li>0100_ApplicationType: 589824</li></ul></li></ul></li><li>Output<ul><li>0004_Groups<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 4<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 30.811994552612305</li><li>006F_StatusFlags: 0</li><li>0100_ApplicationType: 720896</li></ul></li></ul></li><li>Output<ul><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 5<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 6<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 7<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Nov 20 19:48:33 MSK 2020
Телеграм: @Dr_V1
Девайс в каталоге: Нет! присутствует только [без нулевой линии](https://v2.sprut.ai/catalog/item/aqara-wall-switch-d1-zero-line-double-button)
Покупал [тут.](https://a.aliexpress.com/_A2KTJY)

**Comment by sprut666666** [comment]
в след обновлении
