### ISSUE TITLE
WB-MAP6S не добавляется в спрутхаб

### ISSUE THREAD

**Issue by gonczarov** [sprut/Hub#338]
** Подробное описание ошибки **
WB-MAP6S не добавляется в спрутхаб

** Как воспроизвести ? **
при поиске по модбас счетчик WB-MAP6S не добавляется
** Ожидаемое поведение **
хочется конечно чтобы этот счетчик заработал во всеми нами любимом спрутхабе =)

** Скриншоты/ Логи **
20:40:25 | Discovered ID = 41, model = MAP6SȀ |  
-- | -- | --
20:40:24 | Add ID = 38, manufacturer = WirenBoard, model = WB-MRWL3 |  
20:40:24 | Discovered ID = 38, model = MRWL3 |  
20:40:24 | Discovered ID = 37, model = MAP6SȀ** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, IOS]
спрутхаб версия 1.6.5b

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
1.6.6
