### ISSUE TITLE
Добавить поиск по типу сервиса, при создании виртуального устройства

### ISSUE THREAD

**Issue by VolchkovVlad** [sprut/Hub#3399]
** Максимально подробное описание предложения.**
Четкое и краткое описание предложения, так чтобы вас смог понять "глупый" человек.

В SH можно создавать виртуальные устройства. При создании виртуального устройства, вы добавляете в него сервисы.
И сейчас что бы выбрать нужный сервис, нужно открыть список и внимательно листать, что бы не пропустить желаемый сервис.

Предлагаю выпадающий список обьеденить с поисковой строкой, что бы я мог просто ввести "Датчик" и у меня отобразились все сервисы в названии которых используется слово "Датчик"

<img width="688" alt="Снимок экрана 2024-07-27 в 23 34 50" src="https://github.com/user-attachments/assets/0fb798a3-445c-4f97-8d24-584c16511e2e">

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

Пример подобной реализации из конфигуратора wb-mqtt-serial от Wiren Board
<img width="593" alt="Снимок экрана 2024-07-27 в 23 33 39" src="https://github.com/user-attachments/assets/d37db7fc-8e1b-41d6-a435-d469c9f0f816">

**Comment by Batyushin** [comment]
предлагаю запостить в с пометкой а чате поддержки #Предложение_на_развитие

**Comment by VolchkovVlad** [comment]
<img width="966" alt="Снимок экрана 2024-08-18 в 04 20 14" src="https://github.com/user-attachments/assets/184732a9-8bfb-4d39-aba2-88e809c23835">
