### ISSUE TITLE
При добавлении привода рулонных штор AQARA(Zigbee) в SH данный привод никак не отображается в приложении «Дом».

### ISSUE THREAD

**Issue by SkysystemX** [sprut/Hub#34]
При добавлении привода рулонных штор AQARA(Zigbee) в SH данный привод никак не отображается в приложении «Дом».

1. В web-интерфейсе Спрутхаб в строке устройств ZigBee нажимаем на значок лупы. Запускаем поиск новых устройств ZigBee.
2. На пульте привода рулонных штор нажимаем маленькую кнопочку на нижней грани пульта, диод светится синим цветом, потом красным(отпускаем как начал гореть красным). привод переводится в режим сопряжения.
3. Спрутхаб находит и идентифицирует устройство как “lumi.curtain.aq2” и оно отображается в интерфейсе Спрутхаба в разделе ZigBee-устройств.
4. Отображение в приложении «Дом» не происходит, никаких новых иконок не добавляется.

Ожидалось появление в приложении «Дом» иконки для данного устройства с возможностью управлением привода на открытие и закрытие.

![A13079FF-85F7-4298-9ABC-047E1AD4EAC8](https://user-images.githubusercontent.com/55890040/65786681-d993de00-e15f-11e9-836c-f0aa1f1bdd66.jpeg)
![0E663D14-313F-4D38-A2CE-73827B74EEBA](https://user-images.githubusercontent.com/55890040/65786682-da2c7480-e15f-11e9-828d-7129d8c342a8.jpeg)
![50B72286-6E29-4ECC-BC96-A33D37432048](https://user-images.githubusercontent.com/55890040/65786684-da2c7480-e15f-11e9-8ab6-c2163d989078.jpeg)
![007D7B43-B18F-4B54-8FBF-A85F80880BE5](https://user-images.githubusercontent.com/55890040/65786686-dac50b00-e15f-11e9-8627-67ce79c072c6.jpeg)

**Comment by diamond5170** [comment]
Добавил в 1.3.5
