### ISSUE TITLE
lumi.switch.n0agl1

### ISSUE THREAD

**Issue by kersuzio** [sprut/Hub#340]
Address: 04CF8CDF3C8B2FC4/FF2B<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 21</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.n0agl1</li><li>0006_DateCode: Aug  8 2020</li><li>0007_PowerSource: 0</li><li>0008_GenericDeviceClass: 255</li><li>4000_SwBuildId: </li></ul></li><li>FCC0_ManufacturerSpecific<ul></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 0</li><li>0300_UnitOfMeasure: 0</li><li>0301_Multiplier: 1</li><li>0302_Divisor: 1000</li><li>0303_SummationFormatting: 35</li><li>0306_MeteringDeviceType: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0B04_ElectricalMeasurement<ul><li>0000_MeasurementType: 8</li><li>050B_ActivePower: 0</li><li>0800_AcOverloadAlarmsMask: 4</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: 0000000000000000</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 255</li></ul></li><li>0009_Alarms<ul><li>0000_AlarmCount: 0</li></ul></li><li>000A_Time<ul><li>0000_Time: +##+##�����	�����</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0001_FileOffset: 0</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 21<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0.0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 41<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 31<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0.0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Nov 20 23:02:35 MSK 2020

Телеграм: [@kersuzio](tg://resolve?domain=kersuzio)
Покупал [тут](https://www.iv8.lv/preces/majas-automatizacija/86473).

**Comment by Batyushin** [comment]
Необходимо заполнить:
ссылка на каталог, если есть
ссылка на магазин - не работает

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/aqara-single-switch-module-t1

**Comment by kersuzio** [comment]
> Необходимо заполнить:
> 
> ссылка на каталог, если есть
> https://v2.sprut.ai/catalog/item/aqara-single-switch-module-t1

> ссылка на магазин - не работает 

https://www.iv8.lv/preces/majas-automatizacija/86473
