### ISSUE TITLE
Синхронизация видимости сервиса и его статуса.

### ISSUE THREAD

**Issue by VolchkovVlad** [sprut/Hub#3400]
** Максимально подробное описание предложения.**
Четкое и краткое описание предложения, так чтобы вас смог понять "глупый" человек.

Сейчас что бы полностью скрыть сервис из веб интерфейса, не необходимо не только скрыть сервис, но и выключить его отображение в строке "статуса". И так же если я хочу включить отображение сервиса, я должен еще и включить отображение его статуса.

Мое предложение:
Если пользователь выключает отображение (Видимость) сервиса, то и отображение статуса сервиса, отключается.
Если пользователь включает отображение (Видимость) сервиса, то и отображение статуса сервиса, включается.

Если пользователь скрывает видимость сервиса, то и его статус с большой вероятностью он видеть не хочет.

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.
<img width="903" alt="Снимок экрана 2024-07-27 в 23 37 18" src="https://github.com/user-attachments/assets/2b1d2d9a-4906-4f4e-9901-d35e3f727d1b">
<img width="693" alt="Снимок экрана 2024-07-27 в 23 37 13" src="https://github.com/user-attachments/assets/99dcfe96-92e4-4638-b0a7-20cb0aedbdc8">

**Comment by Batyushin** [comment]
в следующем релизной сборки будет полностью переработан интерфейс. Но конкретно этот функционал не появиться. поэтому предлагаю запостить в с пометкой а чате поддержки #Предложение_на_развитие
