### ISSUE TITLE
Отображается надпись "Пришло время обновить ваше устройство"

### ISSUE THREAD

**Issue by VolchkovVlad** [sprut/Hub#3409]
** Подробное описание ошибки **
Отображается надпись "Пришло время обновить ваше устройство"
![photo_2024-08-02 11 36 01](https://github.com/user-attachments/assets/5107ab6c-f51e-4a2c-b921-bd8a50941460)

** Как воспроизвести ? **
Открыть веб интерфейс.

** Ожидаемое поведение **
На контроллере установлена последняя версия ПО. Ветка релиз.
Ожидаю что данная надпись должна появиться только когда появится обновление в ветке release.
И что данную надпись можно будет закрыть

** Скриншоты/ Логи **
Версия SH 1.9.10 (11847) 
Ветка release

** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, IOS]

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by permadm** [comment]
Для релизной версии надо использовать адрес web.spruthub.ru
