### ISSUE TITLE
COSensor-N

### ISSUE THREAD

**Issue by ageladek** [sprut/Hub#343]
Address: 00158D000292EC95/F52A<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 18</li><li>0003_HwVersion: 16</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: COSensor-N</li><li>0007_PowerSource: 3</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 43</li><li>0002_ZoneStatus: 32</li><li>0010_IasCieAddress: 0000000000000000</li><li>0011_ZoneId: 255</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 60A423FFFE4155D3</li><li>0002_CurrentFileVersion: 18</li><li>0006_ImageUpgradeStatus: 0</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Nov 21 09:28:17 MSK 2020

Telegram: amif123

**Comment by Batyushin** [comment]
Необходимо дополнить
ссылка на каталог, если есть устройство 
ссылка на магазин где купить

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-datcik-okisi-ugleroda-co2
