### ISSUE TITLE
TRADFRI on/off switch

### ISSUE THREAD

**Issue by DjBalagur** [sprut/Hub#345]
Address: EC1BBDFFFEC44300/09FB<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 33</li><li>0002_StackVersion: 98</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI on/off switch</li><li>0006_DateCode: 20190723</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 2.2.010</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 172800</li><li>0001_LongPollInterval: 1160</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 27</li><li>0021_BatteryPercentageRemaining: 47</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0009_Alarms<ul></ul></li><li>FC7C_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0102_WindowCovering<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 570492465</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4476</li><li>0008_ImageTypeId: 4549</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Nov 21 06:46:51 MSK 2020
Telegram: somebody_else_123
Покупал здесь: https://www.ikea.lt/ru/products////tradfri-besprovodnoy-reostat-belyy-art-00468432

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ikea-tradfri-on-off-switch

**Comment by Batyushin** [comment]
Дубли:
https://github.com/sprut/Hub/issues/786
https://github.com/sprut/Hub/issues/1055
https://github.com/sprut/Hub/issues/1127
https://github.com/sprut/Hub/issues/1221

**Comment by Batyushin** [comment]
https://github.com/sprut/Hub/issues/1607 дубль
