### ISSUE TITLE
Classic A60 RGBW

### ISSUE THREAD

**Issue by oleg77s** [sprut/Hub#346]
Address: 8418260000DA7E2F/AD05<br><br><b>Structure</b><br><ul><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: OSRAM</li><li>0005_ModelIdentifier: Classic A60 RGBW</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: V1.05.10</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>000F_Options: 0</li><li>0010_OnOffTransitionTime: 0</li><li>0011_OnLevel: 255</li><li>0012_OnTransitionTime: 0</li><li>0013_OffTransitionTime: 0</li><li>0014_DefaultMoveRate: 255</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 60A423FFFE4174D9</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 16909584</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4364</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE4174D9</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>82</td><td>ENABLED</td><td>1</td></tr><tr><td>7CB03EAA00A054CE</td><td>75B4</td><td>Router</td><td>false</td><td>Sibling</td><td>120</td><td>ENABLED</td><td>1</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>64</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>0</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>48042</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>0</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY, MAINS, DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Nov 21 18:20:10 MSK 2020
Телеграм: OLEГ
Ссылка на устройство в каталоге: https://v2.sprut.ai/catalog/item/osram-classic-a60-rgbw или
https://v2.sprut.ai/catalog/item/osram-lightify-led-cla60-e27-rgbw

**Comment by Batyushin** [comment]
напиши мне в телеграм @red_ik, необходима информация по устройсву

**Comment by oleg77s** [comment]
статус после восстановления питания: всегда включено (100% яркость, 2700к), в родном приложении можно настроить это состояние на любую яркость/цвет/температуру; версия zigbee: ZLL; режим сброса: вкл/выкл 5 раз (2 сек вкл/5 сек выкл)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/osram-lightify-led-cla60-e27-rgbw

**Comment by oleg77s** [comment]
работает ОК

**Comment by oleg77s** [comment]
работает ОК
