### ISSUE TITLE
TRADFRI SHORTCUT Button

### ISSUE THREAD

**Issue by DjBalagur** [sprut/Hub#348]
Address: 680AE2FFFE2F39CC/E85D<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 33</li><li>0002_StackVersion: 98</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI SHORTCUT Button</li><li>0007_PowerSource: 3</li><li>0008_GenericDeviceClass: 0</li><li>4000_SwBuildId: 2.3.015</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 172800</li><li>0001_LongPollInterval: 1160</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 0</li><li>0021_BatteryPercentageRemaining: 100</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0009_Alarms<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0102_WindowCovering<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 587290161</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4476</li><li>0008_ImageTypeId: 4550</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Nov 22 00:09:22 MSK 2020
Telegram: somebody_else_123
Покупал здесь: https://www.ikea.lt/ru/products////tradfri-knopka-bystrogo-dostupa-belyy-art-40467765

**Comment by Batyushin** [comment]
Необходимо правильно заполнить.
ссылка на профиль в телеграм для связи.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ikea-tradfri-shortcut-button

**Comment by jonimant** [comment]
есть такая кнопка, ждем добавления спрутхаб
