### ISSUE TITLE
Задвоение устройства. ChiFun 517F

### ISSUE THREAD

**Issue by Anzic23** [sprut/Hub#35]
При текущем шаблоне в аксессуарах создаются дубли состояний. Добавляются так:
Added accessory: id=60, name=Выключатель, model=517F
Added accessory: id=59, name=Выключатель, model=517F_1
Added accessory: id=58, name=Выключатель, model=517F
Added accessory: id=57, name=Выключатель, model=517F_1
Added accessory: id=56, name=Выключатель, model=517F
Added accessory: id=55, name=Выключатель, model=517F_1
Сам шабон выглядит так:
```
{
  "name": "Выключатель",
  "manufacturer": "ChiFun",
  "model": "517F",
  "url": "https://ru.aliexpress.com/item/32806792768.html",
  "mask": "517F_.*",
  "services": [
    {
      "name": "Выключатель",
      "type": "Switch",
      "characteristics": [
        {
          "type": "On",
          "link": "Integer/!DO_.*!"
        }
      ]
    }
  ]
}
```
Топики:
![2019-10-22_16-35-32](https://user-images.githubusercontent.com/37106885/67291296-01216080-f4ea-11e9-9831-4ec03266d83c.png)

**Comment by sprut666666** [comment]
При текущих симптомах, не верю =) Пиши в чат нужны уточнения в реальном времени.
