### ISSUE TITLE
RC_V14

### ISSUE THREAD

**Issue by oleg77s** [sprut/Hub#351]
Address: 005043C90337690D/230A<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 3</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Heiman</li><li>0005_ModelIdentifier: RC_V14</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0009_Alarms<ul><li>0000_AlarmCount: 0</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0501_IasAce<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 16908544</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 21640</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>64</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>0</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE, MAINS_POWER]</td></tr><tr><td width=35%>Manufacturer Code</td><td>48042</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>0</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY, MAINS, DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Nov 22 11:46:27 MSK 2020

Telegram: OLEГ
Ссылка на устройство в каталоге: https://v2.sprut.ai/catalog/item/heiman-karmannyj-cetyrehklavisnyj-pult
Магазин: https://jhome.ru/catalog/switches-and-remotes/221/

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-karmannyj-cetyrehklavisnyj-pult
