### ISSUE TITLE
Розетка LifeControl щелкает (выключается/включается) самопроизвольно

### ISSUE THREAD

**Issue by aleksandrdobrynin** [sprut/Hub#352]
** Подробное описание ошибки **
На билде 3240 розетка LifeControl начала щёлкать. На 1.6.5 работало все отлично.

** Как воспроизвести ? **
Просто ждать и она сама щёлкнет в какой-то момент. Но происходит это у меня раз в 1-2 часа.

** Ожидаемое поведение **
Чтобы перестала самопроизвольно отключаться.

![image](https://user-images.githubusercontent.com/32413181/99899882-8b279400-2cbd-11eb-9bc6-24f4d7274129.png)

**Comment by sprut666666** [comment]
Ревизия > 3240
