### ISSUE TITLE
реле с сухим контактом

### ISSUE THREAD

**Issue by kmira78** [sprut/Hub#3532]
куплено тут :https://aliexpress.ru/item/1005006273804956.html?spm=a2g2w.orderdetail.0.0.34484aa6qS80FD&sku_id=12000036562489172

Address: A4C1388C63C754F2/DC85

Structure
Endpoint 1 (ON_OFF_SWITCH)
Input
E000_ManufacturerSpecific
D001_Custom: ByteArray [value=00 06] [ORDERED_SEQUENCE_ARRAY]
D002_Custom: ByteArray [value=00 0A] [ORDERED_SEQUENCE_ARRAY]
D003_Custom: AAAA [CHARACTER_STRING]
E001_ManufacturerSpecific
D000_TuyaUnknown: 0 [UNSIGNED_8_BIT_INTEGER]
D001_TuyaUnknown: 0 [BITMAP_32_BIT]
D002_TuyaUnknown: 0 [UNSIGNED_32_BIT_INTEGER]
D003_TuyaUnknown: 0 [UNSIGNED_32_BIT_INTEGER]
D004_TuyaUnknown: 0 [UNSIGNED_32_BIT_INTEGER]
D005_TuyaUnknown: 0 [UNSIGNED_32_BIT_INTEGER]
D030_ButtonType: 0 [ENUMERATION_8_BIT]
0006_OnOff
0000_OnOff: true [BOOLEAN]
4001_OnTime: 0 [UNSIGNED_16_BIT_INTEGER]
4002_OffWaitTime: 0 [UNSIGNED_16_BIT_INTEGER]
8002_RestartStatus: 1 [ENUMERATION_8_BIT]
Output
000A_Time

Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor

Power Descriptor

OTA info

Mode: ZCL
Last update: Thu Oct 10 18:02:47 MSK 2024

**Comment by Co1dSUN** [comment]
А зачем так сделано? Почему не создать нормальную заявку из хаба?
https://wiki.spruthub.ru/Моё_устройство_не_поддерживается._Нет_шаблона._Что_делать

**Comment by Batyushin** [comment]
оформите запрос из вкладки контроллера.
