### ISSUE TITLE
добавить для контроллера modbus разные регистры для чтения состояния и управления

### ISSUE THREAD

**Issue by bugor740** [sprut/Hub#3548]
> Разные регистры для чтения состояния и управления
> Иногда в сторонних устройствах встречаются особенности:
> 
> В некоторые регистры можно только писать информацию, но нельзя считывать.
> Один и тот же параметр может читаться по одному адресу, а записываться по другому.
> Для того, чтобы драйвер работал с такими устройствами без ошибок, мы добавили параметр write_address.

По аналогии  с WirenBoard предлагаю сделать [Описание](https://wirenboard.com/wiki/Connecting_Third_Party_Devices_to_Wiren_Board#%D0%A0%D0%B0%D0%B7%D0%BD%D1%8B%D0%B5_%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D1%8B_%D0%B4%D0%BB%D1%8F_%D1%87%D1%82%D0%B5%D0%BD%D0%B8%D1%8F_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_%D0%B8_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)

**Comment by Batyushin** [comment]
Подобные предложения принимаются в чате поддержки, ветка Флуд с пометкой #ПредложенияПоРазвитию

**Comment by bugor740** [comment]
Почему развитие, это баг. Нельзя добавить устройство у которого на запись и чтение разные регистры
