### ISSUE TITLE
Tuya temperature and Humidity Sensor

### ISSUE THREAD

**Issue by hromesss** [sprut/Hub#3563]
** Подробное описание ошибки **
Не обновляются данные с датчика Tuya temperature and Humidity Sensor

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Добавил новый датчик Tuya temperature and Humidity Sensor
2. После добавления, повторного опроса нет.

** Ожидаемое поведение **
Обновление датчика с определенной частотой.

** Скриншоты/ Логи **
![image](https://github.com/user-attachments/assets/ded87c2d-8a9e-4de4-9c4e-2c3570766fad)

** Пожалуйста, заполните следующую информацию: **
Sprut.hub 2 (1.9.10_11847/3897)
IMAQLIQ gbox-x3 (20240617_0235_spruthub2)
JDK: 1.8.0_402 (Zulu 8.76.0.17-CA-linux_aarch64)
Serial: 19AECD2751D6EF17
Time: 2024.10.22 17:36:40 (YEKT)
Uptime: 3066
Еxternal storage: true
wlan1: Клиент - Не активен, DHCP - Автоматически
wlan0: Клиент - Не активен, DHCP - Автоматически
end0: Клиент - Активно, DHCP - Автоматически
_______________________________

** Дополнительные материалы **
Приобретен по ссылке: https://aliexpress.ru/item/1005005109716475.html?spm=a2g2w.orderdetail.0.0.21084aa6yECQWe&sku_id=12000031694014594
![image](https://github.com/user-attachments/assets/28a90588-2f35-4c40-8eb6-7a44ac41a90f)

**Comment by Batyushin** [comment]
напишите в чат поддержки или можно мне в личку в телеграм @red_ik
