### ISSUE TITLE
Добавить диммер DMX512

### ISSUE THREAD

**Issue by Anzic23** [sprut/Hub#36]
У меня диммеры заведены через скрипт. отображаются как dimmer1 dimmer2 dimmer3 dimmer4.
После обновления тип "DimmableLightbulb" перестал поддерживаться. Попробовал создать по шаблону WB-MRGBW-D, но ничего не вышло. Прошу помочь с шаблоном.
![image](https://user-images.githubusercontent.com/37106885/67375083-c6bbd000-f58a-11e9-9909-892a2fa8532e.png)

**Comment by sprut666666** [comment]
Посмотри DDM845R, думаю проблем не возникнет
