### ISSUE TITLE
Motion Sensor-A

### ISSUE THREAD

**Issue by oleg77s** [sprut/Hub#360]
Address: 000D6F000BEC8E3C/5B3E<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: CentraLite</li><li>0005_ModelIdentifier: Motion Sensor-A</li><li>0006_DateCode: ����������������</li><li>0007_PowerSource: 3</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 14400</li><li>0001_LongPollInterval: 24</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li><li>0004_CheckinIntervalMin: 240</li><li>0005_LongPollIntervalMin: 23</li><li>0006_FastPollTimeoutMin: 120</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 13</li><li>0002_ZoneStatus: 38</li><li>0010_IasCieAddress: FFFFFFFFFFFFFFFF</li><li>0011_ZoneId: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 27</li><li>0031_BatterySize: 2</li><li>0033_BatteryQuantity: 1</li><li>0036_BatteryVoltageMinThreshold: 21</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2344</li><li>0001_MinMeasuredValue: -4000</li><li>0002_MaxMeasuredValue: 6000</li><li>0003_Tolerance: 150</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0100_MacRxBcast: 536870912</li><li>0101_MacTxBcast: 536870912</li><li>0102_MacRxUcast: 536871025</li><li>0103_MacTxUcast: 536871017</li><li>0104_MacTxUcastRetry: 0</li><li>0105_MacTxUcastFail: 0</li><li>0106_ApsRxBcast: 3</li><li>0107_ApsTxBcast: 2</li><li>0108_ApsRxUcast: 23</li><li>0109_ApsTxUcastSuccess: 8</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 503337744</li><li>0003_CurrentZigbeeStackVersion: 65535</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4174</li><li>0008_ImageTypeId: 48</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: CentraLite</li><li>0005_ModelIdentifier: Motion Sensor-A</li><li>0006_DateCode: ����������������</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul></ul></li><li>0B05_Diagnostics<ul></ul></li><li>0406_OccupancySensing<ul></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4174</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Nov 22 19:26:18 MSK 2020
Телеграм: OLEГ
Ссылка на устройство в каталоге: https://v2.sprut.ai/catalog/item/osram-smart-motion-sensor

**Comment by sprut666666** [comment]
Напишите мне в телеграм @sprut666666

**Comment by oleg77s** [comment]
https://www.zigbee2mqtt.io/devices/AC01353010G.html

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/osram-smart-motion-sensor
