### ISSUE TITLE
Проблема с уровнем яркости белого RGB лампы  GS BRHM8E27W70-I1

### ISSUE THREAD

**Issue by sergoo-lbt** [sprut/Hub#363]
** Подробное описание ошибки **

При переключении лампы на режим RGB и потом обратно на белый холодный/теплый - уровень яркости падает в два-три раза, и изменение уровня яркости при этом уже не помогает.
В каталоге: https://v2.sprut.ai/catalog/item/trikolor-umnaa-lampa-cvetnaa-gs-brhm8e27w70-i1

**Comment by sprut666666** [comment]
Ревизия больше 3257
