### ISSUE TITLE
Ошибка отображения в HomeKit.

### ISSUE THREAD

**Issue by Eranovmaxim** [sprut/Hub#364]
Неправильно отображается состояния розетки в HomeKit.

** Как воспроизвести ? **
Все устройства добавлены в spruthub
Добавить устройство xiaomi zncz02lm
Добавить устройство xiaomi wxkg01lm
В HomeKit к кнопке wxkg01lm добавить следующие действия— одно нажатие выключает данную розетку , двойное нажатие включает розетку.

** Ожидаемое поведение **
Розетка когда выключена должна отображаться состоянием выключено в HomeKit. Однако она находиться во включённом состоянии. В интерфейсе spruhub отображается корректно.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия: iOS [14.2]
Hub 1.6.6b 3257
** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

![IMG_1223](https://user-images.githubusercontent.com/32778056/99939183-8a086c80-2d7a-11eb-91da-eef21654484d.jpeg)
![IMG_1224](https://user-images.githubusercontent.com/32778056/99939197-8f65b700-2d7a-11eb-95f3-4f6b16948d04.png)
![IMG_0007](https://user-images.githubusercontent.com/32778056/99939358-f3887b00-2d7a-11eb-917f-788bac326dff.png)
![IMG_0008](https://user-images.githubusercontent.com/32778056/99939450-1d41a200-2d7b-11eb-8284-8015b97f8a72.png)

**Comment by sprut666666** [comment]
Мы есть хомкит) похоже на косяк приложения дом, если закрыть/открыть дом баг повторяется ?

**Comment by Eranovmaxim** [comment]
Повторяется.

**Comment by sprut666666** [comment]
Ревизия больше 3257
