### ISSUE TITLE
Добавить на иконку вентилятора %% скорости

### ISSUE THREAD

**Issue by qwedy** [sprut/Hub#3640]
** Максимально подробное описание предложения.**
Устройствам типа Fan или FanBase, если имеют характеристику Скорость вентилятора, имеет смысл выводить эту скорость на иконку рабочего стола, аналогично как выводится Яркость для диммируемой лампочки или %влажности в датчике влажности и тд.

** Дополнительные материалы **
![Screenshot_2024-11-25-23-23-49-136_com android chrome-edit](https://github.com/user-attachments/assets/27997526-6436-466e-80e4-bd1f1e8a6dfc)

**Comment by Batyushin** [comment]
предлагаю запостить в с пометкой "#ПредложенияПоРазвитию" в чате поддержки ветка "Флул"
