### ISSUE TITLE
Hue Motion sensor

### ISSUE THREAD

**Issue by shurikshurikov** [sprut/Hub#366]
https://v2.sprut.ai/catalog/item/philips-motion-sensor

ДД конец движения отдаёт не сразу,есть какая-то отсечка, может зависнуть и на минуту.
Переодически не срабатывает можно долго стоять махать и статус не меняется. В СХ стоит срабатывание через 6 секунд, в реале это 12 секунд. 

Температуру один раз смотрел,но там явно заметно дольше отдаёт данные чем у той же акары. Люксы отдаёт не сразу иногда небольшая задержка секунд в 5, а иногда вообще не меняются люксы. 

Прошивка 1.6.6b, ревизия 3257

На фото ниже видно, что свет в туалете горит, ДД сработал, а люксы не отдал. 

![image](https://user-images.githubusercontent.com/59749751/99962056-90114400-2da0-11eb-84f3-b35ff67a2947.png)

**Comment by pabl33** [comment]
ещё датчики не могут обновить прошивку.несколько раз замечал что они это пытаются сделать,но ничего не выходит
![4D3D9F78-1FE6-4D49-BFF2-B12EB6158621](https://user-images.githubusercontent.com/48541799/100268179-ac121280-2f65-11eb-8db2-76ce517febf8.png)

**Comment by InfinityMe** [comment]
Мой кажется смог получить последнюю прошивку на сегодняшней версии Sprut.hub 3312:

18:34:11	00178801086458F1/23E0: Опрос пройден. Производитель: Philips, Модель: SML001	
18:34:11	00178801086458F1/23E0 : Настройка, 0030_MotionDetectionSensitivity = 1	
18:34:10	00178801086458F1/23E0 : Настройка, 0010_PirOccupiedToUnoccupiedDelay = 60	
18:34:10	00178801086458F1/23E0: REPORTING, 0021_BatteryPercentageRemaining : (5 - 3600, 10)	
18:34:09	00178801086458F1/23E0 : Связь, 0001_PowerConfiguration	
18:34:08	00178801086458F1/23E0: REPORTING, 0000_MeasuredValue : (5 - 3600, 50)	
18:34:08	00178801086458F1/23E0 : Связь, 0402_TemperatureMeasurement	
18:34:07	00178801086458F1/23E0: REPORTING, 0000_MeasuredValue : (5 - 3600, 2000)	
18:34:06	00178801086458F1/23E0 : Связь, 0400_IlluminanceMeasurement	
18:34:05	00178801086458F1/23E0: REPORTING, 0000_Occupancy : (1 - 3600, 1)	
18:34:05	00178801086458F1/23E0 : Связь, 0406_OccupancySensing	
18:34:04	00178801086458F1/23E0 : Firmware update - NO_IMAGE_AVAILABLE	
18:34:04	00178801086458F1/23E0 : Таблица связей	
18:34:03	00178801086458F1/23E0 : Очистка групп	
18:34:03	00178801086458F1/23E0 : Актуализация прошивки	
18:34:03	00178801086458F1/23E0 : Device loaded 'SML001', manufacturer 'Philips', type = 'End Device'	
18:34:02	00178801086458F1/23E0 : Информация о модели	
18:34:01	00178801086458F1/23E0 : 2/2, Изучение конечной точки 1	
18:34:01	00178801086458F1/23E0 : 2/1, Изучение конечной точки 2	
18:34:00	00178801086458F1/23E0 : Изучение возможностей	
18:34:00	00178801086458F1/23E0 : Энергопотребление	
18:33:59	00178801086458F1/23E0 : Базовая информация	
18:33:59	00178801086458F1/23E0: Запущен опрос устройства	
18:33:59	Node 23E0/00178801086458F1 rejoined	
18:33:31	00178801086458F1/23E0 : **Firmware update - DONE**	
18:16:33	00178801086458F1/23E0 : Firmware update - START, ZigBeeOtaFile [headerVersion=256, headerLength=56, headerFieldControl=0, manufacturerCode=4107, imageType=269, fileVersion=1107323831, stackVersion=ZIGBEE_PRO, headerString=, imageSize=240760]
