### ISSUE TITLE
Philio PAN06-5B

### ISSUE THREAD

**Issue by AGKulikov** [sprut/Hub#367]
Инструкция: https://static-eu.insales.ru/files/1/1771/9053931/original/datasheet_philio_pan06_rus.pdf

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>9</td></tr><tr><td width=35%>Manufacturer Id</td><td>013C</td></tr><tr><td width=35%>Device Type</td><td>0001</td></tr><tr><td width=35%>Device Id</td><td>0013</td></tr><tr><td width=35%>App Version</td><td>1.6</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[]</td><td>?</td></tr><tr><td>2</td><td> Load1</td><td>[]</td><td>?</td></tr><tr><td>3</td><td> Load2</td><td>[]</td><td>?</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 Association</li><li>V1 DeviceResetLocally</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V2 Version</li><li>V1 SwitchBinary</li><li>V1 FirmwareUpdateMD</li><li>V1 ZWavePlusInfo</li><li>V1 SceneActuatorConfiguration</li><li>V2 MultiChannel</li><li>V1 NoOperation</li><li>V1 Configuration</li><li>V1 SwitchAll</li><li>V2 ManufacturerSpecific</li><li>V1 Alarm<ul></ul></li><li>V2 Protection</li><li>V1 Basic</li><li>V1 AssociationGRPInfo</li><li>V1 SceneActivation</li></ul></li><li>Endpoint 1<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li><li>Endpoint 2<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li><li>Endpoint 3<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li></ul><br>Last update: Mon Nov 23 15:43:14 MSK 2020

**Comment by Batyushin** [comment]
Необходимо правильно заполнить 
ссылка на устройство в каталоге, если есть
ссылка на магазин

**Comment by AGKulikov** [comment]
https://v2.sprut.ai/catalog/item/philio-pan06

**Comment by Batyushin** [comment]
Как ввести в Режим спаривания, сброса
Статус после восстановления питания

**Comment by AGKulikov** [comment]
Инструкция: https://static-eu.insales.ru/files/1/1771/9053931/original/datasheet_philio_pan06_rus.pdf

**Comment by MakeSimpleOrg** [comment]
r5851
