### ISSUE TITLE
Нажатие на кнопку - вылетает с 404 ошибкой

### ISSUE THREAD

**Issue by DevelopByte** [sprut/Hub#368]
Нажатие на кнопку - вылетает с 404 ошибкой. https://v2.sprut.ai/catalog/sh/Defaro/Sprut.stick%20ZigBee%202%20Pro

![image](https://user-images.githubusercontent.com/1201624/99971371-bdacbc00-2da5-11eb-927e-99e53dea75f0.png)

**Comment by sprut666666** [comment]
Проверяем на ревизии больше 3257
