### ISSUE TITLE
Проблема с сохранением чувствительности газа Honewell.

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#369]
** Подробное описание ошибки **
Чуствительность у датчика газа Honewell сбрасывается при обновлении хаба (но не уверен, что именно обновление, возможно само по себе)

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1) Зайти в аксессуары
2) Выбрать датчик газа Honewell
3) Выставить чувствительность некоторое количество газа.
4) Обновить хаб , когда прилетает обновление.
5) Увидеть, что произошел сброс на "Немного газа"

** Ожидаемое поведение **
Чтобы чувствительность сохранялась, чтобы не происходило с хабом, уже замучился:)

** Скриншоты/ Логи **
Если будут нужны, отпишу

** Пожалуйста, заполните следующую информацию: **
  ios 14.2
ревизия: 3257
** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
раньше настройки не сохранялись, если повторится открыть проблему заново
