### ISSUE TITLE
TS0205

### ISSUE THREAD

**Issue by sergiogazprom** [sprut/Hub#370]
Родного хаба для Tuya у меня нет. Это аварийный датчик задымления от Tuya. Покупался здесь https://aliexpress.ru/item/4001220370806.html?spm=a2g0s.9042311.0.0.264d33edUJz90X&_ga=2.89016403.918040987.1606159362-1024199036.1606159362
telegramm @SergeiLenkov

Address: EC1BBDFFFEDF687A/D713

Structure
Endpoint 1
Input
0000_Basic
0000_ZclVersion: 3
0001_ApplicationVersion: 64
0004_ManufacturerName: _TYZB01_dsjszp0x
0005_ModelIdentifier: TS0205
0007_PowerSource: 3
0500_IasZone
0000_ZoneState: 0
0001_ZoneType: 40
0002_ZoneStatus: 4
0010_IasCieAddress: 0000000000000000
0011_ZoneId: 255
0001_PowerConfiguration
0020_BatteryVoltage: 30
0021_BatteryPercentageRemaining: 200
0003_Identify
0000_IdentifyTime: 0
Output
0003_Identify
0019_OtaUpgrade
0000_UpgradeServerId: FFFFFFFFFFFFFFFF
0001_FileOffset: -1
0006_ImageUpgradeStatus: 0

Aps Flags | 0
-- | --
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 82
Incoming Transfer Size | 82
Logical Type | End Device
Mac Capabilities | [REDUCED_FUNCTION_DEVICE]
Manufacturer Code | 0
Out Going Transfer Size | 82
Stack Compliance | 22

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-datcik-dyma-multi-ir
