### ISSUE TITLE
1.6.6 не работает инверсия на шторах

### ISSUE THREAD

**Issue by peefoo** [sprut/Hub#371]
Модуль wb. для штор, автоматически созданное устройство. Перестали работать инверсии целевого и текущего положения штор в процентах

**Comment by peefoo** [comment]
Ревизия: 3240
Дата сборки: 22.11.2020, 07:50:08

**Comment by MakeSimpleOrg** [comment]
Перезагружать хаб пробовал?

**Comment by peefoo** [comment]
> Перезагружать хаб пробовал?

Да, и хаб и WB

**Comment by sprut666666** [comment]
исправлено
