### ISSUE TITLE
Не работает инверсия на Модуле ввода-вывода WBIO-DI-WD-14

### ISSUE THREAD

**Issue by Myshyk100** [sprut/Hub#373]
к данному датчику подключен датчик двери, получается когда дверь закрыта он показывает открыта
в Параметры характеристики есть возможность включить инверсию но она не работает

Телеграм: [@myshyk100 )
Девайс в [каталоге]нет
Покупал [тут]подарок

**Comment by Myshyk100** [comment]
Помогает перезагрузка SprutHub

**Comment by sprut666666** [comment]
испралено
