### ISSUE TITLE
Не сохраняет состояние датчика Honewell (ревизия 3278)

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#377]
** Подробное описание ошибки **
Не сохраняется состояние датчика газа от Honewell при перезагрузке и обновлении хаба.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1) Зайти в вэбморду
2) Выставить в датчике газа Honewell значение отличное от стандартного на "некоторое кол-во газа"
3) Перезагрузить/обновить хаб и увидеть, что значение не сохранилось и вернулось на "немного газа"

** Ожидаемое поведение **
Сохранение состояния при перезагрузке

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
 Ревизия 3278
Ios 14.2

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
в след обновлении
