### ISSUE TITLE
ZLED-2209

### ISSUE THREAD

**Issue by sergiogazprom** [sprut/Hub#378]
telegramm @SergeiLenkov
Лампочки Trust Zigbee Dimmable LED Bulb Flame ZLED-2209 определились как ZLED-G2705. Фактически работает одна из двух. Вторая не реагирует на команды (хотя по логам ведет себя идентичной первой. Может быть брак самой лампы, но до привязки к хабу загоралась). 
Логи по лампе после добавления (в логе ошибки появляются, до появления лампы их не было). Из хоумкит управление не стабильное. На команду включения не всегда реагирует (статус - включена, по факту не горит) Но если дернуть ползунком яркости - загорается). Привязал через триггер к датчику движения - работает стабильно.
Все же предлагаю сделать отдельную карточку для этой лампы
telegramm @SergeiLenkov

22:17:25 | TX_NAK: EzspMessageSentHandler [networkId=0, type=EMBER_OUTGOING_DIRECT, indexOrDestination=488A, apsFrame=EmberApsFrame [profileId=0104, clusterId=0008, sourceEndpoint=1, destinationEndpoint=1, options=[EMBER_APS_OPTION_ENABLE_ADDRESS_DISCOVERY, EMBER_APS_OPTION_RETRY], groupId=0, sequence=3A], messageTag=19, status=EMBER_DELIVERY_FAILED, messageContents=] |  
22:17:25 | Transaction terminated (Device not respond): 0000_ReadAttributesCommand [0008_LevelControl: 0000/0 -> 488A/1, TID=19, Input, identifiers=[0000_CurrentLevel]] |  
22:16:11 | TX_NAK: EzspMessageSentHandler [networkId=0, type=EMBER_OUTGOING_DIRECT, indexOrDestination=488A, apsFrame=EmberApsFrame [profileId=0104, clusterId=0008, sourceEndpoint=1, destinationEndpoint=1, options=[EMBER_APS_OPTION_ENABLE_ADDRESS_DISCOVERY, EMBER_APS_OPTION_RETRY], groupId=0, sequence=39], messageTag=17, status=EMBER_DELIVERY_FAILED, messageContents=] |  
22:16:11 | Transaction terminated (Device not respond): 0000_ReadAttributesCommand [0008_LevelControl: 0000/0 -> 488A/1, TID=17, Input, identifiers=[0000_CurrentLevel]] |  
22:16:04 | ZigBee поиск завершён |  
22:16:04 | Created accessory: id=18, name=Лампочка, model=ZLED-G2705 |  
22:16:04 | 00158D0000737164/488A: Опрос пройден. Производитель: Trust International B.V., Модель: ZLL-DimmableLigh |  
22:16:04 | 00158D0000737164/488A : Таблица связей |  
22:16:04 | 00158D0000737164/488A : Очистка групп |  
22:16:01 | 00158D0000737164/488A: Запущен опрос устройства |  
22:15:48 | ZigBee поиск запущен на 60 секунд

Address: 00158D0000737164/488A

Structure
Endpoint 1
Input
0000_Basic
0001_ApplicationVersion: 1
0004_ManufacturerName: Trust International B.V.
0005_ModelIdentifier: ZLL-DimmableLigh
0007_PowerSource: 1
0003_Identify
0004_Groups
0005_Scenes
0006_OnOff
0000_OnOff: true
0008_LevelControl
0000_CurrentLevel: 254
0019_OtaUpgrade
FFFF_ManufacturerSpecific
Output
0000_Basic
0003_Identify
0004_Groups
0005_Scenes
0006_OnOff
0008_LevelControl
0019_OtaUpgrade
Endpoint 2
Input
0000_Basic
1000_TouchlinkCommissioning
Output
1000_TouchlinkCommissioning

Aps Flags | 0
-- | --
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 127
Incoming Transfer Size | 80
Logical Type | Router
Mac Capabilities | [FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]
Manufacturer Code | 4151
Out Going Transfer Size | 80
Stack Compliance | 0

Current Power Mode | RECEIVER_ON_IDLE
-- | --
Available Power Sources | [MAINS]
Current Power Source | MAINS
Power Level | FULL

**Comment by Batyushin** [comment]
необходимо правильно заполнить. Добавить:
ссылка на каталог, если есть
ссылка на магазин
