### ISSUE TITLE
Розетка всегда включена

### ISSUE THREAD

**Issue by ElvisPresly** [sprut/Hub#379]
На примере розетки Xiaomi ZNCZ02LM.

Предлагаю добавить в админку параметр «Всегда включена» (да/нет) - как в Athom homey

Например полезно когда я хочу измерять потребление энергии (например роутер, газовый котел и т д), но не хочу чтобы кто-то случайно выключил розетку (например ребенок).

ПС: Ну и соответственно если тыкать в нее в HomeKit то она оставалась бы включена.

**Comment by sprut666666** [comment]
обновиться, и сделать тригер если если выкл -> вкл

**Comment by ElvisPresly** [comment]
Спасибо. Нет возможности сделать, чтобы даже на мгновение не отключалось?

**Comment by sprut666666** [comment]
Если в самом устройстве нет такой настройки, тогда только не отключать, ибо устройство передаёт статус в хаб только после отключения.
