### ISSUE TITLE
QBKG12LM  - двухклавишный выключатель акара 

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#380]
Ревизия: 3284
QBKG12LM - двухклавишный выключатель акара 
одна из кнопок используется как виртуальная (программируемая кнопка)
при перезагрузке хаба отдает сигнал, как буд-то на нее нажали. 
можно это отключить пожалуйста.

**Comment by bumer0** [comment]
lumi.ctrl_ln2.aq1

**Comment by sprut666666** [comment]
Как вас найти в телеграм ?

**Comment by bumer0** [comment]
@alexkost1

**Comment by bumer0** [comment]
ревизия 3323
192.168.1.17 - СХ
192.168.1.9 (отдельный комп) - Node-Red

после перезагрузки или обновления СХ прилетает в NR сигнал о нажатии програмируемой кнопки
в настройках ноды отключено действие отправлять при старте 
см картинку 
![image](https://user-images.githubusercontent.com/31984665/100538742-ac026300-3242-11eb-9b42-8b8f62cdf58d.png)

через пару минут после загрузки хаба, опять прилетает уведомление, что кнопки нажаты. 

видеозапись оправил в телегу в личку
