### ISSUE TITLE
Лампы RGB не добавляются в Яндекс Алису

### ISSUE THREAD

**Issue by sergoo-lbt** [sprut/Hub#382]
** Подробное описание ошибки **
Если добавленная в СХ RGB лампа имеет одновременно параметры цвета и температуры, то в Яндекс добавление не происходит. При создании виртуальной лампы без параметра температуры происходит нормальное добавление в Алису. 
![E4AB7BF2-E369-47B3-AED7-72BB1FD8379D](https://user-images.githubusercontent.com/64399012/100336932-913cae00-2ff8-11eb-85d2-a64cb12f0c5a.png)

**Comment by xsibirevx** [comment]
Да, у меня с gledopto-007P так же

**Comment by MakeSimpleOrg** [comment]
Это исправлено в r4420, надо проверить

**Comment by sergoo-lbt** [comment]
> Это исправлено в r4420, надо проверить

Так у нас последнее актуальное обновление 4376. Обновится. Попробовать?

**Comment by denv3r** [comment]
> Это исправлено в r4420, надо проверить

Как это сделать? У меня последняя доступная версия 4379.

**Comment by sergoo-lbt** [comment]
> > Это исправлено в r4420, надо проверить
> 
> Как это сделать? У меня последняя доступная версия 4379.

Никак. Нам эта версия не доступна🤷🏻‍♂️
