### ISSUE TITLE
Добавьте устройство Z-wave Curtian Switch NeoCoolcam

### ISSUE THREAD

**Issue by eag1968** [sprut/Hub#383]
Добавьте устройство Z-wave Curtian Switch NeoCoolcam
https://szneo.com/en/products/show.php?id=234

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>31</td></tr><tr><td width=35%>Manufacturer Id</td><td>0258</td></tr><tr><td width=35%>Device Type</td><td>0200</td></tr><tr><td width=35%>Device Id</td><td>102C</td></tr><tr><td width=35%>App Version</td><td>2.1</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Class B Motor</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td></td><td>[]</td><td>5</td></tr><tr><td>2</td><td></td><td>[]</td><td>5</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 AssociationGRPInfo</li><li>V2 Association</li><li>V1 NoOperation</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 ZWavePlusInfo</li><li>V1 Configuration</li><li>V1 Basic</li><li>V1 SwitchBinary</li><li>V1 DeviceResetLocally</li><li>V2 Version</li><li>V1 Security</li><li>V2 ManufacturerSpecific</li><li>V3 MultiChannelAssociation</li><li>V4 SwitchMultiLevel<ul></ul></li></ul></li></ul><br>Last update: Thu Nov 26 15:09:02 YEKT 2020

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/neo-curtain-switch

**Comment by MakeSimpleOrg** [comment]
Давно сделано.

**Comment by eag1968** [comment]
А вот это когда?   https://github.com/sprut/Hub/issues/496 <https://github.com/sprut/Hub/issues/496>
