### ISSUE TITLE
Вопрос относительно Docker

### ISSUE THREAD

**Issue by bastshoes** [sprut/Hub#385]
** Максимально подробное описание предложения.**
Четкое и краткое описание предложения, так чтобы вас смог понять "глупый" человек.

Планируется ли к выпуску Sprut.Hub в виде докера?

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
До релиза точно нет
