### ISSUE TITLE
MZ100

### ISSUE THREAD

**Issue by oleg77s** [sprut/Hub#388]
Address: 94103EA2B278B0A6/0BAC<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 131</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: MRVL</li><li>0005_ModelIdentifier: MZ100</li><li>0007_PowerSource: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 128</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 255</li><li>0001_RemainingTime: 0</li><li>0010_OnOffTransitionTime: 30</li><li>0011_OnLevel: 255</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 60A423FFFE4174D9</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 16908419</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 21640</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>64</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>0</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>48042</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>0</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, RECHARGABLE_BATTERY, MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Nov 28 10:56:11 MSK 2020

Статус после восстановления питания: всегда включено
можно было купить https://ivenue.ru/catalog/gadzhety/belkin_wemo_lighting_umnaya_lampa_f7c033vfe27/
Телеграм: OLEГ

**Comment by Batyushin** [comment]
Внимательно заполняйте. Необходимо дополнить:
ссылка на каталог если есть
ссылку где купил

**Comment by oleg77s** [comment]
она же Belkin F7C033. https://www.zigbee2mqtt.io/devices/F7C033.html

**Comment by Batyushin** [comment]
> она же Белкин F7C033. https://www.zigbee2mqtt.io/devices/F7C033.html

https://v2.sprut.ai/catalog/item/belkin-wemo-smart-led-bulb

**Comment by oleg77s** [comment]
статус после восстановления питания: всегда включено 100%, версия zigbee: 2, режим сброса: включенную лампу выкл на 1 сек/вкл на 3-4 сек 3 раза и включить

**Comment by oleg77s** [comment]
работает ОК
