### ISSUE TITLE
Модуль WB-MRGBW-D не принимает изменения RGB каналов из Sprut.Hub

### ISSUE THREAD

**Issue by Rainstation** [sprut/Hub#39]
** Подробное описание ошибки **
При попытки изменения цвета (RGB каналов) из Sprut.Hub (homekit и яндекс, соответственно) никаких изменений не происходит. Отдельно белый канал W отрабатывает отлично. Из самого Wirenboard управление работает, как RGB, так и W каналами. При подключении напрямую к топикам модуля и изменении каналов RGB из Спрутхаба, никаких изменений в топике RGB модуля не происходит тоже.

** Как воспроизвести ? **
Подключить модуль WB-MRGBW-D к Wirenboard по RS-485. Подключить к модулю RGBW ленту и блок питания по инструкции. Убедится, что модуль управляется из WebUI Wirenboard правильно. Установить Спрутхаб на Wirenboard. Убедится, что модуль появился в аксессуарах как два устройства W лента и RGB лента. Проверить работу W ленты, проблем не будет. Проверить работу RGB ленты, можно из под homekit или яндекса, эффект аналогичный - работать не будет.

** Ожидаемое поведение **
Конечный результат изменение цвета из homekit и яндекс

** Скриншоты/ Логи **
Все в описании.

** Пожалуйста, заполните следующую информацию: **
  - Версия: SprutHub 1.3.8b

** Дополнительные материалы **
Все в описании.

**Comment by diamond5170** [comment]
1.4.3
