### ISSUE TITLE
Добавить кнопку Выключение в вэб интерфейсе

### ISSUE THREAD

**Issue by InfinityMe** [sprut/Hub#392]
Предлагаю добавить в вэб интерфейс кнопку "**Выключение**".

Иногда нужно выключить устройство, для переноса в другое место, подключения к другому источнику питания, разборки корпуса и доклейки теплопроводящих прокладок :-) 
Неправильное завершение работы часто портит файловую систему.
Делать это через SSH немного долго, или точнее я на вскидку не знаю команду. 
Добавление кнопки **Выключение** поберегло бы файловые системы устройств.

**Comment by sprut666666** [comment]
вынесено на голосование
