### ISSUE TITLE
Поведение аксессуаров при включении хаба

### ISSUE THREAD

**Issue by AGKulikov** [sprut/Hub#394]
Хочу иметь настройку для виртуальных аксессуаров и аксессуаров, которыми можно управлять (реле, лампочки, выключатели и т.д.) - "поведение аксессуара при загрузке хаба после обесточивания его", это позволит управлять аксессуарами, которые не умеет сохранять свое состояние и более гибко настраивать виртуальную логику для виртуальных устройств

@AGKulikov

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
