### ISSUE TITLE
Не проходит опрос уже добавленное и ранее работавшее устройство.

### ISSUE THREAD

**Issue by ElvisPresly** [sprut/Hub#396]
** Подробное описание ошибки **
Устройство работало, теперь не работает, опрос не проходит. Через админку и хомкит на команды не откликаются.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
Возможно это плавующий баг, я не знаю что привело к его поячвлению.

** Ожидаемое поведение **
Ожидал что добавлю устройство в сеть, и буду им пользоваться пока не удалю из сети.

Ревизия: 3325
Дата сборки: 29.11.2020, 19:31:56

Скриншоты и логи в прикреплении, готов переспаривать устройство пока не буду, готов предоставить любые логи, чтобы впредь эта проблема не повторялась.
[logs.zip](https://github.com/sprut/Hub/files/5614146/logs.zip)
<img width="1070" alt="Снимок экрана 2020-11-30 в 09 35 16" src="https://user-images.githubusercontent.com/18265958/100576773-dc540b00-32ef-11eb-9639-3965bd397aed.png">
<img width="1440" alt="Снимок экрана 2020-11-30 в 09 36 07" src="https://user-images.githubusercontent.com/18265958/100576776-dd853800-32ef-11eb-9a20-8b08d8e0cbf0.png">

**Comment by ElvisPresly** [comment]
забыл добавить, произошло одновременно на двух реле, до этого несколько дней назад было такое же но с мишной розеткой.
Реле акара WXKG03LM
<img width="1440" alt="Снимок экрана 2020-11-30 в 10 12 50" src="https://user-images.githubusercontent.com/18265958/100579210-d6acf400-32f4-11eb-8e7a-ca5838d92501.png">

**Comment by sprut666666** [comment]
В след обновлении
