### ISSUE TITLE
Добавление нового Датчик открытия двери/окна Z-Wave Fibaro FGDW-001

### ISSUE THREAD

**Issue by Bukvoed66** [sprut/Hub#397]
https://manuals.fibaro.com/door-window-sensor/
[FGK-10x-RU-A-v1.01.pdf](https://github.com/sprut/Hub/files/5612044/FGK-10x-RU-A-v1.01.pdf)

<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>13</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0700</td></tr><tr><td width=35%>Device Id</td><td>1000</td></tr><tr><td width=35%>App Version</td><td>2.1</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Sensor Binary</td></tr><tr><td width=35%>Specific Class</td><td>Routing Sensor Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td></td><td>[]</td><td>?</td></tr><tr><td>2</td><td></td><td>[]</td><td>?</td></tr><tr><td>3</td><td></td><td>[]</td><td>?</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 SensorBinary<ul></ul></li><li>V1 WakeUp<ul><li>Interval: 18000</li><li>Interval: 05/00/00.000</li><li>Min: 0</li><li>Max: 2147483647</li><li>Step: 0</li></ul></li><li>V1 FirmwareUpdateMD</li><li>V1 ManufacturerSpecific</li><li>V1 Battery</li><li>V1 SensorAlarm<ul><li>Smoke: 0</li><li>CarbonDioxide: 0</li><li>General: 0</li><li>Heat: 0</li><li>CarbonMonoxide: 0</li><li>Flood: 0</li></ul></li><li>V1 Basic</li><li>V2 Association</li><li>V1 Configuration</li><li>V1 Version</li><li>V1 SceneActivation</li><li>V1 NoOperation</li></ul></li></ul><br>Last update: Mon Nov 30 04:42:03 MSK 2020
[FGK-10x-RU-A-v1.00.pdf](https://github.com/sprut/Hub/files/5614325/FGK-10x-RU-A-v1.00.pdf)

**Comment by MakeSimpleOrg** [comment]
Это FGK-101 а не FGDW-001. Но скоро тоже сделаю.

**Comment by MakeSimpleOrg** [comment]
r4889
