### ISSUE TITLE
Проблема с обновлением SH командой "update" в консоле WB

### ISSUE THREAD

**Issue by SkysystemX** [sprut/Hub#40]
SH не может прокинуться в HomeKit из-за проблемы обновления с Украины. Не устанавливаются файлы обновления, так как они размещены на mirror.yandex.ru

Шаги для воспроизведения ошибки:
1. В консоли WB вводим "update"
2. В логах видим ошибки: "не удалось найти IP-адрес для "mirror.yandex.ru"
3. И соответственно, мы не можем скачать файлы обновления с этого ресурса 
4. SprutHub не обновляется из-за невозможности скачать файлы обновления таким образом

В результате мы не можем прокинуть SH в HomeKit

  - Версия: [Windows 10]

Проверенным решением данной проблемы является замена Репозитория для скачивания файлов обновления. С помощью команды автозамены в консоли Wiren Board:

sed -i -e 's/mirror.yandex.ru/debian.org.ua/g' /etc/apt/sources.list
![photo_2019-11-14_18-55-44](https://user-images.githubusercontent.com/55890040/68878685-cdb0ab00-0710-11ea-8aff-a9b8302c2595.jpg)

**Comment by diamond5170** [comment]
Это скорее к разработчикам Wirenboard, это они прописали яндекс зеркала.
