### ISSUE TITLE
Реле 8x8 ModKam.ru  C31F/00124B001EC7EB30 прошивка ptvo.info

### ISSUE THREAD

**Issue by WinManMC** [sprut/Hub#402]
Устройство
https://modkam.ru/?p=1638
Прошивка
https://ptvo.info/

Address: 00124B001EC7EB30/C31F<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 1</li><li>0001_PersistentMemoryWrites: 0</li><li>0100_MacRxBcast: 0</li><li>0101_MacTxBcast: 0</li><li>0102_MacRxUcast: 0</li><li>0103_MacTxUcast: 0</li><li>0104_MacTxUcastRetry: 4</li><li>0105_MacTxUcastFail: 4</li><li>0106_ApsRxBcast: 0</li><li>0107_ApsTxBcast: 1</li><li>0108_ApsRxUcast: 0</li><li>0109_ApsTxUcastSuccess: 24</li><li>010A_ApsTxUcastRetry: 0</li><li>010B_ApsTxUcastFail: 0</li><li>010C_RouteDiscInitiated: 0</li><li>010D_NeighborAdded: 0</li><li>010E_NeighborRemoved: 0</li><li>010F_NeighborStale: 0</li><li>0110_JoinIndication: 0</li><li>0111_ChildMoved: 0</li><li>0112_NwkFcFailure: 0</li><li>0113_ApsFcFailure: 0</li><li>0114_ApsUnauthorizedKey: 0</li><li>0115_NwkDecryptFailures: 0</li><li>0116_ApsDecryptFailures: 0</li><li>0117_PacketBufferAllocateFailures: 0</li><li>0118_RelayedUcast: 0</li><li>0119_PhyToMacQueueLimitReached: 0</li><li>011A_PacketValidateDropCount: 0</li><li>011B_AverageMacRetryPerApsMessageSent: 0</li><li>011C_LastMessageLqi: 174</li><li>011D_LastMessageRssi: -21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 1</li><li>0001_PersistentMemoryWrites: 0</li><li>0100_MacRxBcast: 0</li><li>0101_MacTxBcast: 0</li><li>0102_MacRxUcast: 0</li><li>0103_MacTxUcast: 0</li><li>0104_MacTxUcastRetry: 4</li><li>0105_MacTxUcastFail: 4</li><li>0106_ApsRxBcast: 0</li><li>0107_ApsTxBcast: 1</li><li>0108_ApsRxUcast: 0</li><li>0109_ApsTxUcastSuccess: 32</li><li>010A_ApsTxUcastRetry: 0</li><li>010B_ApsTxUcastFail: 0</li><li>010C_RouteDiscInitiated: 0</li><li>010D_NeighborAdded: 0</li><li>010E_NeighborRemoved: 0</li><li>010F_NeighborStale: 0</li><li>0110_JoinIndication: 0</li><li>0111_ChildMoved: 0</li><li>0112_NwkFcFailure: 0</li><li>0113_ApsFcFailure: 0</li><li>0114_ApsUnauthorizedKey: 0</li><li>0115_NwkDecryptFailures: 0</li><li>0116_ApsDecryptFailures: 0</li><li>0117_PacketBufferAllocateFailures: 0</li><li>0118_RelayedUcast: 0</li><li>0119_PhyToMacQueueLimitReached: 0</li><li>011A_PacketValidateDropCount: 0</li><li>011B_AverageMacRetryPerApsMessageSent: 0</li><li>011C_LastMessageLqi: 176</li><li>011D_LastMessageRssi: -20</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 4<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li></ul></li><li>Endpoint 5<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li></ul></li><li>Endpoint 6<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 7<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 8<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0006_DateCode: 2019-06-21</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2019-06-21</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><table border=1 width=100%><tr><th>NWK</th><th>IEEE</th><th>Name</th><th>Type</th></tr><tr><td>1683</td><td>00158D000533BE4E</td><td>Универсальный датчик</td><td>End Device</td></tr></table><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>00124B0014B554EF</td><td>0000</td><td>Coordinator</td><td>true</td><td>Parent</td><td>189</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D000533BE4E</td><td>1683</td><td>End Device</td><td>true</td><td>Child</td><td>202</td><td>UNKNOWN</td><td>2</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Dec 01 17:32:07 MSK 2020

**Comment by ZeroBLYNK** [comment]
единственный девайс (+#403), из-за которого не могу полностью отказаться от z2m

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/modkam-vosmikanalnoe-zigbee-rele

**Comment by WinManMC** [comment]
Спасибо огромное !!
Жизнь налаживается ;)

**Comment by WinManMC** [comment]
Спасибо!

Marat Cherkesov
+7(915)2831629
