### ISSUE TITLE
Aqara B1 не работает ручное открытие/закрытие

### ISSUE THREAD

**Issue by Bigmanekb** [sprut/Hub#404]
** Подробное описание ошибки **
При включении режима ручного закрытия/открытия у Aqara B1 в разделе контроллеры - ничего не меняется. Шторой управлял, хаб перезагружал.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Идем в раздел Контроллеры
2. Заходим внутрь Zigbee
3. Находим штору
4. Нажимаем три точки 
5. Выбираем параметры
6. Ставим галку

![изображение](https://user-images.githubusercontent.com/46221443/100898825-f99cfb00-34e2-11eb-9adb-e78e6f806b91.png)

** Ожидаемое поведение **
при провороте мотора при ручном закрытии или открытии - мотор должен закрыть или открыть штору

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.6.6.b Ревизия: 3340 Дата сборки: 02.12.2020, 15:22:32

** Дополнительные материалы **
[B1.zip](https://github.com/sprut/Hub/files/5630568/B1.zip)

**Comment by sprut666666** [comment]
В след обновлении
