### ISSUE TITLE
Водяной кран висит в homekit со статусом обновления

### ISSUE THREAD

**Issue by bumer0** [sprut/Hub#405]
** Подробное описание ошибки **

Создал новый аксессуар водопроводный кран.  
В homekit все время висит со статусом обновление.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Создать а сх аксессуар водопроводный кран
2. Проверить а homekit 

** Ожидаемое поведение **
Корректный статус в homekit 

** Скриншоты/ Логи **
![060E9ACC-C091-450D-A189-591C648B9BFD](https://user-images.githubusercontent.com/31984665/100907277-28af6e80-34db-11eb-9ff8-d3d8b9c188c8.jpeg)

** Пожалуйста, заполните следующую информацию: **
  Ios 14.2 релиз

** Дополнительные материалы **
Телега @alexkost1
https://t.me/c/1419924663/5318

**Comment by MakeSimpleOrg** [comment]
Чтобы такого не происходило, нужно включить логику в настройках сервиса крана.

**Comment by bumer0** [comment]
не могу сообразить где?
![image](https://user-images.githubusercontent.com/31984665/100973326-6946d080-354b-11eb-89d0-3975c76cb59e.png)
![image](https://user-images.githubusercontent.com/31984665/100973355-7237a200-354b-11eb-9dba-87e5fe1834da.png)
