### ISSUE TITLE
Выключатель Aqara D1 3 клавишный - не меняется состояние клавиш при ручном управлении

### ISSUE THREAD

**Issue by deemerby** [sprut/Hub#407]
** Подробное описание ошибки **

https://v2.sprut.ai/catalog/item/aqara-wall-switch-d1-three-button

После ручного управлении выключателем - текущее состояние клавиш не меняется. Проверено в HK и в СХ в аксессуарах.  

** Как воспроизвести ? **
1. Проверить состояние выключателям - все клавиши в выключенном состоянии, состояния совпадают в реальности с отображаемым.  
2. Нажать любую из клавиш и проверить состояние в реальности и в HK и в СХ. оно будет не совпадать с текущим состоянием клавиши.  Т.е. состояние не поменялось. 
3. Проделать туже манипуляцию с остальными клавишами. Поведение будет такое же. 
4. При управлении клавишами дистанционно через HK или СХ - состояние отображается корректно. 

** Ожидаемое поведение **
При ручном управлении - реальное состояние выключателя и состояние в умном доме - должно совпадать. Что и происходит, но только при дистанционном управлении. 

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.6.6b. Ревизия: 3325
Дата сборки: 29.11.2020, 19:31:56

**Comment by sprut666666** [comment]
Не верю, обновить если воспроизведётся, видео и стукнуть в телегу @sprut666666

**Comment by deemerby** [comment]
@sprut666666 
Обновил СХ до последней версии. 
Воспроизводится. 
Видео скину в телегу.

**Comment by sprut666666** [comment]
в след сборке, переспарить девайс
