### ISSUE TITLE
При перезагрузки Спрутхаба в Node-Red прилетают события с кнопок Xiaomi и Aqara

### ISSUE THREAD

**Issue by JonnyLuz** [sprut/Hub#409]
Использую Node-red и плагин от Андрея Попова. При перезагрузке СХ получаю события с кнопок Xiaomi и Aqara. Причем один раз они приходят практически сразу, а потом через 55 секунд еще раз дважды от каждой кнопки. Для создании автоматизаций это совершенно не удобно, так как происходит активация устройств или сценариев.

Ожидаю запрет на отправку сообщений в mqtt, пока СХ не закончит свои операции по перезагрузке. Это приведет к потере сообщений в момент перезагрузки, но не будет мешать логике работы сторонних сценарных движков, пока вашего - нет.
![1](https://user-images.githubusercontent.com/31994854/101143206-a41e3680-3627-11eb-9675-5ba32603362d.JPG)
![2](https://user-images.githubusercontent.com/31994854/101143212-a5e7fa00-3627-11eb-9c6d-45d0f731ee45.JPG)

**Comment by Maxwell70** [comment]
Подтверждаю наличие описанного бага и тоже надеюсь на устранение.

**Comment by JonnyLuz** [comment]
Извиняюсь, здесь я ошибся. Закрываю ишью.

**Comment by JonnyLuz** [comment]
Простите не то ишью закрыл, это в силе

**Comment by sprut666666** [comment]
обновить и то и то
