### ISSUE TITLE
Eltex SZ-W02 не спаривается и не создается аксессуар

### ISSUE THREAD

**Issue by Bigmanekb** [sprut/Hub#426]
** Подробное описание ошибки **
При спаривании процесс останавливается на шаге "Конечные точки". Аксессуар не создается.
Путем шаманства и нескольких попыток спаривания, включая процедуру лечения сети, удается дойти до шага создания аксессуара, но данные не приходят.

Контроллер Z-Wave пересоздавал
Устройства отвязывал и привязывал заново
Проверено на двух устройствах

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Запустить процесс спаривания на СХ и на устройстве

** Ожидаемое поведение **
Создание аксессуара и нормальная работа

** Скриншоты/ Логи **
[eltex_logs.zip](https://github.com/sprut/Hub/files/5655687/eltex_logs.zip)

** Пожалуйста, заполните следующую информацию: **
  - Версия СХ: 1.6.6b Ревизия: 3386

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
