### ISSUE TITLE
lumi.switch.n0agl1

### ISSUE THREAD

**Issue by kvazis** [sprut/Hub#428]
Address: 04CF8CDF3C8E4BAF/E592<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 21</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.n0agl1</li><li>0006_DateCode: Aug  8 2020</li><li>0007_PowerSource: 0</li><li>0008_GenericDeviceClass: 255</li><li>4000_SwBuildId: </li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>00F7_Custom: {3=19, 100=false, 149=0.0, 5=1, 150=2269.120361328125, 151=0.0, 152=0.0, 8=277, 9=256, 154=0, 11=0}</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: 0000000000000000</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Unknown: 33554432</li></ul></li><li>0009_Alarms<ul><li>0000_AlarmCount: 0</li></ul></li><li>000A_Time<ul><li>0000_Time: +##+##�����	�����</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0001_FileOffset: 0</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 21<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0.0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 41<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 31<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 0.0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Dec 08 17:10:16 MSK 2020

[logs (1).zip](https://github.com/sprut/Hub/files/5659720/logs.1.zip)

После сопряжения с шлюзом выполнены следующие действия - 
Вкл/Выкл реле
Вкл / Выкл режима сохранения состояние перед отключением
Сохранение режимов внешнего выключателя 
Тумблер, Возвратный, Нет выключателя, Тумблер
Ссылки в каталоге не нашел, это реле Aqara T1 с нулевой линией

**Comment by kvazis** [comment]
New logs
[logs (2).zip](https://github.com/sprut/Hub/files/5660372/logs.2.zip)

**Comment by Batyushin** [comment]
Без нуля https://v2.sprut.ai/catalog/item/aqara-single-switch-module-t1-no-neutral
с нулем https://v2.sprut.ai/catalog/item/aqara-single-switch-module-t1
