### ISSUE TITLE
Не работает управление Термостатом ОКЕ-20 через Яндекс/Алису

### ISSUE THREAD

**Issue by jigi84** [sprut/Hub#43]
** Подробное описание ошибки **
Отсутсвует какое либо управление термостатом. Ни с приложения Яндекс ни голосом через Алису. При чем, если открыть термостат в приложении Яндекс и выключить его (термостат), кнопка становится становится неактивной и через 10 секунд снова загорается.

** Как воспроизвести ? **
Просто попробовать управлять термостатом. 

** Ожидаемое поведение **
Ожидаю включение и выключение, а также изменение температуры через Алису.

** Скриншоты/ Логи **
Тут откуда логи брать, если не работает связь?

** Пожалуйста, заполните следующую информацию: **
  - Версия: СХ 1.3.8b
 -  iOS  последняя на 16 ноября, Не бета.

**Comment by diamond5170** [comment]
Создал виртуальный термостат, работает.
Нужен как минимум скрин термостата в веб панели, полностью раскрытого.
И учтите, что "обновить список устройств" в яндексе использовать нельзя, т.к. оно у них глючит (их вина) и не полностью обновляет инфу. Нужно отвязывать аккаунт и привязывать его заново.
Например, не обновляются комнаты и имена без перепривязки.

**Comment by jigi84** [comment]
Так он не раскрывается, это же физический термостат теплолюкса. Он просто есть. Отвязывать и привязывать аккаунт к Яндекс пробовал - не помогает.  В версии 1 3 4 все он работал отлично.

**Comment by diamond5170** [comment]
В нашей веб панели. Меня интересует, сколько там характеристик, и какие они. И как назван термостат.

**Comment by diamond5170** [comment]
Исправлялось.
