### ISSUE TITLE
Modbus канал 2 пропали устройства и аксессуары

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#431]
** Подробное описание ошибки **
После обновления на сборку версии 1.6.6b 3-5 подрелизов назад, частично пропали аксессуары (до этого работали и были настроены). Оказалось что в контроллере на 2 канале отсутствуют устройства для которых пропавшие аксессуары были созданы. Поиск находит устройства, но ни они, ни аксессуары от этого не появляются

** Как воспроизвести ? **
Настроить модбас на обоих каналах, попытаться найти устройства и сравнить их список со списком добавленных в хаб аксессуаров

** Ожидаемое поведение **
Что устройства после поиска будут отображаться в хабе и аксессуары будут управляемы через него 

** Скриншоты/ Логи **
Прилагаются
![831A7C84-745D-4681-915E-4EDEEE245974](https://user-images.githubusercontent.com/55746897/101676260-fe762780-3a6b-11eb-925a-bb4c3cbd3b00.jpeg)
![D2F1ABA8-8633-4407-BC61-F2CDEBE4D948](https://user-images.githubusercontent.com/55746897/101676272-02a24500-3a6c-11eb-94b1-d44bebd0ab9d.jpeg)

** Пожалуйста, заполните следующую информацию: **
  - Версия: 1.6.6b build 3375, 3386, 3407

**Comment by sprut666666** [comment]
проверить на актуальной сборке

**Comment by Alxprv** [comment]
В логе кстати ошибка при добавлении устройства:
204/5/Holding/1: Error: Illegal Data Value

Видимо, это к кнопкам относится
