### ISSUE TITLE
TS0121

### ISSUE THREAD

**Issue by apoleshchuk** [sprut/Hub#433]
Address: 842E14FFFE126710/3E24<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_vtscrpmw</li><li>0005_ModelIdentifier: TS0121</li><li>0007_PowerSource: 1</li></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 62</li></ul></li><li>0004_Groups<ul></ul></li><li>0B04_ElectricalMeasurement<ul><li>0505_RmsVoltage: 217</li><li>0508_RmsCurrent: 5803</li><li>050B_ActivePower: 1287</li></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_Unknown: 1</li><li>8002_Unknown: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Dec 10 22:41:33 MSK 2020
Телеграм: @apoleshchuk
Девайс в каталоге: нет
Покупал [тут](https://aliexpress.ru/item/4001118546894.html)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/lonsonho-umnaa-rozetka-tuya-zigbee-eu-16a
