### ISSUE TITLE
TS0011 выключатель одноклавишный

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#437]
** Подробное описание ошибки **
Устройство TS0011 (_TYZB01_xfpdrwvc) в SH определяется как кран
** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
Установить SH 1.6.6 
Привязать устройство

** Ожидаемое поведение **
Чтобы определился как выключатель 
** Скриншоты/ Логи **

** Пожалуйста, заполните следующую информацию: **
  - Версия: SH 1.6.6 Ревизия: 3407
Дата сборки: 08.12.2020, 20:15:19

** Дополнительные материалы **

**Comment by sprut666666** [comment]
в след сборке
