### ISSUE TITLE
Реле lumi.relay.c2acn01 не отвечает каждый час (красная запись в логе)

### ISSUE THREAD

**Issue by SitkoAleksandr** [sprut/Hub#438]
Реле lumi.relay.c2acn01 не отвечает каждый час (красная запись в логе)

Каждый час в логе повторяющееся событие:
**[25] Подсветка - Кухня 00158D0003CB8E10/B779, Не отвечает**
Реле lumi.relay.c2acn01, firmware 35
Ревизия  sh: 3407 (такое поведение было не всех ревизиях)
Логи приложил.
На карте реле не краснеет, все время зеленое.

[logs (1).zip](https://github.com/sprut/Hub/files/5688197/logs.1.zip)
![no respone](https://user-images.githubusercontent.com/63845415/102071468-8fa12180-3e11-11eb-87dc-ff7e7d53aafb.png)

**Comment by sprut666666** [comment]
проверь на последней сборке
