### ISSUE TITLE
Добавьте кнопки Aqara

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#44]
Модель MCCGQ11LM.
В Спрут хаб они заходят. Но действия которые можно создать на нажатие не работают. Другие кнопки Aqara (другая модель) работают прекрасно, так что дело не в кривых руках.

Привожу фото кнопки, коробки и что есть в Спрутхабе.

![image](https://user-images.githubusercontent.com/52490000/69026589-8e1de380-09dc-11ea-8aa8-a91b2b933e1e.png)

![image](https://user-images.githubusercontent.com/52490000/69026619-ac83df00-09dc-11ea-9561-1afab3c2e7a7.png)

![image](https://user-images.githubusercontent.com/52490000/69026715-0a182b80-09dd-11ea-86d2-5d7c02938c49.png)

![image](https://user-images.githubusercontent.com/52490000/69026743-3a5fca00-09dd-11ea-8068-548fea5c077e.png)

![image](https://user-images.githubusercontent.com/52490000/69026785-7004b300-09dd-11ea-8e67-2e3079b32739.png)

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

**Comment by Popov2006** [comment]
возможно коробку не ту схватил, перепроверю, уж больно коробка от датчика влажности похожа :)

**Comment by diamond5170** [comment]
Что именно не работает? Проверял ли в хомките одиночное и двойное нажатие? Если иконка при нажатии подпрыгивает, значит работает.
Долго нажатия у кнопки нет, но есть "потрясти", позже возможно добавлю. А пока жду тестов.

**Comment by Popov2006** [comment]
На эти кнопки нет никакой реакции вообще.  Вот что в контроллерах. Наш подопечный на конце 7DD. В таком виде он и пол года назад заходил. Все что ему прописывается при одиночном нажатии не работает. Для примера выше другая Акаровская кнопка, которая работает.
Я второй пример не зря привел.
![image](https://user-images.githubusercontent.com/52490000/69118608-28495e80-0aa5-11ea-8825-07757624481a.png)

**Comment by diamond5170** [comment]
Проверить в версии 1.4.0, когда она выйдет. Возможно исправлено. Для тестов удалить аксессуар.
