### ISSUE TITLE
AirQMon

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Hub#441]
Address: 00124B001ED0F59B/E5FC<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: SLS</li><li>0005_ModelIdentifier: AirQMon</li><li>0006_DateCode: 2020-06-22</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2020-06-22</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 1</li><li>0001_PersistentMemoryWrites: 0</li><li>0100_MacRxBcast: 0</li><li>0101_MacTxBcast: 0</li><li>0102_MacRxUcast: 0</li><li>0103_MacTxUcast: 0</li><li>0104_MacTxUcastRetry: 0</li><li>0105_MacTxUcastFail: 0</li><li>0106_ApsRxBcast: 0</li><li>0107_ApsTxBcast: 1</li><li>0108_ApsRxUcast: 0</li><li>0109_ApsTxUcastSuccess: 10</li><li>010A_ApsTxUcastRetry: 0</li><li>010B_ApsTxUcastFail: 0</li><li>010C_RouteDiscInitiated: 0</li><li>010D_NeighborAdded: 0</li><li>010E_NeighborRemoved: 0</li><li>010F_NeighborStale: 0</li><li>0110_JoinIndication: 0</li><li>0111_ChildMoved: 0</li><li>0112_NwkFcFailure: 0</li><li>0113_ApsFcFailure: 0</li><li>0114_ApsUnauthorizedKey: 0</li><li>0115_NwkDecryptFailures: 0</li><li>0116_ApsDecryptFailures: 0</li><li>0117_PacketBufferAllocateFailures: 0</li><li>0118_RelayedUcast: 0</li><li>0119_PhyToMacQueueLimitReached: 0</li><li>011A_PacketValidateDropCount: 0</li><li>011B_AverageMacRetryPerApsMessageSent: 0</li><li>011C_LastMessageLqi: 187</li><li>011D_LastMessageRssi: -16</li></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: A</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: SLS</li><li>0005_ModelIdentifier: AirQMon</li><li>0006_DateCode: 2020-06-22</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2020-06-22</li></ul></li><li>0014_MultistateValueBasic<ul></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 1</li><li>0001_PersistentMemoryWrites: 0</li><li>0100_MacRxBcast: 0</li><li>0101_MacTxBcast: 0</li><li>0102_MacRxUcast: 0</li><li>0103_MacTxUcast: 0</li><li>0104_MacTxUcastRetry: 0</li><li>0105_MacTxUcastFail: 0</li><li>0106_ApsRxBcast: 0</li><li>0107_ApsTxBcast: 1</li><li>0108_ApsRxUcast: 0</li><li>0109_ApsTxUcastSuccess: 19</li><li>010A_ApsTxUcastRetry: 0</li><li>010B_ApsTxUcastFail: 0</li><li>010C_RouteDiscInitiated: 0</li><li>010D_NeighborAdded: 0</li><li>010E_NeighborRemoved: 0</li><li>010F_NeighborStale: 0</li><li>0110_JoinIndication: 0</li><li>0111_ChildMoved: 0</li><li>0112_NwkFcFailure: 0</li><li>0113_ApsFcFailure: 0</li><li>0114_ApsUnauthorizedKey: 0</li><li>0115_NwkDecryptFailures: 0</li><li>0116_ApsDecryptFailures: 0</li><li>0117_PacketBufferAllocateFailures: 0</li><li>0118_RelayedUcast: 0</li><li>0119_PhyToMacQueueLimitReached: 0</li><li>011A_PacketValidateDropCount: 0</li><li>011B_AverageMacRetryPerApsMessageSent: 0</li><li>011C_LastMessageLqi: 187</li><li>011D_LastMessageRssi: -16</li></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: C</li><li>0055_PresentValue: 27.0</li></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: SLS</li><li>0005_ModelIdentifier: AirQMon</li><li>0006_DateCode: 2020-06-22</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 2020-06-22</li></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: </li></ul></li></ul></li><li>Output<ul><li>0014_MultistateValueBasic<ul></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: ppm</li><li>0055_PresentValue: 504.0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>842E14FFFEDB8A76</td><td>3BC8</td><td>Router</td><td>true</td><td>Parent</td><td>95</td><td>UNKNOWN</td><td>2</td></tr><tr><td>04CF8CDF3C789651</td><td>EF92</td><td>Router</td><td>true</td><td>Unknown</td><td>96</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00158D000269A27D</td><td>8FBA</td><td>Router</td><td>true</td><td>Unknown</td><td>23</td><td>UNKNOWN</td><td>255</td></tr><tr><td>000B57FFFE7E348A</td><td>0000</td><td>Coordinator</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00124B001EE8E1BE</td><td>D9F0</td><td>Router</td><td>true</td><td>Unknown</td><td>47</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00124B001F7A9F8C</td><td>C475</td><td>Router</td><td>true</td><td>Unknown</td><td>39</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00158D0002EC276C</td><td>02EB</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00158D0002EC770D</td><td>7D64</td><td>Router</td><td>true</td><td>Unknown</td><td>12</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00158D0003668253</td><td>FEA8</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>3BC8</td></tr><tr><td>ACTIVE</td><td>EF92</td><td>EF92</td></tr><tr><td>DISCOVERY_FAILED</td><td>8FBA</td><td>FFFE</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Dec 15 23:38:37 MSK 2020

Датчик CO2 на базе сенсора SenseAir S8 от [@avenit](https://t.me/avenit)
Аналогичен [Этому датчику.](https://v2.sprut.ai/catalog/item/modkam-datcik-co2-zigbee)
Телеграм: [@GeorgeBennelli](https://t.me/GeorgeBennelli)

**Comment by thaserge** [comment]
Вроде как получилось прикрутить
Ложите в папку custom проверяйте 

<img width="628" alt="image" src="https://user-images.githubusercontent.com/54379060/109369243-61759e80-78a4-11eb-8817-e796911d501c.png">


[SLS-AirQMon.zip](https://github.com/sprut/Hub/files/6053388/SLS-AirQMon.zip)
