### ISSUE TITLE
01MINIZB

### ISSUE THREAD

**Issue by upmkvik** [sprut/Hub#448]
Address: EC1BBDFFFE31F5DE/D0B0<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0004_ManufacturerName: SONOFF</li><li>0005_ModelIdentifier: 01MINIZB</li><li>0006_DateCode: 20200820</li><li>0007_PowerSource: 0</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Dec 22 15:08:17 MSK 2020

Телеграм: @Dr_V1
Девайс в каталоге: Нет
Покупал [тут](https://a.aliexpress.com/_AWVTJl) .

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/itead-sonoff-zb-mini

**Comment by InfinityMe** [comment]
Ране уже был ишью https://github.com/sprut/Hub/issues/332

Статус после восстановления питания:
**Всегда выключено.**
