### ISSUE TITLE
Не удаляется триггер на кнопке

### ISSUE THREAD

**Issue by steepoff** [sprut/Hub#45]
![2019-11-29 21 59 40](https://user-images.githubusercontent.com/42616874/69886577-ac94b080-12f3-11ea-841c-dfe5ec8e716f.jpg)

Не удаляется триггер на кнопке, видимо из-за длинного названия, которое перекрывает слой с крестиком удаления.

MacOS: Safari и в Chrome аналогично

**Comment by diamond5170** [comment]
И зачем вы постоянно комнаты в названия добавляете? :)
По проблеме понятно, поправлю.

**Comment by diamond5170** [comment]
В последней версии нормально?

**Comment by steepoff** [comment]
Да, нормально
