### ISSUE TITLE
SP 120

### ISSUE THREAD

**Issue by wpetrov** [sprut/Hub#450]
Address: 00158D00031E9115/6958<br><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: innr</li><li>0005_ModelIdentifier: SP 120</li><li>0006_DateCode: 20171027-100</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 2.0</li></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 0</li><li>0300_UnitOfMeasure: 0</li><li>0303_SummationFormatting: 42</li><li>0306_MeteringDeviceType: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0B04_ElectricalMeasurement<ul><li>0000_MeasurementType: 0</li><li>0505_RmsVoltage: 0</li><li>0508_RmsCurrent: 0</li><li>050B_ActivePower: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 1</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>0010_OnOffTransitionTime: 0</li></ul></li><li>000A_Time<ul><li>0000_Time: �������	�</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: 0</li><li>0002_CurrentFileVersion: 285474818</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4454</li><li>0008_ImageTypeId: 65535</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table width="100%" border="1"><tbody><tr><td width="35%">Aps Flags</td><td>0</td></tr><tr><td width="35%">Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width="35%">Server Capabilities</td><td>[]</td></tr><tr><td width="35%">Buffer Size</td><td>127</td></tr><tr><td width="35%">Incoming Transfer Size</td><td>80</td></tr><tr><td width="35%">Logical Type</td><td>Router</td></tr><tr><td width="35%">Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width="35%">Manufacturer Code</td><td>4454</td></tr><tr><td width="35%">Out Going Transfer Size</td><td>80</td></tr><tr><td width="35%">Stack Compliance</td><td>0</td></tr></tbody></table><br><b>Power Descriptor</b><br><table width="100%" border="1"><tbody><tr><td width="35%">Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width="35%">Available Power Sources</td><td>[MAINS]</td></tr><tr><td width="35%">Current Power Source</td><td>MAINS</td></tr><tr><td width="35%">Power Level</td><td>FULL</td></tr></tbody></table><br><br><br>Last update: Tue Dec 22 20:45:04 UTC 2020

---

ник в телеграме @wp24wp
Подобный (SP 220) девайс в [каталоге](https://v2.sprut.ai/catalog/item/innr-smart-plug).

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/innr-light-link-smart-plug
