### ISSUE TITLE
TS0601

### ISSUE THREAD

**Issue by Moscowlight** [sprut/Hub#454]
Address: 60A423FFFE9F5B76/4414<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 65</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_aoclfnxz</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE417509</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>125</td><td>UNKNOWN</td><td>0</td></tr><tr><td>BC33ACFFFE17E80F</td><td>0716</td><td>Router</td><td>false</td><td>Sibling</td><td>92</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000B3CFFFEFFDF8C</td><td>0F48</td><td>Router</td><td>false</td><td>Sibling</td><td>88</td><td>UNKNOWN</td><td>15</td></tr><tr><td>086BD7FFFE003D22</td><td>18F2</td><td>Router</td><td>false</td><td>Sibling</td><td>54</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00036678BC</td><td>1E30</td><td>Router</td><td>false</td><td>Sibling</td><td>169</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000B3CFFFEF56FB3</td><td>1EF0</td><td>Router</td><td>false</td><td>Sibling</td><td>255</td><td>UNKNOWN</td><td>15</td></tr><tr><td>BC33ACFFFE17066C</td><td>2F55</td><td>Router</td><td>false</td><td>Sibling</td><td>69</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6FFFFEFD8A7F</td><td>3CB3</td><td>Router</td><td>false</td><td>Sibling</td><td>93</td><td>UNKNOWN</td><td>15</td></tr><tr><td>14B457FFFEC54500</td><td>4BE7</td><td>Router</td><td>false</td><td>Sibling</td><td>119</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0001FA5E01</td><td>5641</td><td>Router</td><td>false</td><td>Sibling</td><td>72</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0002B7DBD2</td><td>60A6</td><td>Router</td><td>false</td><td>Sibling</td><td>77</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000B3CFFFEF931DB</td><td>7760</td><td>Router</td><td>false</td><td>Sibling</td><td>73</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6FFFFEFD6918</td><td>7A11</td><td>Router</td><td>false</td><td>Sibling</td><td>207</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6FFFFEE43B53</td><td>85A3</td><td>Router</td><td>false</td><td>Parent</td><td>238</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000B3CFFFEF6D7E0</td><td>8FB8</td><td>Router</td><td>false</td><td>Sibling</td><td>255</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6FFFFEFA4049</td><td>9107</td><td>Router</td><td>false</td><td>Sibling</td><td>67</td><td>UNKNOWN</td><td>15</td></tr><tr><td>086BD7FFFE004BD6</td><td>9EAB</td><td>Router</td><td>false</td><td>Sibling</td><td>58</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0002B7DA03</td><td>9EC6</td><td>Router</td><td>false</td><td>Sibling</td><td>132</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00024021BE</td><td>A14B</td><td>Router</td><td>false</td><td>Sibling</td><td>137</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000B3CFFFEF929E6</td><td>AD05</td><td>Router</td><td>false</td><td>Sibling</td><td>66</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6FFFFEFC2AF7</td><td>DA5E</td><td>Router</td><td>false</td><td>Sibling</td><td>127</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6FFFFEF338C0</td><td>ED87</td><td>Router</td><td>false</td><td>Sibling</td><td>125</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00028D0A75</td><td>F38B</td><td>Router</td><td>false</td><td>Sibling</td><td>127</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00026A13C3</td><td>F71B</td><td>Router</td><td>false</td><td>Sibling</td><td>93</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>7A11</td><td>7A11</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Dec 24 13:34:43 MSK 2020
Telegram: @MoscowAlex
Модель в каталоге: https://v2.sprut.ai/catalog/item/moeshouse-moes-thermostat-electric-floor-2
Покупал тут: https://aliexpress.ru/item/4001290597011.html?spm=a2g0s.9042311.0.0.274233edAtx1tt

**Comment by pablitocrypto** [comment]
Ждем не дождемся

**Comment by wpetrov** [comment]
тоже жду с нетерпением

**Comment by ElvisPresly** [comment]
Ждем, очень ннада)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-moes-thermostat-electric-floor-2
