### ISSUE TITLE
lumi.switch.b1lacn02

### ISSUE THREAD

**Issue by kukins** [sprut/Hub#463]
Address: 00158D000520D43B/2A8A<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 26</li><li>0003_HwVersion: 54</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.b1lacn02</li><li>0007_PowerSource: 4</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0010_BinaryOutputBasic<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>F000_State: 50331392</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0010_BinaryOutputBasic<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 4<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul></ul></li><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 5<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul></ul></li><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 6<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0012_MultistateInputBasic<ul></ul></li><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 8<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[PRIMARY_TRUST_CENTER]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE, MAINS_POWER]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4151</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Dec 30 19:18:52 MSK 2020

Статус после откл/выкл питания - сохраняет
Куплен - https://aliexpress.ru/item/32974697281.html?spm=a2g0s.9042311.0.0.561a33edoYo3Dh&sku_id=66716578789
Telegram -@kukins2006
Каталог - https://v2.sprut.ai/catalog/item/aqara-wall-switch-d1-single-button

**Comment by sprut666666** [comment]
прошу сделать по инструкции https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device + заголовок поправить
