### ISSUE TITLE
TS0012 - ELARI Smart Switch Double

### ISSUE THREAD

**Issue by riorao** [sprut/Hub#465]
Address: EC1BBDFFFEB63C48/38E9<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 65</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYZB01_elazlrg8</li><li>0005_ModelIdentifier: TS0012</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFE2_Unknown: 19</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>512</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>512</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Jan 06 19:44:15 MSK 2021

19:42:47 | ZigBeeSprut поиск завершён |  
-- | -- | --
19:42:47 | Characteristic(false/true/true/true) = 3.10.12/On/true, value = false, last value = true |  
19:42:47 | <-- link = ZigBee_2/System/On//Discovery, value = false, last value = true |  
19:42:45 | Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS] |  
19:42:45 | Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS] |  
19:42:43 | Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS] |  
19:42:43 | Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS] |  
19:42:43 | EC1BBDFFFEB63C48/38E9 : Device loaded 'TS0012', manufacturer '_TYZB01_elazlrg8', type = 'End Device' |  
19:42:43 | EzspZigbeeKeyEstablishmentHandler [networkId=0, partner=EC1BBDFFFEB63C48, status=EMBER_TC_RESPONDED_TO_KEY_REQUEST] |  
19:42:42 | EC1BBDFFFEB63C48/38E9 : Информация о модели |  
19:42:41 | EC1BBDFFFEB63C48/38E9 : 2/2, Изучение конечной точки 2 |  
19:42:41 | EC1BBDFFFEB63C48/38E9 : 2/1, Изучение конечной точки 1 |  
19:42:41 | EC1BBDFFFEB63C48/38E9 : Изучение возможностей |  
19:42:41 | EC1BBDFFFEB63C48/38E9 : Энергопотребление |  
19:42:40 | EC1BBDFFFEB63C48/38E9 : Базовая информация |  
19:42:40 | EC1BBDFFFEB63C48/38E9: Запущен опрос устройства |  
19:42:39 | Unknown node EC1BBDFFFEB63C48, frame: ZigBeeApsFrame [sourceAddress=38E9/0, destinationAddress=0000/0, profile=0000, cluster=0013, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=DF, payload=86 E9 38 48 3C B6 FE FF BD 1B EC 80, lastHopLqi=164, lastHopRssi=-59] |  
19:42:39 | EzspIncomingSenderEui64Handler [networkId=0, senderEui64=EC1BBDFFFEB63C48] |  
19:42:39 | EzspChildJoinHandler [networkId=0, index=1, joining=true, childId=38E9, childEui64=EC1BBDFFFEB63C48, childType=EMBER_SLEEPY_END_DEVICE] |  
19:42:12 | Characteristic(false/true/true/true) = 3.10.12/On/false, value = true, last value = false |  
19:42:12 | ZigBeeSprut поиск запущен на 60 секунд

при пропадании питания по дефолту ВЫКЛ вне зависимости от изначального состояния каналов.
девайс в каталоге
[https://v2.sprut.ai/catalog/item/elari-smart-switch-double](url)
в телеграмме @RioUrawa

**Comment by riorao** [comment]
Model | TS0012
-- | --
Vendor | TuYa
Description | Smart light switch - 2 gang without neutral wire
Exposes | switch (state), linkquality
Picture |  
White-label | Vrey VR-X712U-0013, TUYATEC GDKES-02TZXD, Earda ESW-2ZAA-EU


Notes #
Rebrand #
Also branded as Yagusmart in the UK, with a version that does not require a neutral wire.

Exposes #
Switch (left endpoint) #
The current state of this switch is in the published state under the state_left property (value is ON or OFF). To control this switch publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"state_left": "ON"}, {"state_left": "OFF"} or {"state_left": "TOGGLE"}. To read the current state of this switch publish a message to topic zigbee2mqtt/FRIENDLY_NAME/get with payload {"state_left": ""}.

Switch (right endpoint) #
The current state of this switch is in the published state under the state_right property (value is ON or OFF). To control this switch publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"state_right": "ON"}, {"state_right": "OFF"} or {"state_right": "TOGGLE"}. To read the current state of this switch publish a message to topic zigbee2mqtt/FRIENDLY_NAME/get with payload {"state_right": ""}.

Linkquality (numeric) #
Link quality (signal strength). Value can be found in the published state on the linkquality property. It’s not possible to read (/get) or write (/set) this value. The minimimal value is 0 and the maximum value is 255. The unit of this value is lqi.

Manual Home Assistant configuration #
Although Home Assistant integration through MQTT discovery is preferred, manual integration is possible with the following configuration:
switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_left }}"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/left/set"

switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_right }}"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/right/set"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
    icon: "mdi:signal"

**Comment by sprut666666** [comment]
опрос не полный, попробуйте повторить спаривание на актуальной версии

**Comment by riorao** [comment]
2021-01-02 | 22:37:47.643 | org.makesimple.SprutHub.Message.a        62  | ZigBee поиск уже запущен
D | 2021-01-02 | 22:38:14.971 | o.m.ZigBee.dongle.cc2531.network.e       844 | b sending as synchronous command.
T | 2021-01-02 | 22:38:14.972 | o.m.ZigBee.dongle.cc2531.network.a.b     234 | Put synchronousCommandListeners listener for 1802 command
T | 2021-01-02 | 22:38:14.973 | o.m.ZigBee.dongle.cc2531.network.a.b     237 | Sending SynchronousCommand Packet: subsystem=null, length=2, apiId=270A, data=FE 02 27 0A 01 01 2F, checksum=2F, error=false 
T | 2021-01-02 | 22:38:14.973 | o.m.ZigBee.dongle.cc2531.network.a.b     151 | ->  b (Packet: subsystem=null, length=2, apiId=270A, data=FE 02 27 0A 01 01 2F, checksum=2F, error=false) 
D | 2021-01-02 | 22:38:14.974 | o.m.ZigBee.dongle.cc2531.network.e       883 | Waiting for synchronous command up to 1000ms till 1609616295974 Unixtime
T | 2021-01-02 | 22:38:14.974 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Length  byte, val is base10=1,base16=01,base2=00000001
T | 2021-01-02 | 22:38:14.975 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION MSB  byte, val is base10=103,base16=67,base2=01100111
T | 2021-01-02 | 22:38:14.975 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION LSB  byte, val is base10=10,base16=0A,base2=00001010
T | 2021-01-02 | 22:38:14.976 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 1  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:14.976 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Checksum  byte, val is base10=108,base16=6C,base2=01101100
T | 2021-01-02 | 22:38:14.976 | o.m.Z.dongle.cc2531.network.packet.e     68  | Response is c -> Packet: subsystem=null, length=1, apiId=670A, data=FE 01 67 0A 00 6C, checksum=6C, error=false
T | 2021-01-02 | 22:38:14.977 | o.m.ZigBee.dongle.cc2531.network.a.b     133 | <-  c (FE 01 67 0A 00 6C)
D | 2021-01-02 | 22:38:14.977 | o.m.ZigBee.dongle.cc2531.network.e       847 | Packet: subsystem=null, length=1, apiId=670A, data=FE 01 67 0A 00 6C, checksum=6C, error=false received as synchronous command.
T | 2021-01-02 | 22:38:14.978 | o.m.ZigBee.dongle.cc2531.network.e       897 | b -> c
D | 2021-01-02 | 22:38:14.978 | o.m.ZigBee.dongle.cc2531.network.e       844 | b sending as synchronous command.
T | 2021-01-02 | 22:38:14.979 | o.m.ZigBee.dongle.cc2531.network.a.b     234 | Put synchronousCommandListeners listener for 1802 command
T | 2021-01-02 | 22:38:14.979 | o.m.ZigBee.dongle.cc2531.network.a.b     237 | Sending SynchronousCommand Packet: subsystem=null, length=2, apiId=270A, data=FE 02 27 0A 02 00 2D, checksum=2D, error=false 
T | 2021-01-02 | 22:38:14.980 | o.m.ZigBee.dongle.cc2531.network.a.b     151 | ->  b (Packet: subsystem=null, length=2, apiId=270A, data=FE 02 27 0A 02 00 2D, checksum=2D, error=false) 
D | 2021-01-02 | 22:38:14.980 | o.m.ZigBee.dongle.cc2531.network.e       883 | Waiting for synchronous command up to 1000ms till 1609616295980 Unixtime
T | 2021-01-02 | 22:38:14.981 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Length  byte, val is base10=1,base16=01,base2=00000001
T | 2021-01-02 | 22:38:14.981 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION MSB  byte, val is base10=103,base16=67,base2=01100111
T | 2021-01-02 | 22:38:14.982 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION LSB  byte, val is base10=10,base16=0A,base2=00001010
T | 2021-01-02 | 22:38:14.982 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 1  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:14.982 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Checksum  byte, val is base10=108,base16=6C,base2=01101100
T | 2021-01-02 | 22:38:14.983 | o.m.Z.dongle.cc2531.network.packet.e     68  | Response is c -> Packet: subsystem=null, length=1, apiId=670A, data=FE 01 67 0A 00 6C, checksum=6C, error=false
T | 2021-01-02 | 22:38:14.983 | o.m.ZigBee.dongle.cc2531.network.a.b     133 | <-  c (FE 01 67 0A 00 6C)
D | 2021-01-02 | 22:38:14.984 | o.m.ZigBee.dongle.cc2531.network.e       847 | Packet: subsystem=null, length=1, apiId=670A, data=FE 01 67 0A 00 6C, checksum=6C, error=false received as synchronous command.
T | 2021-01-02 | 22:38:14.984 | o.m.ZigBee.dongle.cc2531.network.e       897 | b -> c
I | 2021-01-02 | 22:38:14.985 | org.makesimple.ZigBee.m                  1052| --> 0036_ManagementPermitJoiningRequest [0000/0 -> 0000/0, TID=06, permitDuration=0, tcSignificance=false]
I | 2021-01-02 | 22:38:14.985 | org.makesimple.ZigBee.m                  1052| --> 0036_ManagementPermitJoiningRequest [0000/0 -> FFFC/0, TID=07, permitDuration=0, tcSignificance=false]
I | 2021-01-02 | 22:38:14.986 | org.makesimple.SprutHub.Message.a        62  | ZigBee поиск завершён
D | 2021-01-02 | 22:38:14.988 | org.makesimple.ZigBee.transaction.b      106 | addTransactionListener: command=0036_ManagementPermitJoiningRequest [0000/0 -> 0000/0, TID=06, permitDuration=0, tcSignificance=false], outstanding=1
D | 2021-01-02 | 22:38:14.989 | org.makesimple.ZigBee.transaction.b      166 | Send transaction (out 1, queue 1, slots 1/7): ZigBeeTransaction [ queueTime=4, runTime=1, state=DISPATCHED, sendCnt=0, command=0036_ManagementPermitJoiningRequest [0000/0 -> 0000/0, TID=06, permitDuration=0, tcSignificance=false], sleepy=false]
D | 2021-01-02 | 22:38:14.989 | org.makesimple.ZigBee.transaction.b      106 | addTransactionListener: command=0036_ManagementPermitJoiningRequest [0000/0 -> FFFC/0, TID=07, permitDuration=0, tcSignificance=false], outstanding=2
D | 2021-01-02 | 22:38:14.989 | org.makesimple.ZigBee.m                  382 | TX CMD: 0036_ManagementPermitJoiningRequest [0000/0 -> 0000/0, TID=06, permitDuration=0, tcSignificance=false]
D | 2021-01-02 | 22:38:14.990 | org.makesimple.ZigBee.transaction.b      166 | Send transaction (out 2, queue 0, slots 2/7): ZigBeeTransaction [ queueTime=4, runTime=1, state=DISPATCHED, sendCnt=0, command=0036_ManagementPermitJoiningRequest [0000/0 -> FFFC/0, TID=07, permitDuration=0, tcSignificance=false], sleepy=false]
D | 2021-01-02 | 22:38:14.991 | o.m.ZigBee.dongle.cc2531.network.e       844 | b sending as synchronous command.
D | 2021-01-02 | 22:38:14.991 | org.makesimple.ZigBee.m                  382 | TX CMD: 0036_ManagementPermitJoiningRequest [0000/0 -> FFFC/0, TID=07, permitDuration=0, tcSignificance=false]
T | 2021-01-02 | 22:38:14.992 | o.m.ZigBee.dongle.cc2531.network.a.b     234 | Put synchronousCommandListeners listener for 1025 command
D | 2021-01-02 | 22:38:14.992 | o.m.ZigBee.dongle.cc2531.network.e       844 | b sending as synchronous command.
T | 2021-01-02 | 22:38:14.993 | o.m.ZigBee.dongle.cc2531.network.a.b     227 | Waiting for other request to complete
T | 2021-01-02 | 22:38:14.993 | o.m.ZigBee.dongle.cc2531.network.a.b     237 | Sending SynchronousCommand Packet: subsystem=null, length=13, apiId=2401, data=FE 0D 24 01 00 00 00 00 36 00 06 30 1E 03 06 00 00 33, checksum=33, error=false 
T | 2021-01-02 | 22:38:14.994 | o.m.ZigBee.dongle.cc2531.network.a.b     151 | ->  b (Packet: subsystem=null, length=13, apiId=2401, data=FE 0D 24 01 00 00 00 00 36 00 06 30 1E 03 06 00 00 33, checksum=33, error=false) 
D | 2021-01-02 | 22:38:14.994 | o.m.ZigBee.dongle.cc2531.network.e       883 | Waiting for synchronous command up to 1000ms till 1609616295994 Unixtime
T | 2021-01-02 | 22:38:14.995 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Length  byte, val is base10=1,base16=01,base2=00000001
T | 2021-01-02 | 22:38:14.996 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION MSB  byte, val is base10=100,base16=64,base2=01100100
T | 2021-01-02 | 22:38:14.997 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION LSB  byte, val is base10=1,base16=01,base2=00000001
T | 2021-01-02 | 22:38:14.997 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 1  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:14.998 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Checksum  byte, val is base10=100,base16=64,base2=01100100
T | 2021-01-02 | 22:38:14.998 | o.m.Z.dongle.cc2531.network.packet.e     68  | Response is d -> AF_DATA_SRSP(Status=SUCCESS(0))
T | 2021-01-02 | 22:38:14.998 | o.m.ZigBee.dongle.cc2531.network.a.b     133 | <-  d (FE 01 64 01 00 64)
D | 2021-01-02 | 22:38:14.999 | o.m.ZigBee.dongle.cc2531.network.e       847 | AF_DATA_SRSP(Status=SUCCESS(0)) received as synchronous command.
T | 2021-01-02 | 22:38:14.999 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Length  byte, val is base10=3,base16=03,base2=00000011
T | 2021-01-02 | 22:38:14.999 | o.m.ZigBee.dongle.cc2531.network.a.b     234 | Put synchronousCommandListeners listener for 1025 command
T | 2021-01-02 | 22:38:15.000 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION MSB  byte, val is base10=69,base16=45,base2=01000101
T | 2021-01-02 | 22:38:15.000 | o.m.ZigBee.dongle.cc2531.network.a.b     237 | Sending SynchronousCommand Packet: subsystem=null, length=13, apiId=2401, data=FE 0D 24 01 FC FF 00 00 36 00 07 30 1E 03 07 00 00 30, checksum=30, error=false 
T | 2021-01-02 | 22:38:15.000 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION LSB  byte, val is base10=182,base16=B6,base2=10110110
T | 2021-01-02 | 22:38:15.000 | o.m.ZigBee.dongle.cc2531.network.a.b     151 | ->  b (Packet: subsystem=null, length=13, apiId=2401, data=FE 0D 24 01 FC FF 00 00 36 00 07 30 1E 03 07 00 00 30, checksum=30, error=false) 
T | 2021-01-02 | 22:38:15.000 | o.m.ZigBee.dongle.cc2531.network.e       897 | b -> d
T | 2021-01-02 | 22:38:15.000 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 3  byte, val is base10=0,base16=00,base2=00000000
D | 2021-01-02 | 22:38:15.001 | o.m.ZigBee.dongle.cc2531.network.e       883 | Waiting for synchronous command up to 1000ms till 1609616296001 Unixtime
T | 2021-01-02 | 22:38:15.001 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 2  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.001 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 1  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.002 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Checksum  byte, val is base10=240,base16=F0,base2=11110000
T | 2021-01-02 | 22:38:15.002 | o.m.Z.dongle.cc2531.network.packet.e     68  | Response is ZToolPacket -> Packet: subsystem=null, length=3, apiId=45B6, data=FE 03 45 B6 00 00 00 F0, checksum=F0, error=false
T | 2021-01-02 | 22:38:15.003 | o.m.ZigBee.dongle.cc2531.network.a.b     127 | <-- ZToolPacket (FE 03 45 B6 00 00 00 F0)
D | 2021-01-02 | 22:38:15.003 | o.m.ZigBee.dongle.cc2531.network.a.b     358 | Received Async Cmd: Packet: subsystem=null, length=3, apiId=45B6, data=FE 03 45 B6 00 00 00 F0, checksum=F0, error=false
D | 2021-01-02 | 22:38:15.003 | org.makesimple.ZigBee.dongle.cc2531.a    364 | Packet: subsystem=null, length=3, apiId=45B6, data=FE 03 45 B6 00 00 00 F0, checksum=F0, error=false
D | 2021-01-02 | 22:38:15.004 | org.makesimple.ZigBee.m                  564 | RX APS: ZigBeeApsFrame [sourceAddress=0000/0, destinationAddress=0000/0, profile=0000, cluster=8036, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=--, payload=00 00, lastHopLqi=-1, lastHopRssi=-1]
T | 2021-01-02 | 22:38:15.005 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Length  byte, val is base10=10,base16=0A,base2=00001010
D | 2021-01-02 | 22:38:15.005 | org.makesimple.ZigBee.transaction.b      112 | removeTransactionListener: command=0036_ManagementPermitJoiningRequest [0000/0 -> 0000/0, TID=06, permitDuration=0, tcSignificance=false], outstanding=1
I | 2021-01-02 | 22:38:15.005 | o.m.SprutHub.Controllers.ZigBee.c        1817| <-- 8036_ManagementPermitJoiningResponse [0000/0 -> 0000/0, TID=00, status=SUCCESS]
T | 2021-01-02 | 22:38:15.006 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION MSB  byte, val is base10=69,base16=45,base2=01000101
T | 2021-01-02 | 22:38:15.006 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION LSB  byte, val is base10=255,base16=FF,base2=11111111
T | 2021-01-02 | 22:38:15.007 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 10  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.007 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 9  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.008 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 8  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.008 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 7  byte, val is base10=54,base16=36,base2=00110110
T | 2021-01-02 | 22:38:15.008 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 6  byte, val is base10=128,base16=80,base2=10000000
T | 2021-01-02 | 22:38:15.009 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 5  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.009 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 4  byte, val is base10=6,base16=06,base2=00000110
T | 2021-01-02 | 22:38:15.010 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 3  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.010 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 2  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.010 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 1  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.011 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Checksum  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.011 | o.m.Z.dongle.cc2531.network.packet.e     68  | Response is ZToolPacket -> Packet: subsystem=null, length=10, apiId=45FF, data=FE 0A 45 FF 00 00 00 36 80 00 06 00 00 00 00, checksum=00, error=false
T | 2021-01-02 | 22:38:15.011 | o.m.ZigBee.dongle.cc2531.network.a.b     127 | <-- ZToolPacket (FE 0A 45 FF 00 00 00 36 80 00 06 00 00 00 00)
D | 2021-01-02 | 22:38:15.011 | o.m.ZigBee.dongle.cc2531.network.a.b     358 | Received Async Cmd: Packet: subsystem=null, length=10, apiId=45FF, data=FE 0A 45 FF 00 00 00 36 80 00 06 00 00 00 00, checksum=00, error=false
D | 2021-01-02 | 22:38:15.012 | org.makesimple.ZigBee.dongle.cc2531.a    364 | Packet: subsystem=null, length=10, apiId=45FF, data=FE 0A 45 FF 00 00 00 36 80 00 06 00 00 00 00, checksum=00, error=false
T | 2021-01-02 | 22:38:15.012 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Length  byte, val is base10=1,base16=01,base2=00000001
T | 2021-01-02 | 22:38:15.012 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION MSB  byte, val is base10=100,base16=64,base2=01100100
T | 2021-01-02 | 22:38:15.013 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read API PROFILE_ID_HOME_AUTOMATION LSB  byte, val is base10=1,base16=01,base2=00000001
T | 2021-01-02 | 22:38:15.013 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Remaining bytes 1  byte, val is base10=0,base16=00,base2=00000000
T | 2021-01-02 | 22:38:15.013 | o.m.Z.dongle.cc2531.network.packet.f     234 | Read Checksum  byte, val is base10=100,base16=64,base2=01100100
T | 2021-01-02 | 22:38:15.014 | o.m.Z.dongle.cc2531.network.packet.e     68  | Response is d -> AF_DATA_SRSP(Status=SUCCESS(0))
T | 2021-01-02 | 22:38:15.014 | o.m.ZigBee.dongle.cc2531.network.a.b     133 | <-  d (FE 01 64 01 00 64)
D | 2021-01-02 | 22:38:15.014 | o.m.ZigBee.dongle.cc2531.network.e       847 | AF_DATA_SRSP(Status=SUCCESS(0)) received as synchronous command.
T | 2021-01-02 | 22:38:15.015 | o.m.ZigBee.dongle.cc2531.network.e       897 | b -> d
D | 2021-01-02 | 22:38:29.991 | org.makesimple.ZigBee.transaction.b      112 | removeTransactionListener: command=0036_ManagementPermitJoiningRequest [0000/0 -> FFFC/0, TID=07, permitDuration=0, tcSignificance=false], outstanding=0
I | 2021-01-02 | 22:41:24.779 | org.makesimple.Utils.UtilsFile           228 | File: /home/makesimple/.SprutHub/spruthub.log

**Comment by riorao** [comment]
06:15:12 | EC1BBDFFFEB63C48/A442 : Базовая информация - Нет ответа |  
-- | -- | --
06:15:12 | Transaction terminated (Timeout): 0002_NodeDescriptorRequest [0000/0 -> A442/0, TID=1F, nwkAddrOfInterest=A442], sleepy |  
06:15:09 | <-- 8036_ManagementPermitJoiningResponse [0000/0 -> 0000/0, TID=00, status=SUCCESS] |  
06:15:09 | Characteristic(false/true/true/true) = 3.10.12/On/true, value = false, last value = true |  
06:15:09 | ZigBee поиск завершён |  
06:15:09 | <-- link = ZigBee_1/System/On//Discovery, value = false, last value = true |  
06:15:09 | --> 0036_ManagementPermitJoiningRequest [0000/0 -> FFFC/0, TID=21, permitDuration=0, tcSignificance=false] |  
06:15:09 | --> 0036_ManagementPermitJoiningRequest [0000/0 -> 0000/0, TID=20, permitDuration=0, tcSignificance=false] |  
06:14:50 | <-- 000A_ReportAttributesCommand [0000_Basic: A442/1 -> 0000/1, TID=01, Input, reports=[[0001_ApplicationVersion: value=65, type=UNSIGNED_8_BIT_INTEGER], [FFE2_Unknown: value=19, type=UNSIGNED_8_BIT_INTEGER]]] |  
06:14:45 | <-- 000A_ReportAttributesCommand [0000_Basic: A442/1 -> 0000/1, TID=00, Input, reports=[[0001_ApplicationVersion: value=255, type=UNSIGNED_8_BIT_INTEGER], [FFE2_Unknown: value=19, type=UNSIGNED_8_BIT_INTEGER]]] |  
06:14:42 | <-- 8002_NodeDescriptorResponse [A442/0 -> 0000/0, TID=A4, status=SUCCESS, nwkAddrOfInterest=A442, nodeDescriptor=NodeDescriptor [apsFlags=0, bufferSize=82, complexDescriptorAvailable=false, manufacturerCode=1002, logicalType=End Device, serverCapabilities=[], incomingTransferSize=512, outgoingTransferSize=512, userDescriptorAvailable=false, frequencyBands=[FREQ_2400_MHZ], macCapabilities=[REDUCED_FUNCTION_DEVICE], extendedEndpointListAvailable=false, extendedSimpleDescriptorListAvailable=false, stackCompliance=22]] |  
06:14:42 | --> 0002_NodeDescriptorRequest [0000/0 -> A442/0, TID=1F, nwkAddrOfInterest=A442] |  
06:14:42 | EC1BBDFFFEB63C48/A442: Запущен опрос устройства |  
06:14:41 | <-- 0013_DeviceAnnounce [A442/0 -> 0000/0, TID=A4, nwkAddrOfInterest=A442, ieeeAddr=EC1BBDFFFEB63C48, capability=80] |  
06:14:41 | Unknown node A442, frame: ZigBeeApsFrame [sourceAddress=A442/0, destinationAddress=0000/0, profile=0000, cluster=0013, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=--, payload=A4 42 A4 48 3C B6 FE FF BD 1B EC 80, lastHopLqi=-1, lastHopRssi=-1] |  
06:14:09 | <-- 8036_ManagementPermitJoiningResponse [0000/0 -> 0000/0, TID=00, status=SUCCESS] |  
06:14:09 | --> 0036_ManagementPermitJoiningRequest [0000/0 -> FFFC/0, TID=1E, permitDuration=60, tcSignificance=false] |  
06:14:09 | --> 0036_ManagementPermitJoiningRequest [0000/0 -> 0000/0, TID=1D, permitDuration=60, tcSignificance=false] |  
06:14:09 | ZigBee поиск запущен на 60 секунд |  
06:14:09 | <-- link = ZigBee_1/System/On//Discovery, value = true, last value = true |  
06:14:09 | --> link = ZigBee_1/System/On//Discovery, value = true, last value = false |  
06:14:09 | Characteristic(true/true/true/true) = 3.10.12/On/false, value = true, last value = false

[spruthub.log](https://github.com/sprut/Hub/files/5761154/spruthub.log)
[stdout.log](https://github.com/sprut/Hub/files/5761156/stdout.log)
