### ISSUE TITLE
Добавление замка Danalock V3 Zigbee (V3-BTZB) 

### ISSUE THREAD

**Issue by elukyan** [sprut/Hub#469]
https://danalock.com/products/danalock-v3-smart-lock/

Telegram: elukyan

Address: 000B57FFFE59D011/7550<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 4</li><li>0004_ManufacturerName: Danalock</li><li>0005_ModelIdentifier: V3-BTZB</li><li>0006_DateCode: 20190806</li><li>0007_PowerSource: 3</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 14400</li><li>0001_LongPollInterval: 20</li><li>0002_ShortPollInterval: 2</li><li>0003_FastPollTimeout: 40</li></ul></li><li>0001_PowerConfiguration<ul><li>0021_BatteryPercentageRemaining: 192</li><li>0031_BatterySize: 8</li><li>0033_BatteryQuantity: 4</li><li>0035_BatteryAlarmMask: 255</li><li>003A_BatteryPercentageMinThreshold: 10</li><li>003B_BatteryPercentageThreshold1: 20</li><li>003C_BatteryPercentageThreshold2: 30</li><li>003D_BatteryPercentageThreshold3: 40</li><li>003E_BatteryAlarmState: 0</li></ul></li><li>0101_DoorLock<ul><li>0000_LockState: 1</li><li>0001_LockType: 0</li><li>0002_ActuatorEnabled: false</li><li>0010_NumLockRecordsSupported: 17918</li><li>0011_NumTotalUsersSupported: 0</li><li>0012_NumPinUsersSupported: 0</li><li>0013_NumRfidUsersSupported: 0</li><li>0014_NumWeekdaySchedulesSupportedPerUser: 0</li><li>0015_NumYeardaySchedulesSupportedPerUser: 0</li><li>0016_NumHolidaySchedulesSupportedPerUser: 0</li><li>0020_EnableLogging: true</li><li>0025_OperatingMode: 0</li><li>0034_ZigbeeSecurityLevel: 0</li><li>0040_AlarmMask: 65535</li><li>0042_RfOperationEventMask: 65535</li><li>0043_ManualOperationEventMask: 65535</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>011B_AverageMacRetryPerApsMessageSent: 2</li><li>011C_LastMessageLqi: 208</li><li>011D_LastMessageRssi: -48</li></ul></li><li>0009_Alarms<ul></ul></li></ul></li><li>Output<ul><li>0B05_Diagnostics<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 286D970002042A09</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 14</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4444</li><li>0008_ImageTypeId: 3</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>300</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4444</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>300</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jan 04 19:29:57 MSK 2021

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/danalock-v3-smart-lock-zigbee

**Comment by elukyan** [comment]
> https://v2.sprut.ai/catalog/item/danalock-v3-smart-lock-zigbee

![2021-01-09](https://user-images.githubusercontent.com/58940876/104090492-39949200-5288-11eb-8138-8d7fba9c24c2.png)

**Comment by stas3133283** [comment]
Ждём с нетерпением

**Comment by stas3133283** [comment]
Address: 588E81FFFE43D383/5491

Structure
	•	Endpoint 1 (DOOR_LOCK)
	◦	Input
	▪	0000_Basic
	▪	0000_ZCLVersion: 3
	▪	0001_ApplicationVersion: 3
	▪	0003_HWVersion: 5
	▪	0004_ManufacturerName: Danalock
	▪	0005_ModelIdentifier: V3-BTZBE
	▪	0006_DateCode: 20210428
	▪	0007_PowerSource: 3
	▪	0020_PollControl
	▪	0000_CheckinInterval: 14400
	▪	0001_LongPollInterval: 20
	▪	0002_ShortPollInterval: 2
	▪	0003_FastPollTimeout: 40
	▪	0001_PowerConfiguration
	▪	0021_BatteryPercentageRemaining: 178
	▪	0035_BatteryAlarmMask: 255
	▪	003E_BatteryAlarmState: 0
	▪	0101_DoorLock
	▪	0000_LockState: 1
	▪	0001_LockType: 0
	▪	0002_ActuatorEnabled: false
	▪	0010_NumLockRecordsSupported: 0
	▪	0011_NumTotalUsersSupported: 20
	▪	0012_NumPINUsersSupported: 20
	▪	0013_NumRFIDUsersSupported: 0
	▪	0014_NumWeekdaySchedulesSupportedPerUser: 0
	▪	0015_NumYeardaySchedulesSupportedPerUser: 0
	▪	0016_NumHolidaySchedulesSupportedPerUser: 0
	▪	0017_MaxPINLength: 11
	▪	0018_MinPINLength: 4
	▪	0030_WrongCodeEntryLimit: 5
	▪	0031_UserCodeTemporaryDisableTime: 120
	▪	0032_SendPINOverTheAir: true
	▪	0033_RequirePINForRFOperation: false
	▪	0034_ZigBeeSecurityLevel: 0
	▪	0040_AlarmMask: 65535
	▪	0041_KeypadOperationEventMask: 65535
	▪	0042_RFOperationEventMask: 65535
	▪	0043_ManualOperationEventMask: 65535
	▪	0003_Identify
	▪	0000_IdentifyTime: 178
	▪	0B05_Diagnostics
	▪	0000_NumberOfResets: 10
	▪	011C_LastMessageLQI: 236
	▪	011D_LastMessageRSSI: -41
	▪	0009_Alarms
	▪	0000_AlarmCount: 0
	▪	FCFF_ManufacturerSpecific
	▪	
	◦	Output
	▪	0019_OtaUpgrade
	▪	0000_UpgradeServerID: FFFFFFFFFFFFFFFF
	▪	0001_FileOffset: -1
	▪	0002_CurrentFileVersion: 285212692
	▪	0003_CurrentZigBeeStackVersion: 2
	▪	0004_DownloadedFileVersion: -1
	▪	0005_DownloadedZigBeeStackVersion: 65535
	▪	0006_ImageUpgradeStatus: 0
	▪	0007_ManufacturerID: 4444
	▪	0008_ImageTypeID: 65535
	▪	0009_MinimumBlockRequestPeriod: 0
	▪	000A_ImageStamp:


Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags
0
Frequency Bands
[FREQ_2400_MHZ]
Server Capabilities
[]
Buffer Size
82
Incoming Transfer Size
82
Logical Type
End Device
Mac Capabilities
[REDUCED_FUNCTION_DEVICE]
Manufacturer Code
4444
Out Going Transfer Size
82
Stack Compliance
22

Power Descriptor
Current Power Mode
RECEIVER_ON_PERIODICALLY
Available Power Sources
[DISPOSABLE_BATTERY]
Current Power Source
DISPOSABLE_BATTERY
Power Level
FULL



Last update: Fri Oct 29 10:17:18 MSK 2021
