### ISSUE TITLE
Нептун нет оповещений о протечке

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#47]
** Подробное описание ошибки **
Датчики протекчки нептун не присылают оповещения о протечке в Homekit.

** Как воспроизвести ? **
Добавляемляем учетную запись нептун в SH.
Добавляем хаб в приложение Дом или SprutHome
Иницируем протечку.

** Ожидаемое поведение **
Уведомления о протечке в Homekit

** Пожалуйста, заполните следующую информацию: **
  - Версия SH: SprutHub 1.4.0b
 - Версия  iOS 12.4.3

**Comment by sprut666666** [comment]
Время обновления попробуй поменять в настройках

**Comment by Ziracul** [comment]
Стоит 6 какой рекомендуется ?

**Comment by diamond5170** [comment]
Проверить снова.

**Comment by diamond5170** [comment]
Закрываю, т.к. нет ответа.
