### ISSUE TITLE
010F Фибаро кнопка

### ISSUE THREAD

**Issue by sotidis** [sprut/Hub#473]
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>15</td></tr><tr><td width=35%>Manufacturer Id</td><td>010F</td></tr><tr><td width=35%>Device Type</td><td>0F01</td></tr><tr><td width=35%>Device Id</td><td>1000</td></tr><tr><td width=35%>App Version</td><td>3.2</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Wall Controller</td></tr><tr><td width=35%>Specific Class</td><td>Basic Wall Controller</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>1</td></tr><tr><td>2</td><td> On/Off</td><td>[]</td><td>5</td></tr><tr><td>3</td><td> Dimmer</td><td>[]</td><td>5</td></tr><tr><td>4</td><td> Alarm</td><td>[]</td><td>5</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 DeviceResetLocally</li><li>V1 Basic</li><li>V2 WakeUp<ul><li>Interval: 18000</li><li>Default: 0</li><li>Min: 0</li><li>Max: 64800</li><li>Step: 3600</li></ul></li><li>V1 NoOperation</li><li>V1 ZWavePlusInfo</li><li>V5 Alarm<ul><li>Burglar</li></ul></li><li>V3 MultiChannelAssociation</li><li>V1 SensorAlarm<ul><li>General: 0</li></ul></li><li>V1 FirmwareUpdateMD</li><li>V2 Version</li><li>V2 ManufacturerSpecific</li><li>V1 Battery<ul><li>Level: 90</li><li>Low: false</li></ul></li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 AssociationGRPInfo</li><li>V1 Security</li><li>V1 CRC16Encap</li><li>V1 Configuration</li><li>V1 SwitchMultiLevel<ul></ul></li><li>V2 Association</li><li>V3 CentralScene</li></ul></li></ul><br>Last update: Thu Jan 07 10:57:00 CET 2021

телеграм @grek21

**Comment by MakeSimpleOrg** [comment]
r4889
