### ISSUE TITLE
TRADFRI Signal Repeater

### ISSUE THREAD

**Issue by deemerby** [sprut/Hub#477]
Address: 680AE2FFFE1C5C65/D7AE<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 33</li><li>0002_StackVersion: 98</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI Signal Repeater</li><li>0007_PowerSource: 1</li><li>0008_GenericDeviceClass: 0</li><li>4000_SwBuildId: 2.2.005</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 0</li><li>0100_MacRxBcast: 0</li><li>0101_MacTxBcast: 0</li><li>0106_ApsRxBcast: 0</li><li>0107_ApsTxBcast: 0</li><li>011C_LastMessageLqi: 255</li><li>011D_LastMessageRssi: -26</li></ul></li><li>0009_Alarms<ul></ul></li></ul></li><li>Output<ul><li>0020_PollControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 570447409</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4476</li><li>0008_ImageTypeId: 4353</li></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jan 08 11:53:08 MSK 2021

Покупал тут: https://www.ikea.lt/ru/products/gostinaya/osveschenie/aksessuary-dlya-elektronnogo-oborudovaniya/tradfri-povtoritel-usilitel-signala-art-10400408
Является частью комплекта штор: https://github.com/sprut/Hub/issues/476
в каталоге отсутсвует.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ikea-tradfri-signal-repeater

**Comment by ryazanof** [comment]
Sprut.hub 1.7.1b Ревизия: 5521 Дата сборки: 14.08.2021, 00:10:26
После добавления init=Удаленный
