### ISSUE TITLE
работа ламп объединенных в виртуальное устройство

### ISSUE THREAD

**Issue by mrgarik** [sprut/Hub#478]
CX v.3730 есть три лампочки lumi.light.aqcn02 (https://v2.sprut.ai/catalog/item/akara-light-bulb). объединены в одну виртуальную лампу. есть две проблемы:
1. автоматизация по времени (максимальная яркость днем\минимальная ночью). при переходе времени в тусклый режим, сначала зажигается ярко, и только потом опускает яркость. автоматизация в НР ({"Brightness": 1, "ColorTemperature": 300, "On": true}) яркость подаю первым параметром. Отсылая без параметра On ({"Brightness": 1, "ColorTemperature": 300}) проблема остается актуальной.

2. яркий\тусклый свет на разных клавишах выключателя. управляется виртуальная лампа. при этом переоднически одна из реальных ламп не синхронно включает яркость, т.к. две тусклые - одна яркая, или наоборот.
Воспроизводил через инжекты в HP:
подал bri: 1, одна лампочка осталась яркой, и повторный инжект ее в тусклую не переводит. Ощущение, что она уже думает что она на минимальной яркости

**Comment by sprut666666** [comment]
проверить на актуальной сборке, если проблема повторится переоткрыть
