### ISSUE TITLE
ZLL-ColorTempera

### ISSUE THREAD

**Issue by oleg77s** [sprut/Hub#482]
Address: 00158D0001CC6A88/E430<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0004_ManufacturerName: Trust International B.V.</li><li>0005_ModelIdentifier: ZLL-ColorTempera</li><li>0007_PowerSource: 1</li></ul></li><li>0300_ColorControl<ul><li>0007_ColorTemperature: 370</li><li>400B_ColorTemperatureMin: 153</li><li>400C_ColorTemperatureMax: 454</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>FFFF_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>80</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4151</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>80</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jan 09 19:51:54 MSK 2021
Телеграм: OLEГ
Ссылка на устройство в каталоге https://v2.sprut.ai/catalog/item/trust-zigbee-tunable-led-bulb-e27
Магазин https://www.trust.com/ru/product/71156-zigbee-tunable-led-bulb-zled-tune9

**Comment by oleg77s** [comment]
это лампа Trust Zigbee Tunable LED Bulb ZLED-TUNE9

**Comment by sprut666666** [comment]
Что тут не работает ?

**Comment by oleg77s** [comment]
работает, только в каталоге не отмечено, что работает на платформе спрутхаб

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/trust-zigbee-tunable-led-bulb-e27
