### ISSUE TITLE
ZLL-ExtendedColo

### ISSUE THREAD

**Issue by oleg77s** [sprut/Hub#485]
Address: 00158D00011EB6E2/2C4F<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>FFFF_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>80</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4151</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>80</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jan 10 16:12:31 MSK 2021
ссылка на каталог: https://v2.sprut.ai/catalog/item/trust-light-bulb-2
магазин: https://www.trust.com/ru/product/71145-zigbee-rgb-tunable-led-bulb-zled-rgb9

В #issue #128  уже эта тема поднималась

2C4F/00158D00011EB6E2 |   | Работает |   |   | Изучение возможностей
И на этом все...
17:04:41 | ZigBee поиск уже остановлен |  
**17:04:41 | 00158D00011EB6E2/2C4F : Информация о модели - Нет ответа |**  
17:04:41 | Transaction terminated (Timeout): 0000_ReadAttributesCommand [0000_Basic: 0000/0 -> 2C4F/1, TID=1A, Input, identifiers=[0001_ApplicationVersion, 0005_ModelIdentifier, 0004_ManufacturerName, 0007_PowerSource, 4000_SwBuildId, 0003_HwVersion]] |  
17:04:26 | 00158D00011EB6E2/2C4F: Запущен опрос устройства |  
17:04:18 | Update mesh: step 1 |  
16:12:32 | ZigBee поиск завершён |  
**16:12:31 | 00158D00011EB6E2/2C4F : Информация о модели - Нет ответа |**  
16:12:31 | Transaction terminated (Timeout): 0000_ReadAttributesCommand [0000_Basic: 0000/0 -> 2C4F/1, TID=14, Input, identifiers=[0001_ApplicationVersion, 0005_ModelIdentifier, 0004_ManufacturerName, 0007_PowerSource, 4000_SwBuildId, 0003_HwVersion]] |  
16:12:16 | 00158D00011EB6E2/2C4F : 2/2, Изучение конечной точки 1 |  
16:12:16 | 00158D00011EB6E2/2C4F : 2/1, Изучение конечной точки 2 |  
16:12:16 | 00158D00011EB6E2/2C4F : Изучение возможностей |  
16:12:16 | 00158D00011EB6E2/2C4F : Энергопотребление |  
16:12:16 | 00158D00011EB6E2/2C4F : Базовая информация |  
16:12:15 | 00158D00011EB6E2/2C4F: Запущен опрос устройства |  
16:12:14 | 2C4F: Node has left from network. |  
16:12:14 | Unknown node 00158D00011EB6E2, frame: ZigBeeApsFrame [sourceAddress=2C4F/0, destinationAddress=0000/0, profile=0000, cluster=0013, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=FB, payload=04 4F 2C E2 B6 1E 01 00 8D 15 00 8E, lastHopLqi=140, lastHopRssi=-65] |  
16:11:46 | ZigBee поиск запущен на 60 секунд

Опрос до конца не доходит, пробовал несколько раз; в deconz и Hue Bridge залетает без проблем

**Comment by sprut666666** [comment]
удалить устройство из контроллера и попробовать снова

**Comment by oleg77s** [comment]
удалял несколько раз ранее и сейчас удалил (версия хаба крайняя, сегодняшняя), но опрос так и не приходит до конца, изучает возможности...

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/trust-light-bulb-2
