### ISSUE TITLE
RWL020

### ISSUE THREAD

**Issue by aleksandryants** [sprut/Hub#487]
Philips Hue dimmer switch RWL020
На сайте нету така как снят с производства. Новая модель: (RWL021)

Address: 0017880110489A7D/85B2<br><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: RWL020</li><li>0006_DateCode: 20150918</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 5.45.1.16265</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: RWL020</li><li>0006_DateCode: 20150918</li><li>0007_PowerSource: 3</li></ul></li><li>FC00_ManufacturerSpecific<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0003_Identify<ul></ul></li><li>000F_BinaryInputBasic<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 1107312521</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4107</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>71</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>45</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>45</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, RECHARGABLE_BATTERY, MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jan 11 00:54:25 MSK 2021

**Comment by aleksandryants** [comment]
Изменяюсь поставил не правильный лейбл 
это signee

**Comment by Batyushin** [comment]
А это точно ZWave?

**Comment by aleksandryants** [comment]
Сори не тот таг поставил не знаю как поменять. Это zigbee

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/philips-hue-dimmer-switch
