### ISSUE TITLE
zw100

### ISSUE THREAD

**Issue by steepoff** [sprut/Hub#49]
В шаблоне /mnt/data/makesimple/.SprutHub/data/Templates/ZWave/AEON\ Labs/ZW100.json не хватает еще одного типа, из-за этого не определяется устройство, нужно строчку
"modelId": "0002:0064,0102:0064,0202:0064",
заменить на 
"modelId": "0002:0064,0102:0064,0202:0064,1A02:0064",

**Comment by diamond5170** [comment]
Добавил, будет в следующей версии.

**Comment by steepoff** [comment]
Добавьте еще влажность, выделил жирным: 
{
  "name": "Движение",
  "manufacturer": "AEON Labs",
  "model": "ZW100",
  "manufacturerId": "0086",
  "modelId": "0002:0064,0102:0064,0202:0064,1A02:0064",
  "services": [
    {
      "name": "Движение",
      "type": "MotionSensor",
      "characteristics": [
        {
          "type": "MotionDetected",
          "link": "Boolean/0/SensorBinary/Motion"
        }
      ]
    },
    {
      "name": "Температура",
      "type": "TemperatureSensor",
      "characteristics": [
        {
          "type": "CurrentTemperature",
          "link": "Float/0/SensorMultiLevel/Temperature"
        }
      ]
    },
    **{
      "name": "Влажность",
      "type": "HumiditySensor",
      "characteristics": [
        {
          "type": "CurrentRelativeHumidity",
          "link": "Float/0/SensorMultiLevel/RelativeHumidity"
        }
      ]
    },**
    {
      "name": "Освещенность",
      "type": "LightSensor",
      "characteristics": [
        {
          "type": "CurrentAmbientLightLevel",
          "link": "Float/0/SensorMultiLevel/Luminance"
        }
      ]
    },
    {
      "name": "Батарейка",
      "type": "BatteryService",
      "characteristics": [
        {
          "type": "BatteryLevel",
          "link": "Integer/0/Battery/Level"
        }
      ]
    }
  ]
}
