### ISSUE TITLE
DIYRuZ_Flower

### ISSUE THREAD

**Issue by khvilon** [sprut/Hub#491]
Address: 00124B001FBF1E8B/6284<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 3</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: DIYRuZ_Flower</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 06/10/2020 05:22</li></ul></li></ul></li><li>Output<ul><li>0400_IlluminanceMeasurement<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0402_TemperatureMeasurement<ul></ul></li><li>0403_PressureMeasurement<ul></ul></li><li>0405_RelativeHumidityMeasurement<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0402_TemperatureMeasurement<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Wed Jan 13 12:05:23 MSK 2021

telegram: @khvilon
Покупался через чаты спрута
питание 2 батарейки ААА

**Comment by khvilon** [comment]
https://modkam.ru/?p=1700

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/modkam-sensor-vlaznosti-pocvy-zigbee-versia-no2

**Comment by Batyushin** [comment]
Модель устройства? 
Как ввести в режим спаривания?

**Comment by khvilon** [comment]
> Как ввести в режим спаривания?

Я пробовал до 5 нажатий кнопки или нажать и держать. Что-то из этого сработало, в логах пошло спаривание. Сказать точно что из двух сложно, есть впечатление, что идет некоторая задержка.

**Comment by khvilon** [comment]
> https://v2.sprut.ai/catalog/item/modkam-sensor-vlaznosti-pocvy-zigbee-versia-no2

Не совсем верно в описании, в полной версии там влажность, температура, давление

**Comment by KVolkov87** [comment]
> Как ввести в режим спаривания?

Проходим интервью и получаем все сущности (states) датчика. Для этого нажимаем на 2-3 сек единственную кнопку на датчике и отпускаем как только светодиод начнем мигать, как только 5 раз проморгает светодиодом значит подключилось (три раза – значит не подключилось). Не получается ? нажмите на 10 сек для сброса в заводствские настройки и начинаем по новой спаривать

**Comment by andreypopov** [comment]
шаблончик уже написал кто-нибудь?
