### ISSUE TITLE
TS0043

### ISSUE THREAD

**Issue by zion009** [sprut/Hub#497]
Address: 5C0272FFFEC243A5/9138<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 66</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_bi6lpsew</li><li>0005_ModelIdentifier: TS0043</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Unknown: </li><li>FFE2_Unknown: 28</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>000A_Time<ul><li>0007_LocalTime: 0</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Jan 14 18:37:39 MSK 2021

zigbee пульт
Покупал тут https://aliexpress.ru/item/1005001512559760.html?spm=a2g0v.12010612.8148356.7.12873f42IROGKS
Версия: Zigbee
Режим спаривания, сброса: нажатие кнопки 5 сек
Количество кнопок: 3
Источник питания: CR2032
Вроде как заявлено 9 действий

**Comment by Batyushin** [comment]
Внимательно прочитайте, и дополните 
https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tuya-smart-life-zigbee-besprovodnoj-pereklucatel

**Comment by REPLAY5** [comment]
Написал JSON, как получилось, описания этих json не нашел нигде.
Не работает только тип нажатия (короткое нажатие/двойное/длинное).

так же, pcap прилагаю, работа с ориг. шлюзом.
[TS0043.zip](https://github.com/sprut/Hub/files/6375952/TS0043.zip)
[pcap_.zip](https://github.com/sprut/Hub/files/6375954/pcap_.zip)
