### ISSUE TITLE
Регистрация, не выводит ошибки

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#5]
** Подробное описание ошибки **
Пытаюсь зарегистрироваться, ничего не происходит, по нажатию на кноку

** Как воспроизвести ? **
попытаться зарегистрироваться с парольлем 123456

** Ожидаемое поведение **
увидеть текст об ошибке

** Скриншоты/ Логи **
![2019-07-03_15-07-37](https://user-images.githubusercontent.com/1624839/60590391-88649000-9da4-11e9-992a-fed00f05321a.png)
![2019-07-03_15-07-49](https://user-images.githubusercontent.com/1624839/60590404-8bf81700-9da4-11e9-8ecc-851248fe4f85.png)

** Пожалуйста, заполните следующую информацию: **
  chrome

**Comment by sprut666666** [comment]
Да сейчас ошибки не выводятся, пожелание учтено и скоро будет реализовано.

**Comment by andreypopov** [comment]
1) зарегать юзера на почту a@a.com
2) в настройках сменить почту на b@b.com 
3) попытаться зайти через а@a.com или зарегить a@a.com невозможно, ошибка, мол, такой юзер есть (у вас на серваке)

Ошибки:
Unexpected reply: User already exists
Unexpected reply: User 'andrey_popov@me.com' already connected!

**Comment by defaktor** [comment]
при перезагрузки wb, повтораная авторизация на хабе
