### ISSUE TITLE
Не добавляется датчик вибрации Aqara (lumi.vibration.aq1)

### ISSUE THREAD

**Issue by airwolf973** [sprut/Hub#502]
При добавлении датчика вибрации Aqara (lumi.vibration.aq1) выдает ошибку - 00158D0002A6E0DD/9668: Настройка (1/0000_Basic/FF0D_Custom) -> (11) : Нет ответа

В устройствах появляется,  но init - инициализация

Ревизия: 3849, Устройство Raspberry 3b + Stick

<img width="1311" alt="Снимок экрана 2021-01-15 в 22 21 03" src="https://user-images.githubusercontent.com/62644309/104780840-77b31980-5792-11eb-905e-b583c877f12a.png">
<img width="863" alt="Снимок экрана 2021-01-15 в 21 28 36" src="https://user-images.githubusercontent.com/62644309/104780872-85689f00-5792-11eb-8553-ff839ccacd1e.png">
<img width="1305" alt="Снимок экрана 2021-01-15 в 21 33 01" src="https://user-images.githubusercontent.com/62644309/104780883-8bf71680-5792-11eb-8f61-de52335ec2d9.png">

**Comment by Batyushin** [comment]
1. удалить отсюда логи
2. указать телеграм для связи

**Comment by airwolf973** [comment]
> * удалить отсюда логи
> * указать телеграм для связи

Удалил, t.me/@airwolf_d

**Comment by airwolf973** [comment]
Проблема отпала. Попробовал спарил датчик через родной хаб, заметил что алгоритм добавления немного иначе, чем по инструкции.
1. Нажать на кнопку сопряжения на 5 секунд
2. Диод моргает 2 раза
3. Отпускаешь кнопку и **сразу нажимаешь ее еще раз**.

С таким же алгоритмом добавил в СХ
