### ISSUE TITLE
Radiator Thermostat Aeotec ZWA021-C (аналог Spirit Eurotronic, которые нормально добавляются в SH)

### ISSUE THREAD

**Issue by permadm** [sprut/Hub#504]
Для добавления поддержки нового устройства в хаб, необходимо:

1)
2) Radiator Thermostat Aeotec ZWA021-C
3) [Официальная страница](https://aeotec.com/z-wave-home-automation/thermostat-radiator-valve-trv/) 
[Мануал](http://manual.zwave.eu/backend/make.php?lang=en&sku=AEOEZWA021)
[Каталог](https://v2.sprut.ai/catalog/item/aeotec-radiator-thermostat)
4) <b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>9</td></tr><tr><td width=35%>Manufacturer Id</td><td>0371</td></tr><tr><td width=35%>Device Type</td><td>0002</td></tr><tr><td width=35%>Device Id</td><td>0015</td></tr><tr><td width=35%>App Version</td><td>0.16</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Thermostat</td></tr><tr><td width=35%>Specific Class</td><td>Thermostat General V2</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>true</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>1</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 Battery</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 SwitchMultiLevel<ul></ul></li><li>V8 Alarm<ul><li>System</li><li>PowerManagement</li></ul></li><li>V1 Protection</li><li>V1 NoOperation</li><li>V1 AssociationGRPInfo</li><li>V2 Version</li><li>V1 Security</li><li>V1 DeviceResetLocally</li><li>V2 Association</li><li>V5 SensorMultiLevel<ul><li>Temperature: 23.61</li></ul></li><li>V1 ZWavePlusInfo</li><li>V1 ManufacturerSpecific</li><li>V1 Configuration</li><li>V1 ThermostatMode<ul><li>Off</li><li>Heat</li><li>Full Power</li><li>Heat Eco</li></ul></li><li>V1 ThermostatSetpoint<ul><li>Heating: </li><li>Furnace: </li></ul></li><li>V1 FirmwareUpdateMD</li><li>V1 Basic</li></ul></li></ul><br>Last update: Sat Jan 16 18:40:31 MSK 2021

telegram: permadm

**Comment by permadm** [comment]
Решение: 
[AEOEZWA021.json.txt](https://github.com/sprut/Hub/files/5824841/AEOEZWA021.json.txt)

**Comment by MakeSimpleOrg** [comment]
r4199

**Comment by permadm** [comment]
оптимизировал шаблон (версия 4604)
