### ISSUE TITLE
Изменить границы регулирования температуры для устройства Thermostat Spirit Eurotronic

### ISSUE THREAD

**Issue by permadm** [sprut/Hub#505]
Границы регулирования температуры для Z-Wave устройства Thermostat Spirit Eurotronic заданы не верно:
          "minValue": 4,
          "maxValue": 30,

Правильные значения:
          "minValue": 8,
          "maxValue": 28,

telegram: permadm
[Spirit.json.txt](https://github.com/sprut/Hub/files/5824849/Spirit.json.txt)

**Comment by MakeSimpleOrg** [comment]
r3861

**Comment by permadm** [comment]
r3863 - не исправлено максимальное значение! Устройство не умеет выставлять температуру выше 28!

**Comment by MakeSimpleOrg** [comment]
r3866, не заметил сразу максимальное.
