### ISSUE TITLE
Удлинитель LELLKI создаёт два аксессуара

### ISSUE THREAD

**Issue by InfinityMe** [sprut/Hub#508]
** Подробное описание ошибки **
Одно устройство отображается как два аксуссуара.

** Как воспроизвести ? **
Удалил дублирующийся аксессуар, 
затем удалил устройство, 
запустил поиск, 
в аксессуарах опять появилось два устройства. 
Может стоило удалить оба аксессуара, я свой напереименованный не трогаю.

** Ожидаемое поведение **
Одно устройство в аксессуарах с четырьмя розетками внутри.

** Скриншоты/ Логи **
Этот я переименовал
<img width="226" alt="Снимок экрана 2021-01-17 в 11 45 24" src="https://user-images.githubusercontent.com/1360926/104835906-dd9ac080-58ba-11eb-80d8-b8cc33c5c1ff.png">
Этот добавляется и не удалить его навсегда
<img width="292" alt="Снимок экрана 2021-01-17 в 11 45 32" src="https://user-images.githubusercontent.com/1360926/104835907-e12e4780-58ba-11eb-96f7-07c5838bbc75.png">

** Пожалуйста, заполните следующую информацию: **
  - сейчас у меня Sprut.hub 1.6.7b, ревизия 3860

** Дополнительные материалы **
[Устройство в каталоге](https://v2.sprut.ai/catalog/item/lellki-setevoj-filtr-zigbee-s-2-usb-i-4-vilkami)

**Comment by sprut666666** [comment]
Удалить надо старый, проблема была давно, тогда же она и решилась )

**Comment by InfinityMe** [comment]
> Удалить надо старый, проблема была давно, тогда же она и решилась )

Вроде помогло.
