### ISSUE TITLE
Проблема при интеграции контроллера Fibaro Home center 2

### ISSUE THREAD

**Issue by Sergbmw** [sprut/Hub#511]
Добавил интеграцию с fibaro, все устройства добавились нормально, но при этом все роллеты со spinner, при этом работают

![photo_2021-01-17_12-51-06](https://user-images.githubusercontent.com/54317682/104838263-800a7200-58c2-11eb-839e-674c470137de.jpg)

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
