### ISSUE TITLE
TS0201 (Tuya)

### ISSUE THREAD

**Issue by ElvisPresly** [sprut/Hub#515]
Address: 5C0272FFFECCDD57/D0F6<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 67</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ2000_a476raq2</li><li>0005_ModelIdentifier: TS0201</li><li>0007_PowerSource: 3</li><li>FFE2_Unknown: 19</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2180</li></ul></li><li>0004_Groups<ul></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 1120</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>512</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>512</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Jan 19 12:58:36 MSK 2021

Девайс в [каталоге](https://v2.sprut.ai/catalog/item/tuya-zigbee-umnyj-domasnij-datcik-temperatury-i-vlaznosti).
Покупал [тут](https://aliexpress.ru/item/4000843004202.html?spm=a2g0s.9042311.0.0.265233edUvSWHE&_ga=2.60716909.1710641382.1611051111-1748917253.1578391681&sku_id=10000009107409116).

Вобщем то датчик залетает, работает корректно, но определяется как [Блитзвульф](https://v2.sprut.ai/catalog/item/blitzwolf-temperature-humidity-sensor).

**Comment by sprut666666** [comment]
увы но у блитза такая же модель

**Comment by ElvisPresly** [comment]
> увы но у блитза такая же модель

Просто не париться и пользоваться шаблоном блитзвульфа?)

**Comment by ElvisPresly** [comment]
@sprut666666 Может сделать возможность выбирать какое у тебя устройство, например блитзвульф или туя, раз китайцы чудят с именами? И так предполагаю не первый случай будет.

**Comment by sprut666666** [comment]
зачем ?

**Comment by ElvisPresly** [comment]
> зачем ?
@sprut666666 
ну например, будет два устройства, чисто теоретически, похожих, с одинаковыми именами, но у них будут разные опции, например в одном будет влажность, а в другом нет, и шаблоны я так понимаю будут уже нужны разные.

**Comment by sprut666666** [comment]
когда будет, тогда решу, обычно если ид полностью равны это одно и то же устройство
