### ISSUE TITLE
TS0601

### ISSUE THREAD

**Issue by nKarlson** [sprut/Hub#516]
Address: 5C0272FFFE856F39/2E7D<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 85</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_ckud7u2l</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Jan 19 17:58:22 MSK 2021

Покупался тут: https://m.aliexpress.ru/item/4001290661477.html?spm=a2g0n.orderlist-amp.item.4001290661477&aff_trace_key=&aff_platform=msite&m_page_id=1187amp-wovDqyN2HeoRwLZGRm_24g1611069124675&browser_id=ce78b7746de74919b747db2be6223451&is_c=Y

В каталоге: https://v2.sprut.ai/catalog/item/moeshouse-bht-002-gblzbw

Телеграм: @nktndrr

Режим спаривания: Выключить термостат центральной кнопкой. Удерживать стрелку вниз на протяжении 8 секунд.

**Comment by tony-g90** [comment]
MoesHouse BHT-002-GBLZBW 
Темплейт предоставил AL Bul @SaenLot


{
  "name": "Термостат",
  "manufacturer": "TUYA",
  "model": "TUYA Zigbee TRV",
  "manufacturerId": "_TZE200_ckud7u2l",
  "modelId": "TS0601",
  "catalogId": 2518,
  "status": "Done",
  "services": [
    {
      "type": "Thermostat",
      "characteristics": [
        {
          "type": "CurrentTemperature",
          "link": {
            "endpoint": 1,
            "cluster": "EF00_ManufacturerSpecific",
            "command": "0001_Notify",
            "param": "CurrentTemperature"
          }
        },
        {
          "type": "TargetTemperature",
          "link": [
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0001_Notify",
              "param": "TargetTemperature"
            },
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0002_Confirmation",
              "param": "TargetTemperature",
              "write": false
            }
          ],
          "minValue": 5
        },
        {
          "type": "CurrentHeatingCoolingState",
          "validValues": ""
        },
        {
          "type": "TargetHeatingCoolingState",
          "link": [
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0001_Notify",
              "param": "TargetHeatingCoolingState"
            },
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0002_Confirmation",
              "param": "TargetHeatingCoolingState",
              "write": false
            }
          ],
          "validValues": "1,2,3"
        }
      ]
    },
    {
      "type": "Valve",
      "data": {
        "Logic": {
          "selected": "InUseFromActive"
        }
      },
      "characteristics": [
        {
          "type": "Active",
          "link": [
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0001_Notify",
              "param": "Valve"
            },
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0002_Confirmation",
              "param": "Valve",
              "write": false
            }
          ]
        }
      ]
    },
    {
      "name": "Окно",
      "type": "Switch",
      "characteristics": [
        {
          "type": "On",
          "link": [
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0001_Notify",
              "param": "Window"
            },
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0002_Confirmation",
              "param": "Window",
              "write": false
            }
          ]
        }
      ]
    },
    {
      "name": "Блокировка",
      "type": "Switch",
      "characteristics": [
        {
          "type": "On",
          "link": [
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0001_Notify",
              "param": "LockPhysicalControls"
            },
            {
              "endpoint": 1,
              "cluster": "EF00_ManufacturerSpecific",
              "command": "0002_Confirmation",
              "param": "LockPhysicalControls",
              "write": false
            }
          ]
        }
      ]
    },
    {
      "type": "BatteryService",
      "data": {
        "Logic": {
          "selected": "LowBatteryFromCurrentLevel"
        }
      },
      "characteristics": [
        {
          "type": "BatteryLevel",
          "link": {
            "endpoint": 1,
            "cluster": "EF00_ManufacturerSpecific",
            "command": "0001_Notify",
            "param": "BatteryLevel"
          }
        }
      ]
    }
  ]
}

**Comment by ElvisPresly** [comment]
Тоже интересно. Ждем

**Comment by nKarlson** [comment]
Олег, ну уже скоро все морозы закончатся)

**Comment by ElvisPresly** [comment]
@sprut666666 ага, ноги отмерзают)
