### ISSUE TITLE
AEOEZW117 Ретранслятор ZWave Aeotec Range Extender 6

### ISSUE THREAD

**Issue by permadm** [sprut/Hub#517]
1) Модель устройства должна определиться как "Unknown". 
Добавил пустой темплейт (временно, чтобы название отображало). Думал будет работать, но не работает нормально, так как уровень мощности по-видимому надо менять, а он в 0 установлен. 

2) ZWave Aeotec Range Extender 6 
AEOEZW117

3) 
http://manuals-backend.z-wave.info/make.php?lang=en&sku=ZW117-C15&cert=ZC10-16095248

https://www.intin.no/wp-content/uploads/2018/05/rangeextender6tech.pdf

http://z-wave-assets.s3-us-west-2.amazonaws.com/docs/286/Aeotec_Z-Wave_Range_Extender_6_Instruction_Manual.pdf?1492712834

https://images-eu.ssl-images-amazon.com/images/I/81wigSoF2oS.pdf

4) 
<b>Aeotec - Range Extender 6</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>20</td></tr><tr><td width=35%>Manufacturer Id</td><td>0086</td></tr><tr><td width=35%>Device Type</td><td>0004</td></tr><tr><td width=35%>Device Id</td><td>0075</td></tr><tr><td width=35%>App Version</td><td>1.5</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Repeater Slave</td></tr><tr><td width=35%>Specific Class</td><td>Repeater Slave</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>1</td></tr></table><br><b>Neighbors</b><br><table border=1 width=100%><tr><th>ID</th><th>Basic</th><th>Generic</th><th>Specific</th><th>Listening</th><th>Ping</th></tr><tr><td>1</td><td>Static Controller</td><td>Static Controller</td><td>Controller</td><td>Yes</td><td>0</td></tr><tr><td>4</td><td>Routing Slave</td><td>Switch Binary</td><td>Power Switch Binary</td><td>Yes</td><td>10</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 Version</li><li>V1 SwitchColor</li><li>V1 NoOperation</li><li>V1 Configuration</li><li>V2 ManufacturerSpecific</li><li>V1 DeviceResetLocally</li><li>V2 Association</li><li>V1 FirmwareUpdateMD</li><li>V1 Security</li><li>V1 Basic</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V2 SwitchMultiLevel<ul></ul></li><li>V1 ZWavePlusInfo</li><li>V1 AssociationGRPInfo</li></ul></li></ul><br>Last update: Tue Jan 19 14:37:32 MSK 2021

https://v2.sprut.ai/catalog/item/aeotec-range-extender-6-uk

telegram: permadm

**Comment by permadm** [comment]
При добавлении устройства устройства без поддержки сх, устройство отваливается через определённый интервал 7200000 (не известно в каких единицах измеряется)
![Uploading AE5E3587-2D56-4119-BA66-F1C67A1A87B5.jpeg…]()

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/aeotec-range-extender-6-uk
