### ISSUE TITLE
LCT007

### ISSUE THREAD

**Issue by aid81** [sprut/Hub#518]
Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device
Address: 00178801020AB93D/CD8C<br><br><b>Structure</b><br><ul><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 17</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: LCT007</li><li>0006_DateCode: 20191216</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 5.130.1.30000</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 58</li><li>0001_CurrentSaturation: 141</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 29980</li><li>0004_CurrentY: 26875</li><li>0007_ColorTemperature: 366</li><li>0008_ColorMode: 2</li><li>4000_EnhancedCurrentHue: 14988</li><li>4001_EnhancedColorMode: 2</li><li>4002_ColorLoopActive: 0</li><li>4003_ColorLoopDirection: 0</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>4000_StartUpCurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 1107326256</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4107</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>71</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>45</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>45</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, RECHARGABLE_BATTERY, MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Jan 20 13:35:01 MSK 2021
[logs.zip](https://github.com/sprut/Hub/files/5841805/logs.zip)

Просьба добавить лампы Philips Hue LCT007 . Подключались к WB через Sprut.stick ZigBee 2 WB Pro без родного моста.
@AiD911

**Comment by Batyushin** [comment]
Необходимо указать ссылку на устройство в магазине где покупал или на оф сайте.  
Необходимо указать ссылку на устройство в каталоге (если добавлено)

**Comment by aid81** [comment]
https://www.shop.philips.ru/svetovyye-resheniya/umnyy-dom-hue/hue/startovyi-komplekt-philips-hue-white-and-color-ambiance.html
Ссылка на  новое поколение, стартеркит с пультом, мой же без пульта, куплен года 3 назад, предположительно Gen2

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/philips-lampa-hue-e27-2000k-6500k-9-vt-60-vt

**Comment by aid81** [comment]
**sprut666666** какбы теперь попросить темплейт к данному девайсу?
