### ISSUE TITLE
TRADFRI bulb E14 W op/ch 400lm моргает лампа при включении.

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#522]
** Подробное описание ошибки **
При включении лампочки через датчик движения , лампа может моргать. 
TRADFRI bulb E14 W op/ch 400lm

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Подключаем лампу
2. Настраиваем включение лампы на автоматизации через хк с датчиком движения
3. Наблюдаем, как лампа начинает моргать.
** Ожидаемое поведение **
Лампа не должна моргать. 2/4 ламп в квартире работают нормально

** Скриншоты/ Логи **
Как я понял, Sprut ты в курсе этой проблемы, если что всегда могу предоставить логи.

** Пожалуйста, заполните следующую информацию: **
IOS 14.3
Ревизия: 3911
Дата сборки: 22.01.2021, 22:35:36

** Дополнительные материалы **
@UskovvNA - telegram

**Comment by sprut666666** [comment]
это для икеи нормально, ждём новые прошивки
