### ISSUE TITLE
Пропадает значение температуры

### ISSUE THREAD

**Issue by tkasyanov** [sprut/Hub#53]
Если свернуть - развернуть термостат, то пропадает значение температуры

![image](https://user-images.githubusercontent.com/11898563/71786768-15b8c380-3018-11ea-90c9-3a783d866f7d.png)
![image](https://user-images.githubusercontent.com/11898563/71786771-22d5b280-3018-11ea-901d-6639b5f9e8c7.png)

**Comment by diamond5170** [comment]
Это не баг, это стандартная работа этого графического компонента в Angular. Изменить это поведение нельзя, только использовать какой-то нестандартный компонент.

**Comment by tkasyanov** [comment]
"Изменить это поведение нельзя" - можно, если нужна помощь в ангуляре могу помочь.

**Comment by diamond5170** [comment]
Сделал
