### ISSUE TITLE
TS0002

### ISSUE THREAD

**Issue by VitaliyRN** [sprut/Hub#530]
Address: 60A423FFFEB38ACE/8E41<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 69</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_svoqrno4</li><li>0005_ModelIdentifier: TS0002</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 178</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 60A423FFFE4174CE</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 211</li><li>0002_CurrentGroup: 8192</li><li>0003_SceneValid: true</li><li>0004_NameSupport: 163</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE4174CE</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>159</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jan 30 20:27:46 MSK 2021

[logs.zip](https://github.com/sprut/Hub/files/5898482/logs.zip)
Телеграм: R.Vytaliy
Девайс в каталоге https://v2.sprut.ai/catalog/item/lonsonho-smart-switch-2-switch-2
Покупал тут https://aliexpress.ru/item/4000298926256.html?spm=a2g0o.cart.0.0.47c23c00RvTzBZ&mp=1&_ga=2.126250249.528869728.1612030880-740618432.1597904328&sku_id=12000016027200761

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/lonsonho-smart-switch-2-switch-2

**Comment by VitaliyRN** [comment]
Подскажите. Пишет нет щаблона для данного девайса. Я новичок!

**Comment by VitaliyRN** [comment]
У меня модель TS0002 , а в каталоге 
X702A

**Comment by sprut666666** [comment]
после апдейта, проверить настройки индикации и отписать

**Comment by VitaliyRN** [comment]
Добрый день!
После апдейта, "опрос пройден" все ок!
Индикация: выключен - зеленый, включен - оранжевый.
Спасибо за помощь, и быструю реакцию на проблему , поддержка супер! Впечатлен !!!

**Comment by sprut666666** [comment]
есть настройка индикации и возможности её отключения, нужно проверить работает ли она

**Comment by VitaliyRN** [comment]
![индикация](https://user-images.githubusercontent.com/78273426/106510161-41d29c80-64d7-11eb-8d82-339fed25ecfb.jpg)
Настойки индикации есть но не работает.

![После восстановления питания](https://user-images.githubusercontent.com/78273426/106510405-8fe7a000-64d7-11eb-80f7-b9d236aac708.jpg)
Настройки после восстановления питания работают корректно.

**Comment by VitaliyRN** [comment]
Отключение  индикации не работает.

**Comment by sprut666666** [comment]
спасибо
