### ISSUE TITLE
TS011F _TZ3000_tvuarksa

### ISSUE THREAD

**Issue by deemerby** [sprut/Hub#531]
Address: BC33ACFFFEFF2C1C/28AC<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_tvuarksa</li><li>0005_ModelIdentifier: TS011F</li><li>0007_PowerSource: 1</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 2</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415613</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>193</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D0003938D23</td><td>1A9D</td><td>Router</td><td>false</td><td>Sibling</td><td>100</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B0009FE0F14</td><td>B833</td><td>Router</td><td>false</td><td>Sibling</td><td>187</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0003938C03</td><td>E06F</td><td>Router</td><td>false</td><td>Sibling</td><td>76</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0003A4AC7B</td><td>E7F3</td><td>Router</td><td>false</td><td>Sibling</td><td>76</td><td>UNKNOWN</td><td>15</td></tr><tr><td>CCCCCCFFFE05CA98</td><td>EF0F</td><td>Router</td><td>false</td><td>Sibling</td><td>149</td><td>UNKNOWN</td><td>15</td></tr><tr><td>680AE2FFFE71374A</td><td>F68C</td><td>Router</td><td>false</td><td>Sibling</td><td>152</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B0009FE33D7</td><td>FECD</td><td>Router</td><td>false</td><td>Sibling</td><td>252</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Feb 03 16:00:34 MSK 2021

Покупался тут: https://a.aliexpress.com/_AYOfx0

В каталоге: https://v2.sprut.ai/catalog/item/tuya-crane
был взят за основу шаблон от TS0111

пересекается с https://github.com/sprut/Hub/issues/513
имеет такой же идендификатор

**Comment by sprut666666** [comment]
после апдейта проверить настройки индикации
