### ISSUE TITLE
Добавление проветривателя  Tion 3S ZWave.

### ISSUE THREAD

**Issue by wolf13118** [sprut/Hub#535]

**Comment by wolf13118** [comment]
Модернизацию серийного устройства провела команда Z-Wave.ME.
Ссылка на сайт устройства https://rus.z-wave.me/shop/termostats/provetrivatel-tion-3s-z-wave/

**Comment by wolf13118** [comment]
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>20</td></tr><tr><td width=35%>Manufacturer Id</td><td>0115</td></tr><tr><td width=35%>Device Type</td><td>0100</td></tr><tr><td width=35%>Device Id</td><td>0900</td></tr><tr><td width=35%>App Version</td><td>2.16</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Power Switch Binary</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>8</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 FirmwareUpdateMD</li><li>V1 DeviceResetLocally</li><li>V3 MultiChannelAssociation</li><li>V1 SwitchBinary</li><li>V2 Association</li><li>V1 ThermostatSetpoint<ul><li>Heating: </li></ul></li><li>V2 ManufacturerSpecific</li><li>V1 Configuration</li><li>V2 MultiChannel</li><li>V2 Version</li><li>V1 ThermostatMode<ul><li>Heat</li><li>Off</li></ul></li><li>V1 SwitchMultiLevel<ul></ul></li><li>V1 AssociationGRPInfo</li><li>V1 NoOperation</li><li>V1 ZWavePlusInfo</li><li>V7 SensorMultiLevel<ul><li>Temperature: </li></ul></li><li>V1 Basic</li></ul></li><li>Endpoint 1<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li><li>Endpoint 2<ul><li>V1 SwitchBinary</li><li>V1 Basic</li></ul></li><li>Endpoint 3<ul><li>V1 SwitchMultiLevel<ul></ul></li><li>V1 Basic</li></ul></li></ul><br>Last update: Mon Feb 08 21:52:27 MSK 2021

**Comment by wolf13118** [comment]
Отлично работает в среде Z-Wave Smart Home на WB 6. Очень хочется интегрировать в SH.

**Comment by wolf13118** [comment]
Функции устройства. 1) вкл-выкл 2) Установка скорости вентилятора 3)Установка температуры подогрева воздуха 4) датчик температуры 
   Запрос на включение в сеть ZWave автоматически в момент подключения в сеть 220V или долгое нажатие на кнопку включения

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tion-tion-3s

**Comment by MakeSimpleOrg** [comment]
Закрыли то зачем? Еще не готово :)

**Comment by MakeSimpleOrg** [comment]
Добавил в r4209 шаблон, сделанный "наугад". Теперь задача проверить его, собрать всю информацию, и отписать здесь. Какие функции работают, какие нет.
Так же включить галочку "Показать все события". И если к примеру не работает задание температуры, то попробовать задать ее вручную на бризере и посмотреть что придет в логи. Аналогично по другим параметрам.
Так же нет информации по настройкам, но возможно их и нет. И документации я не нашел.
