### ISSUE TITLE
FNB56-ZSW01LX2.0

### ISSUE THREAD

**Issue by jonimant** [sprut/Hub#536]
Address: 00158D00044A8773/3F57<br><br><b>Structure</b><br><ul><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: FeiBit</li><li>0005_ModelIdentifier: FNB56-ZSW01LX2.0</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 1000-0001</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 3</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 1</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 0</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 1</li><li>0001_RemainingTime: 0</li><li>000F_Options: 0</li><li>0010_OnOffTransitionTime: 10</li><li>4000_StartUpCurrentLevel: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0002_CurrentFileVersion: 1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>90</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4478</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>90</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Feb 08 23:24:08 CET 2021

Телеграмм: <a href="https://t.me/jonimant">@jonimant</a>
Приобретался: <a href="https://aliexpress.ru/item/Zigbee-3-0-EU-One-Gang-Wall-Light-Switch-Compatible-with-SmartThing-Hub-Echo-Plus-APP/32945533571.html">aliexpress</a>
Название: Zigbee 3.0 Smart 1 Gang Switch
Модель: LXZB-41-EU
Наличия нуля: Да
Версия Zigbee: 3.0
Режим спаривания: 10 сек
Питание: 100-240v AC 50/60 Hz
В каталоге нет
статус после восстановления питания: не сохраняется, после восстановлении режим всегда выкл.

**Comment by Batyushin** [comment]
а это разве не он? https://v2.sprut.ai/catalog/item/zemismart-zigbee-30-eu-one-gang

**Comment by jonimant** [comment]
внешне очень похож, но модель у меня на обороте указана LXZB-41-EU , откуда такой номер взят я не знаю

**Comment by jonimant** [comment]
так отображает z2m:

![изображение_2021-02-09_232534](https://user-images.githubusercontent.com/8249515/107436640-1c284180-6b2e-11eb-9f9a-f22a203601cb.png)

**Comment by sprut666666** [comment]
проверить настройку статус после востановления питания и отписать

**Comment by jonimant** [comment]
статус после восстановления питания работает.
