### ISSUE TITLE
Aqara Cube MFKZQ01LM событие стороны

### ISSUE THREAD

**Issue by CODeRUS** [sprut/Hub#538]
** Подробное описание ошибки **
При событияхъ slide, tap, flip90, flip180 не определяется сторона

** Как воспроизвести ? **
1. Постучать кубиком по столу, подвигать в сторону (не вращение), перевернуть грань
2. Посмотреть на наличие события смены грани

** Ожидаемое поведение **
Есть событие с номером грани, на которой закончилось действие

** Скриншоты/ Логи **
Кроме самого события нет доп события грани

** Пожалуйста, заполните следующую информацию: **
Ревизия: 4002
Дата сборки: 04.02.2021, 14:08:19

** Дополнительные материалы **
Видео работы на z2m
https://www.youtube.com/watch?v=Yz0SfLRYIrY

**Comment by sprut666666** [comment]
на тапы приходит событие, остальное вычислять не буду
