### ISSUE TITLE
Переименование аксессуаров, улучшить сохранение

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#54]
** Подробное описание ошибки **
Когда быстро печатаешь название, сохранение происходит после каждого изменения, в инпут подставляется сохраненное значение
Почему недопустимы пробелы, когда пробел есть в "Универсальный датчик"?

** Как воспроизвести ? **
Переименовать любой аксессуар
![2020-01-06 10 11 32](https://user-images.githubusercontent.com/1624839/71801812-1465b600-306d-11ea-808a-055c455ae829.gif)

** Ожидаемое поведение **
Сделать сохранение с таймером в 1 секунду, пример: функция onkeyup с таймером
![2020-01-06_10-02-56](https://user-images.githubusercontent.com/1624839/71801449-082d2900-306c-11ea-8eea-df52dc7e3a11.png)

**Comment by diamond5170** [comment]
Исправлено
