### ISSUE TITLE
WBIO-DO-R10R-4 не работает инверсия

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#543]
WBIO-DO-R10R-4 подключен через wb-mio-gpio_102:3/2
Направление всегда не то, выбирал inversed (в двух местах) и  в разных вариациях, но все равно, когда в хк написано открывается, по факту закрывается и наоборот. Статус всегда перепутан.

**Comment by andreypopov** [comment]
Очень жду! ) баг подтвержден?

**Comment by andreypopov** [comment]
Есть новости? нужен фикс

**Comment by andreypopov** [comment]
Инверсия будет?

**Comment by sprut666666** [comment]
если проблема сохранилась отписать в чат поддержки
