### ISSUE TITLE
Lonsonho QS-Zigbee-D02-TRIAC-LN и QS-Zigbee-D02-TRIAC-2C-LN не работает настройка "После восстановления питания"

### ISSUE THREAD

**Issue by denv3r** [sprut/Hub#545]
** Подробное описание ошибки **
У диммеров Lonsonho QS-Zigbee-D02-TRIAC-LN и QS-Zigbee-D02-TRIAC-2C-LN не работает настройка "После восстановления питания".
https://github.com/sprut/Hub/issues/512
В приложении Smart Life (Tuya) такой настройки нет, подозреваю, что в самом устройстве это не предусмотрено.
Устройство при любой настройке всегда запоминает последнее состояние.

** Как воспроизвести ? **
1. Открыть настройки любого из двух устройств и поменять настройку на "Всегда выключено" или "Всегда включено"
2. Отключить и включить питание
3. Устройство сохранило предыдущее состояние

** Ожидаемое поведение **
3. Устройство включилось/выключилось после подачи питания в соответствии с настройкой

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия: 4162

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by denv3r** [comment]
При попытке добавить выдает вот такое:
BC33ACFFFE656292/3AB2: Настройка (1/0006_OnOff/8002_RestartStatus) -> (2)Нет ответа
В списке устройств висит в статусе "Инициализация"
При этом работает нормально.

**Comment by shaggyone** [comment]
@denv3r подскажите, пожалуйста, удалось ли решить проблему?

**Comment by shaggyone** [comment]
@denv3r Если я правильно понял issue, у меня та же беда. И, это очень похоже на проблему с прошивкой самого диммера. Я брал два одноканальных и два двухканальных диммера. Одноканальные, если отключить и включить внешнее питание включает свет по ощущениям на 25% яркости. При этом сам диммер, похоже, об этом не знает. В то же время оба двухканальных диммера работают как ожидается. Если на момент пропадания питаяния свет свет выключен, то после восстановления он выключен, если включён, то включается.
