### ISSUE TITLE
LWE002

### ISSUE THREAD

**Issue by kazadbaruk** [sprut/Hub#549]
Address: 0017880109000B1B/0345<br><br><b>Structure</b><br><ul><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Signify Netherlands B.V.</li><li>0005_ModelIdentifier: LWE002</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 1.76.10</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>FC02_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>128</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>128</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Feb 20 14:08:00 MSK 2021
[logs (1).zip](https://github.com/sprut/Hub/files/6014839/logs.1.zip)
https://v2.sprut.ai/catalog/item/philips-lampa-hue-e14-2700k-55-vt-40-vt
kazad

**Comment by sprut666666** [comment]
опрос не полный, переспарь лампу и обнови описание

**Comment by kazadbaruk** [comment]
Только описание, сниффить ненужно?
Сб, 20 февр. 2021 г. в 16:14, Sprut <notifications@github.com>:

**Comment by sprut666666** [comment]
только описание

**Comment by kazadbaruk** [comment]
Address: 0017880108EF7B5A/797B<br><br><b>Structure</b><br><ul><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Signify Netherlands B.V.</li><li>0005_ModelIdentifier: LWE002</li><li>0007_PowerSource: 1</li><li>0051_Custom: 0</li><li>4000_SwBuildId: 1.76.10</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>FC02_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4003_StartUpOnOff: 255</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>4000_StartUpCurrentLevel: 255</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>11</td><td>IEEE</td><td>60A423FFFE415514/1</td><td>0006_OnOff</td></tr><tr><td>11</td><td>IEEE</td><td>60A423FFFE415514/1</td><td>0008_LevelControl</td></tr></table><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>128</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>128</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Feb 20 16:21:14 MSK 2021

**Comment by kazadbaruk** [comment]
Так нормально?

Сб, 20 февр. 2021 г. в 16:18, Sprut <notifications@github.com>:

**Comment by sprut666666** [comment]
в телеге мне отпиши плиз
