### ISSUE TITLE
TRADFRI remote control

### ISSUE THREAD

**Issue by DevelopByte** [sprut/Hub#551]
Address: 90FD9FFFFEE60BB1/E826<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 17</li><li>0002_StackVersion: 87</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI remote control</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 1.2.214</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 74</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul></ul></li><li>0009_Alarms<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 304170354</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4476</li><li>0008_ImageTypeId: 4545</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Feb 21 18:16:01 MSK 2021

Похожий ишью https://github.com/sprut/Hub/issues/125 может версия отличается

Телеграм @Stasyuk

В каталоге https://v2.sprut.ai/catalog/item/ikea-besprovodnoj-reostat-2 может версия отличается

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ikea-besprovodnoj-reostat-2

**Comment by DevelopByte** [comment]
К сожалению все еще не работает :(
Обновлю лог для текущей ревизии

Address: 90FD9FFFFEE60BB1/E826<br><br><b>Structure</b><br><ul><li>Endpoint 0 (ON_OFF_SWITCH)<ul><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li><li>Endpoint 1 (NON_COLOR_CONTROLLER)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 33</li><li>0002_StackVersion: 98</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI remote control</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductUrl: </li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: </li><li>0012_DeviceEnabled: </li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SwBuildId: 2.3.014</li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 172800</li><li>0001_LongPollInterval: 1160</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li><li>0004_CheckinIntervalMin: </li><li>0005_LongPollIntervalMin: </li><li>0006_FastPollTimeoutMax: </li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: </li><li>0001_MainsFrequency: </li><li>0002_Custom: </li><li>0003_Custom: </li><li>0004_Custom: </li><li>0005_Custom: </li><li>0006_Custom: </li><li>0007_Custom: </li><li>000C_Custom: </li><li>0010_MainsAlarmMask: </li><li>0011_MainsVoltageMinThreshold: </li><li>0012_MainsVoltageMaxThreshold: </li><li>0013_MainsVoltageDwellTripPoint: </li><li>0014_Custom: </li><li>0020_BatteryVoltage: 0</li><li>0021_BatteryPercentageRemaining: 100</li><li>0030_BatteryManufacturer: </li><li>0031_BatterySize: </li><li>0032_BatteryAHrRating: </li><li>0033_BatteryQuantity: </li><li>0034_BatteryRatedVoltage: </li><li>0035_BatteryAlarmMask: </li><li>0036_BatteryVoltageMinThreshold: </li><li>0037_BatteryVoltageThreshold1: </li><li>0038_BatteryVoltageThreshold2: </li><li>0039_BatteryVoltageThreshold3: </li><li>003A_BatteryPercentageMinThreshold: </li><li>003B_BatteryPercentageThreshold1: </li><li>003C_BatteryPercentageThreshold2: </li><li>003D_BatteryPercentageThreshold3: </li><li>003E_BatteryAlarmState: </li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: </li><li>0001_PersistentMemoryWrites: </li><li>0100_MacRxBcast: </li><li>0101_MacTxBcast: </li><li>0102_MacRxUcast: </li><li>0103_MacTxUcast: </li><li>0104_MacTxUcastRetry: </li><li>0105_MacTxUcastFail: </li><li>0106_ApsRxBcast: </li><li>0107_ApsTxBcast: </li><li>0108_ApsRxUcast: </li><li>0109_ApsTxUcastSuccess: </li><li>010A_ApsTxUcastRetry: </li><li>010B_ApsTxUcastFail: </li><li>010C_RouteDiscInitiated: </li><li>010D_NeighborAdded: </li><li>010E_NeighborRemoved: </li><li>010F_NeighborStale: </li><li>0110_JoinIndication: </li><li>0111_ChildMoved: </li><li>0112_NwkFcFailure: </li><li>0113_ApsFcFailure: </li><li>0114_ApsUnauthorizedKey: </li><li>0115_NwkDecryptFailures: </li><li>0116_ApsDecryptFailures: </li><li>0117_PacketBufferAllocateFailures: </li><li>0118_RelayedUcast: </li><li>0119_PhyToMacQueueLimitReached: </li><li>011A_PacketValidateDropCount: </li><li>011B_AverageMacRetryPerApsMessageSent: </li><li>011C_LastMessageLqi: </li><li>011D_LastMessageRssi: </li></ul></li><li>0009_Alarms<ul><li>0000_AlarmCount: </li></ul></li><li>FC7C_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: </li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: </li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: </li><li>0001_CurrentScene: </li><li>0002_CurrentGroup: </li><li>0003_SceneValid: </li><li>0004_NameSupport: </li><li>0005_LastConfiguredBy: </li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: </li><li>4000_GlobalSceneControl: </li><li>4001_OnTime: </li><li>4002_OffWaitTime: </li><li>4003_StartUpOnOff: </li><li>8000_MultipleClick: </li><li>8001_IndicatorMode: </li><li>8002_RestartStatus: </li><li>8003_CustomTuya: </li><li>F000_Custom: </li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: </li><li>0001_RemainingTime: </li><li>0002_MinLevel: </li><li>0003_MaxLevel: </li><li>000F_Options: </li><li>0010_OnOffTransitionTime: </li><li>0011_OnLevel: </li><li>0012_OnTransitionTime: </li><li>0013_OffTransitionTime: </li><li>0014_DefaultMoveRate: </li><li>4000_StartUpCurrentLevel: </li></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 587286065</li><li>0003_CurrentZigbeeStackVersion: </li><li>0004_DownloadedFileVersion: </li><li>0005_DownloadedZigbeeStackVersion: </li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4476</li><li>0008_ImageTypeId: 4545</li><li>0009_MinimumBlockRequestPeriod: </li><li>000A_ImageStamp: </li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>Group</td><td>B163</td><td>0000_Basic</td></tr><tr><td>1</td><td>IEEE</td><td>[5] Sprut zigbee (1)</td><td>0001_PowerConfiguration</td></tr><tr><td>1</td><td>Group</td><td>Default</td><td>0008_LevelControl</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Jul 08 15:38:03 MSK 2021

**Comment by jonimant** [comment]
не работает долгое нажатие на центральной кнопке, срабатывает только одиночное нажатие, остальные 4 кнопки работают на одиночном и долгом нажатии.  в Zigbee2MQTT центральная кнопка на долгое нажатие срабатыает.
