### ISSUE TITLE
Прошу добавить модуль аналоговых входов WBIO-AI-DV-12/4-20мА

### ISSUE THREAD

**Issue by wolf13118** [sprut/Hub#553]
Ссылка на сайт https://wirenboard.com/ru/product/WBIO-AI-DV-12_4-20MA/ 
Необходим для подключения датчиков давления. Очень бы хотелось реализации корректировки АЦП как у WB. И отображении в HomeKit  уже реального давления. Пока СХ этот модуль не видит.

**Comment by sprut666666** [comment]
топики покажи

**Comment by wolf13118** [comment]
<img width="1280" alt="Снимок экрана 2021-02-22 в 12 51 38" src="https://user-images.githubusercontent.com/78754059/108691712-d778af00-750c-11eb-9948-bd38be7cff4f.png">

**Comment by wolf13118** [comment]
Додумался только до этого, если нужно другое подскажите пожалуйста как добыть ?

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/wirenboard-modul-vvoda-vyvoda-wbio-ai-dv-12-4-20ma

**Comment by wolf13118** [comment]
<img width="1280" alt="Снимок экрана 2021-02-28 в 21 30 12" src="https://user-images.githubusercontent.com/78754059/109430923-c0f2bc00-7a14-11eb-8036-12fe1d637ea6.png">

**Comment by wolf13118** [comment]
Топики WB

**Comment by wolf13118** [comment]
<img width="1280" alt="Снимок экрана 2021-02-28 в 22 15 32" src="https://user-images.githubusercontent.com/78754059/109430944-dff14e00-7a14-11eb-8358-4ecbf7ff3fa6.png">

**Comment by wolf13118** [comment]
Лог СХ при загрузки контроллера
