### ISSUE TITLE
Не работает поиск на zigbee стике от Wirenboard (WBE2R-R-ZIGBEE)

### ISSUE THREAD

**Issue by peefoo** [sprut/Hub#554]
** Подробное описание ошибки **
При добавлении  зигби стика WBE2R-R-ZIGBEE не удается перейти в режим поиска новых устройств.
** Как воспроизвести ? **

Добавляем стик в интерфейсе WB
Создаем контроллер Зигби в Спрутхабе, выбираем WBE2R-R-ZIGBEE, выбираем правильный порт, сохраняем
Жмем галочку напротив контроллера зигби, получаем ошибку в логе.
Пытаемся выбрать в контроллере зигби "Поиск устройств", спустя секунды приходит еще одна ошибка

Спрутстик про добавляется и ищет нормально

** Ожидаемое поведение **
Нормально добавится устройство, позволит включить поиск
** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.
![image](https://user-images.githubusercontent.com/57656842/108711255-2121c380-7526-11eb-954e-a3b07d10698c.png)

** Пожалуйста, заполните следующую информацию: **
Ревизия: 4214
Дата сборки: 22.02.2021, 06:33:04
** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.
![image](https://user-images.githubusercontent.com/57656842/108711310-3860b100-7526-11eb-99ec-4012fded16e1.png)

**Comment by sprut666666** [comment]
Сейчас времено поддержка сторонних стиков приостановлена, все силы брошены на идеальную работу нашего решения, сейчас варианта 2
- Купить спрутстик, там всё будет работать в лучшем виде
- Подождать пока работа по спрутстику будет закончена и можно будет исправить проблемы сторонних

**Comment by peefoo** [comment]
Понял, принял, спасибо
