### ISSUE TITLE
WB-MS v.2 не залетает в СХ

### ISSUE THREAD

**Issue by aid81** [sprut/Hub#556]
Добавленный в WB датчик [WB-MS v.2](https://v2.sprut.ai/catalog/item/wirenboard-temperatura-vlaznost-osvesennost-voc) Addr.66, не появляется в MQTT и аксессуарах,
хотя в логах инфа о нем присутствует.
[logs.zip](https://github.com/sprut/Hub/files/6027906/logs.zip)
Ревизия: 4219

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/wirenboard-temperatura-vlaznost-osvesennost-voc
