### ISSUE TITLE
TRADFRI bulb E27 CWS opal 600lm

### ISSUE THREAD

**Issue by dmitrydyugaev** [sprut/Hub#561]
Address: D0CF5EFFFE15A254/005E<br><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 17</li><li>0002_StackVersion: 87</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI bulb E27 CWS opal 600lm</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 1.3.002</li></ul></li><li>0300_ColorControl<ul><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 30015</li><li>0004_CurrentY: 26870</li><li>0008_ColorMode: 2</li><li>4001_EnhancedColorMode: 1</li><li>400A_ColorCapabilities: 8</li><li>400B_ColorTemperatureMin: 250</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 0</li><li>0100_MacRxBcast: 0</li><li>0101_MacTxBcast: 0</li><li>0106_ApsRxBcast: 0</li><li>0107_ApsTxBcast: 0</li><li>011C_LastMessageLqi: 255</li><li>011D_LastMessageRssi: -11</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>000F_Options: 0</li><li>0010_OnOffTransitionTime: 5</li><li>0011_OnLevel: 255</li><li>4000_StartUpCurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0020_PollControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 318767730</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4476</li><li>0008_ImageTypeId: 10241</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415362</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>189</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Feb 28 19:49:32 MSK 2021

**Comment by Batyushin** [comment]
прошу заполнить соблюдая все требования https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

https://v2.sprut.ai/catalog/item/ikea-tradfri-bulb-e27-cws-opal-600lm
