### ISSUE TITLE
ZG9101SAC-HP

### ISSUE THREAD

**Issue by wpetrov** [sprut/Hub#563]
Address: 588E81FFFE62C0C4/1E63<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 0</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 0</li><li>0004_ManufacturerName: Sunricher</li><li>0005_ModelIdentifier: ZG9101SAC-HP</li><li>0006_DateCode: NULL</li><li>0007_PowerSource: 1</li><li>0008_GenericDeviceClass: 255</li><li>0009_GenericDeviceType: 255</li><li>4000_SwBuildId: 2.5.3_r47</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 0</li><li>011C_LastMessageLqi: 0</li><li>011D_LastMessageRssi: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 255</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>000F_Options: 1</li><li>0010_OnOffTransitionTime: 1</li><li>0011_OnLevel: 255</li><li>4000_StartUpCurrentLevel: 255</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 47</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4644</li><li>0008_ImageTypeId: 2006</li><li>0009_MinimumBlockRequestPeriod: 0</li><li>000A_ImageStamp: -1</li></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul><li>0000_GpsMaxSinkTableEntries: 20</li><li>0020_GpClientSharedSecurityKeyType: 3</li><li>0021_GpClientSharedSecurityKey: 00000000000000000000000000000000</li><li>0022_GpClientLinkKey: 5A6967426565416C6C69616E63653039</li></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul><li>0010_GppMaxProxyTableEntries: 20</li><li>0011_ProxyTable: ByteArray [value=]</li><li>0016_GppFunctionality: 633903</li><li>0017_GppActiveFunctionality: 16777215</li><li>0022_GpClientLinkKey: 5A6967426565416C6C69616E63653039</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4644</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Mar 01 10:53:03 UTC 2021

---

Реле / диммер в подрозетник с контактами для физической кнопки.

Покупал тут: https://www.amazon.de/gp/product/B07SPH2XVR/
В каталоге отсутствует.
ZigBee 3.0

Режим сброса - 5 кратное нажатие на "reset" либо 5-ти кратное передергивание питания
Режим спаривания - после сброса просто подать питание
Режим поиска / спаривания пульта (TouchLink) - 4 кратное нажатие на "reset" либо 4-ти кратное передергивание питания
Режим поиска / спаривания пульта - 3 кратное нажатие на "reset" либо 3-ти кратное передергивание питания

ник в телеграме @wp24wp

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/sunricher-zigbee-ac-in-wall-switch
