### ISSUE TITLE
DIYRuZ_AirSense

### ISSUE THREAD

**Issue by yorulez** [sprut/Hub#564]
Address: 00124B001ED13447/FBF3<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 3</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: DIYRuZ_AirSense</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 18/01/2021 11:22</li></ul></li></ul></li><li>Output<ul><li>0402_TemperatureMeasurement<ul></ul></li><li>0403_PressureMeasurement<ul></ul></li><li>0405_RelativeHumidityMeasurement<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>040D_CarbonDioxide<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 02 12:00:45 MSK 2021
telegram: yorulez
[modkam.ru](modkam.ru)
[В каталоге](https://v2.sprut.ai/catalog/item/modkam-datcik-co2-zigbee)

Тип датчика: co2
Источник питания: usb

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/modkam-datcik-co2-zigbee

**Comment by al-bulanov** [comment]
Вот шаблон для датчика без bme сенсора. 
[AirSense.txt](https://github.com/sprut/Hub/files/6694716/AirSense.txt)

**Comment by yorulez** [comment]
Вот этот шаблон более полный. Для тех у кого на плате есть bme280
[DIYRuZ_AirSense.txt](https://github.com/sprut/Hub/files/6699528/DIYRuZ_AirSense.txt)

**Comment by little-dgek** [comment]
> Вот этот шаблон более полный. Для тех у кого на плате есть bme280
> [DIYRuZ_AirSense.txt](https://github.com/sprut/Hub/files/6699528/DIYRuZ_AirSense.txt)

Добрый день. А вы не сталкивались с тем, что данные приходят раз в час, не смотря на то, что устанавливаешь параметр "не реже 1 раза в " например в 300 секунд?

Так же, не в курсе, как сделать управление светодиодами через спрут?
Делаю что-то типа этого. Но, конечно же, это не работает))

 ```
"options": [
    {
      "link": {
        "endpoint": 1,
        "cluster": "040D_CarbonDioxide",
        "attribute": "0x0203"
      },
      "name": "led_feedback",
      "type": "Boolean",
      "init": true,
      "value": 1,
      "values": [
        {
          "value": false,
          "name": "OFF"
        },
        {
          "value": true,
          "name": "ON"
        }
      ]
    },
```
