### ISSUE TITLE
Некорректная работа сценарного устройства Tuya в Sprut.Hub

### ISSUE THREAD

**Issue by shtoffen** [sprut/Hub#567]
Включатель сценариев добавленный по [Ишью](https://github.com/sprut/Hub/issues/461) с тремя сценарными кнопками без физических реле, определяется в спрутхабе как три выключателя. Необходимо исправить тип устройства в спрутхабе на три программируемые кнопки.
Лог со сниффера устройства в родном хабе, во вложении.
(https://github.com/sprut/Hub/files/6093333/2021-03-05_23-47-01.zip)

Порядок действий:
Одинарное нажатие кнопки 3
Двойное нажатие кнопки 3
Тройное нажатие кнопки 3
Длинное нажатие кнопки 3
В настройках родного хаба какие-либо настройки устройства отсутствуют, только программирование сценариев.

ник в телеграм @Olrich
[Магазин](https://aliexpress.ru/item/4001094931068.html?spm=a2g0s.9042311.0.0.274233edmaxsn3&sku_id=10000014380896605)
[Каталог](https://v2.sprut.ai/catalog/item/lonsonho-zigbee-scenario-switch-220v)

**Comment by sprut666666** [comment]
слишком долго дебажить, родилось больше вопрсов, заказал выключатель
