### ISSUE TITLE
Уровень движения универсального датчика ставится для всех устройств

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#568]
Ревизия: 4361
Дата сборки: 06/03/2021, 04:04:46

Выставляю значение для одного датчика, но именно это значение ставится всем моим датчикам.
![2021-03-06_10-31-34](https://user-images.githubusercontent.com/1624839/110199043-75eb0580-7e67-11eb-98ee-3a5226a9f509.png)

**Comment by sprut666666** [comment]
не удалось воспроизвести, нужно больше вводных

**Comment by andreypopov** [comment]
исправлено уже
