### ISSUE TITLE
Связь с устройством, неправильное сохранение сервиса

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#57]
Виртуальный девайс, делаю связь с устройством, пытаюсь сохранить Коридор:24, но всегда сохраняет Красное:20. При этом девайс не работает, значит все-таки неправильно сохраняется. Подробности в гифке.
![2020-01-08 21 01 33](https://user-images.githubusercontent.com/1624839/72004131-d37fc400-325b-11ea-83a7-564d342503b3.gif)

И еще один визуальный баг, при редактировании не должно быть характеристики "Включен", но и не позволяет сохранить ее. При создании видна только "Яркость"
![2020-01-08_19-48-50](https://user-images.githubusercontent.com/1624839/72003696-f6f63f00-325a-11ea-85b8-5c9c697a5f9d.png)

**Comment by andreypopov** [comment]
SprutHub 1.4.6b
линковка совсем не работает
триггеры работают

**Comment by diamond5170** [comment]
Проверить на 1.5
