### ISSUE TITLE
Отображение значений с датчиков wb и других датчиков, где данные генерируются очень часто.

### ISSUE THREAD

**Issue by sincereman** [sprut/Hub#570]
** Подробное описание ошибки **
Это что-то

**Вводные данные**
На примере датчика  [wirenboard msw 3](https://wirenboard.com/ru/product/wb-msw-v3/)

    Температура: -40°С — +80°С (±0.5°С)
    Влажность: 0 — 98% (±3%)
    Освещенность: 0.02 — 100000 лк
    Уровень шума: 38 — 105 дБ
    Концентрация СО2: 0 — 5000 ppm.
    Концентрация VOC: 0 — 60000 ppb.
    Движение: до 8 м, угол - 120°

**Первая проблема - падение точности при округлении значений с "инертных" (там где значения крайне редко могут меняться рывком за секунды - если только не экстремальные условия) датчиков.**

_Что вызывает проблему._

Получение значения в SH только n раз в единицу времени и округление до выбранного SH класса точности.

**Температура**

В SH последняя температура округляется до 0,5 градуса (20, 20,5, 21) -  у производителя точность +-0,5 градуса - это граничные значения - может быть и идеально ровно и по границе. Округляя последнее значение мы фактически можем получить ошибку уже на 1 градус. Т.е. ошибка датчика плюс ошибка при округлении. 0,5 + 0,5.

Пример с mqtt приходят значения

root@wirenboard-AB3RVWYB:~# mosquitto_sub -v -t '/devices/wb-msw-v3_59/controls/Temperature/#'
/devices/wb-msw-v3_59/controls/Temperature/meta/type temperature
/devices/wb-msw-v3_59/controls/Temperature/meta/readonly 1
/devices/wb-msw-v3_59/controls/Temperature/meta/order 1
/devices/wb-msw-v3_59/controls/Temperature 24.6
/devices/wb-msw-v3_59/controls/Temperature 24.5
/devices/wb-msw-v3_59/controls/Temperature 24.6
/devices/wb-msw-v3_59/controls/Temperature 24.5
/devices/wb-msw-v3_59/controls/Temperature 24.6
/devices/wb-msw-v3_59/controls/Temperature 24.5

В Sh Вижу   | 25.0

Видел бы 25, даже если бы были  - 

/devices/wb-msw-v3_59/controls/Temperature 25.4
/devices/wb-msw-v3_59/controls/Temperature 25.3

Идеально найти решение задачи, изменять отображаемую температуру в SH при изменении значения более чем на 0,2 (так как вижу разбег с датчика 0,1 градуса) градуса.

Вижу несколько решений
1. Установить в настройках аксессуара коридор в котором значения могут быть разбросаны относительно последнего. например при установке в 0,2  - значения не будут меняться до тех пор пока приходящие из mqtt данные не изменятся более чем на 0,2 градуса. Настройку не ограничивать Хоть 5 градусов поставь.

_Пример_
В настройках коридор 0.2

/devices/wb-msw-v3_59/controls/Temperature 24.6 - Так как значений раньше не было в SH ставим 24.6
/devices/wb-msw-v3_59/controls/Temperature 24.5 - не изменяем
/devices/wb-msw-v3_59/controls/Temperature 24.6 - не изменяем
/devices/wb-msw-v3_59/controls/Temperature 24.5 - не изменяем
/devices/wb-msw-v3_59/controls/Temperature 24.4 -  значение изменилось на 0,2 - ставим текущую в SH 24.4 

2. Брать значение не чаще 1 раза в 5 секунд и не округлять его.
3. Высчитывать среднее за последние 5 секунд. (подойдет не для всех датчиков и параметров.)

На выходе хочется получать значения, где температура показана с "**отображаемой** точностью до 0,1 градуса".

**Влажность**

Сейчас округление до  - 5%

Что в выводе mqtt

 mosquitto_sub -v -t '/devices/wb-msw-v3_59/controls/Humidity/#'
/devices/wb-msw-v3_59/controls/Humidity/meta/type rel_humidity
/devices/wb-msw-v3_59/controls/Humidity/meta/readonly 1
/devices/wb-msw-v3_59/controls/Humidity/meta/order 2
/devices/wb-msw-v3_59/controls/Humidity 18.7
/devices/wb-msw-v3_59/controls/Humidity 18.6
/devices/wb-msw-v3_59/controls/Humidity 18.7
/devices/wb-msw-v3_59/controls/Humidity 18.6
/devices/wb-msw-v3_59/controls/Humidity 18.7
/devices/wb-msw-v3_59/controls/Humidity 18.6

То же приемлемое решение, оставить это на усмотрение пользователя системы

1. Установить в настройках аксессуара коридор в котором значения могут быть разбросаны относительно последнего. например при установке в 0.2%  - значения не будут меняться до тех пор пока приходящие из mqtt данные не изменятся более чем на 0,2 процента. Настройку не ограничивать Хоть 5 -10 % поставь.

**Датчик шума** - 5-10 дб.

Датчик шума несколько отличается от температуры и влажности, так как может взрывным характером менять значения.

Немного покричал

/devices/wb-msw-v3_59/controls/Sound Level 37.56
/devices/wb-msw-v3_59/controls/Sound Level 37.47
/devices/wb-msw-v3_59/controls/Sound Level 44.71
/devices/wb-msw-v3_59/controls/Sound Level 60.23
/devices/wb-msw-v3_59/controls/Sound Level 49.36
/devices/wb-msw-v3_59/controls/Sound Level 45.14
/devices/wb-msw-v3_59/controls/Sound Level 38.31

SH показал 50 Дб А это в 9 раз тише данных поступивших с датчика.

А вот условная тишина

 mosquitto_sub -v -t '/devices/wb-msw-v3_59/controls/Sound Level/#'
/devices/wb-msw-v3_59/controls/Sound Level/meta/type sound_level
/devices/wb-msw-v3_59/controls/Sound Level/meta/readonly 1
/devices/wb-msw-v3_59/controls/Sound Level/meta/order 5
/devices/wb-msw-v3_59/controls/Sound Level 37.85
/devices/wb-msw-v3_59/controls/Sound Level 37.13
/devices/wb-msw-v3_59/controls/Sound Level 37.31
/devices/wb-msw-v3_59/controls/Sound Level 37.95
/devices/wb-msw-v3_59/controls/Sound Level 37.7
/devices/wb-msw-v3_59/controls/Sound Level 37.55
/devices/wb-msw-v3_59/controls/Sound Level 37.49
/devices/wb-msw-v3_59/controls/Sound Level 37.71
/devices/wb-msw-v3_59/controls/Sound Level 37.59
/devices/wb-msw-v3_59/controls/Sound Level 38.01
/devices/wb-msw-v3_59/controls/Sound Level 37.94
/devices/wb-msw-v3_59/controls/Sound Level 37.68
/devices/wb-msw-v3_59/controls/Sound Level 37.08
/devices/wb-msw-v3_59/controls/Sound Level 37.56

Предлагаю также отдать точность значений на откуп пользователю, а не округлять до 5 -10 дб

**Датчик движения**
Датчик шума несколько отличается от температуры и влажности, так как может взрывным характером менять значения.
Поэтому в WB для него два параметра используются - current motion (сырые значения) и max motion (округленные за последние n секунд).

_Current motion_

mosquitto_sub -v -t '/devices/wb-msw-v3_59/controls/Current Motion/#'
/devices/wb-msw-v3_59/controls/Current Motion/meta/type value
/devices/wb-msw-v3_59/controls/Current Motion/meta/readonly 1
/devices/wb-msw-v3_59/controls/Current Motion/meta/order 8
/devices/wb-msw-v3_59/controls/Current Motion 2
/devices/wb-msw-v3_59/controls/Current Motion 3
/devices/wb-msw-v3_59/controls/Current Motion 2
/devices/wb-msw-v3_59/controls/Current Motion 1
/devices/wb-msw-v3_59/controls/Current Motion 2
/devices/wb-msw-v3_59/controls/Current Motion 19
/devices/wb-msw-v3_59/controls/Current Motion 20
/devices/wb-msw-v3_59/controls/Current Motion 17
/devices/wb-msw-v3_59/controls/Current Motion 15
/devices/wb-msw-v3_59/controls/Current Motion 14
/devices/wb-msw-v3_59/controls/Current Motion 13
/devices/wb-msw-v3_59/controls/Current Motion 12
/devices/wb-msw-v3_59/controls/Current Motion 11
/devices/wb-msw-v3_59/controls/Current Motion 9
/devices/wb-msw-v3_59/controls/Current Motion 8
/devices/wb-msw-v3_59/controls/Current Motion 7
/devices/wb-msw-v3_59/controls/Current Motion 6
/devices/wb-msw-v3_59/controls/Current Motion 5
/devices/wb-msw-v3_59/controls/Current Motion 6
/devices/wb-msw-v3_59/controls/Current Motion 5
/devices/wb-msw-v3_59/controls/Current Motion 6

Max motion позволяет не пропустить кратковременное движение - собака пробежала. 

mosquitto_sub -v -t '/devices/wb-msw-v3_59/controls/Max Motion/#'
/devices/wb-msw-v3_59/controls/Max Motion/meta/type value
/devices/wb-msw-v3_59/controls/Max Motion/meta/readonly 1
/devices/wb-msw-v3_59/controls/Max Motion/meta/order 7
/devices/wb-msw-v3_59/controls/Max Motion 7
/devices/wb-msw-v3_59/controls/Max Motion 6
/devices/wb-msw-v3_59/controls/Max Motion 36
/devices/wb-msw-v3_59/controls/Max Motion 32
/devices/wb-msw-v3_59/controls/Max Motion 26
/devices/wb-msw-v3_59/controls/Max Motion 20
/devices/wb-msw-v3_59/controls/Max Motion 16
/devices/wb-msw-v3_59/controls/Max Motion 13
/devices/wb-msw-v3_59/controls/Max Motion 10
/devices/wb-msw-v3_59/controls/Max Motion 8
/devices/wb-msw-v3_59/controls/Max Motion 7
/devices/wb-msw-v3_59/controls/Max Motion 6
/devices/wb-msw-v3_59/controls/Max Motion 5

Но в принципе здесь вопросов нет. - значения при реальном движении меняются значительно выше округлений до 5 единиц движения.

**Датчик освещенности**  - 5 лм 

_День_
Значения при реальном изменении освещенности меняются значительно выше округлений до 5 люкс.

_Ночь_

Конечно ночью 0 и  5 люкс это значительная разница. 

Тут нужно придумывать логарифмическую шкалу (а скорее просто ее найти) оценки значений освещенности.

**Датчик CO2** - 10 ppm  (здесь проблем нет)

Так как значения при реальном ухудшении меняются сильно, единственное настройка - хорошо- плохо, то же было бы хорошо чтобы менять. Например открыт окно хорошо еще на 800 ppm, а не на 1000 и тп

**Датчик VOC** - аналогично датчику CO2

** Как воспроизвести ? **
Типичное поведение.

Последняя версия 

Ревизия: 4379
Дата сборки: 08.03.2021, 17:24:21

**Comment by alexey-gamov** [comment]
Введение понятия "дребезг" во все типы датчиков должно пойти на пользу точности съема показаний. Одно дело округлять, другое же отфильтровывать незначительные изменения в заданном пороге.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
