### ISSUE TITLE
WarningDevice-EF-3.0

### ISSUE THREAD

**Issue by tolkachev071** [sprut/Hub#572]
Address: 842E14FFFEF50875/66B8<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 22</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 5</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: WarningDevice-EF-3.0</li><li>0006_DateCode: 2020.8.20</li><li>0007_PowerSource: 129</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 549</li><li>0002_ZoneStatus: 0</li><li>0010_IasCieAddress: 0000000000000000</li><li>0011_ZoneId: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 41</li><li>0021_BatteryPercentageRemaining: 200</li><li>0034_BatteryRatedVoltage: 41</li></ul></li><li>0502_IasWd<ul><li>0000_MaxDuration: 240</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0B05_Diagnostics<ul><li>011C_LastMessageLqi: 176</li><li>011D_LastMessageRssi: -56</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: -1</li><li>0003_CurrentZigbeeStackVersion: 65535</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4619</li><li>0008_ImageTypeId: 16522</li></ul></li></ul></li></ul></li><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE41541D</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>231</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D0005940D03</td><td>3173</td><td>Router</td><td>false</td><td>Sibling</td><td>94</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B001B783002</td><td>6A77</td><td>Router</td><td>false</td><td>Sibling</td><td>116</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00044AE6B7</td><td>77AD</td><td>Router</td><td>false</td><td>Sibling</td><td>123</td><td>UNKNOWN</td><td>15</td></tr><tr><td>BC33ACFFFE11FEBC</td><td>C62E</td><td>Router</td><td>false</td><td>Sibling</td><td>113</td><td>UNKNOWN</td><td>15</td></tr><tr><td>5C0272FFFEDB0476</td><td>CBDC</td><td>Router</td><td>false</td><td>Sibling</td><td>58</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0005867553</td><td>DC43</td><td>Router</td><td>false</td><td>Sibling</td><td>75</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 09 18:28:22 MSK 2021

покупал https://aliexpress.ru/item/4000185176198.html?spm=a2g0s.9042311.0.0.b8a033ed6mWqiR&_ga=2.200211566.1114217094.1615304334-1376271676.1607971782
телеграм Pavel Tolkachev

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-smart-wireless-siren

**Comment by tolkachev071** [comment]
что значит "убрали их значение".?
