### ISSUE TITLE
TS0041

### ISSUE THREAD

**Issue by fazer174** [sprut/Hub#573]
Address: 5C0272FFFECA9FC6/F88B<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 66</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_peszejy7</li><li>0005_ModelIdentifier: TS0041</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Unknown: </li><li>FFE2_Unknown: 28</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>000A_Time<ul><li>0007_LocalTime: 668626177</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 09 20:36:10 MSK 2021

Павел Шмидт
https://aliexpress.ru/item/4001095272467.html?spm=a2g0s.9042311.0.0.275233edXDcOgr&_ga=2.3445168.1838847452.1615312094-72932028.1594656208
похож на этот https://v2.sprut.ai/catalog/item/lonsonho-zigbee-wireless-scene-switch-1ch

**Comment by Batyushin** [comment]
Режим спаривания, сброса?
Количество нажатий?



https://v2.sprut.ai/catalog/item/lonsonho-zigbee-wireless-scene-switch-1ch

**Comment by fazer174** [comment]
Я новичок в этом. 
Что именно интересует?
Он спаривается, но пишет нет шаблона

С уважение,
Шмидт П.Е.



среда, 10 марта 2021 г., 01:33 +0700 от ***@***.***  ***@***.***>:

**Comment by fazer174** [comment]
Вообще в описании написано что есть одинарное, двойное и долгое удерживание

С уважение,
Шмидт П.Е.



среда, 10 марта 2021 г., 01:33 +0700 от ***@***.***  ***@***.***>:

**Comment by Batyushin** [comment]
а как ввести его в режим спаривания?

**Comment by fazer174** [comment]
Удержанием кнопки на 5 секунд

С уважение,
Шмидт П.Е.



среда, 10 марта 2021 г., 01:42 +0700 от ***@***.***  ***@***.***>:
