### ISSUE TITLE
TS0601 -AM43 рулонная штора

### ISSUE THREAD

**Issue by acidmad** [sprut/Hub#574]
Address: 847127FFFE17BD01/6737<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 71</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_rddyvrci</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 09 23:08:03 MSK 2021

P.s. Ревизия: 4376 логи по кнопке в веб интерфейсе не скачиваются пробовал несколько раз и в разных браузерах.  
[2021-03-09_22-20-09.pcap.zip](https://github.com/sprut/Hub/files/6111139/2021-03-09_22-20-09.pcap.zip)

Метод спаривания:  зажать кнопку set+вниз на 3сек заморгает синим светодиод

Телеграм: @acidmad
В каталоге: https://v2.sprut.ai/catalog/item/moeshouse-zigbee-motorizovannaa-rulonnaa-stora 
Покупал тут:  https://aliexpress.ru/item/1005001698400295.html?spm=a2g0s.9042311.0.0.745933ediyh7Kn&_ga=2.240630851.17928922.1615321024-1991711596.1615321024

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-zigbee-motorizovannaa-rulonnaa-stora

**Comment by acidmad** [comment]
Не будет с туей позитива?
