### ISSUE TITLE
Добавить тип Вентилятор

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#58]
Модуль https://wirenboard.com/ru/product/WBIO-AO-10V-8/
У меня он управляет вытяжкой, пожалуйста, надо добавить.

![2020-01-13_19-12-14](https://user-images.githubusercontent.com/1624839/72271834-ac990780-3638-11ea-9a3a-1e9b9cf01c3c.png)

**Comment by diamond5170** [comment]
Функция смены типа пока под вопросом, т.к. ее некорректно обрабатывает хомкит.
Рекомендуется создавать виртуальное устройство и линковать, вместо смены типа.
