### ISSUE TITLE
PGC410

### ISSUE THREAD

**Issue by Co1dSUN** [sprut/Hub#587]
Address: D052A800DD3C0005/A49A<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 4</li><li>0002_StackVersion: 71</li><li>0003_HwVersion: 3</li><li>0004_ManufacturerName: SmartThings</li><li>0005_ModelIdentifier: PGC410</li><li>0006_DateCode: 130324</li><li>0007_PowerSource: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4362</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Mar 13 17:59:54 UTC 2021
[2021-03-13_16-19-24.zip](https://github.com/sprut/Hub/files/6135458/2021-03-13_16-19-24.zip)

Сброс удержанием кнопки под крышкой в течении примерно 6 секунд, пока не погаснет лампочка. Потом при спаривании один раз кратко нажать на эту же кнопку.

[Моя телега](https://t.me/ColdSUN)
[устройство в каталоге](https://v2.sprut.ai/catalog/item/smartthings-devices-smartthings-arrival-sensor)
Покупался очень давно в стартовом комплекте SmartThings V2.

**Comment by Batyushin** [comment]
просьба заполнить соблюдая все требования
https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

**Comment by Co1dSUN** [comment]
> просьба заполнить соблюдая все требования
> https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

Так?

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/smartthings-devices-smartthings-arrival-sensor

**Comment by Batyushin** [comment]
![image](https://user-images.githubusercontent.com/34019762/111061209-351c6d80-84b3-11eb-8fc5-0915f8d9b4b5.png)

**Comment by Co1dSUN** [comment]
Сорри, не понял сразу, чего не хватает.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/smartthings-devices-smartthings-arrival-sensor
