### ISSUE TITLE
Периодически отваливаются моторы авара В1 (беспроводные)

### ISSUE THREAD

**Issue by Slider007** [sprut/Hub#589]
** Подробное описание ошибки **
- Периодически отваливаются моторы Акбара В1 (беспроводные)
- очень долго(до 10 минут) приходит сообщение о протечке от датчика авары

** Как воспроизвести ? **
ничего не трогаю в в системе - само все отваливается.
иногда в карте висит как присоединенной, но по факту не отвечает

** Ожидаемое поведение **
открывание и закрывание штор

** Скриншоты/ Логи **
Приложил
[
[logs.zip](https://github.com/sprut/Hub/files/6136398/logs.zip)
![2021-03-14_12-46-09](https://user-images.githubusercontent.com/16690768/111064135-71f06080-84c3-11eb-988a-695f0ece83ff.png)
](url)
** Пожалуйста, заполните следующую информацию: **
  - Версия: Ревизия: 4379 Дата сборки: 08.03.2021, 17:24:21
  - стоит все на малинке , присоединено все витой парой

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
решаем в оперативном режиме
