### ISSUE TITLE
WB-RGBW в режиме 4 белых лент, проблемы использования

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#59]
Проблема: 
1) выбирать локацию девайса неправильно, потому что каждый канал может быть в разных помещениях
2) у добавленного в ХК аксессуара может быть только 1 локация, даже если разбить на плитки

Получается, что без виртуальных девайсов нельзя использовать этот модуль.
Я хочу сказать, что каждый канал, должен быть отдельным аксессуаром.
Может можно сделать, чтобы СХ создавал сразу 5-6 аксессуаров, а пользователь бы сам выбирал какие из них использовать в хк.  
1-4) белый 1-4 каналы
5) rgb
6) W белый
Виртульные девайсы хорошо, но это выглядит как workaround и решение не из коробки.

![2020-01-13_21-48-40](https://user-images.githubusercontent.com/1624839/72282909-b75e9700-364e-11ea-901f-64afc3c24743.png)

**Comment by dragaleff** [comment]
+1

**Comment by diamond5170** [comment]
Разделения на каналы "из коробки" больше не будет, вместо этого добавим в интерфейсе возможность вручную указывать составную часть RGBW при линковке. Тогда вы сможете создать нужный вам аксессуар и пролинковать на нужный канал.

**Comment by Alxprv** [comment]
#232 тут решено
