### ISSUE TITLE
Door/window Z-Wave sensor Spetu

### ISSUE THREAD

**Issue by naumserg74** [sprut/Hub#591]
<b>0214 - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>9</td></tr><tr><td width=35%>Manufacturer Id</td><td>0214</td></tr><tr><td width=35%>Device Type</td><td>0002</td></tr><tr><td width=35%>Device Id</td><td>0001</td></tr><tr><td width=35%>App Version</td><td>6.38</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Sensor Notification</td></tr><tr><td width=35%>Specific Class</td><td>Notification Sensor</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>1</td></tr><tr><td>2</td><td> Sensor Basic Set</td><td>[]</td><td>2</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 AssociationGRPInfo</li><li>V1 Basic</li><li>V2 Version</li><li>V1 ZWavePlusInfo</li><li>V4 Alarm<ul><li>Burglar</li><li>AccessControl</li></ul></li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 DeviceResetLocally</li><li>V2 ManufacturerSpecific</li><li>V2 WakeUp<ul><li>Current: 1d</li><li>Default: 1d</li><li>Min: 30m</li><li>Max: 1d</li><li>Step: 3m</li></ul></li><li>V1 Battery</li><li>V1 NoOperation</li><li>V2 SensorBinary<ul><li>DoorWindow</li><li>Tamper</li></ul></li><li>V2 Association</li><li>V1 Configuration</li></ul></li></ul><br>Last update: Sun Mar 14 18:24:14 YEKT 2021

Покупал тут:
https://aliexpress.ru/item/32890719924.html?spm=a2g0o.productlist.0.0.71842909ghhlrG&algo_pvid=138eeaa0-5d62-437d-a7df-86ffd2a92243&algo_expid=138eeaa0-5d62-437d-a7df-86ffd2a92243-8&btsid=0b8b034c16157284353992363e701d&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_&sku_id=65685790866

**Comment by naumserg74** [comment]
Переделал темплейт от аналогичных китайских датчиков NEO-Coolcam  model: NAS-DS01Z  (ID:2346). Закинул его в каталог Custom. В принципе работает. Можно и так оставить. 
[DoorWindowSensor.json.zip](https://github.com/sprut/Hub/files/8357160/DoorWindowSensor.json.zip)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/spetu-door-window-z-wave-sensor

**Comment by permadm** [comment]
Готово
