### ISSUE TITLE
ZB-SW01 Ewelink ZigBee модуль реле дистанционного Управление светильник переключатель

### ISSUE THREAD

**Issue by EShchepilov** [sprut/Hub#598]
DC5-32v Ewelink ZigBee модуль реле дистанционного Управление светильник переключатель работы с Alexa Google Home Sonoff/Tuya Smart Hub шлюз мост
https://star.aliexpress.com/share/share.htm?image=Udea67216b6b245c1bc9be53e1e913ebdo.jpg&businessType=ProductDetail&title=726%2C51%20%D1%80%D1%83%D0%B1.%20%20-57%EF%BC%85%20%7C%20DC5-32v%20Ewelink%20ZigBee%20%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C%20%D1%80%D0%B5%D0%BB%D0%B5%20%D0%B4%D0%B8%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%81&platform=AE&redirectUrl=https%3A%2F%2Fwww.aliexpress.com%2Fitem%2F1005002235115922.html%3F%26srcSns%3Dsns_Copy%26tid%3Dwhite_backgroup_101%26mb%3DM3Zewqn3Q6oGqN7%26businessType%3DProductDetail%26spreadType%3DsocialShare

![image](https://user-images.githubusercontent.com/77865103/111308834-3b097e80-866c-11eb-8c25-f93426705a0b.jpeg)

![image](https://user-images.githubusercontent.com/77865103/111308865-42308c80-866c-11eb-9147-b3d623c42a52.jpeg)

Address: 00124B00226B6835/A0D7<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 4</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW01</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 1.0.3</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 4</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW01</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 1.0.3</li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 16 15:20:18 MSK 2021

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ewelink-dc5-32v-zigbee433-modul-rele-distancionnogo-upravlenia

**Comment by EShchepilov** [comment]
Можно добавить? 
Хочу включить обьединение систем через сухой контакт
