### ISSUE TITLE
Проблема работы esphome в spruthub

### ISSUE THREAD

**Issue by klouner** [sprut/Hub#599]
Добавил в СХ устройство с прошивкой esphome, по инструкции https://wiki.sprut.ai/ru/spruthub/accessory/MQTT_ESPHome
в esphome выведен простой switch, который посылает rf команду на открытие шлагбаума.
Выглядит примерно так:
```
esphome:
  name: spruthub_esphome_rf
...
remote_transmitter:
  pin: D3  
...
switch:
  - platform: template
    name: RF_Shlagbaum
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: 'XXXXXXXX*XXXX'
          protocol: 1
```
          
Для СХ написал шаблон обработки MQTT:
```
{
  "name": "Шлагбаум",
  "manufacturer": "ESPHome",
  "model": "ESP8266",
  "services": [
    {
      "type": "Switch",
      "characteristics": [
        {
          "type": "On",
          "link": {
            "type": "String",
            "topicSearch": "spruthub_(.*)/switch/(.*)/state",
            "topicGet": "spruthub_(1)/switch/(2)/state",
            "topicSet": "spruthub_(1)/switch/(2)/command",
            "map": {
              "false": "OFF",
              "true": "ON"
            }
          }
        }
      ]
    }
  ]
}
```
В СХ появился выключатель, прокинул его через виртуальное устройство "Гаражные ворота".
Единственный корректно работающий для меня вариант был у свича поставить switchOffTime на 10 и Inversed = on.
Далее связка с параметром виртуального устройства "Целевой режим двери" свича. 

Поведение при текущий настройках: Жмем на открытие ворот, статус быстро переключается на открытие и обратно. Т.к. всяких положений у уличного шлагбаума отследить не удается, этого достаточно. 

**Подробное описание ошибки**
С периодичностью раз в час в логах вижу следующее
```
| --> spruthub_esphome_rf/switch/rf_shlagbaum/command, msg: 'ON' |  
| <-- spruthub_esphome_rf/switch/rf_shlagbaum/state, retained: false, msg: 'OFF'
```
Ну и соответсвенно шлагбаум на придомовой территории сам по себе открывается. 
Еще это происходит при обновлении/перезагрузки СХ.
```
| <-- spruthub_esphome_rf/status, retained: true, msg: 'online'
| <-- esphome_rf/switch/rf_shlagbaum/command, retained: true, msg: ''
| <-- spruthub_esphome_rf/switch/rf_shlagbaum/state, retained: true, msg: 'OFF'
| <-- spruthub_esphome_rf/switch/rf_shlagbaum/command, retained: true, msg: 'OFF'
| <-- spruthub_esphome_rf/sensor/test_uptime_sensor/state, retained: true, msg: '5563'
```
Прошу обратить внимание на вторую строку, такое название я нигде не задавал. ветка создается сама, пробовал насильно удалять, при перезагрузке появляется.

**Как воспроизвести ?**
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Сидишь на попе ровно
2. Шлагбаум поднимается раз в час
3. Соседи вызывают священников

**Ожидаемое поведение**
Открытие только через сири. Без фантомных срабатываний.

**Скриншоты/ Логи**
[logs (2).zip](https://github.com/sprut/Hub/files/6149019/logs.2.zip)

**Пожалуйста, заполните следующую информацию:**
  - Версия СХ: 1.6.8b, Ревизия: 4459, Дата сборки: 16.03.2021, 12:30:51
  - Версия IOS 14.5

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
