### ISSUE TITLE
Ошибка Zigbee

### ISSUE THREAD

**Issue by Popov2006** [sprut/Hub#6]
После установки ПО SprutHub на WB и ввода команд рекомендованных к применению относительно модуля WBE2R-R-ZIGBEE
модуль работал, подцепил одно устройство (детектор движения)

Далее

установил на WB Node-Red сразу пошли ошибки по Zigbee

I | 2019-07-03 | 11:58:48.449 | o.m.SprutHub.Controllers.ZigBee.e        281 | Status: OFFLINE
W | 2019-07-03 | 11:58:48.447 | org.makesimple.ZigBee.s                  181 | Error closing serial port: '/dev/ttyMOD3'
E | 2019-07-03 | 11:58:48.446 | o.m.ZigBee.dongle.cc2531.network.e       287 | Failed to start zigbee network.
I | 2019-07-03 | 11:58:47.580 | o.m.SprutHub.Controllers.ZigBee.e        271 | Config: zigbee_trustcentremode=TC_JOIN_INSECURE
I | 2019-07-03 | 11:58:47.578 | o.m.SprutHub.Controllers.ZigBee.e        246 | Status: COMMUNICATION_ERROR
I | 2019-07-03 | 11:58:47.575 | o.m.SprutHub.Controllers.ZigBee.e        557 | Status: OFFLINE
E | 2019-07-03 | 11:58:47.571 | o.m.ZigBee.dongle.cc2531.network.e       266 | Failed to open the dongle.
W | 2019-07-03 | 11:58:47.569 | org.makesimple.ZigBee.s                  96  | Unable to open serial port: Serial port already open.

SprutHub пишет что порт уже открыт.

в консоле при наборе команды service zigbee2mqtt stop пишет, что сервис не запущен
root@wirenboard-AIC2JCL6:~# service zigbee2mqtt stop
Failed to stop zigbee2mqtt.service: Unit zigbee2mqtt.service not loaded.

**Comment by sprut666666** [comment]
скорее всего ты перезагрузил вайрон и не восстановил права,

После каждой перезагрузки для WBE2R-R-ZIGBEE
chown root:dialout /dev/ttymxc6
chmod -R 777 /dev/ttymxc6

после этого перезагружаем сервис
service spruthub restart

как только WB внесут правки, такого костыля не будет.

**Comment by Popov2006** [comment]
Да, мой косяк. Все работает
