### ISSUE TITLE
выключатель 2 клавишный Tuya _TZE200_dhdstcqc

### ISSUE THREAD

**Issue by ohbotya** [sprut/Hub#600]
Address: EC1BBDFFFE69C0CC/941C<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 64</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_dhdstcqc</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 16 19:55:41 MSK 2021

**Comment by ohbotya** [comment]
[logs.zip](https://github.com/sprut/Hub/files/6150983/logs.zip)
Наличие нуля - да
Количество клавиш - 2 механические
типа такого https://aliexpress.ru/item/1005002146686156.html?spm=a2g0o.detail.0.0.307e2eacpBhMYz&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.169870.0&scm_id=1007.13339.169870.0&scm-url=1007.13339.169870.0&pvid=41bc66b2-f35f-49fc-acd1-080615ce9179&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.169870.0,pvid:41bc66b2-f35f-49fc-acd1-080615ce9179,tpp_buckets:21387%230%23183380%230&_ga=2.92230618.1710051062.1615888059-375268901.1578304154&sku_id=12000018886203759

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/benexmart-knopocnyj-vyklucatel

**Comment by sprut666666** [comment]
без физического устройства добавить не смогу
