### ISSUE TITLE
Zigbee OnOff Controller для SmartThings

### ISSUE THREAD

**Issue by ohbotya** [sprut/Hub#601]
Вообще не добавилось, даже не снять характеристики железки, пробовал на 11 и 20 канале добавить

[куплено тут](https://aliexpress.ru/item/32966584298.html?spm=a2g0s.9042311.0.0.264d33ed3hkoWA&_ga=2.88053080.1710051062.1615888059-375268901.1578304154)

**Comment by Batyushin** [comment]
С каким-то другим хабом сопрягается, может брак?

**Comment by ohbotya** [comment]
с туей не хочет, а самсунговского нету((

**Comment by ohbotya** [comment]
[вот оно же ](https://aliexpress.ru/item/1000008194738.html?spm=a2g0o.productlist.0.0.ad676344Ftzf07&algo_pvid=39468f50-a2b2-4201-8224-06153c584632&algo_expid=39468f50-a2b2-4201-8224-06153c584632-50&btsid=0b8b036316159206519598738e948b&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/noname-zigbee-on-off-controller

**Comment by sprut666666** [comment]
Похоже на брак устройства, остальное подключается ?
