### ISSUE TITLE
ORVIBO (HOMMYN) 3-channel relay 

### ISSUE THREAD

**Issue by ohbotya** [sprut/Hub#604]
Address: 00124B0015388108/1A6A<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 16 22:12:35 MSK 2021
[Продается тут](https://aliexpress.ru/item/32859028838.html?spm=a2g0o.detail.0.0.a0885181VbfZ5B&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.169870.0&scm_id=1007.13339.169870.0&scm-url=1007.13339.169870.0&pvid=b26c7381-857f-477e-a45f-635cdca7940e&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.169870.0,pvid:b26c7381-857f-477e-a45f-635cdca7940e,tpp_buckets:21387%230%23183380%230&_ga=2.127766989.1710051062.1615888059-375268901.1578304154&sku_id=65364497214)
без мониторинга
oh_botya

**Comment by ohbotya** [comment]
на устройстве перемычками включаются разные режимы работы
1) управление электромотором с подачей напряжения до полного открытия/закрытия и стоп в любой точке
2) режим обычного реле 3 независимых канала (вкл/выкл)
3) режим кратковременного замыкания той или иной пары (эмуляция нажатия клавиши)
лог сделан в этой последовательности / в каждом режиме делалось открытие закрытие и стоп . в режиме 3 реле делалось вкл/выкл

**Comment by ohbotya** [comment]
Address: 00124B0015388108/4BDF<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li><li>0102_WindowCovering<ul><li>0000_WindowCoveringType: 4</li><li>0001_PhysicalClosedLimitLift: 0</li><li>0002_PhysicalClosedLimitTilt: 0</li><li>0003_CurrentPositionLift: 0</li><li>0004_CurrentPositionTilt: 0</li><li>0005_NumberOfActuationsLift: 0</li><li>0006_NumberOfActuationsTilt: 0</li><li>0007_ConfigStatus: 3</li><li>0008_CurrentPositionLiftPercentage: 0</li><li>0009_CurrentPositionTiltPercentage: 0</li><li>0010_InstalledOpenLimitLift: 0</li><li>0011_InstalledClosedLimitLift: 65535</li><li>0012_InstalledOpenLimitTilt: 0</li><li>0013_InstalledClosedLimitTilt: 65535</li><li>0014_VelocityLift: 0</li><li>0015_AccelerationTimeLift: 0</li><li>0016_DecelerationTimeLift: 0</li><li>0017_Mode: 20</li><li>0018_IntermediateSetpointsLift: ByteArray [value=00]</li><li>0019_IntermediateSetpointsTilt: ByteArray [value=00]</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ORVIBO</li><li>0005_ModelIdentifier: 82c167c95ed746cdbd21d6817f72c593</li><li>0006_DateCode: 2017-08-16</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: v3.1.05</li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Mar 16 23:18:50 MSK 2021

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/orvibo-neutral-smart-switch-3-gang

**Comment by ohbotya** [comment]
![image](https://user-images.githubusercontent.com/80760841/111525157-52309500-876e-11eb-885c-85b15d030c1b.png)
а закрытие что значит?
