### ISSUE TITLE
orvibo (hommyn) door/window

### ISSUE THREAD

**Issue by ohbotya** [sprut/Hub#605]
Address: 00124B000A99D404/2302<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: v1.13_20151212</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: 欧瑞</li><li>0005_ModelIdentifier: 75a4bfe8ef9c4350830a25d13e3ab068</li><li>0006_DateCode: 20151210        </li><li>0007_PowerSource: 3</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 21</li><li>0002_ZoneStatus: 288</li></ul></li><li>0001_PowerConfiguration<ul><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li><li>07C5_Custom: 00124B000A99D404</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Tue Mar 16 23:22:32 MSK 2021

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/orvibo-door-or-window-contact-switch
