### ISSUE TITLE
Уже неделю так работает

### ISSUE THREAD

**Issue by Krylov9** [sprut/Hub#606]
Уже неделю так работает обновления не помогают
[logs.zip](https://github.com/sprut/Hub/files/6154411/logs.zip)

**Comment by sprut666666** [comment]
1) https://wiki.sprut.ai/ru/spruthub/info/make-correct-questions описания проблемы 0
2) Стоят лишние галки которые не просили ставить
3) Подобного рода вопросы решаются оперативно в режиме реального времени в чате поддержки
