### ISSUE TITLE
Расширить/добавить новую опцию в алгоритм работы SwitchOffTime

### ISSUE THREAD

**Issue by meowlab-net** [sprut/Hub#61]
Хорошо бы иметь возможность средствами виртуальной логики, без использования движка правил, реализовать следующие кейсы:

1. По срабатыванию датчика движения включить выключатель, розетку или лампу. По выключению тревоги на движение, через установленный временной промежуток выключить включенный выключатель, розетку или лампу. Если в установленный промежуток времени после выключения тревоги датчик движения опять срабатывает, начать отсчет промежутка времени заново не выключая устройство.
2.  При включении например лампы в ванной, автоматически включать вытяжку (вентилятор). При выключении лампы в ванной, выключать вытяжку через определенный промежуток времени. Если в данный промежуток времени после выключения лампы ее опять включат, начать отсчет промежутка времени заново, не выключая вытяжку. 

Текущая реализация параметра  SwitchOffTime у аксессуара розетка, выключатель, лампочка - автоматически выключает аксессуар через установленный в  SwitchOffTime промежуток времени.
Т.е. применительно к кейсу №1. На датчике движения делаем триггер, на включение лампы. На лампе устанавливаем SwitchOffTime например 2 мин. (120000).
Сработает датчик движения, включится лампа. Если будет продолжаться движение, лампа все равно выключиться через 2 мин. после включения.

**Comment by MakeSimpleOrg** [comment]
Сейчас таймер продлевается каждое движение. Закрываю, т.к. не актуально. Если потребуется оформите новый.
