### ISSUE TITLE
Стоповые биты

### ISSUE THREAD

**Issue by rufusgor** [sprut/Hub#610]
** Подробное описание ошибки **
Нельзя поставить стоп бит в 1, из-за этого нельзя подключить по modbus устройства других производителей.

** Пожалуйста, заполните следующую информацию: **
Ревизия: 4478
Дата сборки: 19.03.2021, 15:34:59

**Comment by sprut666666** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/24498195/111870152-0cedac80-8994-11eb-93ab-1215606ee498.png">
в настройках выставить 1

**Comment by rufusgor** [comment]
Поставил 1, после находит только устройство WB-MSW3, у него стоп бит 2.
<img width="791" alt="Снимок экрана 2021-03-20 в 15 53 29" src="https://user-images.githubusercontent.com/1449265/111870268-bcc31a00-8994-11eb-9691-5422d7fdb2d5.png">
