### ISSUE TITLE
SensoAIR SIEGENIA AUBI - Sensoair Z-Wave CO2 Sensor - Wall (EU)

### ISSUE THREAD

**Issue by WinManMC** [sprut/Hub#619]
http://manuals-backend.z-wave.info/make.php?lang=en&sku=SIG_SENS_W&cert=ZC08-09080006

https://www.siegenia.com/ru/company/latest-news

Siegenia Aubi
Sensoair Z-Wave CO2 Sensor - Wall
SKU: SIG_SENS_W

<b>Siegenia - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>3</td></tr><tr><td width=35%>Manufacturer Id</td><td>0081</td></tr><tr><td width=35%>Device Type</td><td>00A0</td></tr><tr><td width=35%>Device Id</td><td>0001</td></tr><tr><td width=35%>App Version</td><td>1.4</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Sensor MultiLevel</td></tr><tr><td width=35%>Specific Class</td><td>Routing Sensor MultiLevel</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td></td><td>[]</td><td>5</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 Basic</li><li>V1 Version</li><li>V3 SensorMultiLevel<ul></ul></li><li>V1 SensorConfiguration</li><li>V1 Configuration</li><li>V1 Association</li><li>V1 ManufacturerSpecific</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 NoOperation</li></ul></li></ul><br>Last update: Thu Mar 25 21:13:57 MSK 2021

**Comment by WinManMC** [comment]
Устройство идет в комплекте с проветривателями АэроПак той же фирмы

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/siegenia-sensoair-aubi

**Comment by WinManMC** [comment]
> https://v2.sprut.ai/catalog/item/siegenia-sensoair-aubi

Наличие  в каталоге не гарантирует работоспособность к сожалению


![IMG_1240](https://user-images.githubusercontent.com/72528825/112632466-36518100-8e49-11eb-8bbd-41a4f8014820.jpeg)
![IMG_1239](https://user-images.githubusercontent.com/72528825/112632482-3b163500-8e49-11eb-9451-6d263fdefb45.jpeg)

**Comment by MakeSimpleOrg** [comment]
Добавлен
