### ISSUE TITLE
SML001

### ISSUE THREAD

**Issue by meowlab-net** [sprut/Hub#62]
Родного хаба нет.

Address: 0017880102118504/7D01<br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY, MAINS, DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>4000_SwBuildId: 6.1.0.18912</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: SML001</li><li>0006_DateCode: 20160630</li><li>0007_PowerSource: 3</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: SML001</li><li>0006_DateCode: 20160630</li><li>0007_PowerSource: 3</li></ul></li><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 7982</li><li>0001_MinMeasuredValue: 1</li><li>0002_MaxMeasuredValue: 65534</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 22</li><li>0021_BatteryPercentageRemaining: 1</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2854</li><li>0001_MinMeasuredValue: -27315</li><li>0002_MaxMeasuredValue: 32767</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0406_OccupancySensing<ul><li>0000_Occupancy: 0</li><li>0010_PirOccupiedToUnoccupiedDelay: 0</li><li>0001_OccupancySensorType: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br>Last update: Mon Jul 06 19:54:36 MSK 2020

Девайс в каталоге https://v2.sprut.ai/catalog/item/philips-motion-sensor
Телеграмм @meowlab

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by sprut666666** [comment]
Без устройства, добавить не смогу.
Заказал, жду.

**Comment by sprut666666** [comment]
1.6.4
