### ISSUE TITLE
TS0201

### ISSUE THREAD

**Issue by lorond** [sprut/Hub#620]
Address: 5C0272FFFEA16120/3456<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 67</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ2000_a476raq2</li><li>0005_ModelIdentifier: TS0201</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 26</li><li>0021_BatteryPercentageRemaining: 100</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2860</li></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 4610</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>512</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>512</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Mar 26 14:25:17 MSK 2021

ник: @lorond
покупал: https://aliexpress.ru/item/4000843004202.html
каталог: https://v2.sprut.ai/catalog/item/tuya-zigbee-umnyj-domasnij-datcik-temperatury-i-vlaznosti
тип датчика: температура и относительная влажность
версия zigbee: ???
режим спаривания: удержание кнопка 5 секунд
источник питания: AAA батарейки 2 шт.
передаваемые значения температуры и влажности соответствуют измеренному значению * 100 (значения выше получены при 28.6 *С и 46.1 % влажности).

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tuya-zigbee-umnyj-domasnij-datcik-temperatury-i-vlaznosti
