### ISSUE TITLE
COSensor-EF-3.0

### ISSUE THREAD

**Issue by imrche** [sprut/Hub#623]
Address: EC1BBDFFFEADA97C/4F3D<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 17</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 16</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: COSensor-EF-3.0</li><li>0006_DateCode: 2019.9.5</li><li>0007_PowerSource: 3</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 43</li><li>0002_ZoneStatus: 32</li><li>0010_IasCieAddress: 0000000000000000</li><li>0011_ZoneId: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 32</li><li>0021_BatteryPercentageRemaining: 200</li><li>0034_BatteryRatedVoltage: 30</li></ul></li><li>0502_IasWd<ul><li>0000_MaxDuration: 240</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>011C_LastMessageLqi: 124</li><li>011D_LastMessageRssi: -69</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 17</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4619</li><li>0008_ImageTypeId: 16514</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Mar 27 07:43:15 UTC 2021

- [richy_nsk](https://t.me/richy_nsk)
- покупал на [ali](https://aliexpress.ru/item/4000209418201.html?spm=a2g0s.9042311.0.0.264d33edUTHr8K&_ga=2.62495150.327749512.1616828548-1677827172.1608394017)
- датчик СО
- протокол Zigbee 1.2
- питание CR123A/CR17335
- режим спаривания: зажатая на 2 секунды кнопка спаривания

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-smart-carbon-monoxide-sensor-2
