### ISSUE TITLE
SmartThings Multipurpose sensor 3321-S

### ISSUE THREAD

**Issue by Co1dSUN** [sprut/Hub#625]
Address: 000D6F000BBDF678/3D00<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: CentraLite</li><li>0005_ModelIdentifier: 3321-S</li><li>0006_DateCode: ����������������</li><li>0007_PowerSource: 3</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 14400</li><li>0001_LongPollInterval: 24</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li><li>0004_CheckinIntervalMin: 240</li><li>0005_LongPollIntervalMin: 23</li><li>0006_FastPollTimeoutMax: 120</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 21</li><li>0002_ZoneStatus: 37</li><li>0010_IasCieAddress: FFFFFFFFFFFFFFFF</li><li>0011_ZoneId: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 25</li><li>0031_BatterySize: 2</li><li>0033_BatteryQuantity: 1</li><li>0036_BatteryVoltageMinThreshold: 21</li><li>003E_BatteryAlarmState: 0</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2562</li><li>0001_MinMeasuredValue: -4000</li><li>0002_MaxMeasuredValue: 6000</li><li>0003_Tolerance: 150</li></ul></li><li>FC02_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0100_MacRxBcast: 134348800</li><li>0101_MacTxBcast: 134348800</li><li>0102_MacRxUcast: 134348835</li><li>0103_MacTxUcast: 134348856</li><li>0104_MacTxUcastRetry: 5</li><li>0105_MacTxUcastFail: 1</li><li>0106_ApsRxBcast: 3</li><li>0107_ApsTxBcast: 2</li><li>0108_ApsRxUcast: 18</li><li>0109_ApsTxUcastSuccess: 10</li><li>011C_LastMessageLqi: 255</li><li>011D_LastMessageRssi: -56</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 520573712</li><li>0003_CurrentZigbeeStackVersion: 65535</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigbeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4174</li><li>0008_ImageTypeId: 14</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0003_Identify<ul></ul></li><li>0B05_Diagnostics<ul></ul></li><li>FC0F_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4174</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Mar 27 20:23:39 UTC 2021

[2021-03-27_20-15-06.zip](https://github.com/sprut/Hub/files/6216392/2021-03-27_20-15-06.zip)
После спаривания несколько раз поднёс магнит и убрал. Потом постучал по столу и самому датчику. Потом взял его в руки и покрутил по все трём осям по очереди.
Могу приложить видео из интерфейса родного хаба, там в реальном времени отображается происходящее.

Для сброса необходимо вынуть батарейку, зажать кнопку спаривания, и удерживать её подключить батарейку обратно. После загорания светодиода отпустить кнопку.

[Мой телеграмм](https://t.me/ColdSUN)
[Устройство в каталоге](https://v2.sprut.ai/catalog/item/smartthings-devices-smartthings-multi-sensor-2015-model)
Сейчас такие сенсоры новые уже не продаются, но на ebay их достаточно много, за адекватные деньги. У меня стоит на входной двери, батарейки CR2450 хватает на пару лет. В родном хабе было приложение, которое при помощи этого датчика определяло, что в двери кто-то стучит.
[2021-04-12_16-21-25.zip](https://github.com/sprut/Hub/files/6298274/2021-04-12_16-21-25.zip)

**Comment by Co1dSUN** [comment]
Add: Обнаружил, что похоже dump был пустой. Добавил новый.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/smartthings-devices-smartthings-multi-sensor-2015-model

**Comment by Co1dSUN** [comment]
Сейчас добавил этот датчик в свой СХ, до этого был только на тестовом. И вдруг понял, что нет акселерометра. А он вообще-то там есть. Олег, может получится добавить?
