### ISSUE TITLE
LLC020

### ISSUE THREAD

**Issue by stanislavprokopov** [sprut/Hub#626]
Address: 001788010119A28E/BD1F<br><br><b>Structure</b><br><ul><li>Endpoint 242<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: LLC020</li><li>0006_DateCode: 20191216</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 5.130.1.30000</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 32</li><li>0001_CurrentSaturation: 140</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 29972</li><li>0004_CurrentY: 26871</li><li>0007_ColorTemperature: 366</li><li>0008_ColorMode: 2</li><li>4000_EnhancedCurrentHue: 8418</li><li>4001_EnhancedColorMode: 2</li><li>4002_ColorLoopActive: 0</li><li>4003_ColorLoopDirection: 0</li></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 102</li><li>0001_RemainingTime: 0</li><li>4000_StartUpCurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 1107326256</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4107</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>842E14FFFE1392CB</td><td>53AB</td><td>Router</td><td>false</td><td>Parent</td><td>252</td><td>ENABLED</td><td>1</td></tr><tr><td>60A423FFFE415571</td><td>0000</td><td>Coordinator</td><td>false</td><td>Unknown</td><td>255</td><td>ENABLED</td><td>0</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>71</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>45</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>45</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS, RECHARGABLE_BATTERY, DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Mar 31 22:04:06 MSK 2021

<br>

**Log**:
```
22:04:16 | SourceRoute: index = 3, destination = FFFF, closerIndex = 255, status = EMBER_SUCCESS |  
-- | -- | --
22:04:16 | SourceRoute: index = 2, destination = BD1F, closerIndex = 0, status = EMBER_SUCCESS |  
22:04:16 | SourceRoute: index = 1, destination = 1024, closerIndex = 255, status = EMBER_SUCCESS |  
22:04:16 | SourceRoute: index = 0, destination = 53AB, closerIndex = 255, status = EMBER_SUCCESS |  
22:04:02 | 001788010119A28E/BD1F: Обновление не требуется |  
22:04:02 | Device loaded 'LLC020', manufacturer 'Philips', ZigBeeNode BD1F/001788010119A28E, init=Нет шаблона, sleepy=false, loading=false, deleted=false, Type=Router] |  
22:04:00 | 001788010119A28E/BD1F: Запущен опрос устройства |  
22:04:00 | Join node: ZigBeeNode BD1F/001788010119A28E, init=Нет шаблона, state=Работает, sleepy=false, loading=true, deleted=false, ota=Нет доступных обновлений, Type=Router] |  
22:03:47 | Update mesh: step 1 |  
22:00:35 | 001788010119A28E/BD1F: Обновление не требуется |  
22:00:35 | Device loaded 'LLC020', manufacturer 'Philips', ZigBeeNode BD1F/001788010119A28E, init=Нет шаблона, sleepy=false, loading=false, deleted=false, Type=Router] |  
22:00:35 | ZigBee поиск завершён |  
22:00:34 | RX_NAK: EzspMessageSentHandler [networkId=0, type=EMBER_OUTGOING_DIRECT, indexOrDestination=BD1F, apsFrame=EmberApsFrame [profileId=0104, clusterId=0021, sourceEndpoint=1, destinationEndpoint=242, options=[EMBER_APS_OPTION_ENABLE_ADDRESS_DISCOVERY, EMBER_APS_OPTION_RETRY, EMBER_APS_OPTION_ENABLE_ROUTE_DISCOVERY], groupId=0, sequence=1A], messageTag=BA, status=EMBER_DELIVERY_FAILED, messageContents=] |  
22:00:34 | Transaction terminated (Device not respond): 0000_ReadAttributesCommand [0021_GreenPower: 0000/1 -> BD1F/242, TID=BA, Input, identifiers=[0010_GppMaxProxyTableEntries, 0011_ProxyTable, 0012_GppNotificationRetryNumber, 0013_GppNotificationRetryTimer, 0014_GppMaxSearchCounter, 0015_GppBlockedGpdId, 0016_GppFunctionality, 0017_GppActiveFunctionality, 0020_GpClientSharedSecurityKeyType, 0021_GpClientSharedSecurityKey, 0022_GpClientLinkKey, 0000_GpsMaxSinkTableEntries, 0001_SinkTable, 0002_GpsCommunicationMode, 0003_GpsCommissioningExitMode, 0004_GpsCommissioningWindow, 0005_GpsSecurityLevel, 0006_GpsFunctionality, 0007_GpsActiveFunctionality]] |  
22:00:30 | RX_NAK: EzspMessageSentHandler [networkId=0, type=EMBER_OUTGOING_DIRECT, indexOrDestination=BD1F, apsFrame=EmberApsFrame [profileId=0104, clusterId=0021, sourceEndpoint=1, destinationEndpoint=242, options=[EMBER_APS_OPTION_ENABLE_ADDRESS_DISCOVERY, EMBER_APS_OPTION_RETRY, EMBER_APS_OPTION_ENABLE_ROUTE_DISCOVERY], groupId=0, sequence=19], messageTag=B9, status=EMBER_DELIVERY_FAILED, messageContents=] |  
22:00:30 | Transaction terminated (Device not respond): 0000_ReadAttributesCommand [0021_GreenPower: 0000/1 -> BD1F/242, TID=B9, Output, identifiers=[0010_GppMaxProxyTableEntries, 0011_ProxyTable, 0012_GppNotificationRetryNumber, 0013_GppNotificationRetryTimer, 0014_GppMaxSearchCounter, 0015_GppBlockedGpdId, 0016_GppFunctionality, 0017_GppActiveFunctionality, 0020_GpClientSharedSecurityKeyType, 0021_GpClientSharedSecurityKey, 0022_GpClientLinkKey, 0000_GpsMaxSinkTableEntries, 0001_SinkTable, 0002_GpsCommunicationMode, 0003_GpsCommissioningExitMode, 0004_GpsCommissioningWindow, 0005_GpsSecurityLevel, 0006_GpsFunctionality, 0007_GpsActiveFunctionality]] |  
22:00:25 | RX_NAK: EzspMessageSentHandler [networkId=0, type=EMBER_OUTGOING_DIRECT, indexOrDestination=BD1F, apsFrame=EmberApsFrame [profileId=0104, clusterId=0000, sourceEndpoint=1, destinationEndpoint=242, options=[EMBER_APS_OPTION_ENABLE_ADDRESS_DISCOVERY, EMBER_APS_OPTION_RETRY, EMBER_APS_OPTION_ENABLE_ROUTE_DISCOVERY], groupId=0, sequence=18], messageTag=B8, status=EMBER_DELIVERY_FAILED, messageContents=] |  
22:00:25 | Transaction terminated (Device not respond): 0000_ReadAttributesCommand [0000_Basic: 0000/1 -> BD1F/242, TID=B8, Output, identifiers=[FF01_Custom, FF02_Custom, FF0D_Custom, FF2A_Custom, FF19_PowerOffMemory, FF22_MappingModeLeft, FF23_MappingModeRight, FF27_ClearPosition, FF28_Reverse, FF29_PullToOpen, FF30_LockReport]] |  
22:00:20 | RX_NAK: EzspMessageSentHandler [networkId=0, type=EMBER_OUTGOING_DIRECT, indexOrDestination=BD1F, apsFrame=EmberApsFrame [profileId=0104, clusterId=0000, sourceEndpoint=1, destinationEndpoint=242, options=[EMBER_APS_OPTION_ENABLE_ADDRESS_DISCOVERY, EMBER_APS_OPTION_RETRY, EMBER_APS_OPTION_ENABLE_ROUTE_DISCOVERY], groupId=0, sequence=17], messageTag=B7, status=EMBER_DELIVERY_FAILED, messageContents=] |  
22:00:20 | Transaction terminated (Device not respond): 0000_ReadAttributesCommand [0000_Basic: 0000/1 -> BD1F/242, TID=B7, Output, identifiers=[0000_ZclVersion, 0001_ApplicationVersion, 0002_StackVersion, 0003_HwVersion, 0004_ManufacturerName, 0005_ModelIdentifier, 0006_DateCode, 0007_PowerSource, 0008_GenericDeviceClass, 0009_GenericDeviceType, 000A_ProductCode, 000B_ProductUrl, 0010_LocationDescription, 0011_PhysicalEnvironment, 0012_DeviceEnabled, 0013_AlarmMask, 0014_DisableLocalConfig, 0032_Custom, 0033_Custom, 0040_Custom, 0041_Custom, 0050_Custom, 0051_Custom, 0401_Custom, 0404_PositionState, 4000_SwBuildId, F000_Custom, F109_Custom, FFF0_Custom, FFF1_Custom]] |  
22:00:10 | 001788010119A28E/BD1F: Информация о модели |  
22:00:10 | 001788010119A28E/BD1F: Изучение конечной точки 242 (2/2) |  
22:00:10 | 001788010119A28E/BD1F: Изучение конечной точки 11 (2/1) |  
22:00:09 | 001788010119A28E/BD1F: Изучение возможностей |  
22:00:09 | 001788010119A28E/BD1F: Энергопотребление |  
22:00:09 | 001788010119A28E/BD1F: Базовая информация |  
22:00:09 | 001788010119A28E/BD1F: Запущен опрос устройства |  
22:00:09 | Join node: ZigBeeNode BD1F/001788010119A28E, init=Опрос, state=Работает, sleepy=true, loading=true, deleted=false, ota=Неизвестно, Type=Unknown] |  
22:00:08 | Unknown node 001788010119A28E, frame: ZigBeeApsFrame [sourceAddress=BD1F/0, destinationAddress=0000/0, profile=0000, cluster=0013, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=5F, payload=00 1F BD 8E A2 19 01 01 88 17 00 8E, lastHopLqi=236, lastHopRssi=-41] |  
22:00:07 | ZigBee поиск запущен на 60 секунд
```

**Каталог**:
В каталоге нету именно этой модели устройства (LLC020) но есть другая модель (LCT026) https://v2.sprut.ai/catalog/item/philips-hue-go, насколько я понимаю модель LCT026 это более новое устройство со встроенным Bluetooth, у мне же первая версия этого устройства без него. На устройстве указан Model: 7146060PH, Part Number: 915004576701.

**Подключение**: 
врубил в розетку, включил и поднёс вплотную на расстоянии +- 30см к zigbee стику.

Подключал несколько раз, лог и результат один и тот-же.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/philips-hue-go-besprovodnoj-led-svetilnik

**Comment by stanislavprokopov** [comment]
После последнего обновления, устройство теперь в статусе: "Очистка групп"
Удалял и добавлял устройство заново, результат тот-же.
Что это за статус и что он обозначает?

```
21:28:33 | 001788010119A28E/81C9: Обновление не требуется |  
-- | -- | --
21:28:33 | Device loaded 'LLC020', manufacturer 'Philips', ZigBeeNode 81C9/001788010119A28E, init=Очистка групп, sleepy=false, loading=false, deleted=false, Type=Router] |  
21:28:33 | ZigBee поиск завершён |  
21:28:33 | 001788010119A28E/81C9: Опрос = 000B_DefaultResponse [0006_OnOff: 81C9/11 -> 0000/1, TID=A1, Input, commandIdentifier=6, statusCode=UNSUP_GENERAL_COMMAND] |  
21:28:33 | 001788010119A28E/81C9: Опрос (11/0006_OnOff/0000_OnOff) -> (5 - 3600, null) |  
21:28:33 | 001788010119A28E/81C9: Связь (11/0006_OnOff) -> (1/60A423FFFE415571) |  
21:28:33 | 001788010119A28E/81C9: Очистка групп |  
21:28:30 | 001788010119A28E/81C9: Информация о модели |  
21:28:30 | 001788010119A28E/81C9: Изучение конечной точки 242 (2/2) |  
21:28:30 | 001788010119A28E/81C9: Изучение конечной точки 11 (2/1) |  
21:28:30 | 001788010119A28E/81C9: Изучение возможностей |  
21:28:30 | 001788010119A28E/81C9: Энергопотребление |  
21:28:30 | 001788010119A28E/81C9: Базовая информация |  
21:28:30 | 001788010119A28E/81C9: Запущен опрос устройства |  
21:28:30 | Join node: ZigBeeNode 81C9/001788010119A28E, init=Опрос, state=Работает, sleepy=true, loading=true, deleted=false, ota=Неизвестно, Type=Unknown] |  
21:28:29 | Unknown node 001788010119A28E, frame: ZigBeeApsFrame [sourceAddress=81C9/0, destinationAddress=0000/0, profile=0000, cluster=0013, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=26, payload=00 C9 81 8E A2 19 01 01 88 17 00 8E, lastHopLqi=255, lastHopRssi=-26] |  
21:28:19 | ZigBee поиск запущен на 60 секунд
```

Информация:
Address: 001788010119A28E/81C9<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: LLC020</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 5.130.1.30000</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>71</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>45</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>45</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS, RECHARGABLE_BATTERY, DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Apr 25 21:28:33 MSK 2021

**Comment by tim0feev** [comment]
LLC020. 1.9.1. Не спаривается. Пишет "Очистка групп". Лампа стоит уже прям рядом с роутером и хабом.
