### ISSUE TITLE
Добавить сортировку в списке устройств контроллеров

### ISSUE THREAD

**Issue by thaserge** [sprut/Hub#633]
Очень не хватает сортировки в списке устройств на контроллерах, особенно беспроводных интерфейсов Zigbee и Z-Wave.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/54379060/113504605-d2fad980-9541-11eb-8817-00bb41954001.png">

**Comment by sprut666666** [comment]
будет в новом вебе
