### ISSUE TITLE
Heatit Z-TRM3

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#638]
Для добавления поддержки нового устройства в хаб, необходимо:

1) Спарить устройство с хабом, и убедиться, что оно не поддерживается хабом. Устройство должно появиться на вкладке контроллеров, но не появиться в списке аксессуаров. Модель устройства должна определиться как "Unknown".
2) Heatit Z-TRM3 (5430598 TF064)
3) https://media.heatit.com/715
4) <b>Heatit - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>2</td></tr><tr><td width=35%>Manufacturer Id</td><td>019B</td></tr><tr><td width=35%>Device Type</td><td>0003</td></tr><tr><td width=35%>Device Id</td><td>0203</td></tr><tr><td width=35%>App Version</td><td>4.0</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Thermostat</td></tr><tr><td width=35%>Specific Class</td><td>Thermostat General V2</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td> Lifeline</td><td>[1]</td><td>5</td></tr><tr><td>2</td><td> Switch Set</td><td>[]</td><td>5</td></tr><tr><td>3</td><td> Sensor Report A</td><td>[]</td><td>5</td></tr><tr><td>4</td><td> Sensor Report A2</td><td>[]</td><td>5</td></tr><tr><td>5</td><td> Sensor Report F</td><td>[]</td><td>5</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V2 Association</li><li>V2 Version</li><li>V1 FirmwareUpdateMD</li><li>V2 ManufacturerSpecific</li><li>V3 Meter<ul><li>Energy: 0 kWh</li><li>Power: 0.05 W</li><li>Voltage: 233.8 V</li></ul></li><li>V1 DeviceResetLocally</li><li>V1 ThermostatOperatingState<ul></ul></li><li>V0 SensorMultiLevel<ul><li>Temperature: 28</li></ul></li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V3 MultiChannelAssociation</li><li>V1 AssociationGRPInfo</li><li>V2 MultiChannel</li><li>V1 NoOperation</li><li>V1 Configuration</li><li>V1 ZWavePlusInfo</li><li>V1 ThermostatMode<ul><li>Off</li><li>Heat</li></ul></li><li>V1 Security</li><li>V1 ThermostatSetpoint<ul><li>Heating: </li></ul></li><li>V1 Basic</li></ul></li><li>Endpoint 1<ul><li>V2 Association</li><li>V1 AssociationGRPInfo</li><li>V3 Meter<ul><li>Energy: Unknown</li><li>Power: Unknown</li><li>Voltage: Unknown</li></ul></li><li>V1 ThermostatOperatingState<ul></ul></li><li>V1 ZWavePlusInfo</li><li>V1 ThermostatMode<ul><li>Off</li><li>Heat</li></ul></li><li>V1 ThermostatSetpoint<ul><li>Heating: </li></ul></li><li>V1 Basic</li><li>V3 MultiChannelAssociation</li></ul></li><li>Endpoint 2<ul><li>V2 Association</li><li>V1 AssociationGRPInfo</li><li>V1 SensorMultiLevel<ul></ul></li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li><li>V3 MultiChannelAssociation</li></ul></li><li>Endpoint 3<ul><li>V2 Association</li><li>V1 AssociationGRPInfo</li><li>V1 SensorMultiLevel<ul></ul></li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li><li>V3 MultiChannelAssociation</li></ul></li><li>Endpoint 4<ul><li>V2 Association</li><li>V1 AssociationGRPInfo</li><li>V1 SensorMultiLevel<ul></ul></li><li>V1 ZWavePlusInfo</li><li>V1 Basic</li><li>V3 MultiChannelAssociation</li></ul></li></ul><br>Last update: Fri Apr 09 16:18:11 MSK 2021

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heatit-z-trm3

**Comment by MakeSimpleOrg** [comment]
r4664
