### ISSUE TITLE
TS0001

### ISSUE THREAD

**Issue by chap-s** [sprut/Hub#643]
Address: 00124B000A52E11E/CAA2<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 33</li><li>0003_HwVersion: 0</li><li>0004_ManufacturerName: _TYZB01_phjeraqq</li><li>0005_ModelIdentifier: TS0001</li><li>0006_DateCode: 20060831        </li><li>0007_PowerSource: 4</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 177</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>00158D00054EAFF4</td><td>8FD0</td><td>Router</td><td>true</td><td>Parent</td><td>52</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFE417439</td><td>0000</td><td>Coordinator</td><td>true</td><td>Unknown</td><td>27</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Apr 15 23:22:05 MSK 2021

[stdout.log](https://github.com/sprut/Hub/files/6321004/stdout.log)
[spruthub.log](https://github.com/sprut/Hub/files/6321005/spruthub.log)

Telegram: @chap_secrets
Купил: [тут](https://star.aliexpress.com/share/share.htm?image=Uecd9e352c31140a4b2dd29cc4b11583f1.jpg&businessType=ProductDetail&title=1%C2%A0113%2C30%20%D1%80%D1%83%D0%B1.%20%20-38%EF%BC%85%20%7C%20%D0%A3%D0%BC%D0%BD%D1%8B%D0%B9%20%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B8%D0%B9%20%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C%20Tuya%20Zigbee%203%2C0%2C%2016%20%D0%90%2C&platform=AE&redirectUrl=https%3A%2F%2Fwww.aliexpress.com%2Fitem%2F10000209855754.html%3F%26srcSns%3Dsns_Copy%26tid%3Dwhite_backgroup_101%26mb%3DyBQgGP2154OJ34P%26businessType%3DProductDetail%26spreadType%3DsocialShare)

Очень похоже на : [каталожное устройство](https://v2.sprut.ai/catalog/item/tuya-zigbee-30-rele-vklucenia-vyklucenia-16a-4000-vt)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tuya-zigbee-30-rele-vklucenia-vyklucenia-16a-4000-vt
