### ISSUE TITLE
Samsung SmartThings Motion Sensor v3

### ISSUE THREAD

**Issue by Co1dSUN** [sprut/Hub#645]
[2021-04-12_16-11-27.zip](https://github.com/sprut/Hub/files/6333672/2021-04-12_16-11-27.zip)
Address: 286D9700010D70D6/783D<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 17</li><li>0003_HwVersion: 0</li><li>0004_ManufacturerName: Samjin</li><li>0005_ModelIdentifier: motion</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: </li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 0</li><li>0001_LongPollInterval: 28</li><li>0002_ShortPollInterval: 1</li><li>0003_FastPollTimeout: 40</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 13</li><li>0002_ZoneStatus: 33</li><li>0010_IasCieAddress: 0000000000000000</li><li>0011_ZoneId: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 26</li><li>0021_BatteryPercentageRemaining: 146</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2365</li><li>0001_MinMeasuredValue: 0</li><li>0002_MaxMeasuredValue: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 0</li><li>0100_MacRxBcast: 0</li><li>0101_MacTxBcast: 0</li><li>0102_MacRxUcast: 154</li><li>0103_MacTxUcast: 111</li><li>0104_MacTxUcastRetry: 0</li><li>0105_MacTxUcastFail: 0</li><li>0106_ApsRxBcast: 2</li><li>0107_ApsTxBcast: 0</li><li>0108_ApsRxUcast: 16</li><li>0109_ApsTxUcastSuccess: 11</li><li>011C_LastMessageLqi: 144</li><li>011D_LastMessageRssi: -64</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 0</li><li>0008_ImageTypeId: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4673</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Apr 19 06:15:19 UTC 2021

Для добавления достаточно нажать скрепкой и подержать кнопку под крышкой, пока не начнёт мигать красный или красный и зелёный светодиод на передней панели.
Мой [телеграм](https://t.me/ColdSUN)
Устройство в [каталоге](https://v2.sprut.ai/catalog/item/samsung-smartthings-motion-sensor)
Период повторного срабатывания 30 секунд.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/samsung-smartthings-motion-sensor
