### ISSUE TITLE
TS0601

### ISSUE THREAD

**Issue by Rivega42** [sprut/Hub#649]
Address: 5C0272FFFED9C355/C3CE<br><br>

<b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br>

<b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 82</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_zpzndjez</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: �J(�J(</li><li>FFE2_Custom: 21</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>000A_Time<ul><li>0007_LocalTime: 672352926</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b></b><br><br><br><br>Last update: Wed Apr 21 20:42:23 MSK 2021

Телеграм: Rivega42
Девайс в [каталоге](https://v2.sprut.ai/catalog/item/tuya-curtain-motor).
Покупал [тут](https://aliexpress.ru/item/4000739390813.html?af=205380&utm_campaign=205380&aff_platform=link-c-tool&utm_medium=cpa&dp=ad24fc736501c4a9935f0f9338341186&aff_fcid=72c06c0b701a44dd9752a9fcb7fcd185-1619028507688-02063-mr6wR6CC&cv=815660&aff_fsk=mr6wR6CC&sk=mr6wR6CC&aff_trace_key=72c06c0b701a44dd9752a9fcb7fcd185-1619028507688-02063-mr6wR6CC&terminal_id=5dbefaa2aed742b2b18e9fd80d421058&utm_source=admitad&utm_content=815660)

**Comment by Rivega42** [comment]
На гите есть вот такая задача про этот TS0601 c  названием модели DS82  
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4521

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tuya-curtain-motor

**Comment by Rivega42** [comment]
> https://v2.sprut.ai/catalog/item/tuya-curtain-motor

я же данную ссылку в исходном иссуе прикреплял
