### ISSUE TITLE
Запуск триггеров при рестарте SH

### ISSUE THREAD

**Issue by nikolay812** [sprut/Hub#65]
При рестарте SH не обрабатываются триггеры.

Пример:
Есть модуль: WBIO-DO-R10A-8, к нему подключены термоголовки  (нормально-закрытые), в виртуальном термостате сделаны тригеры на реле модуля, в случае отключения питания модуль включается в состоянии разомкнутых реле (по дефолту, этот модуль не умеет запоминать свое состояние до ребута) , при этом термостат включен на нагрев (реле должно быть замкнуто). Пока в термостате не снизишь вручную температуру и не поднимешь до значения нагрева, реле не замкнется. Получается, если по каким то причинам wb-6 перезагрузился по питанию, дом будет остывать, пока вручную не перещелкнешь режим в термостате.

** Ожидаемое поведение **
При загрузке SH обрабатывать все триггеры с явным значением.

**Comment by diamond5170** [comment]
В SH при этом видно правильный статус реле после перезагрузки?

**Comment by nikolay812** [comment]
> В SH при этом видно правильный статус реле после загрузки?

Да, при появлении питания на модуле: в WB статус «выключено», в SH статус «выключено», но если посмотреть условие в виртуальном термостате, то реле должно быть в статусе «включено» в соответствие с созданным триггером.

**Comment by sprut666666** [comment]
Ревизия: 3257
