### ISSUE TITLE
Диммер Ikea работает некорректно, жрет батарею.

### ISSUE THREAD

**Issue by vova0255** [sprut/Hub#650]
Имею 4 Диммер от Икея

2 шт https://v2.sprut.ai/catalog/item/ikea-symfonisk-sound-remote
2 шт https://v2.sprut.ai/catalog/item/ikea-besprovodnoj-reostat

При добавлении первого из первой серии - все ок
При добавлении первого из второй серии - все ок

Как только добавляешь второй диммер первой или второй версии, начинаются чудеса:
Во первых - их тяжело добавить (вторые), а именно добавляются без функционала. После многочисленных попыток удаления и добавления и только после перезагрузке Хаба - заезжают! Физической имел ввиду - перезагрузка Малины.
Во вторых - второй диммер из новой серии (с выемкой) теряет функционал кнопки - на одно нажатие, есть только двойное (и не только у меня - прочтите коммент с первой ссылки).
И третье: все они страшно жрут батарейки! В неделю - одна! Причем и Дюрасель и Varta и GP сдыхают. Ставишь новую, а он пишет 50% заряда. Пользуюсь диммером 2 раза в день.
Помогите решить вопрос.

**Comment by sprut666666** [comment]
Прошу отписать в группу теста, для уточнений.

**Comment by sprut666666** [comment]
на след сборке, переспарить и проверить
