### ISSUE TITLE
Shutter switch with neutral

### ISSUE THREAD

**Issue by tolkachev071** [sprut/Hub#654]
Address: 00047400008D9101/E832<br><br><b>Structure</b><br><ul><li>Endpoint 1 (WINDOW_COVERING_DEVICE)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 0</li><li>0004_ManufacturerName:  Legrand</li><li>0005_ModelIdentifier:  Shutter switch with neutral</li></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0102_WindowCovering<ul><li>0008_CurrentPositionLiftPercentage: 50</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>000F_BinaryInputBasic<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>89</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>63</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4129</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>63</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, MAINS, RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Apr 19 12:31:59 MSK 2021
Telegram - Tolkachev Pavel
Покупал - https://www.onlinetrade.ru/catalogue/umnye_vyklyuchateli_legrand-c6809/legrand/umnyy_vyklyuchatel_rolstavney_legrand_valena_life_with_netatmo_500_va_230v_752190_belyy-2392762.html
в каталоге есть

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/legrand-umnyj-vyklucatel-rolstavnej
