### ISSUE TITLE
Контроллер Sonoff Zigbee Bridge, Можно опрашивать повторно контроллер ?

### ISSUE THREAD

**Issue by EShchepilov** [sprut/Hub#656]
@sprut666666 десть фича у СХ, которою бы хотелось бы пофиксить.  А именно : Версия 4706, контроллер Sonoff Zigbee Bridge, Если происходит пропадание ээ на СХ, а bridge не перезагружался, то после перезагрузки СХ, данный бридж не актуализирует девайсы, и необходимо на контроллер выключить галочку, а потом включить. После такой операции все нормально. Можно если такое происходит, опрашивать повторно контроллер ?

**Comment by EShchepilov** [comment]
@naumserg74 У меня с Sonoff Zigbee Bridge  на прошивке Tasmota абсолютно аналогичная проблема с пропаданием девайсов в SH и она также лечится на какое-то время снятием и возвратом галки в чекбоксе контролера. Все девайсы возвращаются на свои места. Но заметил, что  происходит это совершенно рандомно. Малина со SH подключена  к бесперебойнику, поэтому исключаю эти сбои по питанию малины. Сам бридж также пробовал на различных адаптерах питания и также в данный момент подключён через блок бесперебойного питания. Пока тестирую эту связку. Стабильности нет, в отличие от оригинального USB-stick - Sprut.Stick 2 Pro

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
