### ISSUE TITLE
GL-C-009P

### ISSUE THREAD

**Issue by thaserge** [sprut/Hub#658]
Address: 60A423FFFE041FC9/4163<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11 (DIMMABLE_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 0</li><li>0003_HwVersion: 0</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-C-009P</li><li>0007_PowerSource: 0</li><li>4000_SwBuildId: V1.0.1</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 127</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE4173F6</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>179</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D0002560FD8</td><td>0ED4</td><td>Router</td><td>false</td><td>Sibling</td><td>179</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0001719530</td><td>1C7F</td><td>Router</td><td>false</td><td>Sibling</td><td>148</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0004117566</td><td>42F1</td><td>Router</td><td>false</td><td>Sibling</td><td>86</td><td>UNKNOWN</td><td>15</td></tr><tr><td>588E81FFFED3A15D</td><td>7E8B</td><td>Router</td><td>false</td><td>Parent</td><td>144</td><td>UNKNOWN</td><td>15</td></tr><tr><td>588E81FFFED4AAA6</td><td>8EC1</td><td>Router</td><td>false</td><td>Sibling</td><td>149</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B001EC8DC26</td><td>90A9</td><td>Router</td><td>false</td><td>Sibling</td><td>165</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B0022576AD7</td><td>AA04</td><td>Router</td><td>false</td><td>Sibling</td><td>102</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>90A9</td><td>90A9</td></tr><tr><td>ACTIVE</td><td>7E8B</td><td>7E8B</td></tr><tr><td>ACTIVE</td><td>0ED4</td><td>0ED4</td></tr><tr><td>ACTIVE</td><td>AA04</td><td>8EC1</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon May 17 19:16:17 UTC 2021

Тоже самое устройство что и https://github.com/sprut/Hub/issues/514 только про версия
Изза буковки P не подтягивает шаблон

https://v2.sprut.ai/catalog/item/gledopto-led-dimmer

У меня работает с этим template
[GL-C-009P.json.zip](https://github.com/sprut/Hub/files/6496375/GL-C-009P.json.zip)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/gledopto-led-dimmer-pro
