### ISSUE TITLE
Не подключатся к homekit когда две сети

### ISSUE THREAD

**Issue by kadkin** [sprut/Hub#66]
Поднял на wirenboard, с настройками сети по умолчанию
и когда подключаюсь к сети у роутера, не добавляется в homekit, но шлюз sprut видит, ввожу пароль и висит на подключении

** Как воспроизвести ? **
wlan0 192.168.42.1 развернута на wirenboard сеть без пароля(к ней не подключаюсь)
eth0 192.168.0.16 подключено по проводу

телефон подключен по wifi  к сети, пробовал и к 5 Gz и 2.4
если подключаться к wifi сети от wirenboard, то homekit подключается
правда не понятно, может конечно с роутером что-то, посмотрел правил никаких нет
алиса подключается нормально

`
I | 2020-02-07 | 23:10:10.878 | org.makesimple.SprutHub.Homekit.d        38  | Binding to interfaces:
I | 2020-02-07 | 23:10:10.888 | org.makesimple.SprutHub.Homekit.d        40  | /192.168.42.1
I | 2020-02-07 | 23:10:10.891 | org.makesimple.SprutHub.Homekit.d        40  | /192.168.0.16
I | 2020-02-07 | 23:10:17.088 | org.makesimple.SprutHub.Homekit.a        43  | Generating new mac address...
I | 2020-02-07 | 23:10:17.212 | org.makesimple.SprutHub.Homekit.a        26  | MAC: -------
I | 2020-02-07 | 23:10:17.215 | org.makesimple.SprutHub.Homekit.a        28  | PIN: ---------
I | 2020-02-07 | 23:10:17.915 | org.makesimple.SprutHub.SprutHub         484 | Added accessory: id=1, name=SprutHub, model=SprutHub
I | 2020-02-07 | 23:10:18.258 | org.makesimple.SprutHub.SprutHub         484 | Added accessory: id=2, name=Сигнализация, model=SecuritySystem
I | 2020-02-07 | 23:10:27.414 | org.makesimple.SprutHub.Homekit.http.h   54  | Bound homekit listener to /0.0.0.0:9123

** Ожидаемое поведение **
подключение по всем сетям или дать выбор

** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, IOS] 13.3.1 iphone x

**Comment by diamond5170** [comment]
Показывает ли хаб в списке в хомките? Работает ли веб интерфейс хаба? Работает ли веб интерфейс ВБ? Уточнить, из сообщения это непонятно.

**Comment by kadkin** [comment]
Да, хаб виден в homekit, ввожу пароль и просто идет подключение и не добавляется, после падает добавление с ошибкой

все интерфейсы работают, к  ВБ подключаюсь, к sprut hub тоже
алиса нормально завелась

![Снимок экрана 2020-02-08 в 10 17 19](https://user-images.githubusercontent.com/3262918/74081109-58791b80-4a5c-11ea-8abe-9412cb64bb32.png)

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
