### ISSUE TITLE
TS0012

### ISSUE THREAD

**Issue by Boychenko-nov** [sprut/Hub#661]
Address: BC33ACFFFED85295/36D6<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYZB01_vzrytttn</li><li>0005_ModelIdentifier: TS0012</li><li>0007_PowerSource: 3</li><li>FFE2_Custom: 19</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>512</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>512</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed May 19 14:05:36 MSK 2021

@old_dachnik Владимир Бойченко

Приобретал: https://a.aliexpress.com/_9vF3e1
Каталог: https://v2.sprut.ai/catalog/item/moeshouse-zigbee-vyklucatel-n-and-l-wire-2
Zigbee 2.4 GHz
Режим спаривания, сброса: 5 сек нажатие
С нулевой линией
Двухклавишный
Статус после восстановления питания: Последнее состояние; Всегда включено; Всегда выключено
Модель указанная на устройстве: DS-112. Определился как TS0012 и конечное устройство, но согласно каталога является роутером, и на карте тоже отображается как конечное.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-zigbee-vyklucatel-n-and-l-wire-2

**Comment by Boychenko-nov** [comment]
Не совсем понимаю смысл письма?



Отправлено из мобильной Почты Mail.ru


среда, 19 мая 2021 г., 20:38 +0300 от ***@***.***  ***@***.***>:

**Comment by sprut666666** [comment]
китайцы любят одинаковые модели, тип устройства берётся из устройства
