### ISSUE TITLE
Не могу подключиться к малине по SSH

### ISSUE THREAD

**Issue by shurikshurikov** [sprut/Hub#662]
Не могу больше подключиться к малине по SSH со спрутхабом, выдаёт ошибку: 
ssh: connect to host 192.168.1.24 port 22: Connection refused
к малине с нодредом спокойно подключаюсь.

Ревизия: 4706/4709
Дата сборки: 20.04.2021, 15:14:01

![image](https://user-images.githubusercontent.com/59749751/119231186-280da180-bb28-11eb-8de6-24e736225d9b.png)

Ник в телеге: @Shurik_Shurikov

**Comment by Batyushin** [comment]
ip верный? пинг идет? если да. тут проблема не с хабом а с системой.
