### ISSUE TITLE
 Термостат _TZE200_aoclfnxz

### ISSUE THREAD

**Issue by zloydimo4ka** [sprut/Hub#665]
Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device
Address: 847127FFFE1F28AF/3781<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 65</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_aoclfnxz</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>000B57FFFE80CD13</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>172</td><td>UNKNOWN</td><td>0</td></tr><tr><td>04CF8CDF3C761040</td><td>005E</td><td>Router</td><td>false</td><td>Parent</td><td>191</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00032C8D71</td><td>42EE</td><td>Router</td><td>false</td><td>Sibling</td><td>119</td><td>UNKNOWN</td><td>15</td></tr><tr><td>01124B001BAE72D0</td><td>6FB5</td><td>Router</td><td>false</td><td>Sibling</td><td>116</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00032CA6B3</td><td>7728</td><td>Router</td><td>false</td><td>Sibling</td><td>66</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00039BCD30</td><td>9204</td><td>Router</td><td>false</td><td>Sibling</td><td>77</td><td>UNKNOWN</td><td>15</td></tr><tr><td>01124B001C3BF072</td><td>CF38</td><td>Router</td><td>false</td><td>Sibling</td><td>68</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>ACTIVE</td><td>6FB5</td><td>42EE</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun May 30 21:32:01 YEKT 2021
Ссылка на каталог: https://v2.sprut.ai/catalog/item/moeshouse-moes-thermostat-electric-floor-2
Покупал здесь: https://aliexpress.ru/item/4001290635850.html?_ga=2.6075443.1256901113.1622306114-426352031.1622306114&sku_id=10000015632362563&spm=a2g0s.9042311.0.0.bbde4c4djJ96h7
Ник в телеграмм: ypiter2006

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-moes-thermostat-electric-floor-2
