### ISSUE TITLE
TS0001

### ISSUE THREAD

**Issue by shtoffen** [sprut/Hub#666]
Address: EC1BBDFFFE8030B6/64E0<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 66</li><li>0004_ManufacturerName: _TYZB01_seqwasot</li><li>0005_ModelIdentifier: TS0001</li><li>0007_PowerSource: 1</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8002_RestartStatus: 2</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE4155C7</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>126</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00124B000E250C46</td><td>0D9C</td><td>Router</td><td>false</td><td>Sibling</td><td>107</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00036D2581</td><td>2751</td><td>Router</td><td>false</td><td>Sibling</td><td>143</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00054EA92C</td><td>6B47</td><td>Router</td><td>false</td><td>Sibling</td><td>57</td><td>UNKNOWN</td><td>15</td></tr><tr><td>842E14FFFEFCD3C4</td><td>8CEE</td><td>Router</td><td>false</td><td>Sibling</td><td>119</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00036D2541</td><td>996D</td><td>Router</td><td>false</td><td>Sibling</td><td>54</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0002D80181</td><td>9C0A</td><td>Router</td><td>false</td><td>Sibling</td><td>188</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0003262EEB</td><td>9F63</td><td>Router</td><td>false</td><td>Parent</td><td>150</td><td>UNKNOWN</td><td>15</td></tr><tr><td>01124B001BAE85CF</td><td>BFB4</td><td>Router</td><td>false</td><td>Sibling</td><td>47</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B0009FE37CF</td><td>DE05</td><td>Router</td><td>false</td><td>Sibling</td><td>183</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B001F6685AA</td><td>FEE0</td><td>Router</td><td>false</td><td>Sibling</td><td>55</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon May 31 22:53:12 MSK 2021

Ник @olrich
В каталоге : https://v2.sprut.ai/catalog/item/lonsonho-smart-switch-1-swotch

**Comment by Batyushin** [comment]
а что не так? модель совпадает

**Comment by shtoffen** [comment]
Олег попросил ишью сделать, ошибка добавления устройства в хаб, зависает на инициализации

Sent from iPhone
