### ISSUE TITLE
ZB-SW01

### ISSUE THREAD

**Issue by artyom-s** [sprut/Hub#668]
Address: 00124B0023AE3F03/4456<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 4</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW01</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 1.0.3</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 4</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW01</li><li>0006_DateCode: 20201026</li><li>0007_PowerSource: 1</li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>4000_SwBuildId: 1.0.3</li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br>

**Telegram:** [@surovtsev_artyom](t.me/surovtsev_artyom)
_Покупал_ [тут](https://aliexpress.ru/item/4001331194955.html)

### Выключатель
**Версия Zigbee**: 3.0
**Режим спаривания, сброса:** зажатие кнопки на 10 сек.
**Наличие нуля:** нет
**Количество клавиш:** 1
**Энергоизмеритель:** нет
**Статус после восстановления питания:** да

Last update: Tue Jun 01 20:33:00 MSK 2021

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ejlink-zigbee-30-bez-nulevoj-linii-2
