### ISSUE TITLE
TS0222 MOES Tuya  Датчик освещенности и температуры с влажностью

### ISSUE THREAD

**Issue by EShchepilov** [sprut/Hub#675]
Address: 5C0272FFFE0440D0/B650<br><br><b>Structure</b><br><ul><li>Endpoint 1 (LIGHT_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 72</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYZB01_kvwjujy9</li><li>0005_ModelIdentifier: TS0222</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li></ul></li><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 23055</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul><li>0000_Time: </li><li>0001_TimeStatus: </li><li>0002_TimeZone: </li><li>0003_DstStart: </li><li>0004_DstEnd: </li><li>0005_DstShift: </li><li>0006_StandardTime: </li><li>0007_LocalTime: </li><li>0008_LastSetTime: </li><li>0009_ValidUntilTime: </li></ul></li></ul></li></ul></li><li>Endpoint 2 (TEMPERATURE_SENSOR)<ul><li>Input<ul><li>0400_IlluminanceMeasurement<ul><li>F001_Custom: 20</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2479</li><li>0001_MinMeasuredValue: 2056</li><li>0002_MaxMeasuredValue: 2518</li></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 6345</li><li>0001_MinMeasuredValue: 4548</li><li>0002_MaxMeasuredValue: 8910</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jun 11 17:02:17 MSK 2021

![IMG_20210611_170503.jpg](https://user-images.githubusercontent.com/77865103/121698965-315eae00-cad7-11eb-986e-cc259adbbced.jpg)

 MoesHouse ZigBee, Bluetooth умные Яркость термометр Сенсор светильник Температура детектор влажности Tuya Smart App Alexa Управление
https://a.aliexpress.com/_A0cZex

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-smart-zigbee-gigrometr

**Comment by Batyushin** [comment]
как ввести в режим спаривания?

**Comment by EShchepilov** [comment]
> как ввести в режим сопряжения? 

Нажать на оранжевую кнопку с правого боку и удерживать 5-7сек

**Comment by EShchepilov** [comment]
> Address: 5C0272FFFE0440D0/B650<br><br><b>Structure</b><br><ul><li>Endpoint 1 (LIGHT_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 72</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYZB01_kvwjujy9</li><li>0005_ModelIdentifier: TS0222</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li></ul></li><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 23055</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul><li>0000_Time: </li><li>0001_TimeStatus: </li><li>0002_TimeZone: </li><li>0003_DstStart: </li><li>0004_DstEnd: </li><li>0005_DstShift: </li><li>0006_StandardTime: </li><li>0007_LocalTime: </li><li>0008_LastSetTime: </li><li>0009_ValidUntilTime: </li></ul></li></ul></li></ul></li><li>Endpoint 2 (TEMPERATURE_SENSOR)<ul><li>Input<ul><li>0400_IlluminanceMeasurement<ul><li>F001_Custom: 20</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2479</li><li>0001_MinMeasuredValue: 2056</li><li>0002_MaxMeasuredValue: 2518</li></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 6345</li><li>0001_MinMeasuredValue: 4548</li><li>0002_MaxMeasuredValue: 8910</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jun 11 17:02:17 MSK 2021
> 
> ![IMG_20210611_170503.jpg](https://user-images.githubusercontent.com/77865103/121698965-315eae00-cad7-11eb-986e-cc259adbbced.jpg)
> 
>  MoesHouse ZigBee, Bluetooth умные Яркость термометр Сенсор светильник Температура детектор влажности Tuya Smart App Alexa Управление
> https://a.aliexpress.com/_A0cZex
> 



@sprut666666  переспарь девайс на последней сборке и обнови инфо по нему


Address: 5C0272FFFE0440D0/32AB<br><br><b>Structure</b><br><ul><li>Endpoint 1 (LIGHT_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 72</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYZB01_kvwjujy9</li><li>0005_ModelIdentifier: TS0222</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li></ul></li><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 17483</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 60A423FFFE4154F8</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (TEMPERATURE_SENSOR)<ul><li>Input<ul><li>0400_IlluminanceMeasurement<ul><li>F001_Custom: 20</li></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2701</li><li>0001_MinMeasuredValue: 2056</li><li>0002_MaxMeasuredValue: 2701</li></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 6576</li><li>0001_MinMeasuredValue: 4548</li><li>0002_MaxMeasuredValue: 9323</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jun 12 17:54:33 MSK 2021

**Comment by al-bulanov** [comment]
Вот шаблон. Работает уже пару недель. Все хорошо:
[Moeshouse_THL.txt](https://github.com/sprut/Hub/files/6695736/Moeshouse_THL.txt)

**Comment by EShchepilov** [comment]
Спасибо, работает шаблон. 

Теперь бы @sprut666666  добавил бы в сборку
