### ISSUE TITLE
Cannot resolve hostname

### ISSUE THREAD

**Issue by Sergbmw** [sprut/Hub#679]
При попытке подключить устройства через обратный homekit не удается подключить не нативные устройства не homebridge

Ошибка: Cannot resolve hostname

27:BC:29:4C:AA:33 | HAA-BF5784 | Unknown | RavenSystem HAA | Opened | No | HAA-BF5784.local. | more_vert
-- | -- | -- | -- | -- | -- | -- | --
c#:1ci:29ff:0fullName:HAA-BF5784._hap._tcp.local.ip addresses:[]md:RavenSystem HAAmfi:falseport:5556pv:1.1resolved:falses#:1sf:1sh:8pv27w== | c#: | 1 | ci: | 29 | ff: | 0 | fullName: | HAA-BF5784._hap._tcp.local. | ip addresses: | [] | md: | RavenSystem HAA | mfi: | false | port: | 5556 | pv: | 1.1 | resolved: | false | s#: | 1 | sf: | 1 | sh: | 8pv27w==
c#: | 1
ci: | 29
ff: | 0
fullName: | HAA-BF5784._hap._tcp.local.
ip addresses: | []
md: | RavenSystem HAA
mfi: | false
port: | 5556
pv: | 1.1
resolved: | false
s#: | 1
sf: | 1
sh: | 8pv27w==

**Comment by dzianisreznik** [comment]
У меня cannot resolve hostname с любыми имеющимися у меня устройствами (mi bedside lamp, yeelight led strip, homebridge, xiaomi color led bulb)

**Comment by dzianisreznik** [comment]
Ревизия: 5027
Дата сборки: 14/06/2021, 18:56:20

Сообщение сменилось на 	Service unreachable: 0E_64_D2_9B_35_24.local., ips: []

**Comment by Sergbmw** [comment]
У меня так же: Service unreachable: BroadlinkEasy-6DC5.local., ips: []

**Comment by dzianisreznik** [comment]
P.S. Роутер Xiaomi Mi Router 3 (R3)

**Comment by dzianisreznik** [comment]
Подключаемся по ssh к малине
Пишем команду “sudo nano /etc/hosts”

Добавляем в конец файла пары айпи - хост, например: 

192.168.31.183          0E_64_D2_9B_35_24.local.
192.168.31.162          MijiaColorBulb-F895.local.

где айпи - это айпи устройства в локальной сети (можно посмотреть в настройках роутера)
хост - это имя хоста, к которому пытается стучаться спрутхаб (в контроллере столбик host)

Перезагружаем спрутхаб, пробуем прокинуть заново
