### ISSUE TITLE
Добавить поддержку МОДУЛЬ УПРАВЛЕНИЯ ЖАЛЮЗИ DAR-102 ZWave

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#68]
"manufacturerId": "032E"
  "modelId": "0041:0014"
https://defaro.ru/index.php/product/69-switches/161-dar-102

**Comment by MakeSimpleOrg** [comment]
Добавь информацию.

**Comment by MakeSimpleOrg** [comment]
Дубль.
