### ISSUE TITLE
RWL022 - пульт Hue 

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#680]
Address: 0017880109A645B8/F5C8<br><br><b>Structure</b><br><ul><li>Endpoint 1 (NON_COLOR_SCENE_CONTROLLER)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: Signify Netherlands B.V.</li><li>0005_ModelIdentifier: RWL022</li><li>0007_PowerSource: 3</li></ul></li><li>FC00_ManufacturerSpecific<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 27</li><li>0021_BatteryPercentageRemaining: 156</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 33565696</li><li>0003_CurrentZigbeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4107</li><li>0008_ImageTypeId: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>128</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>128</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jun 13 15:29:55 MSK 2021

Ник в телеграмме : @UskovvNa
Покупал тут: https://euromade.ru/ (К сожалению больше они там не продаются, и ссылки прямой на него уже нет)

https://www.philips-hue.com/en-us/p/hue-dimmer-switch--latest-model-/046677562779 ( это самый последний пульт, в каталоге у нас его еще нет)

Что делал при сниффинге:
1) Сделал все по пунктам, отвязал устройство от родного хаба
2) Включил сниф и в этот момент добавлял в родной Hue хаб 2 модели(последний), зажатием на 3 секунды верхней кнопки
3) Как только он добавился я: 
Нажал каждую кнопку сверху-вниз, затем попробовал еще позажимать каждую, чтобы убедиться, что нет длинных нажатий.
4) Скачал логи.

_В каталоге устройства нет._  
Update , спасибо Red https://v2.sprut.ai/catalog/item/philips-dimmer-switch-latest-model

[2021-06-13_13-04-31.pcap.zip](https://github.com/sprut/Hub/files/6643880/2021-06-13_13-04-31.pcap.zip)

Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/philips-dimmer-switch-latest-model
