### ISSUE TITLE
lumi.motion.agl04

### ISSUE THREAD

**Issue by svt222** [sprut/Hub#682]
Address: 54EF441000083716/E6B6<br><br><b>Structure</b><br><ul><li>Endpoint 1 (OCCUPANCY_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 25</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.motion.agl04</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 2019</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>00F7_Custom: {1=3253, 3=25, 4=424, 100=false, 5=10, 101=0, 6=8, 8=281, 10=0, 12=1}</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 32</li><li>0031_BatterySize: 7</li><li>003E_BatteryAlarmState: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0406_OccupancySensing<ul><li>0000_Occupancy: 1</li><li>0001_OccupancySensorType: 0</li><li>0010_PirOccupiedToUnoccupiedDelay: 120</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0002_CurrentFileVersion: 25</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Jun 15 18:37:11 MSK 2021

Телеграмм - @vsergeev152
[Девайс в каталоге](https://v2.sprut.ai/catalog/item/aqara-human-body-sensor)
[Покупал](https://youpin.com.ru/product/RTCGQ13LM/)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/aqara-human-body-sensor

**Comment by ArtGroup** [comment]
+1 

Address: 54EF441000082C39/1E1D<br><br><b>Structure</b><br><ul><li>Endpoint 1 (OCCUPANCY_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 25</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.motion.agl04</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 2019</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>00F7_Custom: {1=3228, 3=25, 4=424, 100=false, 5=11, 101=0, 6=8, 8=281, 10=0, 12=1}</li><li>00FC_Custom: false</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 32</li><li>0031_BatterySize: 7</li><li>003E_BatteryAlarmState: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0406_OccupancySensing<ul><li>0000_Occupancy: 1</li><li>0001_OccupancySensorType: 0</li><li>0010_PirOccupiedToUnoccupiedDelay: 120</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0002_CurrentFileVersion: 25</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Jun 16 19:32:57 MSK 2021
