### ISSUE TITLE
TS0601

### ISSUE THREAD

**Issue by den1ss666** [sprut/Hub#685]
Address: 5C0272FFFE915D0C/BA96

Structure
* Endpoint 1 (SMART_PLUG)
    * Input
        * 0000_Basic
            * 0000_ZclVersion: 3
            * 0001_ApplicationVersion: 83
            * 0002_StackVersion: 0
            * 0003_HwVersion: 1
            * 0004_ManufacturerName: _TZE200_znzs7yaw
            * 0005_ModelIdentifier: TS0601
            * 0006_DateCode:
            * 0007_PowerSource: 1
            * 0008_GenericDeviceClass:
            * 0009_GenericDeviceType:
            * 000A_ProductCode:
            * 000B_ProductUrl:
            * 0010_LocationDescription:
            * 0011_PhysicalEnvironment:
            * 0012_DeviceEnabled:
            * 0013_AlarmMask:
            * 0014_DisableLocalConfig:
            * 0032_Custom:
            * 0033_Custom:
            * 0040_Custom:
            * 0041_Custom:
            * 0050_Custom:
            * 0051_Custom:
            * 0401_Custom:
            * 0404_Custom:
            * 4000_SwBuildId:
            * F000_Custom:
            * F109_Custom:
            * FF01_ExtInfo:
            * FF02_Custom:
            * FF0D_Custom:
            * FF19_Custom:
            * FF22_Custom:
            * FF23_Custom:
            * FF27_Custom:
            * FF28_Custom:
            * FF29_Custom:
            * FF2A_Custom:
            * FF30_Custom:
            * FFF0_Custom:
            * FFF1_Custom:
        * EF00_ManufacturerSpecific
        * 
        * 0004_Groups
            * 0000_NameSupport: 0
        * 0005_Scenes
            * 0000_SceneCount: 0
            * 0001_CurrentScene: 0
            * 0002_CurrentGroup: 0
            * 0003_SceneValid: false
            * 0004_NameSupport: 0
            * 0005_LastConfiguredBy:
    * Output
        * 0019_OtaUpgrade
            * 0000_UpgradeServerId: FFFFFFFFFFFFFFFF
            * 0001_FileOffset: -1
            * 0002_CurrentFileVersion:
            * 0003_CurrentZigbeeStackVersion:
            * 0004_DownloadedFileVersion:
            * 0005_DownloadedZigbeeStackVersion:
            * 0006_ImageUpgradeStatus: 0
            * 0007_ManufacturerId:
            * 0008_ImageTypeId:
            * 0009_MinimumBlockRequestPeriod:
            * 000A_ImageStamp:
        * 000A_Time
            * 0000_Time:
            * 0001_TimeStatus:
            * 0002_TimeZone:
            * 0003_DstStart:
            * 0004_DstEnd:
            * 0005_DstShift:
            * 0006_StandardTime:
            * 0007_LocalTime:
            * 0008_LastSetTime:
            * 0009_ValidUntilTime:

Binding table

Group membership

Associated devices

Neighbor table
ID	NWK	Type	Sleepy	Relation	LQI	PermitJoining	Depth
60A423FFFE415A6F	0000	Coordinator	false	Parent	216	UNKNOWN	0
CCCCCCFFFE00437C	364A	Router	false	Sibling	151	UNKNOWN	15
00158D0001DE5646	49EE	Router	false	Sibling	164	UNKNOWN	15
CCCCCCFFFEABF11C	9182	Router	false	Sibling	167	UNKNOWN	15
14B457FFFEC4FEA9	B70F	Router	false	Sibling	161	UNKNOWN	15
90FD9FFFFE31FC32	FAC2	Router	false	Sibling	167	UNKNOWN	15
Routing table
Status	Destination	Next hop
ACTIVE	0000	0000
ACTIVE	49EE	B70F
ACTIVE	B70F	B70F
INACTIVE	0000	0000
INACTIVE	0000	0000
INACTIVE	0000	0000
INACTIVE	0000	0000
INACTIVE	0000	0000
INACTIVE	0000	0000
INACTIVE	0000	0000
Node Descriptor
Aps Flags	0
Frequency Bands	[FREQ_2400_MHZ]
Server Capabilities	[]
Buffer Size	82
Incoming Transfer Size	82
Logical Type	Router
Mac Capabilities	[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]
Manufacturer Code	4098
Out Going Transfer Size	82
Stack Compliance	22
Power Descriptor
Current Power Mode	RECEIVER_ON_IDLE
Available Power Sources	[MAINS]
Current Power Source	MAINS
Power Level	FULL

Last update: Fri Jun 18 23:57:52 MSK 2021

К родному хабу не подключал, только напрямую к spruthub.
Телеграм: densh
Девайс в каталоге https://v2.sprut.ai/catalog/item/haozee-umnyj-termostat-tuya-zigbee
Покупал https://a.aliexpress.com/_AUIzDx

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/haozee-umnyj-termostat-tuya-zigbee
