### ISSUE TITLE
RH3052 new ID's

### ISSUE THREAD

**Issue by REPLAY5** [sprut/Hub#687]
Structure
Endpoint 1 (TEMPERATURE_SENSOR)
Input
0000_Basic
0001_ApplicationVersion: 74
0003_HwVersion: 1
0004_ManufacturerName: TUYATEC-yg5dcbfu
0005_ModelIdentifier: RH3052
0007_PowerSource: 3
4000_SwBuildId:
0001_PowerConfiguration
0020_BatteryVoltage: 27
0021_BatteryPercentageRemaining: 110
0402_TemperatureMeasurement
0000_MeasuredValue: 1595
0003_Identify
0405_RelativeHumidityMeasurement
0000_MeasuredValue: 8288
Output
0402_TemperatureMeasurement
0003_Identify
0405_RelativeHumidityMeasurement
0019_OtaUpgrade

-------------------------------------------------------
https://v2.sprut.ai/catalog/item/tuya-temperature-and-humidity-sensor

полностью аналогичен имеющимся в Templates RH3052 
Предложенное решение: "manufacturerId": "(TUYATEC-pwisa7ea|TUYATEC-gqhxixyk|TUYATEC-yg5dcbfu)",

**Comment by Batyushin** [comment]
необходимо добавить ссылку на магазин
