### ISSUE TITLE
RH3040 new ID's

### ISSUE THREAD

**Issue by REPLAY5** [sprut/Hub#688]
Structure
Endpoint 1 (IAS_ZONE)
Input
0000_Basic
0001_ApplicationVersion: 71
0003_HwVersion: 1
0004_ManufacturerName: TUYATEC-53o41joc
0005_ModelIdentifier: RH3040
0007_PowerSource: 3
4000_SwBuildId:
0500_IasZone
0010_IasCieAddress:
0001_PowerConfiguration
0020_BatteryVoltage: 28
0021_BatteryPercentageRemaining: 144
0003_Identify
Output
0019_OtaUpgrade

аналогичен https://v2.sprut.ai/catalog/item/tuya-motion-sensor

Предлагаемое решение: (RH3040.json) -> "manufacturerId": "(TUYATEC-ykufjza0|TUYATEC-53o41joc)",

**Comment by Batyushin** [comment]
необходимо добавить ссылку на магазин
