### ISSUE TITLE
0005_ModelIdentifier: DIYRuZ_Flower

### ISSUE THREAD

**Issue by Myshyk100** [sprut/Hub#689]
Address: 00124B002443D9FF/4BD0<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SIMPLE_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 3</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: DIYRuZ_Flower</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 26/01/2021 21:03</li></ul></li></ul></li><li>Output<ul><li>0400_IlluminanceMeasurement<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0402_TemperatureMeasurement<ul></ul></li><li>0403_PressureMeasurement<ul></ul></li><li>0405_RelativeHumidityMeasurement<ul></ul></li><li>0408_ManufacturerSpecific<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (SIMPLE_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul></ul></li></ul></li><li>Output<ul><li>0402_TemperatureMeasurement<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Mon Jun 14 19:36:02 MSK 2021
телеграмма: @ Myshyk100
в каталоге: https://v2.sprut.ai/catalog/item/modkam-sensor-vlaznosti-pocvy-zigbee-versia-no2

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/modkam-sensor-vlaznosti-pocvy-zigbee-versia-no2

**Comment by yorulez** [comment]
[DIYRuZ_Flower.txt](https://github.com/sprut/Hub/files/6910807/DIYRuZ_Flower.txt)
Шаблон под последнюю прошивку 2.1.0 Все работает. Влажность почвы, батарея, освещенность и все показания с bme280
