### ISSUE TITLE
Добавить поддержку  ТЕРМОСТАТ-АКТУАТОР DAT-101 ZWawe

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#69]
"manufacturerId": "032E"
  "modelId": "0013:0021"
https://defaro.ru/index.php/product/75-termostats/159-dat-101

**Comment by Ziracul** [comment]
[DAT-101.json.zip](https://github.com/sprut/Hub/files/4410837/DAT-101.json.zip)

**Comment by diamond5170** [comment]
Такие темплейты мало помогают.
Во-первых, там ошибка (сравни с другими термостатами), а во-вторых, нужно описать детально все параметры которые есть у устройства.

**Comment by Ziracul** [comment]
Понял
