### ISSUE TITLE
0005_ModelIdentifier: Remote motion sensor

### ISSUE THREAD

**Issue by Myshyk100** [sprut/Hub#691]
Address: 00047400000F3556/7157<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 2</li><li>0001_ApplicationVersion: 0</li><li>0002_StackVersion: 66</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName:  Legrand</li><li>0005_ModelIdentifier:  Remote motion sensor</li><li>0006_DateCode:  </li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 14400</li><li>0001_LongPollInterval: 20</li><li>0002_ShortPollInterval: 2</li><li>0003_FastPollTimeout: 40</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 30</li></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>000F_BinaryInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>FC01_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0006_ImageUpgradeStatus: 0</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>89</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>63</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4129</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>63</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY, DISPOSABLE_BATTERY, MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Apr 10 14:58:02 MSK 2021

telegram:@myshyk100 
в каталоге: https://v2.sprut.ai/catalog/item/legrand-umnyj-besprovodnoj-ik-datcik-dvizenia

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/legrand-umnyj-besprovodnoj-ik-datcik-dvizenia
