### ISSUE TITLE
Добавить темлейт RS-485 Универсальный одноплатный контроллер Syberia (версия 5.0)

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#694]
Производитель http://gtcontrollers.com/catalog/automatika-gtc/automatika-dley-ventilation/controller-syberia-5-0/

Каталог: отутствует
Управление: RS 485 (Modbus RTU)  
Функциональные возможности:
Напряжение питания, В                                                           ~220
Частота электрического тока питания, Гц                           50
Диапазон входного напряжения питания                            185-250
Максимальная потребляемая мощность, Вт                        12
Габаритные размеры, Д х Ш х В, мм                                      100х100х30
вес (с элементом питания CR2032), г                                    150
Температурный диапазон эксплуатации, °С                        от –25 до +40
Количество релейных одинарных выходов ~220В            7
Количество симисторных выходов, ~220В 0.5А                 4
Максимальный суммарный выходной ток ~220В, А          3
Количество выходов ШИМ 24В 20 мА                                   2
Количество универсальных (аналог 0-10 В/дискретных) входов                           2
Количество дискретных входов (без гальванической развязки)                            6
Количество аналоговых входов измерения температуры NTC 10k (без гальванической развязки)                   5
Количество аналоговых входов 0-10 В (без гальванической развязки)                4
Количество аналоговых выходов 0-10 В                             4
Количество последовательных портов без гальванической развязки RS 485 (Modbus RTU)                                3
Разъем для подключения дополнительных модулей тип                                         PLH 2×10
Тип разъема порта подключения пульта управления                                                8P8C (RJ45)
Элемент автономного питания часов                                                                            CR2032 (3В)

[Список регистров Оазис v.5.pdf](https://github.com/sprut/Hub/files/6695712/v.5.pdf)

@droni4 А С

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
