### ISSUE TITLE
ZB-SW02

### ISSUE THREAD

**Issue by kostyagrek** [sprut/Hub#695]
Address: 00124B0022270970/929C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW02</li><li>0006_DateCode: 20191113</li><li>0007_PowerSource: 1</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductUrl: </li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SwBuildId: </li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: </li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: </li><li>0001_CurrentScene: </li><li>0002_CurrentGroup: </li><li>0003_SceneValid: </li><li>0004_NameSupport: </li><li>0005_LastConfiguredBy: </li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: </li><li>4001_OnTime: </li><li>4002_OffWaitTime: </li><li>4003_StartUpOnOff: </li><li>8000_MultipleClick: </li><li>8001_IndicatorMode: </li><li>8002_RestartStatus: </li><li>8003_Custom: </li><li>F000_Custom: </li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: 2</li><li>0002_StackVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW02</li><li>0006_DateCode: 20191113</li><li>0007_PowerSource: 1</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductUrl: </li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SwBuildId: </li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0002_StackVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW02</li><li>0006_DateCode: 20191113</li><li>0007_PowerSource: 1</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductUrl: </li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SwBuildId: </li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: </li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: </li><li>0001_CurrentScene: </li><li>0002_CurrentGroup: </li><li>0003_SceneValid: </li><li>0004_NameSupport: </li><li>0005_LastConfiguredBy: </li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: </li><li>4001_OnTime: </li><li>4002_OffWaitTime: </li><li>4003_StartUpOnOff: </li><li>8000_MultipleClick: </li><li>8001_IndicatorMode: </li><li>8002_RestartStatus: </li><li>8003_Custom: </li><li>F000_Custom: </li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZclVersion: 1</li><li>0001_ApplicationVersion: </li><li>0002_StackVersion: </li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: eWeLink</li><li>0005_ModelIdentifier: ZB-SW02</li><li>0006_DateCode: 20191113</li><li>0007_PowerSource: 1</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductUrl: </li><li>0010_LocationDescription:                 </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SwBuildId: </li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE4174EB</td><td>0000</td><td>Coordinator</td><td>true</td><td>Parent</td><td>40</td><td>UNKNOWN</td><td>0</td></tr><tr><td>086BD7FFFE03EFF3</td><td>4CF6</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>086BD7FFFE2074B1</td><td>1A59</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Jun 23 11:11:06 MSK 2021

KostyaGrek в TG и Instagram
покупал: https://www.aliexpress.ru/item/EJLINK-Zigbee-Push-Button-Switch-No-Neutral-Wire-APP-Remote-Control-Smart-Light-Switches-Works-with/4001331194955.html

**Comment by Batyushin** [comment]
Просьба заполнить, соблюдая все требования, https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device


**Выключатель**
Версия Zigbee
Режим спаривания, сброса
Наличие нуля
Количество клавиш
Энергоизмеритель
Статус после восстановления питания
