### ISSUE TITLE
Пульт RWL022 не добавляется в СХ (Устройство было добавлено Олегом)

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#696]
** Подробное описание ошибки **
Пульт RWL022 не добавляется в СХ, пишет в init отчистка групп

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Отвязываю пульт от хаба Hue путем его удаления, несколько раз кликаю по кнопке, чтобы увидеть красные мигающие диоды, говорящие о том, что пульт отвязан.
2. Добавляю в хаб, путем 3 секундного зажатия на кнопку питания
3. Устройство не добавляется до конца.
** Ожидаемое поведение **
Ожидаю, что устройство появится в аксессуарах и будет управляемым.

** Скриншоты/ Логи **
<img width="1276" alt="Снимок экрана 2021-06-23 в 19 54 00" src="https://user-images.githubusercontent.com/59850734/123147968-5b658800-d468-11eb-9537-7691cd87efe4.png">
<img width="1439" alt="Снимок экрана 2021-06-23 в 19 54 10" src="https://user-images.githubusercontent.com/59850734/123147980-5e607880-d468-11eb-82f0-0e0ddcb043c1.png">
<img width="216" alt="Снимок экрана 2021-06-23 в 19 54 24" src="https://user-images.githubusercontent.com/59850734/123147982-5ef90f00-d468-11eb-9236-7bdb25ac8e28.png">

** Пожалуйста, заполните следующую информацию: **
14.6
Сборка 5081

** Дополнительные материалы **

@sprut666666

**Comment by sprut666666** [comment]
проверить в след апдейте

**Comment by earlywaff** [comment]
Проверил. Верхняя кнопка (Сервисная метка
ServiceLabelIndex 1 ) присылает сразу два параметра 1 и 4. Соответственно при нажатии на нее срабатывают два выключателя, что не очень хорошо. 
Регулировка яркости работает, верхняя и нижняя кнопка - ServiceLabelIndex 2 и 3.
Ну и соответственно кнопка Hue не работает совсем.

**Comment by earlywaff** [comment]
@sprut666666 up!
