### ISSUE TITLE
ptvo.bathroom

### ISSUE THREAD

**Issue by yorulez** [sprut/Hub#697]
Address: 00124B0022532581/E617<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.bathroom</li><li>0007_PowerSource: 1</li><li>4000_SwBuildId: 2021-04-05</li></ul></li><li>0B05_Diagnostics<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li></ul></li></ul></li><li>Endpoint 4 (ON_OFF_LIGHT)<ul><li>Input<ul><li>000C_AnalogInputBasic<ul></ul></li></ul></li><li>Output<ul><li>000C_AnalogInputBasic<ul><li>001C_Description: %</li><li>0055_PresentValue: 59.0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li></ul></li><li>Endpoint 5 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 8 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0006_OnOff<ul></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Jun 23 22:41:50 MSK 2021

endpoint 2 - switch
endpoint 4 - dht11
endpoint 5 - switch
endpoint 8 - pir sensor

До обновления 5050 частично работал вот этот габлон 
[ptvo_bathroom_norm.txt](https://github.com/sprut/Hub/files/6704573/ptvo_bathroom_norm.txt)
 
Сейчас в логе вот так
![изображение](https://user-images.githubusercontent.com/5469841/123160439-e3528e80-d476-11eb-8a42-36e9d3a89588.png)

**Comment by sprut666666** [comment]
В след сборку будет включён темплейт на DIYRuZ_Flower.json его можно изучить и добавить устройство
