### ISSUE TITLE
4-х канальное реле zigbee+rf433   TS0004

### ISSUE THREAD

**Issue by KVolkov87** [sprut/Hub#698]
Address: CC86ECFFFE5B84A9/3AB3<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 71</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_hdlpifbk</li><li>0005_ModelIdentifier: TS0004</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li></ul></li><li>E000_ManufacturerSpecific<ul></ul></li><li>E001_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 177</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>E001_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 211</li><li>0002_CurrentGroup: 8192</li><li>0003_SceneValid: true</li><li>0004_NameSupport: 180</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul></ul></li><li>Endpoint 3 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>E001_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 4</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 4 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>E001_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 9</li><li>0002_CurrentGroup: 37024</li><li>0003_SceneValid: true</li><li>0004_NameSupport: 9</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415683</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>252</td><td>UNKNOWN</td><td>0</td></tr><tr><td>000D6F00131532DC</td><td>1A8E</td><td>Router</td><td>false</td><td>Sibling</td><td>205</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6F00131844CE</td><td>CCF0</td><td>Router</td><td>false</td><td>Sibling</td><td>236</td><td>UNKNOWN</td><td>15</td></tr><tr><td>5C0272FFFEC4F836</td><td>E62A</td><td>Router</td><td>false</td><td>Sibling</td><td>111</td><td>UNKNOWN</td><td>15</td></tr><tr><td>588E81FFFEFF6046</td><td>E9AF</td><td>Router</td><td>false</td><td>Parent</td><td>255</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Jun 24 12:16:35 MSK 2021

Ссылка на aliexpress: https://aliexpress.ru/item/1005002530124474.html?spm=a2g0s.9042311.0.0.55ea33ed03aOwn

каталог sprut.hub: https://v2.sprut.ai/catalog/item/ewelink-zigbee433-4ch-modul-rele-distancionnogo-upravlenia

Template:  [TS0004.json.zip](https://github.com/sprut/Hub/files/6802192/TS0004.json.zip)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ewelink-zigbee433-4ch-modul-rele-distancionnogo-upravlenia

**Comment by KVolkov87** [comment]
рабочий Template пока не появится официальная потдержка.
[https://disk.yandex.ru/d/SawxxcRda9zQ9w](url)
