### ISSUE TITLE
https://v2.sprut.ai/catalog/item/siegenia-sensoair-aubi

### ISSUE THREAD

**Issue by WinManMC** [sprut/Hub#699]
Устройство не работает, не расчаознается. Планируется ли какое-то движение ?

https://v2.sprut.ai/catalog/item/siegenia-sensoair-aubi

_Originally posted by @Batyushin in https://github.com/sprut/Hub/issues/619#issuecomment-808125169_

https://github.com/sprut/Hub/issues/619#issue-841208174

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
