### ISSUE TITLE
Выключатель Aqara E1  без нуля (2 клавиши) lumi.switch.b2lc04

### ISSUE THREAD

**Issue by MobsX** [sprut/Hub#700]
Address: 54EF4410000F3FE1/959A<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>FCC0_ManufacturerSpecific<ul><li>0007_CustomXiaomi (115F): ByteArray [value=00 00 00 00 19 0F 72 CB]</li><li>0009_Mode (115F): 1</li><li>00F6_CustomXiaomi (115F): 300</li><li>00F7_ExtInfo (115F): {3=33, 100=false, 101=false, 5=1, 8=276, 154=0, 10=0, 11=0}</li><li>0200_MappingMode (115F): 1</li><li>0201_PowerOffMemory (115F): true</li></ul></li><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 20</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.b2lc04</li><li>0007_PowerSource: 1</li><li>0001_Custom (115F): 20</li><li>0005_ModelIdentifier (115F): lumi.switch.b2lc04</li><li>0006_Custom (115F): 12-23-2020</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 128</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 50331392</li><li>4000_GlobalSceneControl: true</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0002_CurrentFileVersion: 20</li><li>0006_ImageUpgradeStatus: 0</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 20</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.b2lc04</li><li>0007_PowerSource: 1</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>0007_CustomXiaomi (115F): ByteArray [value=00 00 00 00 00 00 00 00]</li><li>0009_Mode (115F): 0</li><li>00F6_CustomXiaomi (115F): 0</li><li>0200_MappingMode (115F): 1</li><li>0201_PowerOffMemory (115F): false</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 128</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 50331392</li><li>4000_GlobalSceneControl: true</li></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul></ul></li><li>Endpoint 51 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 41 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li><li>Endpoint 42 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li><li>Output<ul></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jun 25 22:16:41 MSK 2021 
Телеграм: Mobs2SPB
Девайс в [каталоге](https://v2.sprut.ai/catalog/item/aqara-smart-wall-switch-e1-double-bond)
Покупал [тут](https://aliexpress.ru/item/1005002669008946.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&social_params=40070417659&aff_fcid=6a864aacb29045f1945bbbc94e41b271-1624650605362-07317-_ArscHV&tt=MG&aff_fsk=_ArscHV&aff_platform=default&sk=_ArscHV&aff_trace_key=6a864aacb29045f1945bbbc94e41b271-1624650605362-07317-_ArscHV&shareId=40070417659&businessType=ProductDetail&platform=AE&terminal_id=0b5f94a26dd34ec984d9179fcef9b2d5)
Версия Zigbee: 3.0
Режим спаривания/сброса: Зажать две клавиши пока светодиоды не начнут моргать синим
Наличие нуля: Без
Количество клавиш: 2
Энергоизмеритель: нет
Статус после восстановления питания: запоминает последнее положение

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/aqara-smart-wall-switch-e1-double-bond

**Comment by Batyushin** [comment]
необходимо изменить протокол на зигбее

**Comment by MobsX** [comment]
@Batyushin не понимаю как это сделать(
