### ISSUE TITLE
Перемешивание названий аксессуаров при входе в /accessories с мобильного телефона.

### ISSUE THREAD

**Issue by REPLAY5** [sprut/Hub#701]
Не однократно возникала ошибка, при открытии страницы /accessories с последующем переходом, вероятно, на другой URL в этой же вкладке, либо при кликах на аксессуары / открытием модалок - возникает перемешивание названий.
Названия распределяются хаотичным образом, меняются местами, названия свойств могут стать названиями аксессуаров, либо меняются названия аксессуаров хаотично.

Открывал с Android , google chrome.

**Comment by MakeSimpleOrg** [comment]
Старый или новый веб? По старому репорты не принимаются.
