### ISSUE TITLE
Smart valve controller  TS0601 (zigbee привод крана на трубу)

### ISSUE THREAD

**Issue by KVolkov87** [sprut/Hub#705]
Address: 847127FFFE74855F/F958<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>EF00_ManufacturerSpecific<ul></ul></li><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 68</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_vrjkcam9</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: </li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: </li><li>8001_IndicatorMode: </li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>[56] SprutZigbeehub (1)</td><td>0006_OnOff</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415683</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>255</td><td>UNKNOWN</td><td>0</td></tr><tr><td>000D6F00131532DC</td><td>1A8E</td><td>Router</td><td>false</td><td>Sibling</td><td>255</td><td>UNKNOWN</td><td>15</td></tr><tr><td>CC86ECFFFE5B84A9</td><td>3AB3</td><td>Router</td><td>false</td><td>Sibling</td><td>232</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000D6F00131844CE</td><td>CCF0</td><td>Router</td><td>false</td><td>Sibling</td><td>255</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0002A8D727</td><td>D14D</td><td>Router</td><td>false</td><td>Parent</td><td>207</td><td>UNKNOWN</td><td>15</td></tr><tr><td>5C0272FFFEC4F836</td><td>E62A</td><td>Router</td><td>false</td><td>Sibling</td><td>103</td><td>UNKNOWN</td><td>15</td></tr><tr><td>588E81FFFEFF6046</td><td>E9AF</td><td>Router</td><td>false</td><td>Sibling</td><td>181</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jul 02 20:29:52 YEKT 2021

Ссылка на aliexpress: https://aliexpress.ru/item/1005002797508175.html?spm=a2g0s.9042311.0.0.274233edUbu3UA

каталог sprut.hub: https://v2.sprut.ai/catalog/item/centechia-smart-valve-controller

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/centechia-smart-valve-controller

**Comment by sprut666666** [comment]
В след сборке проверить обратную связь, если не работает отписать
