### ISSUE TITLE
TS0601	_TZE200_wunufsil	 

### ISSUE THREAD

**Issue by mikeavdeev** [sprut/Hub#706]
Address: 842E14FFFE126922/186C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 66</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZE200_wunufsil</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductUrl: </li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: </li><li>0012_DeviceEnabled: </li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SwBuildId: </li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>EF00_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: </li></ul></li><li>0006_OnOff<ul><li>8002_RestartStatus: </li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 000B57FFFE7E3120</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: </li><li>0003_CurrentZigbeeStackVersion: </li><li>0004_DownloadedFileVersion: </li><li>0005_DownloadedZigbeeStackVersion: </li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: </li><li>0008_ImageTypeId: </li><li>0009_MinimumBlockRequestPeriod: </li><li>000A_ImageStamp: </li></ul></li><li>000A_Time<ul><li>0000_Time: </li><li>0001_TimeStatus: </li><li>0002_TimeZone: </li><li>0003_DstStart: </li><li>0004_DstEnd: </li><li>0005_DstShift: </li><li>0006_StandardTime: </li><li>0007_LocalTime: </li><li>0008_LastSetTime: </li><li>0009_ValidUntilTime: </li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>000B57FFFE7E3120</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>168</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D00035F86A5</td><td>2020</td><td>Router</td><td>false</td><td>Sibling</td><td>159</td><td>UNKNOWN</td><td>15</td></tr><tr><td>842E14FFFE13A975</td><td>57F0</td><td>Router</td><td>false</td><td>Sibling</td><td>117</td><td>UNKNOWN</td><td>15</td></tr><tr><td>842E14FFFE126902</td><td>67B6</td><td>Router</td><td>false</td><td>Sibling</td><td>141</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00124B001B62523B</td><td>BD89</td><td>Router</td><td>false</td><td>Sibling</td><td>160</td><td>UNKNOWN</td><td>15</td></tr><tr><td>842E14FFFE13AB14</td><td>D516</td><td>Router</td><td>false</td><td>Sibling</td><td>216</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>67B6</td></tr><tr><td>ACTIVE</td><td>BD89</td><td>BD89</td></tr><tr><td>ACTIVE</td><td>57F0</td><td>57F0</td></tr><tr><td>ACTIVE</td><td>D516</td><td>D516</td></tr><tr><td>ACTIVE</td><td>67B6</td><td>67B6</td></tr><tr><td>ACTIVE</td><td>2020</td><td>2020</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jul 04 15:17:43 MSK 2021

tg: @mikeavdeev
Выключатель, двухкнопочный (с таким же ID модели есть ещё и термостат, и мотор для штор, и чего только нет)
Покупал здесь: https://aliexpress.ru/item/4001293680500.html
В каталоге есть похожий: https://v2.sprut.ai/catalog/item/lonsonho-smart-switch-1-switch (думал, что беру его)
Протокол: ZigBee
Режим спаривания: пять раз нажать любую кнопку, на шестой раз задержать на 5 секунд
Без нуля
Две клавиши.
После восстановления питания — выключен.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/lonsonho-smart-switch-2-switch

**Comment by mikeavdeev** [comment]
У девайса есть брат-близнец, только однокнопочный ([вот тут ишью было](https://github.com/sprut/Hub/issues/659)), с именем _TZE200_oisqyl4o. У обоих "Endpoint 1 (SMART_PLUG)". Попробовал темплейт от TS0012 и TS0011 — не помогает, даже при перезагрузке и переспаривании…
