### ISSUE TITLE
Названия комнат в триггерах

### ISSUE THREAD

**Issue by nikolay812** [sprut/Hub#71]
Просьба для удобства добавить в триггерах название комнат. Сейчас неудобно сортируются триггеры, не ясно к какой комнате относится тот или иной аксессуар. 

![B555C435-A4EC-42F1-A67F-4172D9AFE13D](https://user-images.githubusercontent.com/60763765/74417172-572e6100-4e57-11ea-9957-0b95da14f858.png)

**Comment by diamond5170** [comment]
В этих карточках сложно впихнуть все данные сразу. Нужно изменить их дизайн, пока не придумал как.

**Comment by diamond5170** [comment]
Добавил, но там есть еще что улучшать.
