### ISSUE TITLE
TS0011

### ISSUE THREAD

**Issue by mashkoff** [sprut/Hub#710]
Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device
Address: 5C0272FFFEDEBC0E/8BCC<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 66</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYZB01_qeqvmvti</li><li>0005_ModelIdentifier: TS0011</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Custom: �|(</li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 1</li><li>FFFE_Custom: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jul 10 22:13:04 ALMT 2021

Похожий девайс в каталоге: https://v2.sprut.ai/catalog/item/moeshouse-zigbee-vyklucatel-only-l-wire-3
После удержания клавиши без проблем находится, но нет шаблона
Покупал на AliExpress: https://www.aliexpress.com/item/4001233386602.html?spm=a2g0s.9042311.0.0.78af4c4dB0LYI5
@SergeyMashkov

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-zigbee-vyklucatel-only-l-wire

**Comment by mashkoff** [comment]
Спасибо большое
