### ISSUE TITLE
GIRIER  ZigBee Mini Switch 16A

### ISSUE THREAD

**Issue by KVolkov87** [sprut/Hub#711]
GIRIER  ZigBee Mini Switch 16A нет шаблона

Address: 0C4314FFFE9AF7FA/4FC0<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 64</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_majwnphg</li><li>0005_ModelIdentifier: TS0001</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: </li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>E000_ManufacturerSpecific<ul><li>D001_Custom: ByteArray [value=00 06]</li><li>D002_Custom: ByteArray [value=00 0A]</li><li>D003_Custom: AAAA</li></ul></li><li>E001_ManufacturerSpecific<ul><li>D010_Custom: 0</li><li>D030_Custom: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 177</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul><li>0010_GppMaxProxyTableEntries: 5</li><li>0011_ProxyTable: ByteArray [value=CF 62 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]</li><li>0016_GppFunctionality: 633903</li><li>0017_GppActiveFunctionality: 16777215</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415683</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>204</td><td>UNKNOWN</td><td>0</td></tr><tr><td>000D6F00131844CE</td><td>CCF0</td><td>Router</td><td>false</td><td>Sibling</td><td>121</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0002A8D727</td><td>D14D</td><td>Router</td><td>false</td><td>Sibling</td><td>173</td><td>UNKNOWN</td><td>15</td></tr><tr><td>5C0272FFFEC4F836</td><td>E62A</td><td>Router</td><td>false</td><td>Sibling</td><td>141</td><td>UNKNOWN</td><td>15</td></tr><tr><td>588E81FFFEFF6046</td><td>E9AF</td><td>Router</td><td>false</td><td>Sibling</td><td>146</td><td>UNKNOWN</td><td>15</td></tr><tr><td>847127FFFE74855F</td><td>F958</td><td>Router</td><td>false</td><td>Sibling</td><td>179</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jul 12 13:38:59 YEKT 2021

Ссылка на aliexpress: https://aliexpress.ru/item/1005002164359835.html?spm=a2g0s.9042311.0.0.380933edh2W5iE

каталог sprut.hub: https://v2.sprut.ai/catalog/item/girier-zigbee-mini-switch-16a

Template: [TS0001.json.zip](https://github.com/sprut/Hub/files/6802186/TS0001.json.zip)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/girier-zigbee-mini-switch-16a

**Comment by KVolkov87** [comment]
временный template: https://disk.yandex.ru/d/S23lz1T9fawirw
