### ISSUE TITLE
Добавить поддержку ZWave Fibaro FGWPF102 Розетка 

### ISSUE THREAD

**Issue by Ziracul** [sprut/Hub#72]
https://www.z-wave.ru/shop/category/ispolniteli/rozetochnyj-vyklyuchatel-fibaro-s-izmeritelem-moshchnosti.html

[FGWPF102.json.zip](https://github.com/sprut/Hub/files/4203873/FGWPF102.json.zip)
Проверено работает

**Comment by diamond5170** [comment]
Добавил, проверить работу в 1.5 и подтвердить.
