### ISSUE TITLE
 lumi.sen_ill.mgl01 - датчик освещенности (XIAOMI)

### ISSUE THREAD

**Issue by earlywaff** [sprut/Hub#720]
Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

Address: 04CF8CDF3C7F3408/6943<br><br><b>Structure</b><br><ul><li>Endpoint 1 (LIGHT_SENSOR)<ul><li>Input<ul><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 7782</li><li>0001_MinMeasuredValue: 1</li><li>0002_MaxMeasuredValue: 50000</li><li>0003_Tolerance: 0</li><li>0004_LightSensorType: 1</li></ul></li><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 26</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.sen_ill.mgl01</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 2019</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>00F7_ExtInfo (115F): {1=3185, 3=25, 4=424, 100=110, 5=12, 6=2, 8=282, 10=64437, 12=1}</li><li>00FC_CustomXiaomi (115F): false</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 31</li><li>0031_BatterySize: 7</li><li>003E_BatteryAlarmState: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>0017880109001531</td><td>6984</td><td>Router</td><td>false</td><td>Parent</td><td>93</td><td>UNKNOWN</td><td>1</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>0</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>0</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>0</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Jul 21 22:42:51 MSK 2021

**В темплейте исправил в manufacturerId с lumi на XIAOMI**
Телеграм: @UskovvNa
Девайс в каталоге: https://v2.sprut.ai/catalog/item/xiaomi-mi-light-detection-sensor
Брал тут https://www.pleer.ru/product_711932_Xiaomi_Mijia_Light_Sensor.html

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/xiaomi-mi-light-detection-sensor

**Comment by earlywaff** [comment]
Address: 04CF8CDF3C7F3408/6F2B<br><br><b>Structure</b><br><ul><li>Endpoint 1 (LIGHT_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 26</li><li>0002_StackVersion: 2</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: XIAOMI</li><li>0005_ModelIdentifier: lumi.sen_ill.mgl01</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 2019</li></ul></li><li>0400_IlluminanceMeasurement<ul><li>0000_MeasuredValue: 10792</li><li>0001_MinMeasuredValue: 1</li><li>0002_MaxMeasuredValue: 50000</li><li>0003_Tolerance: 0</li><li>0004_LightSensorType: 1</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>00F7_ExtInfo (115F): {1=3018, 3=25, 4=424, 100=27, 5=13, 6=4, 8=282, 10=18608, 12=1}</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 30</li><li>0031_BatterySize: 7</li><li>003E_BatteryAlarmState: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE, MAINS_POWER]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4718</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jul 24 21:14:49 MSK 2021

**Comment by earlywaff** [comment]
<img width="1440" alt="Снимок экрана 2021-07-24 в 21 14 55" src="https://user-images.githubusercontent.com/59850734/126877676-1d67e432-601a-44db-99b3-03e057d40e84.png">
