### ISSUE TITLE
Moes Zigbee Scene Switch 4 ch

### ISSUE THREAD

**Issue by KVolkov87** [sprut/Hub#723]
Address: 60A423FFFE803674/E581<br><br><b>Structure</b><br><ul><li>Endpoint 1 (DIMMER_SWITCH)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 65</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_xabckq1v</li><li>0005_ModelIdentifier: TS004F</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Custom: ��(</li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 1</li><li>FFFE_Custom: 0</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 0</li><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>8004_Custom: 0</li></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jul 24 19:20:31 YEKT 2021

Ссылка на aliexpress: https://a.aliexpress.com/_A1l6iy

каталог sprut.hub: https://v2.sprut.ai/catalog/item/moeshouse-moes-zigbee-scene-switch-4-ch
аналоги:  
1: https://v2.sprut.ai/catalog/item/girier-zigbee-scene-switch
2: https://v2.sprut.ai/catalog/item/lonsonho-umnyj-pereklucatel-zigbee

Режим спаривания: нижняя левая клавиша 10 сек. Пока все 4 лампы не начнут моргать.
Клавиши: нажатие, двойное нажатие, удержание.
Батарея: cr2430

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-moes-zigbee-scene-switch-4-ch
