### ISSUE TITLE
Moes Zigbee Smart Vibration Sensor

### ISSUE THREAD

**Issue by KVolkov87** [sprut/Hub#724]
Address: 84FD27FFFE17BCFD/0E3C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 45</li><li>0002_ZoneStatus: 0</li><li>0010_IasCieAddress: 0120001100000000</li><li>0011_ZoneId: 255</li><li>0012_NumberOfZoneSensitivityLevelsSupported: 50</li><li>0013_CurrentZoneSensitivityLevel: 2</li></ul></li><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 70</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TYZB01_3zv6oleo</li><li>0005_ModelIdentifier: TS0210</li><li>0006_DateCode: </li><li>0007_PowerSource: 3</li><li>FFDF_Custom: </li><li>FFE2_Custom: 21</li><li>FFFE_Custom: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 3</li><li>0020_BatteryVoltage: 29</li><li>0021_BatteryPercentageRemaining: 178</li></ul></li><li>000A_Time<ul><li>0007_LocalTime: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE415683</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>243</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>512</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>512</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jul 24 20:12:48 YEKT 2021

Ссылка на aliexpress: https://a.aliexpress.com/_ApO0qU

каталог sprut.hub: https://v2.sprut.ai/catalog/item/moeshouse-moes-zigbee-smart-vibration-sensor

Батарея: 2хААА
СПАРИВАНИЕ: 5 сек единственную клавишу

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-moes-zigbee-smart-vibration-sensor
