### ISSUE TITLE
Smart valve controller TS0001 Tuya (zigbee привод крана на трубу)_TZ3000_nljyfqcf

### ISSUE THREAD

**Issue by ivan-trifonov-77** [sprut/Hub#726]
Address: 0C4314FFFE84C45C/C0B8<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZclVersion: 3</li><li>0001_ApplicationVersion: 64</li><li>0002_StackVersion: 0</li><li>0003_HwVersion: 1</li><li>0004_ManufacturerName: _TZ3000_nljyfqcf</li><li>0005_ModelIdentifier: TS0001</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: ��(</li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>E000_ManufacturerSpecific<ul><li>D001_Custom: ByteArray [value=00 06]</li><li>D002_Custom: ByteArray [value=00 0A]</li><li>D003_Custom: AAAA</li></ul></li><li>E001_ManufacturerSpecific<ul><li>D010_Custom: 2</li><li>D030_Custom: 2</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 177</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 2</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul><li>0010_GppMaxProxyTableEntries: 5</li><li>0011_ProxyTable: ByteArray [value=]</li><li>0016_GppFunctionality: 633903</li><li>0017_GppActiveFunctionality: 16777215</li><li>0022_GpClientLinkKey: 5A6967426565416C6C69616E63653039</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>000B57FFFE18055C</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>161</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D000373C4CE</td><td>0186</td><td>Router</td><td>false</td><td>Sibling</td><td>131</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00024ADF66</td><td>22ED</td><td>Router</td><td>false</td><td>Sibling</td><td>68</td><td>UNKNOWN</td><td>15</td></tr><tr><td>086BD7FFFE39028A</td><td>AD1C</td><td>Router</td><td>false</td><td>Sibling</td><td>102</td><td>UNKNOWN</td><td>15</td></tr><tr><td>000B3CFFFEF8FC34</td><td>ADDA</td><td>Router</td><td>false</td><td>Sibling</td><td>86</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0002FB5160</td><td>B530</td><td>Router</td><td>false</td><td>Sibling</td><td>170</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00039289B5</td><td>F5F0</td><td>Router</td><td>false</td><td>Sibling</td><td>85</td><td>UNKNOWN</td><td>15</td></tr><tr><td>04CF8CDF3C8236D1</td><td>FFC8</td><td>Router</td><td>false</td><td>Sibling</td><td>63</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Jul 25 12:51:13 MSK 2021
Ссылка на aliexpress: https://a.aliexpress.com/_9vZLQY
каталог sprut.hub: https://v2.sprut.ai/catalog/item/tuya-crane

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tuya-crane

**Comment by sprut666666** [comment]
После апдейта проверить работу опций
