### ISSUE TITLE
SPZB0001

### ISSUE THREAD

**Issue by olaaff** [sprut/Hub#729]
Address: 00158D00030CA1FC/4CF3<br><br><b>Structure</b><br><ul><li>Endpoint 1 (THERMOSTAT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 18</li><li>0003_HwVersion: 34</li><li>0004_ManufacturerName: Eurotronic</li><li>0005_ModelIdentifier: SPZB0001</li><li>0007_PowerSource: 3</li><li>4000_SwBuildId: 18181120</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0201_Thermostat<ul><li>4000_TrvMode (1037): 2</li><li>4001_SetValvePosition (1037): 0</li><li>4002_Errors (1037): 0</li><li>4003_CurrentTemperatureSetPoint (1037): 2100</li><li>4008_HostFlags (1037): 1</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0201_Thermostat<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerId: 0000000000000000</li><li>0002_CurrentFileVersion: 19055488</li><li>0004_DownloadedFileVersion: 0</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerId: 4151</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4151</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>DISPOSABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Jul 27 18:07:11 MSK 2021

телеграм: Olfa
покупал тут: https://www.ebay.com/itm/124226008703

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/eurotronic-spirit-zigbee-thermostat
