### ISSUE TITLE
Поправить темплет для FGMS-001 ZW5 v3.3

### ISSUE THREAD

**Issue by llleeehhh** [sprut/Hub#73]
** Подробное описание ошибки **
8: Unsupported device: manufacturerId 010F, deviceType 0801, deviceId 4002

** Как воспроизвести ? **
После обновления отваливается датчик, при добавлении выдает ошибку Unsupported device

** Дополнительные материалы **
модель FGMS-001 ZW5 v3.3
нужно добавить в шаблоне параметр  "0801:4002"

 "modelId": "0800:1001,0800:2001,0800:3001,0800:4001,0801:4002,0800:6001,0801:1001,0801:1002,0801:2001",

**Comment by diamond5170** [comment]
1.5
