### ISSUE TITLE
Нестабильно работает триггер внешнего датчика EUROTRONIC SPIRIT

### ISSUE THREAD

**Issue by antoniob10** [sprut/Hub#736]
** Подробное описание ошибки **
Есть термоголовка Eurotronic Spirit Z-Wave, у нее есть возможность получать данные температуры со внешнего датчика. При установке триггера на датчике температуры к головке время от временем перестают передаваться данные со внешнего датчика и данные начинают браться с термоголовки. 

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Часто лечится путем перезагрузка хаба, но не всегда.
2. Нажмите «....»
3. Прокрутите вниз до «....»
4. Смотрите ошибку

** Ожидаемое поведение **
Четкое и краткое описание того, что вы ожидали.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.
![1](https://user-images.githubusercontent.com/49080186/128696591-a4dc81e3-535b-440e-9680-23fd6142a7a8.png)
![3](https://user-images.githubusercontent.com/49080186/128696596-19fbfe91-6453-4df8-9883-84d2b6757757.png)
![2](https://user-images.githubusercontent.com/49080186/128696599-e7104766-5b1a-4bab-b6f1-d77388f3810d.png)

** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, IOS]

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by MakeSimpleOrg** [comment]
Это вообще не так работает, триггер меняет только визуально температуру, а реальная в устройстве какая была такая и остается.
Чтобы использовать внешний датчик, нужно включить параметр под номером 8, а так же прокинуть ассоциацию от внешнего датчика на термоголовку. Триггеры здесь не нужны.

**Comment by antoniob10** [comment]
в параметре 8 есть выбор лишь "Use ext. temp. sensor", но он не сохраняется ни чего более в это поле не прописывается.  При выборе любой группы устройства термостат во внешнем датчике Neo PIRV3 данные не сохраняются

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
