### ISSUE TITLE
Добавить Темплет ZW FGS-223 Fibaro

### ISSUE THREAD

**Issue by llleeehhh** [sprut/Hub#74]
** Максимально подробное описание предложения.**
При добавлении ZW устройства, выдет ошибку.
17: Unsupported device: manufacturerId 010F, deviceType 0203, deviceId 4000

** Дополнительные материалы **
17: Unsupported device: manufacturerId 010F, deviceType 0203, deviceId 4000
FGS-223 Fibaro
https://z-wave.ru/shop/category/ispolniteli/dvukhkanalnyj-relejnyj-vyklyuchatel-2x15-kvt170717172641.html

**Comment by diamond5170** [comment]
1.5
