### ISSUE TITLE
Выключатель aqara e1 двухклавишный с нейтралью(lumi.switch.b2nc01)

### ISSUE THREAD

**Issue by kachalex** [sprut/Hub#741]
Address: 54EF4410001ADB3D/E701<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 20</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.b2nc01</li><li>0007_PowerSource: 1</li><li>0001_Custom (115F): 20</li><li>0005_ModelIdentifier (115F): lumi.switch.b2nc01</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>0007_CustomXiaomi (115F): ByteArray [value=00 00 00 00 19 1B 0E 27]</li><li>0009_Mode (115F): 1</li><li>00F6_CustomXiaomi (115F): 300</li><li>00F7_ExtInfo (115F): {3=27, 100=false, 101=false, 5=1, 8=276, 9=256, 154=0, 10=0, 11=0}</li><li>023E_TimeInterval (115F): 589845</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 128</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 50331392</li><li>4000_GlobalSceneControl: true</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: 0000000000000000</li><li>0002_CurrentFileVersion: 20</li><li>0006_ImageUpgradeStatus: 0</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 20</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.b2nc01</li><li>0007_PowerSource: 1</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>0007_CustomXiaomi (115F): ByteArray [value=00 00 00 00 00 00 00 00]</li><li>0009_Mode (115F): 0</li><li>00F6_CustomXiaomi (115F): 0</li><li>023E_TimeInterval (115F): 589845</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 128</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 50331392</li><li>4000_GlobalSceneControl: true</li></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 51 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 41 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 42 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE4156AB</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>174</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Aug 14 13:39:01 MSK 2021

**Comment by kachalex** [comment]
![image](https://user-images.githubusercontent.com/42259721/129443864-a1c2734f-338a-40b0-8fcc-059a6de8025a.png)

![image](https://user-images.githubusercontent.com/42259721/129443886-5d9bbfb4-7d6d-4e03-a5de-908e09ef72db.png)

**Comment by Batyushin** [comment]
Можно ссылку на устройство или модель

**Comment by kachalex** [comment]
https://aliexpress.ru/item/1005002922807285.html?spm=a2g39.orderlist.0.0.73044aa689ImGG&_ga=2.249700422.1321738598.1628997210-770840956.1614420733&_gac=1.58853855.1625828894.CjwKCAjw55-HBhAHEiwARMCszgeODczCDIwDe01CZ2j9GdStK8cveDbyoFsWMobzFU2_BQNG15Ik5RoCaXgQAvD_BwE

**Comment by kachalex** [comment]
![image](https://user-images.githubusercontent.com/42259721/129485089-e72250ff-85eb-4ff4-9f1d-10e6d3cb3311.png)

**Comment by Batyushin** [comment]
если не сложно напиши еще модель. та что на коробке

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/aqara-smart-wall-switch-e1-double-bond-with-neutral

**Comment by kachalex** [comment]
![P_20210816_121422](https://user-images.githubusercontent.com/42259721/129540678-55b97bba-36e1-428b-a998-6d5920206a89.jpg)
![P_20210816_121141](https://user-images.githubusercontent.com/42259721/129540742-5fb5d25e-0bfa-4da4-a011-f10b572ec3be.jpg)
![P_20210816_121223](https://user-images.githubusercontent.com/42259721/129540863-fc76c86e-f0aa-41bb-9b8c-585e8deaf107.jpg)

**Comment by kachalex** [comment]
model: QBKG41LM
