### ISSUE TITLE
Heiman smoke sensor SmokeSensor-EF-3.0

### ISSUE THREAD

**Issue by al-bulanov** [sprut/Hub#745]
Является полной копией SmokeSensor-N-3.0. https://v2.sprut.ai/catalog/item/heiman-smoke-detector: 
<b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 2</li><li>0001_ApplicationVersion: 17</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 16</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: SmokeSensor-EF-3.0</li><li>0006_DateCode: 2019.8.29</li><li>0007_PowerSource: 3</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 40</li><li>0002_ZoneStatus: 32</li><li>0010_IASCIEAddress: 60A423FFFE416702</li><li>0011_ZoneID: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 32</li><li>0021_BatteryPercentageRemaining: 200</li><li>0034_BatteryRatedVoltage: 30</li></ul></li><li>0502_IasWd<ul><li>0000_MaxDuration: 240</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>011C_LastMessageLQI: 196</li><li>011D_LastMessageRSSI: -51</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 17</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4619</li><li>0008_ImageTypeID: 16512</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>[69] Sprut zigbee (1)</td><td>0500_IasZone</td></tr><tr><td>1</td><td>IEEE</td><td>[69] Sprut zigbee (1)</td><td>0001_PowerConfiguration</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Aug 15 07:51:29 VLAT 2021

**Comment by al-bulanov** [comment]
Вот по этому шаблону работает нормально и давно.
[SmokeSensor-EF-3.0.txt](https://github.com/sprut/Hub/files/6987232/SmokeSensor-EF-3.0.txt)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/heiman-smoke-detector
