### ISSUE TITLE
Счетчик импульсов modkam

### ISSUE THREAD

**Issue by al-bulanov** [sprut/Hub#746]
Address:<b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: ptvo_counter_2ch</li><li>0006_DateCode: 2021-05-04</li><li>0007_PowerSource: 3</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductURL: </li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SWBuildID: 2021-05-04</li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: </li><li>0001_MainsFrequency: </li><li>0002_Custom: </li><li>0003_Custom: </li><li>0004_Custom: </li><li>0005_Custom: </li><li>0006_Custom: </li><li>0007_Custom: </li><li>000C_Custom: </li><li>0010_MainsAlarmMask: </li><li>0011_MainsVoltageMinThreshold: </li><li>0012_MainsVoltageMaxThreshold: </li><li>0013_MainsVoltageDwellTripPoint: </li><li>0014_Custom: </li><li>0020_BatteryVoltage: 21</li><li>0021_BatteryPercentageRemaining: 0</li><li>0030_BatteryManufacturer: </li><li>0031_BatterySize: </li><li>0032_BatteryAHrRating: </li><li>0033_BatteryQuantity: </li><li>0034_BatteryRatedVoltage: </li><li>0035_BatteryAlarmMask: </li><li>0036_BatteryVoltageMinThreshold: </li><li>0037_BatteryVoltageThreshold1: </li><li>0038_BatteryVoltageThreshold2: </li><li>0039_BatteryVoltageThreshold3: </li><li>003A_BatteryPercentageMinThreshold: </li><li>003B_BatteryPercentageThreshold1: </li><li>003C_BatteryPercentageThreshold2: </li><li>003D_BatteryPercentageThreshold3: </li><li>003E_BatteryAlarmState: </li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: ptvo_counter_2ch</li><li>0006_DateCode: 2021-05-04</li><li>0007_PowerSource: 3</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductURL: </li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SWBuildID: 2021-05-04</li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: </li><li>0001_MainsFrequency: </li><li>0002_Custom: </li><li>0003_Custom: </li><li>0004_Custom: </li><li>0005_Custom: </li><li>0006_Custom: </li><li>0007_Custom: </li><li>000C_Custom: </li><li>0010_MainsAlarmMask: </li><li>0011_MainsVoltageMinThreshold: </li><li>0012_MainsVoltageMaxThreshold: </li><li>0013_MainsVoltageDwellTripPoint: </li><li>0014_Custom: </li><li>0020_BatteryVoltage: 26</li><li>0021_BatteryPercentageRemaining: 28</li><li>0030_BatteryManufacturer: </li><li>0031_BatterySize: </li><li>0032_BatteryAHrRating: </li><li>0033_BatteryQuantity: </li><li>0034_BatteryRatedVoltage: </li><li>0035_BatteryAlarmMask: </li><li>0036_BatteryVoltageMinThreshold: </li><li>0037_BatteryVoltageThreshold1: </li><li>0038_BatteryVoltageThreshold2: </li><li>0039_BatteryVoltageThreshold3: </li><li>003A_BatteryPercentageMinThreshold: </li><li>003B_BatteryPercentageThreshold1: </li><li>003C_BatteryPercentageThreshold2: </li><li>003D_BatteryPercentageThreshold3: </li><li>003E_BatteryAlarmState: </li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 3 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: ptvo_counter_2ch</li><li>0006_DateCode: 2021-05-04</li><li>0007_PowerSource: 3</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductURL: </li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SWBuildID: 2021-05-04</li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: ,0A</li><li>0041_MaxPresentValue: </li><li>0045_MinPresentValue: </li><li>0051_OutOfService: </li><li>0055_PresentValue: 1606.0</li><li>0067_Reliability: </li><li>006A_Resolution: </li><li>006F_StatusFlags: 0</li><li>0075_EngineeringUnits: </li><li>0100_ApplicationType: </li></ul></li></ul></li><li>Output<ul><li>000C_AnalogInputBasic<ul><li>0055_PresentValue: </li></ul></li></ul></li></ul></li><li>Endpoint 5 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: ptvo_counter_2ch</li><li>0006_DateCode: 2021-05-04</li><li>0007_PowerSource: 3</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductURL: </li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SWBuildID: 2021-05-04</li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: ,0A</li><li>0041_MaxPresentValue: </li><li>0045_MinPresentValue: </li><li>0051_OutOfService: </li><li>0055_PresentValue: 6.0</li><li>0067_Reliability: </li><li>006A_Resolution: </li><li>006F_StatusFlags: 0</li><li>0075_EngineeringUnits: </li><li>0100_ApplicationType: </li></ul></li></ul></li><li>Output<ul><li>000C_AnalogInputBasic<ul><li>0055_PresentValue: </li></ul></li></ul></li></ul></li><li>Endpoint 6 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: ptvo_counter_2ch</li><li>0006_DateCode: 2021-05-04</li><li>0007_PowerSource: 3</li><li>0008_GenericDeviceClass: </li><li>0009_GenericDeviceType: </li><li>000A_ProductCode: </li><li>000B_ProductURL: </li><li>0010_LocationDescription: </li><li>0011_PhysicalEnvironment: 0</li><li>0012_DeviceEnabled: true</li><li>0013_AlarmMask: </li><li>0014_DisableLocalConfig: </li><li>0032_Custom: </li><li>0033_Custom: </li><li>0040_Custom: </li><li>0041_Custom: </li><li>0050_Custom: </li><li>0051_Custom: </li><li>0401_Custom: </li><li>0404_Custom: </li><li>4000_SWBuildID: 2021-05-04</li><li>F000_Custom: </li><li>F109_Custom: </li><li>FF01_ExtInfo: </li><li>FF02_Custom: </li><li>FF0D_Custom: </li><li>FF19_Custom: </li><li>FF22_Custom: </li><li>FF23_Custom: </li><li>FF27_Custom: </li><li>FF28_Custom: </li><li>FF29_Custom: </li><li>FF2A_Custom: </li><li>FF30_Custom: </li><li>FFF0_Custom: </li><li>FFF1_Custom: </li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: </li><li>4001_OnTime: </li><li>4002_OffWaitTime: </li><li>4003_StartUpOnOff: </li><li>8000_MultipleClick: </li><li>8001_IndicatorMode: </li><li>8002_RestartStatus: </li><li>8003_CustomTuya: </li><li>F000_Custom: </li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: </li><li>4001_OnTime: </li><li>4002_OffWaitTime: </li><li>4003_StartUpOnOff: </li><li>8000_MultipleClick: </li><li>8001_IndicatorMode: </li><li>8002_RestartStatus: </li><li>8003_CustomTuya: </li><li>F000_Custom: </li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Sat Aug 14 12:04:51 VLAT 2021

Модель: https://v2.sprut.ai/catalog/item/modkam-scetcik-impulsov-zigbee.

Работает давно и нормально по этому шаблону:
[ptvo_counter_2ch_final.txt](https://github.com/sprut/Hub/files/6987242/ptvo_counter_2ch_final.txt)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/modkam-scetcik-impulsov-zigbee
