### ISSUE TITLE
ZESP с другим id

### ISSUE THREAD

**Issue by al-bulanov** [sprut/Hub#747]
Полная копия https://v2.sprut.ai/catalog/item/xiaomi-gateway-zesp-edition. У меня видимо давно прошитый ZESP, определяется по-другому.
Address: <b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: NXP</li><li>0005_ModelIdentifier: ZESProuter</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 1000-0001</li></ul></li><li>0300_ColorControl<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 53</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>VALIDATION_UNDERWAY</td><td>D467</td><td>A1FA</td></tr><tr><td>ACTIVE</td><td>846D</td><td>9055</td></tr><tr><td>ACTIVE</td><td>A1FA</td><td>A1FA</td></tr><tr><td>ACTIVE</td><td>AF62</td><td>9055</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>46D6</td><td>FFFE</td></tr><tr><td>ACTIVE</td><td>81C6</td><td>81C6</td></tr><tr><td>ACTIVE</td><td>D2A8</td><td>D2A8</td></tr><tr><td>ACTIVE</td><td>93B4</td><td>A1FA</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>B5AF</td><td>FFFE</td></tr><tr><td>ACTIVE</td><td>C706</td><td>C706</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>9430</td><td>FFFE</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>5D69</td><td>FFFE</td></tr><tr><td>ACTIVE</td><td>9055</td><td>9055</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>57E0</td><td>FFFE</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>D762</td><td>FFFE</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>3720</td><td>FFFE</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>2726</td><td>FFFE</td></tr><tr><td>ACTIVE</td><td>A529</td><td>A529</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>887C</td><td>FFFE</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>BF19</td><td>FFFE</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>0E00</td><td>FFFE</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4151</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Aug 15 08:11:44 VLAT 2021

Работает давно и нормально по этому шаблону: 
[ZESP.txt](https://github.com/sprut/Hub/files/6987250/ZESP.txt)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/xiaomi-gateway-zesp-edition
