### ISSUE TITLE
Aqara S1 smart panel scene

### ISSUE THREAD

**Issue by al-bulanov** [sprut/Hub#748]
Address: <b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 28</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.switch.n4acn4</li><li>0007_PowerSource: 1</li><li>0005_ModelIdentifier (115F): lumi.switch.n4acn4</li></ul></li><li>FCC0_ManufacturerSpecific<ul><li>0007_CustomXiaomi (115F): ByteArray [value=00 00 00 00 1B AA C0 B3]</li><li>0009_Mode (115F): 1</li><li>00EE_CustomXiaomi (115F): 68683036</li><li>00F6_CustomXiaomi (115F): 300</li><li>00F7_ExtInfo (115F): {3=33, 100=false, 101=false, 5=3, 102=false, 7=0, 9=5376, 11=0, 13=68683036, 14=0, 149=0.0, 150=2290.21728515625, 151=0.0, 152=0.0, 154=0}</li><li>0201_PowerOffMemory (115F): false</li><li>020F_Custom (115F): ByteArray [value=0C 5C 0E 2A 95 A3 CB B8 A7 14 31 71 6A E3 80 A5]</li><li>0210_Custom (115F): 1</li><li>0211_Custom (115F): 50</li><li>0212_Custom (115F): 0</li><li>0214_Custom (115F): 1</li><li>0215_Custom (115F): 0</li><li>0216_Custom (115F): 15</li><li>0217_Custom (115F): 3</li><li>0218_Custom (115F): false</li><li>0219_Custom (115F): 3</li><li>0221_Custom (115F): false</li><li>0222_Custom (115F): 10</li><li>0223_Custom (115F): ByteArray [value=01]</li><li>0224_Custom (115F): ByteArray [value=01]</li><li>0225_Custom (115F): ByteArray [value=01]</li><li>0227_Custom (115F): false</li><li>0228_Custom (115F): 917(41)75905603052404</li><li>022A_Custom (115F): 3</li><li>022B_Custom (115F): 7</li><li>023C_Custom (115F): 0</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 128</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 50331392</li><li>4000_GlobalSceneControl: true</li></ul></li></ul></li><li>Output<ul><li>0300_ColorControl<ul></ul></li><li>0000_Basic<ul></ul></li><li>0013_MultistateOutputBasic<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li><li>000A_Time<ul></ul></li><li>000D_AnalogOutputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>FCC0_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 50331392</li></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 3 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul></ul></li><li>FCC0_ManufacturerSpecific<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>00F5_Custom: 50331392</li></ul></li></ul></li></ul></li><li>Endpoint 21 (SMART_PLUG)<ul><li>Input<ul><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 41 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 42 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 43 (ON_OFF_LIGHT)<ul><li>Input<ul><li>0012_MultistateInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 31 (SMART_PLUG)<ul><li>Input<ul><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Aug 15 21:08:40 VLAT 2021

https://v2.sprut.ai/catalog/item/aqara-umnaa-panel-s1

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/aqara-umnaa-panel-s1

**Comment by stas3133283** [comment]
Ждём что появится

**Comment by stas3133283** [comment]
Очень ждём
