### ISSUE TITLE
Ошибка при смене типа устройства на WB-MDM3

### ISSUE THREAD

**Issue by dragaleff** [sprut/Hub#75]
при смене типа устройства на вентилятор в каналах диммера WB-MDM3 устройство навсегда пропадает со связи. Лечится только удалением и добавлением модуля

1. Перейдите к «Аксессуры»
2. Выбрать WB-MDM3, любой канал. Поменять тип на вентилятор

Устройство пропадет со связи в ХК
Версия: [например, IOS] 13

**Comment by MakeSimpleOrg** [comment]
В 1.6.4 смена типа заменена на создание копии.
