### ISSUE TITLE
Датчик влажности почвы Modkam (JetHome edition, Zigbee,CC2530)

### ISSUE THREAD

**Issue by upmkvik** [sprut/Hub#750]
Address: 00124B002241F615/C196<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SIMPLE_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 3</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: modkam.ru</li><li>0005_ModelIdentifier: DIYRuZ_Flower</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 07/07/2021 16:18</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 28</li><li>0021_BatteryPercentageRemaining: 48</li><li>0200_Custom: 6275</li></ul></li></ul></li><li>Output<ul><li>0400_IlluminanceMeasurement<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0402_TemperatureMeasurement<ul></ul></li><li>0403_PressureMeasurement<ul></ul></li><li>0405_RelativeHumidityMeasurement<ul></ul></li><li>0408_SoilMoisture<ul></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (SIMPLE_SENSOR)<ul><li>Output<ul><li>0402_TemperatureMeasurement<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>[105] Sprut zigbee (1)</td><td>0001_PowerConfiguration</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_PERIODICALLY</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Wed Aug 18 21:29:23 MSK 2021

Покупал тут: https://jhome.ru/catalog/sensors/292/#desc

**Comment by Myshyk100** [comment]
так уже он есть и мое ишью закрыто

**Comment by upmkvik** [comment]
> так уже он есть и мое ишью закрыто
именно JetHome?

**Comment by Myshyk100** [comment]
0005_ModelIdentifier: DIYRuZ_Flower
 вот модель

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/jethome-datcik-vlaznosti-pocvy-modkam-edition-zigbeecc2530
