### ISSUE TITLE
Modkam.ru Zigbee реле. Версия №2 с прошивкой ptvo.switch с дополнительными датчиками

### ISSUE THREAD

**Issue by KVolkov87** [sprut/Hub#752]
В прошивке отвязан выключатель от реле на 4 канеле (4 endpoint)  теперь это кнопка (одиночный, длинный, двойной, тройной)
5 endpoint распаянный зуммер на плате.
6 endpoint BME280 (температура, даление, Влажность)
8 endpoint DHT22 (температура, Влажность)

Address: 00124B002328C873/7187<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: ptvo.info</li><li>0005_ModelIdentifier: ptvo.switch</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 2021-08-17</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0000_Basic<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 2<ul><li>Input<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 3<ul><li>Input<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 4<ul><li>Input<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0012_MultistateInputBasic<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 5<ul><li>Input<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 6<ul><li>Input<ul><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: </li></ul></li><li>0403_PressureMeasurement<ul><li>0000_MeasuredValue: </li></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: </li></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: %,76</li><li>0055_PresentValue: 52.6806640625</li><li>006F_StatusFlags: 31</li></ul></li></ul></li></ul></li><li>Endpoint 8<ul><li>Input<ul><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: </li></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: </li></ul></li><li>000C_AnalogInputBasic<ul><li>001C_Description: %</li><li>0055_PresentValue: 56.70000076293945</li><li>006F_StatusFlags: 31</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>6</td><td>IEEE</td><td>[56] SprutZigbeehub - СИСТЕМА (1)</td><td>0402_TemperatureMeasurement</td></tr><tr><td>6</td><td>IEEE</td><td>[56] SprutZigbeehub - СИСТЕМА (1)</td><td>0405_RelativeHumidityMeasurement</td></tr><tr><td>8</td><td>IEEE</td><td>[56] SprutZigbeehub - СИСТЕМА (1)</td><td>0402_TemperatureMeasurement</td></tr><tr><td>8</td><td>IEEE</td><td>[56] SprutZigbeehub - СИСТЕМА (1)</td><td>0405_RelativeHumidityMeasurement</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>588E81FFFEFF6046</td><td>E9AF</td><td>Router</td><td>true</td><td>Parent</td><td>32</td><td>UNKNOWN</td><td>1</td></tr><tr><td>847127FFFE74855F</td><td>F958</td><td>Router</td><td>true</td><td>Unknown</td><td>14</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00158D0002A8D727</td><td>D14D</td><td>Router</td><td>true</td><td>Unknown</td><td>46</td><td>UNKNOWN</td><td>255</td></tr><tr><td>000D6F00131532DC</td><td>1A8E</td><td>Router</td><td>true</td><td>Unknown</td><td>10</td><td>UNKNOWN</td><td>255</td></tr><tr><td>000D6F00131844CE</td><td>CCF0</td><td>Router</td><td>true</td><td>Unknown</td><td>35</td><td>UNKNOWN</td><td>255</td></tr><tr><td>0C4314FFFE9AF7FA</td><td>4FC0</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>5C0272FFFEC4F836</td><td>E62A</td><td>Router</td><td>true</td><td>Unknown</td><td>148</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00124B00232831DA</td><td>9783</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE415683</td><td>0000</td><td>Coordinator</td><td>true</td><td>Unknown</td><td>84</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>F958</td></tr><tr><td>ACTIVE</td><td>F958</td><td>E9AF</td></tr><tr><td>ACTIVE</td><td>E9AF</td><td>E9AF</td></tr><tr><td>ACTIVE</td><td>E62A</td><td>E62A</td></tr><tr><td>ACTIVE</td><td>9783</td><td>CCF0</td></tr><tr><td>ACTIVE</td><td>D14D</td><td>E9AF</td></tr><tr><td>ACTIVE</td><td>5B5C</td><td>CCF0</td></tr><tr><td>ACTIVE</td><td>CCF0</td><td>CCF0</td></tr><tr><td>ACTIVE</td><td>4FC0</td><td>CCF0</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Aug 19 09:52:25 YEKT 2021

Сайт производителя прошивки с описанием датчиков: https://ptvo.info/zigbee-configurable-firmware-features/

Сайт с устройством Zigbee реле. Версия №2 Modkam: http://modkam.ru/?p=1054
Ссылка на каталог Sprut: https://v2.sprut.ai/catalog/item/modkam-cetyrehkanalnoe-zigbee-rele

Сайт с аналогичным устройством  Modkam и кучей датчиков - Модуль входов/выходов zigbee: http://modkam.ru/?p=1922
Ссылка модуль Входов-Выходов на Sprut.ai: https://v2.sprut.ai/catalog/item/modkam-modul-vhodov-vyhodov-zigbee

Telegram: @KonstantinVolkov

**Comment by KVolkov87** [comment]
В zigbee2mqtt выглядит так:
![image](https://user-images.githubusercontent.com/34130138/130012891-a749d55e-8390-4a2d-9528-c31de2fabd0b.jpeg)
![image](https://user-images.githubusercontent.com/34130138/130012907-e0d86c42-5a4c-44b4-92df-828554c5d47a.jpeg)
![image](https://user-images.githubusercontent.com/34130138/130012919-5d14e8de-d449-4c80-89a0-b5ec332cfdb6.jpeg)

**Comment by KVolkov87** [comment]
В конфигураторе прошивки: ![image](https://user-images.githubusercontent.com/34130138/130013081-0c37e9af-6fab-4ea3-bf12-2f3c7828cd6d.jpeg)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/modkam-cetyrehkanalnoe-zigbee-rele

**Comment by sprut666666** [comment]
Любые самоделки поддерживаются самостоятельно, темплейт можно положить в папку "Custom"
