### ISSUE TITLE
Невозможно удалить устройство, которое добавилось неправильно в старой ревизии

### ISSUE THREAD

**Issue by GDaurov** [sprut/Hub#763]
** Подробное описание ошибки **
Не удаляются неправильно спаренные устройства.
Ревизия: 5591

** Как воспроизвести ? **

Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. http://spruthub.local:55555/controllers
2. Захожу в ZWave
3. Появляется список устройств
4. всё есть на скриншотах
5. 9 и 18 устройства это Пульт-контроллер Aeotec Minimote
6. Ни удалить ни что-либо сделать с ним не получается.

Устройство было добавлено давно.
Вот из Информации
<b>Unknown - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>18</td></tr><tr><td width=35%>Manufacturer Id</td><td>7FFFFFFF</td></tr><tr><td width=35%>Device Type</td><td>7FFFFFFF</td></tr><tr><td width=35%>Device Id</td><td>7FFFFFFF</td></tr><tr><td width=35%>App Version</td><td>0.0</td></tr><tr><td width=35%>Basic Class</td><td>Controller</td></tr><tr><td width=35%>Generic Class</td><td>Generic Controller</td></tr><tr><td width=35%>Specific Class</td><td>Portable Remote Controller</td></tr><tr><td width=35%>Routing</td><td>false</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>false</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V0 Basic</li><li>V1 NoOperation</li></ul></li></ul><br>Last update: null

** Ожидаемое поведение **
Ревизия: 5591
При добавлении этого устройства пишет что устройство не опознано. 
Но его можно спокойно удалить.

** Пожалуйста, заполните следующую информацию: **
Ревизия: 5591
ZWave Sprut stick 700

** Дополнительные материалы **
![Снимок экрана 2021-08-22 в 01 11 16](https://user-images.githubusercontent.com/40370942/130336151-b20a94a2-a372-45c6-9103-e42d1b962c55.png)
![Снимок экрана 2021-08-22 в 01 11 26](https://user-images.githubusercontent.com/40370942/130336157-370ed44b-88c4-4888-b79c-50109c26fa73.png)
![Снимок экрана 2021-08-22 в 01 11 40](https://user-images.githubusercontent.com/40370942/130336158-6909637f-6667-4689-9be5-4ed748ee05ea.png)

Было написано:
_"Если на вкладке информации напротив Manufacturer Id/Device Type/Device Id стоит значение "7FFFFFFF" то необходимо вначале переспарить устройство."_
Тут именно так. но при сваривании создаётся новое устройство.

**Comment by GDaurov** [comment]
И вот ещё что показывает карта
![Снимок экрана 2021-08-22 в 11 23 16](https://user-images.githubusercontent.com/40370942/130347733-f1c786f1-4913-4112-808e-f87e1552433e.png)
![Снимок экрана 2021-08-22 в 11 23 29](https://user-images.githubusercontent.com/40370942/130347736-2500ac75-ee84-49d9-8143-327ba8b81774.png)

**Comment by GDaurov** [comment]
Одно из решений проблемы:
После перезапуска СпретХаба на несколько секунд в меню появляется пункт - "Удалить".
Потом пропадал.

Устройства удалил именно таким способом.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"

**Comment by GDaurov** [comment]
Писал несколько раз. Проигнорировали. 
В итоге нашёл решение.
Выше описано. 
Удалил лишние устройства. 

Тогда была пауза на весь z-wave. Возможно из-за этого.
