### ISSUE TITLE
Обратный hk, aqara ,нет ответа.

### ISSUE THREAD

**Issue by Eranovmaxim** [sprut/Hub#764]
Версия 5591. Лампочки aqara подключены к aqara hub. Aqara hub подключён к СХ через обратный hk. Через интерфейс СХ все работает корректно. Через приложение apple home нет ответа.![image](https://user-images.githubusercontent.com/32778056/130415958-39bcdd15-fd01-4aca-8e1c-8b50e4cd7639.png)
![image](https://user-images.githubusercontent.com/32778056/130415976-0c9e8c76-bc45-4bd7-ae01-235bcc284ffd.png)

@eranovmaxim

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
