### ISSUE TITLE
Неправильно строится карта Zigbee устройств

### ISSUE THREAD

**Issue by dragaleff** [sprut/Hub#77]
Какое-то странное построение карты. Причины не выяснены
![photo_2020-03-01_21-28-34](https://user-images.githubusercontent.com/61537836/75632760-8ba06c00-5c10-11ea-8146-d960c0ce3558.jpg)

**Comment by Mustiktob** [comment]
Проблему подтверждаю. У меня тоже самое. Но у меня нет роутера в сети, поэтому карта выглядит так,
![Снимок экрана 2020-03-16 в 23 43 30](https://user-images.githubusercontent.com/10119698/76790090-fc827f00-67df-11ea-9d53-3c2a59515382.png)

**Comment by diamond5170** [comment]
Не актуально.
