### ISSUE TITLE
Мультисенсор Aeotec 4 in 1 Gen5

### ISSUE THREAD

**Issue by mobibet** [sprut/Hub#770]
Производитель : AEOTEC 
Устройство : AEOTEC MULTISENSOR GEN5
Model: ZW074-C (868.42 MHz)

<b>AEON Labs - Unknown</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>2</td></tr><tr><td width=35%>Manufacturer Id</td><td>0086</td></tr><tr><td width=35%>Device Type</td><td>0002</td></tr><tr><td width=35%>Device Id</td><td>004A</td></tr><tr><td width=35%>App Version</td><td>1.2</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Sensor Notification</td></tr><tr><td width=35%>Specific Class</td><td>Notification Sensor</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th><th>Max</th></tr><tr><td>1</td><td></td><td>[]</td><td>?</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 Basic</li><li>V1 PowerLevel<ul><li>Level: 0</li><li>Timeout: 0</li></ul></li><li>V1 AssociationGRPInfo</li><li>V1 Hail</li><li>V2 Version</li><li>V1 NoOperation</li><li>V1 FirmwareUpdateMD</li><li>V2 WakeUp<ul><li>Current: 5h</li><li>Default: </li><li>Min: </li><li>Max: 24855d, 3h, 14m, 7s</li><li>Step: </li></ul></li><li>V2 ManufacturerSpecific</li><li>V1 Configuration</li><li>V1 ZWavePlusInfo</li><li>V3 Alarm<ul><li>Burglar</li></ul></li><li>V1 Battery<ul><li>Level: 100</li><li>Low: false</li></ul></li><li>V1 Security</li><li>V5 SensorMultiLevel<ul><li>RelativeHumidity: 50</li><li>Temperature: 29</li><li>Luminance: 18</li></ul></li><li>V2 Association</li><li>V1 DeviceResetLocally</li><li>V1 SensorBinary<ul></ul></li></ul></li></ul><br>Last update: Sat Aug 28 08:58:44 MSK 2021

https://rus.z-wave.me/shop/sensors/multisensor-aeon-4-v-1

**Comment by Batyushin** [comment]
Подскажите это он? https://v2.sprut.ai/catalog/item/aeotec-dsb05-zweu-z-wave-multisensor

**Comment by mobibet** [comment]
> Подскажите это он? https://v2.sprut.ai/catalog/item/aeotec-dsb05-zweu-z-wave-multisensor

внешне похож, но маркировка отличается

**Comment by MakeSimpleOrg** [comment]
r5847
