### ISSUE TITLE
State: Работает, Error: 1 lumi.plug.maeu01

### ISSUE THREAD

**Issue by pabl33** [sprut/Hub#771]
5591
lumi.plug.maeu01 на прошивке 32 выдаёт ошибку
![E7D92C29-A33F-4C3B-8ADD-530D59136713](https://user-images.githubusercontent.com/48541799/131223596-76bdc61f-ec55-4f84-a1f5-2ae113adced5.jpeg)

**Comment by sprut666666** [comment]
удали кастомный темплейт

**Comment by pabl33** [comment]
папка зигби/кастом пуста

**Comment by sprut666666** [comment]
в телегу, оперативно уже будем решать
