### ISSUE TITLE
Скачет яркость при объединении TRADFRI bulb E27 W opal 1000lm через виртуальную лампу

### ISSUE THREAD

**Issue by simart11** [sprut/Hub#773]
** Подробное описание ошибки **
При создании виртуальной лампы и привязки к ней 6 ламп TRADFRI bulb E27 W opal 1000lm (пробовал от 1 до 6 ламп, результат тот же) через "связь с устройством" не возможно выставить нужный уровень яркости, при выставлении любого уровня яркости, через несколько сек. яркость возвращется на 100%.
![Снимок экрана 2021-08-28 в 22 10 44](https://user-images.githubusercontent.com/31985815/131228438-29e3307d-1bbe-47a2-af12-24155ae322bd.png)

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Создать виртуальную лампу с возможностью регулировки яркости
2. Через "Связь с устройством" к яркости привязать яркость нескольких ламп TRADFRI bulb E27 W opal 1000lm
3. Через "Связь с устройством" к вкл/выкл привязать вкл/выкл нескольких ламп TRADFRI bulb E27 W opal 1000lm (не обязательный пункт)
4. Попробовать порегулировать яркость виртуальной лампы

** Ожидаемое поведение **
Коректная регулировка яркости у виртуальной лампы к которой привязаны TRADFRI bulb E27 W opal 1000lm (такая же проблема и с лампами GS BDHM8E27W70-I1)

** Скриншоты/ Логи **
Вышлю по запросу (необходимости) @Art_Sim

** Пожалуйста, заполните следующую информацию: **
Версия  SprutHub 5591, установлено на Малине 3

** Дополнительные материалы **
Точно такая же проблема и с лампами GS BDHM8E27W70-I1. На кухне к виртуальной лампе привязаны 2 таких лампы и тоже яркость не возможно отрегулировать. Проблема скорее всего в виртуальной лампе

**Comment by sprut666666** [comment]
обновиться, проверить, если не исправилось в телеграмме логи, будем решать в оперативном порядке
