### ISSUE TITLE
Термоголовка Moes Radiator Zigbee TVR Controller, Model ID: TS0601

### ISSUE THREAD

**Issue by Doublenik8** [sprut/Hub#774]
Address: 84FD27FFFEA65846/4151

Structure
Endpoint 1 (SMART_PLUG)
Input
0000_Basic
0000_ZCLVersion: 3
0001_ApplicationVersion: 64
0002_StackVersion: 0
0003_HWVersion: 1
0004_ManufacturerName: _TZE200_b6wax7g0
0005_ModelIdentifier: TS0601
0006_DateCode:
0007_PowerSource: 3
FFDF_Custom: ���(����(�
FFE2_Custom: 31
FFE4_Custom: 0
FFFE_Custom: 0
EF00_ManufacturerSpecific
0001_Custom: 1
0002_Custom: 26
0003_Custom: 210
0004_Custom: false
0005_Custom: 0
0007_Custom: 0
0008_Custom: false
0009_Custom: 1
000D_Custom: false
000E_Custom: 97
0065_Custom: ByteArray [value=06 00 28 0B 1E 2A 0D 1E 2C 11 1E 2E 06 00 30 0C 00 2E 0E 1E 2C 11 1E 2A 06 00 26 0C 1E 28 0E 1E 2A 12 1E 28]
0067_Custom: 300
0068_Custom: 100
0069_Custom: -2
006A_Custom: false
006B_Custom: 20
006C_Custom: 45
006D_Custom: 5
0004_Groups
0000_NameSupport: 0
0005_Scenes
0000_SceneCount: 0
0001_CurrentScene: 0
0002_CurrentGroup: 0
0003_SceneValid: false
0004_NameSupport: 0
Output
0019_OtaUpgrade
0000_UpgradeServerID: FFFFFFFFFFFFFFFF
0001_FileOffset: -1
0006_ImageUpgradeStatus: 0
000A_Time

Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags 0
Frequency Bands [FREQ_2400_MHZ]
Server Capabilities []
Buffer Size 82
Incoming Transfer Size 82
Logical Type End Device
Mac Capabilities [REDUCED_FUNCTION_DEVICE]
Manufacturer Code 4098
Out Going Transfer Size 82
Stack Compliance 22

Power Descriptor
Current Power Mode RECEIVER_ON_IDLE
Available Power Sources [MAINS]
Current Power Source MAINS
Power Level FULL

**Comment by Batyushin** [comment]
добавьте ссылку на "где купить"

**Comment by Doublenik8** [comment]
Покупал на Али https://aliexpress.ru/item/1005002431040917.html?spm=a2g0s.9042311.0.0.699e33edYIzb5U&_ga=2.79875031.1381721037.1630195455-608439351.1630195455

**Comment by Doublenik8** [comment]
Сделано.

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/moeshouse-moes-radiator-zigbee-tvr-controller

**Comment by Doublenik8** [comment]
Сделано ранее.

**Comment by stas3133283** [comment]
Присоединяюсь к ожиданию

**Comment by kersuzio** [comment]
Так же присоединяюсь к ожиданию 🤞

**Comment by ra5ven** [comment]
тоже жду)
