### ISSUE TITLE
Добавить QS-Zigbee-C01

### ISSUE THREAD

**Issue by kachalex** [sprut/Hub#780]
Address: A4C1383BC1DC9C15/147A<br><br><b>Structure</b><br><ul><li>Endpoint 1 (WINDOW_COVERING_DEVICE)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 66</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_fccpjz5z</li><li>0005_ModelIdentifier: TS130F</li><li>0007_PowerSource: 1</li></ul></li><li>0102_WindowCovering<ul><li>0008_CurrentPositionLiftPercentage: 81</li><li>8000_Custom: 0</li><li>F000_PositionState: 1</li><li>F001_UpDownConfirm: 1</li><li>F002_ControlBack: 0</li><li>F003_ScheduleTime: 100</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 66</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Sep 05 16:44:18 MSK 2021

**Comment by kachalex** [comment]
https://v2.sprut.ai/catalog/item/tuya-zigbee-curtain-module

vendor другой только

**Comment by kachalex** [comment]
заказыл по ссылке с каталога

**Comment by kachalex** [comment]
@kacha_alex - telegram

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/leomoca-zigbee-curtain-module

**Comment by kachalex** [comment]
Надо вендор только длбавить
