### ISSUE TITLE
TRADFRI on/off switch

### ISSUE THREAD

**Issue by beezoncheg** [sprut/Hub#786]
Address: 84FD27FFFE9EE367/DDE8<br><br><b>Structure</b><br><ul><li>Endpoint 1 (NON_COLOR_CONTROLLER)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 33</li><li>0002_StackVersion: 98</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI on/off switch</li><li>0006_DateCode: 20190723</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 2.2.010</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 172800</li><li>0001_LongPollInterval: 1160</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 0</li><li>0021_BatteryPercentageRemaining: 100</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0009_Alarms<ul></ul></li><li>FC7C_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0102_WindowCovering<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 570492465</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4476</li><li>0008_ImageTypeID: 4549</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Sep 10 00:12:18 MSK 2021

Ссылка на товар https://www.ikea.com/ru/ru/p/tradfri-trodfri-besprovodnoy-reostat-belyy-30408601/
Обновленная модель кнопки с партномером 304.086.01
Ссылка на каталог: https://v2.sprut.ai/catalog/item/ikea-tradfri-on-off-switch
Телеграм @beezoncheg

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ikea-tradfri-on-off-switch

**Comment by stas3133283** [comment]
Ждем

**Comment by mrykin** [comment]
Присоединяюсь, ждём, логин в телеге: https://t.me/mrykin

**Comment by mrgarik** [comment]
+1)

**Comment by beezoncheg** [comment]
Не выдержал и набрутфорсил шаблон для кнопки. Нормально работают только одиночные нажатия. Длинные нажатия определяются, но живут своей жизнью. Победить не смог, пользоваться ими не стоит до выхода версии от более компетентных шаблонописцев

**Disclaimer! Шаблон испольуйте на свой страх и риск!**
Нужно закинуть файл в /home/makesimple/.SprutHub/data/Templates/ZigBee/Custom и убрать .txt расширение (гитхаб не дает аттачить json). Когда выйдет нормальный шаблон кастомный нужно будет удалить.
[TRADFRI onoff switch.json.txt](https://github.com/sprut/Hub/files/7697897/TRADFRI.onoff.switch.json.txt)

P.S.
@sprut666666, надеюсь это будет приоритетным шаблоном за выигрыш в инстаграм угадайке про прошивку для сенсорного выключателя 😅

**Comment by Skull09rus** [comment]
Надежда то есть еще на добавление шаблона )?
