### ISSUE TITLE
Устройство TS0043 отдает не все данные 

### ISSUE THREAD

**Issue by MartinzSmitt** [sprut/Hub#788]
Переключатель [Tuya Smart Life ZigBee](https://v2.sprut.ai/catalog/item/tuya-smart-life-zigbee-besprovodnoj-pereklucatel) через HomeKit в HomeAssistant передает состояния только на первую клавишу
 
При добавлении SprutHub в HomeAssistant у устройства только 3 триггера:
"single_press" button 1
"double_press" button 1
"long_press" button 1

**Скриншот**

![](https://i.ibb.co/3zPLMPC/2021-09-10-15-44-29.png)

**Comment by sprut666666** [comment]
Увы это проблема HA, и компонента для работы с HomeKit
