### ISSUE TITLE
Добавить поддержку ZW Fibaro FGT-001 термостат

### ISSUE THREAD

**Issue by gusman163** [sprut/Hub#79]
** Максимально подробное описание предложения.**
manufacturerId 010F, 
deviceId 1301:4000

** Дополнительные материалы **
https://rus.z-wave.me/shop/termostats/radiatornyy-termostat-fibaro-heat-controller/

**Comment by diamond5170** [comment]
Добавил, проверить работу в 1.5 и подтвердить.
