### ISSUE TITLE
Не пробрасываются релейные модули в spruthub

### ISSUE THREAD

**Issue by sincereman** [sprut/Hub#8]
** Подробное описание ошибки **
Чётко и коротко об ошибке.

Не пробрасывааются релейные модули wb-mrwl3 и wb-mr6lv/s  в раздел аксессуары spruthub.

![изображение](https://user-images.githubusercontent.com/52529431/60657409-ff0f9500-9e59-11e9-818a-8774d93db8d8.png)

** Как воспроизвести ? **
Просто иметь датчик подключенный к wirenboard

** Ожидаемое поведение **

Появится в аксессуарах.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

WB 6.5 с последней прошивкой.

**Comment by sprut666666** [comment]
Обновиться, пробовать, решено.

**Comment by sincereman** [comment]
model=WB-MR6LVS - добавился
Wb-MRWL3  - не добавился

**Comment by sincereman** [comment]
> 
> 
> Обновиться, пробовать, решено.
model=WB-MR6LVS - добавился
Wb-MRWL3 - не добавился
