### ISSUE TITLE
Добавить поддержку шарового крана ZW Defaro DAV-101

### ISSUE THREAD

**Issue by gusman163** [sprut/Hub#80]
** Максимально подробное описание предложения.**
manufacturerId 032E
DeviceId 0021:0011
** Дополнительные материалы **
https://defaro.ru/index.php/product/76-tap/175-dav-101

**Comment by MakeSimpleOrg** [comment]
Необходимо скопировать сюда данные из вкладки "Информация" (значок i напротив устройства на вкладке контроллеров), для копирования там есть специальная кнопка.

**Comment by ekomrak** [comment]
<b>Defaro - DAS-101</b><br><br><table border=1 width=100%><tr><td width=35%>Node Id</td><td>4</td></tr><tr><td width=35%>Manufacturer Id</td><td>032E</td></tr><tr><td width=35%>Device Type</td><td>0021</td></tr><tr><td width=35%>Device Id</td><td>0011</td></tr><tr><td width=35%>Basic Class</td><td>Routing Slave</td></tr><tr><td width=35%>Generic Class</td><td>Switch Binary</td></tr><tr><td width=35%>Specific Class</td><td>Valve Open Close</td></tr><tr><td width=35%>Routing</td><td>true</td></tr><tr><td width=35%>Secure</td><td>false</td></tr><tr><td width=35%>Beaming</td><td>true</td></tr><tr><td width=35%>Listening</td><td>true</td></tr><tr><td width=35%>Frequently Listening</td><td>false</td></tr></table><br><b>Association Groups</b><br><table border=1 width=100%><tr><th>ID</th><th>Label</th><th>Associations</th></tr><tr><td>1</td><td></td><td>[node_1]</td></tr><tr><td>2</td><td></td><td>[]</td></tr></table><br><b>Structure</b><br><ul><li>Endpoint 0<ul><li>V1 Configuration</li><li>V1 Basic</li><li>V1 FirmwareUpdateMD</li><li>V1 SwitchBinary</li><li>V1 Association</li><li>V2 Version</li><li>V2 ManufacturerSpecific</li><li>V1 NoOperation</li><li>V1 Security</li><li>V2 MultiChannelAssociation</li><li>V1 SceneActivation</li></ul></li></ul><br>Last update: Fri Jul 31 12:06:05 MSK 2020

**Comment by MakeSimpleOrg** [comment]
Это одно и то же устройство, различие в опциях, у крана их всего две первых, а у реле 1-54.
Отличие только в версии прошивки и в Specific Class - Valve Open Close.

Какая версия прошивки?

**Comment by MakeSimpleOrg** [comment]
1.6.4
