### ISSUE TITLE
TS130F

### ISSUE THREAD

**Issue by riorao** [sprut/Hub#801]
Address: A4C138B1C548FE5C/8D6A<br><br><b>Structure</b><br><ul><li>Endpoint 1 (WINDOW_COVERING_DEVICE)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 66</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_j1xl73iw</li><li>0005_ModelIdentifier: TS130F</li><li>0007_PowerSource: 1</li></ul></li><li>0102_WindowCovering<ul><li>0008_CurrentPositionLiftPercentage: 0</li><li>8000_Custom: 0</li><li>F000_PositionState: 1</li><li>F001_UpDownConfirm: 1</li><li>F002_ControlBack: 0</li><li>F003_ScheduleTime: 100</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 66</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (WINDOW_COVERING_DEVICE)<ul><li>Input<ul><li>0102_WindowCovering<ul><li>0008_CurrentPositionLiftPercentage: 0</li><li>8000_Custom: 0</li><li>F000_PositionState: 1</li><li>F001_UpDownConfirm: 1</li><li>F002_ControlBack: 0</li><li>F003_ScheduleTime: 100</li></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Sep 23 21:08:07 MSK 2021

@RioUrawa

Приобретал: https://aliexpress.ru/item/1005003044227983.html?spm=a2g0s.9042311.0.0.4d5533edf6rMDS
Каталог: отсутствует или не нашел
Zigbee 2,4 ГГц ~ 2,484 ГГц IEEE802.15.4
Режим при первом запуске начинает спариваться, дальше удержание зажатой кнопки 10 секунд, при спаривании начинает моргать синий светодиод.
С нулевой линией
Две клавиши
Управление жалюзи или электро шторой на устройстве на устройстве модель Lonsonho 2ch Curtain Module
Максимальная нагрузка на канал 3А
[spruthub.log](https://github.com/sprut/Hub/files/7219996/spruthub.log)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/lonsonho-2ch-zigbee-curtain-module

**Comment by riorao** [comment]
Когда ждать поддержку в сх?

**Comment by EddieKursk** [comment]
В СХ контролируется только один канал из двух
