### ISSUE TITLE
Долгое обновление статуса устройства при подключении по modbus

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#804]
** Подробное описание ошибки **
При подключении диммеров (wb-mrgbw-d) и реле (wb-mr6cu2) по modbus имеет место некорректное отображение статусов устройств в СХ и в Homekit:
Для диммеров статус после изменения состояния устройства подключенной к соответствующему белому каналу не меняется сразу. Но иногда меняется через некоторое время (несколько часов)
Для реле статус после смены статуса кнопкой крайне редко показывает неверное состояние
При управлении через Homekit отрабатывает корректно. Но если статус включен - то сначала надо нажать выключить и после опять включить, а после управления через Homekit нажатие кнопки на включение не приводит к включению диммера - требуется зажать кнопку для выставления макс яркости. 

** Как воспроизвести ? **
Подключить модули по modbus, диммеры в режиме 4 каналов белой ленты. 

** Ожидаемое поведение **
У диммера есть отдельный контрол Enable (R,G,B,W) для включения - надо как-то получать от него информацию о статусе устройства (связать), ведь по mqtt (с триггерами) оно работает корректно

Ожидаю корректного отображения статуса реле/диммеров в СХ и ХК

Версия: 1.7.2b rev 5844

Ранее был открыт тикет #275

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
