### ISSUE TITLE
Не тот шаблон WB-MRPS6

### ISSUE THREAD

**Issue by annenkovin** [sprut/Hub#806]
Имеется два устройства WB-MRPS6, прошивка 1.16.2, id 15 и 58. В логе ошибки.

![image](https://user-images.githubusercontent.com/70009569/135073920-2f1ea8cf-79be-40cd-9143-6dc46edceabf.jpeg)

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
