### ISSUE TITLE
В спрутхаб вместо WBIO-DI-WD-14  прокидывается WBIO-DI-HVD

### ISSUE THREAD

**Issue by sincereman** [sprut/Hub#81]
** Подробное описание ошибки **
В спрутхаб вместо WBIO-DI-WD-14  прокидывается WBIO-DI-HVD

** Как воспроизвести ? **
Вставить модуль, запустить поиск устройств wirenboard

** Ожидаемое поведение **
Ожидаю появления WBIO-DI-WD-14

![photo_2020-03-10_17-49-55](https://user-images.githubusercontent.com/52529431/76324827-9d140300-62f7-11ea-9cc4-20a7b9036855.jpg)
![photo_2020-03-10_17-50-05](https://user-images.githubusercontent.com/52529431/76324830-9dac9980-62f7-11ea-8c36-fe5847ffd145.jpg)

**Comment by sprut666666** [comment]
сделал универсально, ибо модель идентифицировать нельзя
