### ISSUE TITLE
TS0601

### ISSUE THREAD

**Issue by iPhouse-Pro** [sprut/Hub#813]
Address: 5C0272FFFEDB146D/E179<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 82</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZE200_wv90ladg</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: </li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>EF00_ManufacturerSpecific<ul><li>0001_Custom: true</li><li>0002_Custom: 250</li><li>0003_Custom: 250</li><li>0004_Custom: 0</li><li>0007_Custom: false</li><li>000D_Custom: 0</li><li>000E_Custom: 0</li><li>0065_Custom: ByteArray [value=01 A4 00 DC 01 FE 00 BE 03 FC 00 DC 05 28 00 BE]</li><li>0066_Custom: ByteArray [value=01 A4 00 DC 01 FE 00 BE 03 FC 00 DC 05 28 00 BE]</li><li>0067_Custom: ByteArray [value=01 A4 00 DC 01 FE 00 BE 03 FC 00 DC 05 28 00 BE]</li><li>0068_Custom: ByteArray [value=01 A4 00 DC 01 FE 00 BE 03 FC 00 DC 05 28 00 BE]</li><li>0069_Custom: ByteArray [value=01 A4 00 DC 01 FE 00 BE 03 FC 00 DC 05 28 00 BE]</li><li>006A_Custom: ByteArray [value=01 E0 00 DC 01 FE 00 DC 03 FC 00 DC 05 28 00 BE]</li><li>006B_Custom: ByteArray [value=01 E0 00 DC 01 FE 00 DC 03 FC 00 DC 05 28 00 BE]</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Oct 03 16:48:55 MSK 2021

Telegram: LLK
Каталог https://v2.sprut.ai/catalog/item/etop-termostat-dla-teplogo-pola-zigbee
Покупал https://jhome.ru/catalog/termostats/248/?oid=255

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/etop-termostat-dla-teplogo-pola-zigbee
