### ISSUE TITLE
реостат SYMFONISK Sound remote выключает лампы при достижении 5% яркости крутилкой

### ISSUE THREAD

**Issue by vova0255** [sprut/Hub#819]
Сделайте пожалуйста, чтобы реостат SYMFONISK Sound remote (https://v2.sprut.ai/catalog/item/ikea-symfonisk-sound-remote) работал в СХ так же как он работает в обычном режиме, а именно в крайнем положении крутили (против часовой стрелки) он останавливался на 5% яркости и не выключал лампы (в данный момент в СХ он останавливается на 5% и тут же выключает лампы). За выключение и включение отвечать у него должна кнопка!!! Почему прошу - он тормозной и момент уменьшения яркости пролетаешь в крайнем положении, да и хочется чтобы работал как работает в обычном режиме - не зря они так сделали же. В обычном режиме - это когда подключаешь его напрямую к лампе Филипс.

**Comment by vova0255** [comment]
Убрал триггер с функции диммера - Включен: стало работать как сам просил выше. Однако отсутствует реакция на триггер по одиночному нажатию Программируемой Кнопки - как будто эта функция неактивна. Складывается впечатление что одиночное нажатие  - это функция диммера - Включен. Долгое нажатие также неактивно. Хорошо, что хоть работает двойное нажатие и триггер позволяет включать и выключать лампы. Но тогда нужно убрать автовключение у диммера, потому как его чуток сдвинешь или прикасаешься к реостату и включаются лампы. Пусть уж тогда включаются только по двойному нажатию.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
