### ISSUE TITLE
TRADFRI bulb E14 CWS opal 

### ISSUE THREAD

**Issue by den1ss666** [sprut/Hub#821]
Address: 680AE2FFFEFBFD7A/E7B4<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SHADE)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 19</li><li>0002_StackVersion: 87</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI bulb E14 CWS opal 600lm</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 1.3.013</li></ul></li><li>0300_ColorControl<ul><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 30015</li><li>0004_CurrentY: 26870</li><li>0008_ColorMode: 1</li><li>4001_EnhancedColorMode: 1</li><li>400A_ColorCapabilities: 8</li><li>400B_ColorTemperatureMin: 250</li><li>400C_ColorTemperatureMax: </li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 9</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0000_NumberOfResets: 0</li><li>0100_MACRxBcast: 0</li><li>0101_MACTxBcast: 0</li><li>0106_APSRxBcast: 0</li><li>0107_APSTxBcast: 0</li><li>011C_LastMessageLQI: 132</li><li>011D_LastMessageRSSI: -67</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>000F_Options: 0</li><li>0010_OnOffTransitionTime: 5</li><li>0011_OnLevel: 255</li><li>4000_StartUpCurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0020_PollControl<ul></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 318846322</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4476</li><li>0008_ImageTypeID: 10241</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Oct 12 23:02:24 MSK 2021

Capabilities: | [FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]
-- | --
Currect Source: | MAINS
Device Version: | 2
Last Update: | Oct 12, 2021 11:02:24 PM
Manufacturer Code: | 4476
Power Level: | FULL
Power Mode: | RECEIVER_ON_IDLE
Stack: | 0
Type: | Router
firmware: | 1.3.013
manufacturerId: | IKEA of Sweden
modelId: | TRADFRI bulb E14 CWS opal 600lm

Порядок подключения стандартный для IKEA TRÅDFRI ТРОДФРИ
https://www.ikea.com/ru/ru/p/tradfri-trodfri-svetodiod-e14-600-lm-besprovodnoe-regulirovanie-cvetnoy-i-belyy-spektr-sharovidnyy-molochnyy-10411572/

Teлеграмм @densh

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/ikea-tradfri-bulb-e14-cws-opal

**Comment by maximusLampreht** [comment]
Очень жду эту лампочку в СХ 🙏
