### ISSUE TITLE
rgb в YLLD01YL

### ISSUE THREAD

**Issue by pabl33** [sprut/Hub#829]
5941
homebridge,обратный homekit.
у торшера https://v2.sprut.ai/catalog/item/yeelight-star-floor-lamp через сх не доступны все цвета rgb.
если добавить этот же мост не в сх,а в хк-всё нормально,цвета меняются.
![F2554F13-5C2E-459B-A2A5-36FBD9303B7F](https://user-images.githubusercontent.com/48541799/138228966-0276eb4a-3e2a-4cc6-b71d-ba14ca6d6a34.png)
после управления торшером через веб сх(смена яркости,цветовой температуры,rgb) лампа уходит оффлайн в хк,в сх работает,но меняется только яркость;для восстановления работы нужно перезагрузить лампу и homebridge.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
