### ISSUE TITLE
WB-MDM3

### ISSUE THREAD

**Issue by voynovia** [sprut/Hub#833]
Поиском не находятся устройства mdm3G26.
при этом скриптом:

`for i in {1..247}; do echo -n "$i - "; D=`modbus_client -mrtu /dev/ttyRS485-1 --debug -b9600 -pnone -s2 -a$i -t3 -o100 -r200 -c6 2>/dev/null | grep Data: | awk 'gsub("Data:","")' | sed -e 's/0x00/\\\x/g' -e 's/\s//g'`; echo -e $D; done`

они видятся, ну и в WirenBoard все хорошо.

старый mdm3 работает без проблем

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
