### ISSUE TITLE
TS0502B

### ISSUE THREAD

**Issue by AlexAl77** [sprut/Hub#837]
Address: A4C138CEA983D304/9F89<br><br><b>Structure</b><br><ul><li>Endpoint 1 (COLOR_TEMPERATURE_LIGHT)<ul><li>Input<ul><li>EF00_ManufacturerSpecific<ul><li>0051_Custom: -50</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 82</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3210_avanjket</li><li>0005_ModelIdentifier: TS0502B</li><li>0007_PowerSource: 1</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 148</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>000F_Options: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 82</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Thu Oct 28 17:02:50 UTC 2021

Трековый светильник 
Покупал тут https://clck.ru/YVweU
@ nikulinalex77
Нажал поиск устройств на свестке в WB

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/sunmeiyi-floodight-10w

**Comment by AlexAl77** [comment]
Добрый день, пока не удалось устройство добавить?

**Comment by AlexAl77** [comment]
Лампочка поддерживает и теплоту свечения.

**Comment by AlexAl77** [comment]
Олег, может какая дополнительная инфа нужна ? Когда ожидать добавление устройства ?

**Comment by AlexAl77** [comment]
Что нужно небходимо, что бы добавить это устройство?

**Comment by alexey-gamov** [comment]
https://github.com/alexey-gamov/wirenboard/blob/main/templates/sprut-zigbee/sunmeiyi-ts0502b.json
