### ISSUE TITLE
Неправильный статус устройства Aqara curtain ZNCLDJ11LM в HomeKit

### ISSUE THREAD

**Issue by absentrv** [sprut/Hub#839]
При открытии/закрытии шторы с использованием беспроводной кнопки Aqara (настроен триггер в СХ) в ХК зависает статус "Открытие"

1. Добавил привод в СХ
2. Добавил беспроводную кнопку в СХ.
3. Создал триггер: на одиночный клик клик => Установить значение "Закрыто" + Обратное значение "Открыто"
4. Клик на кнопку - штора открывается полностью но в ХК статус устройства остается "Закрытие" (Открытие)

** Ожидаемое поведение **
После открытия/закрытия шторы корректный статус в ХК (Открыто/Закрыто)

![image](https://user-images.githubusercontent.com/9679662/139392586-32f4ddff-2aca-46df-86ce-24d323757bbe.png)
![image](https://user-images.githubusercontent.com/9679662/139392625-1163d4ef-4505-4488-87a5-50c50fdf08bd.png)

Ревизия: 5952

**Comment by sprut666666** [comment]
проверить на актуальной сборке
