### ISSUE TITLE
Aqara wireless dimmer ZNXNKG02LM, Номер по каталогу Sprut 3570

### ISSUE THREAD

**Issue by Doublenik8** [sprut/Hub#840]
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff">Address: 54EF44100006EC4A/7763</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff"><b>Structure</b></span></p>
<ul style="list-style-type: disc">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">Endpoint 1 (ON_OFF_LIGHT_SWITCH)</span></li>
<ul style="list-style-type: circle">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">Input</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0000_Basic</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0000_ZCLVersion: 3</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0001_ApplicationVersion: 20</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0002_StackVersion: 2</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0003_HWVersion: 1</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0004_ManufacturerName: LUMI</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0005_ModelIdentifier: lumi.remote.rkba01</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0007_PowerSource: 3</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">4000_SWBuildID: 2019</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">FFF0_Setup (115F): ByteArray [value=]</span></li>
</ul>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">FCC0_ManufacturerSpecific</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0007_CustomXiaomi (115F): ByteArray [value=00 00 00 00 17 B2 37 C7]</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0008_CustomXiaomi (115F): ByteArray [value=00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0009_Mode (115F): 0</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">00F6_CustomXiaomi (115F): 3300</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">00F7_ExtInfo (115F): {1=3229, 3=25, 4=5032, 5=37, 6=1, 8=276, 10=24746, 12=1}</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">00FC_CustomXiaomi (115F): false</span></li>
</ul>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0001_PowerConfiguration</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0020_BatteryVoltage: 32</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0031_BatterySize: 7</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">003E_BatteryAlarmState: 0</span></li>
</ul>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0012_MultistateInputBasic</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0055_PresentValue: 2</span></li>
</ul>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0003_Identify</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0000_IdentifyTime: 0</span></li>
</ul>
</ul>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">Output</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0003_Identify</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0006_OnOff</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0019_OtaUpgrade</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0000_UpgradeServerID: 0000000000000000</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0002_CurrentFileVersion: 20</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0006_ImageUpgradeStatus: 0</span></li>
</ul>
</ul>
</ul>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">Endpoint 71 (ON_OFF_SWITCH)</span></li>
<ul style="list-style-type: circle">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">Input</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">FCC0_ManufacturerSpecific</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">022C_Custom: 500</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">022E_Custom: -12.0</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0230_Custom: 0.0</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0231_Custom: 200</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0232_Custom: 0.0</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0233_Custom: -3.3333332538604736</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0238_Custom: 12</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">023A_Custom: 3</span></li>
</ul>
</ul>
</ul>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">Endpoint 72 (ON_OFF_SWITCH)</span></li>
<ul style="list-style-type: circle">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">Input</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">FCC0_ManufacturerSpecific</span></li>
<ul style="list-style-type: square">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">022C_Custom: 500</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">022E_Custom: -12.0</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0230_Custom: 0.0</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0231_Custom: 500</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0232_Custom: 0.0</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0233_Custom: -3.3333332538604736</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">0238_Custom: 12</span></li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="background-color: #ffffff"></span><span style="font-kerning: none; background-color: #ffffff">023A_Custom: 131</span></li>
</ul>
</ul>
</ul>
</ul>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff"><b>Binding table</b></span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff"><b>Group membership</b></span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff"><b>Associated devices</b></span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff"><b>Neighbor table</b></span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff"><b>Routing table</b></span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87)"><span style="font-kerning: none; background-color: #ffffff"><b>Node Descriptor</b></span></p>

Aps Flags | 0
-- | --
Frequency Bands | [FREQ_2400_MHZ]
Server Capabilities | []
Buffer Size | 127
Incoming Transfer Size | 100
Logical Type | End Device
Mac Capabilities | [REDUCED_FUNCTION_DEVICE, MAINS_POWER]
Manufacturer Code | 4447
Out Going Transfer Size | 100
Stack Compliance | 22

<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); min-height: 19.0px"><span style="font-kerning: none"></span><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Helvetica; color: #000000; color: rgba(0, 0, 0, 0.87); background-color: #ffffff"><span style="font-kerning: none">Last update: Fri Oct 29 01:57:14 MSK 2021</span></p>

**Comment by Doublenik8** [comment]
https://v2.sprut.ai/catalog/item/aqara-dimmer-h1-besprovodnoj

Покупал здесь: https://aliexpress.ru/item/1005003153258697.html?spm=a2g39.orderlist.0.0.d8f84aa6a4vAae&_ga=2.133416454.982764140.1635546103-943092114.1634131668

Внимание: этот магазин работает только вечером/ночью (по Москве)

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/aqara-dimmer-h1-besprovodnoj
