### ISSUE TITLE
Danalock v3 BTZBE

### ISSUE THREAD

**Issue by stas3133283** [sprut/Hub#841]
Address: 588E81FFFE43D383/5491

Structure
	•	Endpoint 1 (DOOR_LOCK)
	◦	Input
	▪	0000_Basic
	▪	0000_ZCLVersion: 3
	▪	0001_ApplicationVersion: 3
	▪	0003_HWVersion: 5
	▪	0004_ManufacturerName: Danalock
	▪	0005_ModelIdentifier: V3-BTZBE
	▪	0006_DateCode: 20210428
	▪	0007_PowerSource: 3
	▪	0020_PollControl
	▪	0000_CheckinInterval: 14400
	▪	0001_LongPollInterval: 20
	▪	0002_ShortPollInterval: 2
	▪	0003_FastPollTimeout: 40
	▪	0001_PowerConfiguration
	▪	0021_BatteryPercentageRemaining: 178
	▪	0035_BatteryAlarmMask: 255
	▪	003E_BatteryAlarmState: 0
	▪	0101_DoorLock
	▪	0000_LockState: 1
	▪	0001_LockType: 0
	▪	0002_ActuatorEnabled: false
	▪	0010_NumLockRecordsSupported: 0
	▪	0011_NumTotalUsersSupported: 20
	▪	0012_NumPINUsersSupported: 20
	▪	0013_NumRFIDUsersSupported: 0
	▪	0014_NumWeekdaySchedulesSupportedPerUser: 0
	▪	0015_NumYeardaySchedulesSupportedPerUser: 0
	▪	0016_NumHolidaySchedulesSupportedPerUser: 0
	▪	0017_MaxPINLength: 11
	▪	0018_MinPINLength: 4
	▪	0030_WrongCodeEntryLimit: 5
	▪	0031_UserCodeTemporaryDisableTime: 120
	▪	0032_SendPINOverTheAir: true
	▪	0033_RequirePINForRFOperation: false
	▪	0034_ZigBeeSecurityLevel: 0
	▪	0040_AlarmMask: 65535
	▪	0041_KeypadOperationEventMask: 65535
	▪	0042_RFOperationEventMask: 65535
	▪	0043_ManualOperationEventMask: 65535
	▪	0003_Identify
	▪	0000_IdentifyTime: 178
	▪	0B05_Diagnostics
	▪	0000_NumberOfResets: 10
	▪	011C_LastMessageLQI: 236
	▪	011D_LastMessageRSSI: -41
	▪	0009_Alarms
	▪	0000_AlarmCount: 0
	▪	FCFF_ManufacturerSpecific
	▪	
	◦	Output
	▪	0019_OtaUpgrade
	▪	0000_UpgradeServerID: FFFFFFFFFFFFFFFF
	▪	0001_FileOffset: -1
	▪	0002_CurrentFileVersion: 285212692
	▪	0003_CurrentZigBeeStackVersion: 2
	▪	0004_DownloadedFileVersion: -1
	▪	0005_DownloadedZigBeeStackVersion: 65535
	▪	0006_ImageUpgradeStatus: 0
	▪	0007_ManufacturerID: 4444
	▪	0008_ImageTypeID: 65535
	▪	0009_MinimumBlockRequestPeriod: 0
	▪	000A_ImageStamp:

Binding table

Group membership

Associated devices

Neighbor table

Routing table

Node Descriptor
Aps Flags
0
Frequency Bands
[FREQ_2400_MHZ]
Server Capabilities
[]
Buffer Size
82
Incoming Transfer Size
82
Logical Type
End Device
Mac Capabilities
[REDUCED_FUNCTION_DEVICE]
Manufacturer Code
4444
Out Going Transfer Size
82
Stack Compliance
22

Power Descriptor
Current Power Mode
RECEIVER_ON_PERIODICALLY
Available Power Sources
[DISPOSABLE_BATTERY]
Current Power Source
DISPOSABLE_BATTERY
Power Level
FULL

Last update: Fri Oct 29 10:17:18 MSK 2021

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/danalock-v3-smart-lock-zigbee

**Comment by andreypopov** [comment]
Очень надо, давайте сделаем,:)

**Comment by andreypopov** [comment]
Пробую сделать шаблон - пока не работает:

`{
    "manufacturer": "Danalock",
    "model": "V3-BTZBE",
    "manufacturerId": "Danalock",
    "modelId": "V3-BTZBE",
    "catalogId": 145,
    "status": "Done",
    "services": [
        {
            "type": "LockMechanism",
            "characteristics": [
                {
                    "type": "LockCurrentState",
                    "link": {
                        "endpoint": 1,
                        "cluster": "0101_DoorLock",
                        "attribute": "0000_LockState",
                        "map": {
                            "UNSECURED": "0",
                            "SECURED": "1",
                            "JAMMED": "2",
                            "UNKNOWN": "3"
                        }
                    }
                },
                {
                    "type": "LockTargetState",
                    "link": {
                        "endpoint": 1,
                        "cluster": "0101_DoorLock",
                        "attribute": "0000_LockState",
                        "map": {
                            "UNSECURED": "0",
                            "SECURED": "1"
                        }
                    }
                }
            ]
        }
    ]
}
`

**Comment by andreypopov** [comment]
ихууу ?) праздник на нашей улице
