### ISSUE TITLE
Значения датчика WB-MSW v3(влажность) в ВБ отличаются от значения в СХ

### ISSUE THREAD

**Issue by absentrv** [sprut/Hub#842]
Показания датчика WB-MSW (modbus) влажность в web-интерфейсе WB отличаются от значения в СХ на 5%. (в СХ  > 5% чем в WB). По ощущениях и по сравнению с другим датчиком влажности, СХ явно завышает показания.

** Как воспроизвести ? **
1. Подключил датчик на шину rs-485.
2. Настроил в веб-интерфейсе ВБ.
3. Отключил шину в ВБ
4. Создал modbus контроллер в СХ - msw добавился.
5. Посмотрел значение влажности в СХ (сделал скриншот)
6. Отключил модбас контроллер
7. Подключил шину на которой датчик в ВБ.
8. Сделал скриншот показаний.

** Ожидаемое поведение **
Значение датчика в СХ == Значению датчика в ВБ

Ревизия: 5952
Дата сборки: 23.10.2021, 20:22:29

![image](https://user-images.githubusercontent.com/9679662/139526619-82583d12-d21a-4272-b243-5a0d9b4f1a46.png)
![image](https://user-images.githubusercontent.com/9679662/139526624-07207d22-a82c-4941-a488-18e91ca290a8.png)

**Comment by andreypopov** [comment]
Нужно уменьшить шаг до 1, зачем округление к шагу 5

![2021-11-01_12-51-09](https://user-images.githubusercontent.com/1624839/139654014-f0644948-a9cc-436c-bb7b-af5b0562b48c.png)

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
