### ISSUE TITLE
Шторы: неправильный текст  "калибровка сборос"

### ISSUE THREAD

**Issue by andreypopov** [sprut/Hub#846]
![2021-11-05_11-19-59](https://user-images.githubusercontent.com/1624839/140488785-0dbc04cc-7825-4e39-936a-20563be113cf.png)

Нелогичное поведение кнопок "Сбросить" и "Калибровка сборос"
сброс калибровки работал только после "Сброс"

**Comment by MakeSimpleOrg** [comment]
Текст поправил, а вот поведение кнопки похоже на более серьезный баг, возможно со всеми похожими кнопками.
