### ISSUE TITLE
GL-C-007P

### ISSUE THREAD

**Issue by tsodya** [sprut/Hub#849]
Address: 84FD27FFFEC8A025/4492<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11 (EXTENDED_COLOR_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 0</li><li>0003_HWVersion: 3</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-C-007P</li><li>0007_PowerSource: 0</li><li>4000_SWBuildID: V_1_7_H2</li></ul></li><li>0300_ColorControl<ul><li>0003_CurrentX: 17623</li><li>0004_CurrentY: 43739</li><li>0007_ColorTemperature: 250</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4687</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Nov 08 20:30:49 MSK 2021

Telegram: @iltso

Покупал с Авито (видать перепутал с GL-C-007)

Сбросил шестикратной подачей и отключением питания, после чего Sprut.Hub его нашел.
Воспользовался шаблоном от GL-C-007, подменив имя и все упоминания мдедли в шаблоне. Вроде работает, но все равно в логах бардак

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/gledopto-rgbw-led-controller-2
