### ISSUE TITLE
Некорректная работа MDM3 c кнопочными выключтелями

### ISSUE THREAD

**Issue by kutovoys** [sprut/Hub#85]
** Подробное описание ошибки **
При выключении света с выключателя - статус в СХ не меняется. 
ПРимер:
Свет включен с выключателя. СХ видит это и у него статус включен и выставлена текущая яркость. Но при управлении диммером с помощью двухкнопочного(и однокнопочного тоже) режима, при включении и выключении света Вайрен не трогает его яркость. Записывая только в топик канала switch 0 или 1. Поэтому при следующем включении света с выключателя будет включатся та же яркость. Так бы было если бы не было СХ. 
Спрутхаб управляет диммером только с помощью одного топика - топика яркости. Тем самым при выключении СХ выставляет яркость в 0. Тем самым ломая логику вайрена по сохранению яркости. И при следующем включении с выключателя Вайрен включает свет на минималку. потому что у него в топике яркости до этого стояло 0(От спрутхаба)

** Как воспроизвести ? **
1. Включить свет любым способом.
2. Зайти в СХ и следить за статусом данного аксессуара.
3. Выключить свет с кнопки.
4. Статус в СХ не меняется так как яркость канала не изменилась, канал просто выключили.

** Ожидаемое поведение **
Включение света путем записи coil регистра switch (0/1) в топик вайрена. А не изменение яркости в 0.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия СХ - 1.4.6b
  - Контроллер Wirenboard

** Дополнительные материалы **
Возможное решение:
Управлять включением и выключением света не яркостью а выключателем. Не изменять яркость при выключении канала.

**Comment by sprut666666** [comment]
1.6.4 (Требуется удаление аксессуара)
