### ISSUE TITLE
haozee Умный термостат Tuya ZigBee после выключения питания встает в режим нагрева

### ISSUE THREAD

**Issue by bazhenov-sv** [sprut/Hub#852]
haozee Умный термостат Tuya ZigBee https://v2.sprut.ai/catalog/item/haozee-umnyj-termostat-tuya-zigbee после выключения питания сети встает в режим нагрева, хотя до выключения писания термостат был выключен.

**Comment by bazhenov-sv** [comment]
![2021-11-10_20-59-30](https://user-images.githubusercontent.com/90479528/141147842-5ec6e465-e637-4942-b644-56553a53e6ee.png)

в дополнении термостат висит в статусе удаленный, хотя управление работает.

**Comment by vova0255** [comment]
У меня также, но не термостат встает в режим нагрева, а иконка в ХК, сам термостат физически в статусе в каком был оставлен - в данном случае выключен с сенсорной кнопки выкл. Параметр A4 инструкции сам термостат выполняет.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
