### ISSUE TITLE
ZB-CL01

### ISSUE THREAD

**Issue by Dmitriy-Krylov** [sprut/Hub#853]
Ознакомиться с Address: 00124B002450A1C3/EB15<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 15</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: eWeLight</li><li>0005_ModelIdentifier: ZB-CL01</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 1.0.13</li></ul></li><li>0300_ColorControl<ul><li>0003_CurrentX: 21148</li><li>0004_CurrentY: 21561</li><li>0007_ColorTemperature: 319</li><li>400B_ColorTemperatureMin: 153</li><li>400C_ColorTemperatureMax: 370</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE417570</td><td>0000</td><td>Coordinator</td><td>true</td><td>Parent</td><td>11</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00124B002450A1DF</td><td>1BC9</td><td>Router</td><td>true</td><td>Unknown</td><td>35</td><td>UNKNOWN</td><td>255</td></tr><tr><td>CC86ECFFFEE9B5B9</td><td>10CB</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>0000000000000000</td><td>4E94</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr><tr><td>B4E3F9FFFE22AEFC</td><td>D3B6</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>1BC9</td></tr><tr><td>ACTIVE</td><td>1BC9</td><td>1BC9</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Nov 12 10:40:54 MSK 2021: https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

https://aliexpress.ru/item/1005002035316188.html?spm=a2g39.orderlist.0.0.7ae84aa623WpZl&_ga=2.152197232.875939024.1636363767-1828192186.1635951895

https://t.me/D9310002099

Лампочка Версия Zigbee

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/oobest-smart-light-35-inch-rgbcw
