### ISSUE TITLE
Неверные значения TargetTemperature (Целевая температура) в Спрутхабе.

### ISSUE THREAD

**Issue by stealth4Panda** [sprut/Hub#856]
Спрут установлен на Wirenboard6
Ревизия: 5952
Дата сборки: 23.10.2021, 20:22:29
В Wirenboard были созданы виртуальные термостаты. С некоторых пор значения термостата TargetTemperature (Целевая Температура) в Спрутхабе и Wirenboard отличаются. В MQTT брокере значения совпадают со значениями WB.

Связь спрута и топика MQTT
![Без имени-1](https://user-images.githubusercontent.com/94301203/141684992-ec7a4147-217a-45f1-b11e-b468577323e0.jpg)

Сравнение значений MQTT, Wirenboard, Spruthub
![Без имени-2](https://user-images.githubusercontent.com/94301203/141685003-8ad14047-2ccb-4eb9-b37c-aac876f291b8.jpg)

Кастомный теплейт для термостата
[Thermostat.txt](https://github.com/sprut/Hub/files/7533920/Thermostat.txt)

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
