### ISSUE TITLE
Не добавляется реле MR6C v.2. через Modbus

### ISSUE THREAD

**Issue by bazhenov-sv** [sprut/Hub#858]
** Подробное описание ошибки **

Не добавляется реле MR6C v.2. через Modbus более свежие версии. Версии реле купленные год назад добавляются успешно.
Контроллер их попросту не видит.

** Ожидаемое поведение **
Должны добавляться.

**Comment by bazhenov-sv** [comment]
WB-MDM3 тоже самое.

**Comment by sprut666666** [comment]
прошу отписать в чат поддержки
