### ISSUE TITLE
TS0003

### ISSUE THREAD

**Issue by Yuriy-Shults** [sprut/Hub#859]
Address: A4C138F790B8D1FC/5FD1<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul><li>D001_Custom: ByteArray [value=00 06]</li><li>D002_Custom: ByteArray [value=00 0A]</li><li>D003_Custom: AAAAAgAABAAA</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 67</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_odzoiovu</li><li>0005_ModelIdentifier: TS0003</li><li>0007_PowerSource: 1</li></ul></li><li>E001_ManufacturerSpecific<ul><li>D030_Custom: 0</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 1</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 67</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E001_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 3 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E001_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>00158D000419C504</td><td>7125</td><td>Router</td><td>false</td><td>Parent</td><td>136</td><td>UNKNOWN</td><td>1</td></tr><tr><td>60A423FFFE4155D7</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>100</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D00042AC0C6</td><td>D8D8</td><td>Router</td><td>false</td><td>Sibling</td><td>112</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D0002247A4C</td><td>6B42</td><td>Router</td><td>false</td><td>Sibling</td><td>42</td><td>UNKNOWN</td><td>0</td></tr><tr><td>84FD27FFFED7B6CF</td><td>3528</td><td>Router</td><td>false</td><td>Sibling</td><td>88</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D000428B1D1</td><td>6EB1</td><td>Router</td><td>false</td><td>Sibling</td><td>106</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D0002FC16A1</td><td>4CAA</td><td>Router</td><td>false</td><td>Sibling</td><td>88</td><td>UNKNOWN</td><td>0</td></tr><tr><td>84FD27FFFED25543</td><td>0C9E</td><td>Router</td><td>false</td><td>Sibling</td><td>45</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Nov 20 01:06:45 MSK 2021
Покупал по ссылке в каталоге https://v2.sprut.ai/catalog/newest?sort=-created_at&page=2&search=%D0%A2%D1%80%D0%B5%D1%85%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9
https://a.aliexpress.com/_APNBl4
ПОслЕ СПарИВАниЯ Не раБоТАеТ, ПиШЕТ- НеТ ШАбЛонА

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tuya-zigbee-with-neutral-3gang
