### ISSUE TITLE
Не корректная работа DDM845R в приложении дом на ihpone 

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#86]
** Подробное описание ошибки **
При управлении светом через iphone при включении света происходит уменьшение яркости на 1 процент. Если яркость была установлена на 50% через телефон выключить свет. а потом включить то яркость установиться на 49%
Если изначально яркость была установлена на 100% процентов то следующее включение происходит нормально на 100% .

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Установить яркость канала 99 или меньше % любым способом
2. На телефоне выключить свет
3. Включить свет, яркость будет установлена ну 98%
4. Смотрите ошибку

** Ожидаемое поведение **
При выключении с телефона и включении яркость должна устанавливаться на исходное значение как при выключении 99%

** Скриншоты/ Логи **
10:41:57 | publish: 83.10.13/Brightness/92 to 1 clients | Homekit.e |  
10:41:55 | publish: 83.10.13/Brightness/93 to 1 clients | Homekit.e |  
10:41:53 | publish: 83.10.13/Brightness/94 to 1 clients | Homekit.e |  
10:41:51 | publish: 83.10.13/Brightness/95 to 1 clients | Homekit.e |  
10:41:49 | publish: 83.10.13/Brightness/96 to 1 clients | Homekit.e |  
10:41:47 | publish: 83.10.13/Brightness/97 to 1 clients | Homekit.e |  
10:41:45 | publish: 83.10.13/Brightness/98 to 1 clients | Homekit.e |  
10:41:32 | publish: 83.10.13/Brightness/98 to 1 clients | Homekit.e

** Пожалуйста, заполните следующую информацию: **
  - Версия: [SH 1.4.6b]

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by diamond5170** [comment]
С каким контроллером это проверялось?

**Comment by droni4** [comment]
> С каким контроллером это проверялось? И актуальная версия 1.5, нужно еще раз проверить на ней.
