### ISSUE TITLE
RDM001

### ISSUE THREAD

**Issue by kazadbaruk** [sprut/Hub#862]
Address: 001788010B0070E2/033A<br><br><b>Structure</b><br><ul><li>Endpoint 1 (NON_COLOR_CONTROLLER)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 2</li><li>0001_ApplicationVersion: 9</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 3</li><li>0004_ManufacturerName: Signify Netherlands B.V.</li><li>0005_ModelIdentifier: RDM001</li><li>0006_DateCode: 20210115</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 1.0.3</li></ul></li><li>FC00_ManufacturerSpecific<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 30</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0004_Groups<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 1030</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Nov 23 16:03:07 MSK 2021
[logs.zip](https://github.com/sprut/Hub/files/7588167/logs.zip)
Спаривание: Долгое нажатие кнопки reset примерно 15 секунд до одиночного мигания красного светодиода, потом либо передернуть клавишу выключателя либо коротко нажать reset, красный светодиод должен начать мигать.
Поддерживает:
 - режим on-off.
 - одиночное, двойное, тройное нажатие
https://v2.sprut.ai/catalog/item/philips-hue-wall-switch-module
У моего другое ID и он не роутер а конечное устройство, возможно это другое устройство или в каталоге ошибка, хотя название такое-же.
Покупал тут:
https://chodo.ru/catalog/komplekt_umnyh_vyklyuchatelej_philips_hue_wall_switch_module_2-pack_929003017102/
@kazad

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/philips-hue-wall-switch-module
