### ISSUE TITLE
TS0601

### ISSUE THREAD

**Issue by Vorchikhin** [sprut/Hub#864]
Address: 540F57FFFE97589A/1752<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>EF00_ManufacturerSpecific<ul><li>0002_Custom: 364</li><li>0012_Custom: 248</li><li>0013_Custom: 488</li><li>0015_Custom: 13</li><li>0016_Custom: 3</li></ul></li><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 68</li><li>0002_StackVersion: 0</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZE200_yvx5lh6k</li><li>0005_ModelIdentifier: TS0601</li><li>0006_DateCode: </li><li>0007_PowerSource: 1</li><li>FFDF_Custom: </li><li>FFE2_Custom: 31</li><li>FFE4_Custom: 0</li><li>FFFE_Custom: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE417487</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>218</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D0005210340</td><td>08E7</td><td>Router</td><td>false</td><td>Sibling</td><td>223</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0006D2F7E9</td><td>30B7</td><td>Router</td><td>false</td><td>Sibling</td><td>162</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00028CC639</td><td>492C</td><td>Router</td><td>false</td><td>Sibling</td><td>200</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00017188FE</td><td>5D73</td><td>Router</td><td>false</td><td>Sibling</td><td>112</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0001E858D0</td><td>6306</td><td>Router</td><td>false</td><td>Sibling</td><td>183</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0001A49E2B</td><td>635A</td><td>Router</td><td>false</td><td>Sibling</td><td>193</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D00045F0F80</td><td>7031</td><td>Router</td><td>false</td><td>Sibling</td><td>138</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0006D2F6F5</td><td>7107</td><td>Router</td><td>false</td><td>Sibling</td><td>219</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0001A49D10</td><td>AF5E</td><td>Router</td><td>false</td><td>Sibling</td><td>231</td><td>UNKNOWN</td><td>15</td></tr><tr><td>50325FFFFE418100</td><td>EAFA</td><td>Router</td><td>false</td><td>Parent</td><td>198</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D000520F12B</td><td>EE65</td><td>Router</td><td>false</td><td>Sibling</td><td>172</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0006D3B32F</td><td>F205</td><td>Router</td><td>false</td><td>Sibling</td><td>185</td><td>UNKNOWN</td><td>15</td></tr><tr><td>00158D0006D32A2F</td><td>F401</td><td>Router</td><td>false</td><td>Sibling</td><td>164</td><td>UNKNOWN</td><td>15</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4098</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Nov 24 16:18:49 EET 2021

**Comment by Vorchikhin** [comment]
Нет родного хаба
Подключал через поиск к Sprut.stick ZigBee 2 Pro 
https://v2.sprut.ai/catalog/item/tuya-smart-air-box
@aiex82

Тип датчика: Углекислый газ (CO2)ТемператураВлажностьVOCФормальдегид газ CH2O
Версия Zigbee 3.0
Режим спаривания, сброса: Кнопка сброс 5 секунд до моргания
Источник питания: От сети microUSB

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/tuya-smart-air-box

**Comment by Vorchikhin** [comment]
Что делать с этой ссылкой?

**Comment by Vorchikhin** [comment]
> https://v2.sprut.ai/catalog/item/tuya-smart-air-box

**Comment by Batyushin** [comment]
дубль https://github.com/sprut/Hub/issues/834
