### ISSUE TITLE
Не работает замок Danalock V3-BTZB (Zigbee). Добавился без шаблона.

### ISSUE THREAD

**Issue by elukyan** [sprut/Hub#866]
Добрый день! 

После получения информации, что замок Danalock V3 Zigbee добавлен в список поддерживаемых, я попробовал добавить его в SprutHub. Замок добавился, но в режиме ограниченной функциональности. Шаблон насколько вижу отсутствует.
Что можно сделать?

Лог с добавлением замка:

18:08:56	000B57FFFE59D011/8097: Обновление не требуется	
18:08:55	Device loaded 'V3-BTZB', manufacturer 'Danalock', firmware '1', ZigBeeNode 8097/000B57FFFE59D011, init=Нет шаблона, sleepy=false, loading=false, deleted=false, Type=End Device]	
18:08:55	Поиск завершён	
18:08:54	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:53	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:52	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:51	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:50	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:49	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:48	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:48	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:47	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:46	Unknown message: EzspSendReplyResponse [networkId=0, status=EMBER_SUCCESS]	
18:08:44	000B57FFFE59D011/8097: Информация о модели 50%	
18:08:43	000B57FFFE59D011/8097: Изучение конечных точек 45%, 1 (1/1)	
18:08:43	000B57FFFE59D011/8097: Изучение возможностей 40%	
18:08:42	000B57FFFE59D011/8097: Энергопотребление 30%	
18:08:42	000B57FFFE59D011/8097: Базовая информация 20%	
18:08:39	000B57FFFE59D011/8097: Опрос 10%	
18:08:39	Join node: ZigBeeNode 8097/000B57FFFE59D011, init=Опрос, state=Работает, sleepy=true, loading=true, deleted=false, ota=Неизвестно, Type=Unknown]	
18:08:38	Unknown node 000B57FFFE59D011, frame: ZigBeeApsFrame [sourceAddress=8097/0, destinationAddress=0000/0, profile=0000, cluster=0013, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=3F, payload=85 97 80 11 D0 59 FE FF 57 0B 00 80, lastHopLqi=196, lastHopRssi=-51]	
18:08:38	EzspIncomingSenderEui64Handler [networkId=0, senderEui64=000B57FFFE59D011]	
18:08:38	Node 8097/000B57FFFE59D011 wasn't found in the network	
18:08:38	EzspTrustCenterJoinHandler [networkId=0, newNodeId=8097, newNodeEui64=000B57FFFE59D011, status=EMBER_STANDARD_SECURITY_UNSECURED_JOIN, policyDecision=EMBER_USE_PRECONFIGURED_KEY, parentOfNewNodeId=0000]	
18:08:38	EzspChildJoinHandler [networkId=0, index=1, joining=true, childId=8097, childEui64=000B57FFFE59D011, childType=EMBER_SLEEPY_END_DEVICE]	
18:08:29	Node 8097/000B57FFFE59D011 wasn't found in the network	
18:08:29	EzspTrustCenterJoinHandler [networkId=0, newNodeId=8097, newNodeEui64=000B57FFFE59D011, status=EMBER_STANDARD_SECURITY_UNSECURED_JOIN, policyDecision=EMBER_USE_PRECONFIGURED_KEY, parentOfNewNodeId=0000]	
18:08:29	EzspChildJoinHandler [networkId=0, index=1, joining=true, childId=8097, childEui64=000B57FFFE59D011, childType=EMBER_SLEEPY_END_DEVICE]	
18:08:23	Node 8097/000B57FFFE59D011 wasn't found in the network	
18:08:23	EzspTrustCenterJoinHandler [networkId=0, newNodeId=8097, newNodeEui64=000B57FFFE59D011, status=EMBER_STANDARD_SECURITY_UNSECURED_JOIN, policyDecision=EMBER_USE_PRECONFIGURED_KEY, parentOfNewNodeId=0000]	
18:08:23	EzspChildJoinHandler [networkId=0, index=1, joining=true, childId=8097, childEui64=000B57FFFE59D011, childType=EMBER_SLEEPY_END_DEVICE]	
18:08:12	Поиск запущен на 60 секунд

Как замок сейчас выглядит в SH:

![image](https://user-images.githubusercontent.com/58940876/143773914-ceb37870-69fd-4350-afe6-8116953cbfc0.png)

**Comment by Batyushin** [comment]
В релиз пока не выкладывалась, нужно подождать.
