### ISSUE TITLE
Неверная (странная?) работа с Fibaro FGRGBW442CC RGBW (c белым каналом) в режиме HSB

### ISSUE THREAD

**Issue by dkozickis** [sprut/Hub#87]
**Подробное описание ошибки**
Fibaro FGRGBW442CC RGBW (c белым каналом) в режиме HSB прокинутый через Fibaro Home Center Light странно себя ведет. 

Белый канал выведен как отдельный сервис у аксессуара и невнятно передает команды на HCL. 

**Как воспроизвести ?**
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Открываем аксессуары в Спруте
2. Видим во такой вот акс
![image](https://user-images.githubusercontent.com/769698/78791206-3ba78880-79b8-11ea-8443-6f40efe2db38.png)
3. Крутим Hue, Насыщенность, Яркость - HCL реагирует как предподалагется
4. Крутим отдельно сервис белого канала - показания в HCL скачать туда сюда, и если в HCL крутим белый канал - в Спруте значение не соответсвует.

**Ожидаемое поведение**
Вообще, ожидание, что белый канал будет в одном сервисе с Hue/Saturation, а не вынесен отдельно. И работать будет правильно. Но если надо выносить отдельно - то хоть чтобы работал верно. 

Получается в HCL для белого принимает значения от 0-255, а в Спруте сейчас 0-100 в интерфейсе. Видимо и в беке что-то с логикой.

Спасибо большое!

**Скриншоты/ Логи**
Видео с десктопа записано тут
https://www.youtube.com/watch?v=kvyeVmm-Fy4

**Пожалуйста, заполните следующую информацию:**
  - Версия: Спрут 1.5
  - HCL 4.570

**Comment by diamond5170** [comment]
В одном сервисе быть не может, протокол хомкита не позволяет. Остальное исправлено.
