### ISSUE TITLE
Открытие ворот при перезагрузки спрутхаба

### ISSUE THREAD

**Issue by peefoo** [sprut/Hub#873]
Если создать виртуальное устройство "Гаражные ворота" и назначить его на реле, которое по одному сухому контакту управлять гаражными или въездными воротами (которые будут работать по одному сухому контакту, работающего по принципу кнопки на пульте управления: нажал - ворота поехали, еще раз нажал - остановились, еще раз нажал - поехали в другую сторону), то при перезапуске спрутхаба ворота начинают движение - т.к. ворота проходят процесс инициализации и меняют свое состояние.

** Как воспроизвести ? **
1. к сухому контакту реле подключить управление воротами
2. зайти в аксессуары, создать виртуальное устройство - гаражные ворота.
3. Заходим в триггер целевого положения ворот и на любое действие назначаем включение реле.
4. в настройках реле устанавливаем switchOffDelay на 1000 (отключить через секунду, чтобы сымитировать нажатие на кнопку)
5. переагружаем хаб (программно или аппаратно)
6. при загрузке хаба наблюдаем, как ворота начали движение
** Ожидаемое поведение **
Хотелось бы иметь опцию отключения инициализации ворот в начальное положение. Как и штор.

** Скриншоты/ Логи **
Скриншоты не покажут нужную реакцию ворот

** Пожалуйста, заполните следующую информацию: **
  - ревизия 5952

**Comment by TaranovKursk** [comment]
Огромная дыра в безопасности дома. Проблеме больше года. Обещаниям что-то сделать столько же... Дмитрий вроде нашёл решение, ждём реализации.
