### ISSUE TITLE
прошу добавить HEIMAN Smart Metering Plug

### ISSUE THREAD

**Issue by kachalex** [sprut/Hub#896]
Address: 847127FFFE13B5BB/398E<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 18</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 22</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: SmartPlug-EF-3.0</li><li>0006_DateCode: 2020.9.25</li><li>0007_PowerSource: 1</li></ul></li><li>0702_Metering<ul><li>0000_CurrentSummationDelivered: 0</li><li>0200_Status: 0</li><li>0300_UnitOfMeasure: 0</li><li>0301_Multiplier: 1</li><li>0302_Divisor: 10000</li><li>0303_SummationFormatting: 170</li><li>0304_DemandFormatting: 163</li><li>0400_InstantaneousDemand: 0</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0B04_ElectricalMeasurement<ul><li>0505_RMSVoltage: 22956</li><li>0508_RMSCurrent: 0</li><li>050B_ActivePower: 0</li><li>0600_ACVoltageMultiplier: 1</li><li>0601_ACVoltageDivisor: 100</li><li>0602_ACCurrentMultiplier: 1</li><li>0603_ACCurrentDivisor: 100</li><li>0604_ACPowerMultiplier: 1</li><li>0605_ACPowerDivisor: 10</li><li>0800_ACOverloadAlarmsMask: 7</li><li>0801_ACVoltageOverload: 26500</li><li>0802_ACCurrentOverload: 1600</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0B05_Diagnostics<ul><li>011C_LastMessageLQI: 244</li><li>011D_LastMessageRSSI: -39</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0009_Alarms<ul></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: -1</li><li>0003_CurrentZigBeeStackVersion: 65535</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4619</li><li>0008_ImageTypeID: 16651</li></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Dec 19 16:39:26 IST 2021

![image](https://user-images.githubusercontent.com/42259721/146679069-eed8f43b-d6c8-48c4-b285-8ec3829eba93.png)

Ссылка на девайс:

https://v2.sprut.ai/catalog/item/heiman-smart-metering-plug

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/heiman-smart-metering-plug

**Comment by kachalex** [comment]
Так они добавлены в ревизии 6664 ?
Можно убрать в custom?

чт, 10 февр. 2022 г. в 20:41, ReD ***@***.***>:
