### ISSUE TITLE
прошу добавить HEIMAN Smart Water Leakage Sensor

### ISSUE THREAD

**Issue by kachalex** [sprut/Hub#897]
Address: 847127FFFEAD4182/92D6<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 2</li><li>0001_ApplicationVersion: 21</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 16</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: WaterSensor-EF-3.0</li><li>0006_DateCode: 2019.5.23</li><li>0007_PowerSource: 3</li></ul></li><li>0500_IasZone<ul><li>0000_ZoneState: 0</li><li>0001_ZoneType: 42</li><li>0002_ZoneStatus: 48</li><li>0010_IASCIEAddress: 0000000000000000</li><li>0011_ZoneID: 255</li></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 31</li><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0B05_Diagnostics<ul><li>011C_LastMessageLQI: 224</li><li>011D_LastMessageRSSI: -44</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: -1</li><li>0003_CurrentZigBeeStackVersion: 65535</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4619</li><li>0008_ImageTypeID: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sun Dec 19 17:13:20 IST 2021

![image](https://user-images.githubusercontent.com/42259721/146680332-ff7a1cc2-7cea-4d0a-b726-391780d7ba1f.png)

Ссылка на девайс:
https://v2.sprut.ai/catalog/item/heiman-smart-water-leakage-sensor

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/heiman-smart-water-leakage-sensor

**Comment by kachalex** [comment]
Так вендор другой. 
Можно добавить вендор в шаблоны

בברכה,
 
אלכס קצ'קובסקי
מנהל טכני ורשת מחשבים
נייד: 054-6725004
פקס: 03-5414333
https://www.dibiz.com/alex-32
http://www.beit-zvi.com
