### ISSUE TITLE
WB-MSWv3 неправильный тип переменной для проброса в spruthub

### ISSUE THREAD

**Issue by sincereman** [sprut/Hub#9]
** Подробное описание ошибки **
Wirenboard
![изображение](https://user-images.githubusercontent.com/52529431/60657685-688fa380-9e5a-11e9-9535-25cbf439fed7.png)
Spruthub

![изображение](https://user-images.githubusercontent.com/52529431/60657749-80672780-9e5a-11e9-94ef-f038ddcaf8cd.png)

** Ожидаемое поведение **
Ожидаю увидеть здесь значение (кол-во движения), а не просто есть или нет.

WB 6.5

**Comment by diamond5170** [comment]
Хаб базируется на структуре хомкита. Эта характеристика MotionDetected, она буквально переводится как "Движение обнаружено", и там именно boolean. Других в хомките нет.
Будет лишь пороговое значение в настройках сервиса. Сейчас это 200.

**Comment by andreypopov** [comment]
вот эти бы 200 настройкой сделать, пожалуйста
все датчики по-разному висят и разные пороги у них

**Comment by sprut666666** [comment]
Обновляемся, всё работает.
<img width="424" alt="image" src="https://user-images.githubusercontent.com/24498195/60696061-c53b9e80-9eec-11e9-8762-ef036c07b497.png">
