### ISSUE TITLE
прошу добавить в SH поддержку датчика  WB-MSv2.

### ISSUE THREAD

**Issue by Antonser238** [sprut/Hub#90]
** Максимально подробное описание предложения.**
Четкое и краткое описание предложения, так чтобы вас смог понять "глупый" человек.

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

**Comment by sprut666666** [comment]
Описание недостаточное, куда добавить МКТТ или МодБас ?
Ни топиков? ни лога ? ни идентификаторов
