### ISSUE TITLE
Не показывает состояние заряда батареи Danalock V3 Z-wave

### ISSUE THREAD

**Issue by eag1968** [sprut/Hub#901]
Не показывает состояние заряда батарей замка Danalock V3 Z-WAVE в СХ и HomeKit
После замены батарей состояние заряда не поменялось, лечение не помогло. Хотя в родном приложении показывает полный заряд.

СХ ревизия  5952 установлена на WB
IOS 15.1
стик UZB1 ZWave.Me
![IMG_0449](https://user-images.githubusercontent.com/75105551/147354405-48523d68-9a94-4051-813f-284de8b42ed4.jpeg)
![IMG_0450](https://user-images.githubusercontent.com/75105551/147354417-12fb10e3-5296-459f-824d-e3e56e7b3a97.PNG)
![IMG_0448](https://user-images.githubusercontent.com/75105551/147354425-e2815da7-cbc4-40b2-b019-7dbbe3224764.PNG)

**Comment by decoderst202** [comment]
Такая же беда

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
