### ISSUE TITLE
Remote Control N2

### ISSUE THREAD

**Issue by beezoncheg** [sprut/Hub#911]
Address: 0C4314FFFEDBC42E/D38B<br><br><b>Structure</b><br><ul><li>Endpoint 1 (NON_COLOR_CONTROLLER)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 1</li><li>0002_StackVersion: 103</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: Remote Control N2</li><li>0006_DateCode: 20200708</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 1.0.024</li></ul></li><li>0020_PollControl<ul><li>0000_CheckinInterval: 172800</li><li>0001_LongPollInterval: 1160</li><li>0002_ShortPollInterval: 4</li><li>0003_FastPollTimeout: 40</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0001_PowerConfiguration<ul><li>0020_BatteryVoltage: 0</li><li>0021_BatteryPercentageRemaining: 100</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>FC57_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul></ul></li><li>0005_Scenes<ul></ul></li><li>0006_OnOff<ul></ul></li><li>0008_LevelControl<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 65572</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4476</li><li>0008_ImageTypeID: 4555</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jan 03 04:36:17 MSK 2022

Режим спаривания, сброса: сброс — 4 нажатия на кнопку спаривания в течение 5 сек; спаривание — кнопка спаривания 10 секунд, в спрутхаб залетела по touchlink после сброса (4 нажатия, мерцающий красный индикатор)
Количество клавиш: 4
Источник питания (от батареи, AAA 2шт)

Ссылка на товар https://www.ikea.com/ru/ru/p/styrbar-styurbar-pult-distancionnogo-upravleniya-nerzhaveyushch-stal-30463616/ (IKEA STYRBAR СТЮРБАР)
Ссылка на каталог: отсутствует, добавить не смог
Телеграм @beezoncheg

**Comment by beezoncheg** [comment]
Судя по командам, это вариация круглого пульта [TRADFRI remote control](https://v2.sprut.ai/catalog/item/ikea-besprovodnoj-reostat-2), только без центральной кнопки. Шаблон сделан по ее подобию.
Этот шаблон для версии пульта с металлической крышкой, у белой пластиковой может отличаться название модели.

Disclaimer! Шаблон испольуйте на свой страх и риск!

Нужно закинуть файл в /home/makesimple/.SprutHub/data/Templates/ZigBee/Custom и убрать .txt расширение (гитхаб не дает аттачить json). Когда выйдет нормальный шаблон кастомный нужно будет удалить.
[STYRBAR Remote Control N2.json.txt](https://github.com/sprut/Hub/files/7817152/STYRBAR.Remote.Control.N2.json.txt)

P.S.
Обнаружил, что при длинных нажатиях на стрелки, пульт дополнительно отправляет 0001_OnCommand (одиночное нажатие кнопки включения).


```
[RIGHT]
22:05:05	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=1F, Input, commandIdentifier=9, statusCode=SUCCESS]	
22:05:05	<-- 0009_ChangeRelease [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=1F, Output, data=ByteArray [value=48 02], payload=48:02]	
22:05:03	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=1E, Input, commandIdentifier=8, statusCode=SUCCESS]	
22:05:03	<-- 0008_ChangeHold [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=1E, Output, button=0, data=ByteArray [value=0D 00], payload=00:0D:00]	
22:05:02	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=1D, Input, commandIdentifier=7, statusCode=SUCCESS]	
22:05:02	<-- 0007_ChangePress [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=1D, Output, button=2, data=ByteArray [value=00 00 00], payload=02:00:00:00]	
22:05:01	<-- 0001_OnCommand [0006_OnOff: D38B/1 -> 0000/1, TID=1C, Output]	
22:05:01	--> 000B_DefaultResponse [0006_OnOff: 0000/1 -> D38B/1, TID=1C, Input, commandIdentifier=1, statusCode=SUCCESS]	
22:05:01	<-- 0009_ChangeRelease [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=1B, Output, data=ByteArray [value=00 00], payload=00:00]	
22:05:01	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=1B, Input, commandIdentifier=9, statusCode=SUCCESS]	

[LEFT]
22:04:53	<-- 0009_ChangeRelease [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=1A, Output, data=ByteArray [value=9E 06], payload=9E:06]	
22:04:53	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=1A, Input, commandIdentifier=9, statusCode=SUCCESS]	
22:04:51	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=19, Input, commandIdentifier=8, statusCode=SUCCESS]	
22:04:51	<-- 0008_ChangeHold [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=19, Output, button=1, data=ByteArray [value=0D 00], payload=01:0D:00]	
22:04:50	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=18, Input, commandIdentifier=7, statusCode=SUCCESS]	
22:04:50	<-- 0007_ChangePress [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=18, Output, button=2, data=ByteArray [value=00 00 00], payload=02:00:00:00]	
22:04:50	--> 000B_DefaultResponse [0006_OnOff: 0000/1 -> D38B/1, TID=17, Input, commandIdentifier=1, statusCode=SUCCESS]	
22:04:50	<-- 0001_OnCommand [0006_OnOff: D38B/1 -> 0000/1, TID=17, Output]	
22:04:49	--> 000B_DefaultResponse [0005_Scenes: mc=117C, 0000/1 -> D38B/1, TID=16, Input, commandIdentifier=9, statusCode=SUCCESS]	
22:04:49	<-- 0009_ChangeRelease [0005_Scenes: mc=117C, D38B/1 -> 0000/1, TID=16, Output, data=ByteArray [value=00 00], payload=00:00]
```

**Comment by mSapik** [comment]
Присоединяюсь к просьбе добавить поддержку. Шаблон это хорошо, но в spruthub ce пока нельзя свои пихать.

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/ikea-tradfri-kaukosaadinsetti

**Comment by Batyushin** [comment]
Дубли:
https://github.com/sprut/Hub/issues/1090
https://github.com/sprut/Hub/issues/1483

**Comment by Batyushin** [comment]
https://github.com/sprut/Hub/issues/1612
