### ISSUE TITLE
TS0044

### ISSUE THREAD

**Issue by ghost** [sprut/Hub#922]
Новая версия одного и того же пульта :)

Address: A4C138B9E5FBFCD8/9A65<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 65</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_ee8nrt2l</li><li>0005_ModelIdentifier: TS0044</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 65</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_SWITCH)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 3 (ON_OFF_SWITCH)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li><li>Endpoint 4 (ON_OFF_SWITCH)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li><li>Output<ul><li>0006_OnOff<ul><li>0000_OnOff: false</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Sat Jan 08 16:48:00 MSK 2022

Адрес в каталоге
https://v2.sprut.ai/catalog/item/loratap-tuya-zigbee-30-besprovodnoj-4-knopocnyj-pult

Покупал по ссылке из каталога
https://aliexpress.ru/item/1005002915179764.html?af=3323691_1&cv=40202191&cn=42r5e9b7oxvldx0paeuo0nbuqw3pft7n&dp=v5_42r5e9b7oxvldx0paeuo0nbuqw3pft7n&utm_source=epn&utm_medium=cpa&utm_campaign=3323691_1&utm_content=40202191&product_id=1005002915179764&afref=https%3A%2F%2Fv2.sprut.ai&aff_fcid=445e4adf416d4eb88a7653c90bd2b647-1641650084455-00907-_pIWi2C8&tt=API&aff_fsk=_pIWi2C8&aff_platform=api-new-link-generate&sk=_pIWi2C8&aff_trace_key=445e4adf416d4eb88a7653c90bd2b647-1641650084455-00907-_pIWi2C8&terminal_id=09bea0ca27a141079e3470fe3c90a801

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/loratap-tuya-zigbee-30-besprovodnoj-4-knopocnyj-pult
