### ISSUE TITLE
Не правильный день недели на термостате BHT-002-GBLZB

### ISSUE THREAD

**Issue by Co1dSUN** [sprut/Hub#936]
Время на термостате правильное, но день недели показывает на один меньше.

Спарить термостат с СХ, подождать обновления времени.

День недели должен совпадать с текущим днём.

Добавлю картинку с экраном термостата.

Предполагаю, что началось после нового года. Раньше этого не замечал.

P.S. Хорошо бы было ещё когда-нибудь сделать поддержку настройки расписания для термостата. Пока приходится его настраивать прямо на термостате, но такая возможность точно есть, потому что на родном ТУЯ хабе это можно сделать
![photo_2022-01-12_19-07-13](https://user-images.githubusercontent.com/24419945/149197220-9bb3befc-4101-4f7c-bb7e-6bcd0e93bd93.jpg)
.

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
