### ISSUE TITLE
GLEDOPTO GL-C-008P

### ISSUE THREAD

**Issue by svilpo** [sprut/Hub#939]
Address: A4C138753FB4ED96/5DC0<br><br><b>Structure</b><br><ul><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11 (EXTENDED_COLOR_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 1</li><li>0003_HWVersion: 2</li><li>0004_ManufacturerName: GLEDOPTO</li><li>0005_ModelIdentifier: GL-C-008P</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 10151203</li></ul></li><li>0300_ColorControl<ul><li>0003_CurrentX: 45914</li><li>0004_CurrentY: 19614</li><li>0007_ColorTemperature: 495</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>4000_StartUpCurrentLevel: 255</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 285290497</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4687</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>60A423FFFE41564D</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>112</td><td>UNKNOWN</td><td>0</td></tr><tr><td>847127FFFE0802F0</td><td>30A8</td><td>Router</td><td>false</td><td>Sibling</td><td>155</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4687</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jan 14 21:35:56 EET 2022

Telegram - @svilpo
покупал тут - https://aliexpress.ru/item/1005003690252432.html?gatewayAdapt=glo2rus&srcSns=sns_Telegram&spreadType=socialShare&bizType=ProductDetail&social_params=60130718421&aff_fcid=62ee5192f20548ee8234a356b1b02762-1642189207352-04340-_vPeHfn&tt=MG&aff_fsk=_vPeHfn&aff_platform=default&sk=_vPeHfn&aff_trace_key=62ee5192f20548ee8234a356b1b02762-1642189207352-04340-_vPeHfn&shareId=60130718421&businessType=ProductDetail&platform=AE&terminal_id=0cf98591a2f647198726e77c57c31fe9

P.S запоминает состояние после потери электричества. 
на страницы алиэкспресс и на контролеры указана модель GLC-C-002P.  B SH определяется как GLC-C- 008P.  cопряжение - удерживая кнопку  reset 5 секунд

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/5-in-1-zigbee-mini-ultra-thin-led-controller
