### ISSUE TITLE
Honeywell датчик дыма

### ISSUE THREAD

**Issue by DomikMaksa** [sprut/Hub#94]
Датчик дыма добавился и виден в списке устройств на карте участвует в связи устройств но не появился в хомките после добавления спрутхаба.
![2020-04-19 16 07 13](https://user-images.githubusercontent.com/48162267/79688632-26541900-8258-11ea-800a-ab8e5b14d86a.jpg)
![Снимок экрана 2020-04-19 в 16 05 07](https://user-images.githubusercontent.com/48162267/79688637-2c49fa00-8258-11ea-8eb4-970662d57b4a.png)

**Comment by diamond5170** [comment]
Это не баг, устройство отсутствует в темплейтах.

**Comment by sprut666666** [comment]
https://wiki.sprut.ai/ru/spruthub/setup-sprutstick-sniffer-to-add-new-device

**Comment by sprut666666** [comment]
https://github.com/sprut/Hub/issues/113
