### ISSUE TITLE
TS0601 - Tuya Smart Life ZigBee Garage Door Opener

### ISSUE THREAD

**Issue by stanislavprokopov** [sprut/Hub#940]
Address: A4C138A29AC68558/E43E<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>EF00_ManufacturerSpecific<ul><li>0002_Custom: 0</li><li>0003_Custom: true</li><li>0004_Custom: 10</li><li>0005_Custom: 3600</li><li>000B_Custom: false</li><li>000C_Custom: 2</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 70</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZE200_nklqjk62</li><li>0005_ModelIdentifier: TS0601</li><li>0007_PowerSource: 1</li><li>FFDF_Custom: /</li><li>FFE2_Custom: 54</li><li>FFE4_Custom: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 70</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>001788010119A28E</td><td>2A3B</td><td>Router</td><td>false</td><td>Sibling</td><td>88</td><td>UNKNOWN</td><td>0</td></tr><tr><td>60A423FFFE415571</td><td>0000</td><td>Coordinator</td><td>false</td><td>Sibling</td><td>157</td><td>UNKNOWN</td><td>0</td></tr><tr><td>847127FFFE93165D</td><td>7428</td><td>Router</td><td>false</td><td>Sibling</td><td>33</td><td>UNKNOWN</td><td>0</td></tr><tr><td>842E14FFFE3668F3</td><td>9459</td><td>Router</td><td>false</td><td>Sibling</td><td>12</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jan 14 23:21:30 MSK 2022

Model: PJ-ZGD01
Покупал [тут](https://www.aliexpress.com/item/1005003610757320.html)

<img src="https://ae01.alicdn.com/kf/H98559a899ee64d6b855c704b71742964Q/Tuya-Smart-Life-ZigBee-Garage-Door-Opener-Controller-Timer-App-Monitor-Security-Remote-Control-Supports-Alexa.jpg_Q90.jpg_.webp">

**Comment by stanislavprokopov** [comment]
Лог [2022-01-25_21-36-20.pcap.zip](https://github.com/sprut/Hub/files/7936299/2022-01-25_21-36-20.pcap.zip)

Действия:
```
1. Спарил с родным хабом
2. Зашёл меню управления гаражными воротами. Приложение показывало что ворота открыты.
3. Нажал на кнопку закрыть ворота. Приложение показывало что ворота закрываются.
4. Замкнул геркон. Приложение показало что ворота закрыты.
5. Нажал на кнопку открыть ворота. Приложение показывало что ворота открываются.
6. Раздвинул геркон. Приложение показало что ворота открыты.
```

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/tuya-smart-life-zigbee-garage-door-opener

**Comment by Batyushin** [comment]
Дубль https://github.com/sprut/Hub/issues/1303
