### ISSUE TITLE
 YSRSAI - ModelIdentifier: ZB-CL03

### ISSUE THREAD

**Issue by svilpo** [sprut/Hub#941]
Address: 00124B0022FE1F00/7C1E<br><br><b>Structure</b><br><ul><li>Endpoint 1<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 15</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: YSRSAI</li><li>0005_ModelIdentifier: ZB-CL03</li><li>0006_DateCode: 20210326</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 1.0.13</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 0</li><li>0001_CurrentSaturation: 0</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 21148</li><li>0004_CurrentY: 21561</li><li>0007_ColorTemperature: 203</li><li>0008_ColorMode: 2</li><li>4000_EnhancedCurrentHue: 0</li><li>4001_EnhancedColorMode: 2</li><li>4002_ColorLoopActive: 0</li><li>4003_ColorLoopDirection: 0</li><li>4004_ColorLoopTime: 25</li><li>4005_ColorLoopStartHue: 8960</li><li>4006_ColorLoopStoredHue: 0</li><li>400A_ColorCapabilities: 31</li><li>400B_ColorTemperatureMin: 153</li><li>400C_ColorTemperatureMax: 500</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 65535</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li><li>Endpoint 13<ul><li>Input<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><table border=1 width=100%><tr><th>NWK</th><th>IEEE</th><th>Name</th><th>Type</th></tr><tr><td>B6D0</td><td>04CF8CDF3C77598E</td><td>Lux Virtuve</td><td>End Device</td></tr></table><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>847127FFFE0802F0</td><td>30A8</td><td>Router</td><td>true</td><td>Parent</td><td>102</td><td>UNKNOWN</td><td>1</td></tr><tr><td>04CF8CDF3C77598E</td><td>B6D0</td><td>End Device</td><td>true</td><td>Child</td><td>93</td><td>UNKNOWN</td><td>3</td></tr><tr><td>680AE2FFFE8347FA</td><td>4042</td><td>Router</td><td>true</td><td>Unknown</td><td>32</td><td>UNKNOWN</td><td>255</td></tr><tr><td>14B457FFFE6CA69C</td><td>B408</td><td>Router</td><td>true</td><td>Unknown</td><td>7</td><td>UNKNOWN</td><td>255</td></tr><tr><td>A4C138753FB4ED96</td><td>5DC0</td><td>Router</td><td>true</td><td>Unknown</td><td>107</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00124B001F6A1EF7</td><td>7E91</td><td>Router</td><td>true</td><td>Unknown</td><td>27</td><td>UNKNOWN</td><td>255</td></tr><tr><td>EC1BBDFFFE42D771</td><td>FD51</td><td>Router</td><td>true</td><td>Unknown</td><td>15</td><td>UNKNOWN</td><td>255</td></tr><tr><td>847127FFFE080310</td><td>8BD3</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00158D0003F3EC59</td><td>049C</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>5C0272FFFEEEF185</td><td>9139</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>847127FFFE080300</td><td>63A2</td><td>Router</td><td>true</td><td>Unknown</td><td>16</td><td>UNKNOWN</td><td>255</td></tr><tr><td>60A423FFFE41564D</td><td>0000</td><td>Coordinator</td><td>true</td><td>Unknown</td><td>54</td><td>UNKNOWN</td><td>255</td></tr><tr><td>00124B001CD5FEF5</td><td>F76B</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>14B457FFFE54AF11</td><td>C80A</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>5C0272FFFEBE31C4</td><td>09B5</td><td>Router</td><td>true</td><td>Unknown</td><td>1</td><td>UNKNOWN</td><td>255</td></tr><tr><td>0000000000000000</td><td>3385</td><td>Router</td><td>true</td><td>Unknown</td><td>0</td><td>UNKNOWN</td><td>255</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>FD51</td><td>FD51</td></tr><tr><td>ACTIVE</td><td>0000</td><td>FD51</td></tr><tr><td>DISCOVERY_FAILED</td><td>63A2</td><td>FFFE</td></tr><tr><td>DISCOVERY_FAILED</td><td>9139</td><td>FFFE</td></tr><tr><td>ACTIVE</td><td>108E</td><td>30A8</td></tr><tr><td>ACTIVE</td><td>1F99</td><td>30A8</td></tr><tr><td>ACTIVE</td><td>BDAF</td><td>30A8</td></tr><tr><td>DISCOVERY_FAILED</td><td>996F</td><td>FFFE</td></tr><tr><td>DISCOVERY_FAILED</td><td>945D</td><td>FFFE</td></tr><tr><td>ACTIVE</td><td>76BE</td><td>30A8</td></tr><tr><td>ACTIVE</td><td>049C</td><td>30A8</td></tr><tr><td>ACTIVE</td><td>09B5</td><td>30A8</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>80</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>160</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>0</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>160</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Sat Jan 15 11:54:44 EET 2022

Telegram -  @svilpo
покупал тут - https://www.aliexpress.com/item/1005003213415540.html?spm=a2g0o.9042311.0.0.50624c4dhOyNLE
сопряжение - удерживать 5 секунд кнопку

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/svetodiodnaya-neonovaya-rgb-lenta-zigbee-3-0-12v

**Comment by wire-samara** [comment]
И у меня такой драйвер... Сравнил - все одинаково.
Может временно както шабон подсунуть?

**Comment by svilpo** [comment]
Шаблон есть

сб, 19 февр. 2022 г., 14:27 wire-samara ***@***.***>:

**Comment by wire-samara** [comment]
А как добавить?

**Comment by svilpo** [comment]
Сначала попробуй переспaрить с SH?

сб, 19 февр. 2022 г., 14:32 wire-samara ***@***.***>:

**Comment by wire-samara** [comment]
16:36:56 | Нет шаблона YSRSAI ZB-CL03
16:37:11 | Device loaded 'ZB-CL03', manufacturer 'YSRSAI', firmware '1.0.13', ZigBeeNode 00124B0022ED4C51/5DB4, init=Нет шаблона, sleepy=false, loading=false, removed=false, Type=Router]

**Comment by svilpo** [comment]
sestd., 2022. g. 19. febr., plkst. 14:39 — lietotājs wire-samara (<
***@***.***>) rakstīja:

**Comment by wire-samara** [comment]
> https://sprut.ai/catalog/item/svetodiodnaya-neonovaya-rgb-lenta-zigbee-3-0-12v

Ну есть это в каталоге. Но на коробке YSR-MINI-01 а по факту своя маркировка...
'ZB-CL03', manufacturer 'YSRSAI' 
это именно RGB
и не добавляет в СХ

**Comment by svilpo** [comment]
У меня с этим шаблоном работает  всё. Ko и включить и выключить и менять
цвет и т.п.

сб, 19 февр. 2022 г., 14:50 wire-samara ***@***.***>:

**Comment by wire-samara** [comment]
Так с каким шаблоном работает?
Нашел папку шаблонов...
Там есть
ZB-CL01 и ZB-DL01
Так какой за основу брать?

**Comment by wire-samara** [comment]
"modelId": "ZB-DL01",
  "catalogId": 3044,

или

  "modelId": "ZB-CL01",
  "catalogId": 2646,

а сслыка на ID 3672
но шаблон такой не вижу.

**Comment by svilpo** [comment]
за базу я брал вот этот

sestd., 2022. g. 19. febr., plkst. 19:45 — lietotājs wire-samara (<
***@***.***>) rakstīja:

**Comment by wire-samara** [comment]
В общем сделал копию шаблона ZB-CL01.
Положил в кастом - работает.
Я так понимаю, что "цветовая температура" (ColorTemperature) тут лишняя.
Контролер чисто RGB.
Конечно "цветовая температура" работает, но смысл ее отсутствует.
Можно в шаблоне попробовать ее убрать.
Как есть тоже не мешает и даже пытается регулировать с "использованием того что есть" (в смысле только RGB).

**Comment by svilpo** [comment]
👍

сб, 19 февр. 2022 г., 21:24 wire-samara ***@***.***>:
