### ISSUE TITLE
TS0201  

### ISSUE THREAD

**Issue by svilpo** [sprut/Hub#947]
Address: A4C138A525B94D15/0E0C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (TEMPERATURE_SENSOR)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 66</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_dowj6gyi</li><li>0005_ModelIdentifier: TS0201</li><li>0007_PowerSource: 3</li></ul></li><li>0001_PowerConfiguration<ul></ul></li><li>0402_TemperatureMeasurement<ul><li>0000_MeasuredValue: 2558</li><li>0001_MinMeasuredValue: 2568</li><li>0002_MaxMeasuredValue: 2585</li></ul></li><li>0003_Identify<ul></ul></li><li>0405_RelativeHumidityMeasurement<ul><li>0000_MeasuredValue: 2560</li><li>0001_MinMeasuredValue: 3136</li><li>0002_MaxMeasuredValue: 3472</li></ul></li></ul></li><li>Output<ul><li>0003_Identify<ul></ul></li><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 66</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Sun Jan 16 19:59:47 EET 2022

Telegram - @svilpo
покупал тут - https://www.aliexpress.com/item/1005002591323038.html?spm=a2g0o.9042311.0.0.27424c4dnU8fn5
Источник питания от батареи, CR2450
Режим спаривания, сброса - иголкой держать 5 секунд

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/real-time-monitoring-of-ambient-temperature
