### ISSUE TITLE
Ваттметр выключателя Aqara D1 на 3 клавиши

### ISSUE THREAD

**Issue by svsiznoi** [sprut/Hub#949]
Выключатель Aqara D1 на 3 клавиши lumi.switch.n3acn3
Ваттметр динамически не изменяет показания при включении/выключении нагрузки, а висит в одном значении которое как я заметил было взято в момент последней перезагрузки хаба. На сколько помню раньше работало корректно.

Sprut.hub 1.8.0b
Ревизия: 6412

**Comment by sprut666666** [comment]
Проверить на последней версии, отписаться в чате
