### ISSUE TITLE
сплит Haier HSU-12HTM03/R2 и Cool.stick

### ISSUE THREAD

**Issue by Skull09rus** [sprut/Hub#951]
** Подробное описание ошибки **
Ревизия: 6412
Дата сборки: 16.01.2022, 12:29:38

Сплит Haier HSU-12HTM03/R2, включение любого режима приводит к переходу в автоматический (на видео видно, это проиcходит само собой), большая задержка при переключении на выключить (видео заканчивается через секунду после отключению сплита), изменение температуры в ХК не применяется на сплите, нет звуковой индикации и смены температуры, нет возможности управления жалюз и так далее.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:

** Ожидаемое поведение **

** Скриншоты/ Логи **
[Приложите скриншоты или логи, для описания проблемы.
] https://t.me/c/1525971675/578
** Пожалуйста, заполните следующую информацию: **
  - Версия: iOS 15.2

** Дополнительные материалы **

**Comment by sprut666666** [comment]
Подобные вопросы решаются в оперативном режиме в чате технической поддержки в телеграмм "[Support] Sprut.hub"
