### ISSUE TITLE
lumi.ctrl_ln2

### ISSUE THREAD

**Issue by Dragon66ru** [sprut/Hub#953]
Address: 00158D00014A913E/E028<br><br><b>Structure</b><br><ul><li>Endpoint 1 (SMART_PLUG)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 1</li><li>0001_ApplicationVersion: 32</li><li>0002_StackVersion: 2</li><li>0003_HWVersion: 18</li><li>0004_ManufacturerName: LUMI</li><li>0005_ModelIdentifier: lumi.ctrl_ln2</li><li>0006_DateCode: 06-25-2018</li><li>0007_PowerSource: 1</li><li>FF01_ExtInfo (115F): {3=26, 100=true, 101=false, 149=110.96115112304688, 5=30, 7=10648976768, 152=35.849998474121094, 8=4128, 9=1024, 154=0}</li><li>FF22_MappingModeLeft (115F): 18</li><li>FF23_MappingModeRight (115F): 18</li><li>FFF0_Setup (115F): ByteArray [value=]</li></ul></li><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0001_PowerConfiguration<ul><li>0000_MainsVoltage: 2340</li></ul></li><li>0002_DeviceTemperatureConfiguration<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 128</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li><li>0005_LastConfiguredBy: FFFFFFFFFFFFFFFF</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>F000_Custom: 65021952</li></ul></li><li>000A_Time<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: 0000000000000000</li><li>0002_CurrentFileVersion: 32</li><li>0006_ImageUpgradeStatus: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (SMART_PLUG)<ul><li>Input<ul><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>F000_Custom: 65021952</li></ul></li></ul></li></ul></li><li>Endpoint 3 (MAINS_POWER_OUTLET)<ul><li>Input<ul><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 105.41999816894531</li><li>006F_StatusFlags: 0</li><li>0100_ApplicationType: 589824</li></ul></li></ul></li><li>Output<ul><li>0004_Groups<ul></ul></li><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 4 (METER_INTERFACE)<ul><li>Input<ul><li>000C_AnalogInputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: 110.9392318725586</li><li>006F_StatusFlags: 0</li><li>0100_ApplicationType: 720896</li></ul></li></ul></li><li>Output<ul><li>000C_AnalogInputBasic<ul></ul></li></ul></li></ul></li><li>Endpoint 5 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 2</li><li>006F_StatusFlags: 0</li></ul></li></ul></li></ul></li><li>Endpoint 6 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 1</li><li>006F_StatusFlags: 0</li></ul></li></ul></li></ul></li><li>Endpoint 7 (ON_OFF_SWITCH)<ul><li>Input<ul><li>0010_BinaryOutputBasic<ul><li>0051_OutOfService: false</li><li>0055_PresentValue: false</li><li>006F_StatusFlags: 0</li></ul></li><li>0012_MultistateInputBasic<ul><li>004A_NumberOfStates: 6</li><li>0051_OutOfService: false</li><li>0055_PresentValue: 0</li><li>006F_StatusFlags: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>000B57FFFE7E32AD</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>115</td><td>UNKNOWN</td><td>0</td></tr><tr><td>00158D000152FF4E</td><td>3115</td><td>Router</td><td>false</td><td>Sibling</td><td>75</td><td>UNKNOWN</td><td>1</td></tr><tr><td>00158D0002C41FA6</td><td>0311</td><td>Router</td><td>false</td><td>Sibling</td><td>185</td><td>UNKNOWN</td><td>1</td></tr><tr><td>00158D0003F448EF</td><td>010D</td><td>Router</td><td>false</td><td>Sibling</td><td>162</td><td>UNKNOWN</td><td>1</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>ACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>VALIDATION_UNDERWAY</td><td>3115</td><td>3115</td></tr><tr><td>ACTIVE</td><td>010D</td><td>010D</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>0311</td><td>FFFE</td></tr><tr><td>DISCOVERY_UNDERWAY</td><td>A288</td><td>FFFE</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>127</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>100</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4447</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>100</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Mon Jan 17 20:35:58 MSK 2022

Телеграмм: Dragon66ru 
Устройство в каталоге https://v2.sprut.ai/catalog/item/aqara-wall-switch-2
Покупал давно на Алиэкспресс 
Ознакомиться с инструкцией: https://wiki.sprut.ai/ru/spruthub/materials/setup-sprutstick-sniffer-to-add-new-device

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/aqara-wall-switch-2
