### ISSUE TITLE
Доработка WEB интерфейса аксессуаров

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#96]
** Максимально подробное описание предложения.**
Первое.
![image](https://user-images.githubusercontent.com/60096192/79715724-8775fe00-82e5-11ea-9d5c-363c0cc52999.png)

Закрепить данную панель, в web интерфейса, что бы при прокрутке (скролле) в низ она не участвовала в прокрутке а была всегда статична.

Второе.
![image](https://user-images.githubusercontent.com/60096192/79716121-bf317580-82e6-11ea-9f6b-0a61f3e244a7.png)
![image](https://user-images.githubusercontent.com/60096192/79716171-f011aa80-82e6-11ea-9ba9-2ea7e9bfa4d4.png)
Вынести, продублировать данные значения.

Это позволит, увеличьте скорость работы при настройке SH и совершать меньше действий. Поможет улучшить визуализацию при настройке.

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

**Comment by diamond5170** [comment]
Про инвертирование точно нет. Про меню посмотрим, но это незначительно. Концепт все равно будет меняться скоро.

**Comment by MakeSimpleOrg** [comment]
Не актуально, скоро будет новый интерфейс.
