### ISSUE TITLE
LTC011

### ISSUE THREAD

**Issue by Ser-Ry** [sprut/Hub#964]
Address: 0017880104520222/FFFE<br><br><b>Structure</b><br><ul><li>Endpoint 0 (ON_OFF_SWITCH)<ul><li>Input<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li><li>Output<ul><li>1000_TouchlinkCommissioning<ul></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Input<ul><li>0021_GreenPower<ul></ul></li></ul></li><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li><li>Endpoint 11 (POINT_OF_SALE)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 2</li><li>0003_HWVersion: 2</li><li>0004_ManufacturerName: Philips</li><li>0005_ModelIdentifier: LTC011</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 1.50.2_r30933</li><li>0040_CustomPhilips (100B): ENA_LTC011_1_CherCeiling_v1</li><li>0041_CustomPhilips (100B): 427332137</li><li>0050_CustomPhilips (100B): 1</li><li>F109_CustomPhilips (100B): true</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0300_ColorControl<ul><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 29972</li><li>0004_CurrentY: 26871</li><li>0007_ColorTemperature: 366</li><li>0008_ColorMode: 2</li><li>4001_EnhancedColorMode: 2</li></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>4000_StartUpCurrentLevel: 254</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: 001788FFF1D69C29</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 16783620</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4107</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>00124B0023B372B7</td><td>9108</td><td>End Device</td><td>true</td><td>Child</td><td>127</td><td>DISABLED</td><td>1</td></tr><tr><td>00124B0022EE4830</td><td>1BA2</td><td>End Device</td><td>true</td><td>Child</td><td>190</td><td>DISABLED</td><td>1</td></tr><tr><td>0017880104E7AFE8</td><td>6878</td><td>End Device</td><td>true</td><td>Child</td><td>129</td><td>DISABLED</td><td>1</td></tr></table><br><b>Routing table</b><br><table border=1 width=100%><tr><th>Status</th><th>Destination</th><th>Next hop</th></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr><tr><td>INACTIVE</td><td>0000</td><td>0000</td></tr></table><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>71</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>45</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4107</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>45</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[DISPOSABLE_BATTERY, MAINS, RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Tue Jan 18 21:58:58 MSK 2022

Telegram @Ser_Ry
https://v2.sprut.ai/catalog/item/philips-cher-ceiling-light

**Comment by Batyushin** [comment]
https://v2.sprut.ai/catalog/item/philips-cher-ceiling-light
