### ISSUE TITLE
Доработка WEB интерфейса контроллеры

### ISSUE THREAD

**Issue by droni4** [sprut/Hub#97]
** Максимально подробное описание предложения.**
Первое
![image](https://user-images.githubusercontent.com/60096192/79718967-72519d00-82ee-11ea-8ff5-e18d7c319a7f.png)
Закрепить данную панель, в web интерфейса, что бы при прокрутке (скролле) в низ она не участвовала в прокрутке а была всегда статична.

Второе
![image](https://user-images.githubusercontent.com/60096192/79720676-11c45f00-82f2-11ea-9340-c9be017bb064.png)
добавить в строку возможность автоматического фильтра

Третье
![image](https://user-images.githubusercontent.com/60096192/79720802-505a1980-82f2-11ea-86df-f68c5850118f.png)
добавить кнопку перезагрузки контроллера

Это позволит, увеличьте скорость работы при настройке SH и совершать меньше действий. Поможет улучшить визуализацию при настройке.

** Дополнительные материалы **
Любые внешние материалы, которые помогут в осознании вашего предложения: ссылки, скриншоты и т.д.

**Comment by MakeSimpleOrg** [comment]
Не актуально, скоро будет новый интерфейс.
