### ISSUE TITLE
SmokeSensor-EM

### ISSUE THREAD

**Issue by jorgemsccc** [sprut/Hub#972]
Address: 000D6F00118C3A49/499C<br><br><b>Structure</b><br><ul><li>Endpoint 1 (IAS_ZONE)<ul><li>Input<ul><li>0000_Basic<ul><li>0001_ApplicationVersion: 18</li><li>0003_HWVersion: 16</li><li>0004_ManufacturerName: HEIMAN</li><li>0005_ModelIdentifier: SmokeSensor-EM</li><li>0007_PowerSource: 3</li><li>4000_SWBuildID: 1.1.1</li></ul></li><li>0500_IasZone<ul><li>0010_IASCIEAddress: </li></ul></li><li>0001_PowerConfiguration<ul><li>0021_BatteryPercentageRemaining: 200</li></ul></li><li>0003_Identify<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><table border=1 width=100%><tr><th>Endpoint</th><th>Mode</th><th>Address</th><th>Cluster</th></tr><tr><td>1</td><td>IEEE</td><td>[24] Sprut zigbeeНет (1)</td><td>0500_IasZone</td></tr><tr><td>1</td><td>IEEE</td><td>[24] Sprut zigbeeНет (1)</td><td>0001_PowerConfiguration</td></tr></table><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4619</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>0</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Wed Jan 19 23:27:15 MSK 2022

TG: @Blacky
https://perenio.ru/catalog/datchik-dyma-pecss01-pecss01
На момент написания ишью каталог лежал. нашел только такую ссылку, в каталоге он есть 100% https://v2.sprut.ai/catalog?tags=Perenio
Долгое нажатие скрепкой кнопки для сброса и подключения

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/perenio-smoke-sensor
