### ISSUE TITLE
TS0012

### ISSUE THREAD

**Issue by SrgAnt** [sprut/Hub#977]
Address: A4C138999938346B/E29F<br><br><b>Structure</b><br><ul><li>Endpoint 1 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E000_ManufacturerSpecific<ul><li>D003_Custom: AAAAAgAA</li></ul></li><li>0000_Basic<ul><li>0001_ApplicationVersion: 64</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: _TZ3000_jl7qyupf</li><li>0005_ModelIdentifier: TS0012</li><li>0007_PowerSource: 3</li></ul></li><li>E001_ManufacturerSpecific<ul><li>D030_Custom: 0</li></ul></li><li>0003_Identify<ul></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>8001_IndicatorMode: 1</li><li>8002_RestartStatus: 1</li></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 64</li><li>0003_CurrentZigBeeStackVersion: 2</li><li>0004_DownloadedFileVersion: -1</li><li>0005_DownloadedZigBeeStackVersion: 65535</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4417</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li></ul></li><li>000A_Time<ul></ul></li></ul></li></ul></li><li>Endpoint 2 (ON_OFF_LIGHT)<ul><li>Input<ul><li>E001_ManufacturerSpecific<ul></ul></li><li>0004_Groups<ul></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: false</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><table border=1 width=100%><tr><th>ID</th><th>NWK</th><th>Type</th><th>Sleepy</th><th>Relation</th><th>LQI</th><th>PermitJoining</th><th>Depth</th></tr><tr><td>842E14FFFE40AA53</td><td>0000</td><td>Coordinator</td><td>false</td><td>Parent</td><td>91</td><td>UNKNOWN</td><td>0</td></tr></table><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>66</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>66</td></tr><tr><td width=35%>Logical Type</td><td>End Device</td></tr><tr><td width=35%>Mac Capabilities</td><td>[REDUCED_FUNCTION_DEVICE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4417</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>66</td></tr><tr><td width=35%>Stack Compliance</td><td>21</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_STIMULATED</td></tr><tr><td width=35%>Available Power Sources</td><td>[RECHARGABLE_BATTERY]</td></tr><tr><td width=35%>Current Power Source</td><td>RECHARGABLE_BATTERY</td></tr><tr><td width=35%>Power Level</td><td>MEDIUM</td></tr></table><br><br><br>Last update: Fri Jan 21 10:48:51 YEKT 2022
Родного хаба нет
Телеграмм: @SrgAnt
Покупался: https://aliexpress.ru/item/1005003108226482.html?_ga=2.35861352.971302464.1642754843-1173295367.1625119878&item_id=1005003108226482&sku_id=12000024133997102&spm=a2g39.orderlist.0.0.791f4aa6w3bDHD
В каталоге sprut: нет
Реле
Версия Zigbee: 3,0
Режим спаривания, сброса: удержание кнопки на корпусе 5 сек
Наличие нуля: нет
Количество каналов: 2
Энергоизмеритель: нет
Статус после восстановления питания: вкл, выкл или последнее состояние

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/2ch-zigbee-switch-module-l-1
