### ISSUE TITLE
TRADFRI bulb GU10 CWS 345lm

### ISSUE THREAD

**Issue by pabl33** [sprut/Hub#983]
Address: 2C1165FFFE955F21/6279<br><br><b>Structure</b><br><ul><li>Endpoint 1 (EXTENDED_COLOR_LIGHT)<ul><li>Input<ul><li>0000_Basic<ul><li>0000_ZCLVersion: 3</li><li>0001_ApplicationVersion: 80</li><li>0002_StackVersion: 101</li><li>0003_HWVersion: 1</li><li>0004_ManufacturerName: IKEA of Sweden</li><li>0005_ModelIdentifier: TRADFRI bulb GU10 CWS 345lm</li><li>0007_PowerSource: 1</li><li>4000_SWBuildID: 1.0.021</li></ul></li><li>0300_ColorControl<ul><li>0000_CurrentHue: 24</li><li>0001_CurrentSaturation: 201</li><li>0002_RemainingTime: 0</li><li>0003_CurrentX: 30015</li><li>0004_CurrentY: 26870</li><li>0007_ColorTemperature: 370</li><li>0008_ColorMode: 2</li><li>4000_EnhancedCurrentHue: 0</li><li>4001_EnhancedColorMode: 2</li><li>4002_ColorLoopActive: 0</li><li>4003_ColorLoopDirection: 0</li><li>4004_ColorLoopTime: 25</li><li>4005_ColorLoopStartHue: 8960</li></ul></li><li>1000_TouchlinkCommissioning<ul></ul></li><li>0003_Identify<ul><li>0000_IdentifyTime: 0</li></ul></li><li>0004_Groups<ul><li>0000_NameSupport: 0</li></ul></li><li>0005_Scenes<ul><li>0000_SceneCount: 0</li><li>0001_CurrentScene: 0</li><li>0002_CurrentGroup: 0</li><li>0003_SceneValid: false</li><li>0004_NameSupport: 0</li></ul></li><li>0B05_Diagnostics<ul><li>0108_APSRxUcast: 0</li><li>0109_APSTxUcastSuccess: 0</li><li>010A_APSTxUcastRetry: 0</li><li>010B_APSTxUcastFail: 0</li><li>010C_RouteDiscInitiated: 0</li><li>011C_LastMessageLQI: 0</li><li>011D_LastMessageRSSI: 0</li></ul></li><li>0006_OnOff<ul><li>0000_OnOff: true</li><li>4000_GlobalSceneControl: true</li><li>4001_OnTime: 0</li><li>4002_OffWaitTime: 0</li><li>4003_StartUpOnOff: 1</li></ul></li><li>0008_LevelControl<ul><li>0000_CurrentLevel: 254</li><li>0001_RemainingTime: 0</li><li>000F_Options: 0</li><li>0011_OnLevel: 255</li><li>4000_StartUpCurrentLevel: 255</li></ul></li><li>FC7C_ManufacturerSpecific<ul></ul></li></ul></li><li>Output<ul><li>0019_OtaUpgrade<ul><li>0000_UpgradeServerID: FFFFFFFFFFFFFFFF</li><li>0001_FileOffset: -1</li><li>0002_CurrentFileVersion: 268572245</li><li>0004_DownloadedFileVersion: 1</li><li>0006_ImageUpgradeStatus: 0</li><li>0007_ManufacturerID: 4476</li><li>0008_ImageTypeID: 65535</li><li>0009_MinimumBlockRequestPeriod: 0</li><li>000A_ImageStamp: 0</li></ul></li></ul></li></ul></li><li>Endpoint 242 (ZGP_PROXY_BASIC)<ul><li>Output<ul><li>0021_GreenPower<ul></ul></li></ul></li></ul></li></ul><br><br><b>Binding table</b><br><br><b>Group membership</b><br><br><b>Associated devices</b><br><br><b>Neighbor table</b><br><br><b>Routing table</b><br><br><b>Node Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Aps Flags</td><td>0</td></tr><tr><td width=35%>Frequency Bands</td><td>[FREQ_2400_MHZ]</td></tr><tr><td width=35%>Server Capabilities</td><td>[]</td></tr><tr><td width=35%>Buffer Size</td><td>82</td></tr><tr><td width=35%>Incoming Transfer Size</td><td>82</td></tr><tr><td width=35%>Logical Type</td><td>Router</td></tr><tr><td width=35%>Mac Capabilities</td><td>[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE]</td></tr><tr><td width=35%>Manufacturer Code</td><td>4476</td></tr><tr><td width=35%>Out Going Transfer Size</td><td>82</td></tr><tr><td width=35%>Stack Compliance</td><td>22</td></tr></table><br><b>Power Descriptor</b><br><table border=1 width=100%><tr><td width=35%>Current Power Mode</td><td>RECEIVER_ON_IDLE</td></tr><tr><td width=35%>Available Power Sources</td><td>[MAINS]</td></tr><tr><td width=35%>Current Power Source</td><td>MAINS</td></tr><tr><td width=35%>Power Level</td><td>FULL</td></tr></table><br><br><br>Last update: Fri Jan 21 19:44:35 MSK 2022

@nichiporenkop
в каталоге нет.
брал тут 
https://www.ikea.com/ru/ru/p/tradfri-trodfri-svetodiodnaya-lampochka-gu10-345-lm-besprovodnoe-regulirovanie-cvetnoy-i-belyy-spektr-60439234/
Версия Zigbee: 3.0
Режим спаривания, сброса: touchlink или 6 раз вкл/выкл
Тип цоколя: gu10
Статус после восстановления питания: Последнее состояние,Всегда включено,Всегда выключено.

**Comment by Batyushin** [comment]
https://sprut.ai/catalog/item/traadfri-trodfri-svetodiodnaya-lampochka-gu10-345-lm
